/* Generic public-wrapper regression. All GLSL comes from self-authored coordinate fixtures.
 * Actual Linux browser/GL evidence, never an iPhone or restricted-original performance claim. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {originalsHash,manifest} from './fixtures.mjs';
import {loadProductionFiles,patchLoaderIdentities,installRoutes,URL_ROOT} from './route-host.mjs';
const require=createRequire(import.meta.url),engine=process.env.CORAL_BROWSER||'chromium';
assert(['chromium','webkit'].includes(engine));
const {chromium,webkit}=require('playwright');
const here=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(process.env.CORAL_QA_OUT||path.join(here,'artifacts'),engine);
await mkdir(out,{recursive:true});
const report={engine,scope:'Real Linux browser with self-authored synthetic GLSL; not physical iOS, not original-artwork load or performance',viewport:{width:430,height:932,deviceScaleFactor:3},steps:[],errors:[],requests:[],blocked:[],sourceManifest:manifest,rounds:0,contextNote:'Three selected parent-document cases, max2 GL contexts. Existing tree iframe is not visited and may retain one additional context in real usage.'};
const save=()=>writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));
async function step(name,fn){const row={name,start:new Date().toISOString()};report.steps.push(row);try{row.detail=await fn();row.pass=true;}catch(e){row.pass=false;row.error=String(e.stack||e);throw e;}finally{console.log(JSON.stringify(row));await save();}}
function init(){
 const q=window.__coralQA={blockedUntil:0,attempts:[],retired:[],expected:false};
 const original=HTMLCanvasElement.prototype.getContext;
 HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2'){q.attempts.push({at:Date.now(),canvas:this.id,blocked:Date.now()<q.blockedUntil});if(Date.now()<q.blockedUntil)return null;}return original.call(this,type,...args)};
 q.state=id=>id==='rosette'?window.CoralRecoveryState:JSON.parse(document.querySelector(`[data-original="${id}"] [data-role="diagnostics"]`).textContent);
 q.canvas=(id,teacher=false)=>document.getElementById(id==='rosette'?(teacher?'teacher':'replica'):id+(teacher?'-teacher':'-canvas'));
 q.count=id=>q.state(id)?.gpuCompleted||0;
 q.pixels=id=>{const c=q.canvas(id),g=c.getContext('webgl2');if(!g||g.isContextLost())throw Error('No real GL');g.finish();const p=new Uint8Array(c.width*c.height*4);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,p);let hash=2166136261,min=255,max=0;for(let i=0;i<p.length;i+=4){for(let j=0;j<3;j++){const v=p[i+j];hash=Math.imul(hash^v,16777619);min=Math.min(min,v);max=Math.max(max,v)}}return{hash:(hash>>>0).toString(16),min,max,error:g.getError(),width:c.width,height:c.height}};
 q.hidden=hidden=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>hidden});document.dispatchEvent(new Event('visibilitychange'))};
}
let browser;
const production=await loadProductionFiles();
const candidates=patchLoaderIdentities(production.files).served;
report.sourceFiles=production.provenance;
async function context(served=candidates){const c=await browser.newContext({viewport:{width:430,height:932},deviceScaleFactor:3,hasTouch:true,isMobile:true,serviceWorkers:'block'});await installRoutes(c,served,report);await c.addInitScript(init);c.on('page',p=>{p.on('pageerror',e=>report.errors.push(String(e)));p.on('crash',()=>report.errors.push('Page crashed'));});return c;}
const state=(p,id)=>p.evaluate(id=>window.__coralQA.state(id),id);
const count=(p,id)=>p.evaluate(id=>window.__coralQA.count(id),id);
async function ready(p,id,after=-1){await p.waitForFunction(({id,after})=>{const q=window.__coralQA,s=q?.state(id);return s?.ready&&!s.error&&q.count(id)>after&&(id!=='rosette'||s.current===id)},{id,after},{timeout:30000});return state(p,id)}
async function select(p,id){await p.evaluate(id=>window.CoralRecovery.select(id),id);return ready(p,id)}
async function click(p,id,action){await p.evaluate(({id,action})=>{const el=id==='rosette'?document.getElementById(action):document.querySelector(`[data-original="${id}"] [data-action="${action}"]`);if(!el||el.disabled)throw Error('Control missing/disabled: '+action);el.click()},{id,action})}
async function pixels(p,id){const x=await p.evaluate(id=>window.__coralQA.pixels(id),id);assert.equal(x.error,0);assert(x.max-x.min>50);assert(x.width>100);return x}
async function loss(p,id,cooldown=0){return p.evaluate(({id,cooldown})=>{const q=window.__coralQA,c=q.canvas(id),gl=c.getContext('webgl2'),ext=gl.getExtension('WEBGL_lose_context');if(!ext)throw Error('Loss extension unavailable');q.retired.push(c);q.expected=true;q.blockedUntil=Date.now()+cooldown;const before=q.count(id);ext.loseContext();return {before,at:Date.now(),attempts:q.attempts.length}},{id,cooldown})}
async function settleFrames(p,id,n=14){const start=await count(p,id);await click(p,id,'play');await p.waitForFunction(({id,n})=>window.__coralQA.count(id)>=n,{id,n:start+n},{timeout:30000});await click(p,id,'play');await p.waitForTimeout(100);return count(p,id)}
try{
 browser=await({chromium,webkit}[engine]).launch({headless:true});report.browserVersion=browser.version();
 await step('Actual native GL VAO semantics and shader pixels',async()=>{const c=await context(),p=await c.newPage();await p.goto(URL_ROOT+'#view=home');const a=await p.evaluate(()=>{const c=document.createElement('canvas'),g=c.getContext('webgl2');if(!g)throw Error('WebGL2 unavailable');const v=g.createVertexArray(),before=g.isVertexArray(v);g.bindVertexArray(v);const after=g.isVertexArray(v),error=g.getError();g.getExtension('WEBGL_lose_context')?.loseContext();return{before,after,error}});assert.deepEqual(a,{before:false,after:true,error:0});await c.close();return a});
 await step('R04 baseline: after14 real frames, 2s context-provider cooldown exhausts sole250ms retry',async()=>{const map=new Map(production.files);for(const n of ['original-replay.js','webgl-lifecycle.js','runtime.js'])map.set(n,await readFile(path.join(here,'r04-baseline',n),'utf8'));const old=patchLoaderIdentities(map).served,c=await context(old),p=await c.newPage();await p.goto(URL_ROOT+'#view=transparent&originals='+originalsHash);await ready(p,'transparent');await settleFrames(p,'transparent');const first=await loss(p,'transparent',2000);await p.waitForTimeout(3500);const s=await state(p,'transparent');assert.equal(s.ready,false);assert.match(s.error,/context-create/);assert(s.gpuCompleted>=14);assert.equal(s.lastFailure.stage,'context-create');const a=await p.evaluate(n=>window.__coralQA.attempts.slice(n),first.attempts);assert.equal(a.filter(x=>x.blocked).length,1);await c.close();return {state:s,replacementAttempts:a}});
 const c=await context(),p=await c.newPage();await p.goto(URL_ROOT+'#view=transparent&originals='+originalsHash);await ready(p,'transparent');
 await step('R05 retains loss cause and recovers after2s cooldown with original pose/quality',async()=>{await settleFrames(p,'transparent');const pix=await pixels(p,'transparent'),s0=await state(p,'transparent'),first=await loss(p,'transparent',2000);await ready(p,'transparent',first.before);const s=await state(p,'transparent');assert.equal(s.playing,false);assert.equal(s.time,s0.time);assert.equal(s.quality,s0.quality);assert.equal(s.reference,s0.reference);assert.equal((await pixels(p,'transparent')).hash,pix.hash);const detail=await p.evaluate(n=>({attempts:window.__coralQA.attempts.slice(n),state:window.__coralQA.state('transparent'),gl:window.CoralGLState}),first.attempts);assert(detail.attempts.some(x=>x.blocked));assert.equal(s.firstFailure.contextLost,true);assert.notEqual(s.firstFailure.stage,'context-create');assert.equal(s.lastFailure.stage,'context-create');assert(s.failureHistory.length>=2&&s.failureHistory.length<=16);return detail});
 for(const id of ['transparent','color','rosette'])await step(`${id}: continuous real rendering for${id==='transparent'?180:60}s`,async()=>{await select(p,id);const before=await count(p,id),start=Date.now();await click(p,id,'play');let samples=[];const ms=id==='transparent'?180000:60000;while(Date.now()-start<ms){await p.waitForTimeout(5000);const s=await state(p,id);assert.equal(s.error,null);assert(s.ready);samples.push({ms:Date.now()-start,frames:s.gpuCompleted,time:s.time??s.clock,active:await p.evaluate(()=>window.CoralGLState.active)})}await click(p,id,'play');assert((await count(p,id))>before+100);if(id==='transparent')assert.equal((await state(p,id)).recovery.resetReason,'healthy-30s-30frames');return {before,after:await count(p,id),samples,pixels:await pixels(p,id)}});
 await step('20 actual case-switch and hashless-reopen rounds',async()=>{for(let n=1;n<=20;n++){for(const id of ['color','transparent','rosette']){await select(p,id);await pixels(p,id);assert.equal(await p.evaluate(()=>window.CoralGLState.active),2)}await p.goto(URL_ROOT+'#view=home');await p.evaluate(()=>window.CoralPrivateSources.ready);for(const id of ['color','transparent','rosette']){await select(p,id);await pixels(p,id)}report.rounds=n;await save()}return{rounds:report.rounds,gl:await p.evaluate(()=>window.CoralGLState)}});
 for(const id of ['transparent','color','rosette'])await step(`${id}: live loss after healthy session and lifecycle interruptions`,async()=>{await select(p,id);const a=await pixels(p,id),f=await loss(p,id,1000);await ready(p,id,f.before);assert.equal((await pixels(p,id)).hash,a.hash);for(const type of ['visibility','pagehide']){if(type==='visibility')await p.evaluate(()=>window.__coralQA.hidden(true));else await p.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));assert.equal(await p.evaluate(()=>window.CoralGLState.active),0);if(type==='visibility')await p.evaluate(()=>window.__coralQA.hidden(false));else await p.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await ready(p,id);assert.equal((await pixels(p,id)).hash,a.hash)}return{pixels:a,state:await state(p,id),eventScope:'Visibility/BFCache DOM events injected, not actual OS backgrounding'}});
 await step('Permanent null context stops after3 automatic attempts; manual retry works',async()=>{await select(p,'transparent');const f=await loss(p,'transparent',60000);await p.waitForTimeout(12500);const s=await state(p,'transparent');assert.equal(s.ready,false);const a=await p.evaluate(n=>window.__coralQA.attempts.slice(n),f.attempts);assert.equal(a.filter(x=>x.blocked).length,3);await p.waitForTimeout(3000);assert.equal(await p.evaluate(n=>window.__coralQA.attempts.slice(n).filter(x=>x.blocked).length,f.attempts),3);await p.evaluate(()=>{window.__coralQA.blockedUntil=0});await click(p,'transparent','retry');await ready(p,'transparent',f.before);return{automaticAttempts:a,state:await state(p,'transparent')}});
 await step('Exhausted recovery budget receives a fresh bounded budget after pageshow without visibilitychange',async()=>{await select(p,'transparent');const f=await loss(p,'transparent',60000);await p.waitForTimeout(12500);assert.equal((await state(p,'transparent')).ready,false);const n=await p.evaluate(()=>window.__coralQA.attempts.length);await p.evaluate(()=>{window.__coralQA.blockedUntil=Date.now()+2000;window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))});await ready(p,'transparent',f.before);const after=await p.evaluate(n=>({attempts:window.__coralQA.attempts.slice(n),state:window.__coralQA.state('transparent')}),n);assert(after.attempts.filter(x=>x.blocked).length>=2);assert.equal(after.state.recovery.resetReason,'pageshow');return after});
 await step('Stale retired loss event cannot cancel or disturb replacement',async()=>{const s=await state(p,'transparent');const x=await p.evaluate(()=>{const c=window.__coralQA.retired.at(-1);const e=new WebGLContextEvent('webglcontextlost',{cancelable:true});c.dispatchEvent(e);return{defaultPrevented:e.defaultPrevented,state:window.__coralQA.state('transparent')}});assert.equal(x.defaultPrevented,false);assert.equal(x.state.contextGeneration,s.contextGeneration);assert(x.state.ready);return x});
 await p.screenshot({path:path.join(out,'synthetic-mobile.png')});await c.close();
 await step('Fresh browser context without private cache shows source-needed state and zero GL contexts',async()=>{const z=await context(),q=await z.newPage();await q.goto(URL_ROOT+'#view=transparent');await q.evaluate(()=>window.CoralPrivateSources.ready);assert.equal(await q.evaluate(()=>window.CoralGLState.active),0);assert.equal((await state(q,'transparent')).ready,false);await z.close();return true});
 assert.equal(report.errors.length,0);assert.equal(report.blocked.length,0);report.passed=true;
}catch(e){report.passed=false;report.failure=String(e.stack||e);process.exitCode=1;console.error(report.failure)}finally{await browser?.close();report.finishedAt=new Date().toISOString();await save();console.log(JSON.stringify({engine,browserVersion:report.browserVersion,passed:report.passed,rounds:report.rounds,failure:report.failure||null}))}
