'use strict';
/* Isolated CI browser verification, not a physical-GPU/device certification. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),https=require('node:https'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const html=path.resolve(process.env.HAIYU_HTML||'kaopu-haiyu-workbench/r23/index.html');
const url=process.env.HAIYU_PUBLIC_URL||'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/r23/';
const out=path.resolve(process.env.HAIYU_QA_OUT||'haiyu-r23-browser-results');fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),expected=hash(fs.readFileSync(html));
const report={commit:process.env.GITHUB_SHA,expectedSha256:expected,source:'Official Playwright Chromium with SwiftShader software WebGL',physicalGPU:false,physicalMobileDevice:false,checks:[],errors:[],public:{},file:{}};
const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
function get(u){return new Promise((resolve,reject)=>{const req=https.get(u,r=>{let b=[];r.on('data',c=>b.push(c));r.on('end',()=>resolve({status:r.statusCode,body:Buffer.concat(b)}))});req.setTimeout(45000,()=>req.destroy(Error('HTTP timeout')));req.on('error',reject)})}
async function seek(p,frame){const count=Number(await p.locator('#axisLift').getAttribute('data-render-count'));await p.locator('#liftTime').fill(String(frame));await p.waitForFunction(({frame,count})=>Number(document.querySelector('#axisLift').dataset.renderCount)>count&&Math.abs(Number(document.querySelector('#axisLift').dataset.time)-frame*Math.PI/30)<1e-6,{frame,count})}
async function canvasHash(p){return p.locator('#liftCanvas').evaluate(c=>c.toDataURL('image/png')) .then(hash)}
async function pixelProbe(p){return p.locator('#liftCanvas').evaluate(c=>{const gl=c.getContext('webgl')||c.getContext('experimental-webgl');if(!gl)return {webgl:false};const b=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,b);let visible=0;for(let i=0;i<b.length;i+=4)if(b[i]+b[i+1]+b[i+2]>120)visible++;const ext=gl.getExtension('WEBGL_debug_renderer_info');return {webgl:true,depthTest:gl.isEnabled(gl.DEPTH_TEST),glError:gl.getError(),visiblePixels:visible,width:c.width,height:c.height,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'not-exposed'};})}
async function depthFixture(p){return p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;const r=window.HaiyuDepthRenderer.create(c);if(!r)throw Error('No fixture WebGL');const positions=[[10,10,-5],[54,10,-5],[32,56,-5],[10,10,5],[54,10,5],[32,56,5]];const options={project:p=>p,shade:(n,k)=>k==='front'?'#ff0000':'#0000ff',showSurface:true,showSpine:false,showSections:false,neutral:false};function draw(reverse){const faces=reverse?[[3,4,5],[0,1,2]]:[[0,1,2],[3,4,5]],faceKinds=reverse?['front','back']:['back','front'];r.draw({positions,faces,faceKinds,lines:[],spine:[],sections:[]},options);const b=new Uint8Array(4);r.gl.readPixels(32,32,1,1,r.gl.RGBA,r.gl.UNSIGNED_BYTE,b);return [...b]}return {normal:draw(false),reversed:draw(true),error:r.gl.getError()};})}
(async()=>{let browser;try{
 const deadline=Date.now()+12*60*1000;let response;while(Date.now()<deadline){response=await get(url);if(response.status===200&&hash(response.body)===expected)break;console.log('Waiting for Pages exact bytes',response.status,hash(response.body));await new Promise(r=>setTimeout(r,15000))}assert.equal(response.status,200);assert.equal(hash(response.body),expected);report.public={url,status:response.status,bytes:response.body.length,sha256:hash(response.body)};save();
 browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 for(const phase of ['file','public']){
  const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});const p=await context.newPage();const errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.text()))errors.push(m.text())});p.on('request',r=>requests.push(r.url()));
  await p.goto(phase==='file'?'file://'+html:url,{waitUntil:'load'});await p.waitForFunction(()=>document.body.dataset.stage==='5'&&document.body.dataset.pending==='0');assert.equal(await p.getByRole('navigation',{name:'二维原式',exact:true}).count(),1);
  const baseline=await context.newPage();baseline.on('pageerror',e=>errors.push(e.message));const baselineURL=phase==='file'?'file://'+path.resolve('kaopu-haiyu-workbench/baselines/r18/index.html'):'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/baselines/r18/';await baseline.goto(baselineURL+'?stage=4',{waitUntil:'load'});await baseline.waitForFunction(()=>document.body.dataset.pending==='0');
  report[phase].original04and05=[];for(const sourceStage of [4,5]){await p.locator(`button[data-stage="${sourceStage}"]`).click();await baseline.locator(`button[data-stage="${sourceStage}"]`).click();await p.waitForFunction(()=>document.body.dataset.pending==='0');await baseline.waitForFunction(()=>document.body.dataset.pending==='0');const rows=[];for(const frame of [1,60,120,240]){for(const page of [p,baseline]){await page.locator('#timeline').fill(String(frame));await page.waitForFunction(frame=>document.body.dataset.pending==='0'&&Number(document.body.dataset.frame)===frame,frame);}const a=hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL())),b=hash(await baseline.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL()));assert.equal(a,b);rows.push({frame,sha256:a,exactR18PixelMatch:true});}await p.frameLocator('#live').locator('canvas').screenshot({path:path.join(out,`${phase}-original${sourceStage}-frame240.png`)});report[phase].original04and05.push({stage:sourceStage,frames:rows});}
  await baseline.close();await p.screenshot({path:path.join(out,`${phase}-original05-navigation.png`),fullPage:true});await p.locator('button[data-stage="10"]').click();await p.waitForFunction(()=>document.querySelector('#axisLift')?.dataset.renderCount>0);

  assert.equal(await p.locator('meta[name="haiyu-build"]').getAttribute('content'),'R23-compact-teacher-study-20261004');
  const probe=await pixelProbe(p);assert.equal(probe.webgl,true);assert.equal(probe.depthTest,true);assert.equal(probe.glError,0);assert.ok(probe.visiblePixels>1000);report[phase].pixelProbe=probe;
  const depth=await depthFixture(p);assert.deepEqual(depth.normal,[255,0,0,255]);assert.deepEqual(depth.reversed,depth.normal);assert.equal(depth.error,0);report[phase].depthOrderFixture=depth;
  for(const stage of [10,11]){
   await p.locator(`button[data-stage="${stage}"]`).click();await seek(p,0);const frames=[];for(const frame of [0,15,30,45]){await seek(p,frame);frames.push(await canvasHash(p));await p.locator('#liftCanvas').screenshot({path:path.join(out,`${phase}-stage${stage}-frame${frame}.png`)})}assert.ok(new Set(frames).size>=3);
   await p.locator('#liftMotion').fill('0');await seek(p,0);const frozen=await canvasHash(p);await seek(p,30);assert.equal(await canvasHash(p),frozen);await p.locator('#liftMotion').fill('100');
   await seek(p,0);await p.locator('#liftTop').screenshot({path:path.join(out,`${phase}-stage${stage}-axial-section.png`)});const sectionBefore=await p.locator('#liftTop').evaluate(c=>c.toDataURL());await p.locator('#liftSectionPosition').fill('60');await p.waitForTimeout(250);assert.notEqual(await p.locator('#liftTop').evaluate(c=>c.toDataURL()),sectionBefore);await p.locator('#liftSectionPosition').fill('42');await p.waitForTimeout(250);assert.equal(await p.locator('#liftSurface').count(),0);const before=await canvasHash(p),box=await p.locator('#liftCanvas').boundingBox();await p.mouse.move(box.x+box.width*.45,box.y+box.height*.4);await p.mouse.down();await p.mouse.move(box.x+box.width*.67,box.y+box.height*.48,{steps:12});await p.mouse.up();await p.waitForTimeout(250);assert.notEqual(await canvasHash(p),before);await p.locator('#liftCanvas').screenshot({path:path.join(out,`${phase}-stage${stage}-rotated.png`)});await p.locator('#liftView').click();
   const t0=Number(await p.locator('#axisLift').getAttribute('data-time'));await p.locator('#liftPlay').click();await p.waitForTimeout(1000);await p.locator('#liftPlay').click();const t1=Number(await p.locator('#axisLift').getAttribute('data-time'));assert.ok(t1>t0);const stopped=await canvasHash(p);await p.waitForTimeout(300);assert.equal(await canvasHash(p),stopped);
   report.checks.push({phase,stage,frameHashes:frames,motionFreeze:true,cameraRotation:true,playPause:true,renderer:(await p.locator('#axisLift').getAttribute('data-renderer')),renderMs:Number(await p.locator('#axisLift').getAttribute('data-render-ms'))});
  }
  for(const stage of [1,7,8,10]){await p.locator(`button[data-stage="${stage}"]`).click();if(stage===1)await p.frameLocator('#live').locator('canvas').waitFor();else await p.locator(stage===10?'#axisLift':'#experiment').waitFor({state:'visible'})}
  assert.equal(await p.locator('button[data-stage="6"]').count(),0);
  await p.locator('button[data-stage="9"]').click();await p.frameLocator('#live').locator('canvas').waitFor();await p.waitForFunction(()=>document.body.dataset.pending==='0');
  assert.equal(await p.locator('#title').textContent(),'06 新加入原式 · 10月4日');assert.equal(await p.locator('#sourceVersion').textContent(),'新原式 / 2026.10.04');
  const originalFrames=[];for(const f of [1,60,120,180]){await p.locator('#timeline').fill(String(f));await p.waitForFunction(f=>document.body.dataset.pending==='0'&&Number(document.body.dataset.frame)===f,f);const time=Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'));assert.ok(Math.abs(time-f*Math.PI/120)<1e-10);const c=p.frameLocator('#live').locator('canvas');assert.equal(await c.getAttribute('width'),'400');assert.equal(await c.getAttribute('height'),'400');originalFrames.push(hash(await c.evaluate(c=>c.toDataURL())));await c.screenshot({path:path.join(out,`${phase}-source06-frame${f}.png`)});}
  assert.equal(new Set(originalFrames).size,4);report[phase].source06={sourceFrameStep:'PI/120',pointCount:20000,canvas:[400,400],frameHashes:originalFrames};
  await p.locator('button[data-stage="10"]').click();await seek(p,0);
const lit=await canvasHash(p);await p.locator('#liftLight').click();await p.waitForTimeout(100);assert.notEqual(await canvasHash(p),lit);await p.locator('#liftLight').click();await p.waitForTimeout(100);assert.equal(await canvasHash(p),lit);
  await p.setViewportSize({width:390,height:844});await p.locator('button[data-stage="11"]').click();await seek(p,15);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2));await p.screenshot({path:path.join(out,`${phase}-mobile-390x844.png`),fullPage:true});assert.equal((await pixelProbe(p)).webgl,true);report[phase].mobileViewport=true;
  const base=phase==='file'?'file://'+html:url;await p.goto(base+'?stage=4&frame=120',{waitUntil:'load'});await p.waitForFunction(()=>document.body.dataset.stage==='4'&&document.body.dataset.pending==='0'&&document.body.dataset.frame==='120');assert.ok(Math.abs(Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'))-4*Math.PI)<1e-9);await p.goto(base+'?module=thorax04&frame=120',{waitUntil:'load'});await p.waitForFunction(()=>Math.abs(Number(document.querySelector('#axisLift')?.dataset.time)-4*Math.PI)<1e-7);assert.equal(await p.locator('button[data-stage="10"]').getAttribute('aria-pressed'),'true');await p.goto(base+'?module=source06&frame=60',{waitUntil:'load'});await p.waitForFunction(()=>document.body.dataset.stage==='9'&&document.body.dataset.pending==='0'&&document.body.dataset.frame==='60');assert.ok(Math.abs(Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'))-Math.PI/2)<1e-10);report[phase].deepLinks={restoredOriginalStage4Frame120:true,separateThorax04Frame120:true,newSource06Frame60:true};

  // Compact layout keeps 04/05/06 source entries in the first phone screen.
  for(const n of [4,5,9]) assert.equal(await p.getByRole('navigation',{name:'二维原式',exact:true}).locator(`button[data-stage="${n}"]`).count(),1);
  await p.setViewportSize({width:390,height:844});await p.locator('button[data-stage="9"]').click();await p.waitForFunction(()=>document.body.dataset.pending==='0');await p.evaluate(()=>window.scrollTo(0,0));
  const compact=await p.locator('#live').boundingBox();assert.ok(compact.y<240,JSON.stringify(compact));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));report[phase].compactCanvasTop=compact.y;await p.screenshot({path:path.join(out,`${phase}-compact-phone-source06.png`)});
  await p.setViewportSize({width:1440,height:1000});
  await p.locator('button[data-stage="12"]').click();await p.waitForFunction(()=>document.body.dataset.pending==='0');assert.equal(await p.locator('#timeline').getAttribute('max'),'960');const seven=[];for(const f of [1,240,480,960]){await p.locator('#timeline').fill(String(f));await p.waitForFunction(f=>document.body.dataset.pending==='0'&&Number(document.body.dataset.frame)===f,f);assert.ok(Math.abs(Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'))-f*Math.PI/480)<1e-10);seven.push(hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL())));await p.frameLocator('#live').locator('canvas').screenshot({path:path.join(out,`${phase}-source07-frame${f}.png`)})}assert.equal(new Set(seven).size,4);report[phase].source07={frames:[1,240,480,960],hashes:seven};
  for(const n of [7,8]){await p.locator(`button[data-stage="${n}"]`).click();await p.locator('#expLight').waitFor({state:'visible'});await p.waitForTimeout(400);const c=p.locator('#expCanvas'),lit=hash(await c.evaluate(c=>c.toDataURL()));await p.locator('#expLight').click();await p.waitForTimeout(300);const neutral=hash(await c.evaluate(c=>c.toDataURL()));assert.notEqual(lit,neutral);await p.locator('#expLight').click();await p.waitForTimeout(300);assert.equal(hash(await c.evaluate(c=>c.toDataURL())),lit);await c.screenshot({path:path.join(out,`${phase}-legacy${n}-warm-cool.png`)});const box=await c.boundingBox();await p.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await p.mouse.down();await p.mouse.move(box.x+box.width*.62,box.y+box.height*.49,{steps:10});await p.mouse.up();await p.waitForTimeout(300);assert.notEqual(hash(await c.evaluate(c=>c.toDataURL())),lit);report.checks.push({phase,stage:n,warmCoolActualPixels:true,rotationActualPixels:true})}
  await p.locator('button[data-stage="13"]').click();await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame);await p.locator('#phaseTime').fill('120');await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame==='120'&&document.querySelector('#sourceSpace').dataset.frame==='120');const cloud=p.locator('#phaseCanvas');assert.equal(await p.locator('#sourceSpace').getAttribute('data-renderer'),'WebGL');assert.equal(await p.locator('#sourceSpace').getAttribute('data-depth-test'),'true');assert.equal(await p.locator('#sourceSpace').getAttribute('data-gl-error'),'0');assert.ok(Number(await p.locator('#sourceSpace').getAttribute('data-depth-span'))>50);
  await cloud.screenshot({path:path.join(out,`${phase}-source06-space-orbit.png`)});const warmCloud=hash(await cloud.evaluate(c=>c.toDataURL()));await p.locator('#phaseLight').click();await p.waitForTimeout(100);assert.notEqual(hash(await cloud.evaluate(c=>c.toDataURL())),warmCloud);await cloud.screenshot({path:path.join(out,`${phase}-source06-space-neutral.png`)});await p.locator('#phaseLight').click();await p.waitForTimeout(100);assert.equal(hash(await cloud.evaluate(c=>c.toDataURL())),warmCloud);await p.locator('#phaseView').click();await p.waitForTimeout(100);assert.notEqual(hash(await cloud.evaluate(c=>c.toDataURL())),warmCloud);await cloud.screenshot({path:path.join(out,`${phase}-source06-space-top.png`)});
  const referenceHash=hash(await p.frameLocator('#phaseReference').locator('canvas').evaluate(c=>c.toDataURL()));await p.locator('button[data-stage="9"]').click();await p.locator('#timeline').fill('120');await p.waitForFunction(()=>document.body.dataset.pending==='0'&&document.body.dataset.frame==='120');assert.equal(hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL())),referenceHash);await p.locator('button[data-stage="13"]').click();await p.waitForTimeout(100);const xyz=await p.evaluate(()=>window.HaiyuSourceSpace.evaluate(120));const cloudBox=await cloud.boundingBox();await p.mouse.move(cloudBox.x+100,cloudBox.y+100);await p.mouse.down();await p.mouse.move(cloudBox.x+210,cloudBox.y+145,{steps:8});await p.mouse.up();await p.waitForTimeout(200);assert.deepEqual(await p.evaluate(()=>window.HaiyuSourceSpace.evaluate(120)),xyz);await p.locator('#phasePlay').click();await p.waitForTimeout(800);await p.locator('#phasePlay').click();const stoppedCloud=hash(await cloud.evaluate(c=>c.toDataURL()));await p.waitForTimeout(200);assert.equal(hash(await cloud.evaluate(c=>c.toDataURL())),stoppedCloud);
  await p.locator('#phaseTime').fill('120');await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame==='120');await p.setViewportSize({width:390,height:844});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:path.join(out,`${phase}-compact-phone-source06-space.png`)});assert.ok((await cloud.boundingBox()).y<300);await p.setViewportSize({width:1440,height:1000});report[phase].source06space={depth:true,referenceExactPixels:true,lightsActualPixels:true,rotationCameraIndependent:true,playPause:true};

  if(phase==='file'){const external=requests.filter(u=>/^https?:/.test(u));assert.deepEqual(external,[]);report.file.externalCoreRequests=external}
  assert.deepEqual(errors,[]);report[phase].pageErrors=errors;await context.close();save();
 }
 report.status='PASS';report.scope='Compact phone/desktop navigation, additive source07, source06 quadrature with exact reference pixels and warm/cool lighting across 3D; original04/05 exact R18 pixel matches at four frames, additive skeleton10/11 and new06 visible, actual WebGL depth and mesh section, exact public/standalone bytes; not physical GPU/device or final morphology acceptance';save();console.log(JSON.stringify(report,null,2));
}catch(e){report.status='FAIL';report.errors.push(e.stack||String(e));save();console.error(e);process.exitCode=1}finally{if(browser)await browser.close()}})();
