import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import proj4 from 'https://cdn.jsdelivr.net/npm/proj4@2.11.0/+esm';

proj4.defs('EPSG:32649','+proj=utm +zone=49 +datum=WGS84 +units=m +no_defs +type=crs');

const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
const isMobile=matchMedia('(max-width: 880px)').matches||/Android|iPhone|iPad/i.test(navigator.userAgent);
const state={map:'colour',view:params.get('view')||'overview',truthOnly:false,wire:false,ready:false,interacting:false,needsRender:true,terrain:null,water:null,report:null,enhancedY:null,truthY:null,colours:{},focuses:null,restPixelRatio:Math.min(devicePixelRatio,isMobile?1.15:1.55),interactionPixelRatio:Math.min(1,devicePixelRatio)};
const canvas=$('terrain');
const renderer=new THREE.WebGLRenderer({canvas,antialias:!isMobile,alpha:false,powerPreference:'high-performance',precision:'highp'});
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.04;
renderer.setPixelRatio(state.restPixelRatio);
renderer.setSize(innerWidth,innerHeight,false);
const gl=renderer.getContext();
$('backend').textContent=gl instanceof WebGL2RenderingContext?'WebGL2':'WebGL1';

const scene=new THREE.Scene();
scene.background=new THREE.Color(0xcbd5d1);
scene.fog=new THREE.FogExp2(0xcbd5d1,isMobile?.000075:.000058);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,1,90000);
const controls=new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=25;controls.maxDistance=42000;controls.maxPolarAngle=Math.PI*.495;
scene.add(new THREE.HemisphereLight(0xe7efea,0x35442f,1.12));
const sun=new THREE.DirectionalLight(0xffefd0,2.35);sun.position.set(-6200,8700,4800);scene.add(sun);
const fill=new THREE.DirectionalLight(0xaecbd2,.34);fill.position.set(5200,2800,-4200);scene.add(fill);

function setLoading(value,label){$('loadingProgress').value=value;if(label)$('loadingDetail').textContent=label}
function setStatus(text){$('status').textContent=text}
function deepFindStrings(value,predicate,out=[]){if(typeof value==='string'&&predicate(value))out.push(value);else if(Array.isArray(value))for(const v of value)deepFindStrings(v,predicate,out);else if(value&&typeof value==='object')for(const v of Object.values(value))deepFindStrings(v,predicate,out);return out}
function deepFindValue(value,keyPattern){if(!value||typeof value!=='object')return undefined;for(const [key,v] of Object.entries(value)){if(keyPattern.test(key)&&v!==null&&v!==undefined)return v;if(v&&typeof v==='object'){const found=deepFindValue(v,keyPattern);if(found!==undefined)return found}}}
function resolveRelative(path){if(!path)return null;if(/^https?:/.test(path))return path;return new URL(path.replace(/^\.\//,''),new URL('./data/',location.href)).href}
async function fetchJson(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url} HTTP ${response.status}`);return response.json()}
async function firstJson(urls){let last;for(const url of urls){try{return{url,data:await fetchJson(url)}}catch(error){last=error}}throw last||new Error('未找到 JSON')}
async function firstBuffer(urls){let last;for(const url of urls){try{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url} HTTP ${response.status}`);return{url,buffer:await response.arrayBuffer()}}catch(error){last=error}}throw last||new Error('未找到二进制高程')}
function findBounds(...objects){for(const object of objects){const candidates=[];(function walk(v,key=''){if(Array.isArray(v)&&v.length===4&&v.every(Number.isFinite)){if(Math.max(...v.map(Math.abs))>10000)candidates.push(v.map(Number))}else if(v&&typeof v==='object')for(const [k,q] of Object.entries(v))walk(q,k)})(object);for(const b of candidates){const [a,c,d,e]=b;if(d>a&&e>c)return b}}return[437312.5,2742887.5,462912.5,2768487.5]}
function findSha(...objects){for(const object of objects){const strings=deepFindStrings(object,s=>/^[0-9a-f]{64}$/i.test(s));if(strings.length)return strings[0].toLowerCase()}return'9490b1bd34f67336352cf448729f763ae4e241637d821961efd0290e29d6c9d4'}
function normalizeSource(index,manifest,buffer){const bytes=buffer.byteLength,widthCandidate=Number(deepFindValue(manifest,/^(width|cols|columns|gridWidth)$/i)||deepFindValue(index,/^(width|cols|columns|gridWidth)$/i)),heightCandidate=Number(deepFindValue(manifest,/^(height|rows|gridHeight)$/i)||deepFindValue(index,/^(height|rows|gridHeight)$/i));let width=Number.isFinite(widthCandidate)&&widthCandidate>0?widthCandidate:Math.round(Math.sqrt(bytes/2)),height=Number.isFinite(heightCandidate)&&heightCandidate>0?heightCandidate:Math.round(bytes/2/width);if(width*height*2!==bytes){width=2048;height=2048;if(width*height*2!==bytes)throw new Error(`高程字节数 ${bytes} 与网格不匹配`)}const scale=Number(deepFindValue(manifest,/^(scale_m|heightScale|scale)$/i)||1),offset=Number(deepFindValue(manifest,/^(offset_m|heightOffset|offset)$/i)||0),nodataRaw=deepFindValue(manifest,/nodata/i),nodata=Number.isFinite(Number(nodataRaw))?Number(nodataRaw):-32768,bounds=findBounds(manifest,index);return{width,height,scale,offset,nodata,bounds}}
async function loadTruth(){setLoading(4,'定位候选 D 原生高程');let index={};try{index=(await firstJson(['./data/index.json','./data/candidates.json','./data/manifest.json'])).data}catch{}const manifestPaths=deepFindStrings(index,s=>/\.(json)$/i.test(s)&&/(manifest|meta|candidate)/i.test(s)).map(resolveRelative);const manifestResult=await firstJson([...manifestPaths,'./data/D/manifest.json','./data/D/meta.json','./data/candidate-D/manifest.json','./data/candidate_d/manifest.json','./data/D.json','./data/manifest-D.json']);const manifest=manifestResult.data;const heightPaths=deepFindStrings({index,manifest},s=>/\.(bin|raw)$/i.test(s)&&/(height|elevation)/i.test(s)).map(resolveRelative);const height=await firstBuffer([...heightPaths,'./data/D/height_i16.bin','./data/candidate-D/height_i16.bin','./data/candidate_d/height_i16.bin','./data/height_D_i16.bin']);const source=normalizeSource(index,manifest,height.buffer);return{index,manifest,heightBuffer:height.buffer,truthSha256:findSha(manifest,index),...source}}
function lineLength(line){let total=0;for(let i=1;i<line.length;i++)total+=Math.hypot(line[i].x-line[i-1].x,line[i].y-line[i-1].y);return total}
function bboxIntersects(line,bounds,margin=2500){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of line){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}return maxX>=bounds[0]-margin&&minX<=bounds[2]+margin&&maxY>=bounds[1]-margin&&minY<=bounds[3]+margin}
function projectCoordinate(c){if(Math.abs(c[0])<=180&&Math.abs(c[1])<=90){const [x,y]=proj4('EPSG:4326','EPSG:32649',c);return{x,y}}return{x:Number(c[0]),y:Number(c[1])}}
function extractLines(geojson,bounds){const lines=[];for(const feature of geojson.features||[]){const g=feature.geometry;if(!g)continue;const groups=g.type==='LineString'?[g.coordinates]:g.type==='MultiLineString'?g.coordinates:[];for(const coords of groups){const line=coords.map(projectCoordinate).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));if(line.length>1&&bboxIntersects(line,bounds))lines.push(line)}}return lines}
function endpointDistance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mergeLines(lines,threshold=48){const pool=lines.map(line=>[...line]);let changed=true,guard=0;while(changed&&guard++<5000){changed=false;outer:for(let i=0;i<pool.length;i++)for(let j=i+1;j<pool.length;j++){const a=pool[i],b=pool[j],options=[['ee',endpointDistance(a[a.length-1],b[b.length-1])],['es',endpointDistance(a[a.length-1],b[0])],['se',endpointDistance(a[0],b[b.length-1])],['ss',endpointDistance(a[0],b[0])]].sort((x,y)=>x[1]-y[1]);if(options[0][1]>threshold)continue;const type=options[0][0];let merged;if(type==='es')merged=[...a,...b.slice(1)];else if(type==='ee')merged=[...a,...b.slice(0,-1).reverse()];else if(type==='se')merged=[...b,...a.slice(1)];else merged=[...a.reverse(),...b.slice(1)];pool[i]=merged;pool.splice(j,1);changed=true;break outer}}return pool}
function pointSegmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return endpointDistance(p,a);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l2));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
function simplifyRDP(points,tolerance=6){if(points.length<3)return points;let max=0,index=0;for(let i=1;i<points.length-1;i++){const d=pointSegmentDistance(points[i],points[0],points[points.length-1]);if(d>max){max=d;index=i}}if(max>tolerance){const left=simplifyRDP(points.slice(0,index+1),tolerance),right=simplifyRDP(points.slice(index),tolerance);return[...left.slice(0,-1),...right]}return[points[0],points[points.length-1]]}
async function loadRiver(bounds){setLoading(10,'读取真实漓江中心线');const result=await firstJson(['./data/lijiang_osm.geojson','./data/river.geojson','./data/waterways.geojson']);const lines=extractLines(result.data,bounds);if(!lines.length)throw new Error('候选范围内没有可用真实河线');const merged=mergeLines(lines).sort((a,b)=>lineLength(b)-lineLength(a));return simplifyRDP(merged[0],7)}
function createTerrain(result){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(result.positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(result.colour,3));geometry.setIndex(new THREE.BufferAttribute(result.triangles,1));geometry.computeVertexNormals();geometry.computeBoundingSphere();const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.94,metalness:0,side:THREE.DoubleSide});material.dithering=true;const mesh=new THREE.Mesh(geometry,material);mesh.name='landscape-mother-continuous-terrain';mesh.frustumCulled=true;scene.add(mesh);state.terrain=mesh;state.enhancedY=new Float32Array(result.positions.length/3);for(let i=0;i<state.enhancedY.length;i++)state.enhancedY[i]=result.positions[i*3+1];state.truthY=result.truthY;state.colours={colour:result.colour,slope:result.slopeColour,rock:result.rockColour,wetness:result.wetColour};return mesh}
function createWater(sections){if(!sections?.length)return null;const cols=9,positions=new Float32Array(sections.length*cols*3),colours=new Float32Array(sections.length*cols*3),indices=new Uint32Array((sections.length-1)*(cols-1)*6);let p=0;for(const section of sections){for(let j=0;j<cols;j++){const q=j/(cols-1)*2-1,x=section.localX+section.nx*section.width*.5*q,z=section.localZ-section.ny*section.width*.5*q,edge=Math.abs(q),h=section.localY+.065+.025*Math.sin(section.s*.018+q*4.8);positions[p]=x;positions[p+1]=h;positions[p+2]=z;const deep=new THREE.Color(0x285f68),mid=new THREE.Color(0x3f7c7a),light=new THREE.Color(0x77a398),c=deep.clone().lerp(mid,Math.min(1,edge*1.15)).lerp(light,Math.max(0,(edge-.72)/.28)*.55);colours[p]=c.r;colours[p+1]=c.g;colours[p+2]=c.b;p+=3}}let k=0;for(let i=0;i<sections.length-1;i++)for(let j=0;j<cols-1;j++){const a=i*cols+j,b=a+1,c=a+cols,d=c+1;indices[k++]=a;indices[k++]=c;indices[k++]=b;indices[k++]=b;indices[k++]=c;indices[k++]=d}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(colours,3));geometry.setIndex(new THREE.BufferAttribute(indices,1));geometry.computeVertexNormals();const material=new THREE.MeshPhysicalMaterial({vertexColors:true,roughness:.24,metalness:0,transparent:true,opacity:.86,depthWrite:false,clearcoat:.52,clearcoatRoughness:.22,ior:1.333,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geometry,material);mesh.name='global-continuous-lijiang-water';mesh.renderOrder=5;scene.add(mesh);state.water=mesh;return mesh}
function applyMap(type){state.map=type;document.querySelectorAll('[data-map]').forEach(b=>b.classList.toggle('active',b.dataset.map===type));if(!state.terrain)return;const source=state.colours[type]||state.colours.colour;state.terrain.geometry.setAttribute('color',new THREE.BufferAttribute(source,3));state.terrain.geometry.attributes.color.needsUpdate=true;state.needsRender=true}
function applyTruthMode(enabled){state.truthOnly=enabled;$('truthToggle').classList.toggle('active',enabled);$('truthToggle').textContent=enabled?'恢复候选':'只看真值';if(!state.terrain)return;const position=state.terrain.geometry.attributes.position,source=enabled?state.truthY:state.enhancedY;for(let i=0;i<position.count;i++)position.setY(i,source[i]);position.needsUpdate=true;state.terrain.geometry.computeVertexNormals();state.terrain.geometry.attributes.normal.needsUpdate=true;if(state.water)state.water.visible=!enabled;state.needsRender=true}
function cameraFor(view){if(!state.focuses)return;state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const f=state.focuses,extent=state.report?.workingGrid?state.report.gridSpacingMeters*(state.report.workingGrid-1):25600;if(view==='overview'){camera.position.set(extent*.43,extent*.19,extent*.52);controls.target.set(0,260,-extent*.08);camera.fov=40}else if(view==='river'){camera.position.set(f.river.x+1250,f.river.y+540,f.river.z+1550);controls.target.set(f.river.x,f.river.y+12,f.river.z-120);camera.fov=43}else if(view==='paddy'){camera.position.set(f.paddy.x+540,f.paddy.y+860,f.paddy.z+680);controls.target.set(f.paddy.x,f.paddy.y+4,f.paddy.z);camera.fov=39}else{camera.position.set(f.peak.x+420,f.peak.y+260,f.peak.z+510);controls.target.set(f.peak.x,f.peak.y+100,f.peak.z);camera.fov=45}camera.updateProjectionMatrix();controls.update();state.needsRender=true;history.replaceState(null,'',`${location.pathname}?view=${view}&v=1000`)}
function setQa(id,ok,text){const el=$(id);el.textContent=text;el.className=ok?'pass':'fail'}
function updateMetrics(report){$('sourceGrid').textContent=report.sourceGrid.join(' × ');$('sourceSpacing').textContent=`${report.sourceSpacingMeters.toFixed(1)} m`;$('vertexCount').textContent=report.vertexCount.toLocaleString();$('triangleCount').textContent=report.triangleCount.toLocaleString();$('deltaRange').textContent=`${report.morphologyDeltaRangeMeters[0].toFixed(1)} / +${report.morphologyDeltaRangeMeters[1].toFixed(1)} m`;$('riverSections').textContent=report.riverSectionCount.toLocaleString();$('riverBreaks').textContent=String(report.riverInternalBreakCount);setQa('qaTruth',report.truthSha256?.length===64,report.truthSha256?.length===64?'锁定':'失败');setQa('qaMutation',report.truthMutationCount===0,String(report.truthMutationCount));setQa('qaSeed',report.tileSeedRestartCount===0,String(report.tileSeedRestartCount));setQa('qaProtect',report.protectedMorphologyViolationCount===0,String(report.protectedMorphologyViolationCount));setQa('qaRiver',report.riverInternalBreakCount===0,String(report.riverInternalBreakCount))}
function startWorker(source,riverPoints){return new Promise((resolve,reject)=>{const worker=new Worker('./terrain-worker.js?v=1000',{type:'module'}),gridSize=isMobile?1025:2049,maxError=isMobile?6.0:3.0;worker.onmessage=event=>{const data=event.data;if(data.type==='progress'){setLoading(data.value,data.label)}else if(data.type==='result'){worker.terminate();resolve(data)}else if(data.type==='error'){worker.terminate();reject(new Error(data.message))}};worker.onerror=event=>reject(new Error(event.message));worker.postMessage({rawBuffer:source.heightBuffer,sourceWidth:source.width,sourceHeight:source.height,sourceScale:source.scale,sourceOffset:source.offset,sourceNoData:source.nodata,bounds:source.bounds,gridSize,maxError,riverPoints,truthSha256:source.truthSha256},[source.heightBuffer])})}
function bindUI(){document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>cameraFor(button.dataset.view)));document.querySelectorAll('[data-map]').forEach(button=>button.addEventListener('click',()=>applyMap(button.dataset.map)));$('truthToggle').addEventListener('click',()=>applyTruthMode(!state.truthOnly));$('wireToggle').addEventListener('click',()=>{state.wire=!state.wire;$('wireToggle').classList.toggle('active',state.wire);if(state.terrain)state.terrain.material.wireframe=state.wire;state.needsRender=true});$('resetView').addEventListener('click',()=>cameraFor(state.view));controls.addEventListener('start',()=>{state.interacting=true;renderer.setPixelRatio(state.interactionPixelRatio);renderer.setSize(innerWidth,innerHeight,false);$('perf').textContent='交互性能模式：降低像素密度，几何与字段相位保持不变'});controls.addEventListener('end',()=>{state.interacting=false;renderer.setPixelRatio(state.restPixelRatio);renderer.setSize(innerWidth,innerHeight,false);$('perf').textContent='高清模式已恢复 · 自适应网格保持连续';state.needsRender=true});controls.addEventListener('change',()=>state.needsRender=true);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);state.needsRender=true})}
function animate(){requestAnimationFrame(animate);const moved=controls.update();if(moved||state.needsRender||state.interacting){renderer.render(scene,camera);state.needsRender=false}}
async function samplePerformance(frames=90){const start=performance.now();for(let i=0;i<frames;i++){camera.position.applyAxisAngle(new THREE.Vector3(0,1,0),.0008);camera.lookAt(controls.target);renderer.render(scene,camera);await new Promise(requestAnimationFrame)}const ms=performance.now()-start;return{frames,ms,fps:frames/ms*1000}}
async function boot(){bindUI();animate();try{const source=await loadTruth();const river=await loadRiver(source.bounds);setLoading(12,'启动 Worker 与误差驱动网格');const result=await startWorker(source,river);createTerrain(result);createWater(result.riverSections);state.report=result.report;state.focuses=result.focuses;state.ready=true;updateMetrics(result.report);cameraFor(state.view);applyMap('colour');$('loading').classList.add('hidden');setStatus(`Landscape Mother v1.0 已加载 · ${result.report.adaptiveMesh?'Martini 自适应网格':'连续规则网格回退'} · 河流内部断点 ${result.report.riverInternalBreakCount}`);window.__landscapeMotherQA={...result.report,ready:true,consoleErrors:[],pageErrors:[],visualApproved:false,productionReady:false};window.__landscapeMotherPerf={sample:samplePerformance};state.needsRender=true}catch(error){console.error(error);$('loadingTitle').textContent='连续字段构建失败';$('loadingDetail').textContent=error.message;setStatus(`失败关闭：${error.message}`);window.__landscapeMotherQA={ready:false,error:error.message,truthApproved:false,visualApproved:false,productionReady:false}}}

boot();
