const{chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const out='carry-results',base='http://127.0.0.1:8765/kaopu-unified-human-workbench/';fs.mkdirSync(out,{recursive:true});const report={passed:false,errors:[],cases:[],softwareRendering:true,scope:'same original overview canvas; pre-held box captured walk; no pickup, release, load physics or between-sample CCD claim'};let browser;const save=()=>fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));
(async()=>{try{browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(240000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#load-model').click();await page.waitForFunction(()=>!!window.fullCommonWorkbench?.motion(),null,{timeout:480000});
for(const id of ['r02-child-male-tall-slim','r02-adult-female-rounded','r02-senior-male-sturdy']){
 await page.evaluate(async id=>{const m=fullCommonWorkbench.motion();await m.setMode('shape');await fullCommonWorkbench.applyPreset(id);m.activityClip='carry';await m.setMode('activity');m.expandTraining(true);m.view('three');},id);await page.waitForFunction(()=>fullCommonWorkbench.motion().activity?.bodyPlan);const prefix=id.replace('r02-',''),row={id,diagnostics:await page.evaluate(()=>fullCommonWorkbench.motion().diagnostics()),screens:[]};assert.equal(row.diagnostics.canvasCount,1);assert.equal(row.diagnostics.actors[0].vertices,25417);
 const snapshot=async name=>{const p=prefix+'-'+name;await page.screenshot({path:out+'/'+p+'.png'});row.screens.push(p);save();};
 row.nativeFootCheck=await page.evaluate(()=>{const m=fullCommonWorkbench.motion(),c=m.activity,h=m.actors[0].human;let maxProtectedDifference=0,minSole=Infinity,maxGroundGap=0;for(let f=0;f<285;f++){m.activityFrame(f/120);const p=m.actors[0].latest,original=c.base.evaluate(f/120);for(let j=0;j<h.names.length;j++)if(!c.adapter.armSet.has(j))for(let k=0;k<16;k++)maxProtectedDifference=Math.max(maxProtectedDifference,Math.abs(p.skinMatrices[j][k]-original.skinMatrices[j][k]),Math.abs(p.posedMatrices[j][k]-original.posedMatrices[j][k]));let sole=Infinity;for(const ids of Object.values(c.base.soleIndices))for(const v of ids)sole=Math.min(sole,h.sampleVertex(v)[2]+h.floorOffset);minSole=Math.min(minSole,sole);maxGroundGap=Math.max(maxGroundGap,sole);}m.reset();return{frames:285,maxProtectedDifference,minSole,maxGroundGap};});assert.equal(row.nativeFootCheck.maxProtectedDifference,0);assert(row.nativeFootCheck.minSole>=-1e-6);assert(row.nativeFootCheck.maxGroundGap<1e-5);
 for(const view of ['full','hands']){await page.evaluate(view=>{const m=fullCommonWorkbench.motion();m.reset();m.view(view==='full'?'side':'hands');},view);const dir=out+'/'+prefix+'-'+view;fs.mkdirSync(dir,{recursive:true});for(let i=0;i<30;i++){if(i)await page.evaluate(n=>fullCommonWorkbench.motion().advanceSteps(n),i===29?4:10);await page.screenshot({path:dir+'/'+String(i).padStart(4,'0')+'.png'});}execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-framerate','12','-i',dir+'/%04d.png','-vf',"drawtext=text='OFFLINE FIXED-STEP - PREHELD BOX WALK - NO LOAD PHYSICS':x=12:y=12:fontsize=18:fontcolor=white:box=1:boxcolor=black@0.8",'-c:v','libx264','-pix_fmt','yuv420p',out+'/'+prefix+'-'+view+'.mp4']);}
 await page.evaluate(()=>{const m=fullCommonWorkbench.motion();m.reset();m.advanceSteps(142);});for(const angle of ['front','side','rear','hands']){await page.evaluate(a=>fullCommonWorkbench.motion().view(a),angle);await snapshot(angle+'-mid');}await page.evaluate(()=>{const m=fullCommonWorkbench.motion();m.view('hands');const target=m.viewer.orbit.target.clone(),distance=m.viewer.camera.position.distanceTo(target);m.viewer.camera.position.copy(target).add({x:distance,y:0,z:0});m.viewer.orbit.update();m.viewer.render();});await snapshot('hands-side-mid');
 await page.evaluate(()=>{const m=fullCommonWorkbench.motion();m.reset();m.setPlaying(true);});await page.waitForTimeout(350);await page.evaluate(()=>fullCommonWorkbench.motion().setPlaying(false));const t=await page.evaluate(()=>fullCommonWorkbench.motion().time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>fullCommonWorkbench.motion().time),t);await page.evaluate(()=>fullCommonWorkbench.motion().reset());assert.equal(await page.evaluate(()=>fullCommonWorkbench.motion().time),0);row.pauseReset=true;report.cases.push(row);save();
}
await page.evaluate(()=>fullCommonWorkbench.motion().setMode('shape'));assert.equal(await page.evaluate(()=>document.querySelectorAll('canvas').length),1);assert.deepEqual(report.errors,[]);report.passed=true;}catch(e){report.failure=e.stack;process.exitCode=1;}finally{save();await browser?.close();}})();
