import {sweepTriangles} from './TriangleContact.mjs';
import {SURFACE_TOLERANCE} from './SurfaceNarrowPhase.mjs';
const box=()=>({min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]}),extend=(b,p)=>{for(let k=0;k<3;k++){b.min[k]=Math.min(b.min[k],p[k]);b.max[k]=Math.max(b.max[k],p[k]);}return b;},overlap=(a,b)=>[0,1,2].every(k=>a.min[k]-SURFACE_TOLERANCE<=b.max[k]&&a.max[k]+SURFACE_TOLERANCE>=b.min[k]);
const triangle=(snapshot,t)=>[0,1,2].map(k=>{const v=snapshot.faces[t*3+k];return Array.from(snapshot.positions.subarray(v*3,v*3+3));});
export function snapshotGlove(glove){glove.updateWorldMatrix(true,false);const p=glove.geometry.attributes.position,m=glove.matrixWorld.elements,out=new Float64Array(p.count*3);for(let v=0;v<p.count;v++){const x=p.getX(v),y=p.getY(v),z=p.getZ(v);for(let k=0;k<3;k++)out[v*3+k]=m[k]*x+m[4+k]*y+m[8+k]*z+m[12+k];}return {positions:out,faces:glove.geometry.index.array,side:glove.side,source:'actual posed glove geometry including articulated cuff'};}
function limitedBounds(a,b,t){const q=box();a.forEach(p=>extend(q,p));b.forEach((p,i)=>extend(q,p.map((v,k)=>a[i][k]+(v-a[i][k])*t)));return q;}
function intervalBounds(vertices){const b=box();vertices.forEach(v=>extend(b,v));return b;}
function earliestBoxOverlap(a0,a1,b0,b1){let lo=0,hi=1;for(let k=0;k<3;k++)for(const [x0,x1,y0,y1] of [[a0.min[k],a1.min[k],b0.max[k],b1.max[k]],[b0.min[k],b1.min[k],a0.max[k],a1.max[k]]]){const f=x0-y0-SURFACE_TOLERANCE,d=(x1-x0)-(y1-y0);if(Math.abs(d)<1e-15){if(f>0)return Infinity;}else if(d>0)hi=Math.min(hi,-f/d);else lo=Math.max(lo,-f/d);if(lo>hi)return Infinity;}return lo;}
function attackerTriangles(previous,current){if(previous.positions.length!==current.positions.length||previous.faces.length!==current.faces.length)throw Error('Glove topology changed between snapshots');const entries=[];for(let t=0;t<current.faces.length/3;t++){const a=triangle(previous,t),b=triangle(current,t),bounds=box();a.forEach(p=>extend(bounds,p));b.forEach(p=>extend(bounds,p));entries.push({a,b,bounds,start:intervalBounds(a),end:intervalBounds(b),id:t});}return entries;}
/** Precise mesh surface contact. All opposing regions remain eligible, so an
 * intervening forearm/leg cannot become a mislabeled torso hit. Self/pair
 * filtering belongs to the caller. Budgets are explicit, never silent misses. */
export function castGloveSurface(surface,previous,current,{maxTrianglePairs=100000}={}){
 const attack=attackerTriangles(previous,current),bounds=box();attack.forEach(t=>{extend(bounds,t.bounds.min);extend(bounds,t.bounds.max);});let best=null,unresolved=false,pairs=0;
 const visit=node=>{if(pairs>maxTrianglePairs){unresolved=true;return;}const p=surface.bounds(node,surface.previous),q=surface.bounds(node,surface.current),swept={min:p.min.map((x,k)=>Math.min(x,q.min[k])),max:p.max.map((x,k)=>Math.max(x,q.max[k]))};if(!overlap(bounds,swept))return;const candidates=attack.filter(t=>overlap(t.bounds,swept));if(!candidates.length)return;if(node.children){const center=[0,1,2].map(k=>previous.positions.reduce((s,v,i)=>i%3===k?s+v:s,0)/(previous.positions.length/3));node.children.slice().sort((x,y)=>{const score=n=>{const z=surface.bounds(n,surface.previous);return center.reduce((s,v,k)=>s+Math.max(z.min[k]-v,0,v-z.max[k])**2,0);};return score(x)-score(y);}).forEach(visit);return;}
  for(const t of node.triangles){const ids=[0,1,2].map(k=>surface.human.faces[t*3+k]),a=ids.map(v=>surface.vertex(v,surface.previous)),b=ids.map(v=>surface.vertex(v,surface.current)),tb=box();a.forEach(p=>extend(tb,p));b.forEach(p=>extend(tb,p));for(const candidate of candidates){if(!overlap(tb,candidate.bounds))continue;const lower=earliestBoxOverlap(candidate.start,candidate.end,intervalBounds(a),intervalBounds(b));if(!Number.isFinite(lower)||best&&lower>best.toi)continue;if(best&&!overlap(limitedBounds(a,b,best.toi),limitedBounds(candidate.a,candidate.b,best.toi)))continue;if(++pairs>maxTrianglePairs){unresolved=true;return;}const hit=sweepTriangles(candidate.a,candidate.b,a,b);if(hit?.unresolved){unresolved=true;continue;}if(hit&&(!best||hit.toi<best.toi))best={...hit,triangleId:t,attackerTriangleId:candidate.id,vertexIds:ids,bodyRegion:surface.triangleRegion[t],source:'actual glove mesh / full CSR surface continuous triangle contact',proxyApproximation:false,surfaceToleranceM:SURFACE_TOLERANCE,trajectory:'linear rendered vertices per fixed step'};}}
 };visit(surface.root);return {hit:best,unresolved,trianglePairs:pairs,reason:unresolved?'exact-mesh-budget-or-convergence':null};
}
export function castGloveGuard(attackPrevious,attackCurrent,guardPrevious,guardCurrent,{maxTrianglePairs=100000}={}){
 const attack=attackerTriangles(attackPrevious,attackCurrent),guard=attackerTriangles(guardPrevious,guardCurrent);let best=null,unresolved=false,pairs=0;
 for(const a of attack)for(const b of guard){if(!overlap(a.bounds,b.bounds))continue;const lower=earliestBoxOverlap(a.start,a.end,b.start,b.end);if(!Number.isFinite(lower)||best&&lower>best.toi)continue;if(++pairs>maxTrianglePairs)return {hit:best,unresolved:true,trianglePairs:pairs};const hit=sweepTriangles(a.a,a.b,b.a,b.b);if(hit?.unresolved){unresolved=true;continue;}if(hit&&(!best||hit.toi<best.toi))best={...hit,attackerTriangleId:a.id,triangleId:b.id,bodyRegion:'glove.'+guardCurrent.side,source:'actual glove / actual guard continuous triangle contact',proxyApproximation:false};}
 return {hit:best,unresolved,trianglePairs:pairs};
}
