import * as THREE from '../source/registration-vendor/three.module.js';
import {OrbitControls} from '../ui/vendor/OrbitControls.js';
import {loadCommon} from '../ui/load-common.mjs';
import {defaultState} from '../src/State.mjs';
import {PRESETS,createPresetState} from '../ui/PresetCatalogueR2.mjs';
import {AnimatedHuman} from './AnimatedHuman.mjs';
import {createBoxingRig,sampleBoxingPair,BOXING_VARIANTS,recommendPairSeparation} from './Motion.mjs';
const $=id=>document.getElementById(id),colors=[0x2f90b6,0xc56e43],actors=[],arenas=[],errors=[],perf=[];let renderer,scene,camera,orbit,loaded,busy=false,aborter,ready=false,time=0,last=0,playing=true,speed=1,focus=-1,angle='three',contact=true,skeleton=false,frames=0,raf=0,observer=null,dirty=true,shadowTexture=null;
const pairs=Array.from({length:18},(_,i)=>({id:i,a:PRESETS[i*2],b:PRESETS[i*2+1]}));
for(const p of pairs){const b=document.createElement('button');b.dataset.arena=p.id;b.innerHTML=`${String(p.id+1).padStart(2,'0')} / ${p.a.stageLabel}<small>蓝 · ${p.a.buildLabel}<br>橙 · ${p.b.buildLabel}<br>${BOXING_VARIANTS[p.id%3].label||BOXING_VARIANTS[p.id%3].name||'动作组'}</small>`;b.addEventListener('click',()=>select(p.id));$('arenas').append(b);}
function select(i){focus=i;for(const b of document.querySelectorAll('[data-arena]'))b.classList.toggle('active',+b.dataset.arena===i);if(i<0){$('selection').innerHTML='<h2>18台同时观察</h2><p>不同体型同源动作测试。点选任意擂台放大，36个角色均保持完整计算。</p>';$('view-label').textContent='18 ARENAS / 36 CHARACTERS';}else{const p=pairs[i];$('selection').innerHTML=`<h2>${String(i+1).padStart(2,'0')} · ${p.a.stageLabel}</h2><p>蓝：${p.a.label}<br>橙：${p.b.label}</p><p>${['child','teen'].includes(p.a.stage)?'比例覆盖 · 低强度目标练习':'守架 → 出拳 → 闪避 → 反击 → 恢复'}</p>`;$('view-label').textContent=`ARENA ${String(i+1).padStart(2,'0')} / ${p.a.stageLabel}`;}view();}
function view(){if(!camera)return;const center=focus<0?new THREE.Vector3(0,0,0):new THREE.Vector3(arenas[focus].x,(actors[focus*2].human.height+actors[focus*2+1].human.height)*.25,arenas[focus].z);const dir=angle==='side'?[0,.27,1]:angle==='rear'?[-1,.22,-.45]:angle==='front'?[1,.22,.45]:[.62,.46,1];if(focus<0){camera.position.set(5,24,25);orbit.target.set(0,0,0);}else{camera.position.copy(center).add(new THREE.Vector3(...dir).normalize().multiplyScalar((actors[focus*2].human.height+actors[focus*2+1].human.height)*.5*(innerWidth<750?3.0:2.8)));orbit.target.copy(center);}orbit.update();}
function initRenderer(){renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x1d2a34);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new THREE.Scene();scene.fog=new THREE.Fog(0x1d2a34,35,85);camera=new THREE.PerspectiveCamera(36,1,.05,140);orbit=new OrbitControls(camera,$('canvas'));orbit.enableDamping=true;orbit.addEventListener('change',()=>{dirty=true;});orbit.maxPolarAngle=Math.PI*.485;scene.add(new THREE.HemisphereLight(0xd7eaf5,0x555354,2));const sun=new THREE.DirectionalLight(0xffe4ce,3.2);sun.position.set(-8,15,8);scene.add(sun);const rim=new THREE.DirectionalLight(0x9bc8ec,1.8);rim.position.set(9,6,-5);scene.add(rim);
 const sh=document.createElement('canvas');sh.width=sh.height=128;const sc=sh.getContext('2d'),sg=sc.createRadialGradient(64,64,5,64,64,62);sg.addColorStop(0,'rgba(0,0,0,.55)');sg.addColorStop(.45,'rgba(0,0,0,.3)');sg.addColorStop(1,'rgba(0,0,0,0)');sc.fillStyle=sg;sc.fillRect(0,0,128,128);shadowTexture=new THREE.CanvasTexture(sh);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0x17232c,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.075;scene.add(ground);
 for(let i=0;i<18;i++){const x=(i%6-2.5)*4.4,z=(Math.floor(i/6)-1)*4.4,g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const floor=new THREE.Mesh(new THREE.BoxGeometry(3.8,.08,3.8),new THREE.MeshStandardMaterial({color:i%2?0x324c58:0x3b515b,roughness:.97}));floor.position.y=-.041;g.add(floor);const border=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(3.8,.08,3.8)),new THREE.LineBasicMaterial({color:0x88a2a9,transparent:true,opacity:.5}));border.position.y=-.04;g.add(border);for(const side of [-1,1]){const corner=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.48,8),new THREE.MeshStandardMaterial({color:side<0?colors[0]:colors[1]}));corner.position.set(side*1.8,.24,-1.8);g.add(corner);}const cv=document.createElement('canvas');cv.width=256;cv.height=64;const cx=cv.getContext('2d');cx.fillStyle='#c6dbe1';cx.font='bold 32px sans-serif';cx.textAlign='center';cx.fillText(String(i+1).padStart(2,'0'),128,40);const tag=new THREE.Mesh(new THREE.PlaneGeometry(.7,.18),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(cv),transparent:true,depthWrite:false}));tag.rotation.x=-Math.PI/2;tag.position.set(0,.005,1.63);g.add(tag);arenas.push({x,z,group:g});}
 const resize=()=>{const r=$('canvas').parentElement.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};observer=new ResizeObserver(resize);observer.observe($('canvas').parentElement);resize();view();}
async function start(){if(busy||ready)return;busy=true;aborter=new AbortController();$('start').hidden=true;$('cancel').hidden=false;$('progress').hidden=false;const started=performance.now();try{loaded=await loadCommon({signal:aborter.signal,onProgress:p=>{$('progress').value=p.fraction*.45;$('load-status').textContent='校验现有资产 '+Math.round(p.fraction*100)+'%';}});initRenderer();for(let i=0;i<36;i++){if(aborter.signal.aborted)throw new DOMException('cancel','AbortError');const state=createPresetState(PRESETS[i].id,defaultState);const t=performance.now();loaded.model.compute(state);const human=new AnimatedHuman(loaded.model,state,{color:colors[i%2],tone:.64});const motion=createBoxingRig({names:human.rig.names,parents:human.rig.parents,restMatrices:human.rig.restMatrices,stature:human.height,child:['child','teen'].includes(PRESETS[i].stage)});const group=new THREE.Group();group.rotation.y=i%2?-Math.PI/2:Math.PI/2;group.position.y=human.floorOffset;group.add(human.mesh);arenas[Math.floor(i/2)].group.add(group);const footShadows=['L','R'].map(side=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.24,.37),new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false,opacity:.75}));mesh.rotation.x=-Math.PI/2;mesh.renderOrder=1;group.add(mesh);return {mesh,index:human.names.indexOf('foot.'+side)};});const gloves=[];for(const side of ['L','R']){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.081,18,14),new THREE.MeshStandardMaterial({color:colors[i%2],roughness:.65}));mesh.scale.set(1,1.25,.95);group.add(mesh);gloves.push({mesh,index:human.names.indexOf('wrist.'+side),knuckle:human.names.indexOf('finger3-1.'+side)});}const line=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(new Float32Array(human.names.length*6),3)),new THREE.LineBasicMaterial({color:0xf4e7a7,depthTest:false,transparent:true,opacity:.75}));line.visible=skeleton;line.renderOrder=5;group.add(line);actors.push({human,motion,group,gloves,footShadows,line,preset:PRESETS[i],prepareMS:performance.now()-t,latest:null});$('progress').value=.45+.55*(i+1)/36;$('load-status').textContent=`真实形态装配 ${i+1} / 36 · 每人25,417顶点`;await new Promise(r=>setTimeout(r,0));}
 for(let i=0;i<18;i++){const a=actors[i*2],b=actors[i*2+1],d=recommendPairSeparation(i);a.group.position.x=-d/2;b.group.position.x=d/2;arenas[i].separation=d;}
 ready=true;busy=false;$('loading').hidden=true;$('pause').disabled=false;$('restart').disabled=false;window.boxingWorkbench.loadMS=performance.now()-started;select(-1);last=performance.now();raf=requestAnimationFrame(tick);
 }catch(e){if(e.name!=='AbortError')errors.push(e.message);releasePartial();$('load-status').textContent=e.name==='AbortError'?'载入已取消，重新载入即可。':'载入失败：'+e.message;$('start').hidden=false;$('start').textContent='重新载入';busy=false;}finally{$('cancel').hidden=true;}}
const nativeToView=(m)=>[m[3],m[11],-m[7]];
function poseAt(t){const begin=performance.now();for(let i=0;i<actors.length;i++){const a=actors[i],out=a.motion.evaluate(t,{pairIndex:Math.floor(i/2),fighter:i%2,child:['child','teen'].includes(a.preset.stage),intensity:1,opponentStature:actors[i^1].human.height,contactIK:contact,footLock:contact});a.latest=out;a.human.animate(out.skinMatrices);for(const sh of a.footShadows){const m=out.posedMatrices[sh.index],p=nativeToView(m),scale=a.human.height/1.75;sh.mesh.position.set(p[0],.005-a.group.position.y,p[2]-.035*scale);sh.mesh.scale.setScalar(scale);sh.mesh.material.opacity=.75*Math.exp(-20*Math.max(0,m[11]-a.human.rig.restMatrices[sh.index][11]));}for(const glove of a.gloves)if(glove.index>=0){const m=out.posedMatrices[glove.index],k=out.posedMatrices[glove.knuckle],w=new THREE.Vector3(...nativeToView(m)),kn=new THREE.Vector3(...nativeToView(k)),dir=kn.clone().sub(w).normalize(),s=a.human.height/1.75;glove.mesh.position.copy(w).lerp(kn,.75);glove.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);glove.mesh.scale.set(s,s*1.25,s*.95);}
 if(skeleton){const p=a.line.geometry.attributes.position;let k=0;for(let j=0;j<a.human.names.length;j++){const parent=a.human.rig.parents[j];const u=nativeToView(out.posedMatrices[j]),v=nativeToView(out.posedMatrices[parent<0?j:parent]);p.setXYZ(k++,...u);p.setXYZ(k++,...v);}p.needsUpdate=true;}a.line.visible=skeleton;}return performance.now()-begin;}
function tick(now){if(!ready)return;const actualDT=(now-last)/1000,dt=actualDT;last=now;orbit.update();if(!playing&&!dirty){raf=requestAnimationFrame(tick);return;}dirty=false;if(playing)time+=dt*speed;const cpu=poseAt(time);const r=performance.now();renderer.render(scene,camera);frames++;perf.push({dt:actualDT*1000,cpu,render:performance.now()-r});if(perf.length>180)perf.shift();if(frames%15===0)updateStats();raf=requestAnimationFrame(tick);}
$('start').onclick=start;$('cancel').onclick=()=>aborter?.abort();$('overview').onclick=()=>select(-1);$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'暂停':'继续';updateStats();};$('restart').onclick=()=>{time=0;dirty=true;};$('speed').onchange=e=>speed=+e.target.value;for(const b of document.querySelectorAll('[data-angle]'))b.onclick=()=>{angle=b.dataset.angle;view();};$('contact').onchange=e=>{contact=e.target.checked;dirty=true;};$('skeleton').onchange=e=>{skeleton=e.target.checked;dirty=true;};
window.boxingWorkbench={start,select,seek:t=>{time=t;poseAt(t);updateStats();renderer.render(scene,camera);},setPlaying:v=>{playing=!!v;$('pause').textContent=playing?'暂停':'继续';updateStats();},setContact:v=>{contact=!!v;dirty=true;$('contact').checked=contact;},setAngle:v=>{angle=v;view();},diagnostics:()=>({ready,busy,time,frames,actors:actors.length,pairs:arenas.length,focus,contact,errors,renderer:renderer?gpuInfo():null,drawCalls:renderer?.info.render.calls,trianglesRendered:renderer?.info.render.triangles,perf:perf.length?{meanFrameMS:perf.reduce((s,v)=>s+v.dt,0)/perf.length,meanCPU:perf.reduce((s,v)=>s+v.cpu,0)/perf.length}:null,characters:actors.map(a=>({id:a.preset.id,height:a.human.height,prepareMS:a.prepareMS,...a.human.report,metrics:a.latest?.metrics,state:a.latest?.state,footContacts:a.latest?.footContacts}))}),sample:(i,vertex)=>actors[i].human.sampleVertex(vertex),actors:()=>actors};

function releasePartial(){cancelAnimationFrame(raf);observer?.disconnect();observer=null;orbit?.dispose();for(const a of actors)a.human.dispose();actors.length=0;arenas.length=0;if(scene){scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});scene.clear();}renderer?.dispose();renderer=null;scene=null;camera=null;orbit=null;ready=false;loaded=null;}
addEventListener('pagehide',()=>{cancelAnimationFrame(raf);if(busy)aborter?.abort();});addEventListener('pageshow',e=>{if(e.persisted&&ready){last=performance.now();raf=requestAnimationFrame(tick);}});

addEventListener('visibilitychange',()=>{last=performance.now();});

function gpuInfo(){const gl=renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {masked:gl.getParameter(gl.RENDERER),unmasked:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,version:gl.getParameter(gl.VERSION)};}

function updateStats(){if(!actors.length)return;const sum=perf.reduce((s,v)=>s+v.dt,0),avg=sum/(perf.length||1),fpsReady=perf.length>=30&&sum>=3000;const f=focus<0?0:focus*2,phaseName={guard:'守架',jab:'刺拳',cross:'直拳',hook:'勾拳',slip:'侧闪',duck:'下潜',block:'格挡',recover:'恢复'},states=actors.slice(f,f+2).map(a=>a.latest?.state?.label||phaseName[a.latest?.state?.phase]||a.latest?.state?.phase||'动作');$('stats').textContent=`36 / 36 完整角色 · 18 / 18组运行\n${playing?(fpsReady?(1000/avg).toFixed(1)+' FPS':'帧率采样中'):'已暂停'} · ${time.toFixed(2)}s · ${speed}× · ${contact?'接触IK 开':'接触IK 关'}\n${focus<0?'01组':String(focus+1).padStart(2,'0')+'组'} 蓝 ${states[0]} · 橙 ${states[1]}\n自研规则动作 · 未运行研究权重`;}
