import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {PNG} from 'pngjs';
const url=process.argv[2],publicMode=process.argv.includes('--public');if(!url)throw Error('Specify URL');const out=path.resolve('kaopu-hair-workbench/fusion/r11/evidence',publicMode?'public':'local');fs.mkdirSync(out,{recursive:true});
const report={version:'R11.0',url,publicMode,started:new Date().toISOString(),hardware:'GitHub Actions software WebGL, not a hardware performance test',checks:[],errors:[],browPresets:[],success:false};
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1180,height:900},deviceScaleFactor:1});const page=await context.newPage();page.setDefaultTimeout(300000);page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
const check=(n,v)=>{assert(v,n);report.checks.push(n);console.log('PASS',n)};const d=()=>page.evaluate(()=>window.groomStudy.teachersDiagnostics());
async function frame(name){const buf=await page.screenshot();fs.writeFileSync(path.join(out,name+'.png'),buf);const png=PNG.sync.read(buf),r=await page.locator('#canvas').boundingBox();assert(r&&r.width>100&&r.height>100);let min=255,max=0;for(let y=Math.max(0,Math.ceil(r.y));y<Math.min(png.height,Math.floor(r.y+r.height));y++)for(let x=Math.max(0,Math.ceil(r.x));x<Math.min(png.width,Math.floor(r.x+r.width));x++){const i=(y*png.width+x)*4,v=(png.data[i]+png.data[i+1]+png.data[i+2])/3;min=Math.min(min,v);max=Math.max(max,v)}check(name+' real nonblank canvas',max-min>45)}
try{
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.groomStudy?.ready,{},{timeout:300000});await page.evaluate(()=>window.groomStudy.freeze());let state=await d();report.initial=state;
 check('R11 actually loaded',state.version==='R11.0');check('all 14 original CC0 styles extracted',state.libraryStyles===14&&state.sourceStrands===23087);check('one active eyebrow layer',state.activeEyebrowLayers===1);check('no neural model or CUDA masquerade',!state.cudaSolverRunning&&!state.permNeuralModelRunning);await frame('01-fusion-default');
 await page.evaluate(()=>{window.groomStudy.setGroom({hairVisible:false,beardVisible:false});window.groomStudy.setPanel('brows');window.groomStudy.browCamera()});
 const shapes=new Set();for(let i=1;i<=14;i++){await page.evaluate(i=>document.querySelector(`[data-brows-model="${i}"]`).click(),i);state=await d();const b=state.brows;check('brow '+i+' correct source',b.style===i&&b.sourceCount>=700);check('brow '+i+' real bound fibres',b.finite&&b.triangleAttached&&!b.meshOverlay&&b.count>300&&b.maxRootOffset<.00005);check('brow '+i+' eyelid guard',b.minNeutralEyeGap>=.00349);check('brow '+i+' one layer',state.activeEyebrowLayers===1);shapes.add(b.curveHash);report.browPresets.push(b);await frame('brow-'+String(i).padStart(2,'0'))}check('14 distinct actual curve geometries',shapes.size===14);check('all brow presets leave head mesh unchanged',(await d()).headPositionHash===report.initial.headPositionHash);
 const full=(await d()).brows;await page.evaluate(()=>window.groomStudy.setGroom({browsDensity:35}));let lower=(await d()).brows;check('brow density changes draw count',lower.activeCount<full.activeCount);check('density leaves roots fixed',lower.rootHash===full.rootHash);
 await page.evaluate(()=>window.groomStudy.setGroom({browsDensity:100,browsLength:55}));let short=(await d()).brows;check('shaft length changes real curves',short.curveHash!==full.curveHash);check('shaft length leaves roots fixed',short.rootHash===full.rootHash);
 await page.evaluate(()=>window.groomStudy.setGroom({browsLength:100,browsArch:12,browsSpan:90,browsThickness:75}));let shape=(await d()).brows;check('arch span and thickness alter real roots',shape.rootHash!==full.rootHash&&shape.maxRootOffset<.00005);await frame('brow-custom');
 await page.evaluate(()=>window.groomStudy.setCase('smile'));state=await d();check('brows remain skin-bound in expression',state.brows.finite&&state.brows.maxRootOffset<.00005);await frame('brow-smile');await page.evaluate(()=>window.groomStudy.setCase('neutral'));
 const saved=await page.evaluate(()=>window.groomStudy.fusionSnapshot());await page.evaluate(()=>document.getElementById('fusionSave').click());await page.evaluate(()=>window.groomStudy.setGroom({browsModel:2,browsDensity:20}));await page.evaluate(()=>document.getElementById('fusionRestore').click());const restored=await page.evaluate(()=>window.groomStudy.fusionSnapshot());check('all new parameters save and restore',JSON.stringify(saved.groom)===JSON.stringify(restored.groom));
 await page.evaluate(()=>window.groomStudy.setGroom({browsModel:0}));state=await d();check('R9 original brows retained without overlap',state.activeEyebrowLayers===1&&state.browsModel===0);await frame('brow-r9-original');
 await page.evaluate(()=>{document.querySelector('[data-brows-model="1"]').click();window.groomStudy.setGroom({hairVisible:true,beardVisible:false});window.groomStudy.setStyle('side-sweep');window.groomStudy.setPanel('hair');window.groomStudy.fusionCamera('top')});const original=await d();await page.evaluate(()=>document.getElementById('waveSoft').click());const wave=await d();check('wave residual changes actual curves',wave.scalpCurveHash!==original.scalpCurveHash&&wave.details.maxOffset>0);check('wave residual keeps roots',wave.scalpRootHash===original.scalpRootHash);await frame('02-waves');await page.evaluate(()=>document.getElementById('waveCurl').click());await frame('03-microcurl');await page.evaluate(()=>document.getElementById('waveClear').click());check('detail zero restores exact original curves',(await d()).scalpCurveHash===original.scalpCurveHash);
 for(const s of ['short-crop','swept-back','side-sweep','original','chin-trim','cropped-trim']){await page.evaluate(s=>{window.groomStudy.setStyle(s);window.groomStudy.setCamera('three')},s);check(s+' still operational',(await d()).brows.finite);if(['short-crop','original'].includes(s))await frame('hair-'+s)}
 await page.evaluate(()=>{window.groomStudy.setStyle('side-sweep');window.groomStudy.fusionCamera('nape')});await frame('04-nape');await page.evaluate(()=>window.groomStudy.fusionCamera('left'));await frame('05-ear');
 const roots=await page.evaluate(()=>window.groomStudy.fusionDiagnostics().regionalRootCounts);await page.evaluate(()=>window.groomStudy.setGroom({hairLeftCoverage:25,hairNapeCoverage:30}));const fewer=await page.evaluate(()=>window.groomStudy.fusionDiagnostics().regionalRootCounts);check('R3 regional scalp controls retained',fewer.left<roots.left&&fewer.nape<roots.nape);await page.evaluate(()=>window.groomStudy.setGroom({hairLeftCoverage:100,hairNapeCoverage:95}));
 await page.evaluate(()=>{document.getElementById('fusionBeard').click();window.groomStudy.fusionCamera('beard')});await frame('06-five-zone-beard');
 const packet=await page.evaluate(()=>window.groomStudy.guidePacket(32));check('actual guide topology exported',packet.guideCount===32&&packet.rootBindings.length===32&&packet.topology.roots.length===32&&packet.topology.links.length>100&&packet.notPhysicsSimulation);report.guidePacketSample={guideCount:packet.guideCount,links:packet.topology.links.length/2,firstRoot:packet.rootBindings[0]};
 await page.evaluate(()=>window.groomStudy.resetAll());report.final=await d();check('no JS or GPU errors',report.errors.length===0);await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>report.errors.push('mobile:'+e));await mp.goto(url+'#quality=light',{waitUntil:'domcontentloaded',timeout:120000});await mp.waitForFunction(()=>window.groomStudy?.ready,{},{timeout:300000});await mp.evaluate(()=>window.groomStudy.setPanel('brows'));report.mobile=await mp.evaluate(()=>({viewportOnly:true,width:document.documentElement.scrollWidth,viewport:innerWidth,qualityRoots:window.groomStudy.fusionDiagnostics().qualityRoots,brows:window.groomStudy.teachersDiagnostics().brows.style}));check('mobile viewport 36k light mode',report.mobile.qualityRoots===36000);check('mobile no horizontal overflow',report.mobile.width<=report.mobile.viewport+2);await mp.screenshot({path:path.join(out,'mobile-390x844.png')});await mobile.close();check('mobile no JS errors',report.errors.length===0);report.success=true;
}catch(e){report.failure=String(e.stack||e);console.error(report.failure);try{report.failureBody=await page.locator('body').innerText();await page.screenshot({path:path.join(out,'FAILURE.png')})}catch{}}finally{report.finished=new Date().toISOString();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close()}if(!report.success)process.exitCode=1;
