import*as THREE from'../source/registration-vendor/three.module.js';import{loadCommon}from'../ui/load-common.mjs';import{CommonViewer}from'../ui/Viewer.mjs';import{defaultState}from'../src/State.mjs';import{createState}from'../shape-r031/Catalogue.mjs';
let model,viewer,records,overlay,poseName='neutral',variant=false;const $=x=>document.getElementById(x),colors=[0xff5b55,0xffb84a,0xffe172,0xe2dd7e,0x3de2e3,0xe68afa],display=p=>new THREE.Vector3(p[0],p[2],-p[1]);
const state=()=>{const s=createState('bony-lean-adult',defaultState);if(variant)s.anny.phenotypes.height=.85;if(poseName==='elevated')s.anny.pose={'clavicle.L':[0,-12,0],'shoulder01.L':[10,0,0],'upperarm01.L':[35,0,0]};return s;};
function samples(){return records.landmarks.map(l=>({...l,posedPoint:[0,1,2].map(c=>l.ids.reduce((a,id,k)=>a+l.bary[k]*model.positions[id*3+c],0))}));}
function label(text,color){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=96;const c=canvas.getContext('2d');c.font='bold 42px Arial';c.strokeStyle='#17232b';c.lineWidth=8;c.strokeText(text,8,61);c.fillStyle=color;c.fillText(text,8,61);const tx=new THREE.CanvasTexture(canvas),m=new THREE.SpriteMaterial({map:tx,depthTest:false,depthWrite:false});const s=new THREE.Sprite(m);s.scale.set(.050,.019,1);s.renderOrder=21;return s;}
function updateMarkers(){if(overlay){overlay.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}});viewer.scene.remove(overlay);}overlay=new THREE.Group();const pts=[];for(const[l,i]of samples().map((l,i)=>[l,i])){const pos=display(l.posedPoint);pts.push(pos);const dot=new THREE.Mesh(new THREE.SphereGeometry(.004,12,8),new THREE.MeshBasicMaterial({color:colors[i],depthTest:false}));dot.position.copy(pos);dot.renderOrder=20;overlay.add(dot);const tag=label(l.id,'#'+colors[i].toString(16));tag.position.copy(pos).add(new THREE.Vector3(0,i%2?.026:.012,i%2?.014:-.008));overlay.add(tag);}const path=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xffdf61,depthTest:false}));path.renderOrder=19;overlay.add(path);const rig=model.lastBodyDriver.rig,joints=['clavicle.L','shoulder01.L','upperarm01.L'].map(n=>{const m=rig.posedMatrices[rig.names.indexOf(n)];return display([m[3],m[7],m[11]])});for(const[p,i]of joints.map((p,i)=>[p,i])){const dot=new THREE.Mesh(new THREE.SphereGeometry(.003,10,7),new THREE.MeshBasicMaterial({color:0x4b8dff,depthTest:false,wireframe:true}));dot.position.copy(p);dot.renderOrder=20;overlay.add(dot);const tag=label('J'+i,'#78a5ff');tag.position.copy(p).add(new THREE.Vector3(0,-.020,-.016));overlay.add(tag);}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(joints),new THREE.LineDashedMaterial({color:0x4b8dff,dashSize:.007,gapSize:.005,depthTest:false}));line.computeLineDistances();line.renderOrder=19;overlay.add(line);viewer.scene.add(overlay);viewer.render();}
function apply(){model.compute(state());viewer.update();viewer.skin.set({enabled:false});updateMarkers();}
function view(name){const target=new THREE.Vector3(.06,.49,.015);viewer.camera.up.set(0,1,0);if(name==='front')viewer.camera.position.set(.06,.49,1.14);else if(name==='side')viewer.camera.position.set(1.15,.49,.015);else if(name==='three')viewer.camera.position.set(.67,.64,.96);else{viewer.camera.up.set(0,0,-1);viewer.camera.position.set(.06,1.64,.015);}viewer.orbit.target.copy(target);viewer.orbit.update();viewer.render();}
async function load(){if(model)return;records=await(await fetch(new URL('./Landmarks.json',import.meta.url))).json();model=(await loadCommon()).model;model.compute(state());viewer=new CommonViewer({canvas:$('canvas'),container:$('stage'),model});viewer.skin.set({enabled:false});updateMarkers();view('front');$('status').textContent='只审注册点，不做骨性变形。彩点=表面候选；蓝虚线J0/1/2=内部driver，不是解剖端点。';}
$('load').onclick=load;for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);$('elevate').onclick=()=>{poseName=poseName==='neutral'?'elevated':'neutral';apply()};
window.landmarkStudy={load,view,pose:p=>{poseName=p;apply()},variant:v=>{variant=v;apply()},samples,positions:()=>Array.from(model.positions),archive:()=>model.archive(),recipe:()=>records,pixels:()=>viewer.pixelAudit()};
