import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),sharp=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),cache=path.join(root,'../.cache/fish-r10');fs.mkdirSync(cache,{recursive:true});
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),source=fs.readFileSync(path.join(root,'../local-r09/data/MUSKELLUNGE_PARAMETRIC_SCHOOL_R09.kfc9')),size=source.readUInt32LE(8),meta=JSON.parse(source.subarray(16,16+size)),oldChunks=new Map(meta.package.chunks.map(c=>[c.name,source.subarray(16+size+c.offset,16+size+c.offset+c.bytes)]));
function predictor(raw,wordBytes,strideWords){const n=Math.floor(raw.length/wordBytes),out=Buffer.allocUnsafe(raw.length),mask=wordBytes===4?0xffffffff:65535;for(let i=0;i<n;i++){const value=wordBytes===4?raw.readUInt32LE(i*wordBytes):raw.readUInt16LE(i*wordBytes),previous=i>=strideWords?(wordBytes===4?raw.readUInt32LE((i-strideWords)*wordBytes):raw.readUInt16LE((i-strideWords)*wordBytes)):0,delta=(value-previous)>>>0;for(let b=0;b<wordBytes;b++)out[b*n+i]=(delta>>>(8*b))&255;}raw.copy(out,n*wordBytes,n*wordBytes);return out;}
function undo(raw,wordBytes,strideWords){const n=Math.floor(raw.length/wordBytes),out=Buffer.allocUnsafe(raw.length);for(let i=0;i<n;i++){let delta=0;for(let b=0;b<wordBytes;b++)delta+=raw[b*n+i]*2**(8*b);const previous=i>=strideWords?(wordBytes===4?out.readUInt32LE((i-strideWords)*wordBytes):out.readUInt16LE((i-strideWords)*wordBytes)):0,value=(delta+previous)>>>0;if(wordBytes===4)out.writeUInt32LE(value,i*wordBytes);else out.writeUInt16LE(value&65535,i*wordBytes);}raw.copy(out,n*wordBytes,n*wordBytes);return out;}
const outputChunks=[],audits=[];
function addCompressed(name,raw){let packed=zlib.gzipSync(raw,{level:9}),filter=null;for(const wordBytes of [2,4])for(const strideWords of [1,2,3]){const candidate=zlib.gzipSync(predictor(raw,wordBytes,strideWords),{level:9});if(candidate.length<packed.length){packed=candidate;filter={wordBytes,strideWords};}}const inflated=zlib.gunzipSync(packed),decoded=filter?undo(inflated,filter.wordBytes,filter.strideWords):inflated;if(!decoded.equals(raw))throw Error('Lossless filter mismatch '+name);outputChunks.push({name,bytes:packed.length,decodedBytes:raw.length,decodedSha256:hash(raw),predictor:filter,payload:packed});audits.push({name,oldBytes:oldChunks.get(name)?.length,newBytes:packed.length,decodedByteIdentical:true,predictor:filter});console.log(JSON.stringify(audits.at(-1)));}
for(const name of ['baseKfs2Gzip','residualGzip','normalOctGzip','textureUvGzip'])addCompressed(name,zlib.gunzipSync(oldChunks.get(name)));
for(const name of ['weightsGzip','partInfoGzip','partRootGzip']){const original=zlib.gunzipSync(oldChunks.get(name)),delta=zlib.gunzipSync(oldChunks.get('continuous'+name[0].toUpperCase()+name.slice(1)));if(original.length!==delta.length)throw Error('Binding delta length mismatch');for(let i=0;i<original.length;i++)original[i]^=delta[i];addCompressed(name,original);}
const normal=oldChunks.get('normalPng'),webp=await sharp(normal).webp({lossless:true,effort:6}).toBuffer(),pngPixels=await sharp(normal).ensureAlpha().raw().toBuffer(),webpPixels=await sharp(webp).ensureAlpha().raw().toBuffer();if(!pngPixels.equals(webpPixels))throw Error('Normal atlas decoded pixels changed');console.log(JSON.stringify({normalPngBytes:normal.length,normalWebpBytes:webp.length,pixelsIdentical:true}));
for(const [name,bytes] of [['baseColorJpeg',oldChunks.get('baseColorJpeg')],['normalWebp',webp],['roughMetalJpeg',oldChunks.get('roughMetalJpeg')]])outputChunks.push({name,bytes:bytes.length,payload:bytes});
meta.schema='kaopu.fish.lean-runtime/10';meta.version='R10';meta.instrument={id:'kaopu.fish.lean-runtime',version:'10.0.0',abi:'KFC10'};
meta.runtimeOptimization={sourceR09Sha256:hash(source),lossless:true,sourceSamplesUnchanged:true,normalPixelsSha256:hash(pngPixels),removed:['Unused legacy bindingGzip','Legacy source binding copies and XOR deltas resolved offline','Embedded herring teaching workbench','CPU static surface copies after GPU upload'],singleView:'Only visible actor advances/uploads; resume school retains independent clocks'};
let offset=0;meta.package={...meta.package,normalMime:'image/webp',chunks:outputChunks.map(({payload,...c})=>{const result={...c,offset};offset+=c.bytes;return result;})};
const json=Buffer.from(JSON.stringify(meta)),header=Buffer.alloc(16);header.write('KFS10PK1');header.writeUInt32LE(json.length,8);header.writeUInt32LE(offset,12);const score=Buffer.concat([header,json,...outputChunks.map(c=>c.payload)]);fs.writeFileSync(path.join(cache,'MUSKELLUNGE_LEAN_R10.kfc10'),score);
const alphabet=Array.from({length:94},(_,i)=>String.fromCharCode(33+i)).filter(c=>!['<','>','&',"'",'"','`','\\'].includes(c)).slice(0,85).join('');
function encode(bytes){const chunks=[];let block='';for(let i=0;i<bytes.length;i+=4){let v=(bytes[i]||0)*16777216+(bytes[i+1]||0)*65536+(bytes[i+2]||0)*256+(bytes[i+3]||0),s='';for(let k=0;k<5;k++){s=alphabet[v%85]+s;v=Math.floor(v/85);}block+=s;if(block.length>=65535){chunks.push(block);block='';}}chunks.push(block);return chunks.join('');}
const encoded=encode(score),round=Buffer.alloc(score.length),map=new Map(Array.from(alphabet,(c,i)=>[c,i]));let pos=0;for(let i=0;i<encoded.length;i+=5){let value=0;for(let k=0;k<5;k++)value=value*85+map.get(encoded[i+k]);for(let k=3;k>=0;k--){if(pos+k<round.length)round[pos+k]=value%256;value=Math.floor(value/256);}pos+=4;}if(!round.equals(score))throw Error('HTML carrier changed score');
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('src/workbench.template.html').replace('__SCORE_BYTES__',String(score.length)).replace('__SCORE_85__',()=>encoded).replace('__KFC10_INSTRUMENT__',()=>read('src/instrument.js')).replace('__SCHOOL_RUNTIME__',()=>read('src/school.js')).replace('__KFC10_APP__',()=>read('src/app.js').replace('__DATA_ALPHABET__',alphabet));if(/__(?:KFC|SCORE|DATA|HERRING|SCHOOL)/.test(html))throw Error('Unresolved runtime marker');
const filename='KAOPU_FISH_LEAN_R10.html';fs.writeFileSync(path.join(root,'dist',filename),html);
const receipt={builtAt:new Date().toISOString(),taskId:'FISH_R10_LEAN_RUNTIME_20261001',sourceR09ScoreSha256:hash(source),scoreSha256:hash(score),scoreBytes:score.length,output:filename,htmlSha256:hash(Buffer.from(html)),htmlBytes:Buffer.byteLength(html),baselineHtmlBytes:fs.statSync(path.join(root,'../local-r09/dist/KAOPU_FISH_PARAMETRIC_SCHOOL_R09_WORKBENCH.html')).size,normal:{oldBytes:normal.length,newBytes:webp.length,decodedPixelsIdentical:true,pixelSha256:hash(pngPixels)},chunks:audits,carrierRoundTripIdentical:true,allCoreResourcesInline:true,vertices:497701,triangles:964285,schoolCount:15,visualAcceptance:false,motionAcceptance:false,productionReady:false};fs.writeFileSync(path.join(root,'evidence/BUILD_RECEIPT.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
