'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),https=require('https'),assert=require('assert/strict');
const {chromium}=require('playwright');
const html=path.resolve(process.env.HAIYU_HTML||'kaopu-haiyu-workbench/r24/index.html'),url=process.env.HAIYU_PUBLIC_URL||'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/r24/',out=path.resolve(process.env.HAIYU_QA_OUT||'haiyu-r24-browser-results');fs.mkdirSync(out,{recursive:true});
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),expected=hash(fs.readFileSync(html));const report={commit:process.env.GITHUB_SHA,expectedSha256:expected,renderer:'Official Playwright Chromium / SwiftShader software WebGL',physicalGPU:false,physicalMobileDevice:false,public:{},checks:[],errors:[]};const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
const get=u=>new Promise((resolve,reject)=>{const q=https.get(u,r=>{const b=[];r.on('data',x=>b.push(x));r.on('end',()=>resolve({status:r.statusCode,body:Buffer.concat(b)}))});q.setTimeout(45000,()=>q.destroy(Error('timeout')));q.on('error',reject)});
const cHash=async(p,id='#phaseCanvas')=>hash(await p.locator(id).evaluate(c=>(c.tagName==='IFRAME'?c.contentDocument.querySelector('canvas'):c).toDataURL()));
async function seek(p,f){await p.locator('#phaseTime').fill(String(f));await p.waitForFunction(f=>document.querySelector('#sourceSpace').dataset.frame===String(f)&&document.querySelector('#sourceSpace').dataset.referenceFrame===String(f),f)}
async function drawWait(p,fn){const n=Number(await p.locator('#sourceSpace').getAttribute('data-render-count'));await fn();await p.waitForFunction(n=>Number(document.querySelector('#sourceSpace').dataset.renderCount)>n,n)}
(async()=>{let browser;try{const deadline=Date.now()+12*60e3;let response;while(Date.now()<deadline){response=await get(url);if(response.status===200&&hash(response.body)===expected)break;console.log('Waiting exact Pages',response.status);await new Promise(r=>setTimeout(r,15000))}assert.equal(response.status,200);assert.equal(hash(response.body),expected);report.public={url,status:200,bytes:response.body.length,sha256:expected};save();browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
for(const mode of ['file','public']){const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1}),p=await ctx.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push(r.url()));const base=mode==='file'?'file://'+html:url;await p.goto(base,{waitUntil:'load'});await p.waitForFunction(()=>document.body.dataset.pending==='0');assert.equal(await p.locator('meta[name="haiyu-build"]').getAttribute('content'),'R24-source-volume-study-20261004');
const basicURL='https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/baselines/r23/';assert.equal(await p.getByRole('link',{name:'基础版',exact:true}).getAttribute('href'),basicURL);
if(mode==='public'){
 const basicResponse=await get(basicURL);assert.equal(basicResponse.status,200);assert.equal(hash(basicResponse.body),'cc1f02ad80bd86251fdbdfa769ae1e2db02af07c1b48ed7bafdc08eaedd3d2f4');
 const basic=await ctx.newPage();await basic.goto(basicURL,{waitUntil:'load'});await basic.waitForFunction(()=>document.body.dataset.pending==='0');assert.equal(await basic.locator('meta[name="haiyu-build"]').getAttribute('content'),'R23-compact-teacher-study-20261004');for(const s of[4,5,9,12])assert.equal(await basic.getByRole('navigation',{name:'二维原式',exact:true}).locator(`button[data-stage="${s}"]`).count(),1);await basic.locator('button[data-stage="4"]').click();await basic.waitForFunction(()=>document.body.dataset.pending==='0'&&document.body.dataset.stage==='4');assert.ok(await basic.frameLocator('#live').locator('canvas').count());await basic.screenshot({path:path.join(out,'public-basic-r23.png')});await basic.close();
 report.checks.push({mode,basicVersion:{url:basicURL,status:200,bytes:basicResponse.body.length,sha256:hash(basicResponse.body),originalR23Unchanged:true,actualSourceRenders:true}});save();
}
assert.equal(await p.locator('#axisLift').count(),0);assert.equal(await p.locator('button[data-module="thorax04"],button[data-module="thorax05"]').count(),0);for(const s of[4,5,9,12])assert.equal(await p.getByRole('navigation',{name:'二维原式',exact:true}).locator(`button[data-stage="${s}"]`).count(),1);
async function testOriginalFidelity(){
const baselineURL=mode==='file'?'file://'+path.resolve('kaopu-haiyu-workbench/baselines/r18/index.html'):'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/baselines/r18/';
for(const stage of[4,5]){
 const baseline=await ctx.newPage();await baseline.goto(baselineURL+'?stage='+stage+'&frame=1');await p.goto(base+'?stage='+stage+'&frame=1');const comparisons=[];
 for(const f of[1,60,120,240]){
  for(const page of[p,baseline]){await page.waitForFunction(()=>document.body.dataset.pending==='0');await page.locator('#timeline').fill(String(f));await page.waitForFunction(f=>document.body.dataset.pending==='0'&&document.body.dataset.frame===String(f)&&document.querySelector('#live').contentDocument.body.dataset.sourceFrame===String(f),f);}
  const actual=await cHash(p,'#live'),reference=await cHash(baseline,'#live'),meta=await Promise.all([p,baseline].map(page=>page.frameLocator('#live').locator('canvas').evaluate(c=>({width:c.width,height:c.height,frame:document.body.dataset.sourceFrame,time:document.body.dataset.time}))));comparisons.push({frame:f,actual,reference,meta});
  if(actual!==reference){await p.frameLocator('#live').locator('canvas').screenshot({path:path.join(out,`${mode}-original${stage}-frame${f}-actual.png`)});await baseline.frameLocator('#live').locator('canvas').screenshot({path:path.join(out,`${mode}-original${stage}-frame${f}-reference.png`)});report.checks.push({mode,original:stage,comparisons});save();}assert.equal(actual,reference);
 }
 report.checks.push({mode,original:stage,comparisons,exactPixelMatch:true});await baseline.close();
}
}
for(const s of[9,12]){await p.locator(`button[data-stage="${s}"]`).click();await p.waitForFunction(()=>document.body.dataset.pending==='0');const f=s===9?120:480;await p.locator('#timeline').fill(String(f));await p.waitForFunction(f=>document.body.dataset.pending==='0'&&document.body.dataset.frame===String(f),f);assert.ok(Math.abs(Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'))-Math.PI)<1e-10);}
const depthFixture=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;const r=window.HaiyuVolumeRenderer.create(c),positions=[[-20,-20,-5],[20,-20,-5],[0,20,-5],[-20,-20,5],[20,-20,5],[0,20,5]],o={rotate:p=>p,zoom:1,perspective:false,lit:true,pointSize:1,cloud:false,body:true,spine:true,cut:false,sections:false};function sample(reverse){const faces=reverse?[[3,4,5],[0,1,2]]:[[0,1,2],[3,4,5]],faceKinds=reverse?['axis','rib']:['rib','axis'];r.draw({positions,faces,faceKinds,cloud:positions,rings:[]},o);const b=new Uint8Array(4);r.gl.readPixels(32,32,1,1,r.gl.RGBA,r.gl.UNSIGNED_BYTE,b);return Array.from(b)}return{normal:sample(false),reversed:sample(true),error:r.gl.getError()}});assert.deepEqual(depthFixture.normal,depthFixture.reversed);assert.ok(depthFixture.normal[0]>240&&depthFixture.normal[1]<90);assert.equal(depthFixture.error,0);report.checks.push({mode,depthOrderFixture:depthFixture});
const spatial=[...await p.locator('nav[aria-label="三维学习区"] button[data-module]').evaluateAll(bs=>bs.map(b=>({stage:Number(b.dataset.stage),module:b.dataset.module})))];
for(const {stage,module} of spatial){await p.locator(`button[data-stage="${stage}"]`).click();await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame);const source=Number(await p.locator('#sourceSpace').getAttribute('data-source'));await seek(p,120);const result=await p.evaluate(()=>{const v=window.HaiyuSourceSpace.getPacket(),r=window.HaiyuVolumeStudy.validate(v,true),c=document.querySelector('#phaseCanvas'),gl=c.getContext('webgl'),b=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,b);let visible=0,pink=0;for(let i=0;i<b.length;i+=4){if(b[i]+b[i+1]+b[i+2]>100)visible++;if(b[i]>120&&b[i]>b[i+1]*1.5&&b[i+2]>b[i+1])pink++;}return {validation:r,stats:v.stats,visible,pink,depth:gl.isEnabled(gl.DEPTH_TEST),glError:gl.getError(),source:window.HaiyuSourceSpace.getState().source};});assert.equal(result.validation.ok,true,JSON.stringify(result.validation));assert.equal(result.depth,true);assert.equal(result.glError,0);assert.ok(result.visible>1000);assert.ok(result.pink>5,JSON.stringify(result));
await p.locator('#phaseCanvas').screenshot({path:path.join(out,`${mode}-source${source}-oblique.png`)});const lit=await cHash(p);await drawWait(p,()=>p.locator('#phaseLight').click());assert.notEqual(await cHash(p),lit);await p.locator('#phaseCanvas').screenshot({path:path.join(out,`${mode}-source${source}-neutral.png`)});await drawWait(p,()=>p.locator('#phaseLight').click());assert.equal(await cHash(p),lit);
for(const view of['phaseView','phaseSide','phaseFront','phaseBack']){await drawWait(p,()=>p.locator('#'+view).click());await p.locator('#phaseCanvas').screenshot({path:path.join(out,`${mode}-source${source}-${view}.png`)})}await drawWait(p,()=>p.locator('#phaseOrbit').click());await drawWait(p,()=>p.locator('#phaseCut').click());await p.locator('#phaseCanvas').screenshot({path:path.join(out,`${mode}-source${source}-cut.png`)});await drawWait(p,()=>p.locator('#phaseCut').click());await drawWait(p,()=>p.locator('#phaseSections').click());await p.locator('#phaseCanvas').screenshot({path:path.join(out,`${mode}-source${source}-sections.png`)});await p.locator('#phaseSliceCanvas').screenshot({path:path.join(out,`${mode}-source${source}-true-section.png`)});const slice=await cHash(p,'#phaseSliceCanvas');await drawWait(p,()=>p.locator('#phaseSlicePosition').fill('70'));assert.notEqual(await cHash(p,'#phaseSliceCanvas'),slice);await drawWait(p,()=>p.locator('#phaseSlicePosition').fill('50'));await drawWait(p,()=>p.locator('#phaseSections').click());
const ref=hash(await p.frameLocator('#phaseReference').locator('canvas').evaluate(c=>(c.tagName==='IFRAME'?c.contentDocument.querySelector('canvas'):c).toDataURL()));const before=await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().cloud.positions)));const box=await p.locator('#phaseCanvas').boundingBox();await p.mouse.move(box.x+100,box.y+100);await p.mouse.down();await p.mouse.move(box.x+240,box.y+160,{steps:8});await p.mouse.up();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().cloud.positions))),before);const frame=await p.locator('#sourceSpace').getAttribute('data-frame'),still=await cHash(p);await p.locator('#phaseSpin').click();await p.waitForTimeout(600);await p.locator('#phaseSpin').click();assert.notEqual(await cHash(p),still);assert.equal(await p.locator('#sourceSpace').getAttribute('data-frame'),frame);
await p.locator('#phasePlay').click();await p.waitForTimeout(900);await p.locator('#phasePlay').click();assert.ok(Number(await p.locator('#sourceSpace').getAttribute('data-frame'))>Number(frame));await p.waitForTimeout(100);const stopped=await cHash(p);await p.waitForTimeout(250);assert.equal(await cHash(p),stopped);await seek(p,120);const high=await cHash(p);await p.getByText('厚度与显示',{exact:true}).click();const originalCloud=await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().cloud.positions))),originalShellXY=await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().shell.positions).filter((v,i)=>i%3!==2))),archBefore=await cHash(p);await drawWait(p,()=>p.locator('#phaseOpening').fill('100'));assert.notEqual(await cHash(p),archBefore);assert.equal(await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().shell.positions).filter((v,i)=>i%3!==2))),originalShellXY);assert.equal(await p.evaluate(()=>JSON.stringify(Array.from(window.HaiyuSourceSpace.getPacket().cloud.positions))),originalCloud);await drawWait(p,()=>p.locator('#phaseOpening').fill('65'));await drawWait(p,()=>p.locator('#phaseDepth').fill('25'));assert.notEqual(await cHash(p),high);assert.equal(await p.evaluate(()=>window.HaiyuVolumeStudy.validate(window.HaiyuSourceSpace.getPacket(),true).ok),true);await drawWait(p,()=>p.locator('#phaseDepth').fill('100'));await p.getByText('厚度与显示',{exact:true}).click();
const teacher=source===6?9:source===7?12:source;await p.locator(`button[data-stage="${teacher}"]`).click();await p.waitForFunction(()=>document.body.dataset.pending==='0');await p.locator('#timeline').fill('120');await p.waitForFunction(()=>document.body.dataset.pending==='0'&&document.body.dataset.frame==='120');assert.equal(hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>(c.tagName==='IFRAME'?c.contentDocument.querySelector('canvas'):c).toDataURL())),ref);await p.locator(`button[data-stage="${stage}"]`).click();await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame);
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));const cb=await p.locator('#phaseCanvas').boundingBox();assert.ok(cb.x<=8&&cb.width>=374,JSON.stringify(cb));assert.ok(cb.y<300,JSON.stringify(cb));assert.ok((await p.locator('#phaseSpin').boundingBox()).y<cb.y);await p.screenshot({path:path.join(out,`${mode}-source${source}-phone.png`)});await p.setViewportSize({width:1440,height:1000});report.checks.push({mode,stage,source,module,...result,exactReferencePixels:true,actualLighting:true,manualAndAutoOrbit:true,sourcePlayPause:true,depthControl:true,phoneWidth:cb.width});save();}
for(const s of[1,7,8]){await p.locator(`button[data-stage="${s}"]`).click();if(s===1)await p.waitForFunction(()=>document.body.dataset.pending==='0');else{await p.locator('#expLight').waitFor({state:'visible'});await p.locator('#expTime').fill('0');await p.waitForTimeout(250);const h=await cHash(p,'#expCanvas');await p.locator('#expLight').click();await p.waitForTimeout(150);assert.notEqual(await cHash(p,'#expCanvas'),h);await p.locator('#expLight').click();const timeBefore=await p.locator('#experiment').getAttribute('data-time');await p.locator('#expSideView').click();await p.waitForTimeout(200);const side=await cHash(p,'#expCanvas');assert.notEqual(side,h);await p.locator('#expSpin').click();await p.waitForTimeout(600);await p.locator('#expManual').click();assert.notEqual(await cHash(p,'#expCanvas'),side);assert.equal(await p.locator('#experiment').getAttribute('data-time'),timeBefore);assert.equal(await p.evaluate(()=>window.HaiyuLegacyObservation.getState().spinning),false);await p.locator('#expZoomIn').click();await p.locator('#expFrontView').click();await p.screenshot({path:path.join(out,`${mode}-legacy${s}-camera-controls.png`)});report.checks.push({mode,legacy:s,externalCameraControls:true,autoCameraPreservesTime:true});}}
await testOriginalFidelity();await p.goto(base+'?stage=4&frame=120');await p.waitForFunction(()=>document.body.dataset.pending==='0'&&document.body.dataset.frame==='120');await p.goto(base+'?module=source07space&frame=480');await p.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.source==='7'&&document.querySelector('#sourceSpace').dataset.referenceFrame==='480');if(mode==='file'){const downloadPromise=p.waitForEvent('download');await p.locator('#saveHtml').click();const download=await downloadPromise,saved=path.join(out,'saved-workbench.html');await download.saveAs(saved);const reopened=await ctx.newPage();reopened.on('pageerror',e=>errors.push(e.message));await reopened.goto('file://'+saved);await reopened.waitForFunction(()=>document.body.dataset.pending==='0');assert.equal(await reopened.locator('#expCameraTools').count(),1);await reopened.locator('button[data-stage="13"]').click();await reopened.waitForFunction(()=>document.querySelector('#sourceSpace').dataset.referenceFrame);assert.equal(await reopened.locator('#sourceSpace').getAttribute('data-gl-error'),'0');await reopened.close();fs.unlinkSync(saved);report.checks.push({mode,downloadedStandaloneReopens:true,singleGeneratedToolbar:true});} if(mode==='file')assert.deepEqual(requests.filter(u=>/^https?:/.test(u)),[]);assert.deepEqual(errors,[]);report.checks.push({mode,pageErrors:errors,oldFailedEntryRemoved:true,originalsIndependent:true});await ctx.close();save();}
report.status='PASS';report.scope='Actual source-preserving volume candidate, contained colored learning axis, 2D originals pixel regression, real WebGL and camera/light controls; inferred volumes, not recovered species anatomy';save();console.log(JSON.stringify(report,null,2));
}catch(e){report.status='FAIL';report.errors.push(e.stack||String(e));save();console.error(e);process.exitCode=1}finally{if(browser)await browser.close()}})();
