/* Original KAOPU r04 position-based thick-curve contact kernel.
 * Spatially continuous segment capsules, discrete simulation time (not temporal CCD).
 * No third-party runtime code. Body collider is injected from the shared body mesh. */
(function(root){'use strict';const C=root.AnemoneCore||(typeof require==='function'?require('./anemone-core.js'):null);
const SKIN=.003, EPS=1e-8;
function legalRoots(state){const rs=C.roots(state),N=rs.length,rot=(state.seed*.618033988749895%1)*Math.PI*2;
 for(let i=0;i<N;i++){const a=i*2.399963229728653+rot,f=Math.max(.095,Math.sqrt(.003+(i+.5)/N*.997)),r=C.discRadius(a)*Math.min(.984,f);rs[i].x=Math.cos(a)*r;rs[i].z=Math.sin(a)*r;}
 let min=Infinity,iterations=0;
 for(;iterations<180;iterations++){let largest=0;for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const a=rs[i],b=rs[j],dx=a.x-b.x,dz=a.z-b.z,d=Math.hypot(dx,dz),goal=a.radius+b.radius+SKIN+.0003;if(d<goal){const correction=(goal-d)*.52/Math.max(d,EPS);a.x+=dx*correction;a.z+=dz*correction;b.x-=dx*correction;b.z-=dz*correction;largest=Math.max(largest,goal-d);}}
  for(const a of rs){const angle=Math.atan2(a.z,a.x),r=Math.hypot(a.x,a.z),lo=.04+a.radius+.012,hi=C.discRadius(angle)*.984,cl=C.clamp(r,lo,hi);a.x*=cl/r;a.z*=cl/r;}
  if(largest<.00005)break;
 }
 for(let i=0;i<N;i++)for(let j=i+1;j<N;j++)min=Math.min(min,Math.hypot(rs[i].x-rs[j].x,rs[i].z-rs[j].z)-rs[i].radius-rs[j].radius);
 if(min<SKIN-.0001)throw Object.assign(Error('此数量与粗度组合未能保持根部间距；请减少数量或粗度。原合法状态保持不变。'),{code:'ROOT_LAYOUT_INFEASIBLE',minClearance:min,iterations});
 for(const a of rs){const attachment=C.discAttachmentInfo(a.x,a.z);a.y=attachment.height;a.normal=attachment.normal;a.a=Math.atan2(a.z,a.x);a.r=Math.hypot(a.x,a.z);a.heading=Math.atan2(.5*Math.sin(a.a)+.75*Math.sin(2.6*a.x+1.7*a.z+.4),.5*Math.cos(a.a)+.75*Math.cos(2.6*a.x-1.8*a.z));}
 return {roots:rs,minClearance:min,iterations};
}
// Closest points of two full finite segments; result storage is caller-owned.
function closest(p,a,b,c,d,out){const ux=p[b]-p[a],uy=p[b+1]-p[a+1],uz=p[b+2]-p[a+2],vx=p[d]-p[c],vy=p[d+1]-p[c+1],vz=p[d+2]-p[c+2],wx=p[a]-p[c],wy=p[a+1]-p[c+1],wz=p[a+2]-p[c+2];const aa=ux*ux+uy*uy+uz*uz,bb=ux*vx+uy*vy+uz*vz,cc=vx*vx+vy*vy+vz*vz,dd=ux*wx+uy*wy+uz*wz,ee=vx*wx+vy*wy+vz*wz,den=aa*cc-bb*bb;let s=0,t=0;
 if(aa<1e-20&&cc<1e-20){}else if(aa<1e-20)t=C.clamp(ee/cc,0,1);else if(cc<1e-20)s=C.clamp(-dd/aa,0,1);else{s=den>aa*cc*1e-12?C.clamp((bb*ee-cc*dd)/den,0,1):0;t=(bb*s+ee)/cc;if(t<0){t=0;s=C.clamp(-dd/aa,0,1);}else if(t>1){t=1;s=C.clamp((bb-dd)/aa,0,1);}}
 const x=wx+s*ux-t*vx,y=wy+s*uy-t*vy,z=wz+s*uz-t*vz;out.s=s;out.t=t;out.x=x;out.y=y;out.z=z;out.distance=Math.hypot(x,y,z);out.ux=ux;out.uy=uy;out.uz=uz;out.vx=vx;out.vy=vy;out.vz=vz;return out;
}
class ContactSystem{
 constructor(state,{body=null}={}){this.state={...state};const layout=legalRoots(state);this.roots=layout.roots;this.rootLayout=layout;this.S=C.SEGMENTS;this.N=this.roots.length*(this.S+1);this.M=this.roots.length*this.S;this.positions=new Float64Array(this.N*3);this.previous=new Float64Array(this.N*3);this.target=new Float64Array(this.N*3);this.inverseMass=new Float64Array(this.N).fill(1);this.radius=new Float64Array(this.M);this.segmentA=new Int32Array(this.M);this.segmentB=new Int32Array(this.M);this.chain=new Int32Array(this.M);this.local=new Int32Array(this.M);this.restLength=new Float64Array(this.M);this.body=body;this.cellSize=.12;this.buckets=new Map();this.activeBuckets=[];this.seen=new Int32Array(this.M);this.gridBounds=new Int32Array(this.M*6);this.segmentBounds=new Float64Array(this.M*6);this.closest={};this.nx=new Float64Array(this.S);this.ny=new Float64Array(this.S);this.nz=new Float64Array(this.S);this.diagonal=new Float64Array(this.S);this.rhs=new Float64Array(this.S);this.off=new Float64Array(this.S);this.lambda=new Float64Array(this.S);this.time=0;this.steps=0;this.fallbacks=0;this.solverLimited=false;this.lastSolveMs=0;this.proposalScale=1;this.failedAttempts=0;this.lastDt=1/30;this.contactList=[];this.contactAnchor=null;this.contactBuffer=.012;const makeScratch=()=>({gradient:new Float64Array((this.S+1)*3),out:new Float64Array((this.S+1)*3),normal:new Float64Array(this.S*3),diag:new Float64Array(this.S),rhs:new Float64Array(this.S),off:new Float64Array(this.S),solution:new Float64Array(this.S)});this.scratchA=makeScratch();this.scratchB=makeScratch();
  for(let i=0;i<this.roots.length;i++){const r=this.roots[i],step=r.length/this.S;for(let j=0;j<=this.S;j++){const node=i*(this.S+1)+j,k=node*3;this.positions[k]=r.x;this.positions[k+1]=r.y+j*step;this.positions[k+2]=r.z;if(!j)this.inverseMass[node]=0;if(j<this.S){const q=i*this.S+j;this.segmentA[q]=node;this.segmentB[q]=node+1;this.radius[q]=r.radius;this.chain[q]=i;this.local[q]=j;this.restLength[q]=step;}}}
  this.previous.set(this.positions);this.target.set(this.positions);this.initial=this.positions.slice();this.lastValid=this.positions.slice();this.updateTarget(0);this.metricsLast=this.measure();
 }
 updateTarget(time){const data=C.solve(this.state,this.roots,time);for(let i=0;i<this.N;i++){this.target[i*3]=data[i*4];this.target[i*3+1]=data[i*4+1];this.target[i*3+2]=data[i*4+2];}}
 localExcluded(i,j){if(this.chain[i]!==this.chain[j])return false;const gap=Math.max(0,Math.abs(this.local[i]-this.local[j])-1)*this.restLength[i];return gap<=this.radius[i]+this.radius[j]+SKIN;}
 buildHash(extra=0){for(const b of this.activeBuckets)b.length=0;this.activeBuckets.length=0;const p=this.positions,g=this.gridBounds,B=this.segmentBounds,h=this.cellSize;for(let i=0;i<this.M;i++){const a=this.segmentA[i]*3,b=this.segmentB[i]*3,r=this.radius[i]+(SKIN+extra)*.5,k=i*6;for(let axis=0;axis<3;axis++){B[k+axis*2]=Math.min(p[a+axis],p[b+axis]);B[k+axis*2+1]=Math.max(p[a+axis],p[b+axis]);g[k+axis*2]=Math.floor((B[k+axis*2]-r)/h);g[k+axis*2+1]=Math.floor((B[k+axis*2+1]+r)/h);}for(let x=g[k];x<=g[k+1];x++)for(let y=g[k+2];y<=g[k+3];y++)for(let z=g[k+4];z<=g[k+5];z++){const key=(x+64)+(y+64)*128+(z+64)*16384;let bucket=this.buckets.get(key);if(!bucket){bucket=[];this.buckets.set(key,bucket);}if(!bucket.length)this.activeBuckets.push(bucket);bucket.push(i);}}}
 pairs(callback,extra=0){this.buildHash(extra);this.seen.fill(-1);const g=this.gridBounds,B=this.segmentBounds;let checked=0,excluded=0,aabbRejected=0;for(let i=0;i<this.M;i++){const k=i*6;for(let x=g[k];x<=g[k+1];x++)for(let y=g[k+2];y<=g[k+3];y++)for(let z=g[k+4];z<=g[k+5];z++){const arr=this.buckets.get((x+64)+(y+64)*128+(z+64)*16384);if(!arr)continue;for(const j of arr){if(j<=i||this.seen[j]===i)continue;this.seen[j]=i;if(this.localExcluded(i,j)){excluded++;continue;}const q=j*6,dx=Math.max(0,B[k]-B[q+1],B[q]-B[k+1]),dy=Math.max(0,B[k+2]-B[q+3],B[q+2]-B[k+3]),dz=Math.max(0,B[k+4]-B[q+5],B[q+4]-B[k+5]),radius=this.radius[i]+this.radius[j]+SKIN+extra;if(dx*dx+dy*dy+dz*dz>radius*radius){aabbRejected++;continue;}checked++;callback(i,j);}}}return {checked,excluded,aabbRejected};}
 projectLengths(){const p=this.positions,N=this.S,nx=this.nx,ny=this.ny,nz=this.nz,D=this.diagonal,B=this.rhs,U=this.off,L=this.lambda;for(let iteration=0;iteration<2;iteration++)for(let chain=0;chain<this.roots.length;chain++){const r=this.roots[chain],l=r.length/N,base=chain*(N+1);for(let j=0;j<N;j++){const a=(base+j)*3,b=a+3,x=p[b]-p[a],y=p[b+1]-p[a+1],z=p[b+2]-p[a+2],d=Math.max(EPS,Math.hypot(x,y,z));nx[j]=x/d;ny[j]=y/d;nz[j]=z/d;D[j]=this.inverseMass[base+j]+this.inverseMass[base+j+1];B[j]=l-d;if(j){const off=-this.inverseMass[base+j]*(nx[j-1]*nx[j]+ny[j-1]*ny[j]+nz[j-1]*nz[j]);U[j-1]=off;const q=off/D[j-1];D[j]-=q*off;B[j]-=q*B[j-1];}}L[N-1]=B[N-1]/D[N-1];for(let j=N-2;j>=0;j--)L[j]=(B[j]-U[j]*L[j+1])/D[j];for(let j=1;j<=N;j++){const k=(base+j)*3,w=this.inverseMass[base+j];p[k]+=w*(nx[j-1]*L[j-1]-(j<N?nx[j]*L[j]:0));p[k+1]+=w*(ny[j-1]*L[j-1]-(j<N?ny[j]*L[j]:0));p[k+2]+=w*(nz[j-1]*L[j-1]-(j<N?nz[j]*L[j]:0));}}}
 projectBends(){const p=this.positions,m=this.inverseMass;for(let chain=0;chain<this.roots.length;chain++){const r=this.roots[chain],l=r.length/this.S,cosLimit=1-2*Math.min(.95,l/(4*r.radius))**2;for(let j=0;j<this.S-1;j++){const ia=chain*(this.S+1)+j,ib=ia+1,ic=ia+2,a=ia*3,b=ib*3,c=ic*3;let ux=p[b]-p[a],uy=p[b+1]-p[a+1],uz=p[b+2]-p[a+2],vx=p[c]-p[b],vy=p[c+1]-p[b+1],vz=p[c+2]-p[b+2],al=Math.max(EPS,Math.hypot(ux,uy,uz)),bl=Math.max(EPS,Math.hypot(vx,vy,vz));ux/=al;uy/=al;uz/=al;vx/=bl;vy/=bl;vz/=bl;const dot=ux*vx+uy*vy+uz*vz,Cv=dot-cosLimit;if(Cv>=0)continue;const ax=-(vx-dot*ux)/al,ay=-(vy-dot*uy)/al,az=-(vz-dot*uz)/al,cx=(ux-dot*vx)/bl,cy=(uy-dot*vy)/bl,cz=(uz-dot*vz)/bl,bx=-ax-cx,by=-ay-cy,bz=-az-cz,den=m[ia]*(ax*ax+ay*ay+az*az)+m[ib]*(bx*bx+by*by+bz*bz)+m[ic]*(cx*cx+cy*cy+cz*cz);if(den<EPS)continue;const scratch=this.scratchA;scratch.gradient.fill(0);for(const [idx,x,y,z]of [[ia,ax,ay,az],[ib,bx,by,bz],[ic,cx,cy,cz]]){const k=(idx-chain*(this.S+1))*3;scratch.gradient[k]=x;scratch.gradient[k+1]=y;scratch.gradient[k+2]=z;}const projected=this.tangentProjection(chain,scratch);if(projected.den<1e-12)continue;const correction=Math.min(-Cv/projected.den,.003/Math.max(EPS,projected.max)),base=chain*(this.S+1)*3;for(let k=0;k<scratch.out.length;k++)p[base+k]+=scratch.out[k]*correction;}}}
 ensureContactList(){const p=this.positions,threshold=this.contactBuffer*.24;let rebuild=!this.contactAnchor;if(!rebuild){const a=this.contactAnchor;for(let i=0;i<p.length;i+=3){const x=p[i]-a[i],y=p[i+1]-a[i+1],z=p[i+2]-a[i+2];if(x*x+y*y+z*z>threshold*threshold){rebuild=true;break;}}}if(rebuild){this.contactList.length=0;const q={};this.pairs((i,j)=>{closest(p,this.segmentA[i]*3,this.segmentB[i]*3,this.segmentA[j]*3,this.segmentB[j]*3,q);if(q.distance<this.radius[i]+this.radius[j]+SKIN+this.contactBuffer)this.contactList.push(i,j);},this.contactBuffer);this.contactAnchor=p.slice();}return this.contactList;}
 tangentProjection(chain,q){const p=this.positions,N=this.S,base=chain*(N+1),g=q.gradient,n=q.normal,D=q.diag,B=q.rhs,U=q.off,L=q.solution,out=q.out,m=this.inverseMass;for(let j=0;j<N;j++){const a=(base+j)*3,b=a+3,k=j*3,x=p[b]-p[a],y=p[b+1]-p[a+1],z=p[b+2]-p[a+2],len=Math.max(EPS,Math.hypot(x,y,z));n[k]=x/len;n[k+1]=y/len;n[k+2]=z/len;D[j]=m[base+j]+m[base+j+1];B[j]=n[k]*(g[k+3]*m[base+j+1]-g[k]*m[base+j])+n[k+1]*(g[k+4]*m[base+j+1]-g[k+1]*m[base+j])+n[k+2]*(g[k+5]*m[base+j+1]-g[k+2]*m[base+j]);if(j){const off=-m[base+j]*(n[k-3]*n[k]+n[k-2]*n[k+1]+n[k-1]*n[k+2]);U[j-1]=off;const f=off/D[j-1];D[j]-=f*off;B[j]-=f*B[j-1];}}L[N-1]=B[N-1]/D[N-1];for(let j=N-2;j>=0;j--)L[j]=(B[j]-U[j]*L[j+1])/D[j];let den=0,max=0;for(let j=0;j<=N;j++)for(let axis=0;axis<3;axis++){const k=j*3+axis,v=m[base+j]*(g[k]-(j?n[k-3]*L[j-1]:0)+(j<N?n[k]*L[j]:0));out[k]=v;den+=g[k]*v;max=Math.max(max,Math.abs(v));}return {den,max};}
 projectContacts(){const p=this.positions,m=this.inverseMass,o=this.closest,list=this.ensureContactList();for(let pair=0;pair<list.length;pair+=2){const i=list[pair],j=list[pair+1];const a=this.segmentA[i],b=this.segmentB[i],c=this.segmentA[j],d=this.segmentB[j];closest(p,a*3,b*3,c*3,d*3,o);const pen=this.radius[i]+this.radius[j]+SKIN-o.distance;if(pen<=0)continue;let x=o.x,y=o.y,z=o.z,n=o.distance;
  if(n<1e-8){x=o.uy*o.vz-o.uz*o.vy;y=o.uz*o.vx-o.ux*o.vz;z=o.ux*o.vy-o.uy*o.vx;n=Math.hypot(x,y,z);if(n<1e-8){x=o.uy; y=-o.ux;z=0;n=Math.hypot(x,y);if(n<1e-8){x=1;y=0;z=0;n=1;}}}
  x/=n;y/=n;z/=n;const ca=this.chain[i],cb=this.chain[j],qa=this.scratchA,qb=ca===cb?qa:this.scratchB;qa.gradient.fill(0);if(qb!==qa)qb.gradient.fill(0);const add=(q,chain,node,w)=>{const k=(node-chain*(this.S+1))*3;q.gradient[k]+=x*w;q.gradient[k+1]+=y*w;q.gradient[k+2]+=z*w;};add(qa,ca,a,1-o.s);add(qa,ca,b,o.s);add(qb,cb,c,-(1-o.t));add(qb,cb,d,-o.t);const pa=this.tangentProjection(ca,qa),pb=ca===cb?{den:0,max:0}:this.tangentProjection(cb,qb),den=pa.den+pb.den;if(den<1e-12)continue;let lambda=pen/den*.95;const max=Math.max(pa.max,pb.max);lambda=Math.min(lambda,.006/Math.max(EPS,max));for(const [chain,q]of (ca===cb?[[ca,qa]]:[[ca,qa],[cb,qb]])){const base=chain*(this.S+1)*3;for(let k=0;k<q.out.length;k++)p[base+k]+=q.out[k]*lambda;}
 }}
 projectCollars(){const p=this.positions,cosLimit=Math.cos(.61);for(let i=0;i<this.roots.length;i++){const r=this.roots[i],a=i*(this.S+1)*3,b=a+3,n=r.normal;let x=p[b]-r.x,y=p[b+1]-r.y,z=p[b+2]-r.z;const l=Math.max(EPS,Math.hypot(x,y,z));x/=l;y/=l;z/=l;const dot=x*n[0]+y*n[1]+z*n[2];if(dot<cosLimit){const gx=(n[0]-dot*x)/l,gy=(n[1]-dot*y)/l,gz=(n[2]-dot*z)/l,den=gx*gx+gy*gy+gz*gz,q=(cosLimit-dot)/Math.max(EPS,den);p[b]+=gx*q;p[b+1]+=gy*q;p[b+2]+=gz*q;}p[a]=r.x;p[a+1]=r.y;p[a+2]=r.z;}}
 measure({brute=false,skipContacts=false,skipBody=false}={}){const p=this.positions,o={},res={rootError:0,lengthRelative:0,arcRelative:0,maxPenetration:0,contactViolations:0,contactsChecked:!skipContacts,skinDeficit:0,bodyPenetration:0,bodyChecked:!!this.body&&!skipBody,bendViolation:0,collarViolation:0,targetRms:0,finite:true,rootMinClearance:this.rootLayout.minClearance};let target=0;
  for(let c=0;c<this.roots.length;c++){const r=this.roots[c],b=c*(this.S+1)*3,l=r.length/this.S;res.rootError=Math.max(res.rootError,Math.hypot(p[b]-r.x,p[b+1]-r.y,p[b+2]-r.z));const cv=[p[b+3]-p[b],p[b+4]-p[b+1],p[b+5]-p[b+2]],cn=Math.hypot(...cv);res.collarViolation=Math.max(res.collarViolation,Math.acos(C.clamp(cv.reduce((sum,v,k)=>sum+v*r.normal[k],0)/Math.max(EPS,cn),-1,1))-.61);let arc=0;for(let j=0;j<this.S;j++){const a=b+j*3,d=Math.hypot(p[a+3]-p[a],p[a+4]-p[a+1],p[a+5]-p[a+2]);arc+=d;res.lengthRelative=Math.max(res.lengthRelative,Math.abs(d-l)/l);if(j<this.S-1){const ux=p[a+3]-p[a],uy=p[a+4]-p[a+1],uz=p[a+5]-p[a+2],vx=p[a+6]-p[a+3],vy=p[a+7]-p[a+4],vz=p[a+8]-p[a+5],angle=Math.acos(C.clamp((ux*vx+uy*vy+uz*vz)/Math.max(EPS,Math.hypot(ux,uy,uz)*Math.hypot(vx,vy,vz)),-1,1)),allowed=2*Math.asin(Math.min(.95,l/(4*r.radius)));res.bendViolation=Math.max(res.bendViolation,angle-allowed);}}res.arcRelative=Math.max(res.arcRelative,Math.abs(arc-r.length)/r.length);}
  for(let i=0;i<p.length;i++){if(!Number.isFinite(p[i]))res.finite=false;target+=(p[i]-this.target[i])**2;}res.targetRms=Math.sqrt(target/this.N);
  const pair=(i,j)=>{closest(p,this.segmentA[i]*3,this.segmentB[i]*3,this.segmentA[j]*3,this.segmentB[j]*3,o);const pen=this.radius[i]+this.radius[j]-o.distance;res.maxPenetration=Math.max(res.maxPenetration,pen);res.skinDeficit=Math.max(res.skinDeficit,pen+SKIN);if(pen>Math.max(1e-5,.01*(this.radius[i]+this.radius[j])))res.contactViolations++;};
  if(skipContacts){res.maxPenetration=null;res.contactViolations=null;}else if(brute){for(let i=0;i<this.M;i++)for(let j=i+1;j<this.M;j++)if(!this.localExcluded(i,j))pair(i,j);}else Object.assign(res,this.pairs(pair));
  if(this.body&&!skipBody)Object.assign(res,this.body.measure(this));return res;
 }
 validShape(m){return m.finite&&m.rootError<1e-7&&m.lengthRelative<.002&&m.arcRelative<.001&&m.bodyPenetration<.00045&&m.bendViolation<.01&&m.collarViolation<.005;}
 valid(m){return this.validShape(m)&&(!this.body||m.bodyChecked)&&m.contactsChecked&&m.contactViolations===0&&m.maxPenetration<.00045;}
 step(dt=1/30,{maxSweeps=32,targetStrength=.035}={}){const start=performance.now(),old=this.positions.slice(),prev=this.previous,minimum=Math.min(...this.roots.map(x=>x.radius));this.updateTarget(this.time+dt);this.contactAnchor=null;let passed=false,metrics,sweeps=0,attempts=0;
  for(;attempts<4&&!passed;attempts++){const scale=this.proposalScale*Math.pow(.5,attempts);this.updateTarget(this.time+dt*scale);this.positions.set(old);for(let i=0;i<this.N;i++){if(!this.inverseMass[i])continue;const k=i*3;let x=((old[k]-prev[k])*.5*dt/this.lastDt+(this.target[k]-old[k])*targetStrength)*scale,y=((old[k+1]-prev[k+1])*.5*dt/this.lastDt+(this.target[k+1]-old[k+1])*targetStrength)*scale,z=((old[k+2]-prev[k+2])*.5*dt/this.lastDt+(this.target[k+2]-old[k+2])*targetStrength)*scale;const d=Math.hypot(x,y,z),q=Math.min(1,minimum*.2/Math.max(d,EPS));this.positions[k]+=x*q;this.positions[k+1]+=y*q;this.positions[k+2]+=z*q;}
   for(let it=0;it<maxSweeps;it++){this.projectBends();this.projectCollars();this.projectLengths();if(this.body)this.body.project(this);this.projectContacts();sweeps++;if(it===0||it%4===3||it===maxSweeps-1){metrics=this.measure({skipContacts:true,skipBody:true});if(this.validShape(metrics)){metrics=this.measure();if(this.valid(metrics)){passed=true;break;}}}}
  }
  const rejectedMetrics=passed?null:{...metrics};
  if(passed){this.previous.set(old);this.lastValid.set(this.positions);const acceptedScale=this.proposalScale*Math.pow(.5,Math.max(0,attempts-1));this.time+=dt*acceptedScale;this.lastDt=dt*acceptedScale;this.proposalScale=Math.min(1,acceptedScale*1.15);this.steps++;this.failedAttempts=0;this.solverLimited=acceptedScale<.25;}else{this.positions.set(old);this.previous.set(old);this.fallbacks++;this.failedAttempts++;this.proposalScale=Math.max(1/1024,this.proposalScale*.25);this.solverLimited=true;metrics=this.measure();}
  this.lastSolveMs=performance.now()-start;this.metricsLast={...metrics,sweeps,attempts,accepted:passed,rejectedMetrics,time:this.time,steps:this.steps,fallbacks:this.fallbacks,solverLimited:this.solverLimited,proposalScale:this.proposalScale,solveMs:this.lastSolveMs};return this.metricsLast;
 }
 displayData(out=new Float32Array(this.N*4)){for(let i=0;i<this.roots.length;i++){const r=this.roots[i];for(let j=0;j<=this.S;j++){const n=i*(this.S+1)+j,k=n*4;out[k]=this.positions[n*3];out[k+1]=this.positions[n*3+1];out[k+2]=this.positions[n*3+2];out[k+3]=j===this.S?r.length:r.radius;}}return out;}
}
const api={legalRoots,closest,ContactSystem,SKIN};root.AnemoneContact=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
