import fs from 'node:fs';import path from 'node:path';import {fileURLToPath}from'node:url';import {gunzipSync}from'node:zlib';import assert from'node:assert/strict';import{AnnyModel,rotationVectorDegrees}from'../src/AnnyModel.js';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),base=path.dirname(root),meta=JSON.parse(fs.readFileSync(base+'/assets/anny-model.json')),fm=JSON.parse(fs.readFileSync(root+'/assets/facial-actions.json'));
const ab=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),raw=gunzipSync(Buffer.concat(meta.binary.compressed.parts.map(p=>fs.readFileSync(base+'/'+p.url)))),fr=gunzipSync(fs.readFileSync(root+'/assets/facial-actions.bin.gz'));
const model=new AnnyModel(meta,ab(raw),fm,ab(fr)),fixtures=JSON.parse(fs.readFileSync(root+'/tests/official-r02.json')),gold=gunzipSync(Buffer.concat(fixtures.binaryParts.map(p=>fs.readFileSync(root+'/tests/'+p.file))));let max=0,rms=0,cases=[];
for(const f of fixtures.cases){const out=model.forward(f.inputs),stats={name:f.name};for(const key of ['vertices','bonePoses','restVertices','restBonePoses','coefficients']){const spec=f[key],target=new Float32Array(ab(gold),spec.byteOffset,spec.length),a=out[key];assert.equal(a.length,target.length);let m=0,q=0;for(let i=0;i<a.length;i++){assert.ok(Number.isFinite(a[i]));const d=a[i]-target[i];m=Math.max(m,Math.abs(d));q+=d*d;}assert.ok(m<2e-5,f.name+' '+key+' '+m);stats[key]={max:m,rms:Math.sqrt(q/a.length)};if(key==='vertices'){max=Math.max(max,m);rms=Math.max(rms,Math.sqrt(q/a.length));}}cases.push(stats);}
assert.equal(model.facialActionLabels.length,52);assert.deepEqual(model.forward({}).vertices,model.forward({facialActions:{jawOpen:0},pose:{head:[0,0,0]}}).vertices);assert.notDeepEqual(model.forward({facialActions:{jawOpen:1}}).vertices,model.forward({}).vertices);
const report={passed:true,sourceCommit:fm.sourceCommit,caseCount:cases.length,facialActionCount:52,poseProtocol:fixtures.protocol,maxVertexErrorMetres:max,worstRmsVertexErrorMetres:rms,baseTensorsUnchanged:fm.baseTensorsUnchangedProof,caseResults:cases};fs.writeFileSync(root+'/tests/parity-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,caseResults:undefined}));
const {parseProfile,workshopProfile,officialParameters,poseInput,bodyGLB}=await import('../src/profile.js');
const {AnnyModel:OldModel}=await import('../../src/AnnyModel.js');const old=new OldModel(meta,ab(raw));
const oldState={phenotypes:{age:.7,weight:.8},localChanges:{'measure-shoulder-dist-incr':.4},pose:{head:[20,30,40]}};
const migrated=parseProfile({schema:'kaopu-anny-profile/1',sourceCommit:fm.sourceCommit,modelHash:meta.binary.sha256,rig:'anny',topology:'anny',poseParameterization:'local-ref',eulerOrder:'RxRyRz',parameters:oldState},model,meta,fm).state;
const migratedOut=model.forward({...migrated,pose:poseInput(migrated)}).vertices,oldOut=old.forward(oldState).vertices;let migrationMax=0;for(let i=0;i<oldOut.length;i++)migrationMax=Math.max(migrationMax,Math.abs(oldOut[i]-migratedOut[i]));assert.ok(migrationMax<2e-6,'R01 migration changed geometry');
const s={phenotypes:{age:.6},localChanges:{},facialActions:{jawOpen:.7,mouthSmileLeft:.4},pose:{head:[20,30,40]},translations:{root:[.1,-.2,.3]}};const exportData=officialParameters(model,s),loaded=parseProfile(exportData,model,meta,fm).state;const a=model.forward({...s,pose:poseInput(s)}).vertices,b=model.forward({...loaded,pose:poseInput(loaded)}).vertices;let rtMax=0;for(let i=0;i<a.length;i++)rtMax=Math.max(rtMax,Math.abs(a[i]-b[i]));assert.ok(rtMax<2e-6,'Official JSON round trip changed geometry');const saved=parseProfile(workshopProfile(meta,fm,s),model,meta,fm).state;assert.deepEqual(saved,s);assert.throws(()=>parseProfile({...exportData,pose_parameterization:'world'},model,meta,fm));assert.throws(()=>parseProfile({...exportData,facial_actions:{fake:1}},model,meta,fm));
const normals=new Float32Array(a.length);for(let i=2;i<normals.length;i+=3)normals[i]=1;const glb=bodyGLB(a,normals,model.arrays.faces,exportData),dv=new DataView(glb.buffer);assert.equal(dv.getUint32(0,true),0x46546c67);assert.equal(dv.getUint32(8,true),glb.length);const gltf=JSON.parse(new TextDecoder().decode(glb.subarray(20,20+dv.getUint32(12,true))));assert.equal(gltf.accessors[0].count,13718);assert.equal(gltf.accessors[2].count,27420*3);assert.deepEqual(gltf.materials[0].pbrMetallicRoughness.baseColorFactor,[.4,.8,.8,1]);
console.log(JSON.stringify({R01MigrationMaxMetres:migrationMax,officialJSONRoundtripMaxMetres:rtMax,workshopJSONRoundtrip:true,GLB:true}));
