import fs from 'node:fs';
import * as R36 from '../round-36/r045_round36_kernel.mjs';
import * as R35 from '../round-35/r045_round35_kernel.mjs';

const X0=-220,Z0=-138,DX=10,DZ=6,XMIN=-230,XMAX=135,ZMIN=-150,ZMAX=25;
const seeds={}; let positiveSeedCount=0,maxGain=0,total=0;
for(let z=Z0;z<=ZMAX;z+=DZ){
  for(let x=X0;x<=XMAX;x+=DX){
    total++;
    const a=R35.terraceStateAt(x,z), b=R36.terraceStateAt(x,z);
    const gain=Math.max(0,b.mask-a.mask);
    if(gain>.0005){
      const k=`${Math.round((x-X0)/DX)},${Math.round((z-Z0)/DZ)}`;
      seeds[k]={gain:Number(gain.toFixed(12)),groupIndex:a.groupIndex,mask35:Number(a.mask.toFixed(12)),mask36:Number(b.mask.toFixed(12))};
      positiveSeedCount++; maxGain=Math.max(maxGain,gain);
    }
  }
}
const meta={generated:true,positiveSeedCount,maxGain,total,dx:DX,dz:DZ,x0:X0,z0:Z0,xmin:XMIN,xmax:XMAX,zmin:ZMIN,zmax:ZMAX};
const out=`// AUTO-GENERATED by r045_round37_build_seed_cache.mjs.\nexport const SEEDS = Object.freeze(${JSON.stringify(seeds,null,2)});\nexport const META = Object.freeze(${JSON.stringify(meta,null,2)});\n`;
fs.writeFileSync(new URL('./r045_round37_seed_cache.mjs',import.meta.url),out);
console.log(JSON.stringify(meta,null,2));
if(positiveSeedCount<4){console.error('Too few verified R36 positive stitch seeds for a meaningful cached field');process.exitCode=2;}
