// AUTO-GENERATED by r045_round37_build_seed_cache.mjs.
export const SEEDS = Object.freeze({
  "4,9": {
    "gain": 0.045564797494,
    "groupIndex": 1,
    "mask35": 0.268754724768,
    "mask36": 0.314319522262
  },
  "4,10": {
    "gain": 0.28613950151,
    "groupIndex": 1,
    "mask35": 0.114306428159,
    "mask36": 0.400445929668
  },
  "17,11": {
    "gain": 0.00555253132,
    "groupIndex": 2,
    "mask35": 0.55444746868,
    "mask36": 0.56
  },
  "24,11": {
    "gain": 0.019208407888,
    "groupIndex": 2,
    "mask35": 0.262012049436,
    "mask36": 0.281220457324
  },
  "27,11": {
    "gain": 0.224923218024,
    "groupIndex": 1,
    "mask35": 0.080363533629,
    "mask36": 0.305286751653
  },
  "17,14": {
    "gain": 0.11968871106,
    "groupIndex": 2,
    "mask35": 0.44031128894,
    "mask36": 0.56
  },
  "17,16": {
    "gain": 0.045969630131,
    "groupIndex": 1,
    "mask35": 0.123702387322,
    "mask36": 0.169672017454
  },
  "28,17": {
    "gain": 0.083109163732,
    "groupIndex": 1,
    "mask35": 0.301683492237,
    "mask36": 0.384792655969
  },
  "21,20": {
    "gain": 0.142389857729,
    "groupIndex": 2,
    "mask35": 0.056922151905,
    "mask36": 0.199312009634
  },
  "26,22": {
    "gain": 0.085447144276,
    "groupIndex": 2,
    "mask35": 0.104120548497,
    "mask36": 0.189567692773
  },
  "14,23": {
    "gain": 0.034708071436,
    "groupIndex": 2,
    "mask35": 0.411115163537,
    "mask36": 0.445823234972
  },
  "27,23": {
    "gain": 0.072628860089,
    "groupIndex": 2,
    "mask35": 0.068668866583,
    "mask36": 0.141297726672
  }
});
export const META = Object.freeze({
  "generated": true,
  "positiveSeedCount": 12,
  "maxGain": 0.2861395015095667,
  "total": 1008,
  "dx": 10,
  "dz": 6,
  "x0": -220,
  "z0": -138,
  "xmin": -230,
  "xmax": 135,
  "zmin": -150,
  "zmax": 25
});
