import * as THREE from '../source/registration-vendor/three.module.js';
/** Original geometry, referenced to World Boxing 2024 §13.12 and maker photos.
 * Visual study only: no claim of certified construction or dynamic rope physics. */
export const RING_SPEC=Object.freeze({insideRopes:6.10,platform:7.40,deckHeight:1.00,padding:.025,ropeDiameter:.05,ropeHeights:[.40,.70,1.00,1.30],apron:.65,cornerPosts:4,ropeRuns:16,spacers:8,pitch:8.8});
const merge=(parts)=>{const p=[],n=[],c=[],u=[];for(const {g,color}of parts){const a=g.index?g.toNonIndexed():g,C=new THREE.Color(color);for(let i=0;i<a.attributes.position.count;i++){p.push(a.attributes.position.getX(i),a.attributes.position.getY(i),a.attributes.position.getZ(i));n.push(a.attributes.normal.getX(i),a.attributes.normal.getY(i),a.attributes.normal.getZ(i));c.push(C.r,C.g,C.b);u.push(a.attributes.uv?.getX(i)||0,a.attributes.uv?.getY(i)||0);}if(a!==g)a.dispose();g.dispose();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(n,3));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(u,2));g.computeBoundingSphere();return g;};
function roundedBox(w,h,d,r=.025,segments=4){const g=new THREE.BoxGeometry(w,h,d,segments,segments,segments),p=g.attributes.position,n=g.attributes.normal;for(let i=0;i<p.count;i++){const v=new THREE.Vector3().fromBufferAttribute(p,i),q=new THREE.Vector3(Math.max(-w/2+r,Math.min(w/2-r,v.x)),Math.max(-h/2+r,Math.min(h/2-r,v.y)),Math.max(-d/2+r,Math.min(d/2-r,v.z))),N=v.clone().sub(q).normalize();v.copy(q).addScaledVector(N,r);p.setXYZ(i,v.x,v.y,v.z);n.setXYZ(i,N.x,N.y,N.z);}return g;}
function rod(a,b,r=.022,sides=8){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const d=b.clone().sub(a),g=new THREE.CylinderGeometry(r,r,d.length(),sides,1);g.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize()));g.translate(...a.add(b).multiplyScalar(.5).toArray());return g;}
function clothSide(length,height,axis,sign){const p=[],uv=[],idx=[],half=length/2;for(let i=0;i<=32;i++){const x=-half+i*length/32,fold=.009*Math.sin(i*1.55)+.004*Math.sin(i*.72);for(let j=0;j<2;j++){const y=-.07-j*height,z=sign*(half+.008+fold*j);p.push(...(axis==='x'?[x,y,z]:[z,y,x]));uv.push(i/32,j);}if(i<32){let a=i*2,b=a+2;idx.push(a,b,a+1,b,b+1,a+1);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g;}
let shared=null;
function buildShared(){if(shared)return shared;const hardware=[],pads=[],ropes=[],skirts=[];const add=(arr,g,color)=>arr.push({g,color});const ph=RING_SPEC.platform/2,ch=(RING_SPEC.insideRopes+RING_SPEC.ropeDiameter)/2,post=ch+.27;
 // Full deck support, edge, legs and accessible three-tread training stairs.
 add(hardware,new THREE.BoxGeometry(7.4,.13,7.4).translate(0,-.09,0),0x293844);
 add(pads,new THREE.BoxGeometry(7.4,.025,7.4).translate(0,-.0125,0),0x77949c);
 for(const x of[-3.48,3.48])for(const z of[-3.48,3.48])add(hardware,new THREE.BoxGeometry(.12,.87,.12).translate(x,-.565,z),0x25323a);
 for(let s=0;s<3;s++){const height=(s+1)/3;add(hardware,new THREE.BoxGeometry(.8,height,.36).translate(2.55,-1+height/2,4.62-s*.36),0x313f47);add(hardware,new THREE.BoxGeometry(.82,.025,.37).translate(2.55,-1+height+.014,4.62-s*.36),0x566770);}
 for(const [x,z,color]of[[-1,1,0xb4413f],[-1,-1,0xe3dfd5],[1,-1,0x286da2],[1,1,0xe3dfd5]]){
  add(hardware,new THREE.BoxGeometry(.13,1.59,.13).translate(x*post,.755,z*post),0x344651);
  add(hardware,new THREE.BoxGeometry(.22,.065,.22).translate(x*post,-.015,z*post),0x1c262e);
  const yaw=Math.atan2(-x,-z),pad=roundedBox(.30,1.10,.15,.04,4);pad.rotateY(yaw);pad.translate(x*(ch-.03),.87,z*(ch-.03));add(pads,pad,color);
  const seam=roundedBox(.235,.018,.012,.004,2);seam.rotateY(yaw);seam.translate(x*(ch-.085),1.35,z*(ch-.085));add(pads,seam,0xc2c7c8);
  for(const h of RING_SPEC.ropeHeights){const a=[x*ch,h,z*ch],b=[x*post,h+.01,z*post];add(hardware,rod(a,b,.011,6),0x899296);const cover=rod(a,b,.058,8);add(pads,cover,color);}
 }
 // Four complete continuous-looking tiers, mild static sag, two keeper straps/side.
 for(let tier=0;tier<4;tier++)for(let edge=0;edge<4;edge++){const h=RING_SPEC.ropeHeights[tier],sag=[.037,.029,.014,.010][tier],points=[];for(let k=0;k<=8;k++){const t=k/8,v=-ch+2*ch*t,yy=h-sag*Math.sin(Math.PI*t);points.push(new THREE.Vector3(...(edge===0?[v,yy,ch]:edge===1?[ch,yy,-v]:edge===2?[-v,yy,-ch]:[-ch,yy,v])));}add(ropes,new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),12,RING_SPEC.ropeDiameter/2,6,false),[0xede7df,0x356f9e,0xebe6de,0xb63f3c][tier]);}
 for(let edge=0;edge<4;edge++)for(const fraction of[1/3,2/3]){const v=-ch+2*ch*fraction,g=new THREE.BoxGeometry(.075,.955,.018);if(edge%2)g.rotateY(Math.PI/2);g.translate(...(edge===0?[v,.825,ch+.030]:edge===1?[ch+.030,.825,v]:edge===2?[v,.825,-ch-.030]:[-ch-.030,.825,v]));add(ropes,g,0x23313a);}
 for(const axis of ['x','z'])for(const sign of[-1,1])add(skirts,clothSide(RING_SPEC.platform,.90,axis,sign),0x152e43);
 const plane=new THREE.PlaneGeometry(7.4,7.4);plane.rotateX(-Math.PI/2);plane.translate(0,.0002,0);
 shared={hardware:merge(hardware),pads:merge(pads),ropes:merge(ropes),skirts:merge(skirts),canvas:plane};return shared;
}
let mats=null,canvasTex=null;
function makeMaterials(){if(mats)return mats;const cv=document.createElement('canvas');cv.width=cv.height=512;const c=cv.getContext('2d');c.fillStyle='#436876';c.fillRect(0,0,512,512);c.strokeStyle='rgba(203,224,219,.17)';c.lineWidth=1;for(let i=0;i<512;i+=8){c.beginPath();c.moveTo(i,0);c.lineTo(i,512);c.stroke();c.beginPath();c.moveTo(0,i);c.lineTo(512,i);c.stroke();}c.strokeStyle='rgba(199,220,216,.35)';c.strokeRect(10,10,492,492);c.fillStyle='rgba(211,228,222,.20)';c.textAlign='center';c.font='bold 34px sans-serif';c.fillText('KAOPU',256,235);c.font='12px sans-serif';c.fillText('COMMON HUMAN / MOTION STUDY',256,257);canvasTex=new THREE.CanvasTexture(cv);canvasTex.colorSpace=THREE.SRGBColorSpace;canvasTex.anisotropy=4;
 mats={hardware:new THREE.MeshStandardMaterial({vertexColors:true,roughness:.58,metalness:.35}),pads:new THREE.MeshStandardMaterial({vertexColors:true,roughness:.64,metalness:0}),ropes:new THREE.MeshStandardMaterial({vertexColors:true,roughness:.85,metalness:0}),skirts:new THREE.MeshStandardMaterial({vertexColors:true,roughness:.94,side:THREE.DoubleSide}),canvas:new THREE.MeshStandardMaterial({map:canvasTex,roughness:.98,metalness:0})};return mats;}
export class BoxingArena {
 constructor(index){const g=buildShared(),m=makeMaterials();this.group=new THREE.Group();this.parts={};for(const k of Object.keys(g)){const mesh=new THREE.Mesh(g[k],k==='ropes'?m[k].clone():m[k]);this.group.add(mesh);this.parts[k]=mesh;}const cv=document.createElement('canvas');cv.width=512;cv.height=96;const c=cv.getContext('2d');c.fillStyle='#d7e3df';c.textAlign='center';c.font='bold 39px sans-serif';c.fillText('KAOPU  /  '+String(index+1).padStart(2,'0'),256,46);c.font='16px sans-serif';c.fillText('BODY MOTION LAB     ·     R02',256,73);const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;this.labelTexture=tex;const label=new THREE.Mesh(new THREE.PlaneGeometry(2.35,.44),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));label.position.set(0,-.47,3.75);this.group.add(label);this.label=label;this.ropeMode='solid';}
 setRopeMode(mode='solid'){if(!['solid','ghost','hidden'].includes(mode))throw Error('Unknown rope observation mode');this.ropeMode=mode;const mesh=this.parts.ropes;mesh.visible=mode!=='hidden';mesh.material.opacity=mode==='ghost'?.17:1;mesh.material.transparent=mode==='ghost';mesh.material.depthWrite=mode!=='ghost';mesh.material.needsUpdate=true;}
 report(){return {...RING_SPEC,ropeMode:this.ropeMode,geometryTriangles:Object.values(this.parts).reduce((n,m)=>n+(m.geometry.index?.count||m.geometry.attributes.position.count)/3,0),drawCalls:6,geometrySharedAcrossArenas:true,simulation:'static referenced geometry, not a dynamic rope solver',manufacturerLogosCopied:false};}
 dispose(){this.parts.ropes.material.dispose();this.label.geometry.dispose();this.label.material.dispose();this.labelTexture.dispose();}
}
export function inspectArenaGeometry(){const s=buildShared();return {spec:RING_SPEC,parts:Object.fromEntries(Object.entries(s).map(([k,g])=>[k,{vertices:g.attributes.position.count,triangles:(g.index?.count||g.attributes.position.count)/3,finite:Array.from(g.attributes.position.array).every(Number.isFinite)}])),totalTriangles:Object.values(s).reduce((a,g)=>a+(g.index?.count||g.attributes.position.count)/3,0)};}
