/* Original bounded 2D grading. Attributed flat teacher triangulation is retained.
 * No fitted 3D coordinates are accepted. Every cut receives fresh material UVs.
 */
import{clone,validate,fingerprint}from '../../garments-r04/src/core.mjs';
export const PROGRAM='kaopu-short-sleeve-template-grading@1';
export const edgeLength=(p,key)=>{const ids=p.edges[key];return ids.slice(1).reduce((n,id,j)=>n+Math.hypot(...p.uvMm[id].map((x,k)=>x-p.uvMm[ids[j]][k])),0);};
export function gradePaper(base,{bodyLengthDeltaMm=0,sleeveLengthDeltaMm=0}={}){
 if(!Number.isFinite(bodyLengthDeltaMm)||bodyLengthDeltaMm< -50||bodyLengthDeltaMm>80||!Number.isFinite(sleeveLengthDeltaMm)||sleeveLengthDeltaMm< -30||sleeveLengthDeltaMm>50)throw Error('本例支持衣长 −50…+80 mm、袖长 −30…+50 mm');
 const spec=clone(base),records=[];
 for(const p of spec.panels){const old=base.panels.find(x=>x.id===p.id),role=p.source.role;
  if(role.startsWith('torso')){const side=spec.seams.find(s=>s.stageId==='sides'&&(s.a.panelId===p.id||s.b.panelId===p.id)),e=side.a.panelId===p.id?side.a:side.b,datum=Math.min(...old.edges[e.edge].map(i=>old.uvMm[i][1]));p.uvMm=bodyLengthDeltaMm?old.uvMm.map(([x,y])=>[x,y+bodyLengthDeltaMm*Math.max(0,Math.min(1,(y-datum)/(-datum)))]):old.uvMm.map(q=>[...q]);records.push({panelId:p.id,datumYmm:datum,bodyLengthDeltaMm,operation:'grade every original material point below underarm datum; curved edges held fixed'});}
  else if(role.startsWith('sleeve')){const caps=spec.seams.filter(s=>s.stageId==='armholes'&&(s.a.panelId===p.id||s.b.panelId===p.id)),ids=caps.flatMap(s=>{const e=s.a.panelId===p.id?s.a:s.b;return old.edges[e.edge];}),datum=Math.min(...ids.map(i=>Math.abs(old.uvMm[i][0]))),direction=p.source.side==='L'?1:-1;p.uvMm=sleeveLengthDeltaMm?old.uvMm.map(([x,y])=>[x+direction*sleeveLengthDeltaMm*Math.max(0,Math.min(1,(datum-Math.abs(x))/datum)),y]):old.uvMm.map(q=>[...q]);records.push({panelId:p.id,capNearestAbsoluteXmm:datum,sleeveLengthDeltaMm,operation:'extend distal straight sleeve material strip; complete source sleeve cap held fixed'});}
  else throw Error('Unknown material role');
  for(const key of Object.keys(p.analyticCurvesMm||{}))for(const id of p.edges[key])if(Math.hypot(...p.uvMm[id].map((x,k)=>x-old.uvMm[id][k]))>1e-8)throw Error('Grading unexpectedly moved a protected analytic curve');
 }
 const panels=Object.fromEntries(spec.panels.map(p=>[p.id,p]));for(const s of spec.seams)s.easeMm=edgeLength(panels[s.b.panelId],s.b.edge)-edgeLength(panels[s.a.panelId],s.a.edge);
 let minimum=180,area=0;for(const p of spec.panels)for(const t of p.triangles){const q=t.map(i=>p.uvMm[i]),D=(q[1][0]-q[0][0])*(q[2][1]-q[0][1])-(q[1][1]-q[0][1])*(q[2][0]-q[0][0]);if(D<=1e-8)throw Error('二维放码使材料三角形翻转');area+=D/2;for(let i=0;i<3;i++){const a=q[(i+1)%3].map((x,k)=>x-q[i][k]),b=q[(i+2)%3].map((x,k)=>x-q[i][k]);minimum=Math.min(minimum,Math.acos(Math.max(-1,Math.min(1,(a[0]*b[0]+a[1]*b[1])/(Math.hypot(...a)*Math.hypot(...b)))))*180/Math.PI);}}
 if(minimum<15)throw Error('放码后网格质量超出本例限制');spec.id=`kaopu-short-sleeve-${bodyLengthDeltaMm}-${sleeveLengthDeltaMm}`;spec.revision=1;spec.source.onlineProgram={id:PROGRAM,controls:{bodyLengthDeltaMm,sleeveLengthDeltaMm},sourcePaperFingerprint:fingerprint(base),operationRecords:records,meaning:'bounded 2D material grading with fixed template connectivity; fresh solve from flat material, not new Delaunay or 3D scaling'};spec.source.meshing={...spec.source.meshing,onlineRemeshing:false,connectivityRetained:true,minimumGradedTriangleAngleDeg:minimum,gradedMaterialAreaMm2:area};validate(spec);return spec;
}
export function paperSummary(s){let hem=0;for(const p of s.panels.filter(p=>p.source.role.startsWith('torso'))){const ymax=Math.max(...p.uvMm.map(q=>q[1])),h=Object.entries(p.edges).find(([,ids])=>ids.every(i=>Math.abs(p.uvMm[i][1]-ymax)<1e-7));if(!h)throw Error('Missing material hem');hem+=edgeLength(p,h[0]);}return{program:s.source.onlineProgram,panels:s.panels.length,seams:s.seams.length,hemCircumferenceMm:hem,particleCount:s.panels.reduce((n,p)=>n+p.uvMm.length,0),triangleCount:s.panels.reduce((n,p)=>n+p.triangles.length,0),netMaterialAreaMm2:s.source.meshing.gradedMaterialAreaMm2,minimumTriangleAngleDeg:s.source.meshing.minimumGradedTriangleAngleDeg,connectivityRetained:true};}
