/* Analytic net-pattern drawing plus explicit alignment marks.
 * Curve data are attributed to the MIT teacher pattern; original display code.
 */
export const names={left_ftorso:'左前衣身',right_ftorso:'右前衣身',left_btorso:'左后衣身',right_btorso:'右后衣身',left_sleeve_f:'左前袖片',right_sleeve_f:'右前袖片',left_sleeve_b:'左后袖片',right_sleeve_b:'右后袖片'},colors={left_ftorso:'#d9bd85',right_ftorso:'#d9bd85',left_btorso:'#87a8bb',right_btorso:'#87a8bb',left_sleeve_f:'#8fc0c6',right_sleeve_f:'#8fc0c6',left_sleeve_b:'#7aa4b5',right_sleeve_b:'#7aa4b5'};
const point=q=>q.map(x=>+x.toFixed(6)).join(' ');
function edgeCommand(p,key){const ids=p.edges[key],end=p.uvMm[ids.at(-1)],c=p.analyticCurvesMm?.[key];if(!c)return'L '+point(end);if(c.type==='circle')return`A ${point(c.radiusMm)} ${c.rotationDeg} ${c.largeArc?1:0} ${c.sweep?1:0} ${point(end)}`;const q=c.controlPointsMm;return(c.type==='cubic'?'C ':'Q ')+q.slice(1).map(point).join(' ');}
function atDistance(p,ids,t){const points=ids.map(i=>p.uvMm[i]),lengths=points.slice(1).map((q,i)=>Math.hypot(...q.map((x,k)=>x-points[i][k]))),target=lengths.reduce((a,b)=>a+b,0)*t;let walked=0;for(let j=0;j<lengths.length;j++){if(walked+lengths[j]>=target||j===lengths.length-1){const a=points[j],b=points[j+1],u=(target-walked)/lengths[j];return{p:a.map((x,k)=>x+(b[k]-x)*u),n:[-(b[1]-a[1])/lengths[j],(b[0]-a[0])/lengths[j]]};}walked+=lengths[j];}}
export function paperSVG(spec,{selectedSeamId='',hotspot=null,download=false,focusPair=false}={}){
 const selected=spec.seams.find(s=>s.id===selectedSeamId),visible=focusPair&&!download&&selected?spec.panels.filter(p=>p.id===selected.a.panelId||p.id===selected.b.panelId):spec.panels;const layouts=[];let x=20,maxHeight=0;for(const p of visible){const xs=p.uvMm.map(q=>q[0]),ys=p.uvMm.map(q=>q[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);layouts.push({p,x:x-xmin,y:45-ymin});x+=xmax-xmin+45;maxHeight=Math.max(maxHeight,ymax-ymin);}const w=x,h=maxHeight+122;let out=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" ${download?`width="${w}mm" height="${h}mm"`:''}><metadata>GarmentCode MIT source d449629979028123a5c4dc9e732a2ec19b7fce31; own bounded 2D grade and original SVG renderer. Net pattern only. Alignment marks do not remove material.</metadata><defs><marker id="arrow" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0 0 L6 3 L0 6" fill="#6c4a25"/></marker></defs>`;
 for(const{p,x,y}of layouts){const keys=Object.keys(p.edges),start=p.uvMm[p.edges[keys[0]][0]],outline='M '+point(start)+' '+keys.map(k=>edgeCommand(p,k)).join(' ')+' Z';out+=`<g transform="translate(${x} ${y})"><path d="${outline}" fill="${colors[p.id]}" fill-opacity=".48" stroke="#516067" stroke-width="1.1"/>`;
  for(const[key,ids]of Object.entries(p.edges)){const seam=spec.seams.find(s=>[s.a,s.b].some(e=>e.panelId===p.id&&e.edge===key)),highlight=seam?.id===selectedSeamId;out+=`<path d="M ${point(p.uvMm[ids[0]])} ${edgeCommand(p,key)}" fill="none" stroke="${highlight?'#a54331':seam?'#796340':'#526369'}" stroke-width="${highlight?3.4:1.2}"/>`;if(seam){const mid=atDistance(p,ids,.5);out+=`<text x="${mid.p[0]+3}" y="${mid.p[1]-3}" font-size="7" fill="#493f31">${seam.sourceStitchIndex}</text>`;const a=atDistance(p,ids,.40),b=atDistance(p,ids,.56);out+=`<path d="M ${point(a.p)} L ${point(b.p)}" stroke="#796340" stroke-width=".8" marker-end="url(#arrow)"/>`;for(const mark of p.edgeNotches[key]||[]){const q=atDistance(p,ids,mark.t),a=q.p.map((v,k)=>v-q.n[k]*2.3),b=q.p.map((v,k)=>v+q.n[k]*2.3);out+=`<path d="M ${point(a)} L ${point(b)}" stroke="#6d4b39" stroke-width=".8"/><text x="${q.p[0]+q.n[0]*6}" y="${q.p[1]+q.n[1]*6}" font-size="4.8" fill="#675448">${mark.id}</text>`;}}}
  const xs=p.uvMm.map(q=>q[0]),ys=p.uvMm.map(q=>q[1]),mx=(Math.min(...xs)+Math.max(...xs))/2,my=(Math.min(...ys)+Math.max(...ys))/2;out+=`<path d="${p.grain[0]?`M${mx-22} ${my}h44`:`M${mx} ${my-22}v44`}" stroke="#5b6869" stroke-width="1" marker-end="url(#arrow)"/><text x="${Math.min(...xs)}" y="${Math.min(...ys)-13}" font-size="12" fill="#26373d">${names[p.id]}</text>`;if(hotspot?.panelId===p.id)out+=`<circle cx="${hotspot.uvCentroidMm[0]}" cy="${hotspot.uvCentroidMm[1]}" r="6" fill="#b73128" stroke="#fff" stroke-width="2"/>`;out+='</g>';
 }
 return out+`<path d="M20 ${h-38}h100m-100 -4v8m100 -8v8" stroke="#33464d" stroke-width="1"/><text x="20" y="${h-18}" font-size="10" fill="#33464d">100 mm · 解析曲线净纸样 · 缝份 0 mm（未建模） · N1/N2 为对位记号，不裁缺口</text><text x="20" y="${h-3}" font-size="8" fill="#526369">仿真边界使用纸样曲线的离散采样，基准抽样最大偏差约 0.456 mm；不是物理缝份或投产裁剪图</text></svg>`;
}
