import * as THREE from 'three';
// Read-only source patches; no mirror-generated fin and no replacement source motion.
export function installPectoralStudy(ctx){
 const {compiled,meshes,state,qa,scenes,cam,controls,preset,regionTool,getSurfaces,readSurface}=ctx,$=s=>document.querySelector(s);
 const el=$('#pectoralEvidence'),data=JSON.parse(el.textContent);el.remove();const selection={id:'none',trail:false,isolated:false};
 const panel=document.createElement('div');panel.className='section';panel.id='pectoralPanel';panel.innerHTML='<h2>01H　两侧胸鳍与原连接处 · R011</h2><p class="sub">两侧各保留219个原面；L侧134、R侧136个原索引。各自读取，不用镜像鱼鳍代替。</p><select id="pectoralSelect" class="w100" aria-label="原胸鳍观察"><option value="none">全鱼 · 选择原胸鳍</option><option value="both">两侧同时观察</option><option value="pectoral_l">L侧原胸鳍（候选标签）</option><option value="pectoral_r">R侧原胸鳍（候选标签）</option></select><div class="row"><button id="pectoralFocus">放大胸鳍</button><button id="pectoralIsolate">单独看选中鳍</button></div><div class="row"><button id="pectoralMin">原样本较低位置</button><button id="pectoralMax">原样本较高位置</button></div><div class="row"><button id="pectoralTrail">原表面点轨迹</button><button id="pectoralClear">恢复全鱼</button></div><pre id="pectoralLive">分别检查两侧原鳍面、控制链和鳍根原索引接口，观察它们怎样随原Swim变形。</pre><details><summary>源身份和测量定义</summary><pre id="pectoralSource"></pre><p class="sub">端点为静息原面上距接口均点最远的原索引，运动时不换点。接口均点按原位置分组计算，重复索引全部保留，不焊接。随动高度不是鳍角、升力或真实生物学摆幅；面积为原三角表面积。长度使用归一鱼长，真实尺寸、年龄和解剖标志尚未核准。</p></details>';
 $('#tailPanel').before(panel);
 function line(color){const o=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color,depthTest:false}));o.frustumCulled=false;o.renderOrder=52;o.visible=false;scenes[1].add(o);return o;}
 const edges=line(0x76dfd2),spans=line(0xffc67a),rig=line(0xbfcdfa),trails=line(0xffae67);
 const dots=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffc67a,size:7,sizeAttenuation:false,depthTest:false}));dots.frustumCulled=false;dots.renderOrder=54;dots.visible=false;scenes[1].add(dots);const overlays=[edges,spans,rig,trails,dots];
 const vec=(s,i)=>new THREE.Vector3().fromArray(s.p,i*3),position=o=>new THREE.Vector3().setFromMatrixPosition(o.matrixWorld);
 function fill(o,a){const prev=o.geometry.getAttribute('position');if(prev&&prev.array.length===a.length){prev.array.set(a);prev.needsUpdate=true;}else{o.geometry.dispose();o.geometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(a,3));}}
 function axes(m){const a=new THREE.Matrix3().setFromMatrix4(m),e=a.elements;for(let c=0;c<3;c++){const n=Math.hypot(e[c*3],e[c*3+1],e[c*3+2]);for(let r=0;r<3;r++)e[c*3+r]/=n;}return a;}
 const restAxes=axes(new THREE.Matrix4().fromArray(data.restBodyMatrix));
 function measure(def,surfs,bodyMatrix){const s=surfs[def.mesh],root=def.rootVertices.map(v=>vec(s,v.sourceVertex)),mean=root.reduce((v,p)=>v.add(p),new THREE.Vector3()).divideScalar(root.length),tip=vec(s,def.tip.sourceVertex),r=axes(bodyMatrix).multiply(restAxes.clone().transpose()),offset=tip.clone().sub(mean).applyMatrix3(r.transpose());let area=0,gap=0,alias=0;const ab=new THREE.Vector3(),ac=new THREE.Vector3();for(const f of def.sourceTriangles){const ids=s.idx.subarray(f*3,f*3+3),a=vec(s,ids[0]),b=vec(s,ids[1]),c=vec(s,ids[2]);area+=ab.subVectors(b,a).cross(ac.subVectors(c,a)).length()*.5;}for(const e of def.interfaceEdges)for(let k=0;k<2;k++)gap=Math.max(gap,vec(s,e.finVertices[k]).distanceTo(vec(s,e.trunkVertices[k])));for(const g of def.rootVertices)for(const id of g.sourceAliases)alias=Math.max(alias,vec(s,id).distanceTo(vec(s,g.sourceVertex)));
 return {root,mean,tip,alias,metrics:{rootMeanToTip:tip.distanceTo(mean),bodyFrameTipLongitudinal:offset.x,bodyFrameTipVertical:offset.y,bodyFrameTipLateral:offset.z,sourceFinSurfaceArea:area,interfaceMaxGap:gap}};}
 const selected=()=>data.definitions.filter(d=>selection.id==='both'||d.id===selection.id);
 function update(){if(selection.id==='none'||!getSurfaces()?.length)return;const surfs=getSurfaces(),body=compiled.nodes[data.bodyNode].matrixWorld,defs=selected(),rows=defs.map(d=>({def:d,obs:measure(d,surfs,body)}));fill(edges,defs.flatMap(d=>d.interfaceEdges.flatMap(e=>e.finVertices.flatMap(v=>vec(surfs[d.mesh],v).toArray()))));fill(spans,rows.flatMap(({obs})=>[...obs.mean.toArray(),...obs.tip.toArray()]));fill(dots,rows.flatMap(({obs})=>[...obs.mean.toArray(),...obs.tip.toArray()]));fill(rig,defs.flatMap(d=>d.controls.flatMap(c=>[...position(compiled.nodes[c.parent]).toArray(),...position(compiled.nodes[c.node]).toArray()])));edges.visible=spans.visible=dots.visible=rig.visible=true;trails.visible=selection.trail;
  qa.pectoralCurrent={id:selection.id,time:state.time,rest:state.rest,isolated:selection.isolated,fins:rows.map(({def,obs})=>({id:def.id,sourceVertex:def.tip.sourceVertex,metrics:obs.metrics}))};$('#pectoralLive').textContent=(state.rest?'源静息态':'原 Swim '+state.time.toFixed(4)+' s')+' · '+(selection.isolated?'单独原鳍面':'完整原鱼对照')+'\n'+rows.map(({def,obs})=>{const q=obs.metrics;return (def.id==='pectoral_l'?'L':'R')+'侧 · 原顶点 '+def.tip.sourceVertex+'\n接口均点→端点 '+q.rootMeanToTip.toFixed(6)+'\n随动高度 '+q.bodyFrameTipVertical.toFixed(6)+'\n随动侧向分量 '+q.bodyFrameTipLateral.toFixed(6)+'\n原三角表面积 '+q.sourceFinSurfaceArea.toFixed(6)+'\n原接口最大间距 '+q.interfaceMaxGap.toExponential(2);}).join('\n\n');
 }
 function hide(){const isolated=selection.isolated;selection.id='none';selection.isolated=false;$('#pectoralSelect').value='none';$('#pectoralIsolate').classList.remove('active');overlays.forEach(o=>o.visible=false);qa.pectoralEnabled=false;if(isolated)regionTool.restore();}
 function choose(id){if(id==='none'){clear();return;}if(id!=='both'&&!data.definitions.some(d=>d.id===id))throw Error('Unknown source pectoral side');ctx.clearOther();regionTool.restore();window.FISH_CANONICAL.choose(-1);selection.id=id;selection.isolated=false;$('#pectoralSelect').value=id;$('#pectoralIsolate').classList.remove('active');qa.pectoralEnabled=true;const defs=selected();fill(trails,defs.flatMap(d=>{const index=data.definitions.indexOf(d);return data.samples.slice(1).flatMap((s,i)=>[...data.samples[i].fins[index].tip,...s.fins[index].tip]);}));$('#pectoralSource').textContent=JSON.stringify(defs.map(d=>({id:d.id,tip:d.tip,sourceFaces:d.sourceTriangles.length,sourceVertexIndices:d.sourceVertices.length,originalInterfaceEdges:d.interfaceEdges.length,originalRootAliases:d.rootVertices,sourceControls:d.controls.map(c=>c.sourceName),anatomicalApproval:false})),null,2);update();}
 function focus(){if(selection.id==='none')choose('both');preset('top');const box=new THREE.Box3();for(const d of selected())for(const id of d.sourceVertices)box.expandByPoint(vec(getSurfaces()[d.mesh],id));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),direction=cam.position.clone().sub(controls.target).normalize();controls.target.copy(center);cam.position.copy(center).addScaledVector(direction,3);cam.zoom=Math.max(1,Math.min(5,.6/Math.max(size.x,size.y,size.z)));cam.updateProjectionMatrix();controls.update();}
 function clear(){hide();regionTool.restore();window.FISH_CANONICAL.choose(-1);preset('side');}
 function peak(kind){if(selection.id==='none'||selection.id==='both')choose('pectoral_l');const d=selected()[0],key='bodyFrameTipVertical',index=d.summary[key][kind+'Index'];ctx.jumpExact(data.samples[index].time);$('#time').value=state.time;$('#timeLabel').textContent=state.time.toFixed(3)+' s · 原胸鳍样本';qa.pectoralSelectedSample={kind,id:d.id,index,key};focus();update();}
 function audit(){const saved=selection.id;selection.id='none';overlays.forEach(o=>o.visible=false);let points=0,matrices=0,lengths=0,area=0,aliases=0,gaps=0;const ids=compiled.pkg.skeletonGraphs[0].jointNodes;ctx.beginExact();try{for(const sample of [data.restSample,...data.samples]){ctx.seekExact(sample.time??0,sample.rest);for(const rt of [0,1]){const bone=id=>rt===0?meshes[0][0].skeleton.bones[ids.indexOf(id)]:compiled.nodes[id],surfs=rt===0?readSurface(0):getSurfaces();sample.controlMatrices.forEach(n=>n.matrix.forEach((v,k)=>matrices=Math.max(matrices,Math.abs(v-bone(n.node).matrixWorld.elements[k]))));for(let i=0;i<data.definitions.length;i++){const obs=measure(data.definitions[i],surfs,bone(data.bodyNode).matrixWorld),expected=sample.fins[i];points=Math.max(points,obs.tip.distanceTo(new THREE.Vector3().fromArray(expected.tip)));obs.root.forEach((v,k)=>points=Math.max(points,v.distanceTo(new THREE.Vector3().fromArray(expected.rootPoints[k]))));for(const [key,value]of Object.entries(obs.metrics)){const e=Math.abs(value-expected.metrics[key]);if(key==='sourceFinSurfaceArea')area=Math.max(area,e);else lengths=Math.max(lengths,e);}aliases=Math.max(aliases,obs.alias);gaps=Math.max(gaps,obs.metrics.interfaceMaxGap);}}}}finally{ctx.endExact();selection.id=saved;if(saved!=='none')update();}
 return {restSamples:1,clampedTimes:data.samples.length,comparedRuntimes:2,sourceSides:2,controls:12,sourceTracks:36,sourceTriangles:[219,219],sourceVertexIndices:data.qa.sourceFinVertexIndices,sourceInterfaceEdges:[11,11],pointMaxError:points,matrixMaxError:matrices,lengthMaxError:lengths,surfaceAreaMaxError:area,maxAliasGap:aliases,maxInterfaceGap:gaps,lengthTolerance:1e-6,areaTolerance:1e-8,passed:Math.max(points,matrices,lengths,aliases,gaps)<1e-6&&area<1e-8,mirroredFinCreated:false,anatomicalApproval:false};}
 $('#pectoralSelect').onchange=e=>choose(e.target.value);$('#pectoralFocus').onclick=focus;$('#pectoralMin').onclick=()=>peak('min');$('#pectoralMax').onclick=()=>peak('max');$('#pectoralClear').onclick=clear;$('#pectoralTrail').onclick=()=>{if(selection.id==='none')choose('both');selection.trail=!selection.trail;$('#pectoralTrail').classList.toggle('active',selection.trail);update();};$('#pectoralIsolate').onclick=()=>{if(selection.id==='none'||selection.id==='both')choose('pectoral_l');selection.isolated=!selection.isolated;regionTool.selection.isolate=selection.isolated;regionTool.choose(selection.id);if(!selection.isolated){regionTool.restore();window.FISH_CANONICAL.choose(-1);}$('#pectoralIsolate').classList.toggle('active',selection.isolated);update();};
 for(const id of ['#tailSelect','#featureSelect','#headSelect','#regionSelect','#groupSelect','#jointSelect','#interfaceSelect'])$(id)?.addEventListener('change',()=>{if(selection.id!=='none')hide();},true);
 for(const id of ['#tailFocus','#tailMin','#tailMax','#tailClear','#oralShow','#oralMin','#oralMax','#oralFront','#oralClear','#headFocus','#headPeak','#headClear','#featureMin','#featureMax','#featureFocus','#featureClear','#regionClear','#boundaryClear','#reset'])$(id)?.addEventListener('click',()=>{if(selection.id!=='none')hide();},true);
 qa.pectoralStudy=data.qa;qa.pectoralEnabled=false;const api={data,selection,choose,hide,clear,focus,peak,update,audit};window.FISH_PECTORAL=api;return api;
}
