import test from 'node:test';
import assert from 'node:assert/strict';
import {example,compile,evaluate,LANGUAGE} from '../structured/compiler.mjs';
import {cut,ClothLab,clone,directedEdge} from '../src/core.mjs';
const run=(l,n)=>{for(let i=0;i<n;i++)l.step();};
function gap(l,id){const seam=l.spec.seams.find(s=>s.id===id),a=directedEdge(l.spec,seam.a),b=directedEdge(l.spec,seam.b);return Math.max(...a.ids.map((v,i)=>{const p=l.positions[l.offsets.get(a.panel.id)+v],q=l.positions[l.offsets.get(b.panel.id)+b.ids[i]];return Math.hypot(...p.map((x,k)=>x-q[k]))*1000;}));}
test('manual curve language produces 3 real panels and 2 curved seams',()=>{const source=example(),{spec,report}=compile(source);assert.equal(source.schema,LANGUAGE);assert.equal(report.panelCount,3);assert.equal(report.curveCount,4);assert.equal(report.vertexCount,459);assert.equal(report.triangleCount,768);assert.equal(report.seams.length,2);assert.ok(report.maxCurveApproximationErrorMm<.05);assert.equal(spec.sourceLanguage.input.panels[0].right.control[0],65);assert.equal(report.imageInferenceImplemented,false);});
test('curves change actual material coordinates and frozen identity',()=>{const source=example(),first=compile(source);source.panels[0].right.control[0]-=10;source.panels[1].left.control[0]-=10;source.revision++;const second=compile(source);assert.notDeepEqual(first.spec.panels[0].uvMm,second.spec.panels[0].uvMm);assert.notEqual(cut(first.spec).signature,cut(second.spec).signature);assert.notEqual(first.report.seams[0].lengthAMm,second.report.seams[0].lengthAMm);});
test('normal offset is actual 8 mm material strip at curve samples',()=>{const {spec}=compile(example());for(const p of spec.panels){const rows=17,cols=p.uvMm.length/rows;for(let j=0;j<rows;j++){assert.ok(Math.abs(Math.hypot(...p.uvMm[j*cols].map((x,k)=>x-p.uvMm[j*cols+1][k]))-8)<1e-8);assert.ok(Math.abs(Math.hypot(...p.uvMm[(j+1)*cols-1].map((x,k)=>x-p.uvMm[(j+1)*cols-2][k]))-8)<1e-8);}}});
test('curve mismatch, orientation, missing panel and unsupported free curve fail explicitly',()=>{let s=example();s.panels[0].right.control[0]-=30;assert.throws(()=>compile(s),/EASE_LENGTH/);s=example();s.stitches[0].b.reverse=false;assert.throws(()=>compile(s),/NOTCH_DIRECTION/);s=example();s.stitches[0].b.panelId='X';assert.throws(()=>compile(s),/MISSING_PANEL/);s=example();s.panels[0].right.control[1]=80;assert.throws(()=>compile(s),/CURVE_SUPPORT/);});
test('removing a real panel requires explicit topology editing, not ghost geometry',()=>{const s=example();s.panels.pop();assert.throws(()=>compile(s),/MISSING_PANEL/);s.stitches.pop();s.stages.pop();const r=compile(s);assert.equal(r.report.panelCount,2);assert.equal(r.report.vertexCount,306);assert.equal(r.report.seams.length,1);});
test('sequential curve seams actually solve and old seams do not reopen',()=>{const l=new ClothLab(cut(compile(example()).spec));l.gravity=false;assert.throws(()=>l.activate('join-right'),/STAGE_DEPENDENCY/);l.activate('join-left');run(l,180);assert.ok(gap(l,'left-curve')<1.2);assert.ok(gap(l,'right-curve')>20);const old=l.seamConstraints[0].activatedAt;l.activate('join-right');assert.equal(l.seamConstraints[0].activatedAt,old);run(l,1);assert.ok(gap(l,'left-curve')<1.2,'stage two reopened prior stitches');run(l,240);const m=l.metrics();assert.equal(m.activeStitches,34);assert.ok(gap(l,'right-curve')<1.2);assert.ok(m.maxPrincipalStrain<.05,JSON.stringify(m));assert.equal(m.productionReady,false);});
test('detach resets all declared activation stages without altering rest data',()=>{const l=new ClothLab(cut(compile(example()).spec));l.activate('join-left');l.activate('join-right');l.detach();assert.equal(l.seamConstraints.length,0);assert.deepEqual([...l.completed],['cut']);assert.throws(()=>l.activate('join-right'),/STAGE_DEPENDENCY/);});
