const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.QA_OUT||'qa-skin-quality-r01',URL=process.env.QA_URL||'http://127.0.0.1:8765/kaopu-unified-human-workbench/identity-lab/preview.html';
fs.mkdirSync(OUT,{recursive:true});
const report={version:'skin-sampling/r01',base:'2702e9482cfd1655411bb0920929872669301334',url:URL,checks:[],shots:[],errors:[],visualAcceptance:false,physicalGPU:false,realMobileDevice:false};let browser,page;
const check=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});assert(pass,name+' '+JSON.stringify(detail));};
async function pixels(){return page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer();v.render();const gl=v.renderer.getContext(),data=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,data);if(gl.getError()!==gl.NO_ERROR)throw Error('Readback error');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),x=>x.toString(16).padStart(2,'0')).join('');});}
async function snapshot(name){const result=await page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer(),m=__IDENTITY_QA__.model(),hash=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',x)),v=>v.toString(16).padStart(2,'0')).join('');return{geometry:await hash(m.positions),faces:await hash(m.faces),archive:JSON.stringify(fullCommonWorkbench.archive()),camera:v.cameraState(),lights:v.scene.children.filter(x=>x.isLight).map(x=>({type:x.type,position:x.position.toArray(),color:x.color.toArray(),intensity:x.intensity})),sampling:v.skin.samplingExtension?.report(),canvas:[v.canvas.width,v.canvas.height]};});result.pixels=await pixels();await page.locator('#canvas').screenshot({path:path.join(OUT,name+'.png')});report.shots.push({name,...result,archive:crypto.createHash('sha256').update(result.archive).digest('hex')});return result;}
(async()=>{
 const baseline=fs.readFileSync(ROOT+'/identity-lab/preview.html');check('immutable original ET13 preview',crypto.createHash('sha256').update(baseline).digest('hex')==='99942c121ec46428e980568a6b0b82c5872359bf1a7576f600ac5fa1a4a952ad');
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Shader|WebGLProgram|GL_INVALID/.test(m.text()))report.errors.push(m.text());});
 await page.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__IDENTITY_QA__?.viewer()&&window.fullCommonWorkbench?.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});await page.evaluate(()=>fullFaceTransfer.ready());
 await page.evaluate(async()=>{await fullCommonWorkbench.motion().setMode('shape');fullCommonWorkbench.view('face');window.__SKIN_ORIGINAL__=fullCommonWorkbench.archive();});
 const beforeAttach=await snapshot('00-original-et13');
 await page.evaluate(async()=>{const mod=await import('../skin-quality-r01/SkinSampling.mjs');window.__SAMPLING_MODULE__=mod;window.__SAMPLING__=await mod.attachSkinSampling(__IDENTITY_QA__.viewer().skin);});
 const afterAttach=await snapshot('01-sampling-candidate');check('same native positions',beforeAttach.geometry===afterAttach.geometry);check('same native faces',beforeAttach.faces===afterAttach.faces);check('all face identity and surface archive parameters preserved',beforeAttach.archive===afterAttach.archive);check('same camera and lights',JSON.stringify([beforeAttach.camera,beforeAttach.lights])===JSON.stringify([afterAttach.camera,afterAttach.lights]));check('array shader compiled',afterAttach.sampling.shaderCompiles>0,afterAttach.sampling);
 await page.evaluate(()=>__SAMPLING__.setEnabled(false));check('disabled candidate restores exact baseline framebuffer',await pixels()===beforeAttach.pixels);
 const views=['face','nose','oblique'],lights=['neutral','grazing','back'];
 for(const view of views){await page.evaluate(view=>{const v=__IDENTITY_QA__.viewer();if(view==='face')v.view('face');else __IDENTITY_QA__.model().faceSurface.featureView(view);},view);
  for(const light of lights){await page.evaluate(light=>{const v=__IDENTITY_QA__.viewer(),ls=v.scene.children.filter(x=>x.isLight),ds=ls.filter(x=>x.isDirectionalLight),hs=ls.filter(x=>x.isHemisphereLight);hs.forEach(x=>x.intensity=light==='neutral'?.65:.18);for(const x of ds)x.intensity=0;const key=ds[0];key.color.setRGB(1,1,1);key.intensity=3.2;key.position.fromArray(light==='neutral'?[-2,3,4]:light==='grazing'?[4,1,.1]:[-1,2,-4]);v.render();},light);
   await page.evaluate(()=>__SAMPLING__.setEnabled(false));const a=await snapshot(view+'-'+light+'-before');await page.evaluate(()=>__SAMPLING__.setEnabled(true));const b=await snapshot(view+'-'+light+'-after');
   check(view+' '+light+' controlled A/B',a.geometry===b.geometry&&a.faces===b.faces&&a.archive===b.archive&&JSON.stringify([a.camera,a.lights])===JSON.stringify([b.camera,b.lights]));
  }
 }
 await page.evaluate(()=>{const m=__IDENTITY_QA__.model();m.faceSurface.featureView('nose');fullCommonWorkbench.setSkin({detail:0,variation:0});});await page.evaluate(()=>__SAMPLING__.setEnabled(false));const zeroBefore=await pixels();await page.evaluate(()=>__SAMPLING__.setEnabled(true));check('zero detail and variation preserve original master controls exactly',await pixels()===zeroBefore);
 await page.evaluate(()=>fullCommonWorkbench.restore(__SKIN_ORIGINAL__));const original=await page.evaluate(()=>fullCommonWorkbench.archive());
 for(const recipe of ['freckles','acne','mature','scar']){await page.evaluate(recipe=>identityWorkbench.skinRecipe(recipe),recipe);const a=await page.evaluate(()=>fullCommonWorkbench.archive());await page.evaluate(()=>__SAMPLING__.setEnabled(false));const old=await snapshot('traits-'+recipe+'-before');await page.evaluate(()=>__SAMPLING__.setEnabled(true));const now=await snapshot('traits-'+recipe+'-after');check('identity '+recipe+' remains intact',old.geometry===now.geometry&&old.archive===now.archive&&JSON.stringify(a)===now.archive);}
 await page.evaluate(a=>fullCommonWorkbench.restore(a),original);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fullCommonWorkbench.view('face'));await snapshot('mobile-after');check('mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check('one original canvas',await page.locator('canvas').count()===1);
 check('no JS/WebGL errors',report.errors.length===0,report.errors);report.passed=true;
})().catch(e=>{report.passed=false;report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{if(page&&!report.passed)await page.screenshot({path:OUT+'/failure.png'}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(OUT+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,errors:report.errors,failure:report.failure}));});
