const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const isPublic=!!process.env.PUBLIC_PREVIEW_URL,isDelivery=isPublic||!!process.env.DELIVERY_PREVIEW_URL,URL=process.env.PUBLIC_PREVIEW_URL||process.env.DELIVERY_PREVIEW_URL||'http://127.0.0.1:8765/qa-skin-quality-r01/public/preview.html',OUT='qa-skin-quality-r01/'+(isPublic?'public-verified':isDelivery?'delivery-local':'preview-local');fs.mkdirSync(OUT,{recursive:true});let browser,page;const R={url:URL,publicURL:isPublic,checks:[],errors:[],warnings:[],screenshots:[],filmQualityAccepted:false};
const check=(name,pass,detail)=>{R.checks.push({name,pass:!!pass,detail});assert(pass,name+' '+JSON.stringify(detail));};
async function pixels(){return page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer();v.render();const gl=v.renderer.getContext(),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);if(gl.getError()!==gl.NO_ERROR)throw Error('Preview GL error');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',p)),x=>x.toString(16).padStart(2,'0')).join('');});}
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.on('pageerror',e=>R.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')R.errors.push(m.text());if(m.type()==='warning')R.warnings.push(m.text());});
 const assetResponses=[];page.on('response',r=>{if(r.url().includes('raw.githubusercontent.com'))assetResponses.push({url:r.url(),status:r.status()});});
 const response=await page.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});check('actual HTML loaded',response.ok());await page.waitForFunction(()=>window.regionalWorkbench,null,{timeout:240000});await page.evaluate(()=>__REGIONAL_PREVIEW_READY__);await page.evaluate(()=>fullCommonWorkbench.motion().setMode('shape'));await page.evaluate(()=>regionalWorkbench.view('mouth'));
 check('original 89 controls remain',await page.evaluate(()=>identityWorkbench.catalog().length===89));check('five regional controls present',await page.locator('[data-r]').count()===5);check('single native renderer canvas',await page.locator('canvas').count()===1);
 const original=await page.evaluate(()=>fullCommonWorkbench.archive());const on=await pixels();await page.locator('#canvas').screenshot({path:OUT+'/mouth-on.png'});R.screenshots.push('mouth-on.png');
 await page.locator('[data-r-toggle]').click();const off=await pixels();await page.locator('#canvas').screenshot({path:OUT+'/mouth-off.png'});R.screenshots.push('mouth-off.png');check('public native compare switch changes pixels',on!==off);await page.locator('[data-r-toggle]').click();check('public native compare restores exact pixels',on===await pixels());
 await page.locator('[data-r="lipDryness"]').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}));});check('public slider drives actual material',await pixels()!==on);await page.evaluate(a=>fullCommonWorkbench.restore(a),original);check('public archive exactly restores pixels',await pixels()===on);
 await page.evaluate(()=>regionalWorkbench.view('eyes'));await page.locator('#canvas').screenshot({path:OUT+'/eyes-on.png'});R.screenshots.push('eyes-on.png');await page.evaluate(()=>regionalWorkbench.view('face'));await page.screenshot({path:OUT+'/native-entry.png'});R.screenshots.push('native-entry.png');
 R.settings=await page.evaluate(()=>regionalWorkbench.report());check('bundled runtime has no duplicate Three warning',!R.warnings.some(x=>/Multiple instances of Three/.test(x)));check('no JS or WebGL errors',R.errors.length===0,R.errors);
 if(isDelivery){
 const raw=process.env.PUBLIC_RAW_BASE||process.env.DELIVERY_RAW_BASE,response=await fetch(raw+'/preview.html'),bytes=Buffer.from(await response.arrayBuffer()),manifest=await(await fetch(raw+'/BUILD.json')).json();
 check('fixed entry bytes match build manifest',response.ok&&bytes.length===manifest.previewBytes&&crypto.createHash('sha256').update(bytes).digest('hex')===manifest.previewSHA256);
 R.manifest=manifest;const delivery=await page.evaluate(()=>window.__REGIONAL_DELIVERY__);check('loader verified unchanged tested HTML',delivery?.verified&&delivery.sha256===manifest.renderedSHA256&&delivery.bytes===manifest.renderedBytes&&manifest.renderedSHA256==='5b8769dce62a072562ac41de70a087c68216328e2fc580202831ba751050c709');
 check('loader retains document URL and origin',page.url()===URL&&delivery.documentURL===URL&&await page.evaluate(()=>location.origin)===new global.URL(URL).origin);
 const rebuilt=fs.readFileSync('qa-skin-quality-r01/public/preview.html');check('delivery equals rebuilt source bytes',crypto.createHash('sha256').update(rebuilt).digest('hex')===manifest.renderedSHA256);
 check('native pinned model assets loaded without HTTP errors',assetResponses.length>0&&assetResponses.every(x=>x.status>=200&&x.status<400),assetResponses);R.assetResponses=assetResponses;
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);check('mobile viewport keeps native canvas and controls',await page.locator('canvas').count()===1&&await page.locator('[data-r]').count()===5);await page.screenshot({path:OUT+'/mobile-viewport.png'});R.screenshots.push('mobile-viewport.png');
 const bad=await browser.newPage();await bad.route('**/preview-parts/part-000.txt',r=>r.fulfill({status:200,contentType:'text/plain',body:'corrupted validation fixture'}));await bad.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});await bad.waitForSelector('[data-failed="true"]',{timeout:60000});check('corrupt part rejected before native app execution',await bad.locator('canvas').count()===0&&await bad.evaluate(()=>!window.__IDENTITY_QA__));await bad.close();
 }
 R.pass=true;
})().catch(e=>{R.pass=false;R.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{if(page&&!R.pass)await page.screenshot({path:OUT+'/failure.png'}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(OUT+'/report.json',JSON.stringify(R,null,2));console.log(JSON.stringify(R));});
