const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'../..'),OUT='qa-skin-quality-r01/regions',URL='http://127.0.0.1:8765/kaopu-unified-human-workbench/identity-lab/preview.html';fs.mkdirSync(OUT,{recursive:true});
const R={version:'regional-skin/r02',baseline:'2702e9482cfd1655411bb0920929872669301334',checks:[],shots:[],errors:[],warnings:[],filmQualityAccepted:false,physicalGPU:false};let browser,page;
const check=(name,pass,detail)=>{R.checks.push({name,pass:!!pass,detail});assert(pass,name+' '+JSON.stringify(detail));console.log('CHECK',name);};
async function pixels(){return page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer();v.render();const gl=v.renderer.getContext(),data=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,data);if(gl.getError()!==gl.NO_ERROR)throw Error('Regional WebGL error');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),x=>x.toString(16).padStart(2,'0')).join('');});}
async function state(){return page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer(),m=__IDENTITY_QA__.model(),a=fullCommonWorkbench.archive();delete a.regionalSkin;const hash=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',x)),v=>v.toString(16).padStart(2,'0')).join('');return{geometry:await hash(m.positions),faces:await hash(m.faces),archive:JSON.stringify(a),camera:v.cameraState(),lights:v.scene.children.filter(x=>x.isLight).map(x=>[x.type,x.position.toArray(),x.color.toArray(),x.intensity])};});}
async function shot(name){const s=await state();s.pixels=await pixels();await page.locator('#canvas').screenshot({path:OUT+'/'+name+'.png'});R.shots.push({name,...s,archive:crypto.createHash('sha256').update(s.archive).digest('hex')});return s;}
async function view(v){await page.evaluate(v=>{const m=__IDENTITY_QA__.model();if(v==='face')fullCommonWorkbench.view('face');else if(v==='eyes')m.eyeSurface.viewEyes();else m.faceSurface.featureView(v);},v);}
async function light(kind){await page.evaluate(kind=>{const v=__IDENTITY_QA__.viewer(),ls=v.scene.children.filter(x=>x.isLight),ds=ls.filter(x=>x.isDirectionalLight);ls.filter(x=>x.isHemisphereLight).forEach(x=>x.intensity=kind==='neutral'?.65:.18);ds.forEach(x=>x.intensity=0);ds[0].color.setRGB(1,1,1);ds[0].intensity=3.2;ds[0].position.fromArray(kind==='neutral'?[-2,3,4]:[4,1,.1]);v.render();},kind);}
(async()=>{
 check('ET13 native preview byte unchanged',crypto.createHash('sha256').update(fs.readFileSync(ROOT+'/identity-lab/preview.html')).digest('hex')==='99942c121ec46428e980568a6b0b82c5872359bf1a7576f600ac5fa1a4a952ad');
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.on('pageerror',e=>R.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')R.errors.push(m.text());if(m.type()==='warning')R.warnings.push(m.text());});
 await page.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__IDENTITY_QA__?.viewer()&&window.fullCommonWorkbench?.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});await page.evaluate(()=>fullFaceTransfer.ready());
 await page.evaluate(async()=>{await fullCommonWorkbench.motion().setMode('shape');const mod=await import('../skin-quality-r01/SkinSampling.mjs');window.__SAMPLING__=await mod.attachSkinSampling(__IDENTITY_QA__.viewer().skin);});await view('face');await light('neutral');
 const baseline=await shot('00-sampling-baseline');
 await page.evaluate(async()=>{const mod=await import('../skin-quality-r01/regions/RegionalSkin.mjs');window.__REGION_MOD__=mod;window.__REGION__=mod.installRegionalSkin(__IDENTITY_QA__.model());mod.attachRegionalSkin(__IDENTITY_QA__.viewer().skin,__REGION__);window.__REGION_UI__=mod.mountRegionalControls(__REGION__);window.__REGION_SAVED__=fullCommonWorkbench.archive();});
 const first=await shot('01-regional-candidate');check('native geometry and original identity archive unchanged',baseline.geometry===first.geometry&&baseline.faces===first.faces&&baseline.archive===first.archive);check('native 89 face controls retained',await page.evaluate(()=>identityWorkbench.catalog().length===89));check('five regional controls mounted on same platform',await page.locator('[data-r]').count()===5);check('all 5 surface controls compile',await page.evaluate(()=>__REGION__.report().materials[0].compiles>0));
 await page.evaluate(()=>__REGION__.set({enabled:false}));check('disabled region exactly restores sampling baseline',await pixels()===baseline.pixels);
 // Strict same-camera/light A/B over whole face and special regions.
 for(const v of ['face','nose','mouth','eyes','oblique']){await view(v);for(const l of ['neutral','grazing']){await light(l);await page.evaluate(()=>__REGION__.set({enabled:false}));const a=await shot(v+'-'+l+'-before');await page.evaluate(()=>__REGION__.set({enabled:true}));const b=await shot(v+'-'+l+'-after');check(v+' '+l+' same identity camera lights',JSON.stringify({...a,pixels:0})===JSON.stringify({...b,pixels:0}));check(v+' '+l+' real framebuffer responds',a.pixels!==b.pixels);}}
 await light('neutral');await view('face');await page.evaluate(()=>__REGION__.inspect(true));await shot('region-masks');await page.evaluate(()=>__REGION__.inspect(false));
 const maskReport=await page.evaluate(()=>{const m=__IDENTITY_QA__.model(),f=m.faceSurface.fields,g=__IDENTITY_QA__.viewer().skin.fields;let leak=0,n=0;for(let i=0;i<m.vertexCount;i++){if(g.types[i]>.5&&(f.a[i*4]||g.regions[i*4]))leak++;if(f.a[i*4+2]>.05)n++;}return{nonSkinFaceMaskVertices:leak,orbitalVertices:n};});check('native regions exclude eyeballs teeth and tongue',maskReport.nonSkinFaceMaskVertices===0&&maskReport.orbitalVertices>0,maskReport);
 const orbitalBounds=await page.evaluate(async()=>{const {regionalMasks}=await import('../skin-quality-r01/regions/RegionalRules.mjs'),m=__IDENTITY_QA__.model(),v=__IDENTITY_QA__.viewer(),f=m.faceSurface.fields,g=v.skin.fields,e=v.skin.regionalExtension.report().orbitalWindows.map(p=>[p.x,p.y,p.z,p.w]);let old=0,now=0,foreheadLeak=0;for(let i=m.bodyCount;i<m.vertexCount;i++){if(f.a[i*4+2]>.05)old++;const r=regionalMasks({face:f.a[i*4],cover:g.regions[i*4],type:g.types[i],thin:f.a[i*4+2],x:f.rest[i*3]*1000,y:f.rest[i*3+1]*1000,eyes:e});if(r.orbital>.05)now++;const recipe=m.canonical.gnmRecipes[i-m.bodyCount],nativeIndex=recipe[2]>.5?recipe[1]:recipe[0],name=m.gnm.meta.regionNames[m.gnm.regionId[nativeIndex]];if(name==='forehead'&&r.orbital>.01)foreheadLeak++;}return{originalThinVertices:old,localOrbitalVertices:now,foreheadLeak};});
 check('orbital windows remove broad cheek and forehead spill',orbitalBounds.localOrbitalVertices>0&&orbitalBounds.localOrbitalVertices<orbitalBounds.originalThinVertices*.75&&orbitalBounds.foreheadLeak===0,orbitalBounds);

 // Parameters tested through actual native panel input, not only JS uniforms.
 for(const key of ['lipDryness','lipBorderBlend','orbitalMicrorelief','orbitalRoughness','alarOil']){
  await view(key.startsWith('lip')?'mouth':key==='alarOil'?'nose':'eyes');await page.evaluate(()=>__REGION__.set({...__REGION_MOD__.DEFAULTS}));const input=page.locator(`[data-r="${key}"]`);const before=await pixels();const prior=await state();await input.evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input',{bubbles:true}));});const after=await pixels();check('panel parameter changes pixels '+key,before!==after);const now=await state();check('parameter retains original geometry and archive '+key,prior.geometry===now.geometry&&prior.archive===now.archive);await shot('control-'+key);
 }
 await view('mouth');await page.evaluate(()=>__REGION__.set({...__REGION_MOD__.DEFAULTS,lipFiltering:false}));const lipBefore=await shot('lip-filter-before');await page.evaluate(()=>__REGION__.set({lipFiltering:true}));const lipAfter=await shot('lip-filter-after');check('existing lip furrow filter changes pixels without new grooves',lipBefore.pixels!==lipAfter.pixels&&lipBefore.archive===lipAfter.archive);
 await page.evaluate(()=>__REGION__.set({...__REGION_MOD__.DEFAULTS}));const archive=await page.evaluate(()=>fullCommonWorkbench.archive()),a=await pixels();await page.evaluate(()=>__REGION__.set({lipDryness:0,alarOil:1,orbitalRoughness:-.08}));await page.evaluate(a=>fullCommonWorkbench.restore(a),archive);check('complete archive restores exact regional framebuffer',await pixels()===a);check('regional settings survive archive',JSON.stringify(await page.evaluate(()=>__REGION__.settings))===JSON.stringify(archive.regionalSkin.settings));check('native panel stays synchronized after restore',await page.evaluate(()=>Array.from(document.querySelectorAll('[data-r]')).every(el=>Math.abs(+el.value-__REGION__.settings[el.dataset.r])<1e-6)));
 const invalid=JSON.parse(JSON.stringify(archive));invalid.regionalSkin.settings.alarOil=5;check('invalid archive rejected',await page.evaluate(a=>{try{fullCommonWorkbench.restore(a);return false}catch{return true}},invalid));check('invalid archive leaves exact pixels',await pixels()===a);
 await page.evaluate(()=>__REGION__.set({enabled:false}));const base=await pixels();for(let n=0;n<3;n++){await page.evaluate(()=>__REGION__.set({enabled:true}));await pixels();await page.evaluate(()=>__REGION__.set({enabled:false}));check('repeat rollback '+n,await pixels()===base);}
 const legacy=JSON.parse(JSON.stringify(archive));delete legacy.regionalSkin;await page.evaluate(a=>fullCommonWorkbench.restore(a),legacy);check('legacy archive safely opts out',await page.evaluate(()=>!__REGION__.settings.enabled));check('legacy archive exact baseline',await pixels()===base);
 await page.evaluate(a=>fullCommonWorkbench.restore(a),archive);await view('face');await light('neutral');await page.screenshot({path:OUT+'/native-panel-desktop.png'});check('single native canvas',await page.locator('canvas').count()===1);R.final=await page.evaluate(()=>__REGION__.report());check('no JavaScript or WebGL errors',R.errors.length===0,R.errors);R.pass=true;
})().catch(e=>{R.pass=false;R.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{if(page&&!R.pass)await page.screenshot({path:OUT+'/failure.png'}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(OUT+'/report.json',JSON.stringify(R,null,2));console.log(JSON.stringify({pass:R.pass,checks:R.checks.length,failure:R.failure,errors:R.errors}));});
