const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('playwright');
const OUT='joey-manual-r03-results';fs.mkdirSync(OUT,{recursive:true});
const edits=[['head-scale-horiz-incr',-.12],['head-scale-vert-incr',.04],['chin-height-incr',-.04],['nose-width3-incr',-.30],['nose-scale-depth-incr',-.10],['l-eye-scale-incr',.25],['r-eye-scale-incr',.25],['l-eye-height2-incr',.02],['r-eye-height2-incr',.02],['l-eye-height3-incr',.03],['r-eye-height3-incr',.03]];
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1080}});page.setDefaultTimeout(360000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto('http://127.0.0.1:8765/native/kaopu-unified-human-workbench/');await page.evaluate(()=>fullCommonWorkbench.load());await page.waitForFunction(()=>fullCommonWorkbench?.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy&&fullCommonWorkbench.motion());await page.evaluate(()=>fullCommonWorkbench.motion().setMode('shape'));const original=await page.evaluate(()=>fullCommonWorkbench.archive());
const input=JSON.parse(fs.readFileSync(path.join(__dirname,'archives/manual-r02-archive.json'),'utf8'));await page.evaluate(a=>fullCommonWorkbench.restore(a),input);
const result=await page.evaluate(({edits})=>{const a=fullCommonWorkbench,body=a.motion().controller.model,before=a.positions();for(const[k,v]of edits)a.set('anny.localChanges:'+k,v);const shape=a.archive(),measure=()=>{const p=a.positions();let min=Infinity,max=-Infinity,imin=-1,imax=-1;for(let i=0;i<p.length;i+=3){if(p[i+2]<min){min=p[i+2];imin=i/3;}if(p[i+2]>max){max=p[i+2];imax=i/3;}}return{heightM:max-min,minZ:min,maxZ:max,minVertex:imin,maxVertex:imax};};const heightBefore=measure(),trace=[];let lo=0,hi=1;for(let i=0;i<22;i++){const value=(lo+hi)/2;a.set('anny.phenotypes:height',value);const q=measure();trace.push({value,...q});if(q.heightM<1.72)lo=value;else hi=value;}const height=measure(),saved=a.archive(),p=a.positions();let max=0;for(let i=0;i<p.length;i++){if(!Number.isFinite(p[i]))throw Error('nonfinite');max=Math.max(max,Math.abs(p[i]-before[i]));}return{schema:'joey-manual-native/3',edits,archive:saved,heightBefore,height,heightTrace:trace,maxCoordinateChangeIncludingHeightM:max,identityLikenessAccepted:false,heightTargetM:1.72,heightMethod:'neutral original native mesh vertical Z extent, no hair/shoes/clothes, not a photogrammetric person measurement',expressionFrozen:true,gnmIdentityFrozen:true,manualArtistPass:true,nose30AndOuterCanthus45Excluded:true,pixelAudit:a.pixelAudit()};},{edits});
assert(Math.abs(result.height.heightM-1.72)<.00001);assert.equal(result.pixelAudit.error,0);await page.evaluate(a=>fullCommonWorkbench.restore(a),result.archive);assert.deepEqual(await page.evaluate(()=>fullCommonWorkbench.archive()),result.archive);result.exactArchiveReadback=true;
await page.evaluate(()=>fullCommonWorkbench.view('face'));const base=await page.evaluate(()=>fullCommonWorkbench.camera());for(const[v,angle]of[['front',0],['three',.48],['side',Math.PI/2]]){const c=structuredClone(base),dist=Math.hypot(...c.position.map((x,i)=>x-c.target[i]));c.position=[c.target[0]+Math.sin(angle)*dist,c.target[1],c.target[2]+Math.cos(angle)*dist];await page.evaluate(c=>fullCommonWorkbench.motion().viewer.restoreCamera(c),c);await page.screenshot({path:path.join(OUT,`manual-r03-${v}-page.png`)});const clip=await page.evaluate(()=>{const b=fullCommonWorkbench.motion().viewer.canvas.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height};});await page.screenshot({path:path.join(OUT,`manual-r03-${v}.png`),clip});}
fs.writeFileSync(path.join(OUT,'manual-r03-archive.json'),JSON.stringify(result.archive,null,2));await page.evaluate(a=>fullCommonWorkbench.restore(a),original);assert.deepEqual(await page.evaluate(()=>fullCommonWorkbench.archive()),original);result.originalRestoredExactly=true;result.errors=errors;assert.equal(errors.length,0);fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({pass:true,height:result.height,likeness:false}));
}catch(e){fs.writeFileSync(path.join(OUT,'failure.json'),JSON.stringify({error:e.stack,errors}));throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
