/* Isolated original-engine observation probe. No subject fit; no model setters. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const OUT=process.env.JOEY_OUT||'joey-native-probe-results';fs.mkdirSync(OUT,{recursive:true});
const BASE=process.env.JOEY_URL||'http://127.0.0.1:8765/native/kaopu-unified-human-workbench/';
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1080}});page.setDefaultTimeout(360000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(BASE);await page.evaluate(()=>window.fullCommonWorkbench.load());await page.waitForFunction(()=>{const a=window.fullCommonWorkbench;return a?.diagnostics().ready&&!a.diagnostics().busy&&a.motion();});
const result=await page.evaluate(()=>{const a=window.fullCommonWorkbench,m=a.motion().controller.model,g=m.gnm;const archive=a.archive();const source=new Float32Array(g.landmarkIndices.length);g.computeLandmarks(m.headNative,source);const template=new Float32Array(source.length);g.computeLandmarks(g.template,template);
const inverse=new Map();for(let hi=0;hi<m.canonical.gnmRecipes.length;hi++){const [x,y,t]=m.canonical.gnmRecipes[hi];if(x===y&&t===0){if(!inverse.has(x))inverse.set(x,[]);inverse.get(x).push(m.bodyCount+hi);}}
const common=[],missing=[];for(let l=0;l<source.length/3;l++){let v=[0,0,0],ok=true;for(let k=0;k<3;k++){const src=g.landmarkIndices[l*3+k],ids=inverse.get(src);if(!ids?.length){ok=false;missing.push({landmark:l,sourceVertex:src});continue;}for(let d=0;d<3;d++)v[d]+=m.positions[ids[0]*3+d]*g.landmarkWeights[l*3+k];}common.push(ok?v:null);}
const jacobian=[];const stride=g.numVertices*3;for(let l=0;l<source.length/3;l++)for(let d=0;d<3;d++){const row=[];for(let i=0;i<g.identityDim;i++){let sum=0;for(let k=0;k<3;k++)sum+=g.landmarkWeights[l*3+k]*g.identityBasis[i*stride+g.landmarkIndices[l*3+k]*3+d]*g.identityScales[i];row.push(sum);}jacobian.push(row);}
const expressionAxes=a.catalog().filter(r=>r.group==='gnm.expression'&&r.label.startsWith('lower_face_region_')).map(r=>Number(r.key.split(':')[1]));const expressionJacobian=[];for(let l=0;l<source.length/3;l++)for(let d=0;d<3;d++){const row=[];for(const i of expressionAxes){let sum=0;for(let k=0;k<3;k++)sum+=g.landmarkWeights[l*3+k]*g.expressionBasis[i*stride+g.landmarkIndices[l*3+k]*3+d]*g.expressionScales[i];row.push(sum);}expressionJacobian.push(row);}
return{lowerFaceExpressionAxes:expressionAxes,lowerFaceBindLandmarkJacobian:expressionJacobian,schema:'joey-native-readonly-probe/1',targetCommit:'0b4703359efbae10ffc6c0e5fe3fc081e7eca4fe',subjectFitted:false,archive,catalog:a.catalog().map(r=>({...r,status:a.parameterStatus(r.key)})),diagnostics:a.diagnostics(),sourceLandmarks:Array.from(source),templateLandmarks:Array.from(template),commonLandmarks:common,missing,landmarkIndices:Array.from(g.landmarkIndices),landmarkWeights:Array.from(g.landmarkWeights),bindLandmarkIdentityJacobian:jacobian,jacobianScope:'native bind-pose only, not final posed/shared common derivative',dimensions:{identity:g.identityDim,expression:g.expressionDim,sourceVertices:g.numVertices,commonVertices:m.positions.length/3,landmarks:source.length/3},camera:a.camera(),stateUnchanged:JSON.stringify(archive)===JSON.stringify(a.archive())};});
assert.equal(result.dimensions.identity,253);assert.equal(result.dimensions.landmarks,68);assert(result.stateUnchanged);assert.equal(result.missing.length,0,'all landmark source vertices must exactly survive recipes');fs.writeFileSync(path.join(OUT,'native-observation.json'),JSON.stringify(result));
await page.evaluate(()=>window.fullCommonWorkbench.view('face'));await page.screenshot({path:path.join(OUT,'native-face-before.png'),fullPage:true});
const projected=await page.evaluate(common=>{const v=fullCommonWorkbench.motion().viewer;v.scene.updateMatrixWorld(true);const box=v.canvas.getBoundingClientRect();return common.map((p,i)=>{const q=v.camera.position.clone().set(p[0],p[2],-p[1]).applyMatrix4(v.mesh.matrixWorld).project(v.camera);return {i,x:box.x+(q.x+1)*box.width/2,y:box.y+(1-q.y)*box.height/2,z:q.z};});},result.commonLandmarks);fs.writeFileSync(path.join(OUT,'projected-landmarks.json'),JSON.stringify(projected));
await page.evaluate(points=>{const layer=document.createElement('div');layer.id='joey-test-landmark-overlay';Object.assign(layer.style,{position:'absolute',inset:'0',pointerEvents:'none',zIndex:'99999'});for(const p of points){const n=document.createElement('span');n.textContent=p.i;Object.assign(n.style,{position:'absolute',left:p.x+'px',top:p.y+'px',color:'#00ffff',font:'11px monospace',textShadow:'1px 1px #000'});layer.append(n);}document.body.append(layer);},projected);await page.screenshot({path:path.join(OUT,'native-landmark-numbering.png'),fullPage:true});
fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify({passed:true,targetCommit:result.targetCommit,errors,stateUnchanged:result.stateUnchanged,dimensions:result.dimensions,subjectFitted:false},null,2));console.log(JSON.stringify({passed:true,dimensions:result.dimensions}));
}catch(e){fs.writeFileSync(path.join(OUT,'failure.json'),JSON.stringify({error:e.stack,errors}));await page.screenshot({path:path.join(OUT,'failure.png')}).catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
