import {DEFAULT_SKIN,PRESETS,skinAttributes,createSkin} from './SkinMaterial.js';
import * as THREE from 'three';import {OrbitControls} from '../vendor/OrbitControls.js';import {AnnyModel} from './AnnyModel.js';import {GNMHeadModel,parseContainer} from './GNMModel.js';import {UnifiedModel,DEFAULT_STATE,validateProfile} from './UnifiedModel.js';
const skin=DEFAULT_SKIN();let skinRuntime,skinStats,keyLight,rimLight;const $=id=>document.getElementById(id),state=DEFAULT_STATE();let model,renderer,scene,camera,orbit,mesh,geometry,wire=false,seam=false,busy=false,loadCount=0,lost=false;
const GNM_URL=new URLSearchParams(location.search).get('local')==='1'?'../kaopu-face-workbench/assets/gnm_head_web.bin':'https://raw.githubusercontent.com/xrblocks/assets-gnm/134feb02b11fa642a43ff5e7e880246255a74e86/gnm_head_web.bin';
const render=()=>{if(renderer&&model&&!lost)renderer.render(scene,camera);};
function init(){if(renderer)return;renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x242c32);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(31,1,.01,50);orbit=new OrbitControls(camera,$('canvas'));orbit.enableDamping=false;orbit.addEventListener('change',render);scene.add(new THREE.HemisphereLight(0xdfefff,0x353945,.7));const key=keyLight=new THREE.DirectionalLight(0xffdac1,3.2);key.position.set(-2,3,4);scene.add(key);const rim=rimLight=new THREE.DirectionalLight(0xa3c2df,2.6);rim.position.set(2,2,-2);scene.add(rim);new ResizeObserver(resize).observe($('stage'));}
function resize(){if(!renderer)return;const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render();}
function view(which='front'){if(!model)return;let box=new THREE.Box3().setFromBufferAttribute(geometry.attributes.position);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());let distance=Math.max(size.y,size.x/camera.aspect)/(2*Math.tan(camera.fov*Math.PI/360))*1.16;const angle=which==='side'?Math.PI/2:which==='three'?.48:0;if(which==='face'){center.set(0,box.max.y-.14,0);distance=.78;}if(which==='detail'){center.set(.023,box.max.y-.15,.11);distance=.235;}camera.position.copy(center).add(new THREE.Vector3(Math.sin(angle)*distance,0,Math.cos(angle)*distance));orbit.target.copy(center);camera.zoom=1;camera.updateProjectionMatrix();orbit.update();render();}
const toDisplay=v=>{const p=new Float32Array(v.length);for(let i=0;i<v.length;i+=3){p[i]=v[i];p[i+1]=v[i+2];p[i+2]=-v[i+1];}return p;};
function update(){if(!model)return;model.compute(state);geometry.attributes.position.array.set(toDisplay(model.positions));geometry.attributes.position.needsUpdate=true;geometry.computeVertexNormals();geometry.computeBoundingSphere();const m=model.metrics();$('metrics').textContent=`角色 ${state.personId}\n顶点 ${m.vertices.toLocaleString()} · 三角形 ${m.triangles.toLocaleString()}\n颈缝 ${m.seamTriangles} 面 · 边界边全部双侧相接\n最大颈缝边长 ${m.maxSeamEdgeMM.toFixed(2)} mm\n最小颈缝面面积 ${m.minSeamTriangleAreaMM2.toFixed(3)} mm²\n下颈轮廓调整最大 ${m.neckContourMaxMM.toFixed(2)} mm\n局部平顺最大 ${m.neckFairingMaxMM.toFixed(2)} mm\n头部统一尺寸倍率 ${m.headScale.toFixed(3)}\n拓扑 SHA-256 ${m.topologySha256.slice(0,24)}…`;$('status').textContent='同一共模 · 程序化皮肤材质 · 微表面凹凸 / 分区油脂 / 血色 · 非真实 SSS';render();}
async function checkedFetch(url,hash,expectedBytes=null){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),120000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('HTTP '+r.status+' '+url);const b=await r.arrayBuffer();if(expectedBytes!==null&&b.byteLength!==expectedBytes)throw Error('资产长度不一致');if(hash){const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');if(actual!==hash)throw Error('资产校验不一致');}return b;}finally{clearTimeout(timeout);}}
async function annyCompressed(meta){const info=meta.binary.compressed;if(!info.parts)return checkedFetch('../kaopu-anny-workbench/assets/anny-model.bin.gz',info.sha256,info.byteLength);const joined=new Uint8Array(info.byteLength);let offset=0;for(let i=0;i<info.parts.length;i++){const part=info.parts[i],url=new URL(part.url,new URL('../kaopu-anny-workbench/',location.href));const b=await checkedFetch(url,part.sha256,part.byteLength);if(offset+b.byteLength>joined.length)throw Error('Anny分片超出总长度');joined.set(new Uint8Array(b),offset);offset+=b.byteLength;$('progress').value=offset/joined.length;}if(offset!==joined.length)throw Error('Anny分片不完整');const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',joined)),x=>x.toString(16).padStart(2,'0')).join('');if(actual!==info.sha256)throw Error('Anny完整压缩包校验失败');return joined.buffer;}
async function gzipJson(url,compressedHash,rawHash){const gz=await checkedFetch(url,compressedHash),b=await new Response(new Blob([gz]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();const h=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');if(h!==rawHash)throw Error('解压资产校验不一致');return JSON.parse(new TextDecoder().decode(b));}
async function load(){if(busy||model)return;busy=true;loadCount++;$('retry').hidden=true;try{init();const fingerprint=await fetch('./assets/adapter-fingerprint.json').then(r=>{if(!r.ok)throw Error('Adapter fingerprint unavailable');return r.json()});const [am,c,mhr]=await Promise.all([fetch('../kaopu-anny-workbench/assets/anny-model.json').then(r=>{if(!r.ok)throw Error('Anny metadata HTTP '+r.status);return r.json()}),gzipJson('./assets/canonical.json.gz',fingerprint.inputs.canonicalCompressed,fingerprint.inputs.canonical),gzipJson('./assets/mhr-torso-delta.json.gz',fingerprint.inputs.mhrProjectionCompressed,fingerprint.inputs.mhrProjection)]);if(am.binary.sha256!==fingerprint.inputs.annyBinary)throw Error('Anny adapter version mismatch');const [gz,gb]=await Promise.all([annyCompressed(am),checkedFetch(GNM_URL,'fd19f46eef6f8bfb725fceab581e1bc8837209997ca3fd43f3c1735003c86961')]);const ab=await new Response(new Blob([gz]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();if(ab.byteLength!==am.binary.byteLength)throw Error('Anny解压长度异常');const rawHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',ab)),x=>x.toString(16).padStart(2,'0')).join('');if(rawHash!==am.binary.sha256)throw Error('Anny解压校验失败');const g=parseContainer(gb);model=new UnifiedModel(new AnnyModel(am,ab),new GNMHeadModel(g.meta,g.sections),c,mhr,fingerprint);model.compute(state);geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(toDisplay(model.positions),3));geometry.setIndex(new THREE.BufferAttribute(model.faces,1));geometry.computeVertexNormals();const colors=new Float32Array(model.vertexCount*3);const base=new THREE.Color(0xbab3a5);for(let i=0;i<model.vertexCount;i++)colors.set([base.r,base.g,base.b],i*3);geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));skinStats=skinAttributes(model,geometry);skinRuntime=createSkin(skin);mesh=new THREE.Mesh(geometry,skinRuntime.material);scene.add(mesh);$('loading').hidden=true;update();resize();view('face');}catch(e){$('loading').firstChild.textContent='载入失败：'+e.message;$('retry').hidden=false;$('status').textContent='未就绪，可重试';}finally{busy=false;}}
const controls=['age','weight','muscle','arms','turn','knee','expression','eye','identity','mhr'];function sync(){for(const id of controls){const v=['age','weight','muscle'].includes(id)?state.phenotypes[id]:id==='expression'?state.headExpression[200]:id==='eye'?state.headExpression[0]:id==='identity'?state.headIdentity[0]:id==='mhr'?state.mhr.amount:id==='arms'?-(state.pose['upperarm01.L']?.[2]||0):id==='turn'?(state.pose.head?.[2]||0):id==='knee'?(state.pose['lowerleg01.L']?.[0]||0):0;$(id).value=v;$(id+'Value').value=Number(v).toFixed(2);}}
for(const id of controls)$(id).oninput=()=>{const v=Number($(id).value);$(id+'Value').value=v.toFixed(2);if(['age','weight','muscle'].includes(id))state.phenotypes[id]=v;else if(id==='expression')state.headExpression[200]=v;else if(id==='eye')state.headExpression[0]=v;else if(id==='identity')state.headIdentity[0]=v;else if(id==='mhr')state.mhr={amount:v,channel:'identity_000'};else if(id==='arms'){state.pose['upperarm01.L']=[0,0,-v];state.pose['upperarm01.R']=[0,0,v];}else if(id==='turn')state.pose.head=[0,0,v];else if(id==='knee')state.pose['lowerleg01.L']=[v,0,0];update();};
$('baseline').onclick=()=>{Object.assign(state,DEFAULT_STATE());sync();update();view('three');};$('retry').onclick=load;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('wire').onclick=()=>{wire=!wire;if(mesh)mesh.material.wireframe=wire;$('wire').setAttribute('aria-pressed',wire);render();};$('seam').onclick=()=>{seam=!seam;if(!model)return;const c=geometry.attributes.color,base=new THREE.Color(0xbab3a5),highlight=new Set([...model.canonical.bodyRing,...model.canonical.headRing]);for(let i=0;i<model.vertexCount;i++)c.setXYZ(i,...(seam&&highlight.has(i)?[.9,.32,.08]:[base.r,base.g,base.b]));c.needsUpdate=true;$('seam').setAttribute('aria-pressed',seam);render();};
function download(name,s,type='text/plain'){const u=URL.createObjectURL(new Blob([s],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
$('exportProfile').onclick=()=>download('kaopu-unified-person.json',JSON.stringify({...state,topologySha256:model?.canonical.topologySha256,adapterFingerprint:model?.adapterFingerprint},null,2),'application/json');$('exportObj').onclick=()=>{if(!model)return;const l=['# KAOPU unified person | metres, Z-up | experimental fixed stitched neck'];for(let i=0;i<model.positions.length;i+=3)l.push('v '+Array.from(model.positions.subarray(i,i+3)).join(' '));for(let i=0;i<model.faces.length;i+=3)l.push('f '+Array.from(model.faces.subarray(i,i+3),x=>x+1).join(' '));download('kaopu-unified-person.obj',l.join('\n'));};
window.unifiedWorkbench={diagnostics:()=>({ready:!!model,loadCount,lost,...model?.metrics()}),positions:()=>model?.positions.slice(),state:()=>structuredClone(state),setState:s=>{Object.assign(state,s);update();},view,pixelAudit:()=>{render();const gl=renderer.getContext(),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);const colors=new Set();for(let i=0;i<p.length;i+=128)colors.add(p[i]+','+p[i+1]+','+p[i+2]);return {colors:colors.size,background:Array.from(p.subarray(0,4)),error:gl.getError()};}};sync();load();

$('canvas').addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;$('status').textContent='图形上下文中断，角色参数与网格保持';});
$('canvas').addEventListener('webglcontextrestored',()=>{requestAnimationFrame(()=>{renderer.setClearColor(0x242c32);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;lost=false;resize();update();});});
$('importProfile').onchange=async()=>{const f=$('importProfile').files[0];if(!f)return;try{if(f.size>100000)throw Error('档案超过100KB');const candidate=validateProfile(JSON.parse(await f.text()),model);Object.assign(state,candidate);sync();update();$('status').textContent='已恢复同一角色档案';}catch(e){$('status').textContent='未导入：'+e.message;}finally{$('importProfile').value='';}};

const skinKeys=['tone','blood','mottle','pores','scale','roughness','freckles','lines','scatter','seed'];
function syncSkin(){for(const k of skinKeys){$('skin-'+k).value=skin[k];$('skin-'+k+'Value').value=skin[k].toFixed(k==='seed'?0:2);}for(const k of ['enabled','colorLayer','microLayer','roughLayer'])$('skin-'+k).checked=skin[k];skinRuntime?.update();render();}
for(const k of skinKeys)$('skin-'+k).oninput=()=>{skin[k]=Number($('skin-'+k).value);syncSkin();};for(const k of ['enabled','colorLayer','microLayer','roughLayer'])$('skin-'+k).onchange=()=>{skin[k]=$('skin-'+k).checked;syncSkin();};
document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{Object.assign(skin,PRESETS[b.dataset.skin]);skin.enabled=true;syncSkin();});
document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{if(!keyLight)return;const mode=b.dataset.light;keyLight.color.set(mode==='cool'?0xb9d7ff:mode==='warm'?0xffc99b:0xffe4cf);keyLight.position.set(mode==='rake'?-3:-2,mode==='back'?1:3,mode==='back'?-3:mode==='rake'?.2:4);keyLight.intensity=mode==='back'?4:3.2;rimLight.intensity=mode==='back'?.5:1.3;render();});
$('skin-export').onclick=()=>download('kaopu-skin-profile.json',JSON.stringify({schema:'kaopu-skin-profile/1',skin,topologySha256:model?.canonical.topologySha256,coordinate:'neutral canonical reference metres',trueSSS:false},null,2),'application/json');
$('leave').onclick=()=>{document.querySelector('.workspace').hidden=true;$('resume').hidden=false;};$('resume').onclick=()=>{document.querySelector('.workspace').hidden=false;$('resume').hidden=true;resize();render();};
window.skinWorkbench={profile:()=>structuredClone(skin),setProfile:p=>{Object.assign(skin,p);syncSkin();},diagnostics:()=>({...skinStats,textures:renderer?.info.memory.textures,geometries:renderer?.info.memory.geometries,programs:renderer?.info.programs.length,contextCount:renderer?1:0,framesUseTime:false}),reference:()=>geometry?.attributes.skinRest.array.slice()};syncSkin();
