import * as THREE from 'three';
import {OrbitControls} from '../voxel-train-study/vendor/OrbitControls.js';
import {createStorm,DURATION} from './scene.mjs';
const $=id=>document.getElementById(id),stage=$('stage');
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch(e){$('loading').textContent='这个浏览器暂时无法启动 WebGL，请用支持三维渲染的浏览器打开';throw e;}
const gl=renderer.getContext(),debugInfo=gl.getExtension('WEBGL_debug_renderer_info'),rendererName=debugInfo?gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL):'';const software=/swiftshader|llvmpipe|software|softpipe/i.test(rendererName),lightweight=innerWidth<700||software;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.setPixelRatio(1);renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;stage.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','可拖动观察的风暴球体');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,80),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enabled=false;controls.minDistance=7;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.76;controls.target.set(0,1.25,0);const storm=await createStorm(scene,{mobile:lightweight,cloudScale:software?6:lightweight?4:3});
let time=2.5,playing=false,free=false,last=performance.now(),frames=0,fpsStart=last,avg=0,contextLost=false,renderFrame=0,renderedTime=-1;
function referenceCamera(){const aspect=stage.clientWidth/stage.clientHeight;const fit=aspect<.8? .8/aspect:1;const d=(10.5+time*.57)*fit;camera.position.set(d*.34,d*.25+1.5,d*.91);camera.lookAt(0,1.3,0);controls.target.set(0,1.3,0);}
function resize(){let w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(!free)referenceCamera();}new ResizeObserver(resize).observe(stage);
function ui(){ $('time').textContent=`${time.toFixed(1)} / 11 秒`;$('scrub').value=time;$('play').textContent=playing?'暂停':'播放';$('play').setAttribute('aria-label',playing?'暂停动画':'播放动画');$('camera').setAttribute('aria-pressed',String(free));$('mode').textContent=free?'自由相机 · 拖动旋转 / 双指缩放':'参考镜头 · 缓慢拉远';}
function toggle(){playing=!playing;ui();}$('play').onclick=toggle;$('reset').onclick=()=>{time=0;playing=true;free=false;controls.enabled=false;referenceCamera();ui();};$('scrub').oninput=e=>{time=Number(e.target.value);playing=false;ui();};$('camera').onclick=()=>{free=!free;controls.enabled=free;if(!free)referenceCamera();ui();};$('info').onclick=()=>{const show=$('notes').hidden;$('notes').hidden=!show;$('info').setAttribute('aria-expanded',String(show));};$('closeInfo').onclick=()=>{$('notes').hidden=true;$('info').setAttribute('aria-expanded','false');$('info').focus();};window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('notes').hidden=true;$('info').setAttribute('aria-expanded','false');}if(e.code==='Space'&& !['INPUT','BUTTON','A'].includes(document.activeElement?.tagName)){e.preventDefault();toggle();}});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;$('loading').hidden=false;$('loading').textContent='三维画面已暂停，请重新载入恢复';});renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;$('loading').hidden=true;renderer.shadowMap.needsUpdate=true;resize();});document.addEventListener('visibilitychange',()=>{last=performance.now();});
function draw(now){requestAnimationFrame(draw);const dt=Math.min((now-last)/1000,.25);last=now;if(document.hidden||contextLost)return;if(playing){time+=dt;if(time>DURATION)time=0;}if(free)controls.update();else referenceCamera();storm.update(time,camera);const needsShadow=renderer.shadowMap.needsUpdate;renderer.shadowMap.needsUpdate=false;storm.renderCloud(renderer,camera);renderer.shadowMap.needsUpdate=needsShadow;renderer.render(scene,camera);renderFrame++;renderedTime=time;ui();if(++frames%60===0){avg=60*1000/(now-fpsStart);fpsStart=now;$('perf').textContent=`${software?'自动轻量':'实时 WebGL'} · ${Math.round(avg)} FPS`;}}
resize();$('loading').hidden=true;ui();requestAnimationFrame(draw);
window.__storm={setDiagnosticNormalStrength(v){storm.setDiagnosticNormalStrength(v);},inspectCamera(pos,target){free=true;controls.enabled=true;controls.target.set(...target);camera.position.set(...pos);controls.update();ui();},setEnvelope(v){storm.setEnvelope(v);},setTime(t){time=THREE.MathUtils.clamp(t,0,DURATION);playing=false;ui();},getState(){return{time,renderFrame,renderedTime,playing,free,stats:storm.stats,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,fps:avg,quality:lightweight?'lightweight':'detailed',softwareRenderer:software,pixelRatio:renderer.getPixelRatio(),camera:camera.position.toArray(),contextLost};},renderer,scene,camera};
