const assert=require('assert'),F=require('../src/field-kernel.js');
function rank1(rows,cols){return{rank:1,rows:[rows],cols:[cols]}}
const W=65,H=33,oneW=Array(W).fill(1),oneH=Array(H).fill(1),zeroW=Array(W).fill(0),lin=Array.from({length:W},(_,i)=>-0.5+i/(W-1));
const fields={};for(const k of ['x','red','green','blue','alpha','roughness','ny','sy'])fields[k]=rank1(oneH,k==='x'?lin:k==='alpha'||k==='ny'||k==='sy'?oneW:Array(W).fill(.5));for(const k of ['y','z','nx','nz','er','eg','eb','sx','sz'])fields[k]=rank1(oneH,zeroW);
const patch={id:'synthetic-boundaries',width:W,height:H,mirrorX:false,domain:Array.from({length:H},()=>[0,20,30,31,44,64]),fields};const doc={schema:'kaopu-source-chart-field-study/0.1',sourceLengthUnits:1,patches:[patch]};
const tests=[];function test(name,fn){try{tests.push({name,pass:true,value:fn()})}catch(e){tests.push({name,pass:false,error:e.stack||e.message})}}
test('thin observed interval survives the far-view budget',()=>{const far=F.conduct(15),q=F.sampleCoordinates(patch,far);let rows=0;for(const row of q.rows){const samples=q.coords.slice(row.start,row.start+row.count),thin=samples.filter(x=>x[0]>=30/64-1e-12&&x[0]<=31/64+1e-12);assert(thin.length>=2);assert(Math.abs(thin[0][0]-30/64)<1e-12);assert(Math.abs(thin.at(-1)[0]-31/64)<1e-12);rows++}return{detail:far.detail,rows,samples:q.coords.length}});
test('old regular far grid would miss the same thin interval',()=>{const Wfar=F.resolution(patch,F.conduct(15)).W;let old=0;for(let x=0;x<Wfar;x++){const u=x/(Wfar-1);if(u>=30/64&&u<=31/64)old++}assert.equal(old,0);return{regularGridWidth:Wfar,thinSamples:old}});
test('every generated coordinate stays in explicit observed parameter domain',()=>{for(const px of [15,100,420])for(const q of F.sampleCoordinates(patch,F.conduct(px)).coords)assert(F.valid(patch,q[0],q[1]));return true});
test('sample count remains monotonic while boundaries persist',()=>{const a=[15,100,420].map(px=>F.fish(doc,F.conduct(px)));assert(a[0].count<a[1].count&&a[1].count<a[2].count);for(const q of a){assert(q.boundaryPreserving);assert(q.patchPlans[0].boundarySamples>0)}return a.map(q=>({count:q.count,boundary:q.patchPlans[0].boundarySamples,detail:q.detail}))});
test('generated payload stays finite at far and near budgets',()=>{for(const px of [15,420]){const q=F.fish(doc,F.conduct(px));assert(q.data.every(Number.isFinite));assert.equal(q.data.length,q.count*18)}return true});
test('invalid or reversed domain intervals are rejected',()=>{assert.throws(()=>F.domainSpans({...patch,domain:Array.from({length:H},()=>[5,4])},.5));assert.throws(()=>F.domainSpans({...patch,domain:Array.from({length:H},()=>[0,65])},.5));return true});
const report={revision:'R03.A-run2',date:'2026-09-19',tests,pass:tests.every(t=>t.pass),scope:'synthetic explicit-domain kernel test only; verifies boundary retention under view budgets, not black-bass source fidelity, anatomy, material fidelity or final rendering'};console.log(JSON.stringify(report,null,2));if(!report.pass)process.exit(1);
