const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const path=require('path'),R=path.resolve(__dirname,'..');const F=require(R+'/src/field-kernel.js'),C=require(R+'/src/coral-kernel.js');
const original=JSON.parse(fs.readFileSync(R+'/FISH_REF001_FIELD_STUDY.json'));const packed=JSON.parse(fs.readFileSync(R+'/FISH_REF001_FIELD_COMPACT.json'));
const decoded=F.decode(packed),tests=[];
function test(name,fn){try{const value=fn();tests.push({name,pass:true,value})}catch(e){tests.push({name,pass:false,error:e.message})}}
test('scalar field finite and deterministic at off-grid queries',()=>{for(const p of decoded.patches)for(const key of Object.keys(p.fields))for(let i=0;i<9;i++){const u=(i+.23)/9,v=(i*.317+.12)%1,a=F.field(p.fields[key],u,v);assert(Number.isFinite(a));assert.equal(a,F.field(p.fields[key],u,v))}return true});
test('explicit quantization bounded at sampled scalar queries',()=>{let m=0;for(let j=0;j<decoded.patches.length;j++)for(const key of Object.keys(decoded.patches[j].fields))for(let i=0;i<7;i++){const u=(i+.23)/7,v=(i*.317+.12)%1,a=F.field(original.patches[j].fields[key],u,v),b=F.field(decoded.patches[j].fields[key],u,v);m=Math.max(m,Math.abs(a-b))}assert(m<.002);return m});
test('corrupt coefficient span rejected',()=>{const p=JSON.parse(fs.readFileSync(R+'/FISH_REF001_FIELD_COMPACT.json'));p.patches[0].fields.x.rows.offset=1e9;assert.throws(()=>F.decode(p));return true});
test('brain longitudinal seam closes in position',()=>{let m=0;for(const seed of [0,1.4])for(let i=1;i<100;i++){const a=C.brainAt(0,i/100,seed),b=C.brainAt(1,i/100,seed);m=Math.max(m,Math.hypot(...a.map((x,j)=>x-b[j])))}assert(m<1e-10);return m});
test('brain finite-difference derivative seam',()=>{let m=0;const e=1e-5;for(let i=1;i<30;i++){const d=u=>{const a=C.brainAt(u+e,i/30),b=C.brainAt(u-e,i/30);return a.map((x,j)=>(x-b[j])/(2*e))};const a=d(0),b=d(1);m=Math.max(m,Math.hypot(...a.map((x,j)=>x-b[j])))}assert(m<1e-6);return m});
test('staghorn seed deterministic',()=>{const a=C.staghorn(13),b=C.staghorn(13);assert.equal(a.count,b.count);assert.equal(crypto.createHash('sha256').update(Buffer.from(a.data.buffer)).digest('hex'),crypto.createHash('sha256').update(Buffer.from(b.data.buffer)).digest('hex'));return a.branches});
test('coral generated samples finite and zero triangle buffers',()=>{for(const c of [C.brain(0),C.brain(1.4),C.staghorn(13)]){assert.equal(c.triangleCount,0);assert(c.data.every(Number.isFinite));assert.equal(c.data.length,c.count*18)}return true});
fs.writeFileSync(R+'/qa/kernel-tests.json',JSON.stringify({revision:'R03.A',tests,pass:tests.every(t=>t.pass),scope:'sampled mathematical checks; no global injectivity, biology, physical material or rendering quality certification'},null,2));console.log(tests);
