const assert=require('assert'),F=require('../src/field-kernel.js');
function rank1(rows,cols){return{rank:1,rows:[rows],cols:[cols]}}
const W=65,H=33,oneW=Array(W).fill(1),oneH=Array(H).fill(1),u=Array.from({length:W},(_,i)=>i/(W-1)),v=Array.from({length:H},(_,i)=>i/(H-1)),zeroW=Array(W).fill(0),k=.42;
const fields={x:rank1(oneH,u),y:rank1(v,oneW),z:rank1(v,u.map(x=>k*x)),red:rank1(oneH,Array(W).fill(.4)),green:rank1(oneH,Array(W).fill(.5)),blue:rank1(oneH,Array(W).fill(.6)),alpha:rank1(oneH,oneW),roughness:rank1(oneH,Array(W).fill(.5)),nx:rank1(oneH,zeroW),ny:rank1(oneH,zeroW),nz:rank1(oneH,oneW),er:rank1(oneH,zeroW),eg:rank1(oneH,zeroW),eb:rank1(oneH,zeroW),sx:rank1(v,u.map(x=>-k*x)),sy:rank1(v.map(y=>-k*y),oneW),sz:rank1(oneH,oneW)};
const domain=Array.from({length:H},(_,i)=>i===17?[0,20,44,64]:[0,64]),patch={id:'warped-sheet',width:W,height:H,mirrorX:false,domain,fields},doc={schema:'kaopu-source-chart-field-study/0.1',sourceLengthUnits:1,patches:[patch]};
const tests=[];function test(name,fn){try{tests.push({name,pass:true,value:fn()})}catch(e){tests.push({name,pass:false,error:e.stack||e.message})}}
test('position-derived normal matches known warped-sheet normal',()=>{let worst=1;for(const q of [[.2,.2],[.5,.4],[.8,.8],[.3,.7]]){const f=F.geometricFrame(patch,q[0],q[1]);const ref=[-k*q[1],-k*q[0],1],L=Math.hypot(...ref),n=ref.map(x=>x/L),d=n.reduce((s,x,i)=>s+x*f.normal[i],0);worst=Math.min(worst,d)}assert(worst>.999);return worst});
test('V derivative stays inside explicit domain and skips invalid adjacent row',()=>{const vv=16/(H-1),step=1/(H-1),f=F.geometricFrame(patch,.5,vv,{dv:step});assert.equal(f.vNeighbours[1],18/(H-1));assert(F.valid(patch,.5,f.vNeighbours[1]));return f.vNeighbours});
test('fish payload uses position-derived geometric normal',()=>{const q=F.fish(doc,F.conduct(100));assert(q.geometryNormalFromPositionField);assert(q.data.every(Number.isFinite));assert(q.patchPlans[0].geometricNormalFallbacks===0);return q.patchPlans[0]});
test('shading normal stays separate from display tangent-plane normal',()=>{const f=F.geometricFrame(patch,.7,.6);assert(f.shadingDeviation>.05);return f.shadingDeviation});
test('thin-domain boundary retention remains intact after normal change',()=>{const thin={...patch,domain:Array.from({length:H},()=>[0,20,30,31,44,64])};const q=F.sampleCoordinates(thin,F.conduct(15));for(const row of q.rows){const s=q.coords.slice(row.start,row.start+row.count).filter(x=>x[0]>=30/64-1e-12&&x[0]<=31/64+1e-12);assert(s.length>=2)}return q.coords.length});
const report={revision:'R03.A-run3',date:'2026-09-19',tests,pass:tests.every(t=>t.pass),scope:'synthetic normal-frame separation and explicit-domain derivative checks only; not a black-bass fidelity or PBR acceptance'};console.log(JSON.stringify(report,null,2));if(!report.pass)process.exit(1);
