/** All controls route to original pattern generation. No render-scale fitting knobs. */
const names={'meta':'构成','shirt':'衣身','collar':'领型','sleeve':'袖型','left':'不对称一侧','pants':'裤装','skirt':'基础裙','pencil-skirt':'合体裙','flare-skirt':'展开裙','godet-skirt':'插片裙','levels-skirt':'分层裙','waistband':'腰头'};
const labels={'shirt.length':'衣长比例','shirt.width':'衣身宽度','shirt.flare':'衣摆展开','sleeve.length':'袖长比例','sleeve.end_width':'袖口宽度','pants.length':'裤长比例','pants.width':'裤腿宽度','pants.flare':'裤脚展开','pants.rise':'裤腰高度','skirt.length':'裙长比例','skirt.ruffle':'腰部褶量','waistband.width':'腰头高度','collar.width':'领口宽度','collar.fc_depth':'前领深度','collar.bc_depth':'后领深度','levels-skirt.level_ruffle':'层间褶量'};
const get=(d,path)=>path.split('.').reduce((v,k)=>v[k],d).v;
export async function mountParameterEditor(host,{readCurrentPaper,apply,onState=()=>{}}){
 const[schema,audit]=await Promise.all([fetch('parameter-schema.json').then(r=>r.json()),fetch('PARAMETER_AUDIT_R043.json').then(r=>r.json())]);
 let paper=null,values={},easeCm=0,waistEaseCm=0,busy=false;const byPath=new Map(schema.parameters.map(p=>[p.path,p])),evidence=new Map(audit.rows.map(p=>[p.path,p]));
 host.innerHTML='<div class="parameter-heading"><strong>原生制版参数</strong><span>改裁片，不缩放人物或成衣</span></div><div class="ease-presets"><button data-ease="0">原版</button><button data-ease="3">舒适松量</button><button data-ease="6">宽松</button></div><label>胸 / 臀制版加放量（cm）<input id="garment-ease" type="number" min="0" max="12" step="0.5" value="0"></label><label>腰头加放量（cm）<input id="waist-ease" type="number" min="0" max="6" step="0.5" value="0"></label><p class="muted">腰头默认不随胸臀加放，防止宽松款失去腰部支承。加大腰围可能需要腰带或松紧结构。</p><details id="all-native-parameters"><summary>全部原生参数 · <span id="parameter-total"></span>项</summary><input id="parameter-search" type="search" placeholder="搜索袖长、裤腰或参数名称"><div id="native-parameter-fields"></div></details><div class="parameter-actions"><button id="apply-native-parameters">生成当前参数的新纸样</button><button id="reset-native-parameters">恢复原款参数</button></div><p id="parameter-feedback" role="status">参数需满足当前领型、袖型和版式的启用条件；纸样变化不等于穿着检查通过。</p>';
 const fields=host.querySelector('#native-parameter-fields'),feedback=host.querySelector('#parameter-feedback');host.querySelector('#parameter-total').textContent=schema.parameters.length;
 function render(){if(!paper)return;const groups=new Map();for(const p of schema.parameters){const group=p.path.split('.')[0];if(!groups.has(group))groups.set(group,[]);groups.get(group).push(p)}fields.replaceChildren();
  for(const[group,params]of groups){const box=document.createElement('details'),summary=document.createElement('summary');summary.textContent=(names[group]||group)+' · '+params.length;box.append(summary);
   for(const p of params){const label=document.createElement('label');label.className='parameter-row';label.dataset.parameter=p.path;const title=document.createElement('span');title.textContent=labels[p.path]||p.path;title.title=p.path;let input;
    if(p.type==='bool'){input=document.createElement('input');input.type='checkbox';input.checked=values[p.path]??get(paper.design,p.path)}
    else if(p.choices){input=document.createElement('select');for(const v of p.choices){const o=document.createElement('option');o.value=JSON.stringify(v);o.textContent=v===null?'无 / 关闭':String(v);input.append(o)}input.value=JSON.stringify(Object.hasOwn(values,p.path)?values[p.path]:get(paper.design,p.path));}
    else{input=document.createElement('input');input.type='number';input.min=Math.min(...p.samplingRange);input.max=Math.max(...p.samplingRange);input.step=p.type==='int'?1:'any';input.value=Object.hasOwn(values,p.path)?values[p.path]:get(paper.design,p.path);}
    input.dataset.path=p.path;input.disabled=busy;input.onchange=()=>{const v=p.type==='bool'?input.checked:p.choices?JSON.parse(input.value):Number(input.value);values[p.path]=v;feedback.textContent='参数已修改；生成新纸样后才能重新缝合。旧结果不会当作新参数成衣。';onState(state());};
    const hint=document.createElement('small');const ev=evidence.get(p.path);hint.textContent=ev?.example?'已有原程序变形实测 · '+ev.example.preset:'条件参数 · 尚未在已测款式中证明生效';label.append(title,input,hint);box.append(label);
   }fields.append(box);
  }
 }
 function state(){return{parameterCount:schema.parameters.length,changedParameters:structuredClone(values),easeCm,waistEaseCm,busy,sourceProgram:'original-GarmentCode-pattern-engine',personScaleControls:0,geometryEffectClaimed:false};}
 async function load(){paper=await readCurrentPaper();values={};easeCm=waistEaseCm=0;host.querySelector('#garment-ease').value=0;host.querySelector('#waist-ease').value=0;render();onState(state());}
 function validate(){for(const[k,v]of Object.entries(values)){const p=byPath.get(k);if(!p)throw Error('未知原生参数 '+k);if(['int','float'].includes(p.type)&&(!Number.isFinite(v)||v<Math.min(...p.samplingRange)||v>Math.max(...p.samplingRange)))throw Error('参数超出原程序范围 '+k);}if(!Number.isFinite(easeCm)||easeCm<0||easeCm>12||!Number.isFinite(waistEaseCm)||waistEaseCm<0||waistEaseCm>6)throw Error('加放量超出当前制版范围。');}
 async function generate(){if(busy)return;try{if(!paper)await load();validate();busy=true;render();host.querySelector('#apply-native-parameters').disabled=true;feedback.textContent='原制版程序正在生成新裁片；首次需载入原 Python 运行时。';await apply(state());}catch(e){feedback.textContent=e.message;}finally{busy=false;host.querySelector('#apply-native-parameters').disabled=false;render();onState(state());}}
 host.querySelector('#garment-ease').onchange=e=>{easeCm=Number(e.target.value);onState(state())};host.querySelector('#waist-ease').onchange=e=>{waistEaseCm=Number(e.target.value);onState(state())};
 for(const b of host.querySelectorAll('[data-ease]'))b.onclick=async()=>{if(!paper)await load();easeCm=Number(b.dataset.ease);host.querySelector('#garment-ease').value=easeCm;feedback.textContent='加放量已准备；点击生成新纸样后，由原求解器重新缝合。';onState(state());};
 host.querySelector('#all-native-parameters').ontoggle=async e=>{if(e.target.open&&!paper)await load()};
 host.querySelector('#parameter-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();for(const n of fields.querySelectorAll('.parameter-row')){n.hidden=q&&!n.textContent.toLowerCase().includes(q)&&!n.dataset.parameter.toLowerCase().includes(q);if(q&&!n.hidden)n.parentElement.open=true;}};
 host.querySelector('#apply-native-parameters').onclick=generate;host.querySelector('#reset-native-parameters').onclick=load;
 return{load,state,generate,set:async(parameters,ease=0,waist=0)=>{if(!paper)await load();values=structuredClone(parameters);easeCm=ease;waistEaseCm=waist;host.querySelector('#garment-ease').value=ease;host.querySelector('#waist-ease').value=waist;validate();render();return state()},feedback:text=>feedback.textContent=text,invalidate:()=>{paper=null;values={};easeCm=waistEaseCm=0;fields.replaceChildren();host.querySelector('#garment-ease').value=0;host.querySelector('#waist-ease').value=0;feedback.textContent='已切换原款式；参数编辑将从该款原纸样读取。';},schema:()=>structuredClone(schema)};
}
