import * as THREE from '../../../vendor/three.module.js';
export const PLANT_SEGMENT=Object.freeze({id:'native-ficus-first-node-r02',fromStation:0,toStation:1,sceneMetres:700,groundY:.081,railHalfClearance:1.6,visibilityRadius:175,sourceSpecies:'Ficus microcarpa',units:'metre',timeSource:'host.elapsed',quality:'Complete native78 juvenile; new explicit KAOPU functional-plant adapter; visual review pending'});
export const PLANT_PLACEMENTS=Object.freeze([Object.freeze({id:'station-rear-young-ficus',chainage:-56.2,z:-9,yaw:0,seed:761014,developmentStage:'juvenile'})]);
const paths=Object.freeze({'plant-operator':'rules/plant-operator.mjs','native-equivalence':'rules/native78-equivalence.mjs','mother-author':'rules/native78-ficus-author.mjs','mother-runtime':'rules/native78-runtime.mjs','three-module':'vendor/three.module.min.js','three-core':'vendor/three.core.min.js'});
const defaultRead=async url=>{const r=await fetch(url);if(!r.ok)throw Error('Plant dependency HTTP '+r.status+' at '+url+' ['+(r.headers.get('content-type')||'unknown content-type')+']');return new Uint8Array(await r.arrayBuffer());};
export function createNativePlantSegment({onChange=()=>{},readBytes=defaultRead,loadCodec=()=>import('./native-codec/codec.mjs'),loadOperator=()=>import('./rules/plant-operator.mjs')}={}){
 const root=new THREE.Group();root.name='KAOPU native young Ficus node R02';let current=null,recipe=null,disposed=false,distance=0,elapsed=0,status='uninitialized',error=null,revision=0,initPromise=null,buildPending=false,loadProof=null,stage='uninitialized',failure=null;
 function emit(){onChange(snapshot());}
 function apply(){root.position.x=-distance;if(current){current.root.visible=Math.abs(recipe.instance.positionM[0]-distance+8)<=PLANT_SEGMENT.visibilityRadius;current.update(elapsed);}}
 async function replaceFromBytes(input){if(disposed)throw Error('Plant segment disposed');const token=++revision;buildPending=true;status=current?'ready':'loading';error=null;failure=null;stage='codec-import';emit();let candidate=null;const begin=performance.now();
  try{const codec=await loadCodec();stage='sqlite-decode';const decoded=await codec.decode(input);if(token!==revision||disposed)throw Error('Plant load superseded');const dependencies=codec.pinnedDependencies(),bytes={};stage='dependency-fetch';await Promise.all(dependencies.map(async d=>{if(!Object.hasOwn(paths,d.id))throw Error('Unregistered plant dependency id');bytes[d.id]=await readBytes(new URL(paths[d.id],import.meta.url));}));stage='dependency-integrity';await codec.verifyDependencyBytes(bytes);const verifiedAt=performance.now();if(token!==revision||disposed)throw Error('Plant load superseded');stage='operator-import';const operator=await loadOperator();stage='native-generation';candidate=await operator.buildNativeFicus(decoded,{verifyResources:codec.verifyResourceBytes});if(token!==revision||disposed){candidate.dispose();candidate=null;throw Error('Plant load superseded');}
   stage='scene-install';candidate.root.position.fromArray(decoded.instance.positionM);candidate.root.rotation.y=decoded.instance.yawRadians;candidate.root.scale.set(1,1,1);candidate.update(elapsed);const prior=current;root.add(candidate.root);current=candidate;candidate=null;recipe=structuredClone(decoded);prior?.dispose();status='ready';stage='ready';buildPending=false;loadProof={containerFormat:'SQLite KAOPU prototype envelope',profile:decoded.schema??decoded.profile,actualKaoPuByteLength:input.byteLength,dependencyBytes:Object.values(bytes).reduce((n,b)=>n+b.byteLength,0),containerAndDependencyValidationMs:verifiedAt-begin,totalLoadMs:performance.now()-begin,rollback:'old instance retained until verified new instance ready',replacementRevision:token};apply();emit();return snapshot();
  }catch(e){candidate?.dispose();if(token===revision&&!disposed){buildPending=false;status=current?'ready':'error';error=String(e?.message||e);failure={stage,message:error,stack:String(e?.stack||''),cause:e?.cause?String(e.cause):null};stage=current?'ready':'error';emit();}throw e;}
 }
 function initialize(){if(disposed)return Promise.reject(Error('Plant segment disposed'));if(!initPromise)initPromise=readBytes(new URL('./native-codec/objects/young-ficus.KaoPu',import.meta.url)).then(replaceFromBytes).catch(e=>{if(!current&&!disposed&&!failure){status='error';error=String(e?.message||e);failure={stage:'container-fetch',message:error,stack:String(e?.stack||''),cause:e?.cause?String(e.cause):null};stage='error';emit();}throw e;});return initPromise;}
 function update(view){if(disposed)return;if(!Number.isFinite(view?.distance)||!Number.isFinite(view?.elapsed)||view.elapsed<0)throw Error('Plants require authoritative finite Session distance and nonnegative elapsed');distance=view.distance;elapsed=view.elapsed;apply();}
 function snapshot(){return{...PLANT_SEGMENT,status,stage,error,failure,buildPending,disposed,distance,elapsed,count:current?1:0,active:current?.root.visible?1:0,worldGeometryScale:1,ownAnimationLoop:false,externalMeshes:false,containsDeclaredImageMaterials:true,loadProof,plants:current?[{id:recipe.instance.id??recipe.instance.instanceId,species:'Ficus microcarpa',chainage:recipe.instance.positionM[0],position:[recipe.instance.positionM[0]-distance,recipe.instance.positionM[1],recipe.instance.positionM[2]],visible:current.root.visible,seed:recipe.profile.seed,recipe,proof:current.snapshot()}]:[]};}
 function dispose(){if(disposed)return;disposed=true;revision++;current?.dispose();current=null;root.clear();root.removeFromParent();status='disposed';}
 return{root,initialize,replaceFromBytes,update,snapshot,dispose};
}
