import{loadCommon}from'../ui/load-common.mjs';import{CommonViewer}from'../ui/Viewer.mjs';import{defaultState}from'../src/State.mjs';import{installNativeAdiposeLayer}from'../shape-r03/NativeAdiposeLayer.mjs';import{installBonyLandmarkLayer}from'../shape-r031/BonyLandmarkLayer.mjs';import{createState}from'../shape-r031/Catalogue.mjs';import{installThoracicVolumeLayer}from'./ThoracicVolume.mjs';
let model,viewer,detail,rest,enabled=false,raised=false;const $=x=>document.getElementById(x);
async function load(){if(model)return;const r=await loadCommon({onProgress:p=>$('status').textContent=Math.round(p.fraction*100)+'%'});model=r.model;installNativeAdiposeLayer(model);installBonyLandmarkLayer(model);installThoracicVolumeLayer(model);model.r03Adipose.set(-.45);model.r031Bony.set(1);model.compute(createState('bony-lean-adult',defaultState));rest=model.positions.slice();viewer=new CommonViewer({canvas:$('canvas'),container:$('stage'),model});viewer.skin.set({enabled:false});detail={dispose(){},recipe:()=>({schema:'r033-thoracic-volume-study/1',geometryChanged:enabled,normalDetail:false}),set:on=>{model.r033Thorax.set(on?1:0);model.r031Bony.set(on?0:1);pose(raised);}};light(0);view(0);$('status').textContent='胸廓宽曲面几何候选；未完成全身或动作适配';}
function light(angle){const l=viewer.scene.children.filter(x=>x.isLight);l[0].intensity=.7;l[1].intensity=3.3;l[1].position.set(Math.sin(angle)*3,2,Math.cos(angle)*3);l[2].intensity=.45;viewer.render();}
function view(angle=0){viewer.view('front');const a=model.r031Bony.last.anchors;viewer.restoreCamera({position:[Math.sin(angle)*1.4,(a.clavicle[2]+a.waist[2])*.5,Math.cos(angle)*1.4],target:[0,(a.clavicle[2]+a.waist[2])*.5,0],zoom:1});}
function pose(value){raised=value;const s=createState('bony-lean-adult',defaultState);if(raised)s.anny.pose={'upperarm01.L':[45,0,0],'lowerarm01.L':[0,25,0]};model.compute(s);viewer.update();viewer.mesh.material=material();viewer.render();}
function material(){return savedMaterial;}let savedMaterial;
async function start(){await load();savedMaterial=viewer.mesh.material;}
function toggle(on){enabled=on;detail.set(on);$('switch').textContent=on?'显示R031旧几何':'显示胸廓新几何';}
$('load').onclick=start;$('switch').onclick=()=>toggle(!enabled);$('raise').onclick=()=>pose(true);$('neutral').onclick=()=>pose(false);$('rotate').onclick=()=>light(-1.1);
window.thoraxStudy={load:start,ready:()=>!!detail,on:toggle,pose,light,view,positions:()=>Array.from(model.positions),rest:()=>Array.from(rest),recipe:()=>detail.recipe(),pixels:()=>viewer.pixelAudit(),surface:()=>({positions:model.positions,triangles:model.faces,posedMatrices:model.lastBodyDriver.rig.posedMatrices,restMatrices:model.lastBodyDriver.rig.restMatrices,space:'CommonPerson metres X right, Y back, Z up',schema:'common-person-actual-surface/1'})};
addEventListener('pagehide',()=>{detail?.dispose();viewer?.dispose();});
