const fs=require('fs'),http=require('http'),path=require('path'),crypto=require('crypto');const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const dir='workbenches/landscape-surface-r5-k4',out=process.env.LM_EVIDENCE||'qa/k4';fs.mkdirSync(out,{recursive:true});const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const server=http.createServer((req,res)=>{try{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(process.cwd(),req.url.split('?')[0])))}catch{res.statusCode=404;res.end('missing')}});
(async()=>{await new Promise(r=>server.listen(8780,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath:process.env.LM_CHROME_PATH||chromium.executablePath(),...(process.env.LM_PUBLIC_URL?{proxy:{server:process.env.HTTPS_PROXY}}:{}),args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const p=await b.newPage({ignoreHTTPSErrors:!!process.env.LM_PUBLIC_URL,viewport:{width:1024,height:720}});p.setDefaultTimeout(120000);const errors=[];p.on('pageerror',e=>{errors.push(String(e));console.log('ERROR',String(e))});let response=await p.goto(process.env.LM_PUBLIC_URL||'http://127.0.0.1:8780/'+dir+'/index.html',{waitUntil:'domcontentloaded',timeout:60000});let externalContentNotice=false;if((await response.text()).includes('External Content Notice')){externalContentNotice=true;[response]=await Promise.all([p.waitForNavigation({waitUntil:'domcontentloaded',timeout:60000}),p.getByRole('button',{name:'Open the page',exact:true}).click()]);}const body=await response.body();if(hash(body)!==hash(fs.readFileSync(dir+'/index.html')))throw Error('content hash mismatch');await p.waitForFunction(()=>window.__LM_READY__||window.__LM_ERROR__,{},{timeout:240000});if(await p.evaluate(()=>!!window.__LM_ERROR__))throw Error(await p.evaluate(()=>window.__LM_ERROR__));await p.evaluate(()=>window.__LM_MICRO__.focus());
const result={sha256:hash(body),public:!!process.env.LM_PUBLIC_URL,externalContentNotice,errors,physicalPhone:false,geometry:await p.evaluate(()=>window.__LM_MICRO__.report)};console.log('READY',result.geometry);
const pixels=()=>p.evaluate(()=>{window.__LM__.auditFrame();return document.querySelector('#view').toDataURL()});
await p.evaluate(()=>window.__LM_MICRO__.set({mode:0}));const base=hash(await pixels());await p.screenshot({path:out+'/original.png'});await p.evaluate(()=>window.__LM_MICRO__.set({mode:3,strength:0}));if(hash(await pixels())!==base)throw Error('A=0 pixel restoration failed');result.zeroStrengthPixelsExact=true;
await p.evaluate(()=>window.__LM_MICRO__.set({strength:1}));const detailed=await p.evaluate(()=>window.__LM_MICRO__.fingerprint());for(const mode of [1,2,3]){await p.evaluate(m=>window.__LM_MICRO__.set({mode:m}),mode);const h=hash(await pixels());if(h===base)throw Error('mode does not affect image '+mode);result['mode'+mode+'Hash']=h;await p.screenshot({path:out+'/mode-'+mode+'.png'});}
await p.evaluate(()=>{window.__LM_MICRO__.set({quad:true});document.body.classList.remove('mm-open');});await p.screenshot({path:out+'/four-state.png'});await p.evaluate(()=>{window.__LM_MICRO__.set({quad:false});document.body.classList.add('mm-open');window.__LM_MICRO__.focus(true)});await p.screenshot({path:out+'/side.png'});await p.locator('#mmSectionButton').click();result.sectionSegments=await p.evaluate(()=>window.__LM_MICRO__.section());await p.screenshot({path:out+'/section.png'});await p.locator('#mmSectionClose').click();
await p.evaluate(()=>window.__LM__.setMode(1));await p.screenshot({path:out+'/geometry-gray.png'});await p.evaluate(()=>window.__LM__.setMode(0));await p.evaluate(()=>window.__LM__.goView('hero'));await p.screenshot({path:out+'/hero.png'});await p.evaluate(()=>window.__LM__.goView('back'));await p.screenshot({path:out+'/back.png'});
await p.evaluate(()=>{window.__LM_KARST__.set({phase:.9});window.__LM__.goView('cave')});if(await p.evaluate(()=>window.__LM_MICRO__.fingerprint())!==detailed)throw Error('time changed static geometry');result.timeIndependent=true;
await p.evaluate(()=>window.__LM_MICRO__.set({strength:0}));await p.evaluate(()=>window.__LM_MICRO__.set({strength:1}));if(await p.evaluate(()=>window.__LM_MICRO__.fingerprint())!==detailed)throw Error('geometry roundtrip failed');result.geometryRoundtripExact=true;
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>window.__LM_MICRO__.focus());await p.screenshot({path:out+'/mobile.png'});await p.locator('#mmSide').click();await p.locator('#mmFocus').click();await p.locator('#mmClose').click();await p.locator('#mmToggle').click();const saved=await p.evaluate(()=>window.__LM__.getState());await p.evaluate(()=>window.__LM_MICRO__.set({mode:0,strength:.5}));await p.evaluate(s=>window.__LM__.restoreState(s),saved);if(await p.evaluate(()=>window.__LM_MICRO__.fingerprint())!==detailed)throw Error('state restore failed');
result.baseFingerprint=await p.evaluate(()=>window.__LM__.bufferFingerprint());result.detailFingerprint=detailed;result.horizontalOverflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);result.audit=await p.evaluate(()=>window.__LM__.auditFrame());result.renderSubmitMs=await p.evaluate(()=>window.__LM__.renderTimes);if(result.baseFingerprint!=='42a73c10'||errors.length||result.audit.glError||result.horizontalOverflow)throw Error('QA failed');fs.writeFileSync(out+'/RESULT.json',JSON.stringify(result,null,2));console.log('PASSED',JSON.stringify({base:result.baseFingerprint,detail:detailed,audit:result.audit}));await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
