/* Local policy mirror validator 0.1.0. Covers the locked schemas used here.
   It is not the upstream validator and is not a general JSON Schema engine. */
(function(root){'use strict';
function parse(text){let i=0;const ws=()=>{while(/\s/.test(text[i]||'X'))i++};
function string(){const s=i++;while(i<text.length){const c=text[i++];if(c==='"')return JSON.parse(text.slice(s,i));if(c==='\\')i++;}throw Error('Unterminated JSON string')}
function value(){ws();const c=text[i];if(c==='"')return string();if(c==='{'){i++;const o=Object.create(null),seen=new Set();ws();if(text[i]==='}'){i++;return o}while(true){ws();if(text[i]!=='"')throw Error('Expected key');let k=string();if(seen.has(k))throw Error('Duplicate key '+k);seen.add(k);ws();if(text[i++]!==':')throw Error('Expected colon');o[k]=value();ws();let a=text[i++];if(a==='}')return o;if(a!==',')throw Error('Expected comma')}}if(c==='['){i++;let a=[];ws();if(text[i]===']'){i++;return a}while(true){a.push(value());ws();let c=text[i++];if(c===']')return a;if(c!==',')throw Error('Expected array comma')}}const m=/^(true|false|null|-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)/.exec(text.slice(i));if(!m)throw Error('Invalid JSON token');i+=m[0].length;const v=JSON.parse(m[0]);if(typeof v==='number'&&!Number.isFinite(v))throw Error('Nonfinite number');return v}
const result=value();ws();if(i!==text.length)throw Error('Trailing JSON');return result;}
function same(a,b){if(a===b)return true;if(typeof a!==typeof b||a===null||b===null)return false;if(Array.isArray(a))return Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>same(v,b[i]));if(typeof a==='object'){let k=Object.keys(a),l=Object.keys(b);return k.length===l.length&&k.every(x=>Object.hasOwn(b,x)&&same(a[x],b[x]));}return false}
function validate(v,s,path='$'){if(Object.hasOwn(s,'const')&&!same(v,s.const))throw Error(path+' locked value');if(s.enum&&!s.enum.some(x=>same(x,v)))throw Error(path+' enum');const t=s.type;if(t==='object'&&(!v||typeof v!=='object'||Array.isArray(v)))throw Error(path+' object');if(t==='array'&&!Array.isArray(v))throw Error(path+' array');if(t==='boolean'&&typeof v!=='boolean')throw Error(path+' boolean');if(t==='string'&&typeof v!=='string')throw Error(path+' string');if((t==='number'||t==='integer')&&(typeof v!=='number'||!Number.isFinite(v)||t==='integer'&&!Number.isInteger(v)))throw Error(path+' finite number');if(typeof v==='number'&&(v<s.minimum||v>s.maximum))throw Error(path+' range');if(typeof v==='string'){if(v.length<s.minLength||v.length>s.maxLength)throw Error(path+' length');if(s.pattern&&!(new RegExp(s.pattern)).test(v))throw Error(path+' pattern');}if(v&&typeof v==='object'&&!Array.isArray(v)){for(const k of s.required||[])if(!Object.hasOwn(v,k))throw Error(path+' missing '+k);for(const k of Object.keys(v)){if(!s.properties?.[k]&&s.additionalProperties===false)throw Error(path+' unknown '+k);if(s.properties?.[k])validate(v[k],s.properties[k],path+'.'+k)}}return true}
function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v)}return v}
async function sha(data){const bytes=typeof data==='string'?new TextEncoder().encode(data):data;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
const pins={policy:'80aef698e30a6378e25d6eeb7c6ee67c1df24e6ae96faef5f4df4ef62d19c8d3',schema:'b6f2d496a12f48c58b26051907b67ae247d193db1d3aed31ea4ae3ec084efa6e',profileSchema:'5b91645690002570cd4107883243e7ca1c32f0c7e6ecdfdf027931557884db29'};
function create(){let policy,profileSchema,ready=false;const counts={},rejections=[];return {counts,rejections,pins,async boot(fetchText){const [pt,st,dt]=await Promise.all(['policy.json','policy.schema.json','profile.schema.json'].map(fetchText));if(await sha(pt)!==pins.policy||await sha(st)!==pins.schema||await sha(dt)!==pins.profileSchema)throw Error('POLICY_SCHEMA_HASH_MISMATCH');policy=parse(pt);const schema=parse(st);profileSchema=freeze(parse(dt));validate(policy,schema);freeze(policy);ready=true;return policy},check(action,profile){try{if(!ready)throw Error('POLICY_NOT_LOADED');if(!['generate','mutate','export','preview','release'].includes(action))throw Error('UNKNOWN_GATE');validate(profile,profileSchema);if(action==='release')throw Error('ACCEPTANCE_BLOCKED: exact user approvals and required evidence absent');counts[action]=(counts[action]||0)+1;return true}catch(e){rejections.push({action,error:e.message});throw e}},validatePolicy(candidate,schema){return validate(candidate,schema)},status(){return{ready,policyVersion:policy?.version,policyState:policy?.policyState,visualApproved:false,productionApproved:false}}}}
const api={parse,validate,same,freeze,sha,create,pins};root.WeatherGuard=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
