/* Weather Mother method integration candidate 0.1.0.
   This entry never writes the frozen workspace or other production lines. */
(async()=>{'use strict';const $=id=>document.getElementById(id),G=WeatherGuard,H=WeatherHistory,guard=G.create();
const qa={version:'wm-method-0.1.0',ready:false,errors:[],frames:0,sourceReceived:true,wholeLineIntegrated:false,visualApproved:false,productionApproved:false,sourceHashes:{},dataHashes:{},nativeRenderSize:[],upstreamSchemaVerified:false};
const fail=e=>{$('error').hidden=false;$('error').textContent=e.stack||String(e);qa.errors.push(String(e))};window.WeatherMethod={qa};
async function read(p){let r=await fetch(p);if(!r.ok)throw Error(p+' HTTP '+r.status);return r.text()}
try{const policy=await guard.boot(read);const profile=G.parse(await read('profile.json'));guard.check('preview',profile);let history=new H.History(profile,guard);
let frameNeeded=true,running=false,rate=1,last=performance.now(),mode='neutral_inspection',diag=1,yaw=.14,pitch=-.055,distance=11.8,job=0,noiseReady=false,volumeReady=false,pending=null,groups=[];
const lightValues=[{enabled:true,power:1.4,azimuth:-40,elevation:42,color:'#ffffff'},{enabled:true,power:.55,azimuth:65,elevation:24,color:'#b9d6ff'},{enabled:true,power:1.2,azimuth:165,elevation:35,color:'#fff1db'}];
const n=v=>{let l=Math.hypot(...v)||1;return v.map(x=>x/l)},dir=(a,e)=>{a*=Math.PI/180;e*=Math.PI/180;return [Math.sin(a)*Math.cos(e),Math.sin(e),Math.cos(a)*Math.cos(e)]};
function sourceState(){return history.snapshot()}
function action(fn){try{fn();frameNeeded=true;info()}catch(e){$('status').textContent='操作已阻断：'+e.message;throw e}}
const canvas=$('scene'),gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2 不可用');
const sourcePins={'cloud.glsl':'d0d28a6321d26cf83e2380dac032aee1741bdd87a58cda4883110dab642b0626','field-worker.js':'8c4402977790dc2e9c6116f6f4ac8d75b88bda967183f2df077970663a44aa4e'};
const sources={};for(const [name,pin] of Object.entries(sourcePins)){const text=await read('../clean-v1/'+name),hash=await G.sha(text);if(hash!==pin)throw Error('SOURCE_HASH_MISMATCH '+name);sources[name]=text;qa.sourceHashes[name]=hash;}
const shaderText=sources['cloud.glsl'].slice(0,sources['cloud.glsl'].indexOf('void main(){')).replace('layout(location=1) out vec4 fragInfo;','')+await read('view.glsl');
function shader(type,text){const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader compilation failed');return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'#version 300 es\nvoid main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0,1);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,shaderText));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.bindVertexArray(gl.createVertexArray());
const locs={};function loc(k){return locs[k]??(locs[k]=gl.getUniformLocation(program,k))}const f=(k,v)=>gl.uniform1f(loc(k),v),ii=(k,v)=>gl.uniform1i(loc(k),v),v3=(k,v)=>gl.uniform3fv(loc(k),v),v4=(k,v)=>gl.uniform4fv(loc(k),v);
const macro=gl.createTexture(),noise=gl.createTexture();function upload(tex,data,dims,rg=false){gl.bindTexture(gl.TEXTURE_3D,tex);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);for(let x of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,x,rg?gl.REPEAT:gl.CLAMP_TO_EDGE);gl.texImage3D(gl.TEXTURE_3D,0,rg?gl.RG8:gl.R8,...dims,0,rg?gl.RG:gl.RED,gl.UNSIGNED_BYTE,data)}
const dims=[192,112,160],lo=[-19,-1,-16],hi=[19,13,16];qa.volumeDimensions=dims;qa.volumeUnits='km';qa.renderer='native pixel ratio capped 960x640; 144 view samples, six coarse shadow samples per active light';qa.colorConversion='linear to sRGB piecewise v1; neutral fixed clamp, beauty c/(1+c)';qa.lightUnits='relative directional radiance; no lux or Kelvin calibration';
const blob=URL.createObjectURL(new Blob([sources['field-worker.js']],{type:'text/javascript'})),worker=new Worker(blob);URL.revokeObjectURL(blob);worker.onerror=e=>fail(e.message);
worker.onmessage=async({data:d})=>{if(d.error)return fail(d.error);if(d.noise){upload(noise,d.data,[96,96,96],true);qa.dataHashes.noise=await G.sha(d.data);noiseReady=true;}else if(d.id===job){if(d.borderMax!==0||!d.supportSafe)return fail('Nonzero or unsafe source boundary');upload(macro,d.data,dims);groups=d.groups;qa.dataHashes.density=await G.sha(d.data);qa.dataHashes.shadowCache=await G.sha(new Uint8Array(d.tau.buffer));qa.borderMax=d.borderMax;qa.lobes=d.lobes;volumeReady=true;}qa.ready=noiseReady&&volumeReady;frameNeeded=true;info()};
function generate(){guard.check('generate',history.profile);job++;volumeReady=false;qa.ready=false;worker.postMessage({id:job,kind:'Cu',seed:history.snapshot().identity.shapeSeed,count:1,instability:.45,dims,min:lo,max:hi,sun:dir(-40,42)});}
function mutate(k,v){guard.check('mutate',{...history.profile,[k]:v});history.mutate(k,v);frameNeeded=true;info()}
function setMode(m){if(!policy.presentation.requiredModes.includes(m))throw Error('Unknown presentation mode');guard.check('mutate',history.profile);mode=m;running=false;$('play').textContent='播放过程';$('mode').value=m;$('studio').open=m==='studio_beauty';$('legend').hidden=m!=='diagnostic';for(const el of $('lights').querySelectorAll('input'))el.disabled=m!=='studio_beauty';frameNeeded=true;info()}
function setLight(k,changes){guard.check('mutate',history.profile);if(!Number.isInteger(k)||k<0||k>2)throw Error('Invalid light');for(const [key,v]of Object.entries(changes)){if(!Object.hasOwn(lightValues[k],key))throw Error('Unknown light key');if(key==='enabled'&&typeof v!=='boolean')throw Error('Light boolean');if(key==='color'&&(typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v)))throw Error('Light colour');if(['power','azimuth','elevation'].includes(key)&&(!Number.isFinite(v)||v<(key==='power'?0:key==='elevation'?5:-180)||v>(key==='power'?3:key==='elevation'?85:180)))throw Error('Light range');}Object.assign(lightValues[k],changes);frameNeeded=true;info()}
function range(parent,id,label,min,max,step,val,fn){const d=document.createElement('div');d.className='row';d.innerHTML=`<label for="${id}">${label}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${val}"><output>${val}</output>`;parent.append(d);$(id).oninput=e=>{const v=+e.target.value;try{fn(v);e.target.nextElementSibling.textContent=v.toFixed(step<1?2:0)}catch(e){$('status').textContent='操作阻断：'+e.message}}}
range($('drivers'),'humidity','湿度驱动',0,1,.01,profile.humidity,v=>mutate('humidity',v));range($('drivers'),'cloudSpeedMps','漂移 m/s',0,80,1,profile.cloudSpeedMps,v=>mutate('cloudSpeedMps',v));range($('drivers'),'windFromDegrees','来向 °',0,360,1,profile.windFromDegrees,v=>mutate('windFromDegrees',v));
lightValues.forEach((l,k)=>{const box=document.createElement('fieldset');box.innerHTML=`<legend>${['主光 key','辅光 fill','轮廓光 rim'][k]}</legend><label class="check"><input id="lightOn${k}" type="checkbox" checked> 开启</label><label>颜色 <input id="lightColor${k}" type="color" value="${l.color}"></label>`;$('lights').append(box);$('lightOn'+k).onchange=e=>setLight(k,{enabled:e.target.checked});$('lightColor'+k).oninput=e=>setLight(k,{color:e.target.value});range(box,'lightPower'+k,'相对强度',0,3,.05,l.power,v=>setLight(k,{power:v}));range(box,'lightAz'+k,'方向 °',-180,180,1,l.azimuth,v=>setLight(k,{azimuth:v}));range(box,'lightEl'+k,'仰角 °',5,85,1,l.elevation,v=>setLight(k,{elevation:v}));});
$('mode').onchange=e=>setMode(e.target.value);$('diagnostic').onchange=e=>{diag=+e.target.value;frameNeeded=true;info()};$('physical').oninput=e=>{running=false;history.seek(+e.target.value);frameNeeded=true;info()};$('rate').oninput=e=>{rate=+e.target.value;e.target.nextElementSibling.textContent=rate};$('play').onclick=()=>{running=!running;last=performance.now();$('play').textContent=running?'暂停过程':'播放过程'};$('resetView').onclick=()=>{yaw=.14;pitch=-.055;distance=11.8;frameNeeded=true};
$('seed').onclick=()=>{guard.check('mutate',{...profile,masterSeed:(history.profile.masterSeed+7919)>>>0});history=new H.History({...profile,masterSeed:(history.profile.masterSeed+7919)>>>0},guard);generate()};
async function exportState(){const value=history.export();value.policy={version:policy.version,sha256:G.pins.policy};value.sourceIdentity={...qa.sourceHashes};value.effectiveParametersSha256=await G.sha(JSON.stringify(value.profile));value.dataHashes={...qa.dataHashes};value.presentation={mode,diag,lights:lightValues,nativePixelSize:[canvas.width,canvas.height],cssPixelSize:[innerWidth,innerHeight],colorPipeline:qa.colorConversion,lightUnits:qa.lightUnits};value.acceptance={status:'blocked',visualApproved:false,productionApproved:false,missing:['upstream schema/validator provenance','whole-line migration','user visual record','production approval']};return value}
$('export').onclick=async()=>{try{const v=await exportState(),u=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='Weather_Method_State.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){$('status').textContent=e.message}};
function info(){const s=sourceState();$('physical').value=Math.min(120,s.physicalTime);$('physical').nextElementSibling.textContent=s.physicalTime.toFixed(1);$('legendTitle').textContent=['','光学厚度 τ','对象 z=0 浓度剖面','云内加权深度'][diag];$('legendRange').textContent=['','蓝 0 → 黄 4','蓝 0 → 黄 1.2（无量纲）','蓝 0 → 黄 25 km'][diag];$('info').textContent=JSON.stringify({policy:guard.status(),entity:s.identity,clocks:{physicalTime:s.physicalTime,solverStep:s.solverStep,displayTime:s.displayTime},concentration:s.concentration,offsetM:s.offsetM,densityHash:qa.dataHashes.density,events:history.events.length,nativePixels:qa.nativeRenderSize},null,2);$('status').textContent=(qa.ready?'样本已生成':'生成源密度…')+' · '+mode+' · '+canvas.width+'×'+canvas.height+' 原生像素 / '+innerWidth+'×'+innerHeight+' 显示 · '+qa.frames+' 帧';}
function resize(){const scale=Math.min(1,960/innerWidth,640/innerHeight),w=Math.max(2,Math.round(innerWidth*scale)),h=Math.max(2,Math.round(innerHeight*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;frameNeeded=true;}qa.nativeRenderSize=[w,h];qa.displaySize=[innerWidth,innerHeight]}
function linearHex(hex){return [1,3,5].map(i=>{const c=parseInt(hex.slice(i,i+2),16)/255;return c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4)})}
let drag=false,px=0,py=0;canvas.onpointerdown=e=>{if(mode==='neutral_inspection')return;drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=()=>drag=false;canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-px)*.004;pitch=Math.max(-.2,Math.min(.8,pitch+(e.clientY-py)*.004));px=e.clientX;py=e.clientY;frameNeeded=true};canvas.addEventListener('wheel',e=>{e.preventDefault();if(mode==='neutral_inspection')return;distance=Math.max(4,Math.min(30,distance*Math.exp(e.deltaY*.001)));frameNeeded=true},{passive:false});addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=performance.now()});
function frame(now){requestAnimationFrame(frame);if(qa.errors.length)return;const dt=(now-last)/1000;last=now;if(document.hidden)return;if(running&&qa.ready){history.advance(dt,rate);frameNeeded=true}if(!qa.ready||!frameNeeded)return;resize();const s=sourceState(),neutral=mode==='neutral_inspection',a=neutral?.14:yaw,b=neutral?-.055:pitch,dist=neutral?11.8:distance,cam=[Math.sin(a)*Math.cos(b)*dist,2.55+Math.sin(b)*dist,Math.cos(a)*Math.cos(b)*dist];gl.useProgram(program);gl.viewport(0,0,canvas.width,canvas.height);
for(const [unit,tex]of [[0,macro],[1,noise]]){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_3D,tex)}ii('uMacro',0);ii('uOld',0);ii('uNoise',1);v3('uMin',lo);v3('uMax',hi);v3('uCamera',cam);v3('uTarget',[0,2.55,0]);v3('uWind',s.offsetM.map(v=>v*.001));v3('uWindDirection',[1,0,0]);v3('uLoop',[0,0,0]);v4('uFlow',[0,0,0,0]);v4('uEffects',[0,0,0,0]);v4('uOpt',[s.concentration,.64,0,0]);f('uBlend',1);f('uFastEmpty',0);f('uMicroFilter',1);f('uCloudBase',1.2);f('uCloudTop',4.2);f('uEvolution',0);f('uShear',0);ii('uSteps',144);gl.uniform2f(loc('uRes'),canvas.width,canvas.height);v3('uLo[0]',groups[0].lo);v3('uHi[0]',groups[0].hi);ii('mode',neutral?0:mode==='studio_beauty'?1:2);ii('diag',diag);
const lights=neutral?[{enabled:true,power:1,azimuth:-40,elevation:42,color:'#ffffff'},{enabled:true,power:.5,azimuth:65,elevation:24,color:'#ffffff'},{enabled:false,power:0,azimuth:165,elevation:35,color:'#ffffff'}]:lightValues;
gl.uniform3fv(loc('lightDir[0]'),new Float32Array(lights.flatMap(l=>dir(l.azimuth,l.elevation))));gl.uniform3fv(loc('lightColor[0]'),new Float32Array(lights.flatMap(l=>linearHex(l.color))));gl.uniform1fv(loc('lightPower[0]'),new Float32Array(lights.map(l=>l.enabled?l.power:0)));gl.drawArrays(gl.TRIANGLES,0,3);qa.frames++;qa.lastGLerror=gl.getError();qa.mode=mode;qa.physicalTime=s.physicalTime;qa.effectiveConcentration=s.concentration;qa.camera=cam;frameNeeded=false;if(qa.lastGLerror)fail('WebGL error '+qa.lastGLerror);info();}
window.WeatherMethod={qa,guard,getState:sourceState,getProfile:()=>JSON.parse(JSON.stringify(history.profile)),getPresentation:()=>({mode,diag,lights:JSON.parse(JSON.stringify(lightValues))}),setMode,setLight,setDriver:mutate,seek:t=>action(()=>history.seek(t)),advance:(dt,r=1)=>action(()=>history.advance(dt,r)),branchAt:t=>action(()=>history.branchAt(t)),exportState,attemptProduction:()=>guard.check('release',history.profile),rebuild:()=>generate(),setDiagnostic:d=>{if(![1,2,3].includes(d))throw Error('Unknown diagnostic');diag=d;frameNeeded=true;info()}};
resize();setMode('neutral_inspection');worker.postMessage({noise:true});generate();requestAnimationFrame(frame);
}catch(e){fail(e)}})();
