/* Weather-domain minimal process 0.1.0. Exact piecewise analytic illustrative
   relaxation, not thermodynamic condensation or a measured cloud-water solver. */
(function(root){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
function seed(master,entity,process){const b=new TextEncoder().encode(JSON.stringify(['wm-seed-fnv1a32-v1',master,entity,process]));let h=2166136261;for(const x of b)h=Math.imul(h^x,16777619);return h>>>0}
function integrate(s,driver,dt){if(!Number.isFinite(dt)||dt<0)throw Error('Negative or nonfinite solver step');const target=Math.max(0,Math.min(1,(driver.humidity-.25)/.75)),a=driver.windFromDegrees*Math.PI/180;return{physicalTime:s.physicalTime+dt,concentration:target+(s.concentration-target)*Math.exp(-dt/driver.relaxationSeconds),offsetM:[s.offsetM[0]-Math.sin(a)*driver.cloudSpeedMps*dt,0,s.offsetM[2]+Math.cos(a)*driver.cloudSpeedMps*dt]}}
class History {
 constructor(profile,guard){this.guard=guard;this.guard.check('generate',profile);this.profile=clone(profile);this.initial={physicalTime:0,concentration:profile.initialConcentration,offsetM:[0,0,0]};this.current=clone(this.initial);this.events=[{physicalTime:0,order:0,driver:this.driver(profile)}];this.displayTime=0;this.solverStep=0;this.eventIndex=0;this.branches=[];this.seek(profile.physicalTime)}
 driver(p){return Object.fromEntries(['humidity','cloudSpeedMps','windFromDegrees','relaxationSeconds'].map(k=>[k,p[k]]))}
 advance(displayDt,rate){if(!Number.isFinite(displayDt)||displayDt<0||!Number.isFinite(rate)||rate<0||rate>8)throw Error('Invalid display clock');let dt=displayDt*rate;if(this.current.physicalTime+dt>86400)throw Error('TIME_RANGE');this.displayTime+=displayDt;this.solverStep=dt;const end=this.current.physicalTime+dt;while(this.eventIndex+1<this.events.length&&this.events[this.eventIndex+1].physicalTime<=end){const ev=this.events[this.eventIndex+1];this.current=integrate(this.current,this.events[this.eventIndex].driver,ev.physicalTime-this.current.physicalTime);this.eventIndex++;}this.current=integrate(this.current,this.events[this.eventIndex].driver,end-this.current.physicalTime);Object.assign(this.profile,this.events[this.eventIndex].driver);this.profile.physicalTime=this.current.physicalTime;return this.snapshot()}
 mutate(key,value){if(this.eventIndex<this.events.length-1)throw Error('HISTORY_BRANCH_REQUIRED');if(!Object.hasOwn(this.driver(this.profile),key))throw Error('Unsupported driver');const p={...this.profile,[key]:value,physicalTime:this.current.physicalTime};this.guard.check('mutate',p);this.profile=p;this.events.push({physicalTime:this.current.physicalTime,order:this.events.length,driver:this.driver(p)});this.eventIndex=this.events.length-1;return this.snapshot()}
 seek(t){if(!Number.isFinite(t)||t<0||t>86400)throw Error('Invalid physical time');let s=clone(this.initial),d=this.events[0].driver;this.eventIndex=0;for(let k=1;k<this.events.length;k++){let e=this.events[k];if(e.physicalTime>t)break;s=integrate(s,d,e.physicalTime-s.physicalTime);d=e.driver;this.eventIndex=k;}this.current=integrate(s,d,t-s.physicalTime);this.profile.physicalTime=t;Object.assign(this.profile,d);this.solverStep=0;return this.snapshot()}
 // Editing a rewound history requires an explicit new branch; silent future erasure is forbidden.
 branchAt(t){this.branches.push({branchPoint:t,history:clone(this.events)});this.seek(t);this.events=this.events.filter(e=>e.physicalTime<=t);Object.assign(this.profile,this.events[this.events.length-1].driver);return this.snapshot()}
 snapshot(){return{identity:{motherId:this.profile.motherId,entityId:this.profile.entityId,profileVersion:this.profile.profileVersion,generatorVersion:this.profile.generatorVersion,masterSeed:this.profile.masterSeed,shapeSeed:seed(this.profile.masterSeed,this.profile.entityId,'macro_shape'),seedDerivationVersion:'wm-seed-fnv1a32-v1',noiseCache:'legacy-fixed-271'},...clone(this.current),displayTime:this.displayTime,solverStep:this.solverStep,solver:'piecewise-analytic-v1',calibration:'illustrative_not_calibrated',visualApproved:false,productionApproved:false}}
 export(){this.guard.check('export',this.profile);return{format:'weather-method-history',version:'0.1.0',profile:clone(this.profile),initialState:clone(this.initial),driverHistory:clone(this.events),archivedBranches:clone(this.branches),state:this.snapshot(),modelLimit:'dimensionless open-system appearance proxy; no condensation microphysics'}}
}
const api={seed,integrate,History};root.WeatherHistory=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
