import * as THREE from'../source/registration-vendor/three.module.js';
import{AnimatedHuman}from'../boxing/AnimatedHuman.mjs';
import{createCapturedActivityController}from'../activity-r01/CapturedActivityController.mjs';
import{buildInfluenceEnvelope,posedEnvelope,unionBounds,horizontalClearance,containsHorizontal}from'./Envelope.mjs';
import{planPerimeterZones}from'./Layout.mjs';
const dt=1/120;
async function fingerprint(h){const a=new Uint8Array(h.positions.buffer,h.positions.byteOffset,h.positions.byteLength),b=new TextEncoder().encode(JSON.stringify({names:h.names,parents:h.rig.parents,rest:h.rig.restMatrices})),all=new Uint8Array(a.length+b.length);all.set(a);all.set(b,a.length);return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',all)),x=>x.toString(16).padStart(2,'0')).join('');}
function zoneMesh(bounds,color){const w=bounds.max[0]-bounds.min[0],d=bounds.max[2]-bounds.min[2],group=new THREE.Group(),plane=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshStandardMaterial({color,transparent:true,opacity:.22,roughness:1,depthWrite:false}));plane.rotation.x=-Math.PI/2;plane.position.set((bounds.min[0]+bounds.max[0])/2,.002,(bounds.min[2]+bounds.max[2])/2);group.add(plane);const corners=[[bounds.min[0],.006,bounds.min[2]],[bounds.max[0],.006,bounds.min[2]],[bounds.max[0],.006,bounds.max[2]],[bounds.min[0],.006,bounds.max[2]]].map(v=>new THREE.Vector3(...v)),line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(corners),new THREE.LineBasicMaterial({color,transparent:true,opacity:.75}));group.add(line);return group;}
/** Adds three (or more) full native actors to an existing scene root.
 * states entries: {id,label,state,activity:'walk'|'run'|'jump',color?}.
 * sources maps those activity keys to the already approved CMU source packets.
 * arenaBounds are measured in the SAME host-root local Y-up metre frame.
 * No DOM, renderer, camera, new webpage or hidden low-quality actors. */
export async function createPerimeterActivityGroup({root,model,states,sources,arenaBounds,onProgress=()=>{},signal}={}){
 if(!root?.add||!model?.compute||!Array.isArray(states)||states.length<3)throw Error('Existing scene root, CommonPerson and at least three actors required');
 if(new Set(states.map(s=>s.activity)).size<3||!['walk','run','jump'].every(k=>states.some(s=>s.activity===k)))throw Error('Three distinct captured behaviors required, not phase offsets');
 if(new Set(states.map(s=>JSON.stringify(s.state))).size<3)throw Error('At least three distinct body states required');
 if(new Set(['walk','run','jump'].map(k=>JSON.stringify(sources?.[k]?.points))).size<3)throw Error('Distinct recorded motion content required, not relabelled copies');
 const group=new THREE.Group();group.name='perimeter-full-character-activities';const actors=[],allocatedHumans=[];let plan,disposed=false,time=0,accumulator=0,paused=true,speed=1,finished=false,error=null;
 const check=()=>{if(disposed)throw Error('Perimeter activities disposed');};
 try{for(let i=0;i<states.length;i++){if(signal?.aborted)throw new DOMException('Cancelled','AbortError');const entry=states[i],source=sources?.[entry.activity];if(!source)throw Error('Missing authorized captured source '+entry.activity);model.compute(entry.state);const color=entry.color??[0x65cba7,0xe4a36d,0xa894e4][i%3],human=new AnimatedHuman(model,entry.state,{color});allocatedHumans.push(human);const controller=createCapturedActivityController(human,source),envelope=buildInfluenceEnvelope(human);let sweep=null;for(let f=0;f<source.points.length;f++){const p=controller.evaluate(f/source.fps),bounds=posedEnvelope(envelope,p.skinMatrices,{floorOffset:human.floorOffset});sweep=sweep?unionBounds(sweep,bounds):bounds;}controller.reset();const actorGroup=new THREE.Group();actorGroup.position.y=human.floorOffset;actorGroup.add(human.mesh);const shadows=['L','R'].map(side=>{const mesh=new THREE.Mesh(new THREE.CircleGeometry(1,16),new THREE.MeshBasicMaterial({color:0x091217,transparent:true,opacity:.15,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.scale.set(human.height*.063,human.height*.105,1);group.add(mesh);return{mesh,index:human.names.indexOf('foot.'+side)};});const actor={...entry,color,human,controller,envelope,sweep,group:actorGroup,shapeFingerprint:await fingerprint(human),shadows,latest:null,bounds:null};actors.push(actor);group.add(actorGroup);onProgress({completed:i+1,total:states.length});await new Promise(r=>setTimeout(r,0));}
 if(signal?.aborted)throw new DOMException('Cancelled','AbortError');if(new Set(actors.map(a=>a.shapeFingerprint)).size<3)throw Error('At least three actual distinct generated body/rest fingerprints required');plan=planPerimeterZones(actors.map(a=>a.sweep),arenaBounds);for(let i=0;i<actors.length;i++){const a=actors[i],z=plan.zones[i];a.placement=z.position;a.zone=z.zone;a.group.position.x=z.position[0];a.group.position.z=z.position[2];group.add(zoneMesh(z.zone,a.color));}
 }catch(e){for(const h of allocatedHumans)h.dispose();group.traverse(o=>{if(o.isLine||o.isMesh&&!actors.some(a=>a.human.mesh===o)){o.geometry?.dispose();o.material?.dispose();}});throw e;}
 const duration=Math.max(...actors.map(a=>a.controller.duration));
 function update(t){check();if(!Number.isFinite(t)||t<0)throw Error('Finite nonnegative shared activity time required');const next=Math.min(t,duration),pending=[];try{for(const a of actors){const pose=a.controller.evaluate(next),bounds=posedEnvelope(a.envelope,pose.skinMatrices,{floorOffset:a.human.floorOffset,position:a.placement});if(!containsHorizontal(a.zone,bounds))throw Error('Full character left its verified activity zone');if(arenaBounds.some(b=>horizontalClearance(bounds,b)<.5))throw Error('Full character approached an occupied ring');pending.push({a,pose,bounds});}for(let i=0;i<pending.length;i++)for(let j=0;j<i;j++)if(horizontalClearance(pending[i].bounds,pending[j].bounds)<.5)throw Error('Full activity actors approached each other');}catch(e){error=e.message;paused=true;for(const a of actors){a.controller.reset();a.latest=a.controller.update(time);}throw e;}
  for(const{a,pose,bounds}of pending){a.latest=pose;a.bounds=bounds;a.human.animate(pose.skinMatrices);for(const sh of a.shadows){const m=pose.posedMatrices[sh.index];sh.mesh.position.set(a.placement[0]+m[3],.004,a.placement[2]-m[7]);const footLift=Math.max(0,m[11]-a.human.rig.restMatrices[sh.index][11]);sh.mesh.material.opacity=.15*Math.exp(-18*footLift);}}
  time=next;finished=time>=duration-1e-9;if(finished){paused=true;accumulator=0;}return diagnostics();
 }
 function diagnostics(){return{schema:'perimeter-distinct-activities/1',time,duration,paused,speed,finished,error,backlog:accumulator,clockFPS:120,actors:actors.map(a=>({id:a.id,label:a.label,activity:a.activity,shapeFingerprint:a.shapeFingerprint,vertices:a.human.N,bones:a.human.names.length,phase:a.latest?.ended?'completed-hold':'captured-motion',sourceFrame:a.latest?.frame,placement:a.placement,zone:a.zone,bounds:a.bounds})),plan,quality:'full CSR for every actor; no dropped actors or LOD',collision:'verified separated activity zones, not contact dynamics',loop:false,resetIsExplicit:true};}
 const api={group,actors,duration,plan,update,diagnostics,advance(realDelta){check();if(!Number.isFinite(realDelta)||realDelta<0)throw Error('Invalid real delta');if(paused)return 0;accumulator+=realDelta*speed;let steps=0;while(accumulator+1e-12>=dt&&steps<12&&!paused){update(time+dt);accumulator=Math.max(0,accumulator-dt);steps++;}return steps;},step(count=1){check();if(!paused)throw Error('Pause before stepping');if(!Number.isInteger(count)||count<0||count>10000)throw Error('Invalid step count');for(let n=0;n<count&&!finished;n++)update(time+dt);return diagnostics();},setPlaying(value){check();if(value&&finished)throw Error('Completed clips stay stopped; use explicit reset before replay');paused=!value;},setSpeed(value){if(!Number.isFinite(value)||value<.1||value>2)throw Error('Activity speed must be .1–2');speed=value;},reset(){check();for(const a of actors)a.controller.reset();time=0;accumulator=0;finished=false;paused=true;error=null;return update(0);},dispose(){if(disposed)return;disposed=true;for(const a of actors)a.human.dispose();group.traverse(o=>{if(o.isLine||o.isLineLoop||o.isMesh&&!actors.some(a=>a.human.mesh===o)){o.geometry?.dispose();o.material?.dispose();}});group.removeFromParent();}};
 api.reset();root.add(group);return api;
}
