import {readFileSync as read,writeFileSync as write,mkdirSync,cpSync} from 'node:fs';import {resolve,dirname,join} from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(process.argv[2]||'human'),out=resolve(process.argv[3]||'dist/shorts-original-r5');
const get=p=>read(join(root,p),'utf8'),put=(p,s)=>{mkdirSync(dirname(join(root,p)),{recursive:true});write(join(root,p),s);};
const source='3c3e9a4b7b250f4c8db20c15e2e5fab4ca9ce568';
const manifest=JSON.parse(get('source/assembly.json'));
manifest.modules=manifest.modules.map(p=>p==='body/ProceduralGrassSkirt.js'?'clothing/TailoredShortsR5.js':p);put('source/assembly.json',JSON.stringify(manifest,null,2));const generator=read(join(here,'TailoredShortsR5.js'),'utf8')+'\n'+read(join(here,'SkinBindingR53.js'),'utf8');put('clothing/TailoredShortsR5.js',generator);
let code=get('source/runtime.template.js').replace('/*__SOURCE:body/ProceduralGrassSkirt.js__*/','/*__SOURCE:clothing/TailoredShortsR5.js__*/');
code=code.replace("world.applyPreset('camp',260901);","world.applyPreset('sorting',260901);world.objects=[];world.zones=[];world.scenery=[];");
const a=code.indexOf("if(reviewMode==='face'){",code.indexOf('await installCompactWorkbench')),b=code.indexOf('try{human.characterTaskStatus=',a);
if(a>=0&&b>a)code=code.slice(0,a)+"auto=false;\n"+code.slice(b);
code=code.replace("if(reviewMode!=='face')scheduleCompactHair(window.HumanLab.population?.active||window.HumanLab);","scheduleCompactHair(window.HumanLab);");put('source/runtime.template.js',code);
put('body/CompactWorkbench.js',get('body/CompactWorkbench.js').replace('window.__SHORTS_PROBE__=data.meshes;','').replace('stage.skirt=new ProceduralGrassSkirt','stage.skirt=new BodyBoundShortsR53'));
const {assemble}=await import(pathToFileURL(join(root,'tools/build-pure.mjs')));let {body}=assemble();
const style=`<style>
body{margin:0!important;background:#11191e!important;font-family:system-ui,sans-serif!important}body>header,.layout>aside,.toolbar,.hud,.metrics,.bottom,#labels,.compact-panel{display:none!important}.layout{display:block!important;height:100dvh!important}.stage{position:fixed!important;inset:62px 0 0!important;min-width:0!important}#view{width:100%!important;height:100%!important}.loading{font-size:14px!important}
#r5-ui{position:fixed;inset:0;z-index:80;pointer-events:none;color:#e7edf0;font-size:13px}#r5-ui button,#r5-ui details{pointer-events:auto}#r5-ui button{background:#23333e;border:1px solid #53636c;border-radius:7px;padding:10px 14px;color:#eef1ef;cursor:pointer;font:inherit}#r5-ui button:hover{background:#3a4b55}#r5-ui button:disabled{opacity:.4;cursor:wait}#r5-top{height:62px;box-sizing:border-box;display:flex;align-items:center;gap:18px;padding:12px 20px;background:#142129;border-bottom:1px solid #36424a}#r5-top b{font-size:18px}#r5-status{color:#adccbd;line-height:1.5}#r5-status[data-error=true]{color:#f1a18a}#r5-info{position:absolute;right:16px;top:80px;width:230px;box-sizing:border-box;border:1px solid #40505b;border-radius:10px;background:#14212aed;padding:13px;line-height:1.7}#r5-info summary{cursor:pointer;color:#d8d4c4}#r5-data{font:12px/1.8 system-ui;white-space:pre-line}#r5-actions{position:absolute;bottom:16px;left:16px;right:16px;display:flex;flex-wrap:wrap;gap:7px;justify-content:center}#r5-views{position:absolute;left:16px;top:80px;display:flex;gap:7px;flex-wrap:wrap;max-width:560px}#r5-info p{font-size:11px;color:#a3b3bb;margin:10px 0 0}#r5-export{margin-top:10px;width:100%}
@media(max-width:720px){#r5-top{padding:9px 12px;height:76px;display:block}#r5-top b{font-size:16px}#r5-status{font-size:11px;margin-top:5px}.stage{top:76px!important}#r5-views{top:88px;left:8px;right:8px;max-width:none;gap:4px}#r5-ui button{padding:8px 10px;font-size:11px}#r5-info{top:131px;right:8px;width:190px;padding:8px;font-size:11px}#r5-info:not([open]){width:auto;background:#14212ab8}#r5-actions{bottom:10px;left:6px;right:6px;gap:5px}}
</style>`;
const ui=`<div id="r5-ui"><div id="r5-top"><b>短裤试穿 R5.3 · 原人物版</b><span id="r5-status">正在读取最初 R2 人物…</span></div><div id="r5-views"><button disabled data-r5-view="front">正面</button><button disabled data-r5-view="back">背面</button><button disabled data-r5-view="left">左侧</button><button disabled data-r5-view="right">右侧</button><button disabled data-r5-view="quarter">全身</button><button disabled data-r5-view="quarter" data-close="true">短裤近看</button></div><details id="r5-info"><summary>尺寸卡与制作说明</summary><div id="r5-data">根据当前人物生成，不使用 R4 的人物或旧尺寸卡。</div><button id="r5-export" disabled>保留 / 导出尺寸卡</button><p>连续裤裆、折叠腰头、两个翻折裤脚；原草裙已替换。继承原人体八权重蒙皮与已有动作。骨架随动和大腿避让不是完整布料仿真。原起身动作的落脚可达性未通过，暂不启用。</p></details><div id="r5-actions"><button disabled data-r5-action="reset">站立复位</button><button disabled data-r5-action="walk">行走 1 米</button><button disabled data-r5-action="turn">左转 90°</button><button disabled data-r5-action="sit">坐下</button><button disabled data-r5-action="stand">起身（原动作待修）</button><button disabled data-r5-action="wave">挥手</button><button disabled data-r5-action="pause">暂停 / 继续</button></div></div><script src="./review.js?v=r5-3"></script>`;
body=body.replace(/<title>[^<]*<\/title>/,'<title>短裤试穿 R5.3 · 原人物版</title>').replace('</head>',`<link rel="icon" href="data:,">${style}</head>`).replace('</body>',ui+'</body>');
mkdirSync(out,{recursive:true});write(join(out,'index.html'),body);cpSync(join(root,'reconstruction'),join(out,'reconstruction'),{recursive:true});cpSync(join(here,'review.js'),join(out,'review.js'));write(join(out,'.nojekyll'),'');
const receipt={schema:'shorts-r5-build@1',revision:'R5.3-body-binding',source,body:'original R2; not the new split imported surface',generatorSHA256:createHash('sha256').update(generator).digest('hex'),htmlSHA256:createHash('sha256').update(body).digest('hex'),sliders:false,runtimeExternalCDN:false,physics:'Original eight-influence skinning and local collision envelopes only',knownOriginalControllerFailure:'sit-to-stand foot target out of reach; disabled',productionReady:false};write(join(out,'BUILD.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
