const fs=require('fs'),path=require('path'),crypto=require('crypto'),https=require('https'),{chromium}=require('playwright');
const HTML=process.env.HAIR_KUKO_HTML,OUT=process.env.HAIR_QA_OUT;fs.mkdirSync(OUT,{recursive:true});const bytes=fs.readFileSync(HTML),sha=b=>crypto.createHash('sha256').update(b).digest('hex');const result={timestamp:new Date().toISOString(),htmlSha256:sha(bytes),tests:[],errors:[],requests:[],visualAcceptance:false,productionReady:false,physicalIPhoneTested:false,scope:'Original user-supplied KuKo Day114 SDF. WebGL2 adapter, same-time baseline copy, existing r03/r02 regressions. No tissue/contact claim.'};
function check(name,pass,detail){result.tests.push({name,pass:!!pass,detail});if(!pass)throw Error(name+': '+JSON.stringify(detail));}
function http(url){return new Promise((resolve,reject)=>https.get(url,r=>{const a=[];r.on('data',b=>a.push(b));r.on('end',()=>resolve({status:r.statusCode,bytes:Buffer.concat(a)}));}).on('error',reject));}
async function ready(page){await page.waitForFunction(()=>window.kuko?.ready&&window.workbench?.ready.teacher&&workbench.ready.candidate&&workbench.frameStats.teacher?.frames>=2&&workbench.frameStats.candidate?.frames>=2,null,{timeout:120000});await page.evaluate(()=>{kuko.pause();kuko.seek(0)});}
async function probe(page){return page.evaluate(()=>{kuko.draw();return {pixels:kuko.pixels(),state:kuko.state,errors:[...kuko.errors,...workbench.errors,...anemone.errors],overflow:document.documentElement.scrollWidth>innerWidth};});}
async function sample(page,name){const p=await probe(page);check(name+' live nonblank SDF output',!p.errors.length&&!p.overflow&&p.pixels.every(x=>x.glError===0&&x.alpha&&x.lit>3000),p);await page.screenshot({path:path.join(OUT,name+'.png'),fullPage:true});return p;}
(async()=>{let browser;try{browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text())});page.on('request',r=>{if(!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))result.requests.push(r.url())});if(process.env.HAIR_KUKO_PHASE!=='public'){await page.goto('file://'+HTML,{waitUntil:'load',timeout:120000});await ready(page);
const teacher=await page.evaluate(()=>kuko.source);check('original teacher code exact byte identity',sha(teacher)==='8be527f2e1ebcb5dce18a3b29b2e60c60c295716e4f817c5fd69fa77a3bbf791',{sha256:sha(teacher)});const t0=await sample(page,'kuko-01-file-t0');
await page.evaluate(()=>kuko.seek(2.5));const t25=await sample(page,'kuko-02-file-t2.5');check('time produces actual changing geometry/light',t25.pixels[0].hash!==t0.pixels[0].hash);
const paletteHashes=[];for(const color of ['green','red','blue','yellow']){await page.locator('[data-study-color="'+color+'"]').click();const p=await sample(page,'study-color-'+color);paletteHashes.push(p.pixels[1].hash);check('palette '+color+' leaves teacher exact',p.pixels[0].hash===t25.pixels[0].hash);await page.locator('#kukoCopy').screenshot({path:path.join(OUT,'study-canvas-'+color+'.png')});}
check('four real color controls produce distinct images',new Set(paletteHashes).size===4,paletteHashes);await page.locator('[data-study-color="green"]').click();
await page.locator('#studyVariant').selectOption('original');const orig=await probe(page);check('working copy original switch exactly equals teacher',orig.pixels[0].hash===orig.pixels[1].hash);await page.locator('#studyVariant').selectOption('anemone');
const bound=await page.evaluate(()=>{let min=Infinity;for(let i=0;i<kuko.roots.length;i++)for(let j=0;j<i;j++)min=Math.min(min,Math.hypot(kuko.roots[i][0]-kuko.roots[j][0],kuko.roots[i][1]-kuko.roots[j][1]));return{roots:kuko.roots.length,minRootDistance:min,maxLateralBound:.17,radius:.09,conservativeTubeClearance:min-2*.17-2*.09};});check('bounded nine-root separation has positive analytic margin',bound.roots===9&&bound.conservativeTubeClearance>.24,bound);
const quiet=await page.evaluate(()=>{kuko.setExperiment({current:0,noise:0});kuko.seek(0);kuko.draw();return kuko.pixels()[1].hash});await page.evaluate(()=>kuko.seek(4));check('zero flow/noise is a genuinely static finite cluster',(await probe(page)).pixels[1].hash===quiet);await page.evaluate(()=>{kuko.setExperiment({current:1,noise:1,lengthScale:1.1});kuko.seek(4)});await sample(page,'study-maximum-flow-t4');check('bounded flow actually changes candidate', (await probe(page)).pixels[1].hash!==quiet);const bad=await page.evaluate(()=>{const before=JSON.stringify(kuko.state);let rejected=false;try{kuko.setExperiment({current:2})}catch(e){rejected=true}return rejected&&JSON.stringify(kuko.state)===before});check('out-of-domain changes rejected atomically',bad);await page.locator('#studyReset').click();await page.evaluate(()=>kuko.seek(2.5));
await page.locator('#kukoTeacher').screenshot({path:path.join(OUT,'kuko-canvas-t2.5.png')});const cap=page.waitForEvent('download');await page.locator('#kukoCapture').click();await(await cap).saveAs(path.join(OUT,'kuko-original-960x540-t2.5.png'));check('capture preserves paused clock',(await probe(page)).state.time===2.5);
await page.evaluate(()=>kuko.seek(4.5));await sample(page,'kuko-03-file-t4.5');await page.evaluate(()=>kuko.reset());check('reset restores exact original pixels',(await probe(page)).pixels[0].hash===t0.pixels[0].hash);
await page.evaluate(()=>kuko.pause(false));const start=await page.evaluate(()=>({time:kuko.state.time,frames:kuko.renderers[0].frames,wall:performance.now()}));await page.waitForTimeout(1400);const end=await page.evaluate(()=>{kuko.pause();return{time:kuko.state.time,frames:kuko.renderers[0].frames,wall:performance.now()}});check('real RAF clock and output advance',end.time>start.time+.15&&end.frames>start.frames+1,{start,end});const paused=await probe(page);await page.waitForTimeout(250);check('pause retains exact image and clock',(await probe(page)).pixels[0].hash===paused.pixels[0].hash);
await page.evaluate(()=>{kuko.pause();kuko.seek(2.5)});const state=await page.evaluate(()=>kuko.exportState());const exp=page.waitForEvent('download');await page.locator('#kukoExport').click();const file=path.join(OUT,'exported-kuko-state.json');await(await exp).saveAs(file);await page.evaluate(()=>kuko.seek(1));await page.locator('#kukoFile').setInputFiles(file);await page.waitForFunction(()=>kuko.state.time===2.5);check('actual JSON file input restores exact frame',(await probe(page)).pixels[0].hash===t25.pixels[0].hash);
check('invalid import atomic',await page.evaluate(()=>{const s=JSON.stringify(kuko.state);let rejected=false;try{kuko.importState({...kuko.state,width:123})}catch(e){rejected=true}return rejected&&JSON.stringify(kuko.state)===s}));await page.locator('#kukoSource').click();check('source dialog contains full original',await page.locator('#kukoSourceText').textContent()===teacher);await page.locator('#kukoCloseSource').click();await page.locator('#kukoFocus').click();await sample(page,'kuko-04-original-focus');await page.locator('#kukoCompare').click();await page.locator('#kukoResolution').selectOption('640');const small=await probe(page);check('explicit lower resolution changes both canvases',small.pixels.every(x=>x.width===640&&x.height===360));await page.locator('#kukoResolution').selectOption('960');check('original resolution restored exactly',(await probe(page)).pixels[0].hash===t25.pixels[0].hash);
await page.evaluate(()=>{kuko.pause(false);platform.select('anemone');anemone.pause();anemone.seek(0)});const hidden=await page.evaluate(()=>kuko.state.time);await page.waitForTimeout(150);check('hidden teacher clock stops',await page.evaluate(t=>kuko.state.time===t,hidden));check('r03 anemone still real WebGL',await page.evaluate(()=>{const p=anemone.pixels();return anemone.renderer.frames>0&&anemone.renderer.gl.getError()===0&&anemone.errors.length===0}),await page.evaluate(()=>anemone.metrics()));await page.screenshot({path:path.join(OUT,'kuko-05-r03-retained.png'),fullPage:true});await page.evaluate(()=>platform.select('rabbit'));await page.waitForTimeout(200);const rabbit=await page.frameLocator('#candidateFrame').locator('canvas').evaluate(c=>{renderer.drawScene();const p=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,p);let h=2166136261;for(const x of p)h=Math.imul(h^x,16777619)>>>0;return{hash:h,error:gl.getError(),width:c.width,height:c.height}});check('rabbit frozen r02 image',rabbit.hash===1090190271&&rabbit.error===0,rabbit);await page.evaluate(()=>{platform.select('kuko');kuko.pause();kuko.seek(2.5)});check('module return preserves original teacher',(await probe(page)).pixels[0].hash===t25.pixels[0].hash);check('file core has zero external requests',result.requests.every(x=>x.startsWith('file:')||x==='about:srcdoc'),result.requests.slice());
await page.setViewportSize({width:390,height:844});await sample(page,'kuko-06-file-mobile');check('mobile import remains visible',await page.locator('#kukoImport').isVisible());check('prior document errors zero',(await probe(page)).errors.length===0);if(process.env.HAIR_KUKO_PHASE==='file'){result.passed=true;return;}}
const url='https://haihao0307.github.io/guilin-dem-pipeline/kaopu-hair-workbench/qa/kuko-anemone-candidate.html';let response,deadline=Date.now()+8*60000;do{response=await http(url);if(response.status===200&&sha(response.bytes)===result.htmlSha256)break;await new Promise(r=>setTimeout(r,15000));}while(Date.now()<deadline);check('public exact complete bytes',response.status===200&&sha(response.bytes)===result.htmlSha256,{status:response.status,size:response.bytes.length,sha256:sha(response.bytes)});await page.setViewportSize({width:1440,height:1000});await page.goto(url,{waitUntil:'load',timeout:120000});await ready(page);await page.evaluate(()=>kuko.seek(2.5));await sample(page,'kuko-07-public-desktop');await page.setViewportSize({width:390,height:844});await sample(page,'kuko-08-public-mobile');check('all JS/GL errors zero',!result.errors.length,result.errors);const main=await http('https://haihao0307.github.io/guilin-dem-pipeline/kaopu-hair-workbench/');check('stable main r03 unchanged',sha(main.bytes)==='2b0392ab64f1a8c69d92af8cde640348196f9ea630140b18718f6d6fba0108ed');result.passed=true;
}catch(e){result.passed=false;result.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(OUT,'kuko-'+(process.env.HAIR_KUKO_PHASE||'all')+'-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(browser)await browser.close();}})();
