/** Additive face-groom integration. GNM positions/topology/evaluator are read-only.
 * Teacher data, binding, index-only editor and fibre shaders are copied from the
 * accepted independent hair workbench; no hair-workbench source is modified.
 */
import * as THREE from 'three';
import {modelSnapshot,hydrateBinding} from './groom/GroomFactory.js';
import {createTeacherGroomEditor} from './groom/TeacherGroomEditor.js';
import * as Fiber from './groom/FiberMaterial.js';
import {createHairOpacityShadows} from './groom/HairOpacityShadows.js';
import {geometryFromBinding,refreshBoundGeometry} from './groom/BoundFiberGeometry.js';
import {FACE_GROOM_DEFAULTS,validateGroomOptions} from './groom/GroomOptions.js';
export {FACE_GROOM_DEFAULTS,validateGroomOptions} from './groom/GroomOptions.js';
const hash=a=>{let h=2166136261;for(const v of new Uint8Array(a.buffer,a.byteOffset,a.byteLength))h=Math.imul(h^v,16777619)>>>0;return h.toString(16).padStart(8,'0')};
const yieldFrame=()=>new Promise(r=>setTimeout(r,0));
export async function initFaceGroom({scene,mesh,model,renderer,render,mount,options={}}){
  if(model.numVertices!==17821)throw Error('毛发绑定只支持既定 GNM 拓扑');
  const parent=mount||document.querySelector('#workbench aside');if(!parent)throw Error('毛发控制区不存在');
  const section=document.createElement('section');section.id='faceGroom';section.className='face-groom';
  section.innerHTML=`<h2>毛发 / 绑定当前头模</h2><p class="small">老师原长发与原眉毛，沿真实皮肤变形；睫毛为新增眼睑曲线</p><div class="row"><button data-groom-toggle aria-pressed="false">添加头发 / 眉毛 / 睫毛</button><button data-groom-reset>恢复毛发默认</button></div><p data-groom-status class="small" role="status">点击添加后绑定原始发束；不会影响照片拟合</p><fieldset disabled data-groom-controls><label>发型<select data-groom-key="style"><option value="original">原老师长发</option><option value="chin-trim">原曲线中长裁切</option><option value="cropped-trim">原曲线短层裁切</option></select></label><div class="groom-grid"><label class="check"><input type="checkbox" data-groom-key="hairVisible" checked>头发</label><label>发色<input type="color" data-groom-key="hairColor"></label></div><label>头发长度 <output data-groom-output="hairLength"></output><input type="range" data-groom-key="hairLength" min=".45" max="1" step=".01"></label><label>头发密度 <output data-groom-output="hairDensity"></output><input type="range" data-groom-key="hairDensity" min="0" max="1" step=".01"></label><details><summary>眉毛 / 睫毛调整</summary><div class="groom-grid"><label class="check"><input type="checkbox" data-groom-key="browsVisible" checked>眉毛</label><label>眉色<input type="color" data-groom-key="browsColor"></label></div><label>眉毛长度 <output data-groom-output="browsLength"></output><input type="range" data-groom-key="browsLength" min=".45" max="1" step=".01"></label><label>眉毛密度 <output data-groom-output="browsDensity"></output><input type="range" data-groom-key="browsDensity" min="0" max="1" step=".01"></label><label>眉位上下 <output data-groom-output="browHeight"></output><input type="range" data-groom-key="browHeight" min="-1.5" max="1.5" step=".1"></label><p class="small">眉位放开滑块后重新贴合皮肤，不整块平移悬空</p><div class="groom-grid"><label class="check"><input type="checkbox" data-groom-key="lashesVisible" checked>睫毛</label><label>睫毛色<input type="color" data-groom-key="lashesColor"></label></div><label class="check"><input type="checkbox" data-groom-key="lowerLashes" checked>下睫毛</label><label>睫毛长度 <output data-groom-output="lashesLength"></output><input type="range" data-groom-key="lashesLength" min=".4" max="1.5" step=".01"></label><label>睫毛密度 <output data-groom-output="lashesDensity"></output><input type="range" data-groom-key="lashesDensity" min="0" max="1" step=".01"></label><label>睫毛卷曲 <output data-groom-output="lashesCurl"></output><input type="range" data-groom-key="lashesCurl" min=".35" max="1.6" step=".01"></label><label>头发丝径 <output data-groom-output="hairWidth"></output><input type="range" data-groom-key="hairWidth" min=".5" max="1.6" step=".01"></label><label>眉毛丝径 <output data-groom-output="browsWidth"></output><input type="range" data-groom-key="browsWidth" min=".5" max="1.6" step=".01"></label></details></fieldset><p class="small">三款沿原曲线裁切，保留发根与发缝。极端脸型 / 表情仍需检查穿插。头发和眉毛：Daniel Bystedt · <a href="licenses/TEACHER-GROOM-CC-BY-SA.txt">CC BY-SA</a> · <a href="TEACHER-GROOM-PROVENANCE.json">来源</a></p>`;
  if(mount)parent.append(section);else parent.prepend(section);
  const $=selector=>section.querySelector(selector);let state=validateGroomOptions(options),disposed=false,ready=false,pending=false,revision=0,error=null,opacity=null,opacityCapability=null,worker=null,loadPromise=null,generation=0,browGeneration=0,lightingFallback=false;
  const positions=()=>mesh.geometry.attributes.position.array,normals=()=>mesh.geometry.attributes.normal.array;
  const group=new THREE.Group();group.name='face-groom-additive';scene.add(group);
  const layers={},editors={},materials={},jobs=new Set();const lights=scene.children.filter(x=>x.isDirectionalLight).slice(0,2);
  const snapshot={shadowEnabled:renderer.shadowMap.enabled,shadowType:renderer.shadowMap.type,shadowAuto:renderer.shadowMap.autoUpdate,headCast:mesh.castShadow,headReceive:mesh.receiveShadow,lights:lights.map(l=>({cast:l.castShadow,map:l.shadow.mapSize.clone(),camera:l.shadow.camera.clone(),bias:l.shadow.bias,normalBias:l.shadow.normalBias,radius:l.shadow.radius}))};
  function say(text){$('[data-groom-status]').textContent=text;}
  function syncUI(){for(const el of section.querySelectorAll('[data-groom-key]')){const key=el.dataset.groomKey;if(el.type==='checkbox')el.checked=state[key];else el.value=state[key];const out=$('[data-groom-output="'+key+'"]');if(out)out.textContent=key==='browHeight'?state[key].toFixed(1)+' mm':Math.round(state[key]*100)+'%';}const b=$('[data-groom-toggle]');b.textContent=state.enabled?(ready?'毛发：显示':'取消毛发载入'):(ready?'毛发：隐藏 · R01 净头模':'添加头发 / 眉毛 / 睫毛');b.setAttribute('aria-pressed',String(state.enabled));}
  function setupShadows(enabled){renderer.shadowMap.enabled=enabled||snapshot.shadowEnabled;renderer.shadowMap.type=enabled?THREE.PCFSoftShadowMap:snapshot.shadowType;renderer.shadowMap.autoUpdate=enabled?false:snapshot.shadowAuto;mesh.castShadow=enabled||snapshot.headCast;mesh.receiveShadow=enabled||snapshot.headReceive;lights.forEach((l,i)=>{const s=snapshot.lights[i];l.castShadow=enabled||s.cast;if(enabled){l.shadow.mapSize.set(1536,1536);Object.assign(l.shadow.camera,{left:-.29,right:.29,top:.30,bottom:-.30,near:.05,far:2.5});l.shadow.bias=-.00008;l.shadow.normalBias=.00012;l.shadow.radius=1.5;}else{l.shadow.mapSize.copy(s.map);l.shadow.camera.copy(s.camera);l.shadow.bias=s.bias;l.shadow.normalBias=s.normalBias;l.shadow.radius=s.radius;}l.shadow.camera.updateProjectionMatrix();});renderer.shadowMap.needsUpdate=true;}
  function createLayer(name,binding){const m=new THREE.Mesh(geometryFromBinding(binding,positions(),normals()));m.name='face-groom-'+name;m.renderOrder=name==='hair'?1:name==='brows'?2:3;const fiber=Fiber.attachFiberMaterial(m,{renderer,color:state[name==='hair'?'hairColor':name==='brows'?'browsColor':'lashesColor'],roughness:name==='hair'?.46:.55,specular:.095});layers[name]=m;materials[name]=fiber;group.add(m);if(name!=='lashes')editors[name]=createTeacherGroomEditor(m,binding);return m;}
  function requestBindings(regions=['hair','brows','lashes'],height=state.browHeight){return new Promise((resolve,reject)=>{const job=new Worker(new URL('./groom/BindingWorker.js',import.meta.url),{type:'module'});jobs.add(job);job.cancel=()=>{job.terminate();jobs.delete(job);reject(Object.assign(Error('绑定已取消'),{name:'AbortError'}));};if(regions.length>1)worker=job;job.onmessage=({data})=>{if(data.type==='progress'){say(({hair:'绑定老师原长发…',brows:'贴合原眉毛…',lashes:'生成眼睑曲线睫毛…'})[data.region]);return;}job.terminate();jobs.delete(job);if(worker===job)worker=null;if(data.type==='error'){reject(Error(data.error));return;}resolve(Object.fromEntries(Object.entries(data.bindings).map(([region,raw])=>[region,hydrateBinding(raw,model,region)])));};job.onerror=e=>{job.terminate();jobs.delete(job);if(worker===job)worker=null;reject(Error(e.message||'毛发绑定线程失败'));};job.postMessage({model:modelSnapshot(model),regions,browHeight:height});});}
  function applyLashIndex(){const m=layers.lashes,b=m.geometry.userData.binding,idx=m.geometry.index.array;let cursor=0,active=0;for(let i=0;i<b.count;i++){if((b.lids[i]&&!state.lowerLashes)||((i*73)%b.count)/b.count>=state.lashesDensity)continue;active++;for(let j=0;j<b.segments;j++){const v=(i*b.per+j)*2;idx.set([v,v+1,v+2,v+1,v+3,v+2],cursor);cursor+=6;}}idx.fill(0,cursor);m.geometry.index.needsUpdate=true;m.geometry.setDrawRange(0,cursor);m.userData.activeStrands=active;}
  function applyAppearance(){group.visible=state.enabled;for(const name of ['hair','brows','lashes']){const m=layers[name];m.visible=state[name+'Visible'];Fiber.setFiberModes(m.material,{coverageAA:true,coverageResolve:'blend',shadows:state.enabled});Fiber.setFiberAppearance(m.material,{color:state[name+'Color'],radiusScale:name==='hair'?.0001045/.000037*state.hairWidth:name==='brows'?.00006175/.000045*state.browsWidth:1.35});}editors.hair.apply({style:state.style,length:state.hairLength,density:state.hairDensity});editors.brows.apply({style:'original',length:state.browsLength,density:state.browsDensity});applyLashIndex();setupShadows(state.enabled);opacity?.setEnabled(state.enabled&&!lights.some(light=>!light.visible)&&opacityCapability?.supported);opacity?.markDirty('groom options');syncUI();}
  function update(){if(!ready||disposed)return;if(!state.enabled){pending=true;return;}for(const [name,m]of Object.entries(layers)){if(name==='lashes')m.geometry.userData.binding.setOptions({length:state.lashesLength,curl:state.lashesCurl});refreshBoundGeometry(m,positions(),normals());editors[name]?.updateSource();}revision++;pending=false;opacity?.markDirty('deformed head');renderer.shadowMap.needsUpdate=true;}
  function beforeRender(){if(!ready||disposed||!state.enabled||renderer.getContext().isContextLost())return;if(pending)update();const singleLight=lights.some(light=>!light.visible);if(singleLight!==lightingFallback){lightingFallback=singleLight;opacity?.setEnabled(!singleLight&&state.enabled&&opacityCapability?.supported);say(singleLight?'单灯 / 环境光：使用原纤维投影':'双灯：R8 分层投影'+(opacityCapability?.supported?'已开启':'不可用，使用原投影'));}for(const m of Object.values(layers))Fiber.setFiberViewport(m.material,renderer);const result=opacity?.update();if(result?.error){error=result.error;opacityCapability={...opacityCapability,supported:false,reason:error};say('分层投影不可用，保留纤维与原投影：'+error);}}
  async function rebuildOpacity(){opacity?.dispose();opacity=null;if(lights.length!==2)return;opacity=createHairOpacityShadows({renderer,scene,lights,mapSize:512});opacityCapability=await opacity.init();for(const m of Object.values(layers))opacity.attachFiber(m);opacity.attachHead(mesh);opacity.setEnabled(state.enabled&&!lights.some(light=>!light.visible)&&opacityCapability.supported);}
  function setOptions(patch={}){
    if(disposed)throw Error('毛发组件已关闭');const previous={...state},next=validateGroomOptions({...state,...patch}),changedHeight=next.browHeight!==state.browHeight;state=next;
    if(!ready){syncUI();if(!state.enabled){generation++;worker?.cancel();worker=null;loadPromise=null;clearLayers();setupShadows(false);say('毛发未加载；R01 净头模与照片拟合可继续');return Promise.resolve();}return load();}
    if(changedHeight){const revision=++browGeneration;say('正在重新贴合眉位…');return requestBindings(['brows'],state.browHeight).then(({brows})=>{if(disposed||revision!==browGeneration)return;const old=layers.brows;opacity?.dispose();opacity=null;group.remove(old);materials.brows.dispose();old.geometry.dispose();createLayer('brows',brows);return rebuildOpacity();}).then(()=>{if(disposed||revision!==browGeneration)return;applyAppearance();update();error=null;say('眉位已重新贴合当前皮肤');render();}).catch(e=>{if(revision===browGeneration){state.browHeight=previous.browHeight;syncUI();}throw e;});}
    applyAppearance();if(pending||patch.lashesLength!==undefined||patch.lashesCurl!==undefined)update();render();return Promise.resolve();
  }
  function reset({hide=false}={}){return setOptions({...FACE_GROOM_DEFAULTS,enabled:!hide});}
  function diagnostics(){return {ready,loading:!!loadPromise,disposed,revision,pending,error,options:{...state},headVertices:model.numVertices,headPositionHash:hash(positions()),meshCount:group.children.length,opacityCapability,lightingFallback,bindings:Object.fromEntries(Object.entries(layers).map(([k,m])=>[k,m.geometry.userData.binding.diagnostics()])),editors:Object.fromEntries(Object.entries(editors).map(([k,e])=>[k,e.diagnostics()])),geometryHashes:Object.fromEntries(Object.entries(layers).map(([k,m])=>[k,hash(m.geometry.attributes.position.array)])),lashActive:layers.lashes?.userData.activeStrands,baselineUntouched:true};}
  function dispose(){if(disposed)return;disposed=true;generation++;browGeneration++;for(const job of jobs)job.cancel();worker=null;clearLayers();setupShadows(false);scene.remove(group);section.remove();}
  const api={load,cancelLoading:()=>ready?Promise.resolve():setOptions({enabled:false}),update,beforeRender,setOptions,reset,diagnostics,dispose,getOptions:()=>({...state}),hide:()=>setOptions({enabled:false}),onContextRestored:async()=>{if(!ready||disposed)return;await rebuildOpacity();applyAppearance();pending=true;render();},geometrySnapshot:()=>Object.fromEntries(Object.entries(layers).map(([k,m])=>[k,{positions:m.geometry.attributes.position.array.slice(),roots:m.geometry.userData.binding.roots.slice(),triangles:m.geometry.userData.binding.rootTriangles.slice(),barycentrics:m.geometry.userData.binding.rootBarycentrics.slice()}]))};
  $('[data-groom-toggle]').onclick=()=>setOptions({enabled:!state.enabled}).catch(showError);$('[data-groom-reset]').onclick=()=>reset().catch(showError);for(const el of section.querySelectorAll('[data-groom-key]')){const key=el.dataset.groomKey;el.addEventListener(key==='browHeight'?'change':'input',()=>{try{setOptions({[key]:el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value}).catch(showError);}catch(e){say(e.message);syncUI();}});}syncUI();
  function clearLayers(){opacity?.dispose();opacity=null;for(const [name,m]of Object.entries(layers)){group.remove(m);materials[name].dispose();m.geometry.dispose();delete layers[name];delete materials[name];delete editors[name];}}
  function showError(e){if(e.name==='AbortError')return;error=e.message;if(ready){say('毛发调整未完成：'+e.message+'；当前毛发保留');syncUI();return;}clearLayers();say('毛发未就绪：'+e.message+'；净头模仍可用');group.visible=false;setupShadows(false);state.enabled=false;syncUI();}
  function load(){
    if(disposed)return Promise.reject(Error('毛发组件已关闭'));if(ready){state.enabled=true;applyAppearance();update();render();return Promise.resolve(api);}if(loadPromise)return loadPromise;
    state.enabled=true;error=null;syncUI();const token=++generation;
    loadPromise=(async()=>{try{const bindings=await requestBindings();if(disposed||token!==generation)return api;for(const [name,binding]of Object.entries(bindings)){createLayer(name,binding);await yieldFrame();if(disposed||token!==generation)return api;}await rebuildOpacity();if(disposed||token!==generation)return api;ready=true;applyAppearance();update();$('[data-groom-controls]').disabled=false;say(opacityCapability?.supported?'原长发 / 原眉毛 / 眼睑睫毛已绑定 · R8 分层投影':'原长发 / 原眉毛 / 眼睑睫毛已绑定 · 分层投影不可用，使用原投影');render();return api;}catch(e){if(token!==generation||e.name==='AbortError')return api;showError(e);throw e;}finally{if(token===generation)loadPromise=null;}})();return loadPromise;
  }
  if(state.enabled)load().catch(showError);return api;
}
