import * as THREE from 'three';
const S=window.R39S,{mobile,scene,camera,controls,renderer,MAT,mesh,R}=S;
const {clamp,mix,sm,hash,noise,ridged,rng,geomDetail,fineDetail,mountains,mountainField,baseNatural,terraceMask,terraceInfoFromNatural,gx,gz,nodes,flatFields,pointInPoly,flatFieldAt,riverZ,sourcePath,mainCanal,branchA,branchB,branchC,plainCanal,dseg,polyProjection,dpoly,terrainNoCuts,channelSpecs,channelSurface,terrainY}=window.W;
// Rice/crop instances use the same terrain surface.
const leafGeo=new THREE.PlaneGeometry(.045,.58);leafGeo.translate(0,.29,0);const cropPts=[];for(let x=-136;x<116;x+=mobile?3.4:2.6)for(let z=-128;z<118;z+=mobile?3.4:2.6){const tm=terraceMask(x,z),ff=flatFieldAt(x,z);if(tm>.68){const ti=terraceInfoFromNatural(baseNatural(x,z),x,z);if(ti.f<.62&&hash(x*.2,z*.2)>.18)cropPts.push([x,terrainY(x,z)+.04,z,.72+.28*hash(x,z)]);}else if(ff&&hash(x*.23,z*.21)>.12)cropPts.push([x,ff.bed+.06,z,.72+.3*hash(z,x)]);}const crops=new THREE.InstancedMesh(leafGeo,MAT.crop,cropPts.length);const D=new THREE.Object3D();cropPts.forEach(([x,y,z,s],i)=>{D.position.set(x,y,z);D.rotation.set(0,hash(x,z)*6.28,.08*Math.sin(x+z));D.scale.set(s,s,s);D.updateMatrix();crops.setMatrixAt(i,D.matrix)});crops.castShadow=!mobile;crops.receiveShadow=true;scene.add(crops);

// Trees: dense mountain forest + riparian / field-edge groups, always grounded by terrainY.
const treeSites=[];const treeStep=mobile?9.5:7.2;for(let x=-212;x<212;x+=treeStep)for(let z=-282;z<174;z+=treeStep){const y=terrainY(x,z),tm=terraceMask(x,z),ff=flatFieldAt(x,z),riverDist=Math.abs(z-riverZ(x));let p=0;if(z<-125)p=.72;else if(tm>.2||ff)p=.05;else if(z>120&&riverDist<28)p=.62;else p=.26;if(R()<p){if(ff||tm>.55)continue;treeSites.push([x+(R()-.5)*4,y,z+(R()-.5)*4,3.5+R()*7.5]);}}
const trunkG=new THREE.CylinderGeometry(.09,.17,1,6),crownG=new THREE.IcosahedronGeometry(1,1),trunks=new THREE.InstancedMesh(trunkG,MAT.trunk,treeSites.length),crowns=new THREE.InstancedMesh(crownG,MAT.leaf,treeSites.length*4);treeSites.forEach(([x,y,z,h],i)=>{D.position.set(x,y+h*.34,z);D.scale.set(h*.32,h*.68,h*.32);D.rotation.set(0,R()*6,0);D.updateMatrix();trunks.setMatrixAt(i,D.matrix);for(let j=0;j<4;j++){const a=j*1.57+R()*.4;D.position.set(x+Math.cos(a)*h*.17,y+h*(.60+R()*.25),z+Math.sin(a)*h*.17);D.scale.set(h*(.20+R()*.07),h*(.18+R()*.07),h*(.20+R()*.07));D.rotation.set(R(),R()*6,R());D.updateMatrix();crowns.setMatrixAt(i*4+j,D.matrix)}});trunks.castShadow=!mobile;crowns.castShadow=true;scene.add(trunks,crowns);

// Farmers and one buffalo in the plain paddies, metre-scale and terrain-grounded.
const people=new THREE.Group();scene.add(people);const sphere=new THREE.SphereGeometry(1,10,8),cyl=new THREE.CylinderGeometry(1,1,1,8);function localMesh(g,m,p){const o=new THREE.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}function limb(p,a,b,r,m){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),o=localMesh(cyl,m,p);o.position.copy(A).add(B).multiplyScalar(.5);o.scale.set(r,A.distanceTo(B),r);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),B.sub(A).normalize());return o}function farmer(x,z,bend=0){const g=new THREE.Group();g.position.set(x,terrainY(x,z),z);g.rotation.y=hash(x,z)*6.28;people.add(g);const hip=[0,.78,0],shoulder=[0,1.16,-bend*.35];limb(g,hip,shoulder,.16,MAT.cloth);localMesh(sphere,MAT.skin,g).position.set(0,1.36,-bend*.38);for(const s of[-1,1]){limb(g,[s*.1,.78,0],[s*.15,.38,.02],.055,MAT.dark);limb(g,[s*.15,.38,.02],[s*.18,.07,.03],.04,MAT.skin);limb(g,[s*.16,1.1,-bend*.28],[s*.23,.65,-.35-bend*.22],.045,MAT.cloth);limb(g,[s*.23,.65,-.35-bend*.22],[s*.18,.18,-.62-bend*.28],.032,MAT.skin);}const hat=localMesh(new THREE.ConeGeometry(.31,.18,20),new THREE.MeshStandardMaterial({color:'#c8ae69',roughness:.95}),g);hat.position.set(0,1.55,-bend*.4);hat.rotation.x=-bend*.35;g.scale.setScalar(1)}
[[-42,70,.75],[-18,83,.7],[12,61,.55],[42,94,.65],[-72,46,.2]].forEach(p=>farmer(...p));
function buffalo(x,z){const g=new THREE.Group();g.position.set(x,terrainY(x,z),z);g.rotation.y=-.35;people.add(g);const body=localMesh(sphere,MAT.dark,g);body.scale.set(1.35,.68,.57);body.position.y=.94;const head=localMesh(sphere,MAT.dark,g);head.scale.set(.52,.4,.43);head.position.set(-1.25,1.0,0);for(const xx of[-.55,.48])for(const zz of[-.34,.34])limb(g,[xx,.75,zz],[xx,.08,zz],.065,MAT.dark);for(const zz of[-.23,.23]){const horn=localMesh(new THREE.ConeGeometry(.045,.42,8),MAT.horn,g);horn.position.set(-1.55,1.17,zz);horn.rotation.z=-1.15;horn.rotation.y=zz>0?.22:-.22;}}
buffalo(58,72);

// Flow markers make the entire water path readable, not just decorative.
const fullFlow=[...sourcePath,...mainCanal.slice(1),...branchB.slice(1),...plainCanal.slice(1),[24,riverZ(24)]];const dotG=new THREE.SphereGeometry(.13,7,5),dotM=new THREE.MeshBasicMaterial({color:'#e8f5a6',depthTest:false}),dots=[];for(let j=0;j<18;j++){const o=new THREE.Mesh(dotG,dotM);o.renderOrder=20;scene.add(o);dots.push({o,phase:j/18})}const segL=[];let total=0;for(let i=0;i<fullFlow.length-1;i++){const l=Math.hypot(fullFlow[i+1][0]-fullFlow[i][0],fullFlow[i+1][1]-fullFlow[i][1]);segL.push(l);total+=l}function flowPoint(t){let d=t*total;for(let i=0;i<segL.length;i++){if(d<=segL[i]||i===segL.length-1){const f=clamp(d/segL[i],0,1),x=mix(fullFlow[i][0],fullFlow[i+1][0],f),z=mix(fullFlow[i][1],fullFlow[i+1][1],f);return[x,terrainY(x,z)+.18,z]}d-=segL[i]}}

const views={overview:{p:[190,70,215],t:[-10,13,-45]},terrain:{p:[155,92,95],t:[-5,28,-155]},terrace:{p:[-92,28,38],t:[-38,10,-62]},water:{p:[55,40,78],t:[-30,10,-87]},plain:{p:[120,13,135],t:[5,.6,75]},life:{p:[82,3.0,93],t:[28,.9,72]}};function go(k){camera.position.fromArray(views[k].p);controls.target.fromArray(views[k].t);controls.update();document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v===k))}go('overview');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>go(b.dataset.v));
let start=performance.now();function animate(now){requestAnimationFrame(animate);const t=(now-start)*.000045;for(const d of dots){const p=flowPoint((t+d.phase)%1);d.o.position.set(...p)}controls.update();renderer.render(scene,camera)}requestAnimationFrame(animate);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
window.__FARMLAND_R039__={terrainY,baseNatural,terraceMask,flatFields,treeCount:treeSites.length,cropCount:cropPts.length,views};
