/* Stone Money Island / Survivor Palau. Authored first survival chapter.
   World identities and transitions live here; render buffers are derived.
   Original Ocean Mother V001 sea, sky, spectrum and worker are immutable. */
function createSurvivalChapter(host){
'use strict';
const {gl,canvas,camera,config}=host,TAU=Math.PI*2,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const $=id=>document.getElementById(id),norm=v=>{const l=Math.hypot(...v)||1;return v.map(x=>x/l)},sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
const STORE='stone-money-island.chapter1.v020',FORMAT='smi-world-state/1';
const story='1944 年 10 月。你是一名盟军战斗机飞行员，执行对帕劳群岛间日军小型运输船的攻击任务。飞机受损，无线电失效；你本人没有受伤。向东脱离后迫降，登上救生筏，在海上漂流数日。补给耗尽。现在，你在一片白沙上醒来。你认出了帕劳附近的轮廓，也知道不能贸然向日军控制的岸上求救。';
let rng=49271;const random=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296};
const defs=[
{id:'driftwood-01',type:'wood',name:'直木枝',x:23,z:22},
{id:'driftwood-02',type:'wood',name:'漂来的木枝',x:27,z:24},
{id:'stone-01',type:'stone',name:'可握持的石块',x:23,z:19},
{id:'coconut-01',type:'coconut',name:'完整椰子',x:25,z:20},
{id:'coconut-02',type:'coconut',name:'完整椰子',x:22.5,z:20},
{id:'shell-01',type:'shell',name:'干净的空椰壳',x:28,z:21},
{id:'leaves-01',type:'leaves',name:'落下的宽叶',x:24,z:18.5},
{id:'radio-01',type:'radio',name:'损坏的求生发报装置',x:20,z:23},
{id:'rai-01',type:'rai',name:'石钱',x:23,z:16.5},
{id:'shelter-01',type:'shelter',name:'岩棚深处',x:25.2,z:12.1}
].map(o=>Object.freeze({...o,evidence:'authored-instance',definitionRevision:1}));
const state=()=>({format:FORMAT,revision:0,worldSeconds:0,day:1,phase:'playing',player:{x:24,z:22.8,yaw:-.22,pitch:-.16,crouched:false,food:48,water:34,energy:30},objects:Object.fromEntries(defs.map(o=>[o.id,{location:'world',revision:0}])),spear:false,bed:false,radio:'unknown',fish:{},notes:[],events:[],seen:[],confirmed:false,patrolPassed:false,threat:0,completed:false});
let s=state(),mode='menu',loaded=null,clock=0,wake=0,toastUntil=0,lastUi=0,lastSave=0,thrust=0,cooldown=0,candidate=null,blocked='',caseEpoch=0;
const keys={forward:false,back:false,left:false,right:false};let joy=[0,0],look=null,joyPointer=null;
const palette={wood:[.24,.12,.049],stone:[.37,.39,.35],coconut:[.34,.22,.09],shell:[.40,.23,.10],leaves:[.16,.32,.095],radio:[.30,.30,.25],rai:[.70,.67,.55],sand:[.76,.73,.62]};
// The same shelter slabs define visible surfaces, contact and occlusion.
// This is an authored cave candidate, not a surveyed Palau site.
const slabs=[
{id:'floor',c:[27,1.18,14],r:[3.7,.17,4.1],solid:false},
{id:'west',c:[23.45,3.10,13.8],r:[.65,2.10,4.35]},
{id:'east',c:[30.55,3.12,13.8],r:[.65,2.12,4.35]},
{id:'back',c:[27,3.12,9.8],r:[3.8,2.12,.65]},
{id:'roof',c:[27,5.04,13.8],r:[4.10,.64,4.7]},
{id:'bend',c:[27.15,2.48,14.35],r:[1.15,1.2,.42]}
];
function ground(x,z){let h=host.bed(x,z);if(x>23.3&&x<30.7&&z>9.7&&z<18.1)h=Math.max(h,1.35);if(x>24&&x<30&&z>=18.1&&z<23){const t=(23-z)/4.9;h=Math.max(h,host.bed(x,z)*(1-t)+1.35*t);}return h;}
function canStand(x,z){const y=ground(x,z),sea=host.water(x,z).eta;if(sea-y>1.05)return '水已经太深了，先留在浅水里';if(Math.hypot(x,z)>85)return '先认识这片海岸，不要冒险远行';if(host.rock(x,z)>y+.42)return '前面是岩壁，沿边缘绕过去';const p=[x,y+.76,z];for(const b of slabs)if(b.solid!==false&&b.id!=='roof'&&Math.abs(p[0]-b.c[0])<b.r[0]+.24&&Math.abs(p[2]-b.c[2])<b.r[2]+.24&&Math.abs(p[1]-b.c[1])<b.r[1]+.7)return '岩壁挡住了去路';return '';}
const fish=Array.from({length:12},(_,i)=>({id:'fish-'+String(i+1).padStart(2,'0'),type:i%3,anchor:[31.4+(i%3)*1.9,22+(i%4)*1.25],phase:random()*TAU,length:.44+random()*.23,pos:[0,0,0],yaw:0}));
const birds=Array.from({length:5},(_,i)=>({id:'seabird-'+i,phase:i*1.36,pos:[0,0,0],yaw:0}));
const patrol={pos:[90,0,38],active:false,visible:false,lastCheck:0,cycle:0,start:210};
function locateFish(time){for(const f of fish){const t=time*(.24+f.type*.055)+f.phase,x=f.anchor[0]+Math.sin(t)*1.25,z=f.anchor[1]+Math.cos(t*.87)*.85,water=host.water(x,z).eta,bed=ground(x,z);f.pos=[x,Math.min(water-.17,Math.max(bed+.16,water-.40)),z];f.yaw=Math.atan2(Math.cos(t)*1.25,-Math.sin(t*.87)*.74);}}
function own(type){return defs.filter(d=>d.type===type&&s.objects[d.id].location==='inventory');}
function remaining(d){return s.objects[d.id]?.location==='world';}
function note(key,text){if(s.seen.includes(key))return;s.seen.push(key);s.notes.push({day:s.day,text});}
function event(kind,id,before,after){s.revision++;s.events.push({actionId:'act-'+s.revision,objectId:id,worldTime:s.worldSeconds,day:s.day,kind,before,after});if(s.events.length>250)s.events.shift();}
function transition(id,to){const o=s.objects[id];if(!o||o.location===to)return false;const old=o.location;o.location=to;o.revision++;event('move',id,old,to);return true;}
function toast(text){$('smiToast').textContent=text;toastUntil=clock+5;$('smiToast').classList.add('shown');}
function commit(){try{localStorage.setItem(STORE,JSON.stringify(s));$('smiSaveState').textContent='已在此设备保存';return true;}catch(e){$('smiSaveState').textContent='存档不可用，请勿关闭页面';return false;}}
function validate(v){if(!v||v.format!==FORMAT||!v.player||!Number.isFinite(v.worldSeconds)||v.worldSeconds<0||v.worldSeconds>1e9||!Number.isInteger(v.day)||v.day<1||v.day>10000)return null;for(const k of ['x','z','yaw','pitch','food','water','energy'])if(!Number.isFinite(v.player[k]))return null;if(Math.abs(v.player.x)>100||Math.abs(v.player.z)>100||!defs.every(o=>v.objects?.[o.id]&&['world','inventory','used'].includes(v.objects[o.id].location))||!Array.isArray(v.events)||!Array.isArray(v.notes)||!Array.isArray(v.seen)||typeof v.fish!=='object'||v.fish===null)return null;v.player.food=clamp(v.player.food,0,100);v.player.water=clamp(v.player.water,0,100);v.player.energy=clamp(v.player.energy,0,100);v.threat=clamp(Number(v.threat)||0,0,1);return v;}
try{loaded=validate(JSON.parse(localStorage.getItem(STORE)||'null'));if(loaded?.phase==='failed')loaded=null;}catch(e){loaded=null;}
function clearInput(){joy=[0,0];for(const k in keys)keys[k]=false;look=null;joyPointer=null;const nub=$('smiNub');if(nub)nub.style.transform='translate(-50%,-50%)';}
function start(resume=false){s=resume&&loaded?structuredClone(loaded):state();caseEpoch++;s.phase='playing';mode='playing';wake=resume?3:0;clearInput();s.confirmed=false;config.paused=false;config.fireEnabled=false;config.smokeVisible=false;host.stopCanoe();host.setWorldTime(s.worldSeconds);$('smiMenu').hidden=true;$('smiResult').hidden=true;$('smiHud').hidden=false;$('smiControls').hidden=false;note('arrival','飞机坏了，我没有受伤。只是饿、渴，而且精疲力竭。我认得帕劳，但不能向日军暴露自己。');toast(resume?'回到了你的海岸。':'DAY 1 · 先离开浪能碰到的地方。');locateFish(s.worldSeconds);rebuildStatic();updateUi();commit();audioStart();}
function setMode(next){mode=next;config.paused=next!=='playing';clearInput();$('smiMenu').hidden=next!=='menu';$('smiJournal').hidden=next!=='journal';if(next==='menu'){$('smiContinue').hidden=false;$('smiContinue').textContent='回到海岸';loaded=structuredClone(s);}if(next==='playing')host.resetTime();}
function visibility(a,b){const d=sub(b,a),length=Math.hypot(...d);if(!length)return true;const rd=d.map(v=>v/length);for(const box of slabs){if(box.solid===false)continue;let lo=0,hi=length;for(let k=0;k<3;k++){if(Math.abs(rd[k])<1e-8){if(Math.abs(a[k]-box.c[k])>box.r[k]){hi=-1;break;}}else{let x=(box.c[k]-box.r[k]-a[k])/rd[k],y=(box.c[k]+box.r[k]-a[k])/rd[k];lo=Math.max(lo,Math.min(x,y));hi=Math.min(hi,Math.max(x,y));}}if(hi>=lo&&lo<length-.18&&hi>.15)return false;}for(let t=1;t<length-.5;t+=1.8){const x=a[0]+rd[0]*t,z=a[2]+rd[2]*t,y=a[1]+rd[1]*t;if(host.bed(x,z)>y||host.rock(x,z)>y+.2)return false;}return true;}
function objPos(d){return[d.x,ground(d.x,d.z)+(d.type==='shelter'?.9:d.type==='rai'?1.15:.20),d.z];}
function objective(){if(!own('wood').length&&!s.spear)return{label:'找一根直木枝',id:'driftwood-01'};if(!own('stone').length&&!s.spear)return{label:'找一块可握持的石头',id:'stone-01'};if(!s.spear)return{label:'把木枝加工成木鱼叉',id:null};if(!own('shell').length)return{label:'拾起空椰壳，准备自己的容器',id:'shell-01'};if(!Object.values(s.fish).some(v=>v==='kept'))return{label:'走进浅水，试着刺到一条小鱼',fish:true};if(!own('leaves').length&&!s.bed)return{label:'找些宽叶，整理睡卧处',id:'leaves-01'};if(!s.bed)return{label:'进入岩棚，铺好睡卧处',id:'shelter-01'};if(s.radio==='unknown')return{label:'查看沙滩上的求生装置',id:'radio-01'};if(!s.completed)return{label:'回到岩棚休息，迎来 Day 2',id:'shelter-01'};return{label:'Day 2 · 再认识这片海岸',id:null};}
function findTarget(){const eye=camera.eye,fw=camera.forward;let best=null,score=1e9;for(const d of defs){if(!remaining(d)&&!['rai','shelter'].includes(d.type))continue;const p=objPos(d),dist=Math.hypot(p[0]-s.player.x,p[2]-s.player.z),dir=norm(sub(p,eye)),facing=dot(dir,fw),reach=d.type==='shelter'?3.8:d.type==='rai'?3:2.7;if(dist>reach||facing<-.25)continue;const cost=dist+(1-facing)*1.3;if(cost<score&&visibility(eye,p)){score=cost;best={kind:'object',data:d,distance:dist};}}if(s.spear){for(const f of fish){if(s.fish[f.id])continue;const v=sub(f.pos,eye),depth=dot(v,fw),miss=Math.hypot(...sub(v,fw.map(x=>x*depth)));if(depth<0||depth>3.4||miss>.38||!visibility(eye,f.pos))continue;if(miss<score){best={kind:'fish',data:f,distance:Math.hypot(...v)};score=miss;}}}return best;}
function action(){if(mode!=='playing'||cooldown>0)return;candidate=findTarget();if(!candidate){if(s.spear){thrust=.6;cooldown=.55;toast('没有刺中。靠近一些，让鱼进入准星。');sound('miss');}else toast('靠近材料，再点「拾取」。');return;}const {data:d}=candidate;cooldown=.38;if(candidate.kind==='fish'){if(s.fish[d.id])return;thrust=.6;s.fish[d.id]='kept';event('spear-capture',d.id,'swimming','inventory');note('fish-shape-'+d.type,['第一次观察到银色小鱼。','第一次观察到黄纹鱼。','第一次观察到青背鱼。'][d.type]);toast('捕获 '+['银色小鱼','黄纹鱼','青背鱼'][d.type]+' · 已放入背包，尚未烹饪');sound('reward');}else if(d.type==='rai'){note('rai','洞口有一块带孔的大石盘。这里有比我更久远的故事。');toast('石钱留在原处。发现已经记入日记。');sound('note');}else if(d.type==='radio'){if(s.radio==='damaged'){toast('发报装置仍然损坏，先保存它。');return;}s.radio='damaged';transition(d.id,'inventory');rebuildStatic();note('radio','随救生筏漂来的求生装置已经损坏，不能发报。先保存它；以后需要真正恢复求救能力。');event('inspect',d.id,'unknown','damaged');toast('求生装置已损坏 · 本章不能修好，也不会自动触发救援');}else if(d.type==='shelter'){if(!s.bed){if(!own('leaves').length){toast('需要拾来宽叶，才能铺一个睡卧处。');return;}transition(own('leaves')[0].id,'used');s.bed=true;event('build','bed-01','unbuilt','built');note('shelter','岩棚后方终于有了一处可以休息的地方。');toast('铺好了睡卧处。这里开始像一个家。');rebuildStatic();}else{if(s.threat>.15){toast('巡逻还在观察，先保持隐蔽。');return;}rest();}}else if(remaining(d)){transition(d.id,'inventory');toast('拾取：'+d.name);sound('note');rebuildStatic();}commit();updateUi();}
function craft(){if(mode!=='playing'||s.spear)return;if(!own('wood').length||!own('stone').length){toast('先找到一根直木枝和一块石头。');return;}transition(own('wood')[0].id,'used');s.spear=true;event('craft','spear-01','absent','held');note('spear','第一支木鱼叉还很粗糙，但它是我自己做出来的。');toast('木鱼叉做好了 · 靠近浅水里的鱼，瞄准后刺出');sound('reward');commit();updateUi();}
function coconut(){if(mode!=='playing')return;const c=own('coconut')[0];if(!c){toast('先拾到一个完整椰子。');return;}if(!own('stone').length){toast('需要一块石头辅助打开。');return;}transition(c.id,'used');s.player.food=clamp(s.player.food+18,0,100);s.player.water=clamp(s.player.water+28,0,100);s.player.energy=clamp(s.player.energy+9,0,100);note('coconut','一个椰子让我缓过来一点。空椰壳只能盛水，不会凭空产生淡水。');toast('吃到了椰肉，也喝到了椰子水。');sound('reward');commit();updateUi();}
function rest(){const epoch=caseEpoch;mode='rest';clearInput();$('smiFade').classList.add('dark');commit();setTimeout(()=>{if(epoch!==caseEpoch)return;s.day++;s.worldSeconds+=180;host.setWorldTime(s.worldSeconds);s.player.energy=clamp(s.player.energy+45,0,100);s.player.food=clamp(s.player.food-7,0,100);s.player.water=clamp(s.player.water-9,0,100);event('rest','player','awake','rested');note('day-'+s.day,'Day '+s.day+'：还活着。昨天留下的东西都还在，今天继续认识海岛。');s.completed=s.completed||(s.spear&&Object.values(s.fish).includes('kept')&&s.radio==='damaged');mode='playing';$('smiFade').classList.remove('dark');toast(s.completed?'DAY '+s.day+' · 第一段求生完成。修复电台与救援还在后续章节。':'DAY '+s.day+' · 今天，再活一天。');commit();updateUi();},900);}
function failure(reason){s.confirmed=true;s.phase='failed';mode='failed';clearInput();$('smiResult').hidden=false;$('smiResultTitle').textContent='这一次，没能回家';$('smiResultText').textContent=reason;event('failure','player','active','failed');commit();}
function tick(dt,world){$('smiStart').disabled=!host.ready();$('smiContinue').disabled=!host.ready();clock+=dt;cooldown=Math.max(0,cooldown-dt);thrust=Math.max(0,thrust-dt);if(mode!=='playing')return;wake=Math.min(3,wake+dt);s.worldSeconds=world;s.player.food=Math.max(0,s.player.food-dt*.017);s.player.water=Math.max(0,s.player.water-dt*.024);const forward=(keys.forward?1:0)-(keys.back?1:0)-joy[1],side=(keys.right?1:0)-(keys.left?1:0)+joy[0],len=Math.max(1,Math.hypot(forward,side)),f=forward/len,r=side/len;let dx=Math.sin(s.player.yaw)*f+Math.cos(s.player.yaw)*r,dz=-Math.cos(s.player.yaw)*f+Math.sin(s.player.yaw)*r;const moving=Math.hypot(dx,dz)>.03;if(moving&&wake>1.2){const depth=Math.max(0,host.water(s.player.x,s.player.z).eta-ground(s.player.x,s.player.z)),speed=(s.player.crouched?.9:2.6)*(depth>.12?.55:1)*(s.player.energy<15?.7:1);dx*=dt*speed;dz*=dt*speed;const steps=Math.ceil(Math.hypot(dx,dz)/.10)||1;for(let j=0;j<steps;j++){const ox=s.player.x,oz=s.player.z,h=ground(ox,oz),reason=canStand(ox+dx/steps,oz+dz/steps);if(!reason&&Math.abs(ground(ox+dx/steps,oz+dz/steps)-h)<.36){s.player.x+=dx/steps;s.player.z+=dz/steps;blocked='';}else{blocked=reason||'坡面太陡，绕着岩壁走';if(!canStand(ox+dx/steps,oz)&&Math.abs(ground(ox+dx/steps,oz)-h)<.3)s.player.x+=dx/steps;if(!canStand(s.player.x,oz+dz/steps)&&Math.abs(ground(s.player.x,oz+dz/steps)-h)<.3)s.player.z+=dz/steps;}}s.player.energy=Math.max(0,s.player.energy-dt*.035);}else{s.player.energy=Math.min(100,s.player.energy+dt*.06);blocked='';}
locateFish(s.worldSeconds);for(let i=0;i<birds.length;i++){const b=birds[i],t=s.worldSeconds*.075+b.phase;b.pos=[Math.sin(t)*36,18+i*2+Math.sin(t*2.3),Math.cos(t)*36];b.yaw=t+Math.PI/2;}const t=s.worldSeconds,cycle=Math.floor(Math.max(0,t-210)/210),phase=t-210-cycle*210;patrol.active=t>=210&&phase<55;patrol.cycle=cycle;patrol.pos=[52+Math.sin(phase*.034)*11,host.water(55,15).eta+.20,48-phase*1.25];if(patrol.active&&!s.seen.includes('patrol-'+cycle)){note('patrol-'+cycle,'听见了巡逻艇。它会从湾外经过；岩壁遮挡与距离决定我是否暴露。');toast('远处传来发动机声 · 留意东侧水道');sound('warning');}if(clock-patrol.lastCheck>.2){patrol.lastCheck=clock;const eye=[s.player.x,ground(s.player.x,s.player.z)+(s.player.crouched?.75:1.62),s.player.z],boat=[patrol.pos[0],patrol.pos[1]+2,patrol.pos[2]],d=Math.hypot(...sub(eye,boat));patrol.visible=patrol.active&&d<72&&visibility(boat,eye);}if(patrol.active&&patrol.visible)s.threat=clamp(s.threat+dt*(s.player.crouched?.055:.12),0,1);else s.threat=Math.max(0,s.threat-dt*.22);if(!patrol.active&&t>265)s.patrolPassed=true;if(s.threat>=1)failure('巡逻艇确认了你的藏身位置。本次生存结束。');if(s.player.food<=0||s.player.water<=0)failure('饥饿与口渴耗尽了体力。下次先收集椰子，稳住最初几天的生活。');if(clock-lastUi>.15){lastUi=clock;candidate=findTarget();updateUi();}if(clock-lastSave>8){lastSave=clock;commit();}if(clock>toastUntil)$('smiToast').classList.remove('shown');}
function cameraFrame(aspect){if(mode==='menu')return false;const p=s.player,h=ground(p.x,p.z),rise=.40+(p.crouched?.42:1.24)*Math.min(1,wake/2.3);camera.eye=[p.x,h+rise,p.z];camera.forward=norm([Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),-Math.cos(p.yaw)*Math.cos(p.pitch)]);camera.right=norm(cross(camera.forward,[0,1,0]));camera.up=cross(camera.right,camera.forward);camera.target=camera.eye.map((v,i)=>v+camera.forward[i]);camera.fov=62*Math.PI/180;host.lookAt(camera.view,camera.eye,camera.target,[0,1,0]);host.perspective(camera.proj,camera.fov,aspect,.08,60000);return true;}
function targetText(){if(!candidate)return s.spear?'刺鱼':'拾取';if(candidate.kind==='fish')return'刺鱼';const d=candidate.data;return d.type==='shelter'?(s.bed?'休息到明天':'铺好睡卧处'):d.type==='rai'?'观察石钱':d.type==='radio'?'查看装置':'拾取';}
function updateUi(){if(!$('smiDay'))return;const p=s.player;$('smiDay').textContent='DAY '+s.day;$('smiMeters').textContent='饮水 '+Math.round(p.water)+' · 饱食 '+Math.round(p.food)+' · 体力 '+Math.round(p.energy);const goal=objective();$('smiGoal').textContent=goal.label;$('smiPrimary').textContent=targetText();$('smiPrimary').classList.toggle('ready',!!candidate);$('smiTarget').textContent=candidate?(candidate.kind==='fish'?['银色小鱼','黄纹鱼','青背鱼'][candidate.data.type]:candidate.data.name)+' · '+candidate.distance.toFixed(1)+' m':blocked;$('smiCraft').hidden=s.spear||!own('wood').length||!own('stone').length;$('smiEat').hidden=!own('coconut').length;$('smiCrouch').textContent=p.crouched?'站起':'蹲下';$('smiCross').classList.toggle('aimed',candidate?.kind==='fish');$('smiDanger').hidden=!(patrol.active||s.threat>.01);$('smiDangerText').textContent=patrol.visible?'巡逻艇正在观察你，退到岩壁后面':s.threat>.1?'保持隐蔽，等待疑虑消退':'远处有巡逻艇';$('smiDangerFill').style.width=(s.threat*100)+'%';$('smiBag').textContent='背包 '+(defs.filter(d=>s.objects[d.id].location==='inventory').length+Object.values(s.fish).filter(x=>x==='kept').length);$('smiJournalContent').textContent=s.notes.map(n=>'DAY '+n.day+'\n'+n.text).join('\n\n');$('smiInventory').textContent=[...defs.filter(d=>s.objects[d.id].location==='inventory').map(d=>d.name),...(s.spear?['木鱼叉']:[]),...Object.entries(s.fish).filter(([,v])=>v==='kept').map(()=> '未烹饪的小鱼')].join(' · ')||'没有物资';const d=defs.find(d=>d.id===goal.id),loc=d?objPos(d):goal.fish?fish.find(f=>!s.fish[f.id])?.pos:null;if(loc){const v=sub(loc,camera.eye),z=dot(v,camera.forward),right=dot(v,camera.right),angle=Math.atan2(right,z);$('smiGuide').textContent=(Math.abs(angle)<.35?'前方':angle>0?'右侧':'左侧')+' '+Math.round(Math.hypot(loc[0]-p.x,loc[2]-p.z))+' m';}else $('smiGuide').textContent='';}
function shader(type,text){const v=gl.createShader(type);gl.shaderSource(v,text);gl.compileShader(v);if(!gl.getShaderParameter(v,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(v));return v;}
const vs=`#version 300 es
precision highp float;layout(location=0)in vec3 a;layout(location=1)in vec3 n;layout(location=2)in vec3 c;uniform mat4 P,V,M;out vec3 N,C,W;void main(){vec4 p=M*vec4(a,1);W=p.xyz;N=mat3(M)*n;C=c;gl_Position=P*V*p;}`;
const fs=`#version 300 es
precision highp float;in vec3 N,C,W;uniform vec3 sun,eye;uniform float shade;out vec4 O;void main(){float l=max(dot(normalize(N),sun),0.);float grain=.96+.04*sin(W.x*39.+sin(W.z*37.)+W.y*27.);vec3 c=C*grain*(.35+.85*l)*shade;c=c*(2.51*c+.03)/(c*(2.43*c+.59)+.14);O=vec4(pow(clamp(c,0.,1.),vec3(1./2.2)),1);}`;
const prog=gl.createProgram(),va=shader(gl.VERTEX_SHADER,vs),fa=shader(gl.FRAGMENT_SHADER,fs);gl.attachShader(prog,va);gl.attachShader(prog,fa);gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));gl.deleteShader(va);gl.deleteShader(fa);const loc=Object.fromEntries(['P','V','M','sun','eye','shade'].map(k=>[k,gl.getUniformLocation(prog,k)]));
function builder(){const a=[];function tri(p,q,r,c){const n=norm(cross(sub(q,p),sub(r,p)));for(const v of[p,q,r])a.push(...v,...n,...c);}function quad(p,q,r,t,c){tri(p,q,r,c);tri(p,r,t,c);}function box(c,r,col){const pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(v=>v.map((x,i)=>c[i]+x*r[i]));for(const ids of[[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])quad(...ids.map(i=>pts[i]),col);}function ell(c,r,col,rows=8,cols=14){const pt=(v,u)=>[c[0]+Math.sin(v)*Math.cos(u)*r[0],c[1]+Math.cos(v)*r[1],c[2]+Math.sin(v)*Math.sin(u)*r[2]];for(let i=0;i<rows;i++)for(let j=0;j<cols;j++)quad(pt(i/rows*Math.PI,j/cols*TAU),pt((i+1)/rows*Math.PI,j/cols*TAU),pt((i+1)/rows*Math.PI,(j+1)/cols*TAU),pt(i/rows*Math.PI,(j+1)/cols*TAU),col);}function rod(p,q,r,col){const axis=norm(sub(q,p)),x=norm(cross(axis,Math.abs(axis[1])<.9?[0,1,0]:[1,0,0])),y=cross(axis,x),pt=(c,t)=>c.map((v,k)=>v+r*(x[k]*Math.cos(t)+y[k]*Math.sin(t)));for(let i=0;i<9;i++)quad(pt(p,i/9*TAU),pt(q,i/9*TAU),pt(q,(i+1)/9*TAU),pt(p,(i+1)/9*TAU),col);}function ring(c,r,hole,depth,col){for(let i=0;i<56;i++){const x=i/56*TAU,y=(i+1)/56*TAU,p=(t,r,z)=>[c[0]+Math.cos(t)*r,c[1]+Math.sin(t)*r,c[2]+z];for(const z of[-depth,depth])quad(p(x,r,z),p(y,r,z),p(y,hole,z),p(x,hole,z),col);quad(p(x,r,-depth),p(y,r,-depth),p(y,r,depth),p(x,r,depth),col);quad(p(x,hole,-depth),p(y,hole,-depth),p(y,hole,depth),p(x,hole,depth),col);}}function upload(){const vao=gl.createVertexArray(),buf=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,36,i*12);}gl.bindVertexArray(null);return{vao,buf,count:a.length/9};}return{tri,quad,box,ell,rod,ring,upload};}
function matrix(x,y,z,yaw=0,scale=1){const c=Math.cos(yaw)*scale,n=Math.sin(yaw)*scale;return new Float32Array([c,0,-n,0,0,scale,0,0,n,0,c,0,x,y,z,1]);}
function dispose(g){if(g){gl.deleteVertexArray(g.vao);gl.deleteBuffer(g.buf);}}
let staticGeo;
function rebuildStatic(){dispose(staticGeo);const b=builder();for(const v of slabs)b.box(v.c,v.r,v.id==='floor'?palette.sand:[.34,.35,.31]);b.quad([24,1.35,18.1],[30,1.35,18.1],[30,host.bed(30,23)+.025,23],[24,host.bed(24,23)+.025,23],palette.sand);for(const d of defs){if(!remaining(d)||d.type==='shelter')continue;const p=objPos(d),c=palette[d.type];if(d.type==='wood')b.rod([p[0]-.62,p[1]-.1,p[2]-.2],[p[0]+.62,p[1]-.05,p[2]+.2],.048,c);else if(d.type==='stone')b.ell(p,[.21,.12,.16],c);else if(d.type==='coconut'){b.ell(p,[.19,.24,.19],c);b.ell([p[0],p[1]+.20,p[2]],[.08,.06,.08],[.19,.14,.05]);}else if(d.type==='shell')b.ring([p[0],p[1],p[2]],.23,.13,.075,c);else if(d.type==='leaves'){for(let i=0;i<6;i++)b.ell([p[0]+i*.07,p[1]-.12,p[2]+i*.04],[.4,.028,.13],c,4,8);}else if(d.type==='radio'){b.box(p,[.24,.18,.18],c);b.box([p[0],p[1]+.19,p[2]],[.11,.03,.05],[.10,.11,.09]);b.rod([p[0]-.2,p[1],p[2]],[p[0]-.46,p[1]+.18,p[2]+.10],.025,[.38,.37,.3]);}else if(d.type==='rai')b.ring(p,1.15,.20,.18,c);}if(s.bed){b.box([25.2,1.47,12.1],[1.1,.12,.58],[.13,.24,.08]);for(let i=0;i<14;i++)b.rod([24.2+i*.14,1.61,11.65],[24.2+i*.14,1.61,12.55],.033,[.23,.33,.11]);}staticGeo=b.upload();}
const fishGeo=[0,1,2].map(t=>{const b=builder(),col=[[.58,.68,.65],[.53,.45,.08],[.10,.36,.40]][t];b.ell([0,0,0],[.18,.28,.60],col);b.tri([0,0,-.48],[0,.35,-.95],[0,0,-.74],col);b.tri([0,0,-.48],[0,0,-.74],[0,-.35,-.95],col);b.tri([0,.15,.1],[0,.45,-.2],[0,.15,-.42],col);b.ell([.11,.095,.43],[.025,.04,.038],[.015,.024,.026],5,8);b.ell([-.11,.095,.43],[.025,.04,.038],[.015,.024,.026],5,8);return b.upload();});
const birdGeo=(()=>{const b=builder();b.ell([0,0,0],[.13,.13,.44],[.70,.73,.71]);b.tri([-.08,0,.17],[-1,.07,-.3],[-.27,.02,-.25],[.60,.65,.65]);b.tri([.08,0,.17],[.27,.02,-.25],[1,.07,-.3],[.60,.65,.65]);return b.upload();})();
const boatGeo=(()=>{const b=builder();b.ell([0,.3,0],[1.25,.7,4.3],[.15,.18,.16]);b.box([0,1,0],[.65,.65,1.05],[.26,.27,.23]);b.rod([0,1.5,0],[0,3.6,0],.04,[.2,.2,.17]);return b.upload();})();
const spearGeo=(()=>{const b=builder();b.rod([.28,-.38,-.25],[.08,-.20,1.20],.020,palette.wood);b.tri([.06,-.20,1.15],[.10,-.20,1.15],[.08,-.20,1.46],[.53,.40,.19]);b.ell([.25,-.35,-.05],[.055,.048,.13],[.50,.30,.18]);return b.upload();})();
function draw(g,m=matrix(0,0,0),shade=1){gl.uniformMatrix4fv(loc.M,false,m);gl.uniform1f(loc.shade,shade);gl.bindVertexArray(g.vao);gl.drawArrays(gl.TRIANGLES,0,g.count);host.count(g.count/3);}
function setup(){gl.useProgram(prog);gl.uniformMatrix4fv(loc.P,false,camera.proj);gl.uniformMatrix4fv(loc.V,false,camera.view);gl.uniform3fv(loc.sun,host.sun());gl.uniform3fv(loc.eye,camera.eye);gl.disable(gl.CULL_FACE);gl.disable(gl.BLEND);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LESS);gl.depthMask(true);}
function drawWorld(){if(mode==='menu')return;setup();draw(staticGeo);for(const f of fish)if(!s.fish[f.id])draw(fishGeo[f.type],matrix(...f.pos,f.yaw,f.length));for(const b of birds)draw(birdGeo,matrix(...b.pos,b.yaw));if(patrol.active)draw(boatGeo,matrix(...patrol.pos,Math.PI));}
function drawHand(){if(!s.spear||mode==='menu')return;setup();gl.disable(gl.DEPTH_TEST);const r=camera.right,u=camera.up,f=camera.forward,eye=camera.eye,pulse=thrust>0?Math.sin(thrust/.6*Math.PI)*.30:0,pos=eye.map((v,i)=>v+f[i]*(.3+pulse)),m=new Float32Array([r[0],r[1],r[2],0,u[0],u[1],u[2],0,f[0],f[1],f[2],0,...pos,1]);draw(spearGeo,m);gl.enable(gl.DEPTH_TEST);}
let ac=null,master=null,audioEnabled=false,musicTimer=null,noteIndex=0;
function tone(freq,duration=.18,at=0,volume=.05,type='sine'){if(!ac||!audioEnabled)return;const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+at;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(master);o.start(t);o.stop(t+duration+.03);}
function sound(kind){if(kind==='reward'){tone(392,.35);tone(523.25,.5,.14);tone(659.25,.65,.27);}else if(kind==='warning'){tone(146.8,.7,0,.055,'triangle');tone(138.6,.6,.30,.04,'triangle');}else if(kind==='note')tone(440,.20);else tone(110,.12,0,.02);}
function audioStart(){if(!audioEnabled)return;try{if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.45;master.connect(ac.destination);}ac.resume().catch(()=>{});if(!musicTimer)musicTimer=setInterval(()=>{if(document.hidden||!audioEnabled||mode==='failed')return;const seq=[261.63,329.63,392,440,392,329.63,293.66,196];tone(seq[noteIndex++%seq.length],1.35,0,.028,'triangle');},1100);}catch(e){audioEnabled=false;}}
function ui(){const wrap=document.createElement('div');wrap.id='smiRoot';wrap.innerHTML=`
<section id="smiMenu" class="smiOverlay"><div class="smiTitle"><div class="smiEyebrow">A KAOPU OCEAN STORY</div><h1>STONE MONEY<br><span>ISLAND</span></h1><h2>SURVIVOR PALAU</h2><p id="smiPremise">第一天，只想再活一天。<br>最后，终于可以回家。</p><div class="smiStartRow"><button id="smiStart">在白沙滩醒来</button><button id="smiContinue" ${loaded?'':'hidden'}>继续生存 · DAY ${loaded?.day||1}</button></div><div class="smiMenuSmall"><button id="smiMusic">音乐：关闭</button><button id="smiStory">前情</button><span>第一章 · 岸边求生 V0.2.0</span></div><p id="smiBackstory" hidden></p><small>旧海天原件保留 · 可玩章节候选，非历史复原完成版</small></div></section>
<div id="smiHud" hidden><header><div><b id="smiDay">DAY 1</b><small>STONE MONEY ISLAND · SURVIVOR PALAU</small></div><button id="smiBag">背包 0</button><button id="smiMenuButton" aria-label="暂停与菜单">Ⅱ</button></header><div id="smiObjective"><span id="smiGoal"></span><small id="smiGuide"></small></div><div id="smiDanger" hidden><span id="smiDangerText"></span><div><i id="smiDangerFill"></i></div></div><div id="smiCross">·</div><div id="smiTarget"></div><div id="smiToast" role="status" aria-live="polite"></div><footer><span id="smiMeters"></span><small id="smiSaveState">此设备存档</small></footer></div>
<div id="smiControls" hidden><div id="smiJoy" aria-label="移动摇杆"><span id="smiNub"></span><small>移动</small></div><div id="smiActions"><button id="smiCraft" hidden>制作木鱼叉</button><button id="smiEat" hidden>打开椰子</button><button id="smiPrimary">拾取</button><button id="smiCrouch">蹲下</button></div><p id="smiHelp">WASD 移动 · 拖动画面转头 · E 互动 · C 蹲下</p></div>
<section id="smiJournal" class="smiOverlay" hidden><article><button id="smiCloseJournal">返回海岸</button><h2>漂流者的记录</h2><h3>随身物品</h3><p id="smiInventory"></p><h3>日记</h3><p id="smiJournalContent"></p><p class="smiBoundary">发报装置修复、钩线垂钓和最终救援尚未接入本章。鱼的外观与运动为程序候选，暂不标注真实物种。</p></article></section>
<section id="smiResult" class="smiOverlay" hidden><article><h2 id="smiResultTitle"></h2><p id="smiResultText"></p><button id="smiRetry">重新从 Day 1 开始</button></article></section><div id="smiFade"></div>`;document.body.append(wrap);
$('smiBackstory').textContent=story;$('smiStart').onclick=()=>{if(s.revision>0||loaded){$('smiStart').textContent='确认重新开始？旧存档将替换';$('smiStart').onclick=()=>start(false);}else start(false);};$('smiContinue').onclick=()=>start(true);$('smiRetry').onclick=()=>start(false);$('smiStory').onclick=()=>$('smiBackstory').hidden=!$('smiBackstory').hidden;$('smiMusic').onclick=()=>{audioEnabled=!audioEnabled;$('smiMusic').textContent='音乐：'+(audioEnabled?'开启':'关闭');if(audioEnabled)audioStart();else if(ac)ac.suspend().catch(()=>{});};$('smiMenuButton').onclick=()=>{commit();setMode('menu');};$('smiBag').onclick=()=>{updateUi();setMode('journal');};$('smiCloseJournal').onclick=()=>setMode('playing');$('smiPrimary').onclick=action;$('smiCraft').onclick=craft;$('smiEat').onclick=coconut;$('smiCrouch').onclick=()=>{s.player.crouched=!s.player.crouched;updateUi();};
const map={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(mode!=='playing'){if(e.code==='Escape'&&mode==='journal')setMode('playing');return;}if(map[e.code]){e.preventDefault();keys[map[e.code]]=true;}if(e.repeat)return;if(e.code==='KeyE'){e.preventDefault();action();}if(e.code==='KeyC')$('smiCrouch').click();if(e.code==='KeyJ')$('smiBag').click();if(e.code==='Escape')setMode('menu');});addEventListener('keyup',e=>{if(map[e.code])keys[map[e.code]]=false;});addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){commit();if(ac)ac.suspend().catch(()=>{});}else if(ac&&audioEnabled)ac.resume().catch(()=>{});});
canvas.addEventListener('pointerdown',e=>{if(mode!=='playing')return;look={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!look||e.pointerId!==look.id||mode!=='playing')return;s.player.yaw+=(e.clientX-look.x)*.004;s.player.pitch=clamp(s.player.pitch-(e.clientY-look.y)*.004,-1.25,.9);look.x=e.clientX;look.y=e.clientY;});canvas.addEventListener('pointerup',()=>look=null);canvas.addEventListener('pointercancel',()=>look=null);
const j=$('smiJoy'),move=e=>{if(joyPointer!==e.pointerId)return;const r=j.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38,len=Math.max(1,Math.hypot(x,y));joy=[x/len,y/len];$('smiNub').style.transform=`translate(calc(-50% + ${joy[0]*34}px),calc(-50% + ${joy[1]*34}px))`;};j.onpointerdown=e=>{e.preventDefault();joyPointer=e.pointerId;j.setPointerCapture(e.pointerId);move(e);};j.onpointermove=move;j.onpointerup=j.onpointercancel=e=>{if(e.pointerId===joyPointer)clearInput();};
}
ui();rebuildStatic();locateFish(0);config.fireEnabled=false;config.smokeVisible=false;config.paused=false;
const api={tick,cameraFrame,drawWorld,drawHand,getState:()=>structuredClone(s),getDefinitions:()=>defs.map(d=>({...d,position:objPos(d)})),getFish:()=>fish.map(f=>({...f,pos:[...f.pos],state:s.fish[f.id]||'swimming'})),getMode:()=>mode,ground,visibility,canStand,commit,version:'0.2.0',diagnostics:()=>({mode,worldTime:s.worldSeconds,day:s.day,injury:false,patrol:{...patrol},target:candidate?.data.id,objectCount:defs.length,fishCount:fish.length,staticTriangles:staticGeo.count/3,audioState:ac?.state||'off',source:'object definitions + state + relations; original sea/sky retained',limitations:['authored cave geometry','approximate inherited rock occlusion','unverified fish species','no radio repair or rescue','no real iPhone performance proof']})};
if(new URLSearchParams(location.search).has('qa'))api.test={position:(x,z,yaw=0,pitch=-.3)=>{if(!Number.isFinite(x+z+yaw+pitch))throw Error('Invalid QA position');Object.assign(s.player,{x,z,yaw,pitch});wake=3;},time:t=>{s.worldSeconds=t;host.setWorldTime(t);locateFish(t);},advance:seconds=>{for(let t=0;t<seconds;t+=.05)tick(.05,s.worldSeconds+.05);host.setWorldTime(s.worldSeconds);},act:action,craft,coconut,rest,validate,clearInput};
window.StoneMoneySurvival=api;return api;
}
