import*as THREE from'../source/registration-vendor/three.module.js';
import{OrbitControls}from'./vendor/OrbitControls.js';
/** One canonical mesh. Retains the published R01 lighting/material/camera conventions. */
export class CommonViewer{
 constructor({canvas,container,model,onStatus=()=>{}}){
  this.canvas=canvas;this.container=container;this.model=model;this.onStatus=onStatus;this.active=true;this.wire=false;this.band=false;this.lost=false;this.renders=0;
  this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setClearColor(0x242c32);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(31,1,.01,50);this.orbit=new OrbitControls(this.camera,canvas);this.orbit.enableDamping=false;this.onOrbit=()=>this.render();this.orbit.addEventListener('change',this.onOrbit);
  this.scene.add(new THREE.HemisphereLight(0xdfefff,0x353945,1.6));const key=new THREE.DirectionalLight(0xffdac1,3.2);key.position.set(-2,3,4);const rim=new THREE.DirectionalLight(0xa3c2df,2.6);rim.position.set(2,2,-2);this.scene.add(key,rim);
  this.displayPositions=new Float32Array(model.positions.length);this.geometry=new THREE.BufferGeometry();this.geometry.setAttribute('position',new THREE.BufferAttribute(this.displayPositions,3));this.geometry.setIndex(new THREE.BufferAttribute(model.faces,1));const colors=new Float32Array(model.vertexCount*3),base=new THREE.Color(0xbab3a5);for(let i=0;i<model.vertexCount;i++)colors.set([base.r,base.g,base.b],i*3);this.geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));
  this.material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.72,metalness:0,side:THREE.FrontSide});this.mesh=new THREE.Mesh(this.geometry,this.material);this.scene.add(this.mesh);
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);
  this.onLost=e=>{e.preventDefault();if(!this.active)return;this.lost=true;onStatus('图形上下文暂停；参数仍保留');};this.onRestored=()=>{if(!this.active)return;this.lost=false;this.renderer.setClearColor(0x242c32);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.material.needsUpdate=true;this.update();this.resize();onStatus('已恢复同一个共同网格');};canvas.addEventListener('webglcontextlost',this.onLost);canvas.addEventListener('webglcontextrestored',this.onRestored);
  this.update();this.resize();this.view('three');
 }
 update(){if(!this.active)return;const v=this.model.positions,p=this.displayPositions;for(let i=0;i<v.length;i+=3){p[i]=v[i];p[i+1]=v[i+2];p[i+2]=-v[i+1];}this.geometry.attributes.position.needsUpdate=true;this.geometry.computeVertexNormals();this.geometry.computeBoundingSphere();this.render();}
 resize(){if(!this.active)return;const r=this.container.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.render();}
 render(){if(this.active&&!this.lost){this.renderer.render(this.scene,this.camera);this.renders++;}}
 view(which='three'){if(!this.active)return;const box=new THREE.Box3().setFromBufferAttribute(this.geometry.attributes.position),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());let distance=Math.max(size.y,size.x/this.camera.aspect)/(2*Math.tan(this.camera.fov*Math.PI/360))*1.16;const angle=which==='side'?Math.PI/2:which==='rear'?Math.PI:which==='three'?.48:0;if(which==='face'){const headBox=new THREE.Box3();for(let i=this.model.bodyCount;i<this.model.vertexCount;i++)headBox.expandByPoint(new THREE.Vector3(this.displayPositions[i*3],this.displayPositions[i*3+1],this.displayPositions[i*3+2]));headBox.getCenter(center);const headSize=headBox.getSize(new THREE.Vector3());distance=Math.max(headSize.y,headSize.x/this.camera.aspect)/(2*Math.tan(this.camera.fov*Math.PI/360))*1.25;}this.camera.position.copy(center).add(new THREE.Vector3(Math.sin(angle)*distance,0,Math.cos(angle)*distance));this.orbit.target.copy(center);this.camera.zoom=1;this.camera.updateProjectionMatrix();this.orbit.update();this.render();}
 setWire(value){this.wire=!!value;this.material.wireframe=this.wire;this.render();}
 setBand(value){this.band=!!value;const colors=this.geometry.attributes.color,base=new THREE.Color(0xbab3a5),indices=new Set([...this.model.canonical.bodyRing,...this.model.canonical.headRing]);for(let i=0;i<this.model.vertexCount;i++)colors.setXYZ(i,...(this.band&&indices.has(i)?[.9,.32,.08]:[base.r,base.g,base.b]));colors.needsUpdate=true;this.render();}
 screenshot(){this.render();return new Promise((resolve,reject)=>this.canvas.toBlob(blob=>blob?resolve(blob):reject(Error('截图失败')),'image/png'));}
 cameraState(){return{position:this.camera.position.toArray(),target:this.orbit.target.toArray(),zoom:this.camera.zoom};}
 restoreCamera(saved){if(!saved||!this.active)return;this.camera.position.fromArray(saved.position);this.orbit.target.fromArray(saved.target);this.camera.zoom=saved.zoom;this.camera.updateProjectionMatrix();this.orbit.update();this.render();}
 pixelAudit(){this.render();const gl=this.renderer.getContext(),pixels=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,pixels);const colors=new Set();for(let i=0;i<pixels.length;i+=128)colors.add(pixels[i]+','+pixels[i+1]+','+pixels[i+2]);return{colors:colors.size,background:[...pixels.subarray(0,4)],error:gl.getError()};}
 dispose(){if(!this.active)return;this.active=false;this.observer.disconnect();this.canvas.removeEventListener('webglcontextlost',this.onLost);this.canvas.removeEventListener('webglcontextrestored',this.onRestored);this.orbit.removeEventListener('change',this.onOrbit);this.orbit.dispose();this.geometry.dispose();this.material.dispose();this.renderer.forceContextLoss();this.renderer.dispose();this.scene.clear();this.model=null;this.displayPositions=null;this.mesh=null;this.geometry=null;this.material=null;}
}
