import fs from 'node:fs';
import * as K from './r045_round63_kernel.mjs';
import * as R58 from '../round-58/r045_round58_kernel.mjs';
import * as R30 from '../round-30/r045_round30_kernel.mjs';
const checks=[];const add=(name,pass,value,limit)=>checks.push({name,pass:Boolean(pass),value,limit});
const rows=[];for(let z=-132;z<=12;z+=6){const row=[];for(let x=-222;x<=120;x+=6)row.push({x,z,n:K.terraceStateAt(x,z),p:R58.terraceStateAt(x,z),dd:R30.nearestExtendedDrainageDistance(x,z)});rows.push(row)}
const compat=(a,b)=>{if(a.groupIndex!==b.groupIndex)return false;const step=.5*(a.step+b.step);return Math.abs(a.step-b.step)<=Math.max(.22,.30*step)&&Math.abs(a.index-b.index)<=4};
function topo(key){const H=rows.length,W=rows[0].length,seen=Array.from({length:H},()=>Array(W).fill(false)),sizes=[],dirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];for(let j=0;j<H;j++)for(let i=0;i<W;i++){if(seen[j][i]||rows[j][i][key].mask<=.12)continue;seen[j][i]=true;const q=[[i,j]];let n=0;while(q.length){const[cx,cz]=q.pop(),a=rows[cz][cx][key];n++;for(const[di,dj]of dirs){const ni=cx+di,nj=cz+dj;if(ni<0||ni>=W||nj<0||nj>=H||seen[nj][ni])continue;const b=rows[nj][ni][key];if(b.mask<=.12||!compat(a,b))continue;seen[nj][ni]=true;q.push([ni,nj])}}sizes.push(n)}sizes.sort((a,b)=>b-a);return{components:sizes.length,orphans:sizes.filter(n=>n===1).length,tiny:sizes.filter(n=>n<=2).length,largest:sizes[0]||0,second:sizes[1]||0,sizes}}
function runs(key){const H=rows.length,W=rows[0].length,dirs=[[1,0],[0,1],[1,1],[1,-1]];let best=0,total=0,longRuns=0,longCells=0;for(const[di,dj]of dirs)for(let j=0;j<H;j++)for(let i=0;i<W;i++){const a=rows[j][i][key];if(a.mask<=.12)continue;const pi=i-di,pj=j-dj;if(pi>=0&&pi<W&&pj>=0&&pj<H){const p=rows[pj][pi][key];if(p.mask>.12&&compat(p,a))continue}let len=1,ci=i,cj=j,cur=a;while(true){const ni=ci+di,nj=cj+dj;if(ni<0||ni>=W||nj<0||nj>=H)break;const b=rows[nj][ni][key];if(b.mask<=.12||!compat(cur,b))break;len++;ci=ni;cj=nj;cur=b}best=Math.max(best,len);total+=len;if(len>=4){longRuns++;longCells+=len}}return{best,total,longRuns,longCells}}
function newCrossChains(){const H=rows.length,W=rows[0].length,mark=Array.from({length:H},()=>Array(W).fill(false)),seen=Array.from({length:H},()=>Array(W).fill(false)),sizes=[];for(let j=0;j<H;j++)for(let i=0;i<W;i++)mark[j][i]=rows[j][i].p.mask<=.12&&rows[j][i].n.mask>.12;const dirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];for(let j=0;j<H;j++)for(let i=0;i<W;i++){if(!mark[j][i]||seen[j][i])continue;seen[j][i]=true;const q=[[i,j]];let n=0;while(q.length){const[cx,cz]=q.pop(),a=rows[cz][cx].n;n++;for(const[di,dj]of dirs){const ni=cx+di,nj=cz+dj;if(ni<0||ni>=W||nj<0||nj>=H||seen[nj][ni]||!mark[nj][ni])continue;const b=rows[nj][ni].n;if(!compat(a,b))continue;seen[nj][ni]=true;q.push([ni,nj])}}sizes.push(n)}sizes.sort((a,b)=>b-a);return{components:sizes.length,largest:sizes[0]||0,chainCells:sizes.filter(n=>n>=2).reduce((a,b)=>a+b,0),multiCellComponents:sizes.filter(n=>n>=2).length,sizes}}
let active=0,priorActive=0,gains=0,cross=0,heightMaterial=0,unsupported=0,unsafe=0,oldMaskErr=0,oldDeltaErr=0,maxChange=0,groups=[0,0,0],changedGroups=new Set(),changedPts=[],extension=0,bracket=0,maxReach=0,maxCross=0;
for(const row of rows)for(const c of row){const{n,p,x,z,dd}=c,g=n.mask-p.mask,d=Math.abs(n.delta-p.delta);if(n.mask>.12){active++;if(n.groupIndex>=0&&n.groupIndex<3)groups[n.groupIndex]++}if(p.mask>.12){priorActive++;oldMaskErr=Math.max(oldMaskErr,Math.abs(n.mask-p.mask));oldDeltaErr=Math.max(oldDeltaErr,d)}if(g>.004){gains++;if(d>.004)heightMaterial++;const sup=n.frozenRailSupport;if(!sup)unsupported++;else{if(sup.sameSide)extension++;else bracket++;maxReach=Math.max(maxReach,sup.supportA?.dist||0,sup.supportB?.dist||0);maxCross=Math.max(maxCross,sup.supportA?.cross||0,sup.supportB?.cross||0);changedGroups.add(n.groupIndex)}if(dd<=12)unsafe++;const gap=Math.abs(z-R30.riverZ(x));if(gap<=R30.riverW(x)+12)unsafe++;changedPts.push({x,z,gain:g,change:n.delta-p.delta,groupIndex:n.groupIndex,mode:sup?.mode||null,supportA:sup?.supportA||null,supportB:sup?.supportB||null,dd})}if(p.mask<=.12&&n.mask>.12)cross++;maxChange=Math.max(maxChange,d)}
const tn=topo('n'),tp=topo('p'),rn=runs('n'),rp=runs('p'),nc=newCrossChains();let maxInc=0,maxIncAt=null;for(const p of changedPts){const c=K.terraceDelta(p.x,p.z);for(const[xx,zz]of[[p.x+3,p.z],[p.x-3,p.z],[p.x,p.z+3],[p.x,p.z-3]]){const inc=Math.abs(K.terraceDelta(xx,zz)-c);if(inc>maxInc){maxInc=inc;maxIncAt={x:p.x,z:p.z,xx,zz,inc}}}}
let outside=0,hard=0,receiver=0;for(let x=-216;x<=216;x+=36){for(const z of [-300,-220,-170,-145,30,70,130])outside=Math.max(outside,Math.abs(K.terraceDelta(x,z)));for(let z=-126;z<=6;z+=18)if(R30.nearestExtendedDrainageDistance(x,z)<=12)hard=Math.max(hard,Math.abs(K.terraceDelta(x,z)));const rz=R30.riverZ(x);for(const dz of [-8,0,8])receiver=Math.max(receiver,Math.abs(K.terraceDelta(x,rz+dz)))}
let xSpan=0,zSpan=0;if(changedPts.length){const xs=changedPts.map(p=>p.x),zs=changedPts.map(p=>p.z);xSpan=Math.max(...xs)-Math.min(...xs);zSpan=Math.max(...zs)-Math.min(...zs)}
add('version',K.VERSION==='R045.63',K.VERSION,'R045.63');
add('water_graph_identity',JSON.stringify(K.nodes)===JSON.stringify(R58.nodes)&&JSON.stringify(K.edges)===JSON.stringify(R58.edges),{nodes:K.nodes.length,edges:K.edges.length},'exact R58 inherited graph');
add('existing_r58_active_exact',oldMaskErr<1e-12&&oldDeltaErr<1e-12,{oldMaskErr,oldDeltaErr},'every R58 active 6m cell exact');
add('frozen_rail_material',K.frozenRailCount()>=500,K.frozenRailCount(),'>=500 accepted frozen R58 active rail samples');
add('material_continuation',gains>=8&&cross>=6&&active>=priorActive+6&&heightMaterial>=6,{gains,cross,active,priorActive,heightMaterial},'>=8 supported gains, >=6 threshold crossings, >=6 material height changes');
add('two_rail_support_material',extension+bracket===gains&&gains>=8,{extension,bracket,gains},'every gain has two frozen rails and >=8 total gains');
add('new_cross_chain_materiality',nc.largest>=2&&nc.chainCells>=4&&nc.multiCellComponents>=1,nc,'new promotions include coherent compatible chains; >=4 cells belong to multi-cell chains');
add('rail_geometry_bounded',gains===0||(maxReach<=33.0000001&&maxCross<=10.5000001),{maxReach,maxCross},'all supports <=33m reach and <=10.5m cross-contour');
add('multifamily_continuation',changedGroups.size>=2,[...changedGroups],'>=2 terrace families');
add('whole_slope_spatial_materiality',Math.max(xSpan,zSpan)>=48&&Math.min(xSpan,zSpan)>=12,{xSpan,zSpan},'promotions span >=48m one axis and >=12m other');
add('all_promotions_supported',unsupported===0,unsupported,'zero unsupported gains');
add('promotion_safety',unsafe===0,unsafe,'zero promoted cells in <=12m drainage or receiver +12m');
add('compatible_topology_not_worse',tn.components<=tp.components&&tn.orphans<=tp.orphans&&tn.tiny<=tp.tiny,{new:tn,prior:tp},'components/orphans/tiny non-increasing');
add('major_components_not_shrunk',tn.largest>=tp.largest&&tn.largest+tn.second>=tp.largest+tp.second,{new:[tn.largest,tn.second],prior:[tp.largest,tp.second]},'largest and top-two non-decreasing');
add('long_run_support_improves',rn.best>=rp.best&&rn.longCells>rp.longCells,{new:rn,prior:rp},'best nondecreasing and >=24m straight-run support cells increase');
add('height_change_bounded',maxChange>.004&&maxChange<.16,maxChange,'.004m < max R63-R58 delta < .16m');
add('three_meter_cliff_gate',maxInc<1.05,{maxInc,maxIncAt},'<1.05m terrace increment / 3m around every changed 6m cell');
add('hard_drainage_core_empty',hard<1e-9,hard,'0');
add('foreground_receiver_unchanged',receiver<1e-9,receiver,'0');
add('support_localized',outside<1e-9,outside,'0');
add('three_groups_retained',groups.every(v=>v>20),groups,'three terrace families material');
add('locks_retained',K.snapshot.visualAcceptance===false&&K.snapshot.parcelGenerationEnabled===false&&K.snapshot.waterStateKnown===false&&K.snapshot.productionReady===false,{visual:K.snapshot.visualAcceptance,parcel:K.snapshot.parcelGenerationEnabled,water:K.snapshot.waterStateKnown,production:K.snapshot.productionReady},'all false pending fixed-view acceptance');
add('logic_error_explicit',K.snapshot.round63?.logicCorrection?.includes('threshold chasing')&&K.snapshot.round63?.logicCorrection?.includes('renderability evidence'),K.snapshot.round63?.logicCorrection,'four seeds insufficient; browser != geometry');
add('field_constraint_explicit',K.snapshot.round63?.constraint?.includes('synthetic morphology/QA parameters')&&K.snapshot.round63?.constraint?.includes('cannot provide'),K.snapshot.round63?.constraint,'synthetic parameters and missing field truth explicit');
add('xiaoma_boundary_retained',K.snapshot.round63?.xiaomaBoundary?.includes('do not establish'),K.snapshot.round63?.xiaomaBoundary,'geometry != hydraulic truth');
add('mrrolord_ordering_only',K.snapshot.round63?.mrRolordUse?.includes('ordering discipline')&&K.snapshot.round63?.mrRolordUse?.includes('not agricultural truth'),K.snapshot.round63?.mrRolordUse,'ordering only');
add('reference_nonmetric',K.snapshot.round63?.referenceUse?.includes('non-metric')&&K.snapshot.round63?.referenceUse?.includes('No terrace width'),K.snapshot.round63?.referenceUse,'nonmetric only');
const result={version:K.VERSION,passed:checks.every(c=>c.pass),gateCount:checks.length,passedCount:checks.filter(c=>c.pass).length,checks,metrics:{active,priorActive,gains,cross,heightMaterial,unsupported,unsafe,maxChange,groups,changedGroups:[...changedGroups],supportModes:{extension,bracket},frozenRailCount:K.frozenRailCount(),changedPoints:changedPts,spatialSpan:{xSpan,zSpan},newCrossChains:nc,topology2D:{new:tn,prior:tp},straightRuns:{new:rn,prior:rp},maxReach,maxCross,maxInc,maxIncAt,outside,hard,receiver,qaScope:'authoritative 6m whole-slope frozen-R58 two-rail sweep + explicit new-chain gate + exact old-active inheritance + 2D topology/long-run guards + <=3m path/local safety checks'}};
fs.writeFileSync(new URL('./r045_round63_qa_result.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.passed)process.exitCode=2;
