(function(){'use strict';const C=AnemoneCore,el=id=>document.getElementById(id);let renderer=null,active='anemone',running=false,last=0,time=0,requestedRabbit=false;const errors=[];let failed=false;
const descriptors=[['count','触手数量',120,560,20,'Shape'],['length','相对触手长度',.35,1.05,.01,'Shape'],['thickness','触手半径',.015,.045,.001,'Shape'],['curvature','静态弯曲',.5,2.1,.05,'Shape'],['seed','固定种子',1,9999,1,'Shape'],['current','水流强度',0,1,.01,'Flow'],['direction','水流方向',-180,180,1,'Flow'],['frequency','水流节奏',.08,.9,.01,'Flow'],['turbulence','局部噪声',0,.8,.01,'Flow']];
const DEFAULTS=Object.freeze({...C.DEFAULTS,count:240});
let params={...DEFAULTS};
let material={palette:"green",translucency:.70,mode:"kuko"};
function materialUI(){document.querySelectorAll("[data-cluster-color]").forEach(b=>b.classList.toggle("active",material.palette===b.dataset.clusterColor&&material.mode==="kuko"));el("clusterBaseline").classList.toggle("active",material.mode==="baseline");}
function setMaterial(values){const next=AnemoneRenderer.validateMaterial({...material,...values});material=next;if(renderer)renderer.setMaterial(next);materialUI();draw();}

function error(message){failed=true;el('anemoneCapture').disabled=true;errors.push(String(message));el('anemoneError').hidden=false;el('anemoneError').textContent=message;el('anemoneStatus').textContent='3D 启动或运行异常';}
function ui(){for(const [k]of descriptors){el('anemone-'+k).value=params[k];el('anemone-number-'+k).value=params[k];}el('anemonePause').textContent=params.paused?'▶ 继续水流':'Ⅱ 暂停水流';el('anemonePause').classList.toggle('active',params.paused);}
function draw(){if(!renderer||active!=='anemone'||failed)return;renderer.draw(time);if(failed)return;el('anemoneStats').textContent=renderer.roots.length+' TENTACLES · '+Math.round((renderer.tubeCount/3*renderer.roots.length+renderer.bodyCount/3)/1000)+'K TRIANGLES';el('anemoneStatus').textContent=params.paused?'WebGL 2 · 已暂停':'WebGL 2 · 实时水流';}
function tick(now){running=false;if(active!=='anemone'||!renderer||failed)return;if(!params.paused){if(last)time+=Math.min(.05,(now-last)/1000);last=now;draw();schedule();}else last=0;}
function schedule(){if(!running&&active==='anemone'&&renderer&&!params.paused&&!failed){running=true;requestAnimationFrame(tick);}}
function set(values){const next=C.validate({...params,...values});const rebuild=['count','length','thickness','curvature','seed'].some(k=>next[k]!==params[k]);params=next;if(renderer){if(rebuild){renderer.reset(params);time=0;}else renderer.state={...params};}ui();draw();last=0;schedule();}
function initialize(){if(renderer||failed)return;try{renderer=new AnemoneRenderer(el('anemoneCanvas'));renderer.onError=error;el('anemoneCapture').disabled=false;renderer.reset(params);renderer.setMaterial(material);draw();schedule();}catch(e){error(e.message);}}
function rabbitActive(on){if(!on&&(!window.workbench?.ready.teacher||!workbench.ready.candidate||(workbench.frameStats.teacher?.frames||0)<2||(workbench.frameStats.candidate?.frames||0)<2))return;for(const role of ['teacher','candidate']){const w=el(role+'Frame').contentWindow;if(w)w.postMessage({kaopu:true,type:'active',active:on&&(role!=='teacher'||!el('viewports').classList.contains('single'))},'*');}}
function select(module){if(!['rabbit','anemone'].includes(module))throw Error('Unknown module');active=module;if(module!=='anemone')clearPointers();requestedRabbit=module==='rabbit';document.body.dataset.module=module;el('speciesRabbit').classList.toggle('active',module==='rabbit');el('speciesAnemone').classList.toggle('active',module==='anemone');rabbitActive(module==='rabbit');last=0;if(module==='anemone'){initialize();draw();schedule();}else{for(const role of ['teacher','candidate'])el(role+'Frame').contentWindow.postMessage({kaopu:true,type:'resize'},'*');}}
for(const [key,label,min,max,step,group]of descriptors){const div=document.createElement('div');div.className='control';div.innerHTML=`<label for="anemone-${key}"><span>${label}</span><input type="number" aria-label="海葵${label}数值" id="anemone-number-${key}" min="${min}" max="${max}" step="${step}"></label><input type="range" aria-label="海葵${label}" id="anemone-${key}" min="${min}" max="${max}" step="${step}">`;el('anemone'+group+'Controls').append(div);for(const id of ['anemone-'+key,'anemone-number-'+key])el(id).addEventListener(id.includes('number')?'change':'input',event=>{const v=Number(event.target.value);if(!Number.isFinite(v))return ui();set({[key]:Number(C.clamp(Math.round(v/step)*step,min,max).toFixed(4))});});}
el('speciesRabbit').onclick=()=>select('rabbit');el('speciesAnemone').onclick=()=>select('anemone');el('anemonePause').onclick=()=>set({paused:!params.paused});el('anemoneResetTime').onclick=()=>{time=0;last=0;draw();};
function resetCamera(){clearPointers();if(renderer)renderer.camera={azimuth:.25,elevation:.84,distance:4.6};draw();}
el('anemoneCamera').onclick=resetCamera;el('anemoneReset').onclick=()=>{params={...DEFAULTS};material={palette:"green",translucency:.70,mode:"kuko"};renderer?.setMaterial(material);materialUI();time=0;last=0;renderer?.reset(params);resetCamera();ui();draw();schedule();};
function snapshot(){return {format:'kaopu-anemone-study',version:2,reference:'Wootton-Heteractis-magnifica-macro',material:{...material},params:{...params},time,camera:renderer?{...renderer.camera}:{azimuth:.25,elevation:.84,distance:4.6}};}
function importState(data){if(data?.format!=='kaopu-anemone-study'||![1,2].includes(data.version))throw Error('请选择海葵工作台参数文件');const p=C.validate(data.params);if(!Number.isFinite(data.time)||data.time<0||data.time>1e6)throw Error('时间无效');const c=data.camera;if(!c||!Number.isFinite(c.azimuth)||Math.abs(c.azimuth)>1e4||!Number.isFinite(c.elevation)||c.elevation<.15||c.elevation>1.5||!Number.isFinite(c.distance)||c.distance<2||c.distance>8)throw Error('相机无效');const m=AnemoneRenderer.validateMaterial(data.version===2?data.material:{palette:'green',translucency:.70,mode:'kuko'});params=p;material=m;time=data.time;last=0;initialize();renderer.setMaterial(material);renderer.reset(params);materialUI();renderer.camera={...c};ui();draw();schedule();window.dispatchEvent(new Event('anemonestate'));}
function save(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
el('anemoneExport').onclick=()=>save(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),'KAOPU-海葵参数.json');el('anemoneImport').onclick=()=>el('anemoneImportFile').click();el('anemoneImportFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000)throw Error('参数文件过大');importState(JSON.parse(await f.text()));el('anemoneMessage').textContent='海葵参数与时间已恢复';}catch(error){el('anemoneMessage').textContent=error.message;}e.target.value='';};el('anemoneCapture').disabled=true;el('anemoneCapture').onclick=()=>{if(!renderer||failed||!renderer.frames)return;draw();if(failed)return;el('anemoneCanvas').toBlob(b=>{if(b)save(b,'KAOPU-海葵视图.png');});};
const pointers=new Map();const canvas=el('anemoneCanvas');let gesture=null;
function rebaseGesture(){const p=[...pointers.values()];gesture=p.length>=2?{distance:Math.max(1,Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)),cameraDistance:renderer.camera.distance}:null;}
function clearPointers(){pointers.clear();gesture=null;}
canvas.addEventListener('pointerdown',e=>{if(!renderer||failed||e.button>0)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);rebaseGesture();});
canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old||!renderer)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){renderer.camera.azimuth-=(e.clientX-old.x)*.008;renderer.camera.elevation=C.clamp(renderer.camera.elevation+(e.clientY-old.y)*.006,.15,1.5);}else{const p=[...pointers.values()],d=Math.max(1,Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y));if(gesture)renderer.camera.distance=C.clamp(gesture.cameraDistance*gesture.distance/d,2,8);}draw();window.dispatchEvent(new Event('anemonecamera'));});
for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{pointers.delete(e.pointerId);if(renderer)rebaseGesture();});
window.addEventListener('blur',clearPointers);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearPointers();});
canvas.addEventListener('wheel',e=>{if(!renderer)return;e.preventDefault();renderer.camera.distance=C.clamp(renderer.camera.distance+e.deltaY*.004,2,8);draw();window.dispatchEvent(new Event('anemonecamera'));},{passive:false});new ResizeObserver(()=>draw()).observe(canvas);
window.visualViewport?.addEventListener('resize',()=>draw());window.addEventListener('resize',()=>draw());
window.addEventListener('message',e=>{if(!e.data?.kaopu||!['ready','frame'].includes(e.data.type))return;if(!requestedRabbit&&window.workbench.ready.teacher&&window.workbench.ready.candidate&&window.workbench.frameStats.teacher?.frames>=2&&window.workbench.frameStats.candidate?.frames>=2)rabbitActive(false);});
window.platform={select,get module(){return active;},get errors(){return errors;}};window.anemone={get ready(){return !!renderer;},get renderer(){return renderer;},get state(){return snapshot();},set,setMaterial,get material(){return {...material}},reset:()=>el('anemoneReset').click(),importState,exportState:snapshot,pause:()=>set({paused:true}),seek:t=>{if(!Number.isFinite(t)||t<0||t>1e6)throw Error('Time out of range');time=t;last=0;draw();},redraw:draw,get pointerCount(){return pointers.size},clearPointers,metrics:()=>renderer?.metrics(),pixels:()=>renderer?.pixels(),get errors(){return errors.concat(renderer?.errors||[]);}};
document.querySelectorAll('[data-cluster-color]').forEach(b=>b.onclick=()=>setMaterial({palette:b.dataset.clusterColor,mode:'kuko'}));el('clusterBaseline').onclick=()=>setMaterial({mode:material.mode==='baseline'?'kuko':'baseline'});el('clusterMacro').onclick=()=>{renderer.camera={azimuth:.25,elevation:.84,distance:2.25};draw();};
materialUI();ui();select('anemone');
})();

