/* Original accelerated implementation of the existing garment equations.
 * Float64 storage, unchanged substeps/iteration order/rest material/contact sites.
 */
import {BodySDF,GarmentLab as ReferenceGarmentLab} from './reference-optimized.mjs';
export {BodySDF};
let module;
export function configureWasm(bytes){module=new WebAssembly.Module(bytes);return {bytes:bytes.byteLength};}
export class GarmentLab extends ReferenceGarmentLab{
 constructor(spec,sdf,options={}){super(spec,sdf,options);if(!module)throw Error('Fast kernel must be initialized before constructing cloth');this.kernel=new WebAssembly.Instance(module,{math:{atan2:Math.atan2,cos:Math.cos,sin:Math.sin}}).exports;this.profile={distanceMs:0,strainMs:0,bodyVertexMs:0,bodySurfaceMs:0,integrateAndGroupsMs:0};const n=this.positions.length,t=this.strainTriangles.length,e=this.meshEdges.length,capacity=this.constraints.length+spec.seams.reduce((s,x)=>s+spec.panels.find(p=>p.id===x.a.panelId).edges[x.a.edge].length,0)+16;this.capacity=capacity;let offset=65536;const take=(count,bytes=8)=>{offset=Math.ceil(offset/8)*8;const p=offset;offset+=count*bytes;return p;};this.ptr={pos:take(n*3),vel:take(n*3),old:take(n*3),inv:take(n),alias:take(n,4),ci:take(capacity*2,4),cf:take(capacity*10),ti:take(t*3,4),tf:take(t*6),edges:take(e*2,4),sdf:take(sdf.a.length,2)};if(offset>128*1024*1024)throw Error('Kernel material memory limit exceeded');const memory=this.kernel.memory;memory.grow(Math.ceil(offset/65536)-memory.buffer.byteLength/65536);const b=memory.buffer,p=this.ptr;this.posViews=Array.from({length:n},(_,i)=>new Float64Array(b,p.pos+i*24,3));this.velViews=Array.from({length:n},(_,i)=>new Float64Array(b,p.vel+i*24,3));this.weights=new Float64Array(b,p.inv,n);this.alias=new Int32Array(b,p.alias,n);this.ci=new Int32Array(b,p.ci,capacity*2);this.cf=new Float64Array(b,p.cf,capacity*10);this._old=new Float64Array(b,p.old,n*3);const tids=new Int32Array(b,p.ti,t*3),coefs=new Float64Array(b,p.tf,t*6),edgeIds=new Int32Array(b,p.edges,e*2),field=new Int16Array(b,p.sdf,sdf.a.length);field.set(sdf.a);sdf.a=field;for(let i=0;i<t;i++){tids.set(this.strainTriangles[i].ids,i*3);coefs.set([...this.strainTriangles[i].c,...this.strainTriangles[i].d],i*6);}for(let i=0;i<e;i++)edgeIds.set(this.meshEdges[i],i*2);const m=sdf.meta;this.kernel.configure(p.pos,p.inv,p.alias,p.ci,p.cf,p.ti,p.tf,p.edges,p.sdf,n,0,t,e,...m.dimensions,...m.originMm,m.spacingMm,m.quantizationMm);this.packGroups();this.wrapRebuild();this.syncConstraints();}
 wrapRebuild(){const rebuild=this.stitchGroups.rebuild.bind(this.stitchGroups);this.stitchGroups.rebuild=()=>{rebuild();this.packGroups();};}
 packGroups(){const positions=this.positions,velocity=this.velocity,weights=this.invMass;for(let i=0;i<positions.length;i++){const r=this.stitchGroups.find(i);this.alias[i]=r;this.posViews[r].set(positions[i]);this.velViews[r].set(velocity[i]);this.weights[i]=weights[i];}for(let i=0;i<positions.length;i++){positions[i]=this.posViews[this.alias[i]];velocity[i]=this.velViews[this.alias[i]];}this.invMass=this.weights;}
 syncConstraints(){const all=[...this.constraints,...this.seamConstraints];if(all.length>this.capacity)throw Error('Constraint capacity exceeded');for(let i=0;i<all.length;i++){const c=all[i];this.ci[i*2]=c.a;this.ci[i*2+1]=c.b;this.cf.set([c.rest,c.compliance,c.startRest||0,c.activatedAt||0,c.rampDuration||1,0,c.eliminated?1:0,c.type==='seam'?1:0,0,0],i*10);}this.count=all.length;this.kernel.setConstraintCount(all.length);}
 activate(stageId,current=this.spec){super.activate(stageId,current);if(this.kernel)this.syncConstraints();}
 releasePins(){super.releasePins();if(!this.stitchEqualityElimination)this.packGroups();}
 detach(){super.detach();this.wrapRebuild();this.packGroups();this.syncConstraints();}
 step(dt=1/60){if(this.orientationGuides||this.selfCollisionEnabled)return super.step(dt);this.frameCount++;const n=this.positions.length,h=dt/this.substeps,ps=this.positions,vs=this.velocity,im=this.invMass,old=this._old,k=this.kernel,P=this.profile,baseCount=this.constraints.length;this.bodyContacts=0;
  for(let sub=0;sub<this.substeps;sub++){let now=performance.now();this.elapsed+=h;this.seamElapsed+=h;if(this.stitchEqualityElimination)this.stitchGroups.synchronize();for(let j=0;j<this.seamConstraints.length;j++)this.cf[(baseCount+j)*10+6]=this.seamConstraints[j].eliminated?1:0;
   for(const hold of this.support){const p=ps[hold.id],t=Math.min(1,this.elapsed/4),s=t*t*(3-2*t);for(let axis=0;axis<3;axis++)p[axis]=hold.start[axis]+(hold.target[axis]-hold.start[axis])*s;}
   for(let i=0;i<n;i++){const p=ps[i],o=i*3;old[o]=p[0];old[o+1]=p[1];old[o+2]=p[2];}
   for(let i=0;i<n;i++){if(this.stitchEqualityElimination&&this.alias[i]!==i)continue;const p=ps[i],v=vs[i];if(!im[i])continue;v[1]-=9.81*this.gravityScale*h;p[0]+=v[0]*h;p[1]+=v[1]*h;p[2]+=v[2]*h;}k.prepare(h,this.elapsed);P.integrateAndGroupsMs+=performance.now()-now;
   for(let iter=0;iter<this.iterations;iter++){now=performance.now();k.distances(0,this.count);P.distanceMs+=performance.now()-now;if(this.strainGuard){now=performance.now();k.strains();P.strainMs+=performance.now()-now;}if(this.collisions){now=performance.now();k.vertices(this.clearance);P.bodyVertexMs+=performance.now()-now;}}
   now=performance.now();k.distances(baseCount,this.count);P.distanceMs+=performance.now()-now;if(this.collisions&&sub%3===2){now=performance.now();k.surfaces();P.bodySurfaceMs+=performance.now()-now;}this.bodyContacts+=k.contacts.value;now=performance.now();
   const damping=Math.exp(-20*h);for(let i=0;i<n;i++){if(this.stitchEqualityElimination&&this.alias[i]!==i)continue;const p=ps[i],v=vs[i],o=i*3;v[0]=(p[0]-old[o])/h*damping;v[1]=(p[1]-old[o+1])/h*damping;v[2]=(p[2]-old[o+2])/h*damping;if(p[1]<0){p[1]=0;v[1]=0;}}P.integrateAndGroupsMs+=performance.now()-now;
  }
 }
 export(){const record=super.export();record.positionsMm=this.positions.map(p=>Array.from(p,x=>x*1000));record.solver.execution={backend:'original-f64-wasm-kernels',reducedIterations:false,reducedSubsteps:false,originalConstraintOrder:true};return record;}
}
