const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const URL='https://haihao0307.github.io/guilin-dem-pipeline/kaopu-unified-human-workbench/skin-r01/';
const OUT='/tmp/common-skin-pages';fs.mkdirSync(OUT,{recursive:true});let b,p;
const report={url:URL,scope:'Actual public GitHub Pages, desktop Chromium; not phone hardware',checks:[],errors:[],failedRequests:[]};
function check(name,value){report.checks.push({name,pass:!!value});assert.ok(value,name);}
async function fingerprint(){return p.evaluate(async()=>{const h=async a=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',a))].map(v=>v.toString(16).padStart(2,'0')).join('');return{p:await h(fullCommonWorkbench.positions()),i:await h(fullCommonWorkbench.faces()),a:JSON.stringify(fullCommonWorkbench.archive())};});}
(async()=>{
 b=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});p=await b.newPage({viewport:{width:1440,height:1040}});
 p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))report.errors.push(m.text());});p.on('requestfailed',r=>report.failedRequests.push({url:r.url(),reason:r.failure()?.errorText}));
 await p.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});await p.waitForFunction(()=>window.fullCommonWorkbench,null,{timeout:90000});await p.click('#load-model');await p.waitForFunction(()=>window.commonSkin?.report().ready,null,{timeout:180000});
 check('correct published material version',await p.evaluate(()=>commonSkin.version==='unified-human-skin/r01.1'));check('same 25417 vertex common body',await p.evaluate(()=>fullCommonWorkbench.diagnostics().vertices===25417));check('single canvas',await p.locator('canvas').count()===1);
 const before=await fingerprint();await p.evaluate(()=>fullCommonWorkbench.view('face'));await p.screenshot({path:OUT+'/skin-face.png'});await p.click('[data-skin-mode="white"]');await p.screenshot({path:OUT+'/original-white.png'});check('white toggle preserves geometry and archive',JSON.stringify(before)===JSON.stringify(await fingerprint()));await p.click('[data-skin-mode="skin"]');check('skin toggle preserves geometry and archive',JSON.stringify(before)===JSON.stringify(await fingerprint()));
 await p.click('#skin-panel summary');check('uncertain transmission explicitly disabled',await p.locator('#skin-translucency').isDisabled());await p.locator('#skin-oil').evaluate(e=>{e.value=.45;e.dispatchEvent(new Event('input',{bubbles:true}));});check('material slider active',await p.evaluate(()=>commonSkin.report().settings.oil===.45));await p.click('#skin-reset');await p.click('#skin-panel summary');
 await p.evaluate(()=>{fullCommonWorkbench.set('anny.phenotypes:height',.62);fullCommonWorkbench.set('gnm.rotation:4',.22);});await p.screenshot({path:OUT+'/shape-and-head-pose.png'});check('original three-teacher controls survive',await p.evaluate(()=>fullCommonWorkbench.diagnostics().fixedPositionBuffer&&fullCommonWorkbench.diagnostics().fixedIndexBuffer));
 await p.evaluate(a=>fullCommonWorkbench.restore(JSON.parse(a)),before.a);await p.evaluate(()=>fullCommonWorkbench.view('three'));await p.screenshot({path:OUT+'/skin-whole-body.png'});check('restore returns identical body data',JSON.stringify(before)===JSON.stringify(await fingerprint()));
 await p.setViewportSize({width:1280,height:800});await p.evaluate(()=>fullCommonWorkbench.view('face'));await p.screenshot({path:OUT+'/desktop-1280.png'});
 report.skin=await p.evaluate(()=>commonSkin.report());report.pixels=await p.evaluate(()=>fullCommonWorkbench.pixelAudit());check('actual WebGL pixels',report.pixels.colors>100&&report.pixels.error===0);check('no script or shader errors',report.errors.length===0);check('no failed public assets',report.failedRequests.length===0);report.success=true;
})().catch(e=>{report.success=false;report.failure=e.stack;process.exitCode=1;console.error(e);}).finally(async()=>{if(p)try{await p.screenshot({path:OUT+'/last-state.png'});}catch{}fs.writeFileSync(OUT+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({success:report.success,checks:report.checks,failure:report.failure,errors:report.errors}));await b?.close();});
