import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{gunzipSync}from'node:zlib';import{prepareNativeSource}from'./source-repair-r043.mjs';import{buildOutfits,verifyOutfitMembers}from'./outfits-r043.mjs';import{samePerson,sha,materialHash}from'./source-contract.mjs';import{attachExteriorField}from'./correctives/r043/fit-support.mjs';
const P=path.dirname(fileURLToPath(import.meta.url)),read=n=>JSON.parse(fs.readFileSync(P+'/'+n)),rows=read('assets/catalogue.json').rows,checks=[];
function check(name,v,detail=null){checks.push({name,passed:!!v,detail});if(!v)throw Error(name+' '+JSON.stringify(detail));}
const world=(p,v)=>p.placement.translationMm.map((t,k)=>t+p.placement.matrix3[k][0]*v[0]+p.placement.matrix3[k][1]*v[1]);
for(const r of rows){const bytes=fs.readFileSync(P+'/'+r.nativePaper),d=JSON.parse(gunzipSync(bytes)),before=JSON.stringify(d),n=prepareNativeSource(d);check('immutable original paper '+r.id,await sha(bytes)===r.compressedSHA256&&before===JSON.stringify(d));check('same source panel IDs and sewing interfaces '+r.id,JSON.stringify(n.panels.map(p=>p.id))===JSON.stringify(d.panels.map(p=>p.id))&&JSON.stringify(n.seams.map(s=>[s.id,s.a,s.b]))===JSON.stringify(d.seams.map(s=>[s.id,s.a,s.b])));
 let error=0;for(let i=0;i<d.panels.length;i++){const a=d.panels[i],b=n.panels[i];for(let j=0;j<a.verticesMm.length;j++){const A=world(a,a.verticesMm[j]),B=world(b,b.verticesMm[j]);error=Math.max(error,...A.map((v,k)=>Math.abs(v-B[k])));}}check('source cutting geometry world positions preserved '+r.id,error<1e-8,error);
}
for(const id of['S11','S12','D08']){const r=rows.find(r=>r.id===id),d=prepareNativeSource(JSON.parse(gunzipSync(fs.readFileSync(P+'/'+r.nativePaper))));check('declared tier gathering recovered '+id,d.source.r043SourceRepair.tierRows.length>0);}
const person=read('assets/identity.json').person;check('exact person comparison refuses one changed hash',!samePerson({...person,stateSHA256:'0'.repeat(64)},person));const outfits=buildOutfits(rows);check('432 two-source outfit identities',outfits.length===432&&new Set(outfits.map(r=>r.id)).size===432);
const index=read('assets/results/index.json'),packets=['T01','P01'].map(id=>JSON.parse(gunzipSync(fs.readFileSync(P+'/assets/results/'+index.rows[id].file))));check('native outfit source binding',!!(await verifyOutfitMembers(packets,person)).sameOriginalPerson);let rejected=false;try{await verifyOutfitMembers([{...packets[0],binding:{...packets[0].binding,person:{...person,stateSHA256:'f'.repeat(64)}}},packets[1]],person)}catch{rejected=true}check('wrong-person outfit refused',rejected);
const fake={meta:{originMm:[-200,-200,-200],dimensions:[5,5,5],spacingMm:100},sample(x,y,z,o){o[0]=999;o[4]=x>=-.2&&x<.2&&y>=-.2&&y<.2&&z>=-.2&&z<.2?1:0;return o;}};attachExteriorField(fake,{positionsMm:[[-10,-20,-30],[10,20,30]]});const q=new Float64Array(5);fake.sample(.5,0,0,q);check('outside field is conservative positive body bound',Math.abs(q[0]-.49)<1e-10&&q[4]===1);fake.sample(0,0,0,q);check('inside field sampling unchanged',q[0]===999);
const audit=read('PARAMETER_AUDIT_R043.json');check('all 122 controls have actual geometric perturbation evidence',audit.verifiedParameters===122&&audit.rows.length===122&&audit.rows.every(r=>r.example?.beforeGeometrySHA256!==r.example?.afterGeometrySHA256));check('conditional controls are not labelled always active',audit.allParametersAlwaysActive===false&&audit.conditionalParameters>0);
fs.writeFileSync(P+'/SOURCE_TESTS_R043.json',JSON.stringify({passed:checks.every(c=>c.passed),checks,allSourcePapersImmutable:true,qualityThresholdsChanged:false,physicalCalibration:false},null,2));console.log('SOURCE_TESTS',checks.length);
