import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const source=read('src/learning.js'),data=JSON.parse(read('src/learning-teachers.json')),html=read('index.html');
const js=source.replace("import TEACHERS_DATA from './learning-teachers.json';",'const TEACHERS_DATA='+JSON.stringify(data)+';').replaceAll('export function ','function ').replaceAll('export const ','const ');
const context=vm.createContext({console});
new vm.Script(js+'\n globalThis.testing={inspectObj,validateObservation,homeMarkup,teacherMarkup,overviewMarkup,toolMarkup,motionSection,workflowMarkup};').runInContext(context);
const {inspectObj,validateObservation,homeMarkup,teacherMarkup,overviewMarkup,toolMarkup,motionSection,workflowMarkup}=context.testing;
const checks=[];
function check(name,fn){fn();checks.push({name,status:'passed'});}
const triangle='v 0 0 0\nv 2 0 0\nv 0 3 1\nf 1 2 3\n';
check('triangle vertex and face counts',()=>{const r=inspectObj(triangle);assert.equal(r.vertices,3);assert.equal(r.faces,1);assert.equal(r.trianglesAfterFan,1);});
check('exact finite bounds',()=>{const r=inspectObj(triangle);assert.equal(JSON.stringify(r.bounds.extent),'[2,3,1]');assert.equal(r.bounds.units,'source_unspecified');});
check('negative relative face indices',()=>assert.equal(inspectObj(triangle.replace('f 1 2 3','f -3 -2 -1')).faces,1));
check('UV and normal triplets',()=>{const r=inspectObj(triangle.replace('f 1 2 3','vt 0 0\nvt 1 0\nvt 0 1\nvn 0 0 1\nf 1/1/1 2/2/1 3/3/1'));assert.equal(r.uvCoordinates,3);assert.equal(r.normals,1);});
check('omitted UV is allowed',()=>assert.equal(inspectObj(triangle.replace('f 1 2 3','vn 0 0 1\nf 1//1 2//1 3//1')).normals,1));
check('quadrilateral fan count is declared',()=>assert.equal(inspectObj('v 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4').trianglesAfterFan,2));
check('invalid positive vertex index rejected',()=>assert.throws(()=>inspectObj(triangle.replace('f 1 2 3','f 1 2 4')),/越界/));
check('invalid negative index rejected',()=>assert.throws(()=>inspectObj(triangle.replace('f 1 2 3','f -4 -2 -1')),/越界/));
check('zero index rejected',()=>assert.throws(()=>inspectObj(triangle.replace('f 1 2 3','f 0 2 3')),/越界/));
check('fractional index rejected',()=>assert.throws(()=>inspectObj(triangle.replace('f 1 2 3','f 1.5 2 3')),/整数/));
check('NaN coordinate rejected',()=>assert.throws(()=>inspectObj(triangle.replace('v 0 0 0','v NaN 0 0')),/顶点无效/));
check('Infinity coordinate rejected',()=>assert.throws(()=>inspectObj(triangle.replace('v 0 0 0','v Infinity 0 0')),/顶点无效/));
check('non-unit homogeneous coordinates rejected',()=>assert.throws(()=>inspectObj(triangle.replace('v 0 0 0','v 0 0 0 2')),/齐次/));
check('invalid UV index rejected',()=>assert.throws(()=>inspectObj(triangle.replace('f 1 2 3','f 1/1 2/1 3/1')),/越界/));
check('empty mesh rejected',()=>assert.throws(()=>inspectObj('v 0 0 0'),/没有可检查/));
check('degenerate repeated face warned',()=>assert.equal(inspectObj(triangle.replace('f 1 2 3','f 1 1 2')).issues.length,1));
check('external MTL is never read',()=>assert.match(inspectObj('mtllib remote.mtl\n'+triangle).issues[0],/不加载外部/));
check('all unchecked categories declared',()=>assert.equal(inspectObj(triangle).notChecked.length,5));
const observation={schema:'kaopu/manual-animal-observation@1',origin:'manual_annotation',image:{width:200,height:100},points:[{label:'左前足',x:42.3,y:70,visibility:'visible'}]};
const clone=()=>JSON.parse(JSON.stringify(observation));
check('valid manual observation accepted',()=>assert.equal(validateObservation(clone()).points.length,1));
check('machine origin cannot masquerade as manual',()=>{const r=clone();r.origin='model_inference';assert.throws(()=>validateObservation(r),/manual_annotation/);});
check('out-of-bounds points rejected',()=>{const r=clone();r.points[0].x=201;assert.throws(()=>validateObservation(r),/边界/);});
check('negative points rejected',()=>{const r=clone();r.points[0].y=-1;assert.throws(()=>validateObservation(r),/边界/);});
check('nonfinite points rejected',()=>{const r=clone();r.points[0].x=NaN;assert.throws(()=>validateObservation(r),/边界/);});
check('hidden points cannot be invented',()=>{const r=clone();r.points[0].visibility='inferred';assert.throws(()=>validateObservation(r),/不补猜/);});
check('duplicate anatomical labels rejected',()=>{const r=clone();r.points.push({...r.points[0]});assert.throws(()=>validateObservation(r),/重复/);});
check('oversized label rejected',()=>{const r=clone();r.points[0].label='x'.repeat(61);assert.throws(()=>validateObservation(r),/1–60/);});
check('invalid image dimensions rejected',()=>{const r=clone();r.image.width=0;assert.throws(()=>validateObservation(r),/图片尺寸/);});
check('three named teachers only',()=>assert.equal(data.teachers.map(t=>t.name).join(','),'RAPID,4DEquine,AnimalLift'));
check('teacher IDs unique',()=>assert.equal(new Set(data.teachers.map(t=>t.id)).size,3));
check('all source links HTTPS',()=>data.teachers.forEach(t=>t.links.forEach(l=>assert.equal(new URL(l.url).protocol,'https:'))));
check('five observation layers preserved',()=>assert.equal(data.observationLayers.length,5));
check('all model execution flags remain false',()=>{assert.equal(data.status.weightsDownloaded,false);assert.equal(data.status.inferenceExecuted,false);assert.equal(data.status.resultReproduced,false);});
check('4DEquine and AnimalLift paper identities distinct',()=>{assert(data.teachers[1].links.some(x=>x.url.includes('2603.10125')));assert(data.teachers[2].links.some(x=>x.url.includes('2609.09513')));});
check('4DEquine license and implementation boundary visible',()=>{const t=teacherMarkup(data.teachers[1]);assert.match(t,/BSL-1.1/);assert.match(t,/sam3/);assert.match(t,/2030-12-01/);});
check('AnimalLift implementation and license boundary visible',()=>{const t=teacherMarkup(data.teachers[2]);assert.match(t,/8×64×64/);assert.match(t,/4×128×128/);assert.match(t,/未发现 LICENSE/);});
check('SIFT feature points distinguished from anatomy',()=>assert.match(teacherMarkup(data.teachers[0]),/SIFT 的 keypoints 是花纹特征点/));
check('method diagrams explicitly marked',()=>assert.equal((homeMarkup().match(/自绘方法示意 · 非模型输出/g)||[]).length,3));
check('all card details state not run',()=>data.teachers.forEach(t=>assert.match(teacherMarkup(t),/推理未运行/)));
check('old overview preserves eight public destinations',()=>{const links=data.existingOverview.entries.filter(e=>e.url);assert.equal(links.length,8);assert(links.some(x=>x.url.endsWith('shorts-original-r5/')));assert(links.some(x=>x.url.endsWith('shorts-v9-4-directed-20261003/')));});
check('unpublished old entries have no fabricated href',()=>assert.equal((overviewMarkup().match(/暂无核实网页入口/g)||[]).length,8));
check('private Palau URL not published',()=>{assert.match(overviewMarkup(),/私有工作台/);assert(!JSON.stringify(data).includes('.chatgpt.site'));});
check('old overview quality is not promoted',()=>{assert.equal(data.existingOverview.qualityRechecked,false);assert.match(overviewMarkup(),/尚未在本轮重新验收/);});
check('same-tab sources only',()=>{assert(!source.includes('target="_blank"'));assert(source.includes('target="_self"'));});
check('manual tool is visibly labeled',()=>assert.match(toolMarkup('annotate'),/人工标注，不是模型识别/));
check('OBJ inspector scope visibly limited',()=>assert.match(toolMarkup('obj'),/不生成、不修复网格/));
check('no network inference or upload API exists',()=>assert(!/\bfetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon/.test(source)));
check('no storage of user images',()=>assert(!/localStorage|indexedDB|sessionStorage/.test(source)));
check('standalone contains no external scripts or styles',()=>{assert(!/<script[^>]+src=/i.test(html));assert(!/<link[^>]+rel=["']stylesheet/i.test(html));});
check('standalone CSP forbids network connections',()=>assert(html.includes("connect-src 'none'")));
check('standalone script compiles',()=>{const script=html.match(/<script>([\s\S]*)<\/script>/)[1];new vm.Script(script);});
check('history uses distinct learning namespace',()=>{assert(source.includes('#animal-learning'));assert(source.includes('atlasLearning:{depth:'));assert(source.includes('window.history.go(-state.depth)'));});
check('file processing invalidated by navigation',()=>assert(source.includes("const onNavigation=()=>{loadToken++")));
const workflow=data.motionWorkflows?.[0];
check('one verified video workflow added separately',()=>{assert.equal(data.motionWorkflows.length,1);assert.equal(workflow.id,'video-motion-silhouette');});
check('workflow route does not replace teacher route',()=>assert(!data.teachers.some(t=>t.id===workflow.id)));
check('workflow execution remains explicitly false',()=>assert.equal(workflow.inferenceExecuted,false));
check('primary post and referenced tutorial kept distinct',()=>{assert(workflow.links.some(l=>l.url==='https://x.com/Graalitoo/status/2106536651883421934'));assert(workflow.links.some(l=>l.url==='https://www.youtube.com/watch?v=evK-Y83Qlco'));});
check('actual post is described as humanoid, tutorial as animal description',()=>{assert.match(workflow.demonstratedScope,/盔甲人形/);assert.match(workflow.demonstratedScope,/创作者的完整说明/);});
check('incomplete tutorial viewing disclosed',()=>assert.match(workflow.sourceRelationship,/播放\/转写未完整取得/));
check('old Mixamo stack is not attributed to new method',()=>assert.match(workflow.sourceRelationship,/不能据此视为本帖技术栈/));
check('human failure and depth ambiguity retained',()=>{assert.match(workflow.limits.join(' '),/人体搬石、扛木失败/);assert.match(workflow.coreBoundary,/不能证明三维深度/);});
check('multi-view synchronization and calibration not assumed',()=>{assert.match(workflow.limits.join(' '),/需验证逐帧同步和跨视角一致性/);assert.match(workflow.limits.join(' '),/不能称相机已标定/);});
check('missing movable anatomy cannot be invented',()=>assert.match(workflow.limits.join(' '),/翅膀只是贴图/));
check('unavailable code weights hardware disclosed',()=>{assert.match(workflow.availability,/尚未发现公开代码、权重/);assert.match(workflow.availability,/最低硬件/);});
check('author timing is not benchmarked as local result',()=>assert.match(workflow.authorReportedCost,/不是本工作台实测/));
check('observation protocol is not solved animation output',()=>{assert.match(workflow.output,/不导出新动作/);assert(workflow.suggestedObservationFields.includes('visibility'));assert(workflow.suggestedObservationFields.includes('time_seconds'));});
check('future cross-species maker is not claimed complete',()=>assert.match(workflow.futureGate,/不能由单次演示升级/));
check('new card opens action workspace and preserved method card still downloads',()=>{assert.match(motionSection(),/打开视频动作工作区/);assert.match(workflowMarkup(workflow),/下载动作学习卡 JSON/);assert(!/data-run|run-inference|generate-motion/.test(workflowMarkup(workflow)));});
check('workflow view has explicit evidence status',()=>{const view=workflowMarkup(workflow);assert.match(view,/原帖视频已查看/);assert.match(view,/教程说明已读取/);assert.match(view,/拟合流程未运行/);});
check('diagram is identified as method, not motion result',()=>assert.match(motionSection(),/非动捕或动画结果/));
const report={schema:'kaopu/animal-learning-qa@1',checkedAtUtc:new Date().toISOString(),repository:'haihao0307/guilin-dem-pipeline',scope:'kaopu-animal-learning',checks,counts:{passed:checks.length,failed:0},artifact:{path:'index.html',sha256:crypto.createHash('sha256').update(html).digest('hex'),bytes:Buffer.byteLength(html)},notRun:['Actual browser/UI and file:// runtime','GPU/CPU inference for any teacher','User image or author output testing','Network deployment and live publication checks']};
fs.mkdirSync(path.join(root,'qa'),{recursive:true});fs.writeFileSync(path.join(root,'qa/LEARNING_STATIC_NUMERIC.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({passed:checks.length,failed:0,report:'qa/LEARNING_STATIC_NUMERIC.json'},null,2));

