'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{execFileSync}=require('child_process'),{pathToFileURL}=require('url');
module.exports=async function(browser,inputUrl,out,group='catalog'){
 const root=path.resolve(__dirname,'..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');fs.mkdirSync(out,{recursive:true});
 const result={passed:false,fullRegressionPassed:false,contactAcceptance:false,physicalIPhoneTested:false,productionReady:false,scope:'R9 new editor '+group+' only, preserved accepted R8 shading; existing root radius contacts remain 3/2/3/3',checks:[],errors:[],frames:[],executedRuntime:{}};let context,page,temp;
 const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));
 const check=(name,pass,detail)=>{result.checks.push({name,pass:!!pass,detail});save();console.log('[R9 '+group+']',pass?'PASS':'FAIL',name);if(!pass)throw Error(name+' '+JSON.stringify(detail));};
 try{
  const cert=JSON.parse(fs.readFileSync(path.join(root,'EAR-RUNTIME-CERTIFICATE.json')));result.inheritedContactCertificate=cert;
  let url=inputUrl;if(url.startsWith('file:')){temp=fs.mkdtempSync(path.join(os.tmpdir(),'gnm-r9-'));const target=path.join(temp,'experiment.html');result.offline=JSON.parse(execFileSync('python3',[path.join(root,'tools/build-experiment-offline.py'),'--output',target,'--assets-dir',process.env.GNM_ASSETS_DIR||path.join(temp,'cache'),'--download'],{encoding:'utf8',timeout:180000,maxBuffer:2000000}));url=pathToFileURL(target).href;}
  context=await browser.newContext({viewport:{width:1100,height:900},deviceScaleFactor:1,hasTouch:true,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});
  const files=['experiment.html','experiment.css',...fs.readdirSync(path.join(root,'src')).filter(f=>f.endsWith('.js')).map(f=>'src/'+f),'data/teacher-groom.js'],expected=Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))])),pending=[];result.sourceHashes=expected;
  if(url.startsWith('http')){const deadline=Date.now()+480000;let match=false;do{result.served=Object.fromEntries(await Promise.all(files.map(async f=>{const r=await context.request.get(new URL(f,url).href);return[f,{status:r.status(),sha256:sha(await r.body())}];})));match=files.every(f=>result.served[f].status===200&&result.served[f].sha256===expected[f]);if(match)break;await page.waitForTimeout(10000);}while(Date.now()<deadline);check('all public source bytes equal this commit',match,result.served);page.on('response',r=>{const f=files.find(f=>new URL(f,url).href===r.url());if(f)pending.push(r.body().then(b=>result.executedRuntime[f]={status:r.status(),sha256:sha(b)}).catch(e=>result.executedRuntime[f]={error:String(e)}));});}
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.groomStudy?.ready||!document.getElementById('error').hidden,null,{timeout:240000});check('real WebGL editor starts',await page.evaluate(()=>!!groomStudy.ready));
  if(url.startsWith('http')){await Promise.all(pending);check('browser executed pinned public source responses',files.every(f=>result.executedRuntime[f]?.status===200&&result.executedRuntime[f].sha256===expected[f]),result.executedRuntime);}
  const probe=()=>page.evaluate(()=>{const c=document.getElementById('canvas'),g=c.getContext('webgl2'),a=new Uint8Array(g.drawingBufferWidth*g.drawingBufferHeight*4);g.readPixels(0,0,g.drawingBufferWidth,g.drawingBufferHeight,g.RGBA,g.UNSIGNED_BYTE,a);let hash=2166136261,rgb=2166136261;for(let i=0;i<a.length;i++)hash=Math.imul(hash^a[i],16777619)>>>0;for(let i=0;i<a.length;i+=4)rgb=Math.imul(rgb^a[i]^a[i+1]^a[i+2],16777619)>>>0;return {hash,rgb,gl:g.getError(),d:groomStudy.diagnostics()};});
  const shot=async name=>{const x=await probe();x.image=name+'.png';await page.locator('#canvas').screenshot({path:path.join(out,x.image)});result.frames.push(x);save();return x;};
  const act=(method,arg)=>page.evaluate(({method,arg})=>groomStudy[method](arg),{method,arg});
  const input=async(id,value)=>{await page.locator('#'+id).evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);};
  const base=await shot('00-accepted-r8-default');result.defaultHash=base.hash;
  check('default keeps exact audited R8 head and source curves',base.d.model.positionHash===cert.states.neutral.modelPositionHash&&JSON.stringify(base.d.geometryHashes)===JSON.stringify(cert.states.neutral.geometryHashes),{model:base.d.model,curves:base.d.geometryHashes});
  check('R8 layered shader and default pixels retained exactly',base.d.state.shadowMode==='layered'&&base.d.opacity.enabled&&!base.d.opacity.lastError&&base.hash===1257898639&&base.rgb===3664109723,{hash:base.hash,rgb:base.rgb,buffer:base.d.drawingBuffer,opacity:base.d.opacity});
  check('all default visible geometry finite and original failures disclosed',base.gl===0&&base.d.bindings.every(b=>b.finite)&&base.d.contactAcceptance===false&&base.d.fullRegressionPassed===false);
  if(group==='core'){
   await page.locator('#legacyStyles > summary').click();const styles=['original','chin-trim','cropped-trim','side-sweep','swept-back','short-crop'],hashes=[];
   for(const name of styles){await page.locator('[data-style="'+name+'"]').click();const f=await shot('style-'+name);hashes.push(f.hash);check(name+' changes actual drawn groom only',f.d.state.groom.style===name&&f.d.model.positionHash===base.d.model.positionHash&&f.gl===0&&f.d.legacyScalp.finite&&f.d.bindings.every(b=>b.finite),{hash:f.hash,draw:f.d.editors[0],legacy:f.d.legacyScalp});}
   check('six presets produce distinct rendered pixels',new Set(hashes).size===6,hashes);
   await page.locator('[data-style="swept-back"]').click();await input('hairVolume',75);await input('hairline',75);await input('sideCoverage',40);const regional=await shot('short-regional-adjustment');check('short regional controls edit live groom and retain roots',regional.d.legacyScalp.rootHash===base.d.legacyScalp.rootHash&&regional.d.state.groom.sideCoverage===40&&regional.d.model.positionHash===base.d.model.positionHash&&regional.gl===0,regional.d.legacyScalp);
   await page.locator('#resetAll').click();const reset=await shot('all-six-reset');check('all hairstyle edits restore exact R8 image',reset.hash===base.hash,{before:base.hash,after:reset.hash});
   await page.locator('[data-style="chin-trim"]').click();await page.locator('[data-case="surprise"]').evaluate(el=>el.click());const exp=await shot('trim-surprise');check('trim follows genuine expression and original source roots',exp.d.model.positionHash===cert.states.surprise.modelPositionHash&&JSON.stringify(exp.d.geometryHashes)===JSON.stringify(cert.states.surprise.geometryHashes)&&exp.d.bindings.every(b=>b.finite)&&exp.gl===0);
  }else if(group==='catalog'){
   const edits=[['hairColor','#ba7938'],['hairLength',62],['hairDensity',48],['hairWidth',58],['hairRoughness',78]];
   for(const [key,value]of edits){await input(key,value);const f=await shot('edit-'+key);check(key+' control changes pixels, not head/root binding',f.hash!==base.hash&&f.d.state.groom[key]===value&&f.d.model.positionHash===base.d.model.positionHash&&JSON.stringify(f.d.geometryHashes)===JSON.stringify(base.d.geometryHashes)&&f.gl===0,{hash:f.hash,value:f.d.state.groom[key],editor:f.d.editors[0]});await page.locator('#resetAll').click();}
   await page.locator('#hairVisible').click();const hide=await shot('hair-hidden');check('hair visibility keeps brows available',!hide.d.state.groom.hairVisible&&hide.d.state.groom.browsVisible&&hide.hash!==base.hash);
   await page.locator('#resetAll').click();const restored=await shot('all-controls-restored');check('repeated reset gives exact accepted original image',restored.hash===base.hash,{base:base.hash,restored:restored.hash});
   const before=await page.evaluate(()=>JSON.stringify(groomStudy.getState()));check('invalid patch rejected without partial edits',await page.evaluate(()=>{const before=JSON.stringify(groomStudy.getState());try{groomStudy.setGroom({hairColor:'#ff0000',style:'unknown'});return false}catch{return JSON.stringify(groomStudy.getState())===before}}));
  }else if(group==='orbit'){
   const camera=()=>page.evaluate(()=>groomStudy.diagnostics().camera);const before=await camera();
   const box=await page.locator('#canvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.50,{steps:3});await page.mouse.up();const dragged=await shot('manual-drag');check('real mouse drag rotates live view, leaves model unchanged',JSON.stringify(dragged.d.camera.position)!==JSON.stringify(before.position)&&dragged.d.model.positionHash===base.d.model.positionHash&&dragged.hash!==base.hash&&!dragged.d.state.turntable);
   await page.locator('#reset').click();check('camera reset exactly restores original pixels',(await probe()).hash===base.hash);
   await page.locator('#turnLeft').click();const left=await shot('manual-left');await page.locator('#turnRight').click();const right=await probe();check('visible manual left/right controls reverse the angle',left.hash!==base.hash&&right.d.camera.position.every((x,i)=>Math.abs(x-before.position[i])<1e-6));
   for(let i=0;i<2;i++){const start=await page.evaluate(()=>({frame:groomStudy.diagnostics().frameCount,camera:groomStudy.diagnostics().camera}));await page.locator('#rotate').click();await page.waitForFunction(n=>groomStudy.diagnostics().frameCount>n+2,start.frame,{timeout:120000});await page.locator('#rotate').click();const stopped=await page.evaluate(()=>groomStudy.diagnostics());await page.waitForTimeout(200);const quiet=await page.evaluate(()=>groomStudy.diagnostics());check('automatic rotate cycle '+i+' advances and really pauses',JSON.stringify(stopped.camera.position)!==JSON.stringify(start.camera.position)&&!quiet.state.turntable&&JSON.stringify(quiet.camera)===JSON.stringify(stopped.camera)&&quiet.frameCount===stopped.frameCount);}
   await page.locator('[data-view="back"]').click();await shot('back-view');await page.locator('[data-view="side"]').click();await shot('side-view');await page.locator('#plus').click();check('zoom reaches 200%',await page.evaluate(()=>groomStudy.getState().zoom===2));await page.locator('#reset').click();check('view/zoom/rotation reset exact',(await probe()).hash===base.hash);
   await page.locator('[data-panel="brows"]').click();await page.locator('[data-panel="beard"]').click();await page.locator('[data-panel="hair"]').click();check('repeat editor tabs leave canvas and values untouched',(await probe()).hash===base.hash);
  }else if(group==='touch'){
   await page.locator('[data-panel="brows"]').click();await page.locator('[data-brow-preset="soft"]').click();const soft=await shot('soft-brows');check('brow preset changes actual drawn brow density without moving head',soft.hash!==base.hash&&soft.d.editors[1].activeStrands===650&&soft.d.model.positionHash===base.d.model.positionHash);
   await input('browsLength',50);await input('browsWidth',145);await input('browsColor','#ba7938');const brow=await shot('brow-manual');check('brow length width and color independent of scalp',brow.d.state.groom.hairColor===base.d.state.groom.hairColor&&brow.d.state.groom.browsLength===50&&brow.gl===0&&brow.hash!==soft.hash);
   await page.locator('#resetAll').click();await page.locator('[data-panel="beard"]').click();const beardShots=[];
   for(const name of ['stubble','moustache','goatee','both']){await page.locator('[data-beard-preset="'+name+'"]').click();const f=await shot('beard-'+name);beardShots.push(f.hash);const d=f.d.facial.beard;check(name+' actual bound beard region is finite and correct',f.hash!==base.hash&&f.gl===0&&d.finite&&d.invalidTriangles===0&&d.invalidGuideTriangles===0&&(name!=='moustache'||d.activeChinCount===0&&d.activeMoustacheCount>0)&&(name!=='goatee'||d.activeMoustacheCount===0&&d.activeChinCount>0),d);}
   check('four beard presets have different real pixels',new Set(beardShots).size===4,beardShots);
   await input('beardDensity',32);await input('beardLength',80);await input('beardWidth',150);await input('beardColor','#87837b');const custom=await shot('beard-manual');check('beard independent manual controls work',custom.d.state.groom.beardDensity===32&&custom.d.facial.beard.density===.32&&custom.d.facial.beard.length===.008&&custom.gl===0&&custom.d.facial.beard.minTemplateGuideLipGap>.0035,custom.d.facial.beard);
   await page.locator('#resetAll').click();check('brow and beard reset exactly restores R8',(await probe()).hash===base.hash);
   for(const viewport of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(viewport);await act('setCamera','three');await page.evaluate(()=>scrollTo(0,0));const name=viewport.width===390?'portrait':'landscape';check(name+' rotation controls visible first screen and no overlap',await page.evaluate(()=>{const ids=['rotate','turnLeft','turnRight','reset'];return document.documentElement.scrollWidth<=innerWidth&&ids.every(id=>{const b=document.getElementById(id).getBoundingClientRect();return b.width>0&&b.height>0&&b.top>=0&&b.bottom<=innerHeight})&&document.getElementById('cameraDeck').getBoundingClientRect().bottom<=document.getElementById('stage').getBoundingClientRect().top+.1}));await page.screenshot({path:path.join(out,'mobile-'+name+'.png')});await page.locator('#turnLeft').tap();await page.locator('#reset').tap();check(name+' native touch rotate and reset',await page.evaluate(()=>groomStudy.getState().view==='three'&&!groomStudy.getState().turntable));}
   await page.setViewportSize({width:390,height:844});for(const name of ['hair','brows','beard']){await page.locator('[data-panel="'+name+'"]').tap();const slider=page.locator('#'+name+'Density');await slider.scrollIntoViewIfNeeded();const box=await slider.boundingBox();await page.touchscreen.tap(box.x+box.width*.45,box.y+box.height/2);check('native touch '+name+' density changes',await page.evaluate(k=>groomStudy.getState().groom[k]<80,name+'Density'));await page.locator('#panel-'+name).screenshot({path:path.join(out,'mobile-'+name+'-panel.png')});}
  }
  if(group==='catalog'){
   const navigationContext=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:false}),navigationPage=await navigationContext.newPage();
   const originalEntry=inputUrl.startsWith('http')?new URL('../gnm-study/index.html',inputUrl).href:pathToFileURL(path.join(root,'../gnm-study/index.html')).href;
   await navigationPage.goto(originalEntry,{waitUntil:'domcontentloaded'});const entry=navigationPage.locator('#groomEditorLink');
   check('original human page exposes direct R9 link on mobile first screen',await entry.isVisible()&&await entry.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<innerHeight&&r.right<=innerWidth&&el.getAttribute('href')==='../gnm-groom-editor/experiment.html'}));
   await navigationPage.screenshot({path:path.join(out,'original-human-r9-entry-mobile.png')});await entry.click();check('original human entry reaches exact editor URL',navigationPage.url().endsWith('/gnm-groom-editor/experiment.html'));result.entryScope='Native anchor navigation and layout with scripts disabled; R9 live renderer independently tested above';await navigationContext.close();
   await page.addInitScript(()=>{const base=WebGL2RenderingContext.prototype.getExtension;WebGL2RenderingContext.prototype.getExtension=function(name){if(name==='EXT_color_buffer_float'||name==='EXT_color_buffer_half_float')return null;return base.call(this,name);};});
   await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.groomStudy?.ready||!document.getElementById('error').hidden,null,{timeout:240000});
   const fallback=await shot('unsupported-original-fallback');
   check('unsupported capability starts cleanly in exact original-shadow fallback',fallback.d.ready&&!fallback.d.opacityCapability.supported&&fallback.d.state.shadowMode==='stochastic'&&fallback.hash===1963128749&&fallback.rgb===977755421&&fallback.gl===0,{hash:fallback.hash,capability:fallback.d.opacityCapability});
   check('unsupported layered mode is visibly unavailable and API refuses it',await page.evaluate(()=>{let refused=false;try{groomStudy.setShadowMode('layered')}catch{refused=true}return refused&&document.querySelector('[data-shadow-mode="layered"]').disabled&&document.getElementById('opacityStatus').textContent.includes('保留原投影')}));
   result.fallbackScope='Injected absence of color-buffer float extensions, not a physical device compatibility test';

  }
  check('sampled shaders and console remain error free',result.errors.length===0&&result.frames.every(f=>f.gl===0),result.errors);result.passed=true;
 }catch(e){result.failure=e.stack;if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});}catch{}}finally{if(context)await context.close();if(temp)fs.rmSync(temp,{recursive:true,force:true});save();}return result;
};
