import * as THREE from '../vendor/three.module.js';
import {createLeafTextures,createLeafStudy,leafGeometry,setLeafShape,leafPoint} from './leaf.js';
import {TeacherVenation} from './venation.js';
import {clamp} from './geometry.js';
const bootStarted=performance.now();
const $=s=>document.querySelector(s),host=$('#canvas-host');
const params={curl:5.1,transmission:.58,layers:3,light:135,exposure:1.05,dof:.25,fringe:false,time:0};
const state={case:'01',playing:true,autoOrbit:false,frames:0,shaderErrors:[],pointer:null,teacher:false,dirty:true};
const scene=new THREE.Scene();scene.background=new THREE.Color(0xd4dfb5);const camera=new THREE.PerspectiveCamera(36,1,.01,150);
let renderer,study,leafTextures,teacher=new TeacherVenation(),last=0,post,rt;
let home={target:[0,-1.05,.8],yaw:1.0,pitch:1.2,distance:5.8};
const view={target:new THREE.Vector3(0,-1.05,.8),yaw:1.0,pitch:1.20,distance:5.8};
function error(message){$('#error').hidden=false;$('#error').textContent=message;$('#loading').hidden=true;$('#status').textContent='渲染未通过，请查看错误信息';}
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});}catch(e){error('此浏览器未能建立 WebGL2。三维实验没有运行，未用图片或视频替代。'+e.message);throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=params.exposure;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);
renderer.debug.onShaderError=(gl,program,vs,fs)=>{const message=[gl.getProgramInfoLog(program),gl.getShaderInfoLog(vs),gl.getShaderInfoLog(fs)].join('\n');state.shaderErrors.push(message);error('着色器编译失败：'+message);};
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();state.playing=false;error('图形上下文已丢失。当前参数保留，可重新打开页面恢复。');});
const ambient=new THREE.HemisphereLight(0xeeffd8,0x526045,.12);scene.add(ambient);
const key=new THREE.DirectionalLight(0xfff8dd,3.4);key.position.set(-4,5,-3);key.castShadow=true;key.shadow.mapSize.set(4096,4096);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.camera.near=.1;key.shadow.camera.far=30;key.shadow.bias=-.00002;key.shadow.normalBias=.0005;scene.add(key,key.target);
const rim=new THREE.DirectionalLight(0xe1efca,.24);rim.position.set(4,2,4);scene.add(rim);
// A procedural studio environment provides real specular/transmission illumination.
const studio=new THREE.Scene();studio.background=new THREE.Color(0xb4c39e);const environmentGeo=new THREE.SphereGeometry(1,20,12);
for(const [x,y,z,s,c] of [[-4,5,0,2.1,0xffffff],[3,2,-3,1.5,0xeeffd6],[1,-4,2,1.8,0x768b60]]){const m=new THREE.Mesh(environmentGeo,new THREE.MeshBasicMaterial({color:c}));m.position.set(x,y,z);m.scale.setScalar(s);studio.add(m);}const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(studio,.025);scene.environment=env.texture;scene.environmentIntensity=.03;pmrem.dispose();environmentGeo.dispose();studio.traverse(o=>o.material?.dispose());
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x454d3a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-1.52;ground.receiveShadow=true;ground.visible=false;scene.add(ground);
function createPost(){rt=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:true});rt.depthTexture=new THREE.DepthTexture(1,1,THREE.UnsignedIntType);const material=new THREE.ShaderMaterial({uniforms:{colorTex:{value:rt.texture},depthTex:{value:rt.depthTexture},resolution:{value:new THREE.Vector2()},nearZ:{value:camera.near},farZ:{value:camera.far},focus:{value:6.5},aperture:{value:.25},fringe:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.0,1.0);}',fragmentShader:`precision highp float;varying vec2 vUv;uniform sampler2D colorTex;uniform sampler2D depthTex;uniform vec2 resolution;uniform float nearZ,farZ,focus,aperture,fringe;float depthAt(vec2 uv){float z=texture2D(depthTex,uv).x;return (nearZ*farZ)/(farZ-z*(farZ-nearZ));}void main(){float d=depthAt(vUv);float blur=clamp(abs(d-focus)/max(1.0,d)*aperture*26.0,0.0,9.0);vec3 c=texture2D(colorTex,vUv).rgb;float w=1.0;for(int i=0;i<16;i++){float a=float(i)*2.39996323;vec2 ofs=vec2(cos(a),sin(a))*sqrt((float(i)+.5)/16.0)*blur/resolution;float od=depthAt(vUv+ofs);float accept=mix(.2,1.0,step(d-.4,od));c+=texture2D(colorTex,vUv+ofs).rgb*accept;w+=accept;}c/=w;vec2 radial=(vUv-.5)*fringe*.0018;c.r=mix(c.r,texture2D(colorTex,vUv+radial).r,fringe);c.b=mix(c.b,texture2D(colorTex,vUv-radial).b,fringe);float vignette=1.0-.13*dot(vUv-.5,vUv-.5);gl_FragColor=vec4(c*vignette,1.0);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`,depthTest:false,depthWrite:false});post={scene:new THREE.Scene(),camera:new THREE.OrthographicCamera(-1,1,1,-1,0,1),material};post.scene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),material));}
createPost();
function fitObject(){if(!study)return;study.root.updateMatrixWorld(true);const meshes=[],box=new THREE.Box3(),p=new THREE.Vector3();study.root.traverse(o=>{if(!o.isMesh)return;let v=o;while(v){if(!v.visible)return;v=v.parent;}meshes.push(o);const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld);box.expandByPoint(p);}});if(box.isEmpty())return;box.getCenter(view.target);const outward=new THREE.Vector3().setFromSphericalCoords(1,view.pitch,view.yaw),right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),outward).normalize(),up=new THREE.Vector3().crossVectors(outward,right).normalize(),tanV=Math.tan(THREE.MathUtils.degToRad(camera.fov)/2),tanH=tanV*camera.aspect;let distance=0;for(const o of meshes){const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).sub(view.target);const z=p.dot(outward);distance=Math.max(distance,z+Math.abs(p.dot(right))/(tanH*.91),z+Math.abs(p.dot(up))/(tanV*.83));}}view.distance=Math.max(.5,distance);updateCamera();}
function updateCamera(){state.dirty=true;camera.position.setFromSphericalCoords(view.distance,view.pitch,view.yaw).add(view.target);camera.lookAt(view.target);if(view.roll)camera.rotateZ(view.roll);post.material.uniforms.focus.value=view.distance;}
function resize(){state.dirty=true;const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();const size=new THREE.Vector2();renderer.getDrawingBufferSize(size);rt.setSize(size.x,size.y);post.material.uniforms.resolution.value.copy(size);if(!state.userFraming)fitObject();}
new ResizeObserver(resize).observe(host);resize();updateCamera();
function setLight(){state.dirty=true;const a=params.light*Math.PI/180;key.position.copy(view.target).add(new THREE.Vector3(Math.cos(a)*Math.max(5,view.distance*.6),Math.max(4,view.distance*.5),-Math.sin(a)*Math.max(5,view.distance*.6)));key.target.position.copy(view.target);renderer.toneMappingExposure=params.exposure;post.material.uniforms.aperture.value=params.dof;post.material.uniforms.fringe.value=params.fringe?1:0;}
function updateLeaf(){state.dirty=true;if(!study||state.case!=='01')return;study.leaves.forEach((leaf,i)=>{leaf.visible=i<params.layers;const shape=leaf.userData.shape;setLeafShape(leaf,{curl:params.curl*shape.curl,fold:shape.fold,length:shape.length,width:shape.width,twist:shape.twist,sway:shape.sway,nu:52,nv:180,ripple:.007});});study.material.thinTransmission=params.transmission;state.userFraming=false;fitObject();}
function stats(){if(!study)return;let triangles=0,meshes=0;study.root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);}});$('#stats').textContent=`${Math.round(triangles).toLocaleString()} 三角面 · ${meshes} 网格 · ${renderer.info.memory.textures} 纹理`;}
function drawTeacher(){const c=$('#teacher-canvas').getContext('2d');c.fillStyle='#181818';c.fillRect(0,0,800,600);for(const v of teacher.veins){c.beginPath();c.arc(v.x,v.y,5,0,Math.PI*2);c.fillStyle='#fff';c.fill();c.beginPath();c.arc(v.x,v.y,2,0,Math.PI*2);c.fillStyle='#000';c.fill();c.beginPath();c.moveTo(v.x,v.y);c.lineTo(v.x+v.dx*20,v.y+v.dy*20);c.strokeStyle='#c87fff';c.stroke();}for(const a of teacher.auxins){c.beginPath();c.arc(a.x,a.y,5,0,Math.PI*2);c.fillStyle='#ff3434';c.fill();}$('#teacher-count').textContent=`第 ${teacher.frame} 步 · ${teacher.veins.length} 叶脉点 · ${teacher.auxins.length} 吸引点`;}
$('#baseline').onclick=()=>{state.teacher=true;$('#teacher-view').hidden=false;$('#baseline').classList.add('active');$('#applied').classList.remove('active');drawTeacher();};$('#applied').onclick=()=>{state.teacher=false;$('#teacher-view').hidden=true;$('#applied').classList.add('active');$('#baseline').classList.remove('active');};$('#teacher-step').onclick=()=>{if(teacher.veins.length<20000)teacher.tick();drawTeacher();};$('#teacher-reset').onclick=()=>{teacher=new TeacherVenation();drawTeacher();};
for(const id of ['curl','transmission','layers','light','exposure','dof'])$('#'+id).oninput=e=>{params[id]=Number(e.target.value);$('#'+id+'-out').textContent=id==='light'?`${params[id]}°`:id==='transmission'?`${Math.round(params[id]*100)}%`:id==='layers'?params[id]:params[id].toFixed(2);if(id==='curl'||id==='layers')updateLeaf();if(id==='transmission'&&study?.material)study.material.thinTransmission=params.transmission;setLight();};$('#fringe').onchange=e=>{params.fringe=e.target.checked;setLight();};
$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'暂停':'播放';};$('#restart').onclick=()=>{params.time=0;state.dirty=true;};$('#time').oninput=e=>{params.time=Number(e.target.value);state.playing=false;state.dirty=true;$('#play').textContent='播放';study?.update(params.time);};
$('#orbit').onclick=()=>{state.autoOrbit=!state.autoOrbit;$('#orbit').classList.toggle('active',state.autoOrbit);};
$('#reset').onclick=()=>{state.userFraming=false;view.roll=0;view.target.fromArray(home.target);view.yaw=home.yaw;view.pitch=home.pitch;view.distance=home.distance;fitObject();updateCamera();setLight();};$('#front').onclick=()=>{state.userFraming=false;view.roll=0;view.yaw=0;view.pitch=Math.PI/2;fitObject();};$('#side').onclick=()=>{state.userFraming=false;view.roll=0;view.yaw=Math.PI/2;view.pitch=1.35;fitObject();};$('#near').onclick=()=>{state.userFraming=true;if(state.case==='01'){view.target.set(0,-.9,.75);view.distance=2.65;view.yaw=1.38;}else{view.target.fromArray(home.nearTarget??home.target);view.distance=home.nearDistance??home.distance*.38;}view.pitch=1.35;updateCamera();};
$('#source').onclick=()=>$('#source-dialog').showModal();$('#close-source').onclick=()=>$('#source-dialog').close();$('#source-dialog').onclick=e=>{if(e.target===$('#source-dialog'))e.target.close();};
$('#screenshot').onclick=()=>{render();const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download=`vegetation-study-${state.case}-r01.png`;a.click();};
const canvas=renderer.domElement;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{state.userFraming=true;state.pointer={id:e.pointerId,x:e.clientX,y:e.clientY,button:e.button};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!state.pointer||state.pointer.id!==e.pointerId)return;const dx=e.clientX-state.pointer.x,dy=e.clientY-state.pointer.y;state.pointer.x=e.clientX;state.pointer.y=e.clientY;if(state.pointer.button===2||e.shiftKey){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);view.target.addScaledVector(right,-dx*view.distance*.0012).addScaledVector(up,dy*view.distance*.0012);}else{view.yaw-=dx*.006;view.pitch=clamp(view.pitch-dy*.006,.04,Math.PI-.04);}updateCamera();});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>state.pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.userFraming=true;view.distance=clamp(view.distance*Math.exp(e.deltaY*.001),.7,55);updateCamera();},{passive:false});
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.target.matches('input,button')&&!$('#source-dialog').open){e.preventDefault();if(state.teacher)$('#teacher-step').click();else $('#play').click();}});
function render(){if(state.shaderErrors.length)return;state.dirty=false;renderer.setRenderTarget(rt);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(post.scene,post.camera);state.frames++;}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!document.hidden&&!state.teacher){if(state.playing){params.time+=dt;if(params.time>30){if(state.case==='02'){params.time=30;state.playing=false;$('#play').textContent='播放';}else params.time%=30;}state.dirty=true;}if(state.autoOrbit){view.yaw+=dt*.12;updateCamera();}if(state.dirty){study?.update(params.time);$('#time').value=params.time;$('#time-label').textContent=params.time.toFixed(2)+' s';render();}}requestAnimationFrame(frame);}
window.__plantStudy={state,params,scene,camera,renderer,get study(){return study;},mount(next,config){if(study)study.root.visible=false;study=next;scene.add(study.root);study.root.visible=true;state.case=config.id;state.teacher=false;$('#teacher-view').hidden=true;home=config.view;scene.background.set(config.background??0xd4dfb5);ground.visible=!!config.ground;ground.position.y=-.016;scene.environmentIntensity=config.environmentIntensity??.03;ambient.intensity=config.ambient??1.2;rim.intensity=config.rim??.8;params.dof=config.dof??0;$('#dof').value=params.dof;$('#dof-out').textContent=params.dof.toFixed(2);params.time=config.time??0;state.playing=false;$('#play').textContent='播放';$('#reset').click();study.update(params.time);state.dirty=true;stats();},invalidate(){state.dirty=true;stats();},setTime(t){params.time=t;state.playing=false;$('#play').textContent='播放';$('#time').value=t;$('#time-label').textContent=t.toFixed(2)+' s';study?.update(t);render();},evidence(){return {case:state.case,frame:state.frames,shaderErrors:state.shaderErrors,geometry:study?.info,memory:renderer.info.memory,startupMs:window.__plantStudy.startupMs,real3D:true,videoElements:document.querySelectorAll('video').length,teacherStep:teacher.frame,version:'R09',sourceBaseline:'tsoding-3d828c51',opticalUniforms:{environmentScene:scene.environmentIntensity,environmentShader:study?.material?.userData.compiledUniforms?.envMapIntensity?.value,thinTransmission:study?.material?.thinTransmission},visualAcceptance:false};}};
requestAnimationFrame(()=>{try{leafTextures=createLeafTextures();study=createLeafStudy({textures:leafTextures,params});scene.add(study.root);fitObject();setLight();updateCamera();render();stats();$('#loading').hidden=true;window.__plantStudy.startupMs=performance.now()-bootStarted;window.dispatchEvent(new Event('vegetation-study-ready'));requestAnimationFrame(frame);}catch(e){error(e.stack||e.message);}});

window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='vegetation-study-pause'){state.playing=false;state.autoOrbit=false;$('#play').textContent='播放';}});

function referenceMacro(){params.curl=.65;params.layers=1;params.time=2;state.playing=false;$('#play').textContent='播放';$('#curl').value=.65;$('#curl-out').textContent='0.65';$('#layers').value=1;$('#layers-out').textContent='1';updateLeaf();view.yaw=-.18;view.pitch=1.32;fitObject();view.distance*=.69;view.roll=-.52;state.userFraming=true;params.dof=.72;params.light=35;$('#dof').value=.72;$('#dof-out').textContent='.72';$('#light').value=35;$('#light-out').textContent='35°';setLight();updateCamera();}const macroButton=document.createElement('button');macroButton.id='reference-macro';macroButton.textContent='叶脉对照';macroButton.onclick=referenceMacro;$('.view-actions').insertBefore(macroButton,$('#screenshot'));window.__plantStudy.referenceMacro=referenceMacro;

function referenceDetail(){referenceMacro();const leaf=study.leaves[0],shape=leaf.userData.shape;study.update(params.time);study.root.updateMatrixWorld(true);view.target.copy(new THREE.Vector3(...leafPoint(.57,.48,{length:shape.length,width:shape.width,curl:params.curl*shape.curl,fold:shape.fold,twist:shape.twist,sway:shape.sway,ripple:.007})).applyMatrix4(leaf.matrixWorld));view.distance=1.50;view.yaw=-.08;view.pitch=1.16;view.roll=-.64;params.dof=.85;$('#dof').value=.85;$('#dof-out').textContent='.85';setLight();updateCamera();}window.__plantStudy.referenceDetail=referenceDetail;

function referenceCurlDetail(){referenceDetail();params.curl=2.2;$('#curl').value=2.2;$('#curl-out').textContent='2.20';updateLeaf();const leaf=study.leaves[0],shape=leaf.userData.shape;study.update(params.time);study.root.updateMatrixWorld(true);view.target.copy(new THREE.Vector3(...leafPoint(.56,.48,{length:shape.length,width:shape.width,curl:params.curl*shape.curl,fold:shape.fold,twist:shape.twist,sway:shape.sway,ripple:.007})).applyMatrix4(leaf.matrixWorld));view.distance=1.55;view.yaw=-.10;view.pitch=2.15;view.roll=-.64;params.fringe=true;$('#fringe').checked=true;setLight();updateCamera();}window.__plantStudy.referenceCurlDetail=referenceCurlDetail;
