import * as THREE from '../vendor/three.module.js';
import {curve,smooth,clamp,branchMesh,seeded} from './geometry.js';
import {leafGeometry,leafMaterial} from './leaf.js';
import {GrowthGraph,addRootNetwork} from './growth.js';
export function createCoffeeStudy({textures}){
 const root=new THREE.Group(),graph=new GrowthGraph(),underground=new THREE.Group(),shoot=new THREE.Group();root.add(underground,shoot);const rand=seeded(217);
 const rootMat=new THREE.MeshStandardMaterial({color:0xa79673,roughness:.94}),stemMat=new THREE.MeshStandardMaterial({color:0x657030,roughness:.68});addRootNetwork(graph,underground,rootMat);
 const seedMat=new THREE.MeshStandardMaterial({color:0x746448,roughness:.8});const seed=new THREE.Mesh(new THREE.SphereGeometry(.07,18,12),seedMat);seed.scale.set(1,1.25,.68);seed.position.y=-.03;root.add(seed);
 const stemPoints=Array.from({length:14},(_,i)=>[.045*Math.sin(i*.5),i*.245,.025*Math.cos(i*.7)-.025]);const stem=graph.add({id:'main-stem',path:curve(stemPoints),radius:.037,birth:.08,duration:.58,kind:'shoot',material:stemMat,segments:90,sides:14});shoot.add(stem.mesh);
 const material=leafMaterial(textures,{coffee:true}),nodes=[],flowers=[],berries=[];
 for(let n=0;n<10;n++){const at=.16+n*.082,base=stem.path.getPointAt(at),yaw=n*Math.PI/2+.28;const birth=stem.birth+stem.duration*at;
  for(let side=0;side<2;side++){const angle=yaw+side*Math.PI,dir=new THREE.Vector3(Math.cos(angle),.2,Math.sin(angle)),tip=base.clone().addScaledVector(dir,.10),petiole=graph.add({id:`petiole-${n}-${side}`,parentId:'main-stem',attachment:at,path:curve([base,base.clone().lerp(tip,.5),tip]),radius:.009,birth:birth+.02,duration:.09,kind:'petiole',material:stemMat,segments:8,sides:6});shoot.add(petiole.mesh);
   const length=(.91-n*.032)*(.94+rand()*.12),geo=leafGeometry({length,width:.48,curl:.30,fold:.18,ripple:.013,nu:25,nv:58});
   const bud=leafGeometry({length,width:.48,curl:1.7,fold:2.6,ripple:.006,nu:25,nv:58});geo.morphAttributes.position=[bud.attributes.position];geo.computeVertexNormals();
   const leaf=new THREE.Mesh(geo,material),pivot=new THREE.Group();pivot.position.copy(tip);pivot.rotation.y=-angle;pivot.add(leaf);shoot.add(pivot);leaf.castShadow=leaf.receiveShadow=true;nodes.push({leaf,pivot,petiole,birth:petiole.birth+.025,duration:.14,angle,n,side});
  }
  if(n>0&&n<8){for(let b=0;b<6;b++){const a=b*Math.PI/3+n*.3,origin=base.clone().add(new THREE.Vector3(Math.cos(a)*.052,(b%2)*.02,Math.sin(a)*.052));const flower=new THREE.Group();flower.position.copy(origin);flower.rotation.set(.4*Math.sin(a),a,-.5);const petalMat=new THREE.MeshPhysicalMaterial({color:0xfff5d9,roughness:.48,side:THREE.DoubleSide,transmission:.09,thickness:.012});for(let p=0;p<5;p++){const petal=new THREE.Mesh(leafGeometry({length:.12,width:.39,curl:1.0,fold:.06,ripple:0,nu:8,nv:18}),petalMat);petal.rotation.z=p*Math.PI*2/5;flower.add(petal);}shoot.add(flower);flowers.push({flower,birth:.67+n*.012+b*.002});const berry=new THREE.Mesh(new THREE.SphereGeometry(.048,16,12),new THREE.MeshPhysicalMaterial({color:0x7f1912,roughness:.34,clearcoat:.6,clearcoatRoughness:.2}));berry.scale.set(.9,1.12,.9);berry.position.copy(origin).add(new THREE.Vector3(Math.cos(a)*.02,-.015,Math.sin(a)*.02));berry.castShadow=true;shoot.add(berry);berries.push({berry,birth:.82+n*.01+b*.002});}}
 }
 const soilMaterial=new THREE.MeshStandardMaterial({color:0x242119,roughness:1,side:THREE.DoubleSide});const fullSoil=new THREE.Mesh(new THREE.CircleGeometry(2.1,90),soilMaterial),cutSoil=new THREE.Mesh(new THREE.CircleGeometry(2.1,90,0,Math.PI),soilMaterial);for(const m of [fullSoil,cutSoil]){m.rotation.x=-Math.PI/2;m.position.y=-.012;m.receiveShadow=true;root.add(m);}cutSoil.visible=false;
 const pebbles=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1,0),soilMaterial,280),dummy=new THREE.Object3D();for(let i=0;i<280;i++){const a=rand()*Math.PI*2,r=2*Math.sqrt(rand());dummy.position.set(Math.cos(a)*r,-.004,Math.sin(a)*r);const s=.012+rand()*.016;dummy.scale.set(s*1.2,s*.7,s);dummy.rotation.set(rand(),rand(),rand());dummy.updateMatrix();pebbles.setMatrixAt(i,dummy.matrix);}pebbles.receiveShadow=true;root.add(pebbles);
 let cut=false;return {root,graph,material,info:{geometry:'seed + attached growing root/stem axes + opposite leaf pairs + petals + fruit',species:'coffee-inspired',growth:'axis extension + independent unfolding, not global scale'},setRootCut(value){cut=value;fullSoil.visible=!value;cutSoil.visible=value;pebbles.visible=!value;},update(seconds){const age=clamp(seconds/30);graph.update(age);seed.visible=age<.25;seed.scale.set(1,.8+age*1.8,.68);for(const n of nodes){const a=smooth(n.birth,n.birth+n.duration,age);n.pivot.visible=a>.001;n.pivot.position.copy(n.petiole.path.getPointAt(Math.max(0,n.petiole.progress)));n.leaf.scale.set(Math.max(.001,a)**.7,Math.max(.001,a),Math.max(.001,a));n.leaf.morphTargetInfluences[0]=1-a;n.pivot.rotation.z=-.22-a*1.08;n.pivot.rotation.x=Math.sin(seconds*1.3+n.n)*.017*a;}for(const f of flowers){const a=smooth(f.birth,f.birth+.055,age);f.flower.visible=a>.001;f.flower.scale.setScalar(Math.max(.001,a)*(1-.25*smooth(.9,1,age)));}for(const b of berries){const a=smooth(b.birth,b.birth+.10,age);b.berry.visible=a>.001;b.berry.scale.set(.9*a,1.12*a,.9*a);b.berry.material.color.setHSL(.24*(1-a),.72,.18+.04*a);}this.info.growthEvidence=graph.evidence();this.info.rootCut=cut;}};
}
