/* Original Three.js MarchingCubes is the unmodified isosurface backend.
   This bounded SDF/attribute-transfer layer is our independent implementation.
   Axis identity and parent graph are retained; the mesh is a derived surface. */
import * as THREE from '../vendor/three.module.js';
import {MarchingCubes} from '../teachers/three-marching-cubes/MarchingCubes.js';
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const smoothMin=(a,b,k)=>{if(k<=0)return Math.min(a,b);const h=Math.max(k-Math.abs(a-b),0)/k;return Math.min(a,b)-h*h*k*.25;};
function capsule(p,s){const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,dz=s.b.z-s.a.z,den=dx*dx+dy*dy+dz*dz,q=den?clamp(((p.x-s.a.x)*dx+(p.y-s.a.y)*dy+(p.z-s.a.z)*dz)/den):0,x=p.x-s.a.x-q*dx,y=p.y-s.a.y-q*dy,z=p.z-s.a.z-q*dz;return {distance:Math.hypot(x,y,z)-(s.ra+(s.rb-s.ra)*q),q,x,y,z};}
function axisSegments(axis,axisId,{start=0,end=1,radiusScale=1,spacing=.28}={}){const length=axis.path.getLength(),count=Math.max(4,Math.ceil(length*(end-start)/spacing)),frames=axis.path.computeFrenetFrames(count,false),out=[];for(let i=0;i<count;i++){const t0=start+(end-start)*i/count,t1=start+(end-start)*(i+1)/count;out.push({axis,axisId,a:axis.path.getPointAt(t0),b:axis.path.getPointAt(t1),ra:axis.radiusAt(t0)*radiusScale,rb:axis.radiusAt(t1)*radiusScale,t0,t1,n:frames.normals[i],bframe:frames.binormals[i]});}return out;}
function boundsOfSegment(s,pad=0){const r=Math.max(s.ra,s.rb)+pad;return [new THREE.Vector3(Math.min(s.a.x,s.b.x)-r,Math.min(s.a.y,s.b.y)-r,Math.min(s.a.z,s.b.z)-r),new THREE.Vector3(Math.max(s.a.x,s.b.x)+r,Math.max(s.a.y,s.b.y)+r,Math.max(s.a.z,s.b.z)+r)];}
function weldSurface(input,tolerance=1e-5){const p=input.attributes.position,n=input.attributes.normal,lookup=new Map(),indices=[],positions=[],normals=[],mapping=[];let collapsed=0;for(let i=0;i<p.count;i++){const key=[p.getX(i),p.getY(i),p.getZ(i)].map(v=>Math.round(v/tolerance)).join(',');let id=lookup.get(key);if(id===undefined){id=positions.length/3;lookup.set(key,id);positions.push(p.getX(i),p.getY(i),p.getZ(i));normals.push(0,0,0);}mapping.push(id);normals[id*3]+=n.getX(i);normals[id*3+1]+=n.getY(i);normals[id*3+2]+=n.getZ(i);}for(let i=0;i<mapping.length;i+=3){const a=mapping[i],b=mapping[i+1],c=mapping[i+2];if(a===b||b===c||c===a){collapsed++;continue;}indices.push(a,b,c);}const result=new THREE.BufferGeometry();result.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));result.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));result.setIndex(indices);result.normalizeNormals();input.dispose();return {geometry:result,collapsed,tolerance};}
function auditSurface(g){const p=g.attributes.position.array,ix=g.index.array,edges=new Map();let volume=0;for(let i=0;i<ix.length;i+=3){const a=ix[i]*3,b=ix[i+1]*3,c=ix[i+2]*3;volume+=(p[a]*(p[b+1]*p[c+2]-p[b+2]*p[c+1])+p[a+1]*(p[b+2]*p[c]-p[b]*p[c+2])+p[a+2]*(p[b]*p[c+1]-p[b+1]*p[c]))/6;for(let j=0;j<3;j++){const a=ix[i+j],b=ix[i+(j+1)%3],key=Math.min(a,b)+','+Math.max(a,b);edges.set(key,(edges.get(key)||0)+1);}}let boundaryEdges=0,nonManifoldEdges=0;for(const count of edges.values()){if(count===1)boundaryEdges++;else if(count>2)nonManifoldEdges++;}return {signedVolume:volume,boundaryEdges,nonManifoldEdges,closed:boundaryEdges===0&&nonManifoldEdges===0};}
export function generateCoreVolume(axes,{ids,resolution=96,blend=.23,hollowRatio=.52,windows=[],maxTriangles=180000}={}){
 const begin=performance.now(),byId=new Map(axes.map((a,i)=>[a.id,{a,i}])),selected=ids.map(id=>byId.get(id)).filter(Boolean),segments=selected.flatMap(({a,i})=>axisSegments(a,i)),trunk=byId.get('trunk');if(!segments.length)throw Error('No structural core axes selected');
 const bounds=new THREE.Box3();for(const s of segments){const [a,b]=boundsOfSegment(s,blend+.65);bounds.expandByPoint(a);bounds.expandByPoint(b);}const size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),N=resolution,step=size.clone().multiplyScalar(1/N),field=new Float32Array(N*N*N).fill(100),voidField=new Float32Array(N*N*N).fill(100),xs=Array.from({length:N},(_,i)=>bounds.min.x+i*step.x),ys=Array.from({length:N},(_,i)=>bounds.min.y+i*step.y),zs=Array.from({length:N},(_,i)=>bounds.min.z+i*step.z),p=new THREE.Vector3(),padding=Math.max(step.x,step.y,step.z)*3+blend;
 const indexBounds=(min,max)=>[Math.max(0,Math.floor((min.x-bounds.min.x)/step.x)),Math.min(N-1,Math.ceil((max.x-bounds.min.x)/step.x)),Math.max(0,Math.floor((min.y-bounds.min.y)/step.y)),Math.min(N-1,Math.ceil((max.y-bounds.min.y)/step.y)),Math.max(0,Math.floor((min.z-bounds.min.z)/step.z)),Math.min(N-1,Math.ceil((max.z-bounds.min.z)/step.z))];
 function rasterSegment(s,target,k){const box=boundsOfSegment(s,padding),[x0,x1,y0,y1,z0,z1]=indexBounds(...box);for(let z=z0;z<=z1;z++)for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){p.set(xs[x],ys[y],zs[z]);const i=z*N*N+y*N+x,d=capsule(p,s).distance;target[i]=smoothMin(target[i],d,k);}}
 for(const s of segments)rasterSegment(s,field,blend);
 // Trunk cavity plus surface-access windows. These are actual subtracted
 // volumes, not dark patches or removed front faces.
 const cavitySegments=trunk?axisSegments(trunk.a,trunk.i,{start:.035,end:.975,radiusScale:hollowRatio,spacing:.22}):[];for(const s of cavitySegments)rasterSegment(s,voidField,blend*.35);
 const holes=[];if(trunk){const tframes=trunk.a.path.computeFrenetFrames(200,false),length=trunk.a.path.getLength();for(const w of windows){const j=Math.round(w.t*200),a=w.u*Math.PI*2+(trunk.a.twist??0)*w.t,rad=tframes.normals[j].clone().multiplyScalar(Math.cos(a)).addScaledVector(tframes.binormals[j],Math.sin(a)),side=tframes.normals[j].clone().multiplyScalar(-Math.sin(a)).addScaledVector(tframes.binormals[j],Math.cos(a)),up=trunk.a.path.getTangentAt(w.t),r=trunk.a.radiusAt(w.t),origin=trunk.a.path.getPointAt(w.t).addScaledVector(rad,r*.58),radii=[Math.max(.15,r*Math.sin(w.w*Math.PI*2)),w.h*length,r*1.04];holes.push({origin,side,up,rad,radii});const reach=radii[0]+radii[1]+radii[2]+padding,[x0,x1,y0,y1,z0,z1]=indexBounds(origin.clone().addScalar(-reach),origin.clone().addScalar(reach));for(let z=z0;z<=z1;z++)for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){p.set(xs[x],ys[y],zs[z]).sub(origin);const v=[p.dot(side),p.dot(up),p.dot(rad)],k0=Math.hypot(...v.map((q,i)=>q/radii[i])),k1=Math.hypot(...v.map((q,i)=>q/(radii[i]*radii[i]))),d=k1?k0*(k0-1)/k1:-Math.min(...radii),i=z*N*N+y*N+x;voidField[i]=smoothMin(voidField[i],d,blend*.25);}}}
 const material=new THREE.MeshNormalMaterial(),mc=new MarchingCubes(N,material,false,false,maxTriangles);mc.isolation=0;let solidSamples=0;for(let i=0;i<field.length;i++){field[i]=Math.max(field[i],-voidField[i]);mc.field[i]=-field[i];if(field[i]<0)solidSamples++;}mc.update();if(mc.count/3>=maxTriangles)throw Error('Core surface exceeded triangle allocation');
 let geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(mc.positionArray.slice(0,mc.count*3),3));geometry.setAttribute('normal',new THREE.BufferAttribute(mc.normalArray.slice(0,mc.count*3),3));geometry.scale(size.x/2,size.y/2,size.z/2);geometry.translate(center.x,center.y,center.z);geometry.normalizeNormals();mc.geometry.dispose();material.dispose();const welded=weldSurface(geometry);geometry=welded.geometry;
 const positions=geometry.attributes.position,uv=new Float32Array(positions.count*2),growth=new Float32Array(positions.count),axisIds=new Float32Array(positions.count),colors=new Float32Array(positions.count*3),junction=new Float32Array(positions.count);
 for(let i=0;i<positions.count;i++){p.fromBufferAttribute(positions,i);let best=null,second=Infinity;for(const s of segments){const hit=capsule(p,s),d=Math.abs(hit.distance);if(!best||d<best.d){if(best&&best.s.axisId!==s.axisId)second=Math.min(second,best.d);best={s,hit,d};}else if(s.axisId!==best.s.axisId)second=Math.min(second,d);}const {s,hit}=best,t=s.t0+(s.t1-s.t0)*hit.q,v=s.axis.path.getLength()*t,radial=new THREE.Vector3(hit.x,hit.y,hit.z),angle=Math.atan2(radial.dot(s.bframe),radial.dot(s.n))-(s.axis.twist??0)*t;uv[i*2]=((angle/(Math.PI*2))%1+1)%1;uv[i*2+1]=v;growth[i]=s.axis.growthOffset+v;axisIds[i]=s.axisId;const color=new THREE.Color().setHSL((s.axisId*.61803398875)%1,.55,.52);colors.set([color.r,color.g,color.b],i*3);junction[i]=Number.isFinite(second)?1-clamp((second-best.d)/Math.max(.001,blend)):0;}
 geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));geometry.setAttribute('growthV',new THREE.BufferAttribute(growth,1));geometry.setAttribute('axisId',new THREE.BufferAttribute(axisIds,1));geometry.setAttribute('junction',new THREE.BufferAttribute(junction,1));geometry.computeBoundingSphere();geometry.computeBoundingBox();
 const topology=auditSurface(geometry);const stats={topology,backend:'unmodified official Three r170 MarchingCubes',resolution:N,voxelSize:step.toArray(),selectedAxes:selected.map(x=>x.a.id),capsules:segments.length,innerCapsules:cavitySegments.length,windows:holes.length,blend,hollowRatio,triangles:geometry.index.count/3,weldTolerance:welded.tolerance,collapsedMicroTriangles:welded.collapsed,solidSamples,axisIdentityTransferred:true,elapsedMs:performance.now()-begin,visualAcceptance:false};geometry.userData={kind:'derived-SDF-core',stats};return {geometry,stats,field,bounds,resolution:N,windows:holes,contains(point){const x=clamp(Math.round((point.x-bounds.min.x)/step.x),0,N-1),y=clamp(Math.round((point.y-bounds.min.y)/step.y),0,N-1),z=clamp(Math.round((point.z-bounds.min.z)/step.z),0,N-1);return field[z*N*N+y*N+x]<0;}};
}
