/* Branching coral R01 — visual reproduction, not original author's source file. */
(()=>{'use strict';const $=id=>document.getElementById(id),surface=$('canvas');
const M={mul(a,b){const r=new Float32Array(16);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)r[i+j*4]+=a[i+k*4]*b[k+j*4];return r},perspective(f,a,n,z){let t=1/Math.tan(f/2);return new Float32Array([t/a,0,0,0,0,t,0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0])},look(e,c){let norm=a=>{let d=Math.hypot(...a);return a.map(v=>v/d)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);let z=norm(e.map((v,i)=>v-c[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1])}};
const state=window.BranchStudyState={version:'branch-reproduction-r01-20261004',ready:false,error:null,output:2,growth:1,playing:false,skeleton:false,material:0,zoom:1,yaw:.03,pitch:.08,pan:[0,0],draws:0,meshRevision:0,busy:false,requested:0,completed:0,pausedByNavigation:false,stats:null,sourceFrames:{1:444,2:682},sourceMatched:false,originalAuthorRules:false};
let gl,program,vao,lineVao,count=0,lineCount=0,buffers=[],lineBuffer,worker,jobId=0,latestJob=null,playLast=0,frame=0,active=true,currentGraph=[],resolution=160,playFrom=0;const cache=new Map(),timers={};
const vs=`#version 300 es
precision highp float;layout(location=0)in vec3 position;layout(location=1)in vec3 normal;layout(location=2)in vec3 data;
uniform mat4 vp;out vec3 p;out vec3 n;out vec3 attr;void main(){p=position;n=normal;attr=data;gl_Position=vp*vec4(position,1.);}`;
const fs=`#version 300 es
precision highp float;in vec3 p;in vec3 n;in vec3 attr;uniform vec3 eye;uniform int mode;uniform int material;uniform int lines;out vec4 color;
float noise3(vec3 x){return .5+.22*sin(dot(x,vec3(1.7,2.3,1.1)))+.15*sin(dot(x,vec3(-3.1,1.6,2.5)))+.10*sin(dot(x,vec3(3.4,-1.3,4.9)));}
vec3 environment(vec3 r){vec3 c=mix(vec3(.085,.12,.19),vec3(.68,.80,.90),smoothstep(-.65,.85,r.y));float band=pow(max(0.,dot(r,normalize(vec3(-.7,1.,1.)))),10.);c+=band*vec3(1.,.97,.86)*1.1;float narrow=pow(max(0.,dot(r,normalize(vec3(1.,.6,-.6)))),35.);return c+narrow*vec3(.84,.93,1.)*2.;}
void main(){if(lines==1){color=vec4(.39,.81,.83,1.);return;}
 vec3 v=normalize(eye-p),N=normalize(n);float m=noise3(p*19.),f=noise3(p*75.);vec3 perturb=vec3(cos(p.x*83.+p.y*11.),sin(p.y*77.+p.z*13.),cos(p.z*91.+p.x*9.));N=normalize(N+.032*perturb);
 vec3 L=normalize(vec3(-1.8,2.8,1.8)),R=normalize(vec3(2.5,1.3,-.8));float diffuse=max(dot(N,L),0.),fill=max(dot(N,R),0.),fres=pow(1.-max(dot(v,N),0.),4.);
 vec3 base=mode==1?mix(vec3(.44,.52,.52),vec3(.79,.79,.74),m):mix(vec3(.05,.10,.42),vec3(.20,.31,.67),smoothstep(.16,.88,noise3(p*7.)));
 float pale=clamp(attr.x*.80+.10*attr.y,0.,.88);if(mode==2)base=mix(base,vec3(.88,.94,1.),pale);base*=.92+.12*f;
 float spe=pow(max(dot(N,normalize(v+L)),0.),mode==1?80.:34.);float back=pow(max(dot(-N,L),0.),1.6);
 vec3 c=base*(.16+.84*diffuse+.22*fill)+vec3(1.,.92,.84)*spe*.55;
 if(mode==1)c=mix(c,environment(reflect(-v,N)),.73)+vec3(.22,.22,.18)*fres;
 else{c+=base*.16*back;c+=environment(reflect(-v,N))*(.025+.12*fres);c+=vec3(.19,.035,.21)*pow(m,7.)*.32;}
 if(material==1){c=environment(reflect(-v,N))*(.46+.65*fres)+base*.12;}
 c=c/(c+.70);c=pow(max(c,0.),vec3(1./2.2));float alpha=material==1?clamp(.20+.75*fres,.18,.93):1.;color=vec4(c,alpha);
}`;
function fail(e){state.error=String(e?.stack||e);state.ready=false;stop();$('error').hidden=false;$('error').textContent='三维生成未完成：'+state.error;report()}
function compile(type,text){let s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const uniforms={};function setup(){gl=surface.getContext('webgl2',{alpha:false,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2不可用');program=gl.createProgram();for(const [t,s]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const sh=compile(t,s);gl.attachShader(program,sh)}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));for(const n of ['vp','eye','mode','material','lines'])uniforms[n]=gl.getUniformLocation(program,n);
 vao=gl.createVertexArray();gl.bindVertexArray(vao);for(let i=0;i<3;i++){const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,0,0)}lineVao=gl.createVertexArray();gl.bindVertexArray(lineVao);lineBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,lineBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.disableVertexAttribArray(1);gl.disableVertexAttribArray(2);gl.bindVertexArray(null);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
 surface.addEventListener('webglcontextlost',e=>{e.preventDefault();fail(Error('图形上下文丢失；没有使用截图替代'))});
 const blob=URL.createObjectURL(new Blob(['('+coralWorkerMain.toString()+')()'],{type:'application/javascript'}));worker=new Worker(blob);URL.revokeObjectURL(blob);worker.onerror=e=>fail(e.message);worker.onmessage=e=>{state.busy=false;let m=e.data;if(m.error){fail(m.error);return}state.completed++;cache.set(m.key||state.runningKey,m);if(cache.size>3)cache.delete(cache.keys().next().value);if(m.stats.mode===state.output&&(state.playing||Math.abs(m.stats.growth-state.growth)<.0015))accept(m);if(latestJob){const j=latestJob;latestJob=null;submit(j)}};
 requestMesh();}
function accept(m){gl.bindVertexArray(vao);[m.positions,m.normals,m.attrs].forEach((a,i)=>{gl.bindBuffer(gl.ARRAY_BUFFER,buffers[i]);gl.bufferData(gl.ARRAY_BUFFER,a,gl.STATIC_DRAW)});count=m.positions.length/3;gl.bindVertexArray(lineVao);gl.bindBuffer(gl.ARRAY_BUFFER,lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,m.lines,gl.STATIC_DRAW);lineCount=m.lines.length/3;gl.bindVertexArray(null);state.stats=m.stats;state.geometryHash=hashArray(m.positions);state.graphHash=hashArray(new Float32Array(m.graph.flatMap(b=>b.c)));currentGraph=m.graph;state.meshRevision++;state.ready=true;$('busy').hidden=true;draw();renderUI();report()}
function hashArray(a){let h=2166136261;for(let i=0;i<a.length;i+=7){let x=Math.round(a[i]*1e5);h=Math.imul(h^x,16777619)}return(h>>>0).toString(16)}
function submit(j){state.busy=true;state.runningKey=j.key;state.requested++;worker.postMessage(j)}
function requestMesh(){if(!worker)return;const t=Math.round(state.growth*1000)/1000,j={mode:state.output,seed:73403,spread:1,growth:t,resolution,requestId:++jobId};j.key=[j.mode,t,resolution].join(':');if(cache.has(j.key)){accept(cache.get(j.key));return}if(state.busy){latestJob=j;return}$('busy').hidden=false;submit(j)}
function renderUI(){document.querySelectorAll('[data-output]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.output)===state.output);b.setAttribute('aria-pressed',String(Number(b.dataset.output)===state.output))});$('growth').value=state.growth;$('percent').textContent=Math.round(state.growth*100)+'%';$('play').textContent=state.playing?'暂停生长':'重播生长';$('skeleton').classList.toggle('active',state.skeleton);$('glass').classList.toggle('active',state.material===1);$('zoom').textContent=state.zoom.toFixed(1)+'×';$('title').textContent=state.output===1?'输出一 · 基础分叉':'输出二 · 延展成簇';$('sourceLabel').textContent=state.output===1?'原片 · 中间效果 14.800 s / F0444':'原片 · 延展制作 22.733 s / F0682';if($('refImage').dataset.output!==String(state.output)){$('refImage').src='refs/output-'+state.output+'.webp';$('refImage').dataset.output=state.output;}$('refImage').alt='用户原片参考截帧，非学生输出';$('notes').textContent=state.output===1?'对应灰底银白分叉团簇：先长主轴，再从已形成的端部分出子枝。':'对应延展段的浅蓝扇状分枝：保留三组起始枝体，增加圆钝端头、厚度与立体分枝。';if(state.stats){$('stats').textContent=state.stats.activeBranches+' / '+state.stats.totalBranches+' 条已生长轴 · '+state.stats.buildMs+' ms / 本次表面更新';$('generatedAt').textContent='已生成 '+Math.round(state.stats.growth*100)+'%'} }
function draw(){if(!gl||!active||document.hidden)return;let r=surface.getBoundingClientRect(),d=window.devicePixelRatio||1;const w=Math.max(1,Math.ceil(r.width*d)),h=Math.max(1,Math.ceil(r.height*d));if(w!==surface.width||h!==surface.height){surface.width=w;surface.height=h}gl.viewport(0,0,w,h);const bg=state.output===1?[.68,.69,.68]:[.005,.009,.014];gl.clearColor(...bg,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);let dist=4.9/state.zoom,cp=Math.cos(state.pitch),eye=[dist*Math.sin(state.yaw)*cp+state.pan[0],dist*Math.sin(state.pitch)+state.pan[1]-.05,dist*Math.cos(state.yaw)*cp],target=[state.pan[0],state.pan[1]-.05,0];gl.uniformMatrix4fv(uniforms.vp,false,M.mul(M.perspective(Math.PI/4,w/h,.01,100),M.look(eye,target)));gl.uniform3fv(uniforms.eye,eye);gl.uniform1i(uniforms.mode,state.output);gl.uniform1i(uniforms.material,state.material);gl.uniform1i(uniforms.lines,state.skeleton?1:0);
 if(state.skeleton){gl.bindVertexArray(lineVao);gl.disable(gl.CULL_FACE);gl.drawArrays(gl.LINES,0,lineCount);gl.enable(gl.CULL_FACE)}
 else{gl.bindVertexArray(vao);if(state.material===1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.cullFace(gl.FRONT);gl.drawArrays(gl.TRIANGLES,0,count);gl.cullFace(gl.BACK);gl.drawArrays(gl.TRIANGLES,0,count);gl.depthMask(true);gl.disable(gl.BLEND)}else{gl.drawArrays(gl.TRIANGLES,0,count)}}
 state.draws++;state.resolution=[w,h];state.cssSize=[r.width,r.height];state.dpr=d;let e=gl.getError();if(e!==gl.NO_ERROR)fail(Error('WebGL '+e));}
function stop(){state.playing=false;playLast=0;if(frame)cancelAnimationFrame(frame);frame=0;renderUI()}
function tick(ms){frame=0;if(!active||document.hidden){stop();return}if(!state.playing)return;if(playLast){state.growth=Math.min(1,state.growth+(ms-playLast)/18000)}playLast=ms;if(!state.busy)requestMesh();renderUI();if(state.growth===1){stop();requestMesh()}else frame=requestAnimationFrame(tick)}
function seek(t){stop();state.growth=Math.max(0,Math.min(1,Number(t)||0));latestJob=null;requestMesh();renderUI()}
function changeOutput(v){stop();state.output=Number(v)===1?1:2;state.material=0;state.skeleton=false;state.growth=1;latestJob=null;requestMesh();renderUI()}
function resetCamera(){state.yaw=.03;state.pitch=.08;state.zoom=1;state.pan=[0,0];renderUI();draw()}
function setActive(v){active=!!v;state.pausedByNavigation=!active;if(!active)stop();else draw()}
function report(){if(parent!==window)parent.postMessage({type:'coral:branch-state',ready:state.ready,error:state.error,version:state.version},location.origin)}
const pointers=new Map();let pinch=null;surface.style.touchAction='none';surface.addEventListener('pointerdown',e=>{e.preventDefault();surface.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);pinch=null});surface.addEventListener('pointermove',e=>{const prev=pointers.get(e.pointerId);if(!prev)return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const[a,b]=[...pointers.values()],dist=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)state.zoom=Math.max(.35,Math.min(20,state.zoom*dist/pinch));pinch=dist}else if(e.shiftKey||e.buttons===2){state.pan[0]-=(e.clientX-prev[0])*.004/state.zoom;state.pan[1]+=(e.clientY-prev[1])*.004/state.zoom}else{state.yaw+=(e.clientX-prev[0])*.006;state.pitch=Math.max(-1.4,Math.min(1.4,state.pitch+(e.clientY-prev[1])*.006))}renderUI();draw()});for(const n of ['pointerup','pointercancel'])surface.addEventListener(n,e=>{pointers.delete(e.pointerId);pinch=null});surface.addEventListener('contextmenu',e=>e.preventDefault());surface.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.35,Math.min(20,state.zoom*Math.exp(-e.deltaY*.0015)));renderUI();draw()},{passive:false});surface.addEventListener('dblclick',resetCamera);
$('play').onclick=()=>{if(state.playing){stop();return}state.playing=true;if(state.growth>=.999)state.growth=0;playLast=0;frame=requestAnimationFrame(tick);renderUI()};$('growth').oninput=()=>seek($('growth').value);$('rewind').onclick=()=>seek(0);$('mature').onclick=()=>seek(1);document.querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>changeOutput(b.dataset.output));$('camera').onclick=resetCamera;$('skeleton').onclick=()=>{state.skeleton=!state.skeleton;renderUI();draw()};$('glass').onclick=()=>{state.material=state.material===1?0:1;renderUI();draw()};$('teacher').onclick=()=>{$('reference').hidden=!$('reference').hidden;$('teacher').classList.toggle('active',!$('reference').hidden);draw()};$('closeRef').onclick=()=>{$('reference').hidden=true;$('teacher').classList.remove('active');draw()};$('quality').onchange=()=>{resolution=Number($('quality').value);requestMesh()};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.student').requestFullscreen();draw()}catch(e){$('stats').textContent='此环境不允许全屏；仍可在主窗口观察。'}};document.addEventListener('fullscreenchange',draw);$('save').onclick=()=>{draw();const a=document.createElement('a');a.download='branch-output-'+state.output+'-'+Math.round(state.growth*100)+'.png';a.href=surface.toDataURL('image/png');a.click()};$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({schema:'coral-branch-visual-reproduction/1',state,branches:currentGraph,source:'user supplied video 24.4s',originalParametersKnown:false},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='branch-graph-output-'+state.output+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('back').onclick=()=>{stop();if(parent!==window)parent.postMessage({type:'coral:home'},location.origin);else location.href='../#view=home'};
window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.type==='coral:active')setActive(e.data.active)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else draw()});window.addEventListener('resize',draw);new ResizeObserver(draw).observe(surface);window.BranchStudy={state,seek,changeOutput,resetCamera,draw,setActive,graph:()=>currentGraph,pixelSignature(){if(!gl)return null;const a=new Uint8Array(surface.width*surface.height*4);gl.readPixels(0,0,surface.width,surface.height,gl.RGBA,gl.UNSIGNED_BYTE,a);let h=2166136261;for(let i=0;i<a.length;i+=19)h=Math.imul(h^a[i],16777619);return(h>>>0).toString(16)}};try{renderUI();setup();if(parent!==window)parent.postMessage({type:'coral:branch-ready'},location.origin)}catch(e){fail(e)}
})();
