import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const wrap=document.querySelector('#canvas-wrap'),loading=document.querySelector('#loading'),loadingState=document.querySelector('#loading-state'),errorCard=document.querySelector('#error');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,fract=x=>x-Math.floor(x);
const smoothstep=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
const hash=(x,z,s=0)=>fract(Math.sin(x*127.1+z*311.7+s*74.7)*43758.5453123);
function noise2(x,z,s=0){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,ux=fx*fx*(3-2*fx),uz=fz*fz*(3-2*fz),a=hash(ix,iz,s),b=hash(ix+1,iz,s),c=hash(ix,iz+1,s),d=hash(ix+1,iz+1,s);return mix(mix(a,b,ux),mix(c,d,ux),uz)}
function fbm2(x,z,s=0){let sum=0,amp=.53,freq=1;for(let i=0;i<5;i++){sum+=amp*noise2(x*freq,z*freq,s+i*17);freq*=2.03;amp*=.5}return sum/.97}
function angleDelta(a,b){let d=(a-b+Math.PI)%(Math.PI*2)-Math.PI;if(d< -Math.PI)d+=Math.PI*2;return d}

const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.3,3500);camera.position.set(302,76,470);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;wrap.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,78,-115);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=75;controls.maxDistance=1150;controls.minPolarAngle=.18;controls.maxPolarAngle=Math.PI*.485;controls.screenSpacePanning=false;controls.zoomToCursor=true;controls.update();
const hemi=new THREE.HemisphereLight(0xd8f0ff,0x526138,2.15);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffedc0,4.4);sun.position.set(470,680,390);sun.target.position.set(0,65,-120);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-650;sun.shadow.camera.right=650;sun.shadow.camera.top=650;sun.shadow.camera.bottom=-650;sun.shadow.camera.near=100;sun.shadow.camera.far=1600;sun.shadow.bias=-.00016;sun.shadow.normalBias=.65;scene.add(sun,sun.target);
const fill=new THREE.DirectionalLight(0xaed3e8,1.05);fill.position.set(-380,250,-420);scene.add(fill);
const world=new THREE.Group();scene.add(world);const towerMeshes=[],caveMeshes=[];
const display={rockLight:1,green:1,stain:1,detail:1,sun:1,mode:'clear'};

function makeRockMaterial(){const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.82,metalness:0,envMapIntensity:.5});material.onBeforeCompile=shader=>{shader.uniforms.uRockLight={value:display.rockLight};shader.uniforms.uGreen={value:display.green};shader.uniforms.uStain={value:display.stain};shader.uniforms.uDetail={value:display.detail};shader.vertexShader=shader.vertexShader.replace('#include <common>',`#include <common>\nattribute float aWetLM;attribute float aStainLM;attribute float aMossLM;attribute float aReliefLM;varying float vWetLM;varying float vStainLM;varying float vMossLM;varying float vReliefLM;varying vec3 vWorldPosLM;`).replace('#include <worldpos_vertex>',`#include <worldpos_vertex>\nvWetLM=aWetLM;vStainLM=aStainLM;vMossLM=aMossLM;vReliefLM=aReliefLM;vWorldPosLM=worldPosition.xyz;`);shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\nuniform float uRockLight;uniform float uGreen;uniform float uStain;uniform float uDetail;varying float vWetLM;varying float vStainLM;varying float vMossLM;varying float vReliefLM;varying vec3 vWorldPosLM;float lmhash(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float lmnoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(lmhash(i+vec3(0,0,0)),lmhash(i+vec3(1,0,0)),f.x),mix(lmhash(i+vec3(0,1,0)),lmhash(i+vec3(1,1,0)),f.x),f.y),mix(mix(lmhash(i+vec3(0,0,1)),lmhash(i+vec3(1,0,1)),f.x),mix(lmhash(i+vec3(0,1,1)),lmhash(i+vec3(1,1,1)),f.x),f.y),f.z);}float lmfbm(vec3 p){float s=0.0,a=.55;for(int i=0;i<4;i++){s+=a*lmnoise(p);p=p*2.03+13.7;a*=.5;}return s;}`).replace('#include <color_fragment>',`#include <color_fragment>\nfloat macroN=lmfbm(vWorldPosLM*.018);float grain=lmfbm(vWorldPosLM*.115+vec3(9.1,1.7,4.3));float pits=1.0-abs(lmnoise(vWorldPosLM*.29)-.5)*2.0;float relief=clamp(vReliefLM,0.0,1.0);float detailMix=clamp((grain-.5)*.32*uDetail+(pits-.5)*.12*uDetail,-.18,.18);diffuseColor.rgb*=(uRockLight+detailMix);vec3 calcite=vec3(.77,.79,.74);diffuseColor.rgb=mix(diffuseColor.rgb,calcite,clamp((macroN-.72)*.28*relief,0.0,.12));float moss=clamp(vMossLM*uGreen*(.8+.3*macroN),0.0,1.0);vec3 mossDark=vec3(.055,.145,.075),mossLight=vec3(.19,.33,.12);diffuseColor.rgb=mix(diffuseColor.rgb,mix(mossDark,mossLight,grain),moss*.72);float stain=clamp(vStainLM*uStain*(.82+.4*(1.0-grain)),0.0,1.0);vec3 stainCol=mix(vec3(.055,.065,.052),vec3(.018,.026,.021),stain);diffuseColor.rgb=mix(diffuseColor.rgb,stainCol,stain*.92);float wet=clamp(vWetLM,0.0,1.0);diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*.54,wet*.56);`).replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>\nroughnessFactor=clamp(roughnessFactor-(vWetLM*.52)+(1.0-vReliefLM)*.05,.22,1.0);`);material.userData.shader=shader};material.customProgramCacheKey=()=> 'landscape-mother-rock-v016-3';return material}
const rockMaterial=makeRockMaterial();
const caveMaterial=new THREE.MeshStandardMaterial({color:0x08110d,roughness:.98,metalness:0,side:THREE.DoubleSide});
const caveLipMaterial=new THREE.MeshStandardMaterial({color:0x35403a,roughness:.92,metalness:0,side:THREE.DoubleSide});

function makeTowerGeometry(spec){const seg=spec.segments||180,rings=spec.rings||96,positions=[],colors=[],wet=[],stain=[],moss=[],relief=[],indices=[],phase1=spec.seed*1.371,phase2=spec.seed*2.173,cliffPlanes=spec.cliffs||[],grooves=spec.grooves||[],cave=spec.cave||null;
for(let j=0;j<rings;j++){const t=j/(rings-1)*.985,y=spec.baseY+spec.height*t,leanEase=smoothstep(.1,.92,t),centerX=spec.x+spec.leanX*leanEase+Math.sin(t*5.2+phase1)*spec.height*.006,centerZ=spec.z+spec.leanZ*leanEase+Math.sin(t*4.1+phase2)*spec.height*.005;let profile;if(t<.10)profile=mix(1.09,1,smoothstep(0,.10,t));else if(t<.62)profile=mix(1,.92,smoothstep(.10,.62,t));else if(t<.84)profile=mix(.92,.49,smoothstep(.62,.84,t));else profile=mix(.49,.045,smoothstep(.84,.985,t));
for(let i=0;i<seg;i++){const a=i/seg*Math.PI*2,nHarm=1+Math.sin(a*3+phase1)*.068+Math.sin(a*5-phase2)*.043+Math.sin(a*9+phase1*.7+t*2.1)*.020+Math.sin(a*17-phase2*.4+t*7)*.010;let rn=profile*nHarm,cliffMask=0;for(const plane of cliffPlanes){const d=angleDelta(a,plane.angle),ad=Math.abs(d);if(ad<plane.width){const angularW=smoothstep(plane.width,plane.width*.62,ad),verticalW=smoothstep(plane.low-.05,plane.low+.04,t)*(1-smoothstep(plane.high-.05,plane.high+.04,t)),w=angularW*verticalW,c=Math.max(.18,Math.cos(d)),planeR=plane.distance/c,clipped=Math.min(rn,planeR);rn=mix(rn,clipped,w);cliffMask=Math.max(cliffMask,w)}}let grooveMask=0;for(const groove of grooves){const meander=groove.angle+Math.sin(t*groove.freq+groove.phase)*groove.meander,d=angleDelta(a,meander),g=Math.exp(-(d*d)/(groove.sigma*groove.sigma)),verticalW=smoothstep(.08,.20,t)*(1-smoothstep(.72,.94,t));rn-=groove.depth*g*verticalW*(.76+.24*Math.sin(t*23+groove.phase));grooveMask=Math.max(grooveMask,g*verticalW)}let cavityMask=0;if(cave){const d=angleDelta(a,cave.angle),gA=Math.exp(-(d*d)/(cave.angularSigma*cave.angularSigma)),gY=Math.exp(-Math.pow((t-cave.t)/cave.verticalSigma,2));cavityMask=gA*gY;rn-=cave.recess*cavityMask}const ledge=Math.sin(y*.74+a*1.9+phase1)*.008+Math.sin(y*1.57-a*3.2+phase2)*.004,rough=(fbm2(a*2.3+spec.seed,t*13.7,spec.seed)-.5)*(.018+.018*cliffMask)+(noise2(i*.14,j*.12,spec.seed+91)-.5)*.009;rn=Math.max(.025,rn*(1+ledge+rough));const rx=spec.radiusX*rn,rz=spec.radiusZ*rn;let px=centerX+Math.cos(a)*rx,pz=centerZ+Math.sin(a)*rz,py=y;if(t>.82){const crown=smoothstep(.82,.985,t);py+=crown*spec.height*(.017*Math.sin(a*2+phase1)+.010*Math.sin(a*5-phase2))}positions.push(px,py,pz);
const exposed=clamp(.46+cliffMask*.48+grooveMask*.24+t*.12-cavityMask*.15,0,1),warm=fbm2(px*.019,pz*.019,spec.seed+130),calcite=fbm2(px*.073+17,py*.061,spec.seed+41),iron=smoothstep(.67,.91,fbm2(px*.033,py*.047+pz*.012,spec.seed+66))*exposed*.42,veg=clamp((1-cliffMask*.82)*(1-exposed*.55)*smoothstep(.58,.96,fbm2(px*.015,pz*.015,spec.seed+9))+(1-t)*.06,0,.76),mossV=clamp((grooveMask*.42+cavityMask*.72+(1-exposed)*.24)*smoothstep(.47,.82,fbm2(px*.052,py*.041,spec.seed+17)),0,1),stainV=clamp(grooveMask*.95+cavityMask*.88+smoothstep(.81,.94,fbm2(a*1.2,t*7.3,spec.seed+23))*grooveMask,0,1),wetV=clamp(cavityMask*.82+grooveMask*.45*(1-t)+mossV*.22,0,1);let base=new THREE.Color(),coolRock=new THREE.Color(0x89918d),warmRock=new THREE.Color(0xa09580),lightRock=new THREE.Color(0xbfc0b3);base.copy(coolRock).lerp(warmRock,clamp((warm-.28)*1.05,0,1));base.lerp(lightRock,clamp((calcite-.67)*.48,0,.20));if(iron>0)base.lerp(new THREE.Color(0x8d6241),iron);if(veg>0)base.lerp(new THREE.Color(0x264b25),veg*.86);colors.push(base.r,base.g,base.b);wet.push(wetV);stain.push(stainV);moss.push(mossV+veg*.35);relief.push(clamp(exposed+cliffMask*.28,0,1))}}
for(let j=0;j<rings-1;j++)for(let i=0;i<seg;i++){const ni=(i+1)%seg,a=j*seg+i,b=j*seg+ni,c=(j+1)*seg+i,d=(j+1)*seg+ni;indices.push(a,c,b,b,c,d)}const bottom=positions.length/3;positions.push(spec.x,spec.baseY-2.2,spec.z);colors.push(.22,.27,.21);wet.push(0);stain.push(0);moss.push(.2);relief.push(.4);for(let i=0;i<seg;i++)indices.push(bottom,(i+1)%seg,i);const topRingStart=(rings-1)*seg,apex=positions.length/3;positions.push(spec.x+spec.leanX+spec.apexOffsetX,spec.baseY+spec.height+spec.apexExtra,spec.z+spec.leanZ+spec.apexOffsetZ);colors.push(.64,.64,.58);wet.push(0);stain.push(0);moss.push(.08);relief.push(1);for(let i=0;i<seg;i++)indices.push(topRingStart+i,apex,topRingStart+(i+1)%seg);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.setAttribute('aWetLM',new THREE.Float32BufferAttribute(wet,1));geometry.setAttribute('aStainLM',new THREE.Float32BufferAttribute(stain,1));geometry.setAttribute('aMossLM',new THREE.Float32BufferAttribute(moss,1));geometry.setAttribute('aReliefLM',new THREE.Float32BufferAttribute(relief,1));geometry.setIndex(indices);geometry.computeVertexNormals();geometry.computeBoundingSphere();return geometry}

function addCave(spec,towerGroup){if(!spec.cave)return;const c=spec.cave,t=c.t,profile=t<.10?mix(1.09,1,smoothstep(0,.10,t)):mix(1,.92,smoothstep(.10,.62,t)),a=c.angle,x=spec.x+Math.cos(a)*spec.radiusX*profile*.79,z=spec.z+Math.sin(a)*spec.radiusZ*profile*.79,y=spec.baseY+spec.height*t,outward=new THREE.Vector3(Math.cos(a),0,Math.sin(a)),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),outward);const mouth=new THREE.Mesh(new THREE.CircleGeometry(1,64),caveMaterial);mouth.position.set(x,y,z);mouth.quaternion.copy(q);mouth.scale.set(c.width*.5,c.height*.5,1);mouth.translateZ(-.9);mouth.renderOrder=2;towerGroup.add(mouth);caveMeshes.push(mouth);const inner=new THREE.Mesh(new THREE.CircleGeometry(1,64),new THREE.MeshBasicMaterial({color:0x020503,side:THREE.DoubleSide}));inner.position.copy(mouth.position);inner.quaternion.copy(q);inner.scale.set(c.width*.34,c.height*.34,1);inner.translateZ(-2.5);towerGroup.add(inner);const lip=new THREE.Mesh(new THREE.TorusGeometry(1,.085,10,72),caveLipMaterial);lip.position.set(x,y,z);lip.quaternion.copy(q);lip.scale.set(c.width*.54,c.height*.54,1);lip.translateZ(.2);towerGroup.add(lip)}
function makeGround(){const w=1200,d=980,sx=180,sz=148,g=new THREE.PlaneGeometry(w,d,sx,sz);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i)-135,broad=(fbm2(x*.0034,z*.0034,9)-.5)*5.5,fine=(fbm2(x*.018,z*.018,27)-.5)*1.3,channel=Math.exp(-Math.pow((z+50+Math.sin(x*.006)*42)/35,2))*1.7,y=broad+fine-channel;p.setXYZ(i,x,y,z);const n=fbm2(x*.013,z*.013,43),fields=Math.sin(x*.024)*Math.sin(z*.019)*.5+.5,soil=smoothstep(.75,.94,fbm2(x*.031,z*.031,77)),c1=new THREE.Color(0x617f3f),c2=new THREE.Color(0x8e9c45),c3=new THREE.Color(0x8a7048),col=c1.lerp(c2,clamp(n*.78+fields*.2,0,1)).lerp(c3,soil*.42+channel*.04);colors.push(col.r,col.g,col.b)}g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();const m=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.97,metalness:0}),mesh=new THREE.Mesh(g,m);mesh.receiveShadow=true;return mesh}
loadingState.textContent='建立平原与孤立峰脚';world.add(makeGround());
const towerSpecs=[
{id:'主峰',x:-35,z:-78,baseY:1.2,height:186,radiusX:48,radiusZ:43,seed:11,leanX:12,leanZ:-8,apexOffsetX:3,apexOffsetZ:-2,apexExtra:4,cliffs:[{angle:.28,width:.70,distance:.70,low:.08,high:.76},{angle:2.68,width:.55,distance:.76,low:.16,high:.69}],grooves:[{angle:-.28,sigma:.075,depth:.105,freq:8.8,phase:.2,meander:.065},{angle:.83,sigma:.055,depth:.085,freq:11.2,phase:1.7,meander:.048},{angle:2.15,sigma:.068,depth:.095,freq:9.6,phase:3.1,meander:.055},{angle:-2.18,sigma:.052,depth:.072,freq:13.1,phase:.8,meander:.046}],cave:{angle:.47,t:.105,angularSigma:.19,verticalSigma:.075,recess:.26,width:25,height:18}},
{id:'西侧峰',x:-225,z:-196,baseY:-.4,height:143,radiusX:43,radiusZ:37,seed:29,leanX:-8,leanZ:2,apexOffsetX:-2,apexOffsetZ:1,apexExtra:2,cliffs:[{angle:-.2,width:.64,distance:.73,low:.12,high:.72},{angle:-2.55,width:.46,distance:.79,low:.20,high:.67}],grooves:[{angle:.1,sigma:.065,depth:.09,freq:9.2,phase:2.4,meander:.05},{angle:1.55,sigma:.057,depth:.075,freq:12.2,phase:.7,meander:.043},{angle:-1.62,sigma:.06,depth:.082,freq:10.4,phase:1.6,meander:.05}],cave:{angle:-.12,t:.11,angularSigma:.20,verticalSigma:.077,recess:.24,width:19,height:15}},
{id:'东侧峰',x:198,z:-208,baseY:.6,height:164,radiusX:45,radiusZ:39,seed:47,leanX:7,leanZ:-4,apexOffsetX:2,apexOffsetZ:2,apexExtra:3,cliffs:[{angle:2.95,width:.62,distance:.71,low:.09,high:.77},{angle:1.25,width:.43,distance:.77,low:.2,high:.69}],grooves:[{angle:3.02,sigma:.066,depth:.10,freq:9.7,phase:.9,meander:.052},{angle:1.86,sigma:.055,depth:.075,freq:12.7,phase:2.2,meander:.045},{angle:-.75,sigma:.058,depth:.08,freq:11.1,phase:4.1,meander:.05}],cave:{angle:2.85,t:.10,angularSigma:.19,verticalSigma:.073,recess:.23,width:21,height:16}},
{id:'西北峰',x:-390,z:-408,baseY:1.1,height:108,radiusX:35,radiusZ:31,seed:71,leanX:5,leanZ:-3,apexOffsetX:1,apexOffsetZ:-1,apexExtra:1,cliffs:[{angle:.42,width:.56,distance:.74,low:.1,high:.72}],grooves:[{angle:.35,sigma:.063,depth:.088,freq:8.4,phase:2.7,meander:.05},{angle:-1.8,sigma:.055,depth:.07,freq:12.4,phase:1.1,meander:.04}]},
{id:'东北峰',x:360,z:-426,baseY:-.2,height:121,radiusX:38,radiusZ:33,seed:93,leanX:-6,leanZ:3,apexOffsetX:-1,apexOffsetZ:1,apexExtra:2,cliffs:[{angle:2.75,width:.58,distance:.72,low:.13,high:.74}],grooves:[{angle:2.78,sigma:.061,depth:.09,freq:9.3,phase:1.4,meander:.05},{angle:.7,sigma:.055,depth:.07,freq:13.3,phase:3.2,meander:.043}]}
];
loadingState.textContent='雕刻连续陡壁、尖峰冠与水蚀沟';for(const spec of towerSpecs){const group=new THREE.Group(),geometry=makeTowerGeometry(spec),mesh=new THREE.Mesh(geometry,rockMaterial);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={id:spec.id,height:spec.height,spec};group.add(mesh);addCave(spec,group);world.add(group);towerMeshes.push(mesh)}
const blockMat=rockMaterial.clone();blockMat.onBeforeCompile=rockMaterial.onBeforeCompile;blockMat.customProgramCacheKey=rockMaterial.customProgramCacheKey;for(let i=0;i<22;i++){const a=hash(i,1,41)*Math.PI*2,r=64+hash(i,2,91)*165,x=-35+Math.cos(a)*r,z=-78+Math.sin(a)*r,s=2.2+hash(i,3,33)*4.8,g=new THREE.DodecahedronGeometry(s,1),p=g.attributes.position,c=[],wetA=[],stainA=[],mossA=[],reliefA=[];for(let k=0;k<p.count;k++){const col=new THREE.Color(0x777e75).lerp(new THREE.Color(0x988a72),hash(k,i,7)*.4);c.push(col.r,col.g,col.b);wetA.push(0);stainA.push(0);mossA.push(hash(k,i,3)*.2);reliefA.push(.8)}g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setAttribute('aWetLM',new THREE.Float32BufferAttribute(wetA,1));g.setAttribute('aStainLM',new THREE.Float32BufferAttribute(stainA,1));g.setAttribute('aMossLM',new THREE.Float32BufferAttribute(mossA,1));g.setAttribute('aReliefLM',new THREE.Float32BufferAttribute(reliefA,1));const m=new THREE.Mesh(g,blockMat);m.position.set(x,1+s*.65,z);m.rotation.set(hash(i,6,1)*2,hash(i,7,2)*2,hash(i,8,3)*2);m.castShadow=true;m.receiveShadow=true;world.add(m)}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),selection=document.querySelector('#selection'),selectionName=document.querySelector('#selection-name'),selectionValue=document.querySelector('#selection-value');let pointerDown=null;renderer.domElement.addEventListener('pointerdown',e=>{pointerDown={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(!pointerDown||Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)>8)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(towerMeshes,false)[0];if(hit){selectionName.textContent=hit.object.userData.id;selectionValue.textContent=`${hit.object.userData.height} m`;selection.classList.remove('hidden');setTimeout(()=>selection.classList.add('hidden'),2800)}});
const viewPresets={ground:{pos:new THREE.Vector3(302,76,470),target:new THREE.Vector3(0,78,-115)},cliff:{pos:new THREE.Vector3(112,67,178),target:new THREE.Vector3(-26,78,-84)},side:{pos:new THREE.Vector3(-470,98,74),target:new THREE.Vector3(-25,80,-150)},aerial:{pos:new THREE.Vector3(312,475,420),target:new THREE.Vector3(0,22,-145)}};let tween=null;function goView(name){const v=viewPresets[name];if(!v)return;tween={start:performance.now(),duration:900,fromP:camera.position.clone(),fromT:controls.target.clone(),toP:v.pos.clone(),toT:v.target.clone()};document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>goView(b.dataset.view)));document.querySelector('#reset').addEventListener('click',()=>goView('ground'));
let touring=false;const tourButton=document.querySelector('#tour');tourButton.addEventListener('click',()=>{touring=!touring;tourButton.classList.toggle('active',touring);tourButton.textContent=touring?'暂停':'巡览'});controls.addEventListener('start',()=>{if(touring){touring=false;tourButton.classList.remove('active');tourButton.textContent='巡览'}});
const panel=document.querySelector('#panel'),panelToggle=document.querySelector('#panel-toggle');function setPanel(open){panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));panelToggle.setAttribute('aria-expanded',String(open))}panelToggle.addEventListener('click',()=>setPanel(!panel.classList.contains('open')));document.querySelector('#panel-close').addEventListener('click',()=>setPanel(false));
function updateRockUniforms(){for(const mat of [rockMaterial,blockMat]){const shader=mat.userData.shader;if(shader){shader.uniforms.uRockLight.value=display.rockLight;shader.uniforms.uGreen.value=display.green;shader.uniforms.uStain.value=display.stain;shader.uniforms.uDetail.value=display.detail}}}
for(const [id,out,key] of [['rock-light','rock-light-output','rockLight'],['green','green-output','green'],['stain','stain-output','stain'],['sun','sun-output','sun'],['detail','detail-output','detail']]){const input=document.querySelector(`#${id}`),output=document.querySelector(`#${out}`);input.addEventListener('input',()=>{output.value=`${input.value}%`;display[key]=Number(input.value)/100;if(key==='sun'){sun.intensity=4.4*display.sun;fill.intensity=1.05*mix(.85,1.1,display.sun)}else updateRockUniforms()})}
document.querySelectorAll('[data-light]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-light]').forEach(b=>b.classList.toggle('active',b===button));display.mode=button.dataset.light;if(display.mode==='clear'){renderer.toneMappingExposure=1.18;sun.color.set(0xffedc0);sun.intensity=4.4*display.sun;hemi.intensity=2.15;fill.intensity=1.05}else if(display.mode==='neutral'){renderer.toneMappingExposure=1.04;sun.color.set(0xffffff);sun.intensity=3.5*display.sun;hemi.intensity=1.75;fill.intensity=.78}else{renderer.toneMappingExposure=1.12;sun.color.set(0xd8e6f4);sun.intensity=2.7*display.sun;hemi.intensity=2.25;fill.intensity=1.25;display.stain=Math.max(display.stain,1.2);document.querySelector('#stain').value=Math.round(display.stain*100);document.querySelector('#stain-output').value=`${Math.round(display.stain*100)}%`;updateRockUniforms()}}));
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(_){}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65))});
let previous=performance.now();function render(now){requestAnimationFrame(render);const dt=Math.min(.05,(now-previous)/1000);previous=now;if(tween){const t=clamp((now-tween.start)/tween.duration,0,1),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;camera.position.lerpVectors(tween.fromP,tween.toP,e);controls.target.lerpVectors(tween.fromT,tween.toT,e);if(t>=1)tween=null}if(touring&&!tween){const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),dt*.075);camera.position.copy(controls.target).add(offset)}controls.update();renderer.render(scene,camera)}requestAnimationFrame(render);
renderer.compile(scene,camera);loadingState.textContent='完成，正在进入贴地观察';setTimeout(()=>loading.classList.add('done'),500);window.__LANDSCAPE_READY__=true;window.__LANDSCAPE_VERSION__='V016-HERO-R1';window.__LANDSCAPE_STATS__={towers:towerSpecs.length,mainPeakHeightM:186,textureSampling:false,externalModels:false,images:false,visualApproved:false,productionReady:false};addEventListener('error',e=>{errorCard.textContent=`页面启动失败：${e.message||'未知错误'}`;errorCard.classList.remove('hidden')});
