import * as THREE from 'three';
// Source study only. No joint edits, invented jaw movement, topology changes or anatomical self-approval.
export function installHeadStudy(ctx){
 const {compiled,meshes,state,qa,scenes,cam,controls,regionTool,preset,getSurfaces,readSurface}=ctx,$=s=>document.querySelector(s);
 const el=$('#headEvidence'),data=JSON.parse(el.textContent);el.remove();
 const labels=['头部控制 Head','上颌控制 UpperJaw','下颌控制 LoweJaw','左眼控制 Eye.L','右眼控制 Eye.R','左侧控制 Side.L（鳃盖未核准）','右侧控制 Side.R（鳃盖未核准）'];
 const choice={index:-1,trail:false,weights:true};
 const panel=document.createElement('div');panel.className='section';panel.id='headPanel';
 panel.innerHTML='<h2>01D　头颌与眼区 · R007</h2><p class="sub">逐项学习原作者的控制关系。Side 不能直接命名为鳃盖；眼表面中心不是已测眼眶中心。</p><select id="headSelect" class="w100" aria-label="头部原控制"><option value="-1">全鱼 · 选择一个头部控制</option></select><div class="row"><button id="headFocus">放大头部</button><button id="headMaterial">原材质 / 权重</button></div><div class="row"><button id="headPeak">原动作最大偏转</button><button id="headTrail">控制轴轨迹</button></div><div class="row"><button id="headClear">恢复全鱼</button></div><p class="sub" id="headInfo">保留 7 个原控制、21 条原曲线、4 个眼表面观测点及 24 条口沿接口边。</p><pre id="headLive">播放原 Swim 或拖动底部时间条，查看原控制变换；没有增加新动作。</pre><details><summary>测量定义与未解问题</summary><p class="sub">小点标记作者控制枢轴和源眼表面的面积加权中心，不冒充真实骨骼或科学解剖标志。轴端是显示探针，不是鱼体特征点。局部角差相对原 clip 起点，使用 q 与 −q 等价的旋转；不是嘴部张开角。轨迹取原 209 个时刻。真实鱼长、年龄、鳃盖划分尚无核准数据。</p></details>';
 $('#canonicalPanel').before(panel);labels.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s;$('#headSelect').appendChild(o);});
 const axes=new THREE.AxesHelper(.035);axes.material.depthTest=false;axes.renderOrder=45;axes.matrixAutoUpdate=false;scenes[1].add(axes);
 const dots=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffbc6e,size:6,sizeAttenuation:false,depthTest:false}));dots.renderOrder=46;dots.frustumCulled=false;scenes[1].add(dots);
 const mouth=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x70e6d1,depthTest:false}));mouth.renderOrder=44;mouth.frustumCulled=false;scenes[1].add(mouth);
 const trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xffc16b,depthTest:false,transparent:true,opacity:.85}));trail.renderOrder=43;trail.frustumCulled=false;scenes[1].add(trail);[axes,dots,mouth,trail].forEach(x=>x.visible=false);
 function fill(o,a){const old=o.geometry.getAttribute('position');if(old&&old.array.length===a.length){old.array.set(a);old.needsUpdate=true;}else{o.geometry.dispose();o.geometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(a,3));}}
 function centroid(probe,surfs){const surf=surfs[probe.mesh],a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),ab=new THREE.Vector3(),ac=new THREE.Vector3(),sum=new THREE.Vector3();let area=0;for(const f of probe.sourceTriangles){const ids=surf.idx.subarray(f*3,f*3+3);a.fromArray(surf.p,ids[0]*3);b.fromArray(surf.p,ids[1]*3);c.fromArray(surf.p,ids[2]*3);const weight=ab.subVectors(b,a).cross(ac.subVectors(c,a)).length()*.5;sum.addScaledVector(a,weight/3).addScaledVector(b,weight/3).addScaledVector(c,weight/3);area+=weight;}return {areaCentroid:sum.divideScalar(area).toArray(),area};}
 const matrix=()=>compiled.nodes[data.controls[choice.index].sourceNode].matrixWorld;
 function axisTip(m){return new THREE.Vector3().setFromMatrixPosition(m).addScaledVector(new THREE.Vector3().setFromMatrixColumn(m,1).normalize(),.035).toArray();}
 function localAngle(n,q){return THREE.MathUtils.radToDeg(n.quaternion.clone().normalize().angleTo(new THREE.Quaternion().fromArray(q).normalize()));}
 function update(){if(choice.index<0)return;const def=data.controls[choice.index],node=compiled.nodes[def.sourceNode],m=matrix(),surfs=getSurfaces();if(!surfs.length)return;
  axes.matrix.copy(m);for(let k=0;k<3;k++){const length=new THREE.Vector3().setFromMatrixColumn(m,k).length();for(let row=0;row<3;row++)axes.matrix.elements[k*4+row]/=length;}axes.matrixWorldNeedsUpdate=true;
  const probes=data.probeDefinitions.map(p=>({id:p.id,...centroid(p,surfs)}));fill(dots,[...data.controls.flatMap(d=>new THREE.Vector3().setFromMatrixPosition(compiled.nodes[d.sourceNode].matrixWorld).toArray()),...probes.flatMap(p=>p.areaCentroid)]);
  const rim=[];for(const i of data.mouthInterfaceSeamIds){const s=regionTool.data.seams[i].a;for(const v of s.vertices)rim.push(...surfs[s.mesh].p.subarray(v*3,v*3+3));}fill(mouth,rim);axes.visible=dots.visible=mouth.visible=true;trail.visible=choice.trail;
  const q0=data.samples[0].nodes.find(n=>n.id===def.sourceNode).localTRS.rotation,angle=localAngle(node,q0);
  qa.headCurrent={sourceNode:def.sourceNode,sourceName:def.sourceName,time:state.time,rest:state.rest,canonicalMatrix:m.toArray(),localTRS:{translation:node.position.toArray(),rotation:node.quaternion.toArray(),scale:node.scale.toArray()},localAngleFromClipStartDeg:angle,eyeSurfaceProbes:probes,anatomicalApproval:false};
  const fmt=a=>a.map(x=>x.toFixed(6)).join(', ');$('#headLive').textContent=(state.rest?'源静息态':'原 Swim t='+state.time.toFixed(4)+' s')+'\n局部旋转差 '+angle.toFixed(5)+'°（不是张嘴角）\nT: '+fmt(node.position.toArray())+'\nQ xyzw: '+fmt(node.quaternion.toArray())+'\nS: '+fmt(node.scale.toArray())+'\n归一世界枢轴: '+fmt(new THREE.Vector3().setFromMatrixPosition(m).toArray());
 }
 function focus(){const p=regionTool.data.parts.find(p=>p.id==='head'),surfs=getSurfaces(),box=new THREE.Box3();p.sourceVertices.forEach(v=>box.expandByPoint(new THREE.Vector3().fromArray(surfs[p.mesh].p,v*3)));const center=box.getCenter(new THREE.Vector3()),dir=cam.position.clone().sub(controls.target).normalize();controls.target.copy(center);cam.position.copy(center).addScaledVector(dir,3);cam.zoom=2.25;cam.updateProjectionMatrix();controls.update();qa.headFocused=true;}
 function choose(index){if(index<-1||index>=data.controls.length)throw Error('Invalid head control');choice.index=index;$('#headSelect').value=index;qa.headSelected=index;if(index<0){[axes,dots,mouth,trail].forEach(x=>x.visible=false);return;}regionTool.restore();const def=data.controls[index];window.FISH_CANONICAL.choose(choice.weights?def.groupId:-1);fill(trail,data.samples.flatMap(s=>axisTip(new THREE.Matrix4().fromArray(s.nodes.find(n=>n.id===def.sourceNode).canonicalMatrix))));$('#headInfo').textContent=def.sourceName+' · 原 node '+def.sourceNode+' · 原父节点 '+def.parentNode+' · '+def.sourceTrackRefs.map(t=>t.property+': '+t.sourceKeyCount+'键').join(' / ')+'。'+(def.quaternionSignCrossings?'原四元数有 '+def.quaternionSignCrossings+' 次符号跳变，不等于眼球翻转。':'全体原曲线与混合权重保留。');update();}
 function clear(){choose(-1);window.FISH_CANONICAL.choose(-1);regionTool.restore();preset('side');}
 function peak(){if(choice.index<0)choose(2);const d=data.controls[choice.index],q0=new THREE.Quaternion().fromArray(data.samples[0].nodes.find(n=>n.id===d.sourceNode).localTRS.rotation).normalize();let best=data.samples[0],max=-1;for(const s of data.samples){const a=q0.angleTo(new THREE.Quaternion().fromArray(s.nodes.find(n=>n.id===d.sourceNode).localTRS.rotation).normalize());if(a>max){best=s;max=a;}}window.FISH.setTime(best.time);$('#time').value=best.time;$('#timeLabel').textContent=best.time.toFixed(3)+' s · 原动作样本';focus();qa.headPeakTime=best.time;}
 function audit(){const saved=choice.index;choice.index=-1;[axes,dots,mouth,trail].forEach(x=>x.visible=false);let sourceMax=0,candidateMax=0,probeMax=0,localMax=0;const ids=compiled.pkg.skeletonGraphs[0].jointNodes;ctx.beginExact();try{for(const s of [data.restSample,...data.samples]){ctx.seekExact(s.time??0,s.rest);const sourceSurface=readSurface(0),candidateSurface=getSurfaces();for(const n of s.nodes){const source=meshes[0][0].skeleton.bones[ids.indexOf(n.id)],candidate=compiled.nodes[n.id];n.canonicalMatrix.forEach((v,k)=>{sourceMax=Math.max(sourceMax,Math.abs(v-source.matrixWorld.elements[k]));candidateMax=Math.max(candidateMax,Math.abs(v-candidate.matrixWorld.elements[k]));});for(const [k,prop]of [['translation','position'],['scale','scale']])n.localTRS[k].forEach((v,j)=>localMax=Math.max(localMax,Math.abs(v-candidate[prop].toArray()[j])));const q=n.localTRS.rotation,actual=candidate.quaternion.toArray();localMax=Math.max(localMax,Math.min(Math.max(...q.map((v,k)=>Math.abs(v-actual[k]))),Math.max(...q.map((v,k)=>Math.abs(v+actual[k])))));}
 for(const probe of data.probeDefinitions){const expected=s.surfaceProbes.find(p=>p.id===probe.id).areaCentroid;for(const surfs of [sourceSurface,candidateSurface]){const actual=centroid(probe,surfs).areaCentroid;probeMax=Math.max(probeMax,Math.hypot(...actual.map((v,k)=>v-expected[k])));}}}}finally{ctx.endExact();choice.index=saved;if(saved>=0)update();}
 return {restSamples:1,clampedNonLoopSamples:data.samples.length,headControls:7,surfaceProbes:4,sourceMatrixMaxError:sourceMax,candidateMatrixMaxError:candidateMax,localTRSMaxError:localMax,surfaceCentroidMaxError:probeMax,threshold:1e-6,passed:Math.max(sourceMax,candidateMax,localMax,probeMax)<1e-6,biologicalApproval:false};}
 $('#headSelect').onchange=e=>choose(+e.target.value);$('#headFocus').onclick=()=>{if(choice.index<0)choose(0);focus();};$('#headMaterial').onclick=()=>{choice.weights=!choice.weights;if(choice.index>=0)choose(choice.index);};$('#headPeak').onclick=peak;$('#headTrail').onclick=()=>{choice.trail=!choice.trail;$('#headTrail').classList.toggle('active',choice.trail);if(choice.index<0)choose(2);update();};$('#headClear').onclick=clear;
 ['#regionSelect','#groupSelect','#jointSelect'].forEach(id=>$(id).addEventListener('change',()=>choose(-1)));
 qa.headStudy={version:data.version,headControls:7,sourceTracks:21,surfaceProbes:4,sourceTimes:209,sourceMotionOnly:true,landmarkApproval:false,sideNotPromotedToOperculum:true};const api={data,choice,choose,clear,focus,peak,update,audit};window.FISH_HEAD=api;return api;
}
