import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';
import {RADIX85_ALPHABET,decodeRadix85} from '../src/radix85-r07.js';
import {verifyBindings} from './validate-production-bindings-r09.mjs';
const require=createRequire(import.meta.url);let esbuild;try{esbuild=require('esbuild');}catch{esbuild=require('G:/Three.js/Human/Crab-Static-R05/node_modules/esbuild');}
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),task='FISH_EMBEDDED_PRODUCTION_KNOWLEDGE_R09_20261003',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const sourceHead=execFileSync('git',['-c','core.fsmonitor=false','rev-parse','HEAD'],{cwd:path.dirname(root),windowsHide:true}).toString().trim(),builtAt=new Date().toISOString();
export function encodeRadix85(bytes){const out=Buffer.alloc(Math.ceil(bytes.length/4)*5);let j=0;for(let i=0;i<bytes.length;i+=4){let v=0;for(let k=0;k<4;k++)v=v*256+(bytes[i+k]||0);for(let k=4;k>=0;k--){out[j+k]=RADIX85_ALPHABET.charCodeAt(v%85);v=Math.floor(v/85);}j+=5;}return out.toString('ascii');}
for(const n of [1,2,3,4,5,262143,262144,262145]){const input=crypto.randomBytes(n),round=await decodeRadix85(encodeRadix85(input),n);if(!Buffer.from(round).equals(input))throw Error('Radix85 exact-byte boundary test failed');}
const registry=JSON.parse(fs.readFileSync(path.join(root,'data/r07/registry.json'))),legacy=JSON.parse(fs.readFileSync(path.join(root,'data/r07/legacy-registry.json'))),items=registry.items.map(item=>({...item,source:JSON.parse(fs.readFileSync(path.join(root,'data',item.metadataFile))).source}));if(items.length!==5)throw Error('Five original sources required');
const payloads=[{id:'barracuda',bytes:fs.readFileSync(path.join(root,'data/r07',legacy.file)),sha256:legacy.sha256,format:'FBR7_GZIP'},...items.map(item=>({id:item.id,bytes:fs.readFileSync(path.join(root,'data',item.file)),sha256:item.sha256,format:item.format}))];
const onlineDir=path.join(root,'dist/online-r09'),assetDir=path.join(onlineDir,'assets');fs.mkdirSync(assetDir,{recursive:true});
const assets=payloads.map(p=>{const hash=sha(p.bytes);if(hash!==p.sha256)throw Error('Frozen source hash mismatch '+p.id);const file=`assets/${p.id}.${hash.slice(0,16)}.bin`;fs.writeFileSync(path.join(onlineDir,file),p.bytes);return {id:p.id,file,bytes:p.bytes.length,sha256:hash,format:p.format};});
const thumbnails=fs.readFileSync(path.join(root,'data/thumbnails-r03.json'),'utf8'),shots=JSON.parse(thumbnails).items,labels={barracuda:'海狼鱼',herring:'鲱鱼','tuna-yellow-label':'黄鳍标签金枪鱼','tuna-blue-label':'蓝鳍标签金枪鱼',colorful:'彩色珊瑚鱼',picasso:'毕加索标签鱼'};
const catalog=assets.map(({id})=>{const s=shots.find(s=>s.id===id);if(!s?.uri?.startsWith('data:image/'))throw Error('Source thumbnail missing');return `<button type="button" class="fish-choice" data-fish="${id}" aria-label="显示${labels[id]}的三维模型" aria-pressed="false"><img class="specimen-preview" width="512" height="256" src="${s.uri}" alt="" decoding="async" draggable="false"><span class="name">${labels[id]}</span></button>`;}).join('');
const bundle=await esbuild.build({entryPoints:[path.join(root,'src/app.js')],bundle:true,format:'iife',target:['chrome120'],minify:true,write:false,legalComments:'inline'}),template=fs.readFileSync(path.join(root,'src/workbench.template.html'),'utf8').replace('FISH_SCOREMAKER_STARTUP_R06','FISH_SCOREMAKER_KNOWLEDGE_R09').replace('FISH SCOREMAKER / R06','FISH SCOREMAKER / R09'),startup=fs.readFileSync(path.join(root,'src/startup-r06.js'),'utf8'),behavior=fs.readFileSync(path.join(root,'src/behavior.js'),'utf8');
const knowledge=JSON.parse(fs.readFileSync(path.join(root,'data/production-cards-r09.json'))),Knowledge=require(path.join(root,'src/production-knowledge-r09.js'));
if(knowledge.knowledgeVersion!==Knowledge.version||knowledge.cards.length!==assets.length||new Set(knowledge.cards.map(c=>c.id)).size!==assets.length)throw Error('Production registry mismatch');
const implementationErrors=verifyBindings(knowledge.implementationBindings,{required:true});if(implementationErrors.length)throw Error('Production functions changed: update stage knowledge before building '+JSON.stringify(implementationErrors));
for(const card of knowledge.cards){const result=Knowledge.validateCard(card),errors=verifyBindings(card.evidenceBindings,{required:true});if(!result.valid||errors.length)throw Error('Invalid/stale production evidence card '+card.id+': '+JSON.stringify({result,errors}));if(card.source.payloadSha256!==assets.find(a=>a.id===card.id)?.sha256)throw Error('Card bound to wrong source '+card.id);}
const knowledgeReceipt={version:Knowledge.version,coreSha256:sha(fs.readFileSync(path.join(root,'src/production-knowledge-r09.js'))),cardsSha256:sha(fs.readFileSync(path.join(root,'data/production-cards-r09.json'))),stageIds:Knowledge.stages.map(s=>s.id)};
const schooling=fs.readFileSync(path.join(root,'src/schooling-r08.js'),'utf8');
const encoded=new Map();for(const p of payloads){const text=encodeRadix85(p.bytes),round=await decodeRadix85(text,p.bytes.length);if(sha(round)!==p.sha256)throw Error('Whole-source inline byte roundtrip failed '+p.id);encoded.set(p.id,text);}
function carrier(p,online){const a=assets.find(a=>a.id===p.id);return `<script type="application/octet-stream" id="${p.id==='barracuda'?'barracudaModule':'score-'+p.id}" data-bytes="${p.bytes.length}" data-format="${p.format}"${p.id==='barracuda'?' data-encoding="fbr7-gzip-base64"':''}${online?` data-url="${a.file}" data-sha256="${a.sha256}"`:' data-inline-encoding="radix85-r07"'}>${online?'':encoded.get(p.id)}</script>`;}
function render(online){
 const carriers=payloads.filter(p=>p.id!=='barracuda').map(p=>carrier(p,online)).join('\n')+`\n<script type="application/json" id="manifest">${JSON.stringify({items,buildSourceHead:sourceHead,taskId:task,buildTime:builtAt,deliveryMode:online?'ONLINE_SELECTED_SOURCE':'STANDALONE_INLINE',sourceEncoding:'EXACT_BINARY_R07',productionKnowledge:knowledgeReceipt,assets:online?assets:[]}).replace(/</g,'\\u003c')}</script>`;
 const html=template.replace('__CATALOG_SHELL__',()=>catalog).replace('__STARTUP__',()=>startup).replace('__DATA_CARRIERS__',()=>carriers).replace('__THUMBNAILS__',()=>thumbnails.replace(/</g,'\\u003c')).replace('__BARRACUDA_MODULE__',()=>carrier(payloads[0],online)).replace('__BEHAVIOR__',()=>schooling+'\n'+behavior).replace('__APP_BUNDLE__',()=>bundle.outputFiles[0].text.replace(/<\/script/gi,'<\\/script'));
 if(/__(?:CATALOG_SHELL|STARTUP|DATA_CARRIERS|THUMBNAILS|BARRACUDA_MODULE|BEHAVIOR|APP_BUNDLE)__/.test(html))throw Error('Unresolved R09 build token');return html;
}
const offline=render(false),online=render(true);if(Buffer.byteLength(offline)>=104857600)throw Error('Standalone exceeds100MiB');if(Buffer.byteLength(online)>1200000)throw Error('Online entry not small enough');
fs.writeFileSync(path.join(root,'dist/KAOPU_FISH_SCOREMAKER_R09.html'),offline);fs.writeFileSync(path.join(onlineDir,'index.html'),online);
const receipt={taskId:task,builtAt,sourceHead,htmlSha256:sha(offline),htmlBytes:Buffer.byteLength(offline),onlineEntrySha256:sha(online),onlineEntryBytes:Buffer.byteLength(online),assets,totalAssetBytes:assets.reduce((n,a)=>n+a.bytes,0),legacyR14HtmlSha256:legacy.originalR14HtmlSha256,legacySourcePackageSha256:legacy.storedSourcePackageSha256,sourceSamplesAndEncodedImagesByteIdentical:true,sourceIds:assets.map(a=>a.id),thumbnailsSha256:sha(thumbnails),standaloneAllCoreResourcesInline:true,standaloneEncoding:'RADIX85_R07',wholeSourceInlineRoundtripVerified:true,onlineUsesSameOriginIntegrityCheckedSelectedSources:true,collectiveMotionKernel:'PARAMETERIZED_LOCAL_INTERACTION_R08',productionKnowledge:knowledgeReceipt,initialSource:'barracuda',unselectedSourcePreload:false,sourceModified:true,interactive3D:true,staticImageSubstitute:false,visualAcceptance:false,productionReady:false};
fs.writeFileSync(path.join(root,'evidence/R09_BUILD_RECEIPT.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
