import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),html=path.join(root,'dist/KAOPU_FIVE_FISH_R01.html'),report={createdAt:new Date().toISOString(),htmlSha256:crypto.createHash('sha256').update(fs.readFileSync(html)).digest('hex'),rows:[]};
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-angle=d3d11']});
try{const page=await browser.newPage();await page.goto(pathToFileURL(html).href,{timeout:120000});await page.waitForFunction(()=>__FIVE_FISH__?.ready,null,{timeout:120000});for(const id of ['herring','tuna-yellow-label','tuna-blue-label','colorful','picasso']){await page.evaluate(id=>__FIVE_FISH__.select(id),id);const row=await page.evaluate(()=>{const api=__FIVE_FISH__;api.state.playing=false;const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl2');if(!gl)throw Error('GPU verifier requires WebGL2');
const vert='#version 300 es\nprecision highp float;precision highp int;\n'+api.DEFORM_GLSL.replace(/attribute /g,'in ').replace(/texture2D/g,'texture')+'\nin vec3 position;in vec3 normal;out vec3 resultPosition;out vec3 resultNormal;void main(){resultPosition=fishLocal(position);resultNormal=fishNormal(position,normal);gl_Position=vec4(resultPosition,1.0);}';
const frag='#version 300 es\nprecision highp float;out vec4 outColor;void main(){outColor=vec4(1);}';const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vert));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.transformFeedbackVaryings(program,['resultPosition','resultNormal'],gl.INTERLEAVED_ATTRIBS);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const uniform=name=>gl.getUniformLocation(program,name),pose=gl.createTexture(),fin=gl.createTexture();function upload(tex,unit,image){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,image.width,image.height,0,gl.RGBA,gl.FLOAT,image.data);}
gl.uniform1i(uniform('fishPose'),0);gl.uniform1i(uniform('fishFinAngles'),1);gl.uniform1f(uniform('fishCount'),1);const roots=new Float32Array(48),axes=new Float32Array(48);for(const f of api.score.rig.fins){roots.set(f.root,f.id*3);axes.set(f.axis,f.id*3);}gl.uniform3fv(uniform('finRoots[0]'),roots);gl.uniform3fv(uniform('finAxes[0]'),axes);const actorAddress=gl.getAttribLocation(program,'actorAddress');gl.disableVertexAttribArray(actorAddress);gl.vertexAttrib1f(actorAddress,0);
let maxNormalError=0,maxSeamError=0,maxCpuError=0,vertices=0,allFinite=true;const frames=[];for(const mode of ['rest','hover','cruise','burst','turn']){for(let step=0;step<90;step++)api.Behavior.update(api.behavior,1/60,{mode});api.updatePoses();upload(pose,0,api.poseTexture.image);upload(fin,1,api.finTexture.image);const seams=new Map();let frameCpu=0,frameSeam=0;for(const mesh of api.meshes){const p=mesh.userData.primitive,count=p.positions.length/3,vao=gl.createVertexArray();gl.bindVertexArray(vao);function attribute(name,values,width){const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,values,gl.STATIC_DRAW);const a=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,width,gl.FLOAT,false,0,0);return buf;}
const buffers=[attribute('position',mesh.geometry.attributes.position.array,3),attribute('normal',mesh.geometry.attributes.normal.array,3),attribute('finInfo',mesh.geometry.attributes.finInfo.array,2)];gl.disableVertexAttribArray(actorAddress);gl.vertexAttrib1f(actorAddress,0);const out=gl.createBuffer();gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,out);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,count*24,gl.STREAM_READ);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,out);gl.enable(gl.RASTERIZER_DISCARD);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,count);gl.endTransformFeedback();gl.disable(gl.RASTERIZER_DISCARD);const result=new Float32Array(count*6);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,result);vertices+=count;const actor=api.behavior.actors[0],spine=api.Behavior.sampleSpine(actor,api.state.selected,65);
for(let i=0;i<count;i++){const q=Array.from(mesh.geometry.attributes.position.array.slice(i*3,i*3+3)),got=Array.from(result.slice(i*6,i*6+3)),n=Array.from(result.slice(i*6+3,i*6+6));allFinite&&=got.every(Number.isFinite)&&n.every(Number.isFinite);maxNormalError=Math.max(maxNormalError,Math.abs(Math.hypot(...n)-1));const key=q.map(v=>Math.round(v*1e7)).join(',');if(seams.has(key)){const other=seams.get(key);frameSeam=Math.max(frameSeam,Math.hypot(...got.map((v,k)=>v-other[k])));}else seams.set(key,got);
let expected=q.slice();const id=p.finId[i],w=p.finWeight[i];if(id&&w){const f=api.score.rig.fins.find(f=>f.id===id),x=api.finTexture.image.data,id4=id*4,ang=(x[id4]*Math.sin(x[id4+1]+x[id4+2]*(q[0]-f.root[0]))+x[id4+3])*w,axis=f.axis.map(v=>v/(Math.hypot(...f.axis)||1)),v=q.map((x,k)=>x-f.root[k]),c=Math.cos(ang),s=Math.sin(ang),dot=axis.reduce((sum,x,k)=>sum+x*v[k],0),cross=[axis[1]*v[2]-axis[2]*v[1],axis[2]*v[0]-axis[0]*v[2],axis[0]*v[1]-axis[1]*v[0]];expected=v.map((x,k)=>f.root[k]+x*c+cross[k]*s+axis[k]*dot*(1-c));}expected=api.Behavior.deform(expected,actor,api.state.selected,spine);frameCpu=Math.max(frameCpu,Math.hypot(...got.map((v,k)=>v-expected[k])));}
gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.deleteBuffer(out);for(const b of buffers)gl.deleteBuffer(b);gl.deleteVertexArray(vao);}
maxCpuError=Math.max(maxCpuError,frameCpu);maxSeamError=Math.max(maxSeamError,frameSeam);frames.push({mode,cpuGpuError:frameCpu,seamError:frameSeam});}const error=gl.getError();gl.getExtension('WEBGL_lose_context')?.loseContext();return{id:api.state.selected,verticesTested:vertices,frames,allFinite,maxNormalError,maxSeamError,maxCpuError,glError:error,passed:allFinite&&maxNormalError<1e-4&&maxSeamError<3e-6&&maxCpuError<3e-5&&error===0};});report.rows.push(row);console.log(JSON.stringify(row));}report.passed=report.rows.every(r=>r.passed);}catch(e){report.passed=false;report.error=String(e.stack||e);console.log(report.error);}finally{await browser.close();fs.writeFileSync(path.join(root,'evidence/GPU_SURFACE_REPORT.json'),JSON.stringify(report,null,2)+'\n');}if(!report.passed)process.exitCode=1;
