function init3d(){try{gl=c3.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw new Error('当前浏览器未启用 WebGL 2');prog=mkprog(VS,FS);waterProg=mkprog(WVS,WFS);status('构建一张连续三维地形');progress(86);setTimeout(()=>{meshOverview=mesh(257);water=waterMesh();glReady=true;progress(100);status('连续地形、水系与镜头已就绪');$('modeBtn').textContent='切换二维';switchMode('3d');requestAnimationFrame(frame3d)},20)}catch(e){console.error(e);status('二维稳定审核模式可用，三维未启动','warn');progress(100)}}
function rebuildLocal(c){if(local){gl.deleteVertexArray(local.vao);gl.deleteBuffer(local.vb);gl.deleteBuffer(local.ib)}local=mesh(257,c,22000)}
function fly3d(k){const a=ANCHORS[k],h=heightAt(a.c[0],a.c[1]);rebuildLocal(a.c);startCam({target:[a.c[0],h+90,a.c[1]],radius:k==='yandang'?9000:12500,theta:k==='haimen'?-2.15:-.92,phi:k==='yandang'?.34:.43},1500)}
function startCam(to,d=1200){flight={kind:'3d',t:performance.now(),d,from:{target:[...cam.target],radius:cam.radius,theta:cam.theta,phi:cam.phi},to}}
function updateCam(now){if(!flight||flight.kind!=='3d')return;let t=Math.min(1,(now-flight.t)/flight.d);t=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;const a=flight.from,b=flight.to;cam.target=a.target.map((v,i)=>v+(b.target[i]-v)*t);cam.radius=Math.exp(Math.log(a.radius)+(Math.log(b.radius)-Math.log(a.radius))*t);cam.theta=a.theta+(b.theta-a.theta)*t;cam.phi=a.phi+(b.phi-a.phi)*t;if(t>=1)flight=null}
function switchMode(m){state.mode=m;document.documentElement.dataset.mode=m;if(m==='3d'){$('modeBtn').textContent='切换二维';$('fps').textContent='0 FPS'}else{$('modeBtn').textContent='切换三维';$('fps').textContent='二维模式';draw2d()}}
function resize3d(){const q=Math.min(devicePixelRatio||1,2),w=Math.max(1,innerWidth*q|0),h=Math.max(1,innerHeight*q|0);if(c3.width!==w||c3.height!==h){c3.width=w;c3.height=h}gl.viewport(0,0,w,h)}
function set1(p,n,v){gl.uniform1f(gl.getUniformLocation(p,n),v)}function set3(p,n,v){gl.uniform3fv(gl.getUniformLocation(p,n),v)}
function drawMesh(m,vp,eye){if(!m)return;gl.bindVertexArray(m.vao);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'vp'),false,vp);set3(prog,'eye',eye);const al=state.sun*Math.PI/180;set3(prog,'sun',[Math.cos(al)*-.55,Math.sin(al),Math.cos(al)*.65]);set1(prog,'erosion',state.erosion);set1(prog,'sediment',state.sediment);set1(prog,'cliff',state.cliff);set1(prog,'karst',state.karst);set1(prog,'bank',state.bank);set1(prog,'detail',state.detail);set1(prog,'fog',state.fog);gl.uniform1i(gl.getUniformLocation(prog,'satellite'),state.satellite);gl.drawElements(gl.TRIANGLES,m.count,gl.UNSIGNED_INT,0)}
function groundDir(){return[Math.cos(cam.pitch)*Math.cos(cam.yaw),Math.sin(cam.pitch),Math.cos(cam.pitch)*Math.sin(cam.yaw)]}
function updateGround(dt){if(cam.mode!=='ground')return;const d=groundDir(),r=norm(cross(d,[0,1,0]));let x=0,z=0;if(keys.has('w')||keys.has('arrowup')){x+=d[0];z+=d[2]}if(keys.has('s')||keys.has('arrowdown')){x-=d[0];z-=d[2]}if(keys.has('a')||keys.has('arrowleft')){x-=r[0];z-=r[2]}if(keys.has('d')||keys.has('arrowright')){x+=r[0];z+=r[2]}const l=Math.hypot(x,z)||1,s=keys.has('shift')?28:8;cam.pos[0]+=x/l*s*dt;cam.pos[2]+=z/l*s*dt;cam.pos[1]=heightAt(cam.pos[0],cam.pos[2])+1.6;if(!local||Math.hypot(cam.pos[0]-local.center[0],cam.pos[2]-local.center[1])>4500)rebuildLocal([cam.pos[0],cam.pos[2]])}
function frame3d(now){if(!glReady)return;resize3d();updateCam(now);updateGround((now-lastFrame)/1000);lastFrame=now;gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.045,.085,.082,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);let eye,center;if(cam.mode==='ground'){eye=cam.pos;const d=groundDir();center=[eye[0]+d[0]*100,eye[1]+d[1]*100,eye[2]+d[2]*100]}else{eye=orbitEye();center=cam.target}const vp=mul(perspective(Math.PI/4,c3.width/c3.height,cam.mode==='ground'?.05:2,420000),look(eye,center,[0,1,0]));gl.useProgram(prog);drawMesh(meshOverview,vp,eye);if(local){gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(-1,-1);drawMesh(local,vp,eye);gl.disable(gl.POLYGON_OFFSET_FILL)}if(state.river&&water){gl.useProgram(waterProg);gl.bindVertexArray(water.vao);gl.uniformMatrix4fv(gl.getUniformLocation(waterProg,'vp'),false,vp);set1(waterProg,'width',state.centerline?.02:state.width);set1(waterProg,'diag',state.centerline?1:0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawElements(gl.TRIANGLES,water.count,gl.UNSIGNED_INT,0);gl.disable(gl.BLEND)}frames++;if(now-fpsT>700){$('fps').textContent=Math.round(frames*1000/(now-fpsT))+' FPS';frames=0;fpsT=now}$('cameraInfo').textContent=cam.mode==='ground'?`离地 ${(eye[1]-heightAt(eye[0],eye[2])).toFixed(1)} m · 近地锁定`:`连续镜头距离 ${Math.round(cam.radius).toLocaleString()} m`;requestAnimationFrame(frame3d)}
function enterGround(){if(!state.anchor)selectAnchor('yandang');const a=ANCHORS[state.anchor];cam.mode='ground';cam.pos=[a.c[0],heightAt(a.c[0],a.c[1])+1.6,a.c[1]];cam.yaw=-1.55;cam.pitch=-.08;rebuildLocal(a.c);document.body.classList.add('ground');if(state.mode!=='3d'&&glReady)switchMode('3d')}
function bindUI(){document.querySelectorAll('.section-title').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('closed'));document.querySelectorAll('[data-anchor]').forEach(b=>b.onclick=()=>selectAnchor(b.dataset.anchor));$('overview').onclick=overview;$('resetBtn').onclick=overview;$('ground').onclick=enterGround;$('modeBtn').onclick=()=>glReady?switchMode(state.mode==='3d'?'2d':'3d'):status('三维仍在初始化，二维结果已经可查看','warn');$('shotBtn').onclick=()=>{const out=document.createElement('canvas');out.width=out.height=2048;const x=out.getContext('2d');x.drawImage(baseCanvas,0,0,2048,2048);if(state.river&&R.length){const sc=2048/META.world[0];x.lineCap='round';for(const r of R){x.beginPath();r.p.forEach((p,i)=>{const sx=(p[0]+META.world[0]/2)*sc,sy=(META.world[1]/2-p[1])*sc;i?x.lineTo(sx,sy):x.moveTo(sx,sy)});x.strokeStyle=state.centerline?'#f2c84b':'rgba(38,135,196,.86)';x.lineWidth=state.centerline?1.2:Math.max(.7,(r.w||18)*state.width*sc);x.stroke()}}const a=document.createElement('a');a.download='WENZHOU_CONTINUOUS_DEM_2048.png';a.href=out.toDataURL('image/png');a.click()};
for(const k of['sculpt','erosion','sediment','cliff','karst','bank','detail']){$(k).oninput=e=>{state[k]=+e.target.value;$(k+'V').textContent=state[k].toFixed(2);scheduleBase()}}$('satellite').onchange=e=>{state.satellite=+e.target.value;scheduleBase()};$('river').onchange=e=>{state.river=e.target.checked;draw2d()};$('centerline').onchange=e=>{state.centerline=e.target.checked;draw2d()};$('width').oninput=e=>{state.width=+e.target.value;$('widthV').textContent=state.width.toFixed(2)+'×';draw2d()};$('sun').oninput=e=>{state.sun=+e.target.value;$('sunV').textContent=state.sun.toFixed(0)+'°';scheduleBase()};$('fog').oninput=e=>{state.fog=+e.target.value;$('fogV').textContent=state.fog.toFixed(2)};
window.addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='Escape'&&cam.mode==='ground'){cam.mode='orbit';document.body.classList.remove('ground');if(state.anchor)fly3d(state.anchor)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));let gd=false,gx=0,gy=0,pan=false;c3.addEventListener('pointerdown',e=>{gd=true;gx=e.clientX;gy=e.clientY;pan=e.button===2||e.shiftKey;c3.setPointerCapture(e.pointerId);flight=null});c3.addEventListener('pointerup',e=>{gd=false;c3.releasePointerCapture(e.pointerId)});c3.addEventListener('pointermove',e=>{if(!gd)return;const dx=(e.clientX-gx)/innerWidth,dy=(e.clientY-gy)/innerHeight;gx=e.clientX;gy=e.clientY;if(cam.mode==='ground'){cam.yaw-=dx*5;cam.pitch=Math.max(-1.2,Math.min(1.2,cam.pitch-dy*4))}else if(pan){const s=cam.radius*.7;cam.target[0]-=dx*s;cam.target[2]-=dy*s}else{cam.theta-=dx*5;cam.phi=Math.max(.04,Math.min(1.49,cam.phi+dy*4))}});c3.addEventListener('wheel',e=>{e.preventDefault();if(cam.mode!=='ground')cam.radius=Math.max(180,Math.min(350000,cam.radius*Math.exp(e.deltaY*.001)))},{passive:false});c3.addEventListener('contextmenu',e=>e.preventDefault())}
window.addEventListener('resize',()=>{draw2d();if(glReady)resize3d()});bind2d();bindUI();loadData().catch(e=>{console.error(e);status('在线地形载入失败，请刷新页面','bad');progress(100)});
