"use strict";

const META={grid:129,nativeGrid:[11866,11866],world:[148325,148325],min:0,max:1373,heightChunks:3,riverChunks:0,truthSha:"8a1bc6ee17dd731007804a0281f9e083e01f5745468f90cf2c11c108ec0b1c6e"};
const ANCHORS={
 wenzhou:{label:"温州城",c:[-43250,-29787.5],zoom:6.4},
 xianxi:{label:"仙溪镇",c:[-3225,15862.5],zoom:7.4},
 haimen:{label:"海门城",c:[34750,44762.5],zoom:7.0},
 yandang:{label:"雁荡山",c:[-4875,10575],zoom:9.2}
};
const $=id=>document.getElementById(id),c2=$('view2d'),c3=$('view3d'),ctx=c2.getContext('2d',{alpha:false});
const state={mode:'2d',anchor:null,sculpt:.62,erosion:.58,sediment:.50,cliff:.72,karst:.34,bank:.55,detail:.65,satellite:0,river:true,centerline:false,width:1,sun:38,fog:.24};
let H=null,R=[],slope=null,curv=null,baseCanvas=document.createElement('canvas'),baseCtx=baseCanvas.getContext('2d'),renderPending=false;
let view={cx:0,cz:0,zoom:1},flight=null,drag=false,lastX=0,lastY=0;
let gl=null,glReady=false,prog=null,waterProg=null,meshOverview=null,local=null,water=null,cam={target:[0,240,0],theta:-1.05,phi:.72,radius:190000,mode:'orbit',pos:[0,0,0],yaw:-1.55,pitch:-.08},keys=new Set(),lastFrame=performance.now(),frames=0,fpsT=performance.now();
function status(t,k='ok'){const e=$('boot');e.textContent=t;e.dataset.kind=k}
function progress(v){$('progress').style.width=Math.max(0,Math.min(100,v))+'%'}
async function fetchJoined(dir,n){let parts=await Promise.all(Array.from({length:n},(_,i)=>fetch(`${dir}/${String(i).padStart(2,'0')}.txt`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${dir} ${r.status}`);return r.text()})));return parts.join('')}
function b64Bytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function inflateText(s,binary=false){if(!('DecompressionStream'in window))throw new Error('浏览器缺少 DecompressionStream');const ds=new DecompressionStream('deflate'),stream=new Blob([b64Bytes(s)]).stream().pipeThrough(ds),buf=await new Response(stream).arrayBuffer();return binary?buf:new TextDecoder().decode(buf)}
async function loadData(){status('读取连续真实 DEM');progress(8);const hb=await fetchJoined('data/height',META.heightChunks);progress(38);const raw=await inflateText(hb,true);H=new Int16Array(raw);if(H.length!==META.grid*META.grid)throw new Error('高程网格长度不匹配');status('计算地形导数与灰度增强');progress(52);derive();renderBase();draw2d();progress(68);R=deriveRivers();$('riverInfo').textContent=`${R.length} 条固定中心线 · 河宽只作横向变化`;progress(78);draw2d();status('二维连续地形已就绪，后台初始化三维');setTimeout(init3d,40)}

function deriveRivers(){const n=META.grid,N=n*n,down=new Int32Array(N);down.fill(-1);const acc=new Float32Array(N);acc.fill(1);const order=[];const dirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];for(let y=1;y<n-1;y++)for(let x=1;x<n-1;x++){const i=y*n+x,h=H[i];if(h<=0)continue;let best=i,bh=h;for(const[dX,dY]of dirs){const j=(y+dY)*n+x+dX;if(H[j]<bh){bh=H[j];best=j}}if(best!==i)down[i]=best;order.push(i)}order.sort((a,b)=>H[b]-H[a]);for(const i of order){const j=down[i];if(j>=0)acc[j]+=acc[i]}const lines=[];const threshold=85;for(let y=1;y<n-1;y++)for(let x=1;x<n-1;x++){const i=y*n+x,j=down[i];if(j<0||acc[i]<threshold||H[i]<=0)continue;const jy=Math.floor(j/n),jx=j-jy*n;const wx=(x/(n-1)-.5)*META.world[0],wz=(.5-y/(n-1))*META.world[1],wx2=(jx/(n-1)-.5)*META.world[0],wz2=(.5-jy/(n-1))*META.world[1],w=Math.max(10,Math.min(110,Math.sqrt(acc[i])*3.2));lines.push({p:[[wx,wz,H[i]],[wx2,wz2,H[j]]],w})}return lines}
function derive(){const n=META.grid;slope=new Float32Array(H.length);curv=new Float32Array(H.length);for(let y=1;y<n-1;y++){let o=y*n;for(let x=1;x<n-1;x++){const i=o+x,dx=(H[i+1]-H[i-1])*.5,dz=(H[i+n]-H[i-n])*.5;slope[i]=Math.hypot(dx,dz);curv[i]=H[i+1]+H[i-1]+H[i+n]+H[i-n]-4*H[i]}}}
function hash(x,y){let n=(x*374761393+y*668265263)>>>0;n=(n^(n>>>13))*1274126177>>>0;return((n^(n>>>16))>>>0)/4294967295}
function ramp(t){const p=[[.08,.19,.12],[.24,.40,.19],[.49,.52,.25],[.57,.40,.24],[.68,.63,.53],[.94,.92,.86]],s=[0,.16,.36,.60,.82,1];let k=0;while(k<4&&t>s[k+1])k++;const f=(t-s[k])/(s[k+1]-s[k]||1),a=p[k],b=p[k+1];return[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,a[2]+(b[2]-a[2])*f]}
function renderBase(){if(!H)return;const n=META.grid;baseCanvas.width=baseCanvas.height=n;const im=baseCtx.createImageData(n,n),d=im.data;const sun=state.sun*Math.PI/180,az=-.78;for(let y=0;y<n;y++){for(let x=0;x<n;x++){const i=y*n+x,j=i*4,h=H[i];if(h<=0){d[j]=20;d[j+1]=75;d[j+2]=108;d[j+3]=255;continue}const t=Math.max(0,Math.min(1,(h-5)/930)),s=Math.min(1,slope[i]/42),cv=Math.max(-1,Math.min(1,curv[i]/26)),n1=hash(x,y)-.5,n2=hash(x>>2,y>>2)-.5;let col=ramp(t);let cliff=Math.pow(s,1.65)*state.cliff,eros=Math.max(0,-cv)*state.erosion,dep=Math.max(0,cv)*state.sediment,karst=Math.pow(s,1.15)*(0.5+Math.abs(n2))*state.karst,bank=h<32?state.bank*(1-h/32):0,detail=(n1*.13+n2*.08)*state.detail;col=col.map(v=>v*(1-eros*.18-detail*.08));col=[col[0]*(1-cliff*.20)+.55*cliff*.20,col[1]*(1-cliff*.20)+.54*cliff*.20,col[2]*(1-cliff*.20)+.50*cliff*.20];col=[col[0]*(1-dep*.22)+.62*dep*.22,col[1]*(1-dep*.22)+.52*dep*.22,col[2]*(1-dep*.22)+.34*dep*.22];col=[col[0]*(1-karst*.14)+.76*karst*.14,col[1]*(1-karst*.14)+.75*karst*.14,col[2]*(1-karst*.14)+.71*karst*.14];col=[col[0]*(1-bank*.18)+.67*bank*.18,col[1]*(1-bank*.18)+.55*bank*.18,col[2]*(1-bank*.18)+.35*bank*.18];const nx=-(x>0&&x<n-1?(H[i+1]-H[i-1])*.5:0),nz=-(y>0&&y<n-1?(H[i+n]-H[i-n])*.5:0),ny=24,ln=Math.hypot(nx,ny,nz)||1,lx=Math.cos(sun)*Math.cos(az),ly=Math.sin(sun),lz=Math.cos(sun)*Math.sin(az),light=.38+.70*Math.max(0,(nx*lx+ny*ly+nz*lz)/ln);col=col.map(v=>v*light);if(state.satellite===1)col=[col[0]*.91,col[1]*1.12,col[2]*.93];if(state.satellite===2)col=[col[0]*1.05,col[1]*.98,col[2]*.90];if(state.satellite===3){const g=col[0]*.299+col[1]*.587+col[2]*.114;col=[g,g,g]}if(state.satellite===4){const g=col[0]*.299+col[1]*.587+col[2]*.114;col=col.map(v=>g*.42+v*.58);col=[col[0]*1.04,col[1],col[2]*.88]}d[j]=Math.max(0,Math.min(255,col[0]*255));d[j+1]=Math.max(0,Math.min(255,col[1]*255));d[j+2]=Math.max(0,Math.min(255,col[2]*255));d[j+3]=255}}baseCtx.putImageData(im,0,0)}
function resize2d(){const q=Math.min(devicePixelRatio||1,2),w=Math.max(1,innerWidth*q|0),h=Math.max(1,innerHeight*q|0);if(c2.width!==w||c2.height!==h){c2.width=w;c2.height=h;draw2d()}}
function worldToScreen(x,z){const scale=Math.min(c2.width,c2.height)/META.world[0]*view.zoom;return[c2.width/2+(x-view.cx)*scale,c2.height/2-(z-view.cz)*scale]}
function screenToWorld(x,y){const scale=Math.min(c2.width,c2.height)/META.world[0]*view.zoom;return[(x-c2.width/2)/scale+view.cx,-(y-c2.height/2)/scale+view.cz]}
function draw2d(){if(!H)return;resize2d();ctx.fillStyle='#07100f';ctx.fillRect(0,0,c2.width,c2.height);const scale=Math.min(c2.width,c2.height)/META.world[0]*view.zoom,w=META.world[0]*scale,h=META.world[1]*scale,x=c2.width/2-view.cx*scale-w/2,y=c2.height/2+view.cz*scale-h/2;ctx.imageSmoothingEnabled=true;ctx.drawImage(baseCanvas,x,y,w,h);if(state.river&&R.length){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';for(const r of R){const pts=r.p;if(pts.length<2)continue;ctx.beginPath();for(let i=0;i<pts.length;i++){const p=worldToScreen(pts[i][0],pts[i][1]);i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.strokeStyle=state.centerline?'rgba(255,205,79,.9)':'rgba(47,154,213,.78)';ctx.lineWidth=state.centerline?1.2:Math.max(.55,(r.w||18)*state.width*scale);ctx.stroke()}ctx.restore()}ctx.save();for(const [k,a]of Object.entries(ANCHORS)){const p=worldToScreen(a.c[0],a.c[1]);ctx.beginPath();ctx.arc(p[0],p[1],k===state.anchor?9:6,0,Math.PI*2);ctx.fillStyle=k===state.anchor?'#f4d477':'#8bd3b5';ctx.fill();ctx.strokeStyle='#07100f';ctx.lineWidth=2;ctx.stroke();ctx.font=`${Math.max(11,12*(devicePixelRatio||1))}px sans-serif`;ctx.fillStyle='#fff';ctx.fillText(a.label,p[0]+10,p[1]-8)}ctx.restore();$('cameraInfo').textContent=`二维连续总览 · 缩放 ${view.zoom.toFixed(2)}×`}
