/* Ocean Mother V001. One WebGL2 canvas, displaced water, shared numerical weather. */
(async()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('sea'),W=OceanWeather;
const qa={version:'0.1.0',ready:false,frames:0,completedFrames:0,errors:[],storedImageAssets:0,baselineVerified:false,cloudAtlasFrames:0,visualAcceptance:false,aaaQualityApproved:false,productionReady:false};
window.OceanMother={qa};function fail(e){const s=e?.stack||String(e);qa.errors.push(s);$('error').hidden=false;$('error').textContent='Ocean Mother 运行检查\n'+s;$('loading').style.display='none';console.error(s)}
addEventListener('error',e=>fail(e.error||e.message));addEventListener('unhandledrejection',e=>fail(e.reason));
const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl){fail('浏览器未提供 WebGL2');return;}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('WebGL context lost. 请重新加载页面。')});
const hdr=!!gl.getExtension('EXT_color_buffer_float'),timer=gl.getExtension('EXT_disjoint_timer_query_webgl2');qa.hdr=hdr;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const S={swell:1.35,period:8.8,chop:.72,rough:.16,foam:.32,tint:.15,height:9,seaSpeed:1,seed:8071,quality:innerWidth<700?'balanced':'fine',yaw:-.48,pitch:-.055};
const seaPresets={breeze:{title:'晴日海风',caption:'长涌浪、局部风浪与微细波纹共同演化。',swell:1.35,period:8.8,wind:10,chop:.72,rough:.16,foam:.32,tint:.15,hour:16.2,weather:'fair',height:9},calm:{title:'平静海面',caption:'微风轻拂，云层和天光沿水面延伸。',swell:.22,period:10.4,wind:2,chop:.34,rough:.095,foam:.05,tint:.12,hour:12,weather:'high',height:5},swell:{title:'远洋涌浪',caption:'长周期涌浪与方向分散的短波相互叠加。',swell:3.0,period:12.5,wind:12,chop:.85,rough:.18,foam:.45,tint:.04,hour:15.5,weather:'fair',height:11},golden:{title:'金色黄昏',caption:'同一太阳照亮云层、浪脊与水面的反射。',swell:.8,period:9,wind:6,chop:.66,rough:.145,foam:.15,tint:.20,hour:17.4,weather:'fair',height:6},gale:{title:'阴天风浪',caption:'风浪尺度、波峰白沫与阴云共同变化。',swell:2.6,period:7.2,wind:19,chop:.92,rough:.24,foam:.75,tint:.03,hour:14.4,weather:'rain',height:13},lagoon:{title:'青碧海水',caption:'青碧水色与清澈天光。水色是材质预设，未使用海底数据。',swell:.45,period:6.2,wind:5,chop:.56,rough:.13,foam:.13,tint:.90,hour:12.3,weather:'fair',height:7}};
const weatherKeys=new Set(['wind','direction','hour','density','cloudSpeed','exposure']);
function range(parent,id,label,min,max,step,value,unit=''){const row=document.createElement('div');row.className='row';row.innerHTML=`<label for="${id}">${label}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output>${value}${unit}</output>`;$(parent).append(row);$(id).oninput=e=>{set(id,+e.target.value);row.querySelector('output').textContent=Number(e.target.value).toFixed(step<1?1:0)+unit};}
range('oceanControls','wind','风力',0,28,1,10,' m/s');range('oceanControls','direction','来风方向',0,360,1,270,'°');range('oceanControls','swell','涌浪尺度',0,6,.1,S.swell,' m');range('oceanControls','period','主涌浪周期',4,16,.1,S.period,' s');range('oceanControls','chop','浪峰尖锐度',0,1,.01,S.chop);range('oceanControls','seaSpeed','海浪演示速度',0,3,.05,1,'×');range('oceanControls','foam','泡沫强度',0,1,.01,S.foam);range('oceanControls','tint','青碧水色',0,1,.01,S.tint);
range('weatherControls','hour','时刻',0,24,.05,16.2,' h');range('weatherControls','density','云浓度',0,1.8,.01,.86);range('weatherControls','cloudSpeed','云漂移',0,80,1,12,' m/s');range('weatherControls','exposure','曝光',.4,1.8,.02,1);range('viewControls','height','观察高度',1.6,120,.1,S.height,' m');range('viewControls','rough','表面粗糙度',.035,.4,.005,S.rough);
let preset='breeze',seaTime=0,paused=new URLSearchParams(location.search).has('still'),last=performance.now(),needFrame=true,workerJob=0,noiseReady=false,volumeReady=false,pendingVolume=null,pendingNoise=null,pendingLight=null,lightBusy=false,shadowSun=null,shadowRequested=null;
let envDirty=true,envForce=true,waveDirty=true,readyEnvironment=false,envIndex=0,envCompleted=0,baking=false,bakeRow=0,bakeSnapshot=null,bakeEnv=null,bakeStart=0,nextBakeAt=0,envMix=1,lastEnvSwap=0,busyFence=null,pendingQuery=null,queryQueue=[],frameTimes=[],gpuTimes=[],lastComplete=0;
const hash=(n)=>{n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return ((n^(n>>>16))>>>0)/4294967296};
const waveK=new Float32Array(24*4),waveA=new Float32Array(24*4);let currentK=null,currentA=null,gridVao,gridIndexCount=0,gridRows=160;
const min=[-19,-1,-16],max=[19,13,16],dims=innerWidth<700?[192,112,160]:[320,192,256];qa.densityDimensions=dims;
async function text(url){const r=await fetch(url);if(!r.ok)throw Error(url+' HTTP '+r.status);return r.text()}
async function sha(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(v=>v.toString(16).padStart(2,'0')).join('')}
const raw=await text('weather/cloud.glsl');if(await sha(raw)!=='d0d28a6321d26cf83e2380dac032aee1741bdd87a58cda4883110dab642b0626')throw Error('天气着色器哈希与交接基线不一致');
const workerSource=await text('weather/field-worker.js');if(await sha(workerSource)!=='8c4402977790dc2e9c6116f6f4ac8d75b88bda967183f2df077970663a44aa4e')throw Error('天气密度生成器哈希不一致');qa.baselineVerified=true;
const V='#version 300 es\nvoid main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0.,1.);}';
function shader(type,src){const a=gl.createShader(type);gl.shaderSource(a,src);gl.compileShader(a);if(!gl.getShaderParameter(a,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(a)||'Shader compile failure');return a}
function program(v,f){const p=gl.createProgram(),a=shader(gl.VERTEX_SHADER,v),b=shader(gl.FRAGMENT_SHADER,f);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(a);gl.deleteShader(b);return p}
const base=raw.slice(0,raw.indexOf('void main(){'));
let envSource=base+(await text('cloud-atlas.frag'));if(!hdr)envSource=envSource.replace('return s*uOpt.x;','return s*60.*uOpt.x;');
const atmosphere=base.slice(0,base.indexOf('vec2 shadowAt')).replace('layout(location=0) out vec4 fragColor;','').replace('layout(location=1) out vec4 fragInfo;','');
const seaProgram=program(await text('ocean.vert'),atmosphere+await text('water.frag')),skyProgram=program(V,atmosphere+await text('sky.frag')),envProgram=program(V,envSource);
const fullVao=gl.createVertexArray(),locations=new Map();function loc(p,n){let m=locations.get(p);if(!m){m=new Map();locations.set(p,m)}if(!m.has(n))m.set(n,gl.getUniformLocation(p,n));return m.get(n)}
const f=(p,n,x)=>gl.uniform1f(loc(p,n),x),i=(p,n,x)=>gl.uniform1i(loc(p,n),x),v2=(p,n,a,b)=>gl.uniform2f(loc(p,n),a,b),v3=(p,n,a)=>gl.uniform3fv(loc(p,n),a),v4=(p,n,a)=>gl.uniform4fv(loc(p,n),a);
function tex3(data,size,mode=0){const t=gl.createTexture();upload3(t,data,size,mode);return t}
function upload3(t,data,size,mode=0){gl.bindTexture(gl.TEXTURE_3D,t);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,mode===3?gl.NEAREST:gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,mode===3?gl.NEAREST:gl.LINEAR);for(const n of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,n,mode===1?gl.REPEAT:gl.CLAMP_TO_EDGE);if(mode===2&&!hdr){data=Uint8Array.from(data,x=>Math.round(Math.min(1,x/60)*255))}gl.texImage3D(gl.TEXTURE_3D,0,mode===2?(hdr?gl.RG16F:gl.RG8):mode===1?gl.RG8:gl.R8,...size,0,mode===1||mode===2?gl.RG:gl.RED,mode===2&&hdr?gl.FLOAT:gl.UNSIGNED_BYTE,data)}
const macro=tex3(new Uint8Array([0]),[1,1,1]),noise=tex3(new Uint8Array([128,128]),[1,1,1],1),shadow=tex3(new Float32Array([0,0]),[1,1,1],2),occupancy=tex3(new Uint8Array([255]),[1,1,1],3);let groups=[],occupancySize=[1,1,1];
let envW=0,envH=0,envSteps=128,atlases=[];
function makeAtlas(){const texture=gl.createTexture(),framebuffer=gl.createFramebuffer();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,hdr?gl.RGBA16F:gl.RGBA8,envW,envH,0,gl.RGBA,hdr?gl.HALF_FLOAT:gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('天空缓存不完整');gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);return{texture,framebuffer}}
function quality(){const q=S.quality,sz=q==='ultra'?[768,256,256]:q==='fine'?[512,192,160]:[256,96,112];if(envW===sz[0])return;for(const a of atlases){gl.deleteTexture(a.texture);gl.deleteFramebuffer(a.framebuffer)}[envW,envH,envSteps]=sz;atlases=[makeAtlas(),makeAtlas(),makeAtlas()];envIndex=0;envCompleted=0;baking=false;envMix=1;readyEnvironment=false;envForce=true;gridRows=q==='ultra'?240:q==='fine'?176:120;const columns=q==='ultra'?288:q==='fine'?208:144,vertices=new Float32Array((columns+1)*(gridRows+1)*2),indices=new Uint32Array(columns*gridRows*6);let k=0;for(let y=0;y<=gridRows;y++)for(let x=0;x<=columns;x++){vertices[k++]=x/columns;vertices[k++]=y/gridRows}k=0;for(let y=0;y<gridRows;y++)for(let x=0;x<columns;x++){const j=y*(columns+1)+x;indices.set([j,j+1,j+columns+1,j+1,j+columns+2,j+columns+1],k);k+=6}if(gridVao){gl.deleteVertexArray(gridVao.vao);gl.deleteBuffer(gridVao.v);gl.deleteBuffer(gridVao.i)}gridVao={vao:gl.createVertexArray(),v:gl.createBuffer(),i:gl.createBuffer()};gl.bindVertexArray(gridVao.vao);gl.bindBuffer(gl.ARRAY_BUFFER,gridVao.v);gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,gridVao.i);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);gridIndexCount=indices.length;qa.meshVertices=vertices.length/2;qa.meshTriangles=indices.length/3;qa.cloudAtlasSize=[envW,envH];qa.cloudSteps=envSteps;needFrame=true;}
const workerURL=URL.createObjectURL(new Blob([workerSource],{type:'text/javascript'})),worker=new Worker(workerURL);URL.revokeObjectURL(workerURL);worker.onerror=e=>fail(e.message);worker.onmessage=({data:d})=>{if(d.error){fail(d.error);return}if(d.noise)pendingNoise=d;else if(d.light){if(d.id===workerJob)pendingLight={...d,sun:shadowRequested};lightBusy=false}else if(d.id===workerJob)pendingVolume={...d,sun:shadowRequested};needFrame=true};
function rebuild(){workerJob++;const s=W.snapshot(),e=W.getEnvironment();shadowRequested=e.sun.direction[1]>=0?e.sun.direction:e.sun.direction.map(x=>-x);worker.postMessage({id:workerJob,kind:s.kind,seed:s.seed,count:Math.round(s.count),instability:s.instability,dims,min,max,sun:shadowRequested});$('status').textContent='生成云场 · 海面保持运行'}
function bind3(p){for(const[unit,tex]of[[0,macro],[1,noise],[2,shadow],[3,occupancy]]){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_3D,tex)}i(p,'uMacro',0);i(p,'uOld',0);i(p,'uNoise',1);i(p,'uShadow',2);i(p,'uOldShadow',2);i(p,'uOccupancy',3)}
function lighting(p,s,e){const elev=e.sun.direction[1],a=clamp((elev+.13)/.25,0,1);v3(p,'uSun',e.sun.direction);v3(p,'uMoon',e.sun.direction.map(x=>-x));v3(p,'uSunColor',e.sun.linearColor);f(p,'uDay',a*a*(3-2*a));v4(p,'uLight',[s.sunlight,s.skylight,s.scatter,s.haze]);v4(p,'uWeather',[s.rain,s.fog,s.snow,s.humidity/100]);f(p,'exposure',s.exposure)}
function bakeTile(now){if(!noiseReady||!volumeReady)return;if(!baking){if(!envForce&&paused&&!envDirty)return;if(!envForce&&now<nextBakeAt)return;baking=true;bakeRow=0;bakeStart=now;bakeSnapshot=W.snapshot();bakeEnv=W.getEnvironment();envDirty=false;envForce=false}
const p=envProgram,s=bakeSnapshot,e=bakeEnv,target=atlases[(envIndex+1)%3];gl.bindFramebuffer(gl.FRAMEBUFFER,target.framebuffer);gl.viewport(0,0,envW,envH);gl.enable(gl.SCISSOR_TEST);const strip=Math.ceil(envH/12);gl.scissor(0,bakeRow,envW,Math.min(strip,envH-bakeRow));gl.disable(gl.DEPTH_TEST);gl.useProgram(p);gl.bindVertexArray(fullVao);bind3(p);lighting(p,s,e);v2(p,'uRes',envW,envH);f(p,'encodedEnv',hdr?0:1);v3(p,'uCamera',[0,S.height/1000,8]);v3(p,'uWind',s.windOffset);v3(p,'uMin',min);v3(p,'uMax',max);v3(p,'uWindDirection',e.wind.direction);v3(p,'uOccupancySize',occupancySize);v3(p,'uLoop',[1,s.loopPhase,s.loopAmount]);v4(p,'uFlow',[s.wind,s.cloudSpeed,s.gust,s.turbulence]);v4(p,'uOpt',[s.density*(.78+s.humidity*.0032),s.detail,0,0]);v4(p,'uEffects',[0,0,0,0]);v4(p,'uLightning',[0,4.8,0,0]);v2(p,'uSurface',s.silver,s.groundLight);f(p,'uFastEmpty',1);f(p,'uMicroFilter',1);f(p,'uBlend',1);f(p,'uEvolution',s.evolutionTime);f(p,'uTime',s.time);f(p,'uShear',s.shear);f(p,'uCloudBase',['Ci','Cc','Cs'].includes(s.kind)?5.5:1.2);f(p,'uCloudTop',s.kind==='Cb'?9:['Ci','Cc','Cs'].includes(s.kind)?7:4.2);i(p,'uSteps',envSteps);i(p,'uGroups',groups.length);gl.uniform3fv(loc(p,'uLo[0]'),new Float32Array(groups.flatMap(g=>g.lo)));gl.uniform3fv(loc(p,'uHi[0]'),new Float32Array(groups.flatMap(g=>g.hi)));gl.drawArrays(gl.TRIANGLES,0,3);gl.disable(gl.SCISSOR_TEST);bakeRow+=strip;
if(bakeRow>=envH){const first=!readyEnvironment;envIndex=(envIndex+1)%3;envCompleted++;qa.cloudAtlasFrames=envCompleted;qa.atlasSimulationTime=s.time;qa.lastBakeMs=now-bakeStart;lastEnvSwap=now;envMix=first?1:0;readyEnvironment=true;baking=false;nextBakeAt=now+(S.quality==='ultra'?400:220);qa.ready=true;$('loading').style.display='none';$('readyDot').className='ok';$('status').textContent='Ocean Mother V0.1 · 可交互候选'}}
function makeWaves(){const ws=W.snapshot(),bearing=ws.direction*Math.PI/180,base=Math.atan2(Math.cos(bearing),-Math.sin(bearing));let sumSteep=0;for(let group=0;group<2;group++){let raw=[],sum2=0;for(let j=0;j<12;j++){const idx=j+12*group,h=hash(S.seed+idx*341),d=base+(hash(S.seed+idx*991)-.5)*(group?1.8:.58)+(group?0:.24),len=group?Math.max(1.7,Math.min(40,2.0+ws.wind*1.6))*Math.pow(.79,j):9.81*S.period*S.period/(2*Math.PI)*(.62+hash(S.seed+idx*723)*.78),weight=group?Math.pow(.83,j):.46+hash(S.seed+idx*419);raw.push({idx,d,len,weight,h});sum2+=weight*weight;}const scale=(group?Math.min(3.7,ws.wind*ws.wind*.010):S.swell)/(4*Math.sqrt(.5*sum2));for(const w of raw){const k=2*Math.PI/w.len,amp=w.weight*scale,idx=w.idx;waveK.set([Math.cos(w.d),Math.sin(w.d),k,Math.sqrt(9.81*k)],idx*4);waveA.set([amp,amp*.65,w.h*2*Math.PI,w.len],idx*4);sumSteep+=amp*.65*k;}}
const gain=Math.min(1,.70/Math.max(sumSteep,1e-8));for(let j=0;j<24;j++)waveA[j*4+1]*=gain;qa.maxSteepnessBound=sumSteep*gain*S.chop;qa.spectralComponents=24;waveDirty=false;if(!currentK){currentK=new Float32Array(waveK);currentA=new Float32Array(waveA)}}
function surface(x,z,t=seaTime){let y=0;for(let j=0;j<24;j++){const a=j*4,k=currentK||waveK,v=currentA||waveA;y+=v[a]*Math.sin((k[a]*x+k[a+1]*z)*k[a+2]-k[a+3]*t+v[a+2])}return y}
function cameraData(){const cam=[0,Math.max(S.height,surface(0,8000)+1.6),8000],fw=norm([Math.sin(S.yaw)*Math.cos(S.pitch),Math.sin(S.pitch),-Math.cos(S.yaw)*Math.cos(S.pitch)]),right=norm(cross(fw,[0,1,0])),up=cross(right,fw);return{cam,fw,right,up,flat:norm([fw[0],0,fw[2]])}}
function set(id,value){if(weatherKeys.has(id)){W.set(id,value);if(id==='wind'||id==='direction')waveDirty=true;if(['hour','density'].includes(id)){envDirty=true;envForce=true;baking=false}}else S[id]=value;if(['swell','period','seed','chop'].includes(id))waveDirty=true;if(id==='height'){envDirty=true}needFrame=true;syncUI()}
function syncUI(){const w=W.snapshot();for(const id of['wind','direction','hour','density','cloudSpeed','exposure','swell','period','chop','rough','foam','tint','height','seaSpeed']){const el=$(id);if(!el)continue;const v=weatherKeys.has(id)?w[id]:S[id];el.value=v;el.nextElementSibling.textContent=(id==='hour'?Math.floor(v)+':'+String(Math.round(v%1*60)).padStart(2,'0'):Number(v).toFixed(['wind','direction','cloudSpeed'].includes(id)?0:1))+(id==='wind'||id==='cloudSpeed'?' m/s':id==='swell'||id==='height'?' m':id==='period'?' s':'')}$('quality').value=S.quality;$('weather').value=w.weather;$('kind').value=w.kind}
function applyPreset(key){if(!Object.hasOwn(seaPresets,key))throw Error('未知海况');const p=seaPresets[key];preset=key;for(const k of['swell','period','chop','rough','foam','tint','height'])S[k]=p[k];W.setWeather(p.weather);W.set('wind',p.wind);W.set('hour',p.hour);W.set('direction',270);S.yaw=key==='golden'?-1.22:-.48;S.pitch=key==='golden'?-.045:-.055;$('presetTitle').textContent=p.title;$('caption').textContent=p.caption;document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===key));waveDirty=true;baking=false;envForce=true;syncUI();rebuild()}
function common(p,now,s,e,c){gl.useProgram(p);lighting(p,s,e);v3(p,'camera',c.cam);v3(p,'fw',c.fw);v3(p,'right',c.right);v3(p,'up',c.up);f(p,'aspect',canvas.width/canvas.height);f(p,'tanFov',Math.tan(55*Math.PI/360));v2(p,'resolution',canvas.width,canvas.height);for(const[unit,tex]of[[4,atlases[(envIndex+2)%3].texture],[5,atlases[envIndex].texture]]){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,tex)}i(p,'envA',4);i(p,'envB',5);f(p,'envMix',envMix);f(p,'encodedEnv',hdr?0:1);f(p,'tSea',seaTime)}
function resize(){const scale=S.quality==='ultra'?Math.min(devicePixelRatio,1.5):S.quality==='fine'?1:.8,w=Math.max(2,Math.round(innerWidth*scale)),h=Math.max(2,Math.round(innerHeight*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;needFrame=true}qa.renderSize=[w,h]}
function percentile(a,q){if(!a.length)return null;let b=[...a].sort((x,y)=>x-y);return b[Math.floor((b.length-1)*q)]}
function statistics(now){while(queryQueue.length){const q=queryQueue[0];if(!gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE))break;queryQueue.shift();if(!gl.getParameter(timer.GPU_DISJOINT_EXT)){gpuTimes.push(gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6);if(gpuTimes.length>90)gpuTimes.shift()}gl.deleteQuery(q)}if(now-lastComplete<800)return;lastComplete=now;const mean=frameTimes.length?frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length:0,fps=mean?1000/mean:0;qa.performance={completedFrameFPS:fps,samples:frameTimes.length,frameP95ms:percentile(frameTimes,.95),gpuP50ms:percentile(gpuTimes,.5),gpuP95ms:percentile(gpuTimes,.95),gpuTimerAvailable:!!timer,includesProgressiveSkyBaking:true};$('fps').textContent=paused?'已暂停':fps?fps.toFixed(1)+' FPS':'测量中';$('metrics').textContent=`完成帧 ${fps.toFixed(1)} FPS\nP95 帧时 ${(qa.performance.frameP95ms||0).toFixed(1)} ms\nGPU ${qa.performance.gpuP50ms===null?'不可用':qa.performance.gpuP50ms.toFixed(1)+' ms'}\n海面 ${canvas.width}×${canvas.height}\n云缓存 ${envW}×${envH} / ${envSteps} 步\n${qa.meshTriangles} 三角形 · 24 层几何波\n生成缓存驻留内存，未存图像素材`}
let completeAt=0;function frame(now){requestAnimationFrame(frame);try{if(document.hidden){last=now;return}if(busyFence){if(gl.clientWaitSync(busyFence,0,0)===gl.TIMEOUT_EXPIRED)return;gl.deleteSync(busyFence);busyFence=null;qa.completedFrames++;if(completeAt&&!paused){frameTimes.push(now-completeAt);if(frameTimes.length>90)frameTimes.shift()}completeAt=now;}
statistics(now);const dt=Math.min(Math.max(0,(now-last)/1000),.35);last=now;if(!paused){W.tick(dt);seaTime+=dt*S.seaSpeed;}if(pendingNoise){upload3(noise,pendingNoise.data,[96,96,96],1);pendingNoise=null;noiseReady=true}
if(pendingVolume){const d=pendingVolume;pendingVolume=null;if(d.borderMax!==0||!d.supportSafe)throw Error('天气密度边界核验未通过');upload3(macro,d.data,dims);upload3(shadow,d.tau,d.shadowSize,2);upload3(occupancy,d.occupancy.data,d.occupancy.size,3);occupancySize=d.occupancy.size;groups=d.groups;volumeReady=true;shadowSun=d.sun;qa.borderInputMax=d.borderMax;qa.cloudVolumeBytes=d.data.byteLength;qa.cloudKind=d.kind;qa.cloudSeed=d.seed;envForce=true;baking=false}
if(pendingLight){upload3(shadow,pendingLight.tau,pendingLight.shadowSize,2);shadowSun=pendingLight.sun;pendingLight=null;envForce=true;baking=false}
const s=W.snapshot(),e=W.getEnvironment(),sun=e.sun.direction[1]>=0?e.sun.direction:e.sun.direction.map(x=>-x);if(volumeReady&&!lightBusy&&shadowSun&&Math.hypot(...sun.map((v,k)=>v-shadowSun[k]))>.025){lightBusy=true;shadowRequested=[...sun];worker.postMessage({light:true,id:workerJob,revision:workerJob,sun})}
if(paused&&qa.ready&&!needFrame&&!baking&&!envForce&&envMix>=1&&!pendingLight)return;
quality();resize();if(waveDirty)makeWaves();for(let k=0;k<96;k++){currentK[k]+=(waveK[k]-currentK[k])*Math.min(1,dt*2);currentA[k]+=(waveA[k]-currentA[k])*Math.min(1,dt*2)}
if(timer&&queryQueue.length<4){pendingQuery=gl.createQuery();gl.beginQuery(timer.TIME_ELAPSED_EXT,pendingQuery)}
bakeTile(now);envMix=envCompleted<=1?1:clamp((now-lastEnvSwap)/400,0,1);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);const c=cameraData();common(skyProgram,now,s,e,c);gl.bindVertexArray(fullVao);gl.drawArrays(gl.TRIANGLES,0,3);
common(seaProgram,now,s,e,c);f(seaProgram,'chop',S.chop);f(seaProgram,'gridRows',gridRows);v3(seaProgram,'flatForward',c.flat);f(seaProgram,'rough',S.rough);f(seaProgram,'waterTint',S.tint);f(seaProgram,'foamGain',S.foam);f(seaProgram,'windSpeed',s.wind);v2(seaProgram,'windTo',e.wind.direction[0],e.wind.direction[2]);f(seaProgram,'doFoam',$('foamEnabled').checked?1:0);f(seaProgram,'doReflection',$('reflections').checked?1:0);gl.uniform4fv(loc(seaProgram,'uWaveK[0]'),currentK);gl.uniform4fv(loc(seaProgram,'uWaveA[0]'),currentA);gl.bindVertexArray(gridVao.vao);gl.drawElements(gl.TRIANGLES,gridIndexCount,gl.UNSIGNED_INT,0);
if(pendingQuery){gl.endQuery(timer.TIME_ELAPSED_EXT);queryQueue.push(pendingQuery);pendingQuery=null}busyFence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);gl.flush();qa.frames++;qa.waveTime=seaTime;qa.environment=e;qa.camera=c;qa.lastGLerror=gl.getError();if(qa.lastGLerror)throw Error('WebGL '+qa.lastGLerror);needFrame=false;
}catch(err){paused=true;fail(err)}}
$('pause').onclick=()=>{paused=!paused;if(paused)W.pause();else W.play();$('pause').textContent=paused?'继续':'暂停';last=performance.now();frameTimes=[];completeAt=0;needFrame=true};$('reset').onclick=()=>{S.yaw=preset==='golden'?-1.22:-.48;S.pitch=-.055;S.height=seaPresets[preset].height;syncUI();needFrame=true};$('togglePanel').onclick=()=>$('panel').classList.toggle('closed');if(innerWidth<700)$('panel').classList.add('closed');
$('newSeed').onclick=()=>{S.seed=(S.seed+7919)>>>0;waveDirty=true;needFrame=true};$('cloudSeed').onclick=()=>{W.setSeed(W.snapshot().seed+7919);rebuild()};$('quality').onchange=e=>{S.quality=e.target.value;quality();needFrame=true};$('weather').onchange=e=>{W.setWeather(e.target.value);syncUI();rebuild()};$('kind').onchange=e=>{W.setKind(e.target.value);rebuild()};for(const k of['foamEnabled','reflections'])$(k).onchange=()=>needFrame=true;document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));document.querySelectorAll('[data-hour]').forEach(b=>b.onclick=()=>set('hour',+b.dataset.hour));
let drag=false,x=0,y=0;canvas.onpointerdown=e=>{drag=true;x=e.clientX;y=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;S.yaw-=(e.clientX-x)*.003;S.pitch=clamp(S.pitch+(e.clientY-y)*.003,-.75,.60);x=e.clientX;y=e.clientY;needFrame=true};canvas.onpointerup=()=>drag=false;canvas.onpointercancel=()=>drag=false;canvas.addEventListener('wheel',e=>{e.preventDefault();S.height=clamp(S.height*Math.exp(e.deltaY*.001),1.6,120);syncUI();needFrame=true},{passive:false});addEventListener('resize',()=>needFrame=true);
function config(){return{format:'ocean-mother-scene',version:1,ocean:{...S},weather:W.snapshot(),waterModel:'24 directionally distributed Gerstner components plus 12 filtered micro-slope harmonics',foam:'instantaneous crest-compression appearance',reflections:'same numerical weather hemispherical radiance cache',limitations:['not FFT or CFD','no coastline or bathymetry','distant cloud cache has no reflection parallax','no storm microphysics']}}
$('save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Ocean_Mother_'+S.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.OceanMother={qa,set:(k,v)=>{const el=$(k);if(!el||el.type!=='range'||!Number.isFinite(v))throw Error('Invalid control');set(k,clamp(v,+el.min,+el.max))},setPreset:applyPreset,getConfiguration:config,getEnvironment:W.getEnvironment,sampleHeight:surface,pause:()=>{paused=true;W.pause();$('pause').textContent='继续';needFrame=true},play:()=>{paused=false;W.play();last=performance.now();$('pause').textContent='暂停';needFrame=true},setView:(yaw,pitch,height)=>{S.yaw=yaw;S.pitch=clamp(pitch,-.75,.60);S.height=clamp(height,1.6,120);syncUI();needFrame=true}};
quality();worker.postMessage({noise:true});const presetParam=new URLSearchParams(location.search).get('preset');applyPreset(presetParam&&seaPresets[presetParam]?presetParam:'breeze');if(paused){W.pause();$('pause').textContent='继续'}requestAnimationFrame(frame);
})().catch(e=>{console.error(e);const box=document.getElementById('error');box.hidden=false;box.textContent=e.stack||String(e);document.getElementById('loading').style.display='none';if(window.OceanMother)OceanMother.qa.errors.push(String(e));});
