const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),{chromium}=require('playwright');
const commit=process.env.PUBLIC_COMMIT,OUT=process.env.QA_OUT||(commit?'qa-et14/public':'qa-et14/source'),URL=process.env.QA_URL||(commit?'https://htmlpreview.github.io/?https://raw.githubusercontent.com/haihao0307/guilin-dem-pipeline/'+commit+'/kaopu-unified-human-workbench/skin-cinema-et14/preview.html':'http://127.0.0.1:8765/kaopu-unified-human-workbench/skin-cinema-et14/preview.html');
fs.mkdirSync(OUT,{recursive:true});const R={version:'ET14-S1',url:URL,commit,checks:[],shots:[],controls:[],errors:[],warnings:[],realMobileDevice:false,mobileAcceptanceRequested:false,filmQualityAccepted:false};let browser,page;
function check(name,pass,detail){R.checks.push({name,pass:!!pass,detail});assert(pass,name+' '+JSON.stringify(detail));}
async function pixel(){return page.evaluate(async()=>{cinemaWorkbench.render();const gl=__IDENTITY_QA__.viewer().renderer.getContext(),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);if(gl.getError()!==gl.NO_ERROR)throw Error('WebGL framebuffer error');let visible=0;for(let i=0;i<p.length;i+=64)if(p[i]+p[i+1]+p[i+2]>30)visible++;return{hash:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',p)),v=>v.toString(16).padStart(2,'0')).join(''),visible,width:gl.drawingBufferWidth,height:gl.drawingBufferHeight};});}
async function state(){return page.evaluate(async()=>{const m=__IDENTITY_QA__.model(),v=__IDENTITY_QA__.viewer(),hash=async p=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',p)),v=>v.toString(16).padStart(2,'0')).join('');const a=fullCommonWorkbench.archive();delete a.cinemaSkin;return{geometry:await hash(m.positions),faces:await hash(m.faces),archive:JSON.stringify(a),camera:v.cameraState(),lights:v.scene.children.filter(x=>x.isLight).map(x=>({type:x.type,intensity:x.intensity,position:x.position.toArray(),color:x.color.toArray()}))};});}
async function shot(name){const p=await pixel();await page.locator('#canvas').screenshot({path:OUT+'/'+name+'.png',timeout:60000});R.shots.push({name,...p});console.log('SHOT',name);return p;}
async function light(kind){await page.evaluate(kind=>{const v=__IDENTITY_QA__.viewer(),ls=v.scene.children.filter(x=>x.isLight),ds=ls.filter(x=>x.isDirectionalLight);ls.filter(x=>x.isHemisphereLight).forEach(x=>x.intensity=kind==='neutral'?.65:.18);ds.forEach(x=>x.intensity=0);ds[0].color.setRGB(1,1,1);ds[0].intensity=3.2;ds[0].position.fromArray(kind==='neutral'?[-2,3,4]:kind==='grazing'?[4,1,.1]:[-1,2,-4]);v.render();},kind);}
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.on('pageerror',e=>R.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')R.errors.push(m.text());if(m.type()==='warning')R.warnings.push(m.text());});
 await page.goto(URL,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.cinemaWorkbench&&window.fullCommonWorkbench?.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});await page.evaluate(()=>cinemaWorkbench.ready());await page.evaluate(()=>fullFaceTransfer.ready());
 await page.evaluate(async()=>{await fullCommonWorkbench.motion().setMode('shape');cinemaWorkbench.view('face');});
 R.initial=await page.evaluate(()=>cinemaWorkbench.report());check('new shader compiled on same material',R.initial.materials.some(m=>m.compiles>0),R.initial);check('original 89 native named controls retained',await page.evaluate(()=>identityWorkbench.catalog().length===89));check('17 new controls in DOM',await page.locator('[data-cfield]').count()===17);
 const saved=await page.evaluate(()=>fullCommonWorkbench.archive()),original=await state();check('native canvas has real pixels',(await pixel()).visible>100);await page.screenshot({path:OUT+'/entry-desktop.png'});
 for(const view of ['face','nose','oblique']){
  await page.evaluate(view=>cinemaWorkbench.view(view),view);
  for(const kind of ['neutral','grazing']){await light(kind);await page.evaluate(()=>cinemaWorkbench.set({enabled:false}));const a=await state(),p=await shot(view+'-'+kind+'-baseline');await page.evaluate(()=>cinemaWorkbench.set({enabled:true}));const b=await state(),q=await shot(view+'-'+kind+'-candidate');check(view+' '+kind+' exact same native person camera and lights',JSON.stringify(a)===JSON.stringify(b));check(view+' '+kind+' surface changes visible framebuffer',p.hash!==q.hash);}
 }
 await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);await light('neutral');
 for(const id of ['fine','dry','oily','weathered','mature']){await page.evaluate(id=>{cinemaWorkbench.preset(id);cinemaWorkbench.view('face');},id);await shot('preset-'+id);}
 await page.evaluate(()=>cinemaWorkbench.view('nose'));
 // Per-field testing is deliberately separate from artistic approval.
 for(const row of await page.evaluate(()=>cinemaWorkbench.fields)){
  const [key,,lo,hi]=row;await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);await page.evaluate(key=>{if(['foldRelief','foldSpread','compression'].includes(key)){identityWorkbench.skinRecipe('mature');cinemaWorkbench.view('face');}else cinemaWorkbench.view(key==='lipGrain'?'mouth':'nose');},key);
  const prior=await page.evaluate(key=>cinemaWorkbench.report().settings[key],key),next=Math.abs(prior-hi)>Math.abs(prior-lo)?hi:lo;
  const before=await pixel();await page.evaluate(({key,next})=>cinemaWorkbench.set({[key]:next}),{key,next});const after=await pixel();R.controls.push({key,prior,next,pixelsChanged:before.hash!==after.hash});check('real framebuffer responds: '+key,before.hash!==after.hash);console.log('CONTROL',key);
 }
 await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);const archive=await page.evaluate(()=>{cinemaWorkbench.preset('dry');cinemaWorkbench.set({poreSize:1.25,oilFilm:.22});return fullCommonWorkbench.archive();});const h=await pixel();await page.evaluate(()=>cinemaWorkbench.preset('oily'));await page.evaluate(a=>fullCommonWorkbench.restore(a),archive);check('complete archive recreates surface pixels',(await pixel()).hash===h.hash);check('complete archive recreates settings',JSON.stringify(await page.evaluate(()=>cinemaWorkbench.report().settings))===JSON.stringify(archive.cinemaSkin.settings));
 const bad=JSON.parse(JSON.stringify(archive));bad.cinemaSkin.settings.poreSize=100;check('bad archive rejected',await page.evaluate(a=>{try{fullCommonWorkbench.restore(a);return false}catch{return true}},bad));check('bad archive keeps previous pixels',(await pixel()).hash===h.hash);
 const legacy=JSON.parse(JSON.stringify(archive));delete legacy.cinemaSkin;await page.evaluate(a=>fullCommonWorkbench.restore(a),legacy);check('old archive opts out rather than changing identity',!(await page.evaluate(()=>cinemaWorkbench.report().settings.enabled)));
 await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);await page.evaluate(()=>cinemaWorkbench.set({enabled:false}));const baselineHash=(await pixel()).hash;for(let i=0;i<3;i++){await page.evaluate(()=>cinemaWorkbench.set({enabled:true}));await pixel();await page.evaluate(()=>cinemaWorkbench.set({enabled:false}));check('repeat baseline toggle '+i,(await pixel()).hash===baselineHash);}
 await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);for(const recipe of ['freckles','acne','scar']){await page.evaluate(recipe=>identityWorkbench.skinRecipe(recipe),recipe);const before=await state();await page.evaluate(()=>cinemaWorkbench.set({hydration:.8}));const after=await state();check('retained identity archive and geometry '+recipe,before.geometry===after.geometry&&before.faces===after.faces&&before.archive===after.archive);await shot('identity-'+recipe);}
 await page.evaluate(a=>fullCommonWorkbench.restore(a),saved);const end=await state();check('all original geometry and index bytes unchanged',original.geometry===end.geometry&&original.faces===end.faces);check('all original archive fields preserved',original.archive===end.archive);check('single canvas',await page.locator('canvas').count()===1);check('no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));R.final=await page.evaluate(()=>cinemaWorkbench.report());check('no JavaScript WebGL errors',R.errors.length===0,R.errors);
 if(commit){const raw='https://raw.githubusercontent.com/haihao0307/guilin-dem-pipeline/'+commit+'/kaopu-unified-human-workbench/skin-cinema-et14/',res=await fetch(raw+'preview.html'),bytes=Buffer.from(await res.arrayBuffer()),manifest=await(await fetch(raw+'BUILD.json')).json();check('actual public bytes match build manifest',res.ok&&bytes.length===manifest.previewBytes&&crypto.createHash('sha256').update(bytes).digest('hex')===manifest.previewSHA256);R.publicBuild=manifest;}
 await page.screenshot({path:OUT+'/final-desktop.png'});R.pass=true;
})().catch(e=>{R.pass=false;R.failure=e.stack;console.error(e);process.exitCode=1}).finally(async()=>{if(page&&!R.pass)await page.screenshot({path:OUT+'/failure.png',timeout:15000}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(OUT+'/report.json',JSON.stringify(R,null,2));console.log('ET14_QA',JSON.stringify({pass:R.pass,checks:R.checks.length,controls:R.controls.length,failure:R.failure,errors:R.errors}));});
