/** Local research adapter. Full captured lower body is retained exactly.
 * A bimanual kinematic task does not claim mass feedback or certified skin fit. */
import{BoxingRig}from'../boxing/Motion.mjs';
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),scale=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>scale(a,1/(Math.hypot(...a)||1)),pos=m=>[m[3],m[7],m[11]],rot=m=>[m[0],m[1],m[2],m[4],m[5],m[6],m[8],m[9],m[10]],mv=(m,v)=>[dot(m.slice(0,3),v),dot(m.slice(3,6),v),dot(m.slice(6,9),v)],tr=m=>[m[0],m[3],m[6],m[1],m[4],m[7],m[2],m[5],m[8]],mm=(a,b)=>Array.from({length:9},(_,k)=>{const i=k/3|0,j=k%3;return a[i*3]*b[j]+a[i*3+1]*b[3+j]+a[i*3+2]*b[6+j];});
function basis(f,n){f=unit(f);n=unit(sub(n,scale(f,dot(f,n))));const c=cross(f,n);return[f[0],n[0],c[0],f[1],n[1],c[1],f[2],n[2],c[2]];}
export class CarryUpperBodyAdapter{
 constructor(options){this.rig=new BoxingRig(options);this.h=options.stature;this.armSet=new Set();for(const S of['L','R'])for(let j=0;j<this.rig.count;j++){let p=j;while(p>=0){if(p===this.rig.limbs['arm'+S].a){this.armSet.add(j);break;}p=this.rig.parents[p];}}}
 evaluate(base,{objectPosition=null,halfWidth=this.h*.23/3.4,depth=this.h*.16/3.4,height=this.h*.18/3.4,handReference=null,gripClearance={L:0,R:0},objectForwardOffset=0}={}){
  const r=this.rig;if(!Number.isFinite(objectForwardOffset)||Math.abs(objectForwardOffset)>this.h*.15)throw Error('Bounded forward object offset required');if(!gripClearance||!['L','R'].every(S=>Number.isFinite(gripClearance[S])&&Math.abs(gripClearance[S])<=this.h*.02))throw Error('Finite bounded per-hand clearance required');if(base.posedMatrices.length!==r.count||base.skinMatrices.length!==r.count)throw Error('Native bone count mismatch');
  if(![halfWidth,depth,height].every(x=>Number.isFinite(x)&&x>0))throw Error('Positive finite object dimensions required');
  if(objectPosition&&(!Array.isArray(objectPosition)||objectPosition.length!==3||!objectPosition.every(Number.isFinite)))throw Error('Finite native object position required');
  if(handReference){if(!handReference.names||!handReference.parents||!handReference.restMatrices||handReference.names.length!==r.count||handReference.skinMatrices?.length!==r.count)throw Error('Hand reference needs exact native rest metadata');for(let j=0;j<r.count;j++){if(handReference.names[j]!==r.names[j]||handReference.parents[j]!==r.parents[j])throw Error('Hand reference bone order mismatch');for(let k=0;k<16;k++)if(handReference.restMatrices[j][k]!==r.rest[j][k]||!Number.isFinite(handReference.skinMatrices[j][k]))throw Error('Hand reference rest or matrix mismatch');}}

  for(let j=0;j<r.count;j++){r.posedMatrices[j].set(base.posedMatrices[j]);r.skinMatrices[j].set(base.skinMatrices[j]);}for(let k=0;k<3;k++)r.rootTranslation[k]=base.rootTranslation[k];
  const chest=r.index.get('spine03'),R=rot(r.skinMatrices[chest]),center=objectPosition?.slice()||add(pos(r.posedMatrices[chest]),mv(R,[0,-this.h*.18-objectForwardOffset,-this.h*.035])),hands={};
  const requestedCenter=center.slice();
  // Project one common object target into the intersection of both reach
  // spheres. Never move left/right object grips independently.
  for(let iteration=0;iteration<32;iteration++){let correction=0;for(const S of['L','R']){const sign=S==='L'?1:-1,l=r.limbs['arm'+S],offset=mv(R,[sign*(halfWidth+this.h*(.09-.23/3.4)+gripClearance[S]),-this.h*.026,this.h*.035]),sphereCenter=sub(pos(r.posedMatrices[l.a]),offset),d=sub(center,sphereCenter),distance=Math.hypot(...d),radius=(l.upper+l.lower)*.99;if(distance>radius){const fixed=add(sphereCenter,scale(d,radius/distance));correction=Math.max(correction,distance-radius);for(let k=0;k<3;k++)center[k]=fixed[k];}}if(correction<1e-9)break;}
  for(const S of['L','R']){const sign=S==='L'?1:-1,l=r.limbs['arm'+S],goal=add(center,mv(R,[sign*(halfWidth+this.h*(.09-.23/3.4)+gripClearance[S]),-this.h*.026,this.h*.035])),distance=Math.hypot(...sub(goal,pos(r.posedMatrices[l.a])));if(distance>(l.upper+l.lower)*.99+1e-7)throw Error('Bimanual object target unreachable: reach spheres do not converge');}
  for(const S of['L','R']){const sign=S==='L'?1:-1,limb=r.limbs['arm'+S],shoulder=pos(r.posedMatrices[limb.a]),goal=add(center,mv(R,[sign*(halfWidth+this.h*(.09-.23/3.4)+gripClearance[S]),-this.h*.026,this.h*.035])),pole=add(shoulder,mv(R,[sign*this.h*.25,this.h*.025,-this.h*.18])),solve=r.solveLimb(limb,goal,pole,.995),forward=mv(R,[0,-1,-.15]),palm=mv(R,[-sign,0,0]);r.orientSkin(limb.c,mm(basis(forward,palm),tr(basis(r.hand[S].forward,r.hand[S].palm))));
   // Reference only carries parent-relative hand rotations; it cannot replace
   // the captured root or any globally posed matrix directly.
   if(handReference){for(const j of r.order){if(j===limb.c||!r.names[j].endsWith('.'+S)||!/^(finger|metacarpal)/.test(r.names[j]))continue;const parent=r.parents[j],relative=mm(tr(rot(handReference.skinMatrices[parent])),rot(handReference.skinMatrices[j]));r.orientSkin(j,mm(rot(r.skinMatrices[parent]),relative));}}
   hands[S]={target:goal,wrist:pos(r.posedMatrices[limb.c]),error:Math.hypot(...sub(pos(r.posedMatrices[limb.c]),goal)),reachError:solve.reachError};if(hands[S].error>1e-6)throw Error('Bimanual wrist target violates minimum or maximum reachable distance');
  }
  let protectedDifference=0;for(let j=0;j<r.count;j++)if(!this.armSet.has(j))for(let k=0;k<16;k++)protectedDifference=Math.max(protectedDifference,Math.abs(r.posedMatrices[j][k]-base.posedMatrices[j][k]),Math.abs(r.skinMatrices[j][k]-base.skinMatrices[j][k]));if(protectedDifference!==0)throw Error('Carry adapter altered protected captured body');r.exportNativePose(r.pose);
  return{posedMatrices:r.posedMatrices,skinMatrices:r.skinMatrices,rootTranslation:r.rootTranslation,pose:r.pose,footContacts:base.footContacts,hands,object:{position:center,rotation:R,halfExtents:[halfWidth,depth,height],mode:'bimanual kinematic target'},metrics:{protectedDifference,requestedCenter,targetProjectionM:Math.hypot(...sub(center,requestedCenter)),weightFeedback:false,actualSkinContactCertified:false}};
 }
}
