import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=n=>fs.readFileSync(path.join(root,'src',n),'utf8'),write=(n,s)=>fs.writeFileSync(path.join(root,'src',n),s);
let app=read('app.js');
function replace(old,next){if(!app.includes(old))throw Error('Missing app anchor: '+old.slice(0,90));app=app.replaceAll(old,next);}
replace('const School=globalThis.KaopuSchoolMotion;','const School=globalThis.KaopuSchoolMotion;\nconst FISH_COUNT=School.COUNT;');
for(const [a,b] of [['9*15','9*FISH_COUNT'],['4,15,0','4,FISH_COUNT,0'],['4*4*15','4*4*FISH_COUNT'],['i<15','i<FISH_COUNT'],['length:15','length:FISH_COUNT'],['/15)', '/FISH_COUNT)'],['0,4,15,','0,4,FISH_COUNT,'],['0,15);','0,FISH_COUNT);'],["'15 条 · 独立摆动／跟随／避碰'","'30 条 · 三维错位／局部跟随／避碰'"]])replace(a,b);
replace('this.camera.halfWidth=3.85','this.camera.halfWidth=5.2');replace('on?3.85:.58','on?5.2:.58');
replace('h.state.jaw,h.state.gill,0,0','h.state.jaw,h.state.gill,this.state.school?f.pitch:0,this.state.school?f.roll:0');
replace('float c=cos(root.w),ss=sin(root.w);mat3 rot=mat3(vec3(c,0,-ss),vec3(0,1,0),vec3(ss,0,c));','float c=cos(root.w),ss=sin(root.w),cp=cos(local.z),sp=sin(local.z),cr=cos(local.w),sr=sin(local.w);mat3 rot=mat3(vec3(c*cp,-sp,-ss*cp),vec3(c*sp*cr+ss*sr,cp*cr,-ss*sp*cr+c*sr),vec3(-c*sp*sr+ss*cr,-cp*sr,ss*sp*sr+c*cr));');
const oldAdvance="advance(dt){for(const i of (this.state.school?Array.from({length:FISH_COUNT},(_,i)=>i):[this.state.selected])){const f=this.school.fish[i],opts={...this.state,speed:this.state.speed*f.variant.tempo,eyeYawOffset:this.state.eyeYawOffset+f.variant.eyeOffset,eyeSeed:90401+i*7411};A.update(this.actors[i],dt,opts);}if(this.state.school&&!['REST','IDLE','FIN_FAN','JAW','EYE_TRACK'].includes(this.state.mode))School.update(this.school,dt,this.state.speed*clamp(this.h.state.driveStrength,0,1.6));}";
replace(oldAdvance,"advance(dt){const translating=this.state.school&&!['REST','IDLE','FIN_FAN','JAW','EYE_TRACK'].includes(this.state.mode);if(translating)School.update(this.school,dt,this.state.speed*clamp(this.state.amplitude,0,1.6));for(const i of (this.state.school?Array.from({length:FISH_COUNT},(_,i)=>i):[this.state.selected])){const f=this.school.fish[i],opts={...this.state,speed:this.state.speed*f.variant.tempo,amplitude:this.state.amplitude*(translating?f.gaitAmplitude:1),gaitFrequencyScale:translating?f.gaitFrequency:1,eyeYawOffset:this.state.eyeYawOffset+f.variant.eyeOffset,eyeSeed:90401+i*7411};A.update(this.actors[i],dt,opts);}}");
write('app.js',app);
let instrument=read('instrument.js');const anchor='frequency=(p.frequency||0)*(.65+.35*drive)';if(!instrument.includes(anchor))throw Error('Missing gait frequency anchor');instrument=instrument.replace(anchor,'frequency=(p.frequency||0)*(.65+.35*drive)*clamp(options.gaitFrequencyScale??1,.7,1.35)');write('instrument.js',instrument);
let template=read('workbench.template.html');template=template.replaceAll('15 条','30 条').replaceAll('15条','30条').replaceAll('15 independent','30 independent').replace('鱼群 R12 · 蓝灰鱼群 · 自然注视','鱼群 R12 · 30 条 · 三维群游').replace('SMALL SCHOOL','DYNAMIC SCHOOL').replace('分别计算动作与眼神，尺寸、体型和色调只有小幅差异。','前后、上下错位地游动，按邻鱼保持间距和方向，转向与各自速度衔接。尺寸、体型和色调只有小幅差异。');write('workbench.template.html',template);
let qa=fs.readFileSync(path.join(root,'scripts/verify-runtime.mjs'),'utf8');qa=qa.replaceAll('===15','===30').replaceAll('initial.states===15','initial.states===30').replaceAll('independentPhases===15','independentPhases===30');fs.writeFileSync(path.join(root,'scripts/verify-runtime.mjs'),qa);
console.log('R12 dynamic count, shared3D body/eye transform, gait coupling and UI wired.');
