const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{fileURLToPath,pathToFileURL}=require('node:url'),{execFileSync}=require('node:child_process');
module.exports=async function gnmQA(browser,url,out,externalCheck){
 fs.mkdirSync(out,{recursive:true});const result={passed:false,url,errors:[],checks:[],screenshots:[],sourceSha256:null};let context,page;
 function check(name,passed,detail){result.checks.push({name,passed:!!passed,detail});console.log('[GNM]',passed?'PASS':'FAIL',name);if(!passed)throw Error(name+' '+JSON.stringify(detail));}
 function sha(b){return crypto.createHash('sha256').update(b).digest('hex');}
 try{
  const root=path.resolve(__dirname,'..');
  if(url.startsWith('file:')){const offline=path.join(out,'gnm-offline.html');execFileSync('python3',[path.join(root,'tools/build-offline.py'),'--output',offline,'--assets-dir',path.join(out,'asset-cache'),'--download'],{timeout:180000,maxBuffer:4000000});url=pathToFileURL(offline).href;result.offlineBuild=true;result.sourceSha256=sha(fs.readFileSync(offline));}
  else result.sourceSha256=sha(fs.readFileSync(path.join(root,'index.html')));
  context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});
  const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});if(url.startsWith('http')){result.servedSha256=sha(await response.body());check('served index exactly matches source',result.servedSha256===result.sourceSha256);}
  await page.waitForFunction(()=>window.gnmStudy?.ready||document.querySelector('#error:not([hidden])'),null,{timeout:120000});const failure=await page.locator('#error').evaluate(e=>e.hidden?null:e.textContent);check('model initializes without failure',!failure,failure);
  async function snap(name){await page.evaluate(()=>gnmStudy.freeze());const file=name+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});result.screenshots.push(file);}
  async function frame(){return page.evaluate(()=>{gnmStudy.render();const c=document.getElementById('canvas'),gl=c.getContext('webgl2')||c.getContext('webgl'),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);let blue=0,range=0,min=255,max=0,hash=2166136261;for(let i=0;i<p.length;i+=16){if(p[i+2]>p[i]*1.2&&p[i+2]>70)blue++;min=Math.min(min,p[i]);max=Math.max(max,p[i]);hash=Math.imul(hash^p[i]^p[i+1]^p[i+2],16777619);}return {bluePixelsSampled:blue,range:max-min,pixelHash:hash>>>0,glError:gl.getError(),diagnostics:gnmStudy.getDiagnostics()};});}
  const neutral=await frame();check('full official model dimensions',neutral.diagnostics.identityDim===253&&neutral.diagnostics.expressionDim===383&&neutral.diagnostics.vertices===17821,neutral.diagnostics);check('both full assets pass byte and SHA checks',neutral.diagnostics.assetRecords.length===2&&neutral.diagnostics.assetRecords.every(x=>x.sha256===x.expectedSha256),neutral.diagnostics.assetRecords);check('visible real WebGL head',neutral.glError===0&&neutral.bluePixelsSampled>1000&&neutral.range>30,neutral);await snap('01-neutral');await page.locator('#canvas').screenshot({path:path.join(out,'01-neutral-canvas.png')});
  const neutralPositions=await page.evaluate(()=>gnmStudy.getPositions());
  for(const name of ['identity','expression']){await page.evaluate(n=>gnmStudy.setCase(n),name);const f=await frame();check(name+' has changed finite geometry',f.diagnostics.finite&&await page.evaluate(n=>gnmStudy.getPositions().some((v,i)=>Math.abs(v-n[i])>.001),neutralPositions));check(name+' changes real pixels',f.pixelHash!==neutral.pixelHash&&f.glError===0,f);await snap(name==='identity'?'02-identity':'03-expression');}
  await page.evaluate(()=>{gnmStudy.setCase('neutral');gnmStudy.setParameter('identity',252,1);gnmStudy.setParameter('expression',382,.5);});check('last dimensions remain available',await page.evaluate(()=>gnmStudy.getState().params.identity[252]===1&&gnmStudy.getState().params.expression[382]===.5));
  await page.evaluate(()=>gnmStudy.setCase('neutral'));check('neutral reset exact',await page.evaluate(n=>gnmStudy.getPositions().every((v,i)=>v===n[i]),neutralPositions));
  await page.click('[data-tab="identity"]');await page.locator('[data-param-kind="identity"]').first().focus();await page.locator('[data-param-kind="identity"]').first().press('End');check('visible identity slider writes official parameter',await page.evaluate(()=>gnmStudy.getState().params.identity[0]===3));
  const saved=await page.evaluate(()=>gnmStudy.getState());await page.evaluate(()=>gnmStudy.setCase('expression'));await page.evaluate(s=>gnmStudy.setState(s),saved);check('parameter round trip exact',await page.evaluate(s=>JSON.stringify(gnmStudy.getState().params)===JSON.stringify(s.params),saved));check('invalid short vector rejected atomically',await page.evaluate(()=>{const before=JSON.stringify(gnmStudy.getState().params),s=gnmStudy.getState();s.params.identity=[0];try{gnmStudy.setState(s);return false;}catch{return JSON.stringify(gnmStudy.getState().params)===before;}}));
  await page.evaluate(()=>{gnmStudy.setCase('neutral');gnmStudy.setCamera('three');});await page.evaluate(()=>gnmStudy.setHair(true));await page.click('[data-tab="hair"]');let hd=await page.evaluate(()=>gnmStudy.getDiagnostics().hair);check('hair binds actual skin triangles',hd.finite&&hd.invalidTriangles===0&&hd.minWeight>=-1e-7&&hd.maxSumError<1e-6&&hd.maxRootSurfaceDistance<.00036,hd);const neutralHairHash=hd.rootHash;await snap('06-hair-neutral');await page.evaluate(()=>gnmStudy.setCase('identity'));hd=await page.evaluate(()=>gnmStudy.getDiagnostics().hair);check('hair roots follow changed identity',hd.rootHash!==neutralHairHash&&hd.maxRootSurfaceDistance<.00036,hd);await snap('07-hair-identity');await page.evaluate(()=>gnmStudy.setCase('expression'));check('hair expression remains finite',await page.evaluate(()=>gnmStudy.getDiagnostics().hair.finite));await snap('08-hair-expression');await page.evaluate(()=>gnmStudy.setCase('neutral'));check('hair root neutral reset exact',await page.evaluate(h=>gnmStudy.getDiagnostics().hair.rootHash===h,neutralHairHash));await page.evaluate(()=>gnmStudy.setHair(false));
  await page.evaluate(()=>{gnmStudy.setCase('neutral');gnmStudy.setCamera('side');});await snap('04-side');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>gnmStudy.setCamera('three'));await page.waitForTimeout(250);await snap('05-mobile');check('mobile has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('mobile renders head',(await frame()).bluePixelsSampled>1000);
  await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{gnmStudy.setCase('neutral');gnmStudy.setCamera('three');});await page.waitForTimeout(200);await page.locator('#canvas').screenshot({path:path.join(out,'thumbnail.png')});check('no console or runtime errors',result.errors.length===0,result.errors);result.final=await frame();result.passed=true;
 }catch(error){result.errors.push(error.stack||String(error));if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});}catch{}fs.writeFileSync(path.join(out,'failure.txt'),String(error.stack||error));}
 finally{if(page)try{await page.evaluate(()=>window.gnmStudy?.dispose());}catch{}if(context)await context.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));}
 if(externalCheck)externalCheck('GNM official full-model experiment',result.passed,result);return result;
};
