const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');let playwright;try{playwright=require('playwright')}catch{playwright=require('/opt/codex/cua_node/lib/node_modules/playwright')}
const engine=process.env.SKIN_BROWSER||'chromium',base=process.env.SKIN_URL||'http://127.0.0.1:8765/kaopu-skin-workbench/?local=1';
const hash=x=>crypto.createHash('sha256').update(Buffer.from(new Float32Array(x).buffer)).digest('hex');
(async()=>{const browser=await playwright[engine].launch(engine==='webkit'?{headless:true}:{headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1500,height:1050},acceptDownloads:true});const errors=[],writes=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'){consoleErrors.push(m.text());console.error(m.text());fs.writeFileSync('skin-console-errors.json',JSON.stringify(consoleErrors,null,2));}});page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url())});let fail=true;await page.route('**/assets/mhr-torso-delta.json.gz',async r=>{if(fail){fail=false;await r.fulfill({status:503,body:'QA retry'});}else await r.continue();});await page.goto(base);await page.waitForSelector('#retry:not([hidden])');await page.click('#retry');await page.waitForFunction(()=>window.unifiedWorkbench?.diagnostics().ready,null,{timeout:180000});
const positions=()=>page.evaluate(()=>Array.from(unifiedWorkbench.positions())),reference=()=>page.evaluate(()=>Array.from(skinWorkbench.reference())),profile=()=>page.evaluate(()=>skinWorkbench.profile());const original=hash(await positions()),ref=hash(await reference()),initial=await profile();const diag=await page.evaluate(()=>unifiedWorkbench.diagnostics());assert.equal(diag.vertices,25417);assert.equal(diag.triangles,50624);
const shot=async name=>{await page.waitForTimeout(150);await page.locator('#stage').screenshot({path:'skin-'+name+'.png'});};
await page.screenshot({path:'skin-desktop.png',fullPage:true});const presetPixels=[];
for(const preset of ['porcelain','olive','umber']){await page.click('[data-skin='+preset+']');await page.click('[data-view=face]');await shot(preset+'-face');presetPixels.push(await page.locator('#canvas').screenshot());assert.equal(hash(await positions()),original,'Skin changed geometry');assert.equal(hash(await reference()),ref,'Skin changed reference coordinates');await page.click('[data-view=detail]');await shot(preset+'-detail');}
assert.notDeepEqual(presetPixels[0],presetPixels[1]);assert.notDeepEqual(presetPixels[1],presetPixels[2]);await page.click('[data-skin=olive]');await page.click('[data-view=detail]');await page.click('[data-light=rake]');await shot('rake-detail');const microOn=await page.locator('#canvas').screenshot();await page.locator('#skin-microLayer').uncheck();await shot('micro-off-detail');const microOff=await page.locator('#canvas').screenshot();assert.notDeepEqual(microOn,microOff,'Micro surface has no rendered effect');await page.locator('#skin-microLayer').check();
await page.click('[data-view=face]');for(const light of ['cool','warm','rake','back']){await page.click('[data-light='+light+']');await shot(light+'-face');}
await page.click('[data-light=warm]');await page.locator('#skin-enabled').uncheck();await shot('white-ab');await page.locator('#skin-enabled').check();
const slider=async(id,v)=>page.locator('#'+id).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));},v);
const retainedProfile=await profile();for(const [name,changes]of [['heavy',[['weight',.88]]],['lean',[['weight',.12]]],['muscular',[['muscle',.9]]],['pose',[['turn',30],['arms',25],['knee',45]]],['mhr',[['mhr',.8]]]]){await page.click('#baseline');for(const [id,v]of changes)await slider(id,v);await page.click('[data-view=three]');await shot(name+'-body');await page.click('[data-view=face]');await shot(name+'-neck');assert.equal(hash(await reference()),ref,'Reference drift under '+name);assert.deepEqual(await profile(),retainedProfile,'Skin changes with geometry');assert.equal((await page.evaluate(()=>unifiedWorkbench.diagnostics())).topologySha256,diag.topologySha256);}
await page.click('#baseline');await page.click('[data-view=face]');await shot('reset-face');assert.equal(hash(await positions()),original);const fixedShot=await page.locator('#canvas').screenshot();await page.waitForTimeout(1200);assert.deepEqual(await page.locator('#canvas').screenshot(),fixedShot,'Static field changes with time');for(let n=0;n<20;n++){await page.click('#leave');assert.equal(await page.locator('.workspace').isVisible(),false);await page.click('#resume');await page.click('[data-view=three]');await page.click('[data-view=face]');}assert.equal(hash(await positions()),original);assert.equal(hash(await reference()),ref);assert.deepEqual(await page.locator('#canvas').screenshot(),fixedShot,'Camera return changes deterministic skin');
await page.evaluate(()=>{window.qaExt=document.querySelector('canvas').getContext('webgl2').getExtension('WEBGL_lose_context');qaExt.loseContext()});await page.waitForFunction(()=>unifiedWorkbench.diagnostics().lost);await page.evaluate(()=>qaExt.restoreContext());await page.waitForFunction(()=>!unifiedWorkbench.diagnostics().lost);await shot('context-restored');assert.equal(hash(await positions()),original);assert.equal(hash(await reference()),ref);
const download=page.waitForEvent('download');await page.click('#skin-export');const d=await download;const exported=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(exported.schema,'kaopu-skin-profile/1');assert.deepEqual(exported.skin,retainedProfile);
await page.setViewportSize({width:390,height:844});await page.click('[data-view=face]');await page.screenshot({path:'skin-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const pixel=await page.evaluate(()=>unifiedWorkbench.pixelAudit());assert.ok(pixel.colors>100);assert.equal(pixel.error,0);const stats=await page.evaluate(()=>skinWorkbench.diagnostics());assert.equal(stats.textures,0);assert.equal(stats.contextCount,1);assert.equal(stats.programs,1);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.ok(!consoleErrors.some(x=>/Shader Error|VALIDATE_STATUS|compile|syntax error/i.test(x)),consoleErrors.join('\n'));
fs.writeFileSync('skin-browser-report.json',JSON.stringify({passed:true,engine,version:browser.version(),diag,stats,pixel,presetChangesRendered:true,microSurfaceChangesRendered:true,geometryUnchangedBySkin:true,restPositionStableAcrossBodyAndPose:true,cameraReturnPixelIdentical:true,staticTimePixelIdentical:true,twentyEntryCycles:true,contextRestored:true,skinProfileExport:true,mobileNoOverflow:true,physicalIPhone:false,trueSSS:false,visualAcceptance:'Await human inspection of screenshots; pixel differences are not realism proof',writes,errors,consoleErrors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
