import fs from 'node:fs';
let qr={passed:false,metrics:{changedPoints:[],opportunityPoints:[]},audit:null};try{qr=JSON.parse(fs.readFileSync(new URL('./r045_round78_qa_result.json',import.meta.url),'utf8'))}catch{}
if(!qr.audit?.before||!qr.audit?.after||!qr.audit?.plan||!qr.audit?.rivers)throw new Error('R78 authoritative QA audit grid missing');
const A=qr.audit,{x0,x1,z0,z1,nx,nz}=A,before=A.before,after=A.after,exactChanges=(qr.metrics?.changedPoints||[]).filter(p=>Math.abs(p.change)>1e-6);
let changeMax=0,coarseChanged=0;for(let j=0;j<before.length;j++)for(let i=0;i<before[j].length;i++){const d=after[j][i]-before[j][i];changeMax=Math.max(changeMax,Math.abs(d));if(Math.abs(d)>.002)coarseChanged++}
const plan=A.plan.map(c=>({...c,change:0,r78Changed:false})),changeByKey=new Map(exactChanges.map(p=>[`${p.x},${p.z}`,p.change]));for(const c of plan){const d=changeByKey.get(`${c.x},${c.z}`)||0;c.change=d;c.r78Changed=Math.abs(d)>1e-6}
const profiles=[];const byId=new Map();for(const p of exactChanges){const id=`${p.groupIndex}/${p.index}`;if(!byId.has(id))byId.set(id,[]);byId.get(id).push(p)}for(const [id,pts] of [...byId.entries()].sort((a,b)=>b[1].length-a[1].length).slice(0,4)){pts.sort((a,b)=>a.x-b.x||a.z-b.z);profiles.push({label:`carrier ${id} · ${pts.length} R78 changes`,points:pts.map((q,i)=>[i,q.change,q.x,q.z,q.projected?1:0,q.allowance||0])})}
const data={version:'R045.78',qaContract:'R045.78-safety-projected-concentrated-riser-v1',sourceSha:qr.sourceSha||null,terrain:{x0,x1,z0,z1,nx,nz,before,after},rivers:A.rivers,planSpec:A.planSpec,plan,exactChanges,opportunityPoints:qr.metrics?.opportunityPoints||[],profiles,state:{changeMax,coarseChanged,exactChanged:exactChanges.length,qaPassed:qr.passed===true,opportunities:qr.metrics?.opportunities||0,projected:qr.metrics?.projected||0,maxAllowance:qr.metrics?.maxAllowance??null,maxVsR77:qr.metrics?.maxVsR77??null,largest:qr.metrics?.largest||0,largestSpan:qr.metrics?.largestSpan||0,longRunCount:qr.metrics?.longRunCount||0,cellsInLong:qr.metrics?.cellsInLong||0,maxInc:qr.metrics?.maxInc??null},generatedAt:new Date().toISOString(),source:'R045.78 fixed view uses the authoritative 6 m A/B grid from the same QA. A is R77 predecessor geometry; B adds a bounded zero-mean concentrated-riser profile on the same frozen evidence carrier. Every endpoint is projected into half of the actual predecessor 3 m pair margin to a 1.045 m proof target; orange is physical R78-R77 change, red rings are safety-projected requests, blue-grey is inherited hard drainage. No footprint, family, stair, parcel, drainage or water-state identity is added.'};
fs.writeFileSync(new URL('./r045_round78_audit_cache.mjs',import.meta.url),`export const AUDIT=${JSON.stringify(data)};\n`);console.log(JSON.stringify({version:data.version,vertices:(nx+1)*(nz+1),exactChanged:data.state.exactChanged,projected:data.state.projected,largest:data.state.largest,largestSpan:data.state.largestSpan,longRunCount:data.state.longRunCount,cellsInLong:data.state.cellsInLong,maxInc:data.state.maxInc,qaPassed:data.state.qaPassed,changeMax:data.state.changeMax},null,2));
