const fs=require('fs'),assert=require('node:assert/strict'),crypto=require('crypto'),{chromium}=require('playwright');
const out=process.env.QA_OUT||'qa-eye-e1';fs.mkdirSync(out,{recursive:true});
const root='http://127.0.0.1:8765/kaopu-unified-human-workbench';
const report={commit:process.env.GITHUB_SHA,base:'2702e9482cfd1655411bb0920929872669301334',checks:[],errors:[],shots:[],realGPU:false};let browser,page;
const check=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});assert(pass,name+': '+JSON.stringify(detail));};
const shot=async name=>{await page.screenshot({path:out+'/'+name+'.png'});report.shots.push(name+'.png');};
const pixels=()=>page.evaluate(async()=>{const v=__IDENTITY_QA__.viewer();v.render();const gl=v.renderer.getContext(),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);if(gl.getError())throw Error('Pixel read error');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',p)),v=>v.toString(16).padStart(2,'0')).join('');});
(async()=>{
 const baseline=fs.readFileSync('kaopu-unified-human-workbench/identity-lab/preview.html');check('immutable ET13 preview unchanged',crypto.createHash('sha256').update(baseline).digest('hex')==='99942c121ec46428e980568a6b0b82c5872359bf1a7576f600ac5fa1a4a952ad');
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Shader|WebGLProgram|GL_INVALID/.test(m.text()))report.errors.push(m.text());});
 await page.goto(root+'/identity-lab/preview.html',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__IDENTITY_QA__?.viewer()&&fullCommonWorkbench.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});await page.evaluate(()=>fullFaceTransfer.ready());
 await page.evaluate(()=>{window.__E1Geometry=fullCommonWorkbench.positions().slice();window.__E1Faces=fullCommonWorkbench.faces().slice();window.__E1Archive=fullCommonWorkbench.archive();window.__E1Material=__IDENTITY_QA__.viewer().skin.material;});
 await page.evaluate(()=>{const v=__IDENTITY_QA__.viewer(),g=v.nativeGeometry,f=g.attributes.fEye.array,p=g.attributes.position.array,c=[0,0,0];let n=0;for(let i=0;i<f.length/4;i++)if(f[i*4+2]>.9&&Math.hypot(f[i*4],f[i*4+1])<.45){for(let k=0;k<3;k++)c[k]+=p[i*3+k];n++;}if(!n)throw Error('No native pupil samples');c.forEach((_,k)=>c[k]/=n);window.__E1Center=c;v.camera.position.set(c[0],c[1],c[2]+.16);v.orbit.target.set(...c);v.camera.zoom=1.2;v.camera.updateProjectionMatrix();v.orbit.update();v.render();});
 report.beforeHash=await pixels();await shot('01-native-et13-before');
 report.nativeSurface=await page.evaluate(()=>{const v=__IDENTITY_QA__.viewer(),g=v.nativeGeometry,f=g.attributes.fEye.array,p=g.attributes.position.array,rows=[];for(const side of[0,1])for(const [lo,hi]of[[0,.2],[.3,.5],[.6,.8],[.9,1.1],[1.1,1.4]]){const a=[];for(let i=0;i<f.length/4;i++)if(f[i*4+2]>.9&&f[i*4+3]===side){const r=Math.hypot(f[i*4],f[i*4+1]);if(r>=lo&&r<hi)a.push(p[i*3+2]*1000);}if(a.length)rows.push({side,r:[lo,hi],vertices:a.length,meanFrontMM:a.reduce((s,x)=>s+x,0)/a.length,minFrontMM:Math.min(...a),maxFrontMM:Math.max(...a)});}return {coordinate:'display-space +Z toward viewer; annuli from fixed fEye mapping',rows,shadowMapEnabled:v.renderer.shadowMap.enabled,meshCastShadow:v.mesh.castShadow,meshReceiveShadow:v.mesh.receiveShadow,lights:v.scene.children.filter(o=>o.isLight).map(o=>({type:o.type,intensity:o.intensity,castShadow:o.castShadow,position:o.position.toArray()})),host:v.report()};});
 report.nativeLayers=await page.evaluate(()=>{const m=__IDENTITY_QA__.model(),g=m.gnm,c=m.canonical,B=m.bodyCount,v=__IDENTITY_QA__.viewer(),P=v.nativeGeometry.attributes.position.array,N=v.nativeGeometry.attributes.normal.array,F=v.nativeGeometry.attributes.fEye.array,T=v.nativeGeometry.attributes.csType.array,rows=[];for(const e of m.eyeSurface.eyes)for(const i of e.vertices){const [a,b,t]=c.gnmRecipes[i-B],mat=g.materialId[t>.5?b:a];rows.push({eye:e.side,index:i,material:mat,materialName:g.meta.materialNames?.[mat],componentName:g.meta.componentNames?.[g.componentId[t>.5?b:a]],csType:T[i],fEye:Array.from(F.slice(i*4,i*4+4)),positionMM:Array.from(P.slice(i*3,i*3+3),x=>x*1000),normal:Array.from(N.slice(i*3,i*3+3))});}return{nativeMeta:g.meta,headScale:m.headScale,vertices:rows};});fs.writeFileSync(out+'/native-eye-layer-audit.json',JSON.stringify(report.nativeLayers,null,2));delete report.nativeLayers;
 report.initial=await page.evaluate(async root=>{const [{attachNativeEyeOptics},THREE]=await Promise.all([import(root+'/eye-optics-r01/NativeEyeOptics.mjs'),import(root+'/full/source/registration-vendor/three.module.js')]);window.__E1=attachNativeEyeOptics(__IDENTITY_QA__.viewer().skin,{THREE});return __E1.report();},root);
 report.candidateHash=await pixels();check('native eye candidate changes real framebuffer',report.beforeHash!==report.candidateHash);await shot('02-dense-brown');
 report.compiled=await page.evaluate(()=>__E1.report());check('new eye shader actually compiled',report.compiled.compiles>0,report.compiled);check('single existing host material and canvas',await page.evaluate(()=>__IDENTITY_QA__.viewer().skin.material===__E1Material&&document.querySelectorAll('canvas').length===1));
 await page.evaluate(()=>__E1.enabled(false));check('disable restores exact baseline framebuffer',await pixels()===report.beforeHash);await page.evaluate(()=>__E1.enabled(true));
 report.presets=[];for(const preset of['dense-brown','open-hazel','radial-blue']){await page.evaluate(preset=>__E1.set({preset}),preset);const hash=await pixels();report.presets.push({preset,hash,report:await page.evaluate(()=>__E1.report())});await shot('preset-'+preset);}
 check('three structurally distinct presets change pixels',new Set(report.presets.map(x=>x.hash)).size===3);
 report.teacher=await page.evaluate(async root=>{const [{attachET08PhotoReference},THREE]=await Promise.all([import(root+'/eye-optics-r01/TeacherComparison.mjs'),import(root+'/full/source/registration-vendor/three.module.js')]);window.__E1Teacher=await attachET08PhotoReference(__IDENTITY_QA__.viewer().skin,{THREE});return{source:__E1Teacher.source,refractionReproduced:__E1Teacher.refractionReproduced,textureSHA256:__E1Teacher.textureSHA256};},root);report.teacher.hash=await pixels();await shot('teacher-et08-CC0-reference-only');await page.evaluate(()=>__E1Teacher.dispose());
 await page.evaluate(()=>{__E1.enabled(false);fullFaceTransfer.set({layer:'normal'});});await shot('native-normal-diagnostic');await page.evaluate(()=>__E1.enabled(true));await shot('e1-normal-diagnostic');await page.evaluate(()=>fullFaceTransfer.set({layer:'beauty'}));
 for(const[key,a,b]of[['pupilDiameterMM',2.4,5.8],['irisReliefMM',0,.22],['limbusWidthMM',.15,.7],['wetRoughness',.05,.22]]){await page.evaluate(({key,a})=>__E1.set({[key]:a}),{key,a});const one=await pixels();await page.evaluate(({key,b})=>__E1.set({[key]:b}),{key,b});const two=await pixels();check(key+' changes rendered pixels',one!==two);}
 await page.evaluate(()=>__E1.set({preset:'open-hazel',pupilDiameterMM:3.4,irisReliefMM:.14,limbusWidthMM:.36,wetRoughness:.09}));
 for(const deg of[0,30,60]){await page.evaluate(deg=>{const v=__IDENTITY_QA__.viewer(),c=__E1Center,a=deg*Math.PI/180;v.camera.position.set(c[0]+Math.sin(a)*.16,c[1],c[2]+Math.cos(a)*.16);v.orbit.update();v.render();},deg);await shot('view-'+deg);check('view '+deg+' finite',await page.evaluate(()=>fullCommonWorkbench.positions().every(Number.isFinite)&&__IDENTITY_QA__.viewer().pixelAudit().error===0));}
 check('native positions and indices byte-for-byte untouched',await page.evaluate(()=>{const p=fullCommonWorkbench.positions(),f=fullCommonWorkbench.faces();return p.every((v,i)=>v===__E1Geometry[i])&&f.every((v,i)=>v===__E1Faces[i]);}));
 const invalid=await page.evaluate(()=>{const before=JSON.stringify(__E1.report().parameters);let rejected=false;try{__E1.set({pupilDiameterMM:99});}catch(e){rejected=true;}return rejected&&before===JSON.stringify(__E1.report().parameters);});check('invalid eye setting rejected atomically',invalid);
 await page.evaluate(()=>{__E1.dispose();fullCommonWorkbench.restore(__E1Archive);});check('dispose restores original skin extension',await page.evaluate(()=>!__IDENTITY_QA__.viewer().skin.eyeOptics&&__IDENTITY_QA__.viewer().skin.material===__E1Material));
 check('no JS or shader errors',report.errors.length===0,report.errors);report.pass=true;
})().catch(e=>{report.pass=false;report.error=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{if(page&&!report.pass)await shot('failure').catch(()=>{});if(browser)await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,error:report.error}));});
