import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),parent=path.join(root,'../local-r10');for(const dir of ['src','dist','evidence'])fs.mkdirSync(path.join(root,dir),{recursive:true});
const anchor={taskId:'FISH_R11_BLUE_NATURAL_GAZE_20261001',dispatchTime:new Date().toISOString(),baseSha:'168482e732917324724f72a178c32a43cc9b4593',branch:'work/fish-r11-blue-gaze-20261001',userDirective:'主要在蓝色系里面变化，不要太明显，眼睛动作自然灵动一些',targetObject:'R10 fifteen source-sampled fish',targetDefectOrChange:'Narrow cool blue-gray material variation and irregular gentle eye fixations',allowedPaths:['local-r11','knowledge/fish-motion'],protectedInvariants:['Source compact payload charts/residual/geometry/UV/normals/bindings/atlases','Source spine/fin/gait/44byte tip and school trajectory','Same variant shapes/phase/tempo','Same KFE1 geometry/eye position/light and no invented eyelid','R10 lean CPU release and single-file offline packaging'],authorizedVisualChanges:['Subtle blue family material treatment','Small brightness/saturation variation','Seeded per-fish/per-eye fixation,dwell and short smooth glance; manual controls retained'],acceptanceGates:['Exact source payload and non-eye motion regression','Palette numeric envelope and source texture detail retained','Deterministic gaze, bounded angular velocity, fixation dwell and different fish clocks','REST static reference; reset and manual eye controls','Fresh actual desktop/mobile visual/eye motion QA','Independent verifier','Public HTTP/browser exact build'],visualAcceptance:false,motionAcceptance:false,productionReady:false};fs.writeFileSync(path.join(root,'TASK_ANCHOR.json'),JSON.stringify(anchor,null,2)+'\n');fs.writeFileSync(path.join(root,'AGENTS.md'),'Read ../knowledge/fish-motion/README.md and TASK_ANCHOR.json. Only blue-family material and gaze rhythm change. Preserve source sampling, gait, shapes, KFE1 eye geometry and lean memory. No mouse; independent verifier required.\n');
const edit=(text,from,to)=>{if(!text.includes(from))throw Error('Missing token '+from.slice(0,80));return text.replace(from,to);};
let school=fs.readFileSync(path.join(parent,'src/school.js'),'utf8');school=edit(school,'tones=[[.91,1.02,1.10],[1.08,1.02,.91],[.94,1.07,1.01],[1.03,.98,1.04],[1,1,1]]','tones=[[.965,1.003,1.045],[.953,1.008,1.055],[.973,.997,1.036],[.960,1.012,1.052],[.969,1.002,1.044]]');school=edit(school,'v*(.98+.04*r())):[1,1,1],brightness:i?.92+.17*r():1,saturation:i?.88+.24*r():1','v*(.998+.004*r())):tones[0].slice(),brightness:i?.975+.05*r():1,saturation:i?.915+.03*r():.93');school=edit(school,'eyeOffset:(r()-.5)*.06','eyeOffset:(r()-.5)*.016');fs.writeFileSync(path.join(root,'src/school.js'),school);
let app=fs.readFileSync(path.join(parent,'src/app.js'),'utf8').replaceAll('R10','R11').replaceAll('KFC10','KFC11').replaceAll('__KAOPU_R10__','__KAOPU_R11__');
app=edit(app,'tex=clamp(mix(vec3(gray),tex,vTint.w)*vTint.rgb,0.0,1.0);','tex=mix(vec3(gray),tex,vTint.w);tex=clamp(mix(gray*vec3(.92,1.0,1.075),tex,.28)*vTint.rgb,0.0,1.0);');
app=edit(app,"A.reset(q,'CRUISE',this.state);","A.reset(q,'CRUISE',{...this.state,eyeSeed:90401+i*7411});");app=edit(app,'A.reset(this.actors[i],this.state.mode,this.state);','A.reset(this.actors[i],this.state.mode,{...this.state,eyeSeed:90401+i*7411});');app=edit(app,'eyeYawOffset:this.state.eyeYawOffset+f.variant.eyeOffset','eyeYawOffset:this.state.eyeYawOffset+f.variant.eyeOffset,eyeSeed:90401+i*7411');app=app.replace('01 · 一比一复刻基准','01 · 源采样基准');fs.writeFileSync(path.join(root,'src/app.js'),app);
let instrument=fs.readFileSync(path.join(parent,'src/instrument.js'),'utf8').replaceAll("VERSION:'10.0.0',ABI:'KFC10'","VERSION:'11.0.0',ABI:'KFC11'").replaceAll("'KFS10PK1'","'KFS11PK1'").replaceAll("meta.instrument.abi!=='KFC10'","meta.instrument.abi!=='KFC11'");
const natural=`
// User-authorized animation envelope, not species physiological calibration.
function gazeNoise(seed,cycle,salt){let x=(seed+Math.imul(cycle+1,0x9e3779b9)+Math.imul(salt,0x85ebca6b))|0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return((x^(x>>>16))>>>0)/4294967296;}
function newGaze(seed=90401){return [0,1].map(side=>{const id=(seed+side*13007)|0;return {seed:id,cycle:-1,nextAt:.45+1.7*gazeNoise(id,0,1),started:0,travel:.14,fromYaw:0,fromPitch:0,targetYaw:0,targetPitch:0,yaw:0,yawV:0,pitch:0,pitchV:0};});}
function gazeTarget(g,time,wide){if(time>=g.nextAt){g.cycle++;g.fromYaw=g.targetYaw;g.fromPitch=g.targetPitch;const home=gazeNoise(g.seed,g.cycle,2)<.28;g.targetYaw=home?0:(gazeNoise(g.seed,g.cycle,3)*2-1)*(wide?.125:.047);g.targetPitch=home?0:(gazeNoise(g.seed,g.cycle,4)*2-1)*(wide?.055:.023);g.started=time;g.travel=.12+.10*gazeNoise(g.seed,g.cycle,5);g.nextAt=time+g.travel+1.9+2.5*gazeNoise(g.seed,g.cycle,6);}const u=clamp((time-g.started)/g.travel),ease=u*u*u*(u*(u*6-15)+10);return [lerp(g.fromYaw,g.targetYaw,ease),lerp(g.fromPitch,g.targetPitch,ease)];}
function stepNaturalEyes(h,forcing,options,dt){const s=h.state,r=h.metadata.continuum.eyes,rest=s.mode==='REST',wide=s.mode==='EYE_TRACK',gain=clamp(options.eyeGain??1,0,2.2),yawOffset=Number(options.eyeYawOffset)||0,pitchOffset=Number(options.eyePitchOffset)||0;for(const g of s.gaze){const target=rest?[0,0]:gazeTarget(g,s.time,wide),yaw=target[0]+(wide?0:forcing.eyeYaw*.22),pitch=target[1]+(wide?0:forcing.eyePitch*.22),micro=rest?0:.0007*Math.sin(s.time*.71+(g.seed%37));springStep(g,'yaw',clamp(yaw*gain+micro+yawOffset,-r.gazeLimitYawRad,r.gazeLimitYawRad),170,27,dt);springStep(g,'pitch',clamp(pitch*gain+pitchOffset,-r.gazeLimitPitchRad,r.gazeLimitPitchRad),150,25,dt);}s.eyeYaw=s.gaze[0].yaw;s.eyeYawV=s.gaze[0].yawV;s.eyePitch=s.gaze[0].pitch;s.eyePitchV=s.gaze[0].pitchV;const breath=rest?0:.008*Math.sin(s.time*.37+(s.gaze[0].seed%23));springStep(s,'pupil',clamp(forcing.pupil*gain+(Number(options.pupilBias)||0)+breath,0,1),r.pupilStiffness,r.pupilDamping,dt);}
`;
instrument=edit(instrument,'function newState(meta,mode=\'REST\',options={}){',natural+'\nfunction newState(meta,mode=\'REST\',options={}){');instrument=edit(instrument,'return {time:0,modeTime:0,','return {gaze:newGaze(options.eyeSeed??90401),time:0,modeTime:0,');
const oldLine=instrument.split('\n').find(line=>line.includes('const eyeGain=clamp(options.eyeGain'));if(!oldLine)throw Error('Missing eye update');instrument=edit(instrument,oldLine,'  stepNaturalEyes(h,f,options,dt);');
instrument=edit(instrument,'gazeYaw:animated?h.state.eyeYaw:0,gazePitch:animated?h.state.eyePitch:0','gazeYaw:animated?h.state.gaze[side===1?0:1].yaw:0,gazePitch:animated?h.state.gaze[side===1?0:1].pitch:0');fs.writeFileSync(path.join(root,'src/instrument.js'),instrument);
let template=fs.readFileSync(path.join(parent,'src/workbench.template.html'),'utf8').replaceAll('R10','R11').replaceAll('KFC10','KFC11').replaceAll('>K10<','>K11<').replace('精简运行版 × 15 个体','蓝灰鱼群 · 自然注视').replace('原始 4K 表面光照','蓝灰 4K 表面光照').replace('原色图（无灯光）','蓝灰表面（无灯光）').replace('保留当前 KFE1 眼睛。','蓝灰色调只有细微明暗差别；眼睛会短暂轻扫、停留注视，个体节奏各不相同。保留当前 KFE1 眼睛。');fs.writeFileSync(path.join(root,'src/workbench.template.html'),template);
for(const file of ['verify-runtime.mjs','verify-public.mjs','prepare-publication.mjs']){let code=fs.readFileSync(path.join(parent,'scripts',file),'utf8').replaceAll('R10','R11').replaceAll('r10','r11').replaceAll('KFC10','KFC11').replaceAll('KAOPU_FISH_LEAN_R11.html','KAOPU_FISH_BLUE_GAZE_R11.html');if(file==='verify-runtime.mjs')code=code.replace('KAOPU_FISH_LEAN_R11.html','KAOPU_FISH_BLUE_GAZE_R11.html');fs.writeFileSync(path.join(root,'scripts',file),code);}
console.log(JSON.stringify({initialized:true,taskId:anchor.taskId}));
