import {readGLB,normals,B_SHA,gate} from './source.mjs';import {CompareView} from './fit-view.mjs';import {readColorEvidence} from './color-evidence.mjs';
const $=id=>document.getElementById(id);const state=window.__FIT={version:'B1.0',ready:false,error:null,recipe:null,audit:null,source:null,generated:null,identity:null,colorEvidence:null};let view,worker,ticket=0,file=null,raw=null;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error)}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;setTimeout(()=>$('toast').style.opacity=0,2800)}
function failure(e){worker?.terminate();worker=null;state.error=e.message??String(e);state.ready=false;$('building').hidden=true;status(state.error,true);for(const id of ['exportRecipe','exportAudit'])$(id).disabled=true}
try{view=new CompareView($('view'));state.snapshot=()=>view.snapshot();state.view=view}catch(e){failure(e)}
const digest=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
function reset(){worker?.terminate();worker=null;state.ready=false;state.error=null;state.recipe=null;state.generated=null;state.audit=null;state.source=null;state.identity=null;state.geometryHash=null;state.recipeHash=null;state.colorEvidence=null;file=null;raw=null;view?.clear();$('features').replaceChildren();$('facts').replaceChildren();$('bar').style.width='0%';$('sourceCount').textContent='等待原件';$('fitCount').textContent='等待提取';$('empty').hidden=false;$('building').hidden=true;for(const id of ['exportRecipe','exportAudit','save','colorMode'])$(id).disabled=true}
async function load(selected){if(!view){failure(Error('当前浏览器未提供 WebGL2，原件未读取'));return}const job=++ticket;reset();try{file=selected;status('读取原件并计算 SHA256…');raw=await file.arrayBuffer();const sha256=await digest(raw);if(job!==ticket)return;const mesh=readGLB(raw);state.source=mesh;state.identity={filename:file.name,bytes:raw.byteLength,sha256,slot:sha256===B_SHA?'B':'selected-original',isLockedB:sha256===B_SHA};$('filename').textContent=file.name+' · '+sha256.slice(0,16)+'…';const sourceNormals=normals(mesh.positions,mesh.indices);view.setSource({...mesh,normals:sourceNormals},mesh.bounds);$('empty').hidden=true;$('building').hidden=false;$('buildLabel').textContent='从当前原件提取…';$('sourceCount').textContent=(mesh.indices.length/3).toLocaleString()+' 面 · 完整原件';$('save').disabled=false;$('bar').style.width='5%';
 const color=await readColorEvidence(raw,mesh);if(job!==ticket)return;state.colorEvidence=color.report;status('原件已读取。正在提取面方向、分区及折边候选。');worker=new Worker(new URL('./fit-worker.mjs',import.meta.url),{type:'module'});worker.onerror=e=>failure(Error(e.message||'数值工作线程失败'));worker.onmessage=async({data})=>{if(job!==ticket)return;if(data.type==='progress'){$('bar').style.width=Math.round(data.value*100)+'%';$('buildLabel').textContent=data.label;return}if(data.type==='error'){failure(Error(data.message));return}try{gate(data.generated?.indices.length>0,'生成几何为空');state.recipe=data.recipe;state.generated=data.generated;state.audit=data.audit;state.audit.colorEvidence=state.colorEvidence;state.audit.inputUnchanged=(await digest(raw))===sha256;gate(state.audit.inputUnchanged,'原件字节变化');state.audit.sourceHashAfter=sha256;view.setResult({...mesh,normals:data.sourceNormals,colors:data.sourceColors,regions:data.sourceRegions},data.generated);state.ready=true;$('building').hidden=true;$('bar').style.width='100%';$('fitCount').textContent=(data.generated.indices.length/3).toLocaleString()+' 面 · 字段生成';status('原件 → 测量分区 → 三维字段 → 新拓扑，已运行。\n这是原件特定拟合候选，视觉与地质解释尚未批准。');if(data.audit.generated.boundaryEdges>data.audit.source.boundaryEdges||data.audit.generated.components>data.audit.source.components||data.audit.generated.nonManifoldEdges>0){status('原件拟合已生成，但存在新增边界、分离组件或非流形边，需几何审查。\n未修补未知表面，不能作为成品。',true)}$('summary').textContent='固定步长 '+data.recipe.spacing.toFixed(4)+' 源单位 · 同尺度 / 同光照';for(const id of ['exportRecipe','exportAudit'])$(id).disabled=false;$('colorMode').disabled=!data.recipe.color.measured;facts(data);features(data.recipe);worker.terminate();worker=null;state.recipeHash=await digest(new TextEncoder().encode(JSON.stringify(state.recipe)));state.geometryHash=await digest(data.generated.positions.buffer);state.audit.recipeHash=state.recipeHash;state.audit.generatedPositionHash=state.geometryHash;$('auditText').textContent=auditText();}catch(e){failure(e)}};worker.postMessage({mesh:{positions:mesh.positions,indices:mesh.indices,bounds:mesh.bounds},identity:state.identity,colors:color.colors});
 }catch(e){failure(e)}}
function facts({recipe:r,audit:a}){const rows=[['源表面支持区',r.patches.length.toLocaleString()],['折边候选',r.sourceFacts.sharpEdgeCount.toLocaleString()],['凸台 / 基脚候选',r.features.filter(f=>/凸台|基脚/.test(f.kind)).length],['数值规则大小',(a.recipeBytes/1024).toFixed(1)+' KiB'],['采样 RMS →',a.distance.sourceToFit.rms.toFixed(4)],['采样 RMS ←',a.distance.fitToSource.rms.toFixed(4)]];$('facts').replaceChildren(...rows.map(([k,v])=>{const d=document.createElement('div'),s=document.createElement('small'),b=document.createElement('b');s.textContent=k;b.textContent=v;d.append(s,b);return d}))}
function features(r){const out=$('features');for(const f of [...r.features,...r.creases]){const b=document.createElement('button');b.className='feature';const id=document.createElement('b'),text=document.createTextNode(f.kind),small=document.createElement('small');id.textContent=f.id;small.textContent=f.area?'支持面积 '+f.area.toFixed(2)+' 源单位² / '+f.supportPatches+' 区':'观测折角 '+f.angle.toFixed(1)+'° · 裂隙宽深未确认';b.append(id,text,small);b.onclick=()=>{view.focus(f);toast(f.id+' · 原件位置同步对照')};out.append(b)}}
function auditText(){if(!state.audit)return '尚未运行原件。';const a=state.audit,r=state.recipe;return ['原件 SHA256\n'+state.identity.sha256,'状态：原件特定表面场拟合，人工批准 = false','源单位：按 GLB 坐标；实际测绘尺度未核实','原件表面：'+a.source.triangles+' 面；生成件：'+a.generated.triangles+' 面','配方：'+r.patches.length+' 个定向二次支持区，无源三角索引','固定提取间距：'+r.spacing+'；相机与设备不触发降档','双向采样表面距离：\n'+JSON.stringify(a.distance,null,2),'拓扑：\n'+JSON.stringify({source:a.source,generated:a.generated},null,2),'来源图像分析：\n'+JSON.stringify(state.colorEvidence,null,2),'限制：折边只作为候选；没有确认裂隙宽深、岩性、地质过程或完整 PBR。支持区内存在有限外推，缺失表面不作地质补造，不能据此证明无桥接误差。','本次测量含 '+a.distance.sourceToFit.samples+' / '+a.distance.fitToSource.samples+' 个面中心样本，不能当成全表面最大误差。','原件字节不变：'+a.inputUnchanged,'生成耗时：'+(a.elapsedMs/1000).toFixed(2)+' 秒（本机此次运行）'].join('\n\n')}
function download(name,data){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('exportRecipe').onclick=()=>state.recipe&&download('Landscape_Mother_B_surface_recipe.json',state.recipe);$('exportAudit').onclick=()=>state.audit&&download('Landscape_Mother_B_fit_evidence.json',{...state.audit,identity:state.identity,features:state.recipe.features,creases:state.recipe.creases,limits:state.recipe.limits});
$('source').onchange=e=>e.target.files[0]&&load(e.target.files[0]);for(const event of ['dragenter','dragover'])document.addEventListener(event,e=>{e.preventDefault();document.body.classList.add('dragging')});document.addEventListener('dragleave',()=>document.body.classList.remove('dragging'));document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(e.dataTransfer.files[0])load(e.dataTransfer.files[0])});for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{view.mode=Number(b.dataset.mode);view.selected=-1;view.request();for(const q of document.querySelectorAll('[data-mode]'))q.classList.toggle('on',q===b)};for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view.fit(b.dataset.view);for(const b of document.querySelectorAll('[data-category]'))b.onclick=()=>toast(b.dataset.category==='rock'?'本轮只处理原件 B，未预设岩性':'等待你提供该类别的原件，不载入旧样板');$('light').oninput=e=>{view.angle=Number(e.target.value)*Math.PI/180;view.request()};$('metrics').onclick=()=>{$('auditText').textContent=auditText();$('auditPanel').hidden=false};$('closeAudit').onclick=()=>$('auditPanel').hidden=true;window.addEventListener('fit-error',e=>failure(Error(e.detail)));
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('landscape-mother-custody',1);r.onupgradeneeded=()=>r.result.createObjectStore('originals');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function restore(auto=false){try{const d=await db(),item=await new Promise((resolve,reject)=>{const r=d.transaction('originals').objectStore('originals').get('B');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});d.close();if(!item){if(!auto)status('本浏览器没有 B 保管副本，请选择原 GLB。无需压缩。');return}gate(await digest(await item.file.arrayBuffer())===item.hash,'本机保管副本校验失败');await load(item.file)}catch(e){if(!auto)failure(e)}}
$('restore').onclick=()=>restore();$('save').onclick=async()=>{try{gate(file&&state.identity,'先选择原件');const d=await db(),savedFile=file,hash=state.identity.sha256,key=hash===B_SHA?'B':hash;await new Promise((resolve,reject)=>{const t=d.transaction('originals','readwrite');t.objectStore('originals').put({file:savedFile,hash},key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)});d.close();toast('原件已保存在本浏览器，未上传服务器')}catch(e){failure(e)}};
// Only a previously explicitly stored B original is restored. No network model, demo, or substitute.
restore(true);
