function GeneratorRuntime(){
// B3.1: photo-observed shape relationships with explicitly authored hidden volume.
// Never imports a reference mesh or generated image. All dimensions are authoring choices.
'use strict';
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t;
const smooth=(a,b,x)=>{let t=clamp((x-a)/(b-a));return t*t*(3-2*t)};
function hash(x,y,z,s=0){let h=Math.imul(x|0,374761393)^Math.imul(y|0,668265263)^Math.imul(z|0,2147483647)^Math.imul(s|0,1274126177);h=Math.imul(h^(h>>>13),1274126177);return ((h^(h>>>16))>>>0)/4294967295;}
function noise(x,y,z,s=17){let a=Math.floor(x),b=Math.floor(y),c=Math.floor(z),u=x-a,v=y-b,w=z-c;u=u*u*(3-2*u);v=v*v*(3-2*v);w=w*w*(3-2*w);return mix(mix(mix(hash(a,b,c,s),hash(a+1,b,c,s),u),mix(hash(a,b+1,c,s),hash(a+1,b+1,c,s),u),v),mix(mix(hash(a,b,c+1,s),hash(a+1,b,c+1,s),u),mix(hash(a,b+1,c+1,s),hash(a+1,b+1,c+1,s),u),v),w)*2-1;}
const norm=(x,y,z)=>{let q=Math.hypot(x,y,z)||1;return[x/q,y/q,z/q]};
const sun=norm(-.58,.84,.62);
const poly=[[-10.5,-4.1],[-7.4,-6.1],[-2.0,-6.9],[3.3,-6.25],[7.0,-5.8],[9.65,-3.0],[10.1,.5],[9.45,4.45],[5.8,5.85],[3.7,5.42],[.4,6.62],[-2.3,5.65],[-5.65,5.85],[-7.0,4.25],[-10.3,3.4],[-11,.2]];
function sdPlan(x,z){let d=1e10,inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let ax=poly[j][0],az=poly[j][1],bx=poly[i][0],bz=poly[i][1],ex=bx-ax,ez=bz-az,px=x-ax,pz=z-az,t=clamp((px*ex+pz*ez)/(ex*ex+ez*ez)),qx=px-ex*t,qz=pz-ez*t;d=Math.min(d,qx*qx+qz*qz);if(((az>z)!==(bz>z))&&(x<(bx-ax)*(z-az)/(bz-az)+ax))inside=!inside;}return Math.sqrt(d)*(inside?-1:1)}
function crown(x,z,seed){return 10.0+4.4*Math.exp(-((x-2.0)**2/38+(z+1.5)**2/33))+1.7*Math.exp(-((x+5.3)**2/12+(z+1.8)**2/14))+noise(x*.24,2,z*.24,seed)*.65+noise(x*.69,4,z*.66,seed+4)*.19+.20*Math.sin(x*.5-z*.32);}
function taperAt(y){return 1-.018*smooth(1.3,1.75,y)-.033*smooth(5.4,6.0,y)-.145*smooth(8.7,14.5,y)}
function macroRock(x,y,z,seed){let t=taperAt(y),base=sdPlan((x-.08*Math.sin(y*.43))/t,z/t)*t;
 for(const b of [[-6.6,4.7,2.1,1.00,9.5],[-1.2,5.90,2.25,1.04,11.2],[4.0,5.10,2.4,1.24,12.1],[8.5,2.65,1.15,1.6,7.8]]){
  const dx=Math.abs(x-b[0]+.04*y+.08*Math.sin(y*.68))-b[2],dz=Math.abs(z-b[1])-(b[3]-.03*y),dy=Math.max(-.45-y,y-b[4]);let block=Math.max(dx,dz,dy,(x-b[0])*.27+(z-b[1])*.55-b[3]*.69);base=Math.min(base,block);
 }
 let crest=crown(x,z,seed);crest-=.45*Math.exp(-Math.pow((x+3.1)/.65,2))*smooth(2.2,4.7,z)+.28*Math.exp(-Math.pow((x-4.6)/.9,2))*smooth(2.8,4.9,z);return Math.max(base,y-crest,-.55-y);
}
const layerYs=[.46,.81,1.39,2.57,3.04,4.39,4.66,5.86,6.84,7.91,9.12,9.73,10.92,12.54,13.23];
function buildRecipe(seed){
 const joints=[{x:-6.55,lo:.5,hi:11.8,z:3.4,w:.13,lean:.019},{x:-3.0,lo:3.1,hi:15,z:4.65,w:.17,lean:-.03},{x:.72,lo:0,hi:12.2,z:5.25,w:.15,lean:.014},{x:4.35,lo:1.6,hi:15,z:4.62,w:.13,lean:-.042},{x:7.35,lo:4.5,hi:11.2,z:3.25,w:.18,lean:.027}];
 const caves=[];
 function add(a,y,scale,i){let dx=Math.sin(a),dz=Math.cos(a),lo=0,hi=16;for(let j=0;j<22;j++){let r=(lo+hi)/2;if(macroRock(dx*r,y,dz*r,seed)<0)lo=r;else hi=r}let r=(lo+hi)/2-.20*scale;let sx=(.24+hash(i,2,seed)*.55)*scale,sy=(.25+hash(i,5,seed)*.75)*scale,sz=(.38+hash(i,9,seed)*.58)*scale;const basis=[dz,-dx];caves.push({x:dx*r,y,z:dz*r,dx,dz,tx:basis[0],tz:basis[1],sx,sy,sz,phase:hash(i,11,seed)*6.28});}
 for(let i=0;i<65;i++){let a=(-1.18+hash(i,3,seed)*2.48);if(i>44)a=hash(i,7,seed)*6.283;let y=i<27?4.25+hash(i,17,seed)*4.4:.9+hash(i,19,seed)*10.8;add(a,y,i%23===0?1.4:.78,i);}
 for(let i=65;i<155;i++){let a=-1.08+hash(i,23,seed)*2.3,y=1.1+hash(i,33,seed)*9.8;add(a,y,.43,i);}
 const bins=new Map();for(const h of caves){const R=Math.max(h.sx,h.sy,h.sz)*1.5;for(let z=Math.floor((h.z-R)/2);z<=Math.floor((h.z+R)/2);z++)for(let y=Math.floor((h.y-R)/2);y<=Math.floor((h.y+R)/2);y++)for(let x=Math.floor((h.x-R)/2);x<=Math.floor((h.x+R)/2);x++){let k=x+','+y+','+z;if(!bins.has(k))bins.set(k,[]);bins.get(k).push(h)}}
 function solid(x,y,z){
  const taper=taperAt(y);let top=crown(x,z,seed),d=macroRock(x,y,z,seed),side=d;
  if(d>1.95||d<-2.1)return d;
  if(Math.abs(d)<1.0)d+=noise(x*.32,y*.25,z*.36,seed+47)*.20+noise(x*1.1,y*.72,z*1.2,seed+49)*.035;
  if(side>-.8&&y>.1&&y<13.4){const level=y+.048*x-.038*z+.065*Math.sin(x*.72+z*.6)+.026*Math.sin(x*2.3);let recess=0;for(let k=0;k<layerYs.length;k++){const a=Math.abs(level-layerYs[k]);if(a>.40)continue;let support=smooth(-.40,.22,noise(x*.21,k*.79,z*.23,seed+23));recess=Math.max(recess,(.055+.13*hash(k,8,seed))*Math.exp(-Math.pow(a/(.045+.019*hash(k,9,seed)),2))*support);}d+=recess*(1-smooth(top-.45,top+.02,y));}
  for(const j of joints){if(y<j.lo-.2||y>j.hi+.2||z<j.z-.2)continue;let px=x-j.x-j.lean*(y-6)-.10*Math.sin(y*.9+j.x)-.10*noise(y*1.4,1,j.x,seed+45),w=j.w*(.72+.28*Math.sin(y*2.1+j.x)+.24*noise(y*2,0,j.x,seed+46));let cut=Math.max(Math.abs(px)-w,j.z+.12*Math.sin(y*.7)-z,j.lo-y,y-j.hi);d=Math.max(d,-cut);}
  if(x>7.4&&y>2&&y<12){let cut=Math.max(Math.abs(z+.7-.045*y)-.15,7.1-x,2-y,y-12);d=Math.max(d,-cut)}
  if(z<-4&&y>1.5&&y<13){let cut=Math.max(Math.abs(x+2.1-.02*y)-.14,z+4.4,1.5-y,y-13);d=Math.max(d,-cut)}
  if(y<1.55&&z>3.0){const footVoid=Math.max(Math.abs(x+3.8)-1.0,Math.abs(y-.51)-.52,4.85-z);d=Math.max(d,-footVoid)}
  const list=bins.get(Math.floor(x/2)+','+Math.floor(y/2)+','+Math.floor(z/2));if(list)for(const h of list){let dx=x-h.x,dy=y-h.y,dz=z-h.z,u=(dx*h.tx+dz*h.tz)/h.sx,v=dy/h.sy,w=(dx*h.dx+dz*h.dz)/h.sz;const oval=Math.sqrt(u*u+v*v+w*w);if(oval>1.6)continue;let lobe=1+.17*Math.sin(u*4+v*3+h.phase)+.095*Math.sin(v*5-w*3);let cavity=(oval-lobe)*Math.min(h.sx,h.sy,h.sz);d=Math.max(d,-cavity);}
  if(Math.abs(d)<.28){d+=noise(x*1.27,y*1.13,z*1.24,seed+51)*.065+noise(x*3.05,y*2.63,z*3.1,seed+62)*.022;}
  return d;
 }
 return {seed,solid,crown:(x,z)=>crown(x,z,seed),caves,joints};
}
function meshField(fn,bounds,step,material,withAO=true){
 const min=bounds[0],max=bounds[1],nx=Math.ceil((max[0]-min[0])/step)+1,ny=Math.ceil((max[1]-min[1])/step)+1,nz=Math.ceil((max[2]-min[2])/step)+1,xy=nx*ny,total=xy*nz;if(total>10000000)throw Error('Fixed field exceeds declared budget');const f=new Float32Array(total);let id=0;
 for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){let d=fn(min[0]+x*step,min[1]+y*step,min[2]+z*step);if(!Number.isFinite(d))throw Error('Invalid distance field');f[id++]=Math.abs(d)<step*.006?(d<0?-1:1)*step*.006:d;}
 function sample(x,y,z){let u=(x-min[0])/step,v=(y-min[1])/step,w=(z-min[2])/step,a=Math.floor(u),b=Math.floor(v),c=Math.floor(w);if(a<0||a>=nx-1||b<0||b>=ny-1||c<0||c>=nz-1)return 100;u-=a;v-=b;w-=c;let i=c*xy+b*nx+a;return mix(mix(mix(f[i],f[i+1],u),mix(f[i+nx],f[i+nx+1],u),v),mix(mix(f[i+xy],f[i+xy+1],u),mix(f[i+xy+nx],f[i+xy+nx+1],u),v),w)}
 let orient=[0,1,0];const positions=[],normals=[],attributes=[],indices=[],cache=new Map(),tet=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]],off=[0,1,1+nx,nx,xy,xy+1,xy+1+nx,xy+nx];
 const xyz=i=>{let z=Math.floor(i/xy),s=i-z*xy,y=Math.floor(s/nx);return[min[0]+(s-y*nx)*step,min[1]+y*step,min[2]+z*step]};
 function vertex(a,b){if(a>b)[a,b]=[b,a];let k=a*total+b;if(cache.has(k))return cache.get(k);let t=f[a]/(f[a]-f[b]),pa=xyz(a),pb=xyz(b),x=mix(pa[0],pb[0],t),y=mix(pa[1],pb[1],t),z=mix(pa[2],pb[2],t),e=step*.65,n=norm(sample(x+e,y,z)-sample(x-e,y,z),sample(x,y+e,z)-sample(x,y-e,z),sample(x,y,z+e)-sample(x,y,z-e));let ao=1,shadow=1;
  if(withAO){let occ=0;for(const [h,w]of [[.20,.26],[.45,.24],[.95,.24],[1.8,.20]]){let d=sample(x+n[0]*h,y+n[1]*h,z+n[2]*h);occ+=clamp((h-d)/h)*w}ao=clamp(1-occ,.23,1);if(n[0]*sun[0]+n[1]*sun[1]+n[2]*sun[2]>-.05){for(const h of [.22,.43,.75,1.2,1.8,2.7,4.0,5.6,8,11,15,21]){let d=sample(x+n[0]*.15+sun[0]*h,y+n[1]*.15+sun[1]*h,z+n[2]*.15+sun[2]*h);if(d<-.075){shadow=.0;break}}}}
  let idx=positions.length/3;positions.push(x,y,z);normals.push(...n);attributes.push(ao,shadow,material,0);cache.set(k,idx);return idx;}
 function tri(a,b,c){if(a===b||a===c||b===c)return;let x1=positions[b*3]-positions[a*3],y1=positions[b*3+1]-positions[a*3+1],z1=positions[b*3+2]-positions[a*3+2],x2=positions[c*3]-positions[a*3],y2=positions[c*3+1]-positions[a*3+1],z2=positions[c*3+2]-positions[a*3+2],nx=y1*z2-z1*y2,ny=z1*x2-x1*z2,nz=x1*y2-y1*x2;if(nx*orient[0]+ny*orient[1]+nz*orient[2]<0)[b,c]=[c,b];indices.push(a,b,c)}
 for(let z=0;z<nz-1;z++)for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){let base=z*xy+y*nx+x,ids=off.map(o=>base+o),low=1e9,high=-1e9;for(let i of ids){low=Math.min(low,f[i]);high=Math.max(high,f[i])}if(low>0||high<0)continue;for(let t of tet){let ins=[],out=[];for(let i of t)(f[ids[i]]<0?ins:out).push(ids[i]);if(ins.length===0||out.length===0)continue;orient=[0,0,0];for(let j of out){let q=xyz(j);for(let k=0;k<3;k++)orient[k]+=q[k]/out.length}for(let j of ins){let q=xyz(j);for(let k=0;k<3;k++)orient[k]-=q[k]/ins.length}if(ins.length===1||out.length===1){let s=ins.length===1?ins[0]:out[0],r=ins.length===1?out:ins;tri(vertex(s,r[0]),vertex(s,r[1]),vertex(s,r[2]))}else{let a=vertex(ins[0],out[0]),b=vertex(ins[0],out[1]),c=vertex(ins[1],out[1]),d=vertex(ins[1],out[0]);tri(a,b,c);tri(a,c,d)}}}
 return {positions:new Float32Array(positions),normals:new Float32Array(normals),attributes:new Float32Array(attributes),indices:new Uint32Array(indices),sample,fieldSpec:{grid:[nx,ny,nz],step,total},bounds};
}
function topology(m){const ix=m.indices,p=m.positions,edges=new Map();let volume=0,deg=0;for(let i=0;i<ix.length;i+=3){let a=ix[i],b=ix[i+1],c=ix[i+2];for(let [u,v]of [[a,b],[b,c],[c,a]]){if(u>v)[u,v]=[v,u];let k=u*(p.length/3)+v;edges.set(k,(edges.get(k)||0)+1)}let ax=p[a*3],ay=p[a*3+1],az=p[a*3+2],bx=p[b*3],by=p[b*3+1],bz=p[b*3+2],cx=p[c*3],cy=p[c*3+1],cz=p[c*3+2];volume+=(ax*(by*cz-bz*cy)+ay*(bz*cx-bx*cz)+az*(bx*cy-by*cx))/6;let u=[bx-ax,by-ay,bz-az],v=[cx-ax,cy-ay,cz-az];if(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])<1e-10)deg++;}let boundary=0,non=0;for(let v of edges.values()){if(v===1)boundary++;if(v!==2)non++;}return {vertices:p.length/3,triangles:ix.length/3,boundaryEdges:boundary,nonManifoldEdges:non,degenerateTriangles:deg,signedVolume:volume,closed:boundary===0&&non===0};}
function keepConnectedMain(mesh){
 const nv=mesh.positions.length/3,pa=Int32Array.from({length:nv},(_,i)=>i);const root=i=>{while(pa[i]!==i){pa[i]=pa[pa[i]];i=pa[i]}return i};
 for(let i=0;i<mesh.indices.length;i+=3){let a=root(mesh.indices[i]),b=root(mesh.indices[i+1]),c=root(mesh.indices[i+2]);pa[a]=b;pa[c]=b;}
 const counts=new Map();for(let i=0;i<nv;i++){let r=root(i);counts.set(r,(counts.get(r)||0)+1)}let largest=-1,best=0;for(const [r,n]of counts)if(n>best){best=n;largest=r}
 if(counts.size===1)return {...mesh,constructionCleanup:{discardedNumericalComponents:0,discardedVertices:0}};
 const map=new Int32Array(nv).fill(-1),p=[],n=[],a=[],ix=[];for(let i=0;i<nv;i++)if(root(i)===largest){map[i]=p.length/3;p.push(...mesh.positions.subarray(i*3,i*3+3));n.push(...mesh.normals.subarray(i*3,i*3+3));a.push(...mesh.attributes.subarray(i*4,i*4+4));}
 for(let i=0;i<mesh.indices.length;i+=3)if(map[mesh.indices[i]]>=0)ix.push(map[mesh.indices[i]],map[mesh.indices[i+1]],map[mesh.indices[i+2]]);
 return {...mesh,positions:new Float32Array(p),normals:new Float32Array(n),attributes:new Float32Array(a),indices:new Uint32Array(ix),constructionCleanup:{discardedNumericalComponents:counts.size-1,discardedVertices:nv-best,scope:'authored procedural body only; once at construction; camera independent'}};
}
function soilSampler(mesh){
 const bins=new Map(),p=mesh.positions,ix=mesh.indices,cell=.5;
 for(let i=0;i<ix.length;i+=3){const a=ix[i]*3,b=ix[i+1]*3,c=ix[i+2]*3;let x0=Math.floor(Math.min(p[a],p[b],p[c])/cell),x1=Math.floor(Math.max(p[a],p[b],p[c])/cell),z0=Math.floor(Math.min(p[a+2],p[b+2],p[c+2])/cell),z1=Math.floor(Math.max(p[a+2],p[b+2],p[c+2])/cell);for(let z=z0;z<=z1;z++)for(let x=x0;x<=x1;x++){let k=x+','+z;if(!bins.has(k))bins.set(k,[]);bins.get(k).push(i)}}
 return (x,z)=>{const list=bins.get(Math.floor(x/cell)+','+Math.floor(z/cell));if(!list)return null;let top=-Infinity;for(const i of list){let a=ix[i]*3,b=ix[i+1]*3,c=ix[i+2]*3,ax=p[a],az=p[a+2],bx=p[b],bz=p[b+2],cx=p[c],cz=p[c+2],den=(bz-cz)*(ax-cx)+(cx-bx)*(az-cz);if(Math.abs(den)<1e-12)continue;let u=((bz-cz)*(x-cx)+(cx-bx)*(z-cz))/den,v=((cz-az)*(x-cx)+(ax-cx)*(z-cz))/den,w=1-u-v;if(u<-.000001||v<-.000001||w<-.000001)continue;top=Math.max(top,u*p[a+1]+v*p[b+1]+w*p[c+1]);}return Number.isFinite(top)?top:null;};
}
function transform(m,pos,angle,scale){let ca=Math.cos(angle),sa=Math.sin(angle);for(let i=0;i<m.positions.length;i+=3){let x=m.positions[i]*scale[0],y=m.positions[i+1]*scale[1],z=m.positions[i+2]*scale[2];m.positions[i]=ca*x+sa*z+pos[0];m.positions[i+1]=y+pos[1];m.positions[i+2]=-sa*x+ca*z+pos[2];let nx=m.normals[i]/scale[0],ny=m.normals[i+1]/scale[1],nz=m.normals[i+2]/scale[2],n=norm(ca*nx+sa*nz,ny,-sa*nx+ca*nz);m.normals.set(n,i)}}
function concatenate(list){let nv=list.reduce((s,m)=>s+m.positions.length,0),ni=list.reduce((s,m)=>s+m.indices.length,0),p=new Float32Array(nv),n=new Float32Array(nv),a=new Float32Array(nv/3*4),rest=new Float32Array(nv),ix=new Uint32Array(ni),po=0,io=0;for(const m of list){p.set(m.positions,po);n.set(m.normals,po);a.set(m.attributes,po/3*4);rest.set(m.rest??m.positions,po);for(let i=0;i<m.indices.length;i++)ix[io+i]=m.indices[i]+po/3;po+=m.positions.length;io+=m.indices.length;}return {positions:p,normals:n,attributes:a,rest,indices:ix}}
function tilt(m,ax,az){const cx=Math.cos(ax),sx=Math.sin(ax),cz=Math.cos(az),sz=Math.sin(az);for(const v of [m.positions,m.normals])for(let i=0;i<v.length;i+=3){let x=v[i],y=cx*v[i+1]-sx*v[i+2],z=sx*v[i+1]+cx*v[i+2];v[i]=cz*x-sz*y;v[i+1]=sz*x+cz*y;v[i+2]=z}}
function fragment(s){return meshField((x,y,z)=>{
 let d=Math.max(Math.abs(x+.23*y)-1.15,Math.abs(z-.24*x)-.65,-y-.78,y+.56*x+.16*z-.70,(-x*.55+y*.8+z*.35)-.62,(x*.5+y*.7-z*.3)-.78);d+=noise(x*2,y*1.7,z*2,s)*.06;
 let level=y+.11*x-.06*z;for(let h of [-.53,.05,.43])d+=.10*Math.exp(-Math.pow((level-h)/.055,2))*smooth(-.8,-.1,z);
 let pocket=(Math.hypot((x-.36)/(.25+.10*hash(s,1,7)),(y+.12)/(.32+.06*hash(s,1,11)),(z-.62)/.36)-1)*.27;d=Math.max(d,-pocket);return d;
 },[[-1.65,-1.25,-1.2],[1.65,1.3,1.2]],.085,0,true)}
function groundHeight(x,z){return -.12+.11*noise(x*.3,2,z*.3,86)+.25*Math.exp(-((x/13)**2+(z/9)**2))}
function groundSurfaceHeight(x,z){const step=.25,ax=Math.floor(x/step)*step,az=Math.floor(z/step)*step,u=(x-ax)/step,v=(z-az)/step,a=groundHeight(ax,az),b=groundHeight(ax+step,az),c=groundHeight(ax,az+step),d=groundHeight(ax+step,az+step);return u+v<=1?a*(1-u-v)+b*u+c*v:b*(1-v)+c*(1-u)+d*(u+v-1)}
function makeGround(body,seed){const nx=181,nz=165,step=.25,p=[],n=[],a=[],ix=[];for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){let xx=(x-(nx-1)/2)*step,zz=(z-(nz-1)/2)*step,yy=groundHeight(xx,zz);p.push(xx,yy,zz);let e=.04,nn=norm(-(groundHeight(xx+e,zz)-groundHeight(xx-e,zz))/(2*e),1,-(groundHeight(xx,zz+e)-groundHeight(xx,zz-e))/(2*e));n.push(...nn);let shadow=1;for(let h=0.3;h<30;h+=.44){if(body.sample(xx+sun[0]*h,yy+.12+sun[1]*h,zz+sun[2]*h)<-.07){shadow=0;break}}let dist=Math.max(0,sdPlan(xx,zz));a.push(.82+.18*smooth(0,2,dist),shadow,2,0);}for(let z=0;z<nz-1;z++)for(let x=0;x<nx-1;x++){let aa=z*nx+x,bb=aa+1,cc=aa+nx,dd=cc+1;ix.push(aa,cc,bb,bb,cc,dd)}return {positions:new Float32Array(p),normals:new Float32Array(n),attributes:new Float32Array(a),indices:new Uint32Array(ix)}}
function produce(seed=9031){
 const started=performance.now(),recipe=buildRecipe(seed),notify=(value,label)=>{if(typeof postMessage==='function')postMessage({type:'progress',value,label})};notify(.02,'准备样板');const body=keepConnectedMain(meshField(recipe.solid,[[-12,-1.1,-8],[11.5,16.5,8]],.115,0,true));const bodyAudit=topology(body);if(!bodyAudit.closed||bodyAudit.degenerateTriangles)throw Error('Main rock topology gate failed');notify(.45,'正在完成岩体与基脚');
 const soils=meshField((x,y,z)=>{const top=recipe.crown(x,z),inside=sdPlan(x/.72,z/.72),patch=noise(x*.31,1,z*.30,seed+170),edge=Math.max(inside+.16+Math.max(0,patch-.1)*2.1,(patch-.43)*3.2),thickness=.28+.14*smooth(-.6,.6,noise(x*.42,3,z*.41,seed+172));return Math.max(edge,Math.abs(y-(top-.10+thickness*.5))-thickness*.5);},[[-10,8.0,-6.6],[9.8,16,6.3]],.14,1,false);
 const rockList=[],rockMeta=[];for(let i=0;i<6;i++){let m=fragment(seed+i*131);rockList.push(m)}
 const scatter=[],contactReports=[];for(let i=0;i<44;i++){
 let angle=(-1.6+hash(i,1,seed)*3.5),r=8.1+hash(i,3,seed)*6.9,x=Math.sin(angle)*r,z=Math.cos(angle)*r*.78+1.8;if(sdPlan(x,z)<.6)continue;
 let ss=.32+hash(i,5,seed)*1.05,sc=[ss*(.9+hash(i,7,seed)*.6),ss*(.66+hash(i,9,seed)*.8),ss],prototype=rockList[i%6],m={positions:prototype.positions.slice(),normals:prototype.normals.slice(),attributes:prototype.attributes.slice(),rest:prototype.positions.slice(),indices:prototype.indices.slice()};
 tilt(m,(hash(i,13,seed)-.5)*1.75,(hash(i,15,seed)-.5)*1.05);transform(m,[x,0,z],hash(i,11,seed)*6.283,sc);
 let contact=Infinity;for(let k=0;k<m.positions.length;k+=3)contact=Math.min(contact,m.positions[k+1]-groundSurfaceHeight(m.positions[k],m.positions[k+2]));const shift=-contact-.035;
 for(let k=0;k<m.positions.length;k+=3){m.positions[k+1]+=shift;let blocked=false;for(let h=.22;h<26;h+=.58)if(body.sample(m.positions[k]+sun[0]*h,m.positions[k+1]+.10+sun[1]*h,m.positions[k+2]+sun[2]*h)<-.075){blocked=true;break}m.attributes[k/3*4+1]=blocked?0:1;}
 let minimum=Infinity;for(let k=0;k<m.positions.length;k+=3)minimum=Math.min(minimum,m.positions[k+1]-groundSurfaceHeight(m.positions[k],m.positions[k+2]));if(Math.abs(minimum+.035)>.00002)throw Error('Talus ground contact failed');scatter.push(m);contactReports.push({id:'talus-'+i,minVertexClearanceM:minimum,method:'all final vertices against exact final ground triangle planes'});rockMeta.push({id:'talus-'+i,position:[x,shift,z],scale:sc,parent:'main-karst-block-bed-and-pocket-family',roundBoulder:false,placement:'tilted fragment rested by minimum ground clearance; 0.035 m shallow burial',materialCoordinates:'rotated with rock, not world-projected'});
 }
 notify(.68,'正在完成土壤与生长位置');const anchors=[];for(let i=0;i<3100;i++){let x=(hash(i,17,seed)*2-1)*9.5,z=(hash(i,19,seed)*2-1)*5.9;if(sdPlan(x/.68,z/.68)>-.15)continue;let coverage=noise(x*.36,3,z*.37,seed+201);if(coverage<-.24)continue;let top=recipe.crown(x,z),t=.28+.14*smooth(-.6,.6,noise(x*.42,3,z*.41,seed+172));anchors.push({id:'crown-'+i,kind:'crown',position:[x,top+t-.087,z],surfaceNormal:[0,1,0],soilDepth:t,rockParent:'main',waterRetention:clamp(.5+coverage*.3),rooted:true})}
 const pocketMeshes=[],ledgeSites=[];
 for(let i=0;i<body.positions.length/3;i+=37){let x=body.positions[i*3],y=body.positions[i*3+1],z=body.positions[i*3+2];if(y<1.2||y>10.8||z<2.4||body.normals[i*3+1]<.84)continue;if(ledgeSites.some(a=>Math.hypot(x-a[0],y-a[1],z-a[2])<1.4))continue;let radius=.19+.13*hash(i,91,seed);let patch=meshField((px,py,pz)=>(Math.sqrt((px/radius)**2+(py/.075)**2+(pz/(radius*.68))**2)-1)*.12,[[-.45,-.22,-.36],[.45,.25,.36]],.065,1,false);transform(patch,[x,y-.041,z],0,[1,1,1]);pocketMeshes.push(patch);ledgeSites.push([x,y,z]);anchors.push({id:'ledge-'+i,kind:'ledge',position:[x,y+.029,z],surfaceNormal:Array.from(body.normals.subarray(i*3,i*3+3)),soilDepth:.075,rockParent:'main',waterRetention:.73,rooted:true});if(ledgeSites.length>=18)break;
 }
 const allSoil=concatenate([soils,...pocketMeshes]);
 const soilTop=soilSampler(allSoil);let supportedAnchors=[];for(const a of anchors){let y=soilTop(a.position[0],a.position[2]);if(y===null)continue;a.position[1]=y+.002;let xp=soilTop(a.position[0]+.02,a.position[2]),xm=soilTop(a.position[0]-.02,a.position[2]),zp=soilTop(a.position[0],a.position[2]+.02),zm=soilTop(a.position[0],a.position[2]-.02);if([xp,xm,zp,zm].every(v=>v!==null))a.surfaceNormal=norm(-(xp-xm)/.04,1,-(zp-zm)/.04);a.supportEvidence='vertical intersection with final soil triangles';supportedAnchors.push(a)}anchors.length=0;anchors.push(...supportedAnchors);
 const ground=makeGround(body,seed),rubble=concatenate(scatter);const meshes=[body,allSoil,rubble,ground];const kinds=['rock','soil','talus','ground'];const result=meshes.map((m,i)=>({kind:kinds[i],positions:m.positions,normals:m.normals,attributes:m.attributes,rest:m.rest??m.positions,indices:m.indices}));
 const soilAudit=topology(allSoil),talusAudit=topology(rubble);if(!soilAudit.closed||!talusAudit.closed||soilAudit.degenerateTriangles||talusAudit.degenerateTriangles)throw Error('Soil or talus topology gate failed');const totals={vertices:result.reduce((s,m)=>s+m.positions.length/3,0),triangles:result.reduce((s,m)=>s+m.indices.length/3,0),arrayBytes:result.reduce((s,m)=>s+m.positions.byteLength+m.normals.byteLength+m.attributes.byteLength+m.indices.byteLength+(m.rest===m.positions?0:m.rest.byteLength),0)};
 const audit={version:'B3.1',seed,referenceBasis:'three user-supplied photos; visible morphology, not photogrammetric reconstruction',authoringUnits:'metres chosen for sample; photo dimensions not measured',solidVolume:true,body:bodyAudit,mainConnectedComponents:1,constructionCleanup:body.constructionCleanup,soil:soilAudit,talus:talusAudit,groundIsDisplaySupport:true,fieldSpacing:.115,lod:false,textureSampling:false,sourceMeshImported:false,fixedDuringCameraMotion:true,plantSystem:'no vegetation placeholders; only source-photo-informed real soil and rooted habitat interface',vegetationInstances:0,growthAnchors:anchors.length,ledgeSoilSites:ledgeSites.length,detachedRockCount:scatter.length,totals,elapsedMs:performance.now()-started,visualApproved:false,productionReady:false};
 notify(.98,'样板准备完成');return {meshes:result,audit,anchors,rockMeta,contactReports};
}
if(typeof self!=='undefined')self.onmessage=({data})=>{try{const r=produce(data.seed);const buffers=[...new Set(r.meshes.flatMap(m=>[m.positions.buffer,m.normals.buffer,m.attributes.buffer,m.rest.buffer,m.indices.buffer]))];postMessage({type:'complete',...r},buffers)}catch(e){postMessage({type:'error',message:e.message,stack:e.stack})}};
return {produce,buildRecipe,meshField,topology,noise,soilSampler,groundSurfaceHeight};
}
if(typeof module!=='undefined')module.exports=GeneratorRuntime;
