import {parseGLB} from './glb-reader.mjs';
const $=id=>document.getElementById(id),canvas=$('view');
const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true});
const state={model:null,buffer:null,file:null,hash:null,notes:[],point:null,mode:'clay',ready:false,error:null,sourceUploads:0,draws:0,images:[]};
window.__SOURCE={state,clear,report:()=>state.model?{...state.model.report,filename:state.file.name,sha256:state.hash,custodyMode:'Custody Mode',requestedSlotLiteral:'B',category:null,annotations:state.notes,sourcePublished:false,knowledgeDistilled:false}:null};
const status=(text,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error)};
if(!gl){state.error='WebGL2 unavailable';status('当前浏览器未提供 WebGL2。原件无需修改或压缩。',true);throw Error('WebGL2 unavailable')}
const normalize=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n)},sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const vertex=`#version 300 es
precision highp float;layout(location=0) in vec3 position;layout(location=1) in vec3 normal;uniform mat4 viewProjection;out vec3 n;out vec3 wp;void main(){n=normal;wp=position;gl_Position=viewProjection*vec4(position,1.);gl_PointSize=10.;}`;
const fragment=`#version 300 es
precision highp float;in vec3 n;in vec3 wp;out vec4 outColor;uniform vec3 eye;uniform vec3 light;uniform int mode;void main(){if(mode==3){outColor=vec4(.06,.12,.10,1.);return;}if(mode==4){if(length(gl_PointCoord-vec2(.5))>.5)discard;outColor=vec4(.92,.37,.13,1.);return;}vec3 nn=normalize(n);if(!gl_FrontFacing)nn=-nn;if(mode==1){outColor=vec4(nn*.5+.5,1.);return;}float a=max(dot(nn,normalize(light)),0.);float fill=max(dot(nn,normalize(vec3(-.8,.4,-.6))),0.);float rim=pow(1.-abs(dot(nn,normalize(eye-wp))),3.);vec3 col=vec3(.48,.48,.42)*(.34+.76*a+.23*fill)+vec3(.06)*rim;col=pow(max(col,vec3(0.)),vec3(1./2.2));outColor=vec4(col,1.);}`;
function shader(type,text){const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
const uniforms=Object.fromEntries(['viewProjection','eye','light','mode'].map(n=>[n,gl.getUniformLocation(program,n)]));let gpu=[],target=[0,0,0],radius=1,distance=3,yaw=.35,pitch=.22,scheduled=false,eye=[0,0,3],right=[1,0,0],up=[0,1,0],forward=[0,0,-1],vp;
const pointVao=gl.createVertexArray(),pointBuffer=gl.createBuffer();gl.bindVertexArray(pointVao);gl.bindBuffer(gl.ARRAY_BUFFER,pointBuffer);gl.bufferData(gl.ARRAY_BUFFER,12,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.disableVertexAttribArray(1);gl.vertexAttrib3f(1,0,1,0);gl.bindVertexArray(null);
function mult(a,b){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)out[c*4+r]+=a[k*4+r]*b[c*4+k];return out}
function camera(){
 eye=[target[0]+distance*Math.cos(pitch)*Math.sin(yaw),target[1]+distance*Math.sin(pitch),target[2]+distance*Math.cos(pitch)*Math.cos(yaw)];forward=normalize(sub(target,eye));right=normalize(cross(forward,[0,1,0]));up=cross(right,forward);const back=forward.map(v=>-v);
 const view=[right[0],up[0],back[0],0,right[1],up[1],back[1],0,right[2],up[2],back[2],0,-dot(right,eye),-dot(up,eye),-dot(back,eye),1];
 const near=Math.max(radius*.0002,distance-radius*2.5,.00001),far=Math.max(distance+radius*5,near+radius*4),f=1/Math.tan(.60/2),aspect=canvas.width/canvas.height;
 vp=mult([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0],view);
}
function requestDraw(){if(!scheduled){scheduled=true;requestAnimationFrame(draw)}}
function draw(){scheduled=false;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.78,.82,.80,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(!state.model)return;camera();gl.useProgram(program);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.uniformMatrix4fv(uniforms.viewProjection,false,vp);gl.uniform3fv(uniforms.eye,eye);const angle=Number($('light').value)*Math.PI/180;gl.uniform3f(uniforms.light,Math.sin(angle),.85,Math.cos(angle));gl.uniform1i(uniforms.mode,state.mode==='normal'?1:0);
 for(const item of gpu){gl.bindVertexArray(item.vao);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,item.index);if(state.mode==='wire'){gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1)}gl.drawElements(gl.TRIANGLES,item.count,gl.UNSIGNED_INT,0);gl.disable(gl.POLYGON_OFFSET_FILL);if(state.mode==='wire'){gl.uniform1i(uniforms.mode,3);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,item.edges);gl.drawElements(gl.LINES,item.edgeCount,gl.UNSIGNED_INT,0);gl.uniform1i(uniforms.mode,0)}}
 if(state.point){gl.bindVertexArray(pointVao);gl.disable(gl.DEPTH_TEST);gl.uniform1i(uniforms.mode,4);gl.drawArrays(gl.POINTS,0,1);gl.enable(gl.DEPTH_TEST)}gl.bindVertexArray(null);state.draws++;
}
function release(){for(const a of gpu){for(const b of a.buffers)gl.deleteBuffer(b);gl.deleteVertexArray(a.vao)}gpu=[];for(const url of state.images)URL.revokeObjectURL(url);state.images=[];$('images').replaceChildren()}
function clear(){release();state.model=null;state.buffer=null;state.file=null;state.hash=null;state.point=null;state.ready=false;state.error=null;state.notes=[];$('noteList').replaceChildren();$('fileInfo').hidden=true;$('empty').hidden=false;for(const id of ['save','export','addNote'])$(id).disabled=true;$('point').textContent='尚未选点';$('source').value='';status('当前查看已清空。本机已保存副本不会被删除。');requestDraw()}
function makeGpu(model){for(const p of model.primitives){const vao=gl.createVertexArray(),buffers=[];gl.bindVertexArray(vao);for(const [location,data]of [[0,p.positions],[1,p.normals]]){const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,3,gl.FLOAT,false,0,0);state.sourceUploads++}const index=gl.createBuffer();buffers.push(index);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,p.indices,gl.STATIC_DRAW);const edgeData=new Uint32Array(p.indices.length*2);for(let i=0,j=0;i<p.indices.length;i+=3){const [a,b,c]=p.indices.subarray(i,i+3);edgeData.set([a,b,b,c,c,a],j);j+=6}const edges=gl.createBuffer();buffers.push(edges);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,edges);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,edgeData,gl.STATIC_DRAW);state.sourceUploads+=2;gpu.push({vao,buffers,index,edges,count:p.indices.length,edgeCount:edgeData.length})}gl.bindVertexArray(null)}
function fit(view='fit'){if(!state.model)return;const {min,max}=state.model.report.bounds;target=min.map((v,i)=>(v+max[i])/2);radius=Math.hypot(...sub(max,min))/2||1;const aspect=canvas.clientWidth/canvas.clientHeight;distance=radius/Math.sin(.3)*1.1/Math.min(1,aspect);if(view==='front'){yaw=0;pitch=.03}else if(view==='side'){yaw=Math.PI/2;pitch=.02}else if(view==='top'){yaw=0;pitch=Math.PI/2-.005}else{yaw=.36;pitch=.20}requestDraw()}
const digest=async raw=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',raw))].map(x=>x.toString(16).padStart(2,'0')).join('');
let loadId=0;
async function load(file,saved=false){const id=++loadId;clear();state.error=null;status('正在检查原始文件与几何，请稍候……');try{const buffer=await file.arrayBuffer();if(id!==loadId)return;const hash=await digest(buffer);if(id!==loadId)return;const model=parseGLB(buffer);state.model=model;state.buffer=buffer;state.file=file;state.hash=hash;state.notes=[];state.ready=true;makeGpu(model);$('empty').hidden=true;$('fileInfo').hidden=false;$('filename').textContent=file.name;$('hash').textContent='SHA256 '+hash;const r=model.report;const facts=[['原始文件',`${(buffer.byteLength/1e6).toFixed(2)} MB`],['三角面',r.triangles.toLocaleString('en-US')],['顶点',r.vertices.toLocaleString('en-US')],['内嵌图片',`${r.imageCount} 张，仅参考`],['变换后包围尺寸',r.dimensions.map(v=>v.toFixed(3)).join(' × ')+' m*']];$('facts').replaceChildren();for(const [label,value]of facts){const d=document.createElement('div');d.className='fact'+(label==='变换后包围尺寸'?' wide':'');const s=document.createElement('span'),b=document.createElement('b');s.textContent=label;b.textContent=value;d.append(s,b);$('facts').append(d)}for(const k of ['save','export'])$(k).disabled=false;status('原件已打开 · 全部三角面保留。\n* 按文件坐标单位显示，实际物理尺度未核实。');$('custody').textContent=saved?'已从本浏览器本机保管副本恢复，文件 SHA256 已重新计算。':'当前原件只在本次会话中；点击“保存到本机”才写入本浏览器。不会上传服务器。';fit();if($('imageDetails').open)showImages()}catch(e){release();state.model=null;state.buffer=null;state.file=null;state.ready=false;state.error=e.message;status(e.message+'\n原件没有修改，ZIP 无法修复解析限制。',true)}}
$('source').addEventListener('change',e=>{if(e.target.files[0])load(e.target.files[0])});
for(const event of ['dragenter','dragover'])document.addEventListener(event,e=>{e.preventDefault();document.body.classList.add('dragging')});document.addEventListener('dragleave',()=>document.body.classList.remove('dragging'));document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(e.dataTransfer.files[0])load(e.dataTransfer.files[0])});
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{state.mode=b.dataset.mode;for(const item of document.querySelectorAll('[data-mode]'))item.classList.toggle('active',item===b);requestDraw()};for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>fit(b.dataset.view);$('light').oninput=requestDraw;$('clear').onclick=()=>{loadId++;clear()};new ResizeObserver(requestDraw).observe(canvas);
let drag=null;canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(!state.model)return;if(e.shiftKey){pick(e,false);return}drag={x:e.clientX,y:e.clientY,button:e.button};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(drag.button===2){camera();const s=distance*.6/canvas.clientHeight;target=target.map((v,i)=>v-dx*s*right[i]+dy*s*up[i])}else{yaw-=dx*.006;pitch=Math.max(-1.5,Math.min(1.56,pitch+dy*.006))}requestDraw()};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(radius*.04,Math.min(radius*40,distance*Math.exp(e.deltaY*.001)));requestDraw()},{passive:false});canvas.ondblclick=e=>pick(e,true);
function pick(event,recenter){if(!state.model)return;camera();const rect=canvas.getBoundingClientRect(),x=((event.clientX-rect.left)/rect.width*2-1)*Math.tan(.3)*(rect.width/rect.height),y=(1-(event.clientY-rect.top)/rect.height*2)*Math.tan(.3),direction=normalize(forward.map((v,i)=>v+x*right[i]+y*up[i]));let closest=Infinity,found=null;for(let mi=0;mi<state.model.primitives.length;mi++){const mesh=state.model.primitives[mi];for(let k=0;k<mesh.indices.length;k+=3){const a=mesh.positions.subarray(mesh.indices[k]*3,mesh.indices[k]*3+3),b=mesh.positions.subarray(mesh.indices[k+1]*3,mesh.indices[k+1]*3+3),c=mesh.positions.subarray(mesh.indices[k+2]*3,mesh.indices[k+2]*3+3),e1=sub(b,a),e2=sub(c,a),h=cross(direction,e2),det=dot(e1,h);if(Math.abs(det)<1e-12)continue;const s=sub(eye,a),u=dot(s,h)/det;if(u<0||u>1)continue;const q=cross(s,e1),v=dot(direction,q)/det;if(v<0||u+v>1)continue;const t=dot(e2,q)/det;if(t>0&&t<closest){closest=t;found={mesh:mi,triangle:k/3,point:eye.map((v,i)=>v+t*direction[i])}}}}if(found){state.point=found;gl.bindBuffer(gl.ARRAY_BUFFER,pointBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,new Float32Array(found.point));$('point').textContent=`三角面 ${found.triangle}\nXYZ: ${found.point.map(v=>v.toFixed(4)).join(', ')}`;$('addNote').disabled=false;if(recenter)target=[...found.point];requestDraw()}}
$('addNote').onclick=()=>{if(!state.point)return;const note={...state.point,text:$('note').value.trim(),id:state.notes.length+1};state.notes.push(note);const li=document.createElement('li');li.textContent=`#${note.id} 面${note.triangle}: ${note.text||'待讨论'}`;$('noteList').append(li);$('note').value=''};
$('export').onclick=()=>{const report=window.__SOURCE.report();if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Landscape_Mother_Reference_B.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('landscape-mother-custody',1);request.onupgradeneeded=()=>request.result.createObjectStore('originals');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
$('save').onclick=async()=>{if(!state.file)return;$('save').disabled=true;try{const file=state.file,hash=state.hash,db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('originals','readwrite');tx.objectStore('originals').put({file,hash},'B');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});db.close();$('custody').textContent='原始文件已完整保存到本浏览器 B 保管槽，SHA256 '+hash.slice(0,16)+'…。保留你原来的本机文件，浏览器数据不能替代长期备份。'}catch(e){$('custody').textContent='本机保存未完成：'+e.message+'。原文件没有受影响。'}finally{$('save').disabled=!state.ready}};
$('restore').onclick=async()=>{try{const db=await database(),item=await new Promise((resolve,reject)=>{const r=db.transaction('originals').objectStore('originals').get('B');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();if(!item){status('本浏览器尚无保存的 B 原件。');return}if(await digest(await item.file.arrayBuffer())!==item.hash)throw Error('本机原件校验不一致');await load(item.file,true)}catch(e){status('本机恢复失败：'+e.message,true)}};
function showImages(){if(!state.model||state.images.length)return;for(const i of state.model.images){const url=URL.createObjectURL(new Blob([state.buffer.slice(i.offset,i.offset+i.bytes)],{type:i.mimeType}));state.images.push(url);const fig=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=url;img.alt=i.name;img.loading='lazy';caption.textContent=i.name+' · 仅二维来源资料';fig.append(img,caption);$('images').append(fig)}}$('imageDetails').addEventListener('toggle',()=>{if($('imageDetails').open)showImages()});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();state.ready=false;status('图形上下文已丢失，请刷新后重新选择或恢复本机原件。',true)});requestDraw();
