export const B_SHA='8e3ad9b7e35e4acca3cf414f044f1afebcbd9fcf07f101a72413725842de3678';
export const gate=(v,m)=>{if(!v)throw Error(m)};
export const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
export const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
export const unit=v=>{const l=Math.hypot(...v)||1;return v.map(x=>x/l)};
export const sub=(a,b)=>a.map((x,i)=>x-b[i]);
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function mul(a,b){const o=Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
export function normals(p,ix){const n=new Float32Array(p.length);for(let i=0;i<ix.length;i+=3){const ids=[ix[i]*3,ix[i+1]*3,ix[i+2]*3],a=p.subarray(ids[0],ids[0]+3),b=p.subarray(ids[1],ids[1]+3),c=p.subarray(ids[2],ids[2]+3),q=cross(sub(b,a),sub(c,a));for(const j of ids)for(let k=0;k<3;k++)n[j+k]+=q[k]}for(let i=0;i<n.length;i+=3){const l=Math.hypot(n[i],n[i+1],n[i+2])||1;for(let k=0;k<3;k++)n[i+k]/=l}return n}
export function readGLB(raw){
 gate(raw instanceof ArrayBuffer&&raw.byteLength>=28&&raw.byteLength<=268435456,'原件大小不在本轮支持范围');const dv=new DataView(raw);gate(dv.getUint32(0,true)===0x46546c67&&dv.getUint32(4,true)===2,'需要 GLB 2.0');gate(dv.getUint32(8,true)===raw.byteLength,'原件长度不符');let j=null,bin=-1,binSize=0,o=12;
 while(o<raw.byteLength){gate(o+8<=raw.byteLength,'块头截断');const n=dv.getUint32(o,true),t=dv.getUint32(o+4,true);o+=8;gate(n%4===0&&o+n<=raw.byteLength,'块越界');if(t===0x4e4f534a){gate(j===null&&o===20,'JSON 顺序错误');j=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(raw,o,n)))}else if(t===0x004e4942){gate(bin<0,'多个 BIN');bin=o;binSize=n}o+=n}
 gate(j?.asset?.version==='2.0'&&bin>=0,'缺少模型正文');gate(!j.extensionsRequired?.length&&!j.skins?.length&&!j.animations?.length,'本轮支持未压缩静态原件');gate(j.buffers?.length===1&&!j.buffers[0].uri,'禁止加载外部资源');gate(j.buffers[0].byteLength<=binSize&&binSize-j.buffers[0].byteLength<=3,'BIN 长度不符');const views=j.bufferViews??[];
 for(const b of views)gate(!b.extensions&&b.buffer===0&&Number.isInteger(b.byteLength)&&b.byteLength>=0&&Number.isInteger(b.byteOffset??0)&&(b.byteOffset??0)>=0&&(b.byteOffset??0)+b.byteLength<=j.buffers[0].byteLength,'数据区越界');
 const cs={5120:[1,'getInt8'],5121:[1,'getUint8'],5122:[2,'getInt16'],5123:[2,'getUint16'],5125:[4,'getUint32'],5126:[4,'getFloat32']},ds={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
 function acc(id){const a=j.accessors?.[id],b=views[a?.bufferView];gate(a&&b&&!a.sparse&&cs[a.componentType]&&ds[a.type],'不支持的 accessor');const [bytes,get]=cs[a.componentType],n=ds[a.type],stride=b.byteStride??bytes*n,off=a.byteOffset??0;gate(Number.isInteger(a.count)&&a.count>0&&a.count<5000000&&Number.isInteger(off)&&off>=0&&stride>=bytes*n&&off+(a.count-1)*stride+bytes*n<=b.byteLength,'accessor 越界');const out=new Float64Array(a.count*n),start=bin+(b.byteOffset??0)+off;for(let i=0;i<a.count;i++)for(let k=0;k<n;k++){let v=dv[get](start+i*stride+k*bytes,true);gate(Number.isFinite(v),'非有限数值');if(a.normalized){if(a.componentType===5121)v/=255;else if(a.componentType===5123)v/=65535;else if(a.componentType===5120)v=Math.max(-1,v/127);else if(a.componentType===5122)v=Math.max(-1,v/32767);else gate(false,'无效归一化')}out[i*n+k]=v}return {out,n,count:a.count,type:a.componentType}}
 const positions=[],indices=[],parts=[],min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];
 function mat(n){if(n.matrix){gate(n.matrix.length===16&&n.matrix.every(Number.isFinite),'矩阵无效');return n.matrix}const [x,y,z,w]=n.rotation??[0,0,0,1],[a,b,c]=n.scale??[1,1,1],[u,v,t]=n.translation??[0,0,0];return [(1-2*(y*y+z*z))*a,2*(x*y+z*w)*a,2*(x*z-y*w)*a,0,2*(x*y-z*w)*b,(1-2*(x*x+z*z))*b,2*(y*z+x*w)*b,0,2*(x*z+y*w)*c,2*(y*z-x*w)*c,(1-2*(x*x+y*y))*c,0,u,v,t,1]}
 function walk(id,parent,path){gate(j.nodes?.[id]&&!path.has(id)&&path.size<128,'节点循环或无效');const node=j.nodes[id],m=mul(parent,mat(node)),next=new Set(path).add(id);gate(m.every(Number.isFinite),'变换无效');if(node.mesh!==undefined){const mesh=j.meshes?.[node.mesh];gate(mesh?.primitives?.length,'缺少网格');for(const p of mesh.primitives){gate((p.mode??4)===4&&!p.targets&&!p.extensions,'本轮只支持 TRIANGLES');const a=acc(p.attributes.POSITION);gate(a.n===3&&a.type===5126,'位置属性无效');const it=p.indices===undefined?null:acc(p.indices);gate(!it||(it.n===1&&[5121,5123,5125].includes(it.type)),'索引无效');const ii=it?it.out:Uint32Array.from({length:a.count},(_,i)=>i),off=positions.length/3,faceStart=indices.length/3;gate(ii.length%3===0&&off+a.count<=300000&&faceStart+ii.length/3<=600000,'超出分析预算或索引数量错误；未降精度');for(let i=0;i<a.count;i++){const [x,y,z]=a.out.subarray(i*3,i*3+3),p=[m[0]*x+m[4]*y+m[8]*z+m[12],m[1]*x+m[5]*y+m[9]*z+m[13],m[2]*x+m[6]*y+m[10]*z+m[14]];for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[k]);max[k]=Math.max(max[k],p[k]);positions.push(p[k])}}
 const det=m[0]*(m[5]*m[10]-m[9]*m[6])-m[4]*(m[1]*m[10]-m[9]*m[2])+m[8]*(m[1]*m[6]-m[5]*m[2]);gate(Math.abs(det)>1e-24,'奇异变换');for(let i=0;i<ii.length;i+=3){let ids=[ii[i],ii[i+1],ii[i+2]];gate(ids.every(v=>Number.isInteger(v)&&v>=0&&v<a.count),'越界索引');if(det<0)[ids[1],ids[2]]=[ids[2],ids[1]];indices.push(...ids.map(v=>v+off))}
 let uv=null;if(p.attributes.TEXCOORD_0!==undefined){const u=acc(p.attributes.TEXCOORD_0);gate(u.n===2&&u.count===a.count,'UV 数量不符');uv=u.out}const material=j.materials?.[p.material]??{},t=material.pbrMetallicRoughness?.baseColorTexture;parts.push({off,faceStart,faces:ii.length/3,uv,image:t?j.textures?.[t.index]?.source:null,factor:material.pbrMetallicRoughness?.baseColorFactor??[1,1,1,1],texCoord:t?.texCoord??0,transform:t?.extensions??null});}}
 for(const child of node.children??[])walk(child,m,next)}
 const scene=j.scenes?.[j.scene??0];gate(scene?.nodes?.length,'无默认场景');for(const n of scene.nodes)walk(n,[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],new Set());gate(indices.length>0,'空模型');
 const images=(j.images??[]).map(im=>{gate(!im.uri,'禁止外部图片');const b=views[im.bufferView];gate(b&&['image/png','image/jpeg'].includes(im.mimeType),'图片格式无效');return {offset:bin+(b.byteOffset??0),bytes:b.byteLength,type:im.mimeType}});return {positions:new Float32Array(positions),indices:new Uint32Array(indices),bounds:{min,max},parts,images};
}
