import fs from 'node:fs';
import * as K from './r045_round43_kernel.mjs';
import * as R42 from '../round-42/r045_round42_kernel.mjs';
import * as R41 from '../round-41/r045_round41_kernel.mjs';
import * as R40 from '../round-40/r045_round40_kernel.mjs';
import * as R39 from '../round-39/r045_round39_kernel.mjs';
import * as R35 from '../round-35/r045_round35_kernel.mjs';
import * as R30 from '../round-30/r045_round30_kernel.mjs';
const checks=[];const add=(name,pass,value,limit)=>checks.push({name,pass:Boolean(pass),value,limit});const med=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
add('version',K.VERSION==='R045.43',K.VERSION,'R045.43');
add('water_graph_identity_preserved',JSON.stringify(K.nodes)===JSON.stringify(R42.nodes)&&JSON.stringify(K.edges)===JSON.stringify(R42.edges),{nodes:[R42.nodes.length,K.nodes.length],edges:[R42.edges.length,K.edges.length]},'exact inherited graph');
add('terrain_carriers_identity_preserved',JSON.stringify(K.terrainChannels)===JSON.stringify(R42.terrainChannels)&&JSON.stringify(K.outletContinuum)===JSON.stringify(R42.outletContinuum),{terrainChannels:K.terrainChannels.length,outlets:K.outletContinuum.length},'exact inherited carriers');
const rows=[];for(let z=-132;z<=12;z+=6){const row=[];for(let x=-222;x<=120;x+=6)row.push({x,z,n:K.terraceStateAt(x,z),p:R42.terraceStateAt(x,z),r41:R41.terraceStateAt(x,z),b:R40.terraceStateAt(x,z),o:R39.terraceStateAt(x,z),dd:R30.nearestExtendedDrainageDistance(x,z)});rows.push(row)}
const shape=(row,key)=>{let runs=0,best=0,cur=0;for(const c of row){if(c[key].mask>.12){if(!cur)runs++;cur++;best=Math.max(best,cur)}else cur=0}return{runs,best:best*6}};
let dmax=0,change42=0,active=0,oldActive=0,core=0,oldCore=0,incGainCells=0,incThreshold=0,incUnsupported=0,unsafe=0,maxIncGain=0,rowRunsN=0,rowRunsP=0,rowRuns40=0,existingActiveMaskChange=0,existingActiveDeltaChange=0,branchSourceCrossings=0;const groups=[0,0,0],longN=[],longP=[],long40=[];
for(const row of rows){const a=shape(row,'n'),p=shape(row,'p'),b=shape(row,'b');rowRunsN+=a.runs;rowRunsP+=p.runs;rowRuns40+=b.runs;if(a.best)longN.push(a.best);if(p.best)longP.push(p.best);if(b.best)long40.push(b.best);for(const c of row){const {n,p}=c,gi=n.mask-p.mask;dmax=Math.max(dmax,Math.abs(n.delta));change42=Math.max(change42,Math.abs(n.delta-p.delta));if(n.mask>.12){active++;if(n.groupIndex>=0&&n.groupIndex<3)groups[n.groupIndex]++}if(p.mask>.12){oldActive++;existingActiveMaskChange=Math.max(existingActiveMaskChange,Math.abs(n.mask-p.mask));existingActiveDeltaChange=Math.max(existingActiveDeltaChange,Math.abs(n.delta-p.delta))}if(n.mask>.60)core++;if(p.mask>.60)oldCore++;
 if(gi>.004){incGainCells++;maxIncGain=Math.max(maxIncGain,gi);const riverGap=Math.abs(c.z-R30.riverZ(c.x));if(c.dd<=12||R35.broadTerraceEligibility(c.x,c.z)<.03||R35.terraceGroupEnvelope(c.x,c.z)<.035||riverGap<=R30.riverW(c.x)+18)unsafe++}
 if(p.mask<=.12&&n.mask>.12){incThreshold++;if(!n.branchCompanionSupport)incUnsupported++;else if(n.branchCompanionSupport.sourceGain>.004)branchSourceCrossings++}
}}
const active40=rows.flat().filter(c=>c.b.mask>.12).length,burdenN=rowRunsN/(active||1),burdenP=rowRunsP/(oldActive||1),burden40=rowRuns40/(active40||1),medN=med(longN),medP=med(longP),med40=med(long40),maxN=Math.max(...longN),maxP=Math.max(...longP),max40=Math.max(...long40);const geom={deltaMax:dmax,changeFrom42:change42,active,oldActive,core,oldCore,incGainCells,incThreshold,incUnsupported,branchSourceCrossings,maxIncGain,unsafe,groups,rowRunsN,rowRunsP,rowRuns40,fragmentationBurdenN:burdenN,fragmentationBurdenP:burdenP,fragmentationBurden40:burden40,medianLongestN:medN,medianLongestP:medP,medianLongest40:med40,maxLongestN:maxN,maxLongestP:maxP,maxLongest40:max40,existingActiveMaskChange,existingActiveDeltaChange};
add('terrace_geometry_substantive_bounded',dmax>.20&&dmax<.95,geom,'.20m < max delta < .95m');
add('r43_increment_is_material',incGainCells>=2&&incThreshold>=2&&maxIncGain>.004,{incGainCells,incThreshold,maxIncGain},'>=2 frozen-source companion gains and >=2 threshold crossings');
add('r43_crossings_have_frozen_branch_source',incUnsupported===0&&branchSourceCrossings===incThreshold,{incThreshold,incUnsupported,branchSourceCrossings},'every crossing is supported by an already-active R41 familyRepairGain source');
add('r43_change_from_r42_bounded',change42>.001&&change42<.14,change42,'.001m < sampled max change < .14m');
add('existing_r42_active_surface_exact',existingActiveMaskChange<1e-12&&existingActiveDeltaChange<1e-12,{existingActiveMaskChange,existingActiveDeltaChange},'all already-active R42 samples exact');
add('support_does_not_shrink',active>=oldActive,{active,oldActive},'active >= R42');add('core_does_not_shrink',core>=oldCore,{core,oldCore},'core >= R42');
add('fragmentation_regression_repaired',burdenN<=burden40*1.01&&burdenN<burdenP,{burdenN,burdenP,burden40},'must improve R42 and satisfy unchanged <=101% R40 normalized row-run burden gate');
add('row_run_count_not_worse',rowRunsN<=rowRunsP,{rowRunsN,rowRunsP},'branch companions may lengthen a run but may not create additional row runs');
add('longest_ribbons_hold',medN>=medP&&maxN>=maxP,{medianNew:medN,medianOld:medP,maxNew:maxN,maxOld:maxP},'median/max longest ribbons do not shrink');
add('all_three_groups_remain_material',groups.every(n=>n>20),groups,'each >20');add('companion_candidates_stay_safe',unsafe===0,{unsafe},'no incremental gain in hard drainage/outside eligibility/receiver');
let hardCoreActive=0,hardCoreDelta=0;for(const row of rows)for(const c of row)if(c.dd<=12){if(c.n.mask>.01)hardCoreActive++;hardCoreDelta=Math.max(hardCoreDelta,Math.abs(c.n.delta))}add('hard_drainage_core_empty',hardCoreActive===0&&hardCoreDelta<1e-9,{hardCoreActive,hardCoreDelta},'zero support/delta <=12m drainage');
let frameN=0,maxStep=0,maxPhase=0,maxRaw=0;for(let x=-210;x<=110;x+=32)for(let z=-128;z<=2;z+=20){const n=K.terraceStateAt(x,z),p=R42.terraceStateAt(x,z);frameN++;maxStep=Math.max(maxStep,Math.abs(n.step-p.step));maxPhase=Math.max(maxPhase,Math.abs(n.phase-p.phase));maxRaw=Math.max(maxRaw,Math.abs(n.raw-p.raw))}add('r42_stair_frame_exact',maxStep<1e-12&&maxPhase<1e-12&&maxRaw<1e-12,{frameN,maxStep,maxPhase,maxRaw},'step/phase/raw exact');
let far=0,nearDrain=0,receiver=0,outside=0;for(let x=-216;x<=216;x+=36){for(const z of [-300,-220,-170,-145])far=Math.max(far,Math.abs(K.terraceDelta(x,z)));for(const z of [-300,-220,-170,-145,30,70,130])outside=Math.max(outside,Math.abs(K.terraceDelta(x,z)));for(let z=-126;z<=0;z+=18)if(R30.nearestExtendedDrainageDistance(x,z)<=12)nearDrain=Math.max(nearDrain,Math.abs(K.terraceDelta(x,z)));const rz=R30.riverZ(x);for(const dz of [-8,0,8])receiver=Math.max(receiver,Math.abs(K.terraceDelta(x,rz+dz)))}add('far_upstream_untouched',far<1e-9,far,'0');add('support_localized',outside<1e-9,outside,'0');add('drainage_core_protected',nearDrain<1e-9,nearDrain,'0');add('foreground_receiver_unchanged',receiver<1e-9,receiver,'0');
let maxInc=0;for(let x=-210;x<=110;x+=18)for(let z=-126;z<=0;z+=12)maxInc=Math.max(maxInc,Math.abs(K.terraceDelta(x+6,z)-K.terraceDelta(x,z)),Math.abs(K.terraceDelta(x,z+6)-K.terraceDelta(x,z)));add('terrace_increment_not_cliff',maxInc<1.25,maxInc,'<1.25m / 6m');
add('visual_acceptance_locked',K.snapshot.visualAcceptance===false,K.snapshot.visualAcceptance,false);add('parcel_locked',K.snapshot.parcelGenerationEnabled===false,K.snapshot.parcelGenerationEnabled,false);add('water_unknown',K.snapshot.waterStateKnown===false,K.snapshot.waterStateKnown,false);add('production_locked',K.snapshot.productionReady===false,K.snapshot.productionReady,false);
add('logic_error_explicit',K.snapshot.round43?.logicCorrection?.includes('zero incremental gain')&&K.snapshot.round43?.logicCorrection?.includes('not a necessary condition'),K.snapshot.round43?.logicCorrection,'browser/no-op != geometry pass; row-run count is not alone a necessary topology condition');
add('real_world_constraint_explicit',K.snapshot.round43?.constraint?.includes('morphology/QA parameters')&&K.snapshot.round43?.constraint?.includes('cannot provide'),K.snapshot.round43?.constraint,'synthetic parameters and missing field truth explicit');
add('xiaoma_boundary_retained',K.snapshot.round43?.xiaomaBoundary?.includes('do not establish parcel ownership'),K.snapshot.round43?.xiaomaBoundary,'continuity/adjacency/conservation != ownership/hydraulics');add('mrrolord_ordering_only',K.snapshot.round43?.mrRolordUse?.includes('drainage hierarchy')&&K.snapshot.round43?.mrRolordUse?.includes('not agricultural truth'),K.snapshot.round43?.mrRolordUse,'ordering only');add('reference_nonmetric',K.snapshot.round43?.referenceUse?.includes('non-metric')&&K.snapshot.round43?.referenceUse?.includes('No terrace width'),K.snapshot.round43?.referenceUse,'visual morphology only');
const result={version:K.VERSION,passed:checks.every(c=>c.pass),gateCount:checks.length,passedCount:checks.filter(c=>c.pass).length,checks,metrics:{geometry:geom,far,near:nearDrain,receiver,outside,maxInc,qaScope:'full 6m R43 frozen-R41-source companion sweep + unchanged R40-normalized fragmentation burden target + exact active-R42 inheritance + drainage/receiver boundaries'}};fs.writeFileSync(new URL('./r045_round43_qa_result.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.passed)process.exitCode=2;
