import * as THREE from '/native/kaopu-unified-human-workbench/full/source/registration-vendor/three.module.js';
import {meshGuideRoutes} from './MeshGuideRoutes.js';
import {scalpMargin} from './RegionFields.js';
/** 18 intentionally visible diagnostic guides. No claim of reconstructed hidden tie. */
export function attachGuideStructureR30(a){
 const m=a.motion().controller.model,v=a.motion().viewer,g=m.gnm,started=performance.now(),inv=new Int32Array(g.numVertices).fill(-1);m.canonical.gnmRecipes.forEach(([x,y,t],i)=>{if(x===y&&t===0)inv[x]=m.bodyCount+i;});
 const p=v.geometry.attributes.position.array,n=v.geometry.attributes.normal.array,pt=(ar,i)=>new THREE.Vector3().fromArray(ar,i*3),V=q=>new THREE.Vector3(...q),supports=[];
 for(let i=0;i<g.triangles.length;i+=3){const ids=Array.from(g.triangles.subarray(i,i+3));if(ids.some(id=>g.componentId[id]!==0))continue;const ps=ids.map(id=>pt(g.template,id));if(ps.some(q=>scalpMargin(q.toArray())<0))continue;supports.push({ids,t:new THREE.Triangle(...ps)});}
 const oriented=new Set(),usedFaces=new Set();for(let i=0;i<m.faces.length;i+=3){const [x,y,z]=m.faces.slice(i,i+3);oriented.add(`${x},${y},${z}`);oriented.add(`${y},${z},${x}`);oriented.add(`${z},${x},${y}`);}const q=new THREE.Vector3();function surface(target,lift){let d=Infinity,best=null,cp=new THREE.Vector3();for(const s of supports){s.t.closestPointToPoint(target,q);const e=q.distanceToSquared(target);if(e<d){d=e;best=s;cp.copy(q);}}if(best.ids.some(id=>inv[id]<0)||!oriented.has(best.ids.map(id=>inv[id]).join(',')))throw Error('Missing oriented guide surface support');usedFaces.add(best.ids.join(','));const bary=best.t.getBarycoord(cp,new THREE.Vector3()),out=new THREE.Vector3(),normal=new THREE.Vector3();best.ids.forEach((id,k)=>{out.addScaledVector(pt(p,inv[id]),bary.getComponent(k));normal.addScaledVector(pt(n,inv[id]),bary.getComponent(k));});out.addScaledVector(normal.normalize(),lift);return{world:out,neutral:cp};}
 function nearest(target){let id=-1,d=Infinity;for(let i=0;i<g.numVertices;i++){if(inv[i]<0)continue;const e=pt(g.template,i).distanceToSquared(V(target));if(e<d){d=e;id=i;}}return id;}
 const anchors=[nearest([-.07,.32,.015]),nearest([.07,.32,.015]),nearest([0,.395,0])];function frame(ar,mapped=false){const z=anchors.map(id=>pt(ar,mapped?inv[id]:id)),o=z[0].clone().add(z[1]).multiplyScalar(.5),x=z[1].clone().sub(z[0]),sx=x.length();x.normalize();const y=z[2].clone().sub(o).addScaledVector(x,-z[2].clone().sub(o).dot(x)),sy=y.length();y.normalize();return{o,x,y,z:new THREE.Vector3().crossVectors(x,y).normalize(),sx,sy};}const nf=frame(g.template),cf=frame(p,true),scale=(cf.sx/nf.sx+cf.sy/nf.sy)/2;
 const transform=d=>cf.x.clone().multiplyScalar(d.dot(nf.x)*scale).addScaledVector(cf.y,d.dot(nf.y)*scale).addScaledVector(cf.z,d.dot(nf.z)*scale);
 function fairLine(free,pins=new Set(),lambda=.003){const original=free.map(p=>p.clone()),N=free.length,unknown=N-4,H=Array.from({length:unknown},()=>new Float64Array(unknown)),rhs=Array.from({length:unknown},()=>new Float64Array(3));for(let j=1;j<N-1;j++){const ids=[j-1,j,j+1],c=[1,-2,1];for(let x=0;x<3;x++){const row=ids[x]-2;if(row<0||row>=unknown)continue;for(let y=0;y<3;y++){const col=ids[y]-2,w=c[x]*c[y];if(col>=0&&col<unknown)H[row][col]+=w;else for(let k=0;k<3;k++)rhs[row][k]-=w*original[ids[y]].getComponent(k);}}}for(let j=0;j<unknown;j++){const weight=pins.has(j+2)?100:lambda;H[j][j]+=weight;for(let k=0;k<3;k++)rhs[j][k]+=weight*original[j+2].getComponent(k);}for(let j=0;j<unknown;j++){let pivot=j;for(let k=j+1;k<unknown;k++)if(Math.abs(H[k][j])>Math.abs(H[pivot][j]))pivot=k;[H[j],H[pivot]]=[H[pivot],H[j]];[rhs[j],rhs[pivot]]=[rhs[pivot],rhs[j]];const div=H[j][j];for(let k=j;k<unknown;k++)H[j][k]/=div;for(let k=0;k<3;k++)rhs[j][k]/=div;for(let r=0;r<unknown;r++){if(r===j)continue;const mul=H[r][j];for(let k=j;k<unknown;k++)H[r][k]-=mul*H[j][k];for(let k=0;k<3;k++)rhs[r][k]-=mul*rhs[j][k];}}for(let j=0;j<unknown;j++)free[j+2].set(...rhs[j]);return free;}
 const bodyTriangles=[];for(let i=0;i<v.geometry.index.array.length;i+=3)bodyTriangles.push(new THREE.Triangle(...[0,1,2].map(k=>pt(p,v.geometry.index.array[i+k]))));let contactTargets=0,maxTargetAdjustment=0;function bodyTarget(neutral,fallback,radial=false){const side=neutral[2]>=0?1:-1,r=radial?V([neutral[0],0,neutral[2]]).normalize():V([0,0,side]),start=radial?V([0,neutral[1],0]).add(r):V([neutral[0],neutral[1],side]),origin=cf.o.clone().add(transform(start.sub(nf.o))),direction=transform(r.negate()).normalize(),ray=new THREE.Ray(origin,direction),hit=new THREE.Vector3();let best=null,normal=null,dist=Infinity;for(const tri of bodyTriangles){if(ray.intersectTriangle(tri.a,tri.b,tri.c,false,hit)){const d=hit.distanceToSquared(origin);if(d<dist){dist=d;best=hit.clone();normal=tri.getNormal(new THREE.Vector3());}}}if(!best)return fallback;if(normal.dot(direction)>0)normal.negate();const offset=best.addScaledVector(normal,.007);maxTargetAdjustment=Math.max(maxTargetAdjustment,offset.distanceTo(fallback));contactTargets++;return offset;}
 const routes=meshGuideRoutes(v.geometry);const definitions=[];for(let i=0;i<6;i++){const x=(i-2.5)*.018;definitions.push({region:'upper-sweep',color:0xffbc52,root:[x,.345,.085],surface:[ [x*.9,.379,.018],[x*.6,.342,-.074] ],tail:[[x*.3,.28,-.12],[x*.9,.14,-.15],[x*1.7,-.13,-.17]]});}
 for(const sign of[-1,1])for(let i=0;i<2;i++)definitions.push({region:'ear-side',color:0x48dfde,root:[sign*.067,.34,.035-i*.03],surface:[[sign*.077,.322,-.012],[sign*.078,.275,-.069]],tail:sign<0?[[sign*.10,.21,-.07],[sign*.125,.11,.13],[sign*(.10+i*.045),-.12,.17]]:[[sign*.09,.20,-.12],[sign*.12,.08,-.15],[sign*(.11+i*.025),-.14,-.16]]});
 for(let i=0;i<6;i++){const x=(i-2.5)*.02,front=i<2;definitions.push({region:'lower-curtain',color:0x8ed66a,root:[x,.305,-.075],surface:[[x,.28,-.09],[x,.255,-.095]],tail:front?[[i===1?-.085:-.10,.20,i===1?-.055:-.09],[i===1?-.12:-.125,.09,.13],[-.085-i*.045,-.16,.175]]:[[x*1.5,.18,-.135],[x*2,.05,-.15],[x*2.3,-.18,-.165]]});}
 for(const sign of[-1,1])definitions.push({region:'temple-wisp',color:0xe886ef,root:[sign*.06,.34,.055],surface:[[sign*.072,.329,.052],[sign*.078,.313,.048]],tail:[[sign*.082,.303,.043],[sign*.083,.292,.05],[sign*.079,.276,.049]]});
 const count=definitions.length,surfaceSegments=20,segments=64,per=segments+1,positions=new Float32Array(count*per*6),group=new THREE.Group();group.name='18 colour-coded structural guides (diagnostic thickness)';const records=[];
 definitions.forEach((d,i)=>{const prefix=new THREE.CatmullRomCurve3([V(d.root),...d.surface.map(V)],false,'centripetal'),dense=[];let end;for(let j=0;j<=128;j++){const u=j/128,r=surface(prefix.getPointAt(u),.00002+.004*(1-Math.exp(-u*16)));dense.push(r.world);end=r;}
  function resamplePolyline(ps,count){const lengths=[0];for(let j=1;j<ps.length;j++)lengths.push(lengths[j-1]+ps[j].distanceTo(ps[j-1]));const out=[];let k=1;for(let j=0;j<=count;j++){const d=lengths.at(-1)*j/count;while(k<lengths.length-1&&lengths[k]<d)k++;const u=(d-lengths[k-1])/Math.max(1e-12,lengths[k]-lengths[k-1]);out.push(ps[k-1].clone().lerp(ps[k],u));}return out;}
  const points=resamplePolyline(dense,surfaceSegments),joinTangent=points.at(-1).clone().sub(points.at(-2)).normalize(),tailPoints=[points.at(-1),points.at(-1).clone().addScaledVector(joinTangent,d.region==='temple-wisp'?.008:.03),...d.tail.map(q=>{const authored=end.world.clone().add(transform(V(q).sub(end.neutral)));return d.region==='temple-wisp'?authored:bodyTarget(q,authored);})],tangents=tailPoints.map((q,k)=>k<=1?joinTangent.clone():k===tailPoints.length-1?q.clone().sub(tailPoints[k-1]).normalize():tailPoints[k+1].clone().sub(tailPoints[k-1]).normalize()),handles=tailPoints.map((q,k)=>.36*Math.min(k>0?q.distanceTo(tailPoints[k-1]):Infinity,k<tailPoints.length-1?q.distanceTo(tailPoints[k+1]):Infinity)),path=new THREE.CurvePath();
  for(let k=0;k<tailPoints.length-1;k++){const curve=new THREE.CubicBezierCurve3(tailPoints[k],tailPoints[k].clone().addScaledVector(tangents[k],handles[k]),tailPoints[k+1].clone().addScaledVector(tangents[k+1],-handles[k+1]),tailPoints[k+1]);curve.arcLengthDivisions=256;path.add(curve);}path.arcLengthDivisions=1024;let free=path.getSpacedPoints(segments-surfaceSegments);free=fairLine(free);free=resamplePolyline(free,segments-surfaceSegments);if(d.region!=='temple-wisp'){const skin=routes.route([points.at(-1),...tailPoints.slice(2,-1)],{clearance:(i===6||i===7)?.018:.012}),release=skin.at(-1),axis=transform(V([0,0,d.tail.at(-1)[2]>=0?1:-1])).normalize(),finish=tailPoints.at(-1).clone();finish.addScaledVector(axis,Math.max(0,release.clone().sub(finish).dot(axis))+(i===11?.03:.02));const down=transform(V([0,-1,0])).normalize(),releaseT=skin.at(-1).clone().sub(skin.at(-2)).normalize(),hang=new THREE.CubicBezierCurve3(release,release.clone().addScaledVector(releaseT,.045),finish.clone().addScaledVector(down,-.07),finish);skin.push(...hang.getSpacedPoints(24).slice(1));free=resamplePolyline(skin,segments-surfaceSegments);free[0].copy(points.at(-1));const ds=free[1].distanceTo(free[0]);free[1].copy(free[0]).addScaledVector(joinTangent,ds);free=fairLine(free);for(let pass=0;pass<6;pass++){const pins=new Set(),front=d.tail.at(-1)[2]>=0,axis=transform(V([0,0,front?1:-1])).normalize();for(let j=2;j<free.length;j++){const rel=free[j].clone().sub(cf.o),neutral=nf.o.clone().addScaledVector(nf.x,rel.dot(cf.x)/scale).addScaledVector(nf.y,rel.dot(cf.y)/scale).addScaledVector(nf.z,rel.dot(cf.z)/scale);if(neutral.y>.145&&i!==7&&i!==11)continue;const neck=neutral.y>.145,target=bodyTarget(neck?neutral.toArray():[neutral.x,neutral.y,front?.2:-.2],free[j],neck),constraintAxis=neck?transform(V([neutral.x,0,neutral.z])).normalize():axis;if(free[j].clone().sub(target).dot(constraintAxis)<0){free[j].copy(target);pins.add(j);}}if(!pins.size)break;free=fairLine(free,pins);}free=resamplePolyline(free,segments-surfaceSegments);}points.push(...free.slice(1));
  const turns=[],curvatures=[],lens=[];for(let j=1;j<points.length;j++)lens.push(points[j].distanceTo(points[j-1]));for(let j=1;j<points.length-1;j++){const a=points[j].clone().sub(points[j-1]),b=points[j+1].clone().sub(points[j]),angle=a.angleTo(b);turns.push(angle*180/Math.PI);curvatures.push(angle/Math.max(1e-8,(a.length()+b.length())*.5));}
  for(let j=0;j<per;j++){points[j].toArray(positions,(i*per+j)*6);points[j].toArray(positions,(i*per+j)*6+3);}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:d.color,depthTest:true}));group.add(line);records.push({index:i,region:d.region,color:d.color,root:d.root,tail:d.tail,authoredFreeArcLength:path.getLength(),solvedFreePolylineLength:lens.slice(surfaceSegments).reduce((a,b)=>a+b,0),lengthRatio:lens.slice(surfaceSegments).reduce((a,b)=>a+b,0)/path.getLength(),lengthConstraint:"not inextensible; authored shape solve, length change measured",analyticalJoinAngleDeg:0,renderedJoinAngleDeg:turns[surfaceSegments-1],maxTurnDeg:Math.max(...turns),maxCurvaturePerMetre:Math.max(...curvatures),maxSurfaceCurvaturePerMetre:Math.max(...curvatures.slice(0,surfaceSegments-1)),maxFreeCurvaturePerMetre:Math.max(...curvatures.slice(surfaceSegments)),maxFreeTurnDeg:Math.max(...turns.slice(surfaceSegments)),maxFreeTurnVertex:surfaceSegments+1+turns.slice(surfaceSegments).indexOf(Math.max(...turns.slice(surfaceSegments))),freeChordRatio:Math.max(...lens.slice(surfaceSegments))/Math.min(...lens.slice(surfaceSegments)),interpolation:'C1 Bezier chain with scalp terminal tangent; arc-length sampled; global minimum discrete bending with weak regional targets with fixed scalp-tangent release'});});
 group.matrixAutoUpdate=false;group.matrix.copy(v.mesh.matrix);v.scene.add(group);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const mesh=new THREE.Mesh(geometry);mesh.matrixAutoUpdate=false;mesh.matrix.copy(v.mesh.matrix);mesh.matrixWorld.copy(v.mesh.matrixWorld);const constructionMs=performance.now()-started;v.render();
 return{mesh,update(){},report:()=>({kind:'18-guide-structure-hypothesis',count,segments,surfaceSegments,finite:positions.every(Number.isFinite),missingSupports:0,orientedFacesVerified:usedFaces.size,skinRoutes:routes.report(),bodyTargetSampling:{contactTargets,maxTargetAdjustment,clearance:.007,method:"actual R30 final mesh directional surface intersections; authored fallback if ray misses"},rootLiftMax:.00002,geometryBytes:positions.byteLength,constructionMs,headFrame:{sourceOrigin:nf.o.toArray(),sourceAxes:[nf.x.toArray(),nf.y.toArray(),nf.z.toArray()],currentOrigin:cf.o.toArray(),currentAxes:[cf.x.toArray(),cf.y.toArray(),cf.z.toArray()],scale},records,referenceState:'One photographed asymmetric state; hidden gathering unknown; R30 semantic-root remap',physics:false}),dispose(){v.scene.remove(group);group.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});geometry.dispose();}};
}
