import * as THREE from '/native/kaopu-unified-human-workbench/full/source/registration-vendor/three.module.js';
import {FullerScalpBinding} from './RefinedHairLayer.js';
import {scalpMargin,smooth} from './RegionFields.js';
import {attachFiberMaterial,fiberMaterialDiagnostics} from './FiberMaterial.js';

// Own pulled-back long-hair rules. Surface prefix is exactly barycentric;
// the hanging tail is a static authored curve, not simulated collision hair.
class PulledBackBinding extends FullerScalpBinding {
 flow(p,i){const[x,y,z]=p,a=Math.abs(x),low=1-smooth(.30,.36,y),ear=smooth(.052,.071,a)*smooth(-.01,.055,z)*(1-smooth(.313,.335,y));return [x*.35+(x<0?-1:1)*.03*Math.exp(-Math.abs(x)/.004), -.04-.88*low+1.8*ear+1.8*smooth(.045,.09,z)*(1-smooth(.002,.014,scalpMargin(p))),-1];}
 setStyle(style){if(this.style===style)return;const per=this.segments+1;this.triangleIndices=new Int32Array(this.count*per);this.barycentrics=new Float32Array(this.count*per*3);this.guideEnds=new Uint8Array(this.count).fill(this.segments);let clipped=0;
  for(let i=0;i<this.count;i++){let t=this.rootTriangles[i],b=Array.from(this.rootBarycentrics.subarray(i*3,i*3+3)),stopped=false;for(let j=0;j<per;j++){const q=i*per+j;this.triangleIndices[q]=t;this.barycentrics.set(b,q*3);if(stopped||j===this.segments)continue;const direction=this.flow(this.point(t,b),i),step=.42/this.segments;let next=this.advance(t,b,step,direction);const here=this.point(t,b);if(scalpMargin(this.point(next.t,next.b))<.0002&&(here[2]>-.015||here[1]>.30)){const e=.0001,grad=[0,1,2].map(k=>{const a=[...here],c=[...here];a[k]+=e;c[k]-=e;return(scalpMargin(a)-scalpMargin(c))/(2*e);}),normal=this.faceNormal(t),dot=(a,b)=>a.reduce((s,x,k)=>s+x*b[k],0),gn=dot(grad,normal);for(let k=0;k<3;k++)grad[k]-=normal[k]*gn;const gg=dot(grad,grad),dg=dot(direction,grad);if(gg>1e-8)for(const steer of[.3,.7,1.4,2.8]){const corrected=direction.map((x,k)=>x-grad[k]*Math.min(0,dg)/gg+grad[k]*steer/Math.sqrt(gg)),probe=this.advance(t,b,step,corrected);if(scalpMargin(this.point(probe.t,probe.b))>=.0002){next=probe;break;}}}if(scalpMargin(this.point(next.t,next.b))<.0002){let lo=0,hi=step;next={t,b};for(let k=0;k<9;k++){const mid=(lo+hi)/2,probe=this.advance(t,b,mid,direction);if(scalpMargin(this.point(probe.t,probe.b))>=.0002){lo=mid;next=probe;}else hi=mid;}stopped=true;this.guideEnds[i]=j+1;clipped++;}t=next.t;b=next.b;}}
  this.style=style;this.guideBuilds++;this.clipped=clipped;
 }
}
const pt=(p,i)=>new THREE.Vector3().fromArray(p,i*3);
export function attachLongHair(a,{count=32000,surfaceSegments=20,tailSegments=20,radius=.000045,length=.43}={}){
 const m=a.motion().controller.model,v=a.motion().viewer,g=m.gnm,start=performance.now();
 const binding=new PulledBackBinding(g,{count,segments:64,seed:9127,length:.42});
 const inv=new Int32Array(g.numVertices).fill(-1);m.canonical.gnmRecipes.forEach(([x,y,t],hi)=>{if(x===y&&t===0){if(inv[x]>=0)throw Error('Ambiguous hair source');inv[x]=m.bodyCount+hi;}});
 const oriented=new Set();for(let i=0;i<m.faces.length;i+=3){const[x,y,z]=m.faces.slice(i,i+3);oriented.add(`${x},${y},${z}`);oriented.add(`${y},${z},${x}`);oriented.add(`${z},${x},${y}`);}
 const supportT=new Int32Array(count*(surfaceSegments+1)),supportB=new Float32Array(supportT.length*3),used=new Set(),faces=new Set();
 for(let i=0;i<count;i++)for(let j=0;j<=surfaceSegments;j++){const q=i*(surfaceSegments+1)+j,f=Math.pow(j/surfaceSegments,1.4)*binding.guideEnds[i],step=Math.min(64,Math.floor(f)),u=f-step,qa=i*65+step,qb=Math.min(i*65+64,qa+1),ta=binding.triangleIndices[qa],tb=binding.triangleIndices[qb],ba=binding.barycentrics.subarray(qa*3,qa*3+3),bb=binding.barycentrics.subarray(qb*3,qb*3+3);let t=ta,b;if(j===0){t=binding.rootTriangles[i];b=binding.rootBarycentrics.subarray(i*3,i*3+3);}else if(ta===tb)b=[0,1,2].map(k=>ba[k]*(1-u)+bb[k]*u);else{const pa=binding.point(ta,ba),pb=binding.point(tb,bb);t=u<.5?ta:tb;b=binding.barycentric(t,pa.map((x,k)=>x*(1-u)+pb[k]*u)).map(x=>Math.max(0,x));const sum=b.reduce((a,b)=>a+b,0);b=b.map(x=>x/sum);}supportT[q]=t;supportB.set(b,q*3);faces.add(t);}
 for(const t of faces){const ids=Array.from(g.triangles.subarray(t*3,t*3+3));for(const id of ids){if(inv[id]<0)throw Error('Missing long-hair source '+id);used.add(id);}if(!oriented.has(ids.map(id=>inv[id]).join(',')))throw Error('Missing oriented hair face '+t);}
 function nearest(target){let best=-1,d=Infinity;for(let i=0;i<g.numVertices;i++){if(inv[i]<0||g.componentId[i]!==0)continue;const dist=pt(g.template,i).distanceToSquared(target);if(dist<d){d=dist;best=i;}}used.add(best);return best;}
 const anchors=[nearest(new THREE.Vector3(-.07,.32,.015)),nearest(new THREE.Vector3(.07,.32,.015)),nearest(new THREE.Vector3(0,.395,0))];
 const src=g.template.slice(),nor=new Float32Array(src.length),segments=surfaceSegments+tailSegments,per=segments+1,n=count*per*2,positions=new Float32Array(n*3),tangents=new Float32Array(n*3),normals=new Float32Array(n*3),side=new Float32Array(n),along=new Float32Array(n),random=new Float32Array(n),radii=new Float32Array(n),indices=new Uint32Array(count*segments*6),centerline=new Float32Array(count*per*3);let ix=0,active=0;
 for(let i=0;i<count;i++){const rand=binding.random[i*4+2],margin=scalpMargin(binding.templateRoots.subarray(i*3,i*3+3));const draw=rand<smooth(.0002,.006,margin)*.96;for(let j=0;j<per;j++)for(let k=0;k<2;k++){const q=(i*per+j)*2+k,s=j/segments;side[q]=k?1:-1;along[q]=s;random[q]=rand;radii[q]=radius*(.75+.45*rand)*(1-.92*s**7);}if(draw){active++;for(let j=0;j<segments;j++){const x=(i*per+j)*2;for(const z of[x,x+1,x+2,x+1,x+3,x+2])indices[ix++]=z;}}}
 const geometry=new THREE.BufferGeometry();for(const[name,array,size]of[['position',positions,3],['tangent',tangents,3],['scalpNormal',normals,3],['strandSide',side,1],['along',along,1],['strandRandom',random,1],['strandRadius',radii,1]])geometry.setAttribute(name,new THREE.BufferAttribute(array,size));geometry.setIndex(new THREE.BufferAttribute(indices,1));geometry.setDrawRange(0,ix);
 const mesh=new THREE.Mesh(geometry);mesh.name='KAOPU pulled-back long hair candidate';const fiber=attachFiberMaterial(mesh,{renderer:v.renderer,color:'#080708',roughness:.43,specular:.075,coverageResolve:'blend'});v.scene.add(mesh);
 function frame(p){const l=pt(p,anchors[0]),r=pt(p,anchors[1]),top=pt(p,anchors[2]),o=l.clone().add(r).multiplyScalar(.5),x=r.clone().sub(l),sx=x.length();x.normalize();const y=top.clone().sub(o);y.addScaledVector(x,-y.dot(x));const sy=y.length();y.normalize();return{o,x,y,z:new THREE.Vector3().crossVectors(x,y).normalize(),sx,sy};}
 const neutralFrame=frame(g.template);let frameData=null,lastVersion=-1,updates=0,lastUpdateMs=0,rootLiftMax=0,maxSegment=0;
 function update(force=false){if(!force&&lastVersion===m.revision)return;const begun=performance.now(),p=v.geometry.attributes.position.array,nn=v.geometry.attributes.normal.array;for(const id of used){src.set(p.subarray(inv[id]*3,inv[id]*3+3),id*3);nor.set(nn.subarray(inv[id]*3,inv[id]*3+3),id*3);}const current=frame(src),scale=(current.sx/neutralFrame.sx+current.sy/neutralFrame.sy)/2;frameData={sourceOrigin:neutralFrame.o.toArray(),sourceAxes:[neutralFrame.x.toArray(),neutralFrame.y.toArray(),neutralFrame.z.toArray()],currentOrigin:current.o.toArray(),currentAxes:[current.x.toArray(),current.y.toArray(),current.z.toArray()],scale};
  const transformVector=d=>current.x.clone().multiplyScalar(d.dot(neutralFrame.x)*scale).addScaledVector(current.y,d.dot(neutralFrame.y)*scale).addScaledVector(current.z,d.dot(neutralFrame.z)*scale);
  rootLiftMax=0;maxSegment=0;
  for(let i=0;i<count;i++){const rand=binding.random[i*4+2];let endNormal=new THREE.Vector3(),neutralEnd;
   for(let j=0;j<=surfaceSegments;j++){const q=i*(surfaceSegments+1)+j,t=supportT[q],b=supportB.subarray(q*3,q*3+3),sp=new THREE.Vector3(),sn=new THREE.Vector3();for(let k=0;k<3;k++){const id=g.triangles[t*3+k];sp.addScaledVector(pt(src,id),b[k]);sn.addScaledVector(pt(nor,id),b[k]);}sn.normalize();const s=Math.pow(j/surfaceSegments,1.4),lift=.00002+(.0025*(1-Math.exp(-s*30))+.003*Math.sin(Math.PI*s))*(.7+.6*rand);sp.addScaledVector(sn,lift);sp.toArray(centerline,(i*per+j)*3);sn.toArray(normals,(i*per+j)*6);sn.toArray(normals,(i*per+j)*6+3);if(j===0)rootLiftMax=Math.max(rootLiftMax,lift);if(j===surfaceSegments){endNormal.copy(sn);neutralEnd=new THREE.Vector3(...binding.point(t,b));}}
   const p0=pt(centerline,i*per+surfaceSegments),root=pt(binding.templateRoots,i),sign=root.x<0?-1:1,lateral=smooth(.028,.072,Math.abs(root.x)),tailLength=length*(.82+.28*rand),endX=sign*(.035+.105*lateral),endZ=-.105+.175*lateral;
   const earExit=smooth(.055,.075,Math.abs(neutralEnd.x))*smooth(-.02,.015,neutralEnd.z)*smooth(.235,.27,neutralEnd.y);
   const c1=new THREE.Vector3(neutralEnd.x+sign*.08*earExit,neutralEnd.y-.065+.12*earExit,Math.min(neutralEnd.z-.055,-.125));
   const c2=new THREE.Vector3(sign*(.045+.17*lateral),neutralEnd.y-tailLength*.60,-.175+.025*lateral);
   const end=new THREE.Vector3(endX,neutralEnd.y-tailLength,endZ);
   const c1w=p0.clone().add(transformVector(c1.sub(neutralEnd))),c2w=p0.clone().add(transformVector(c2.sub(neutralEnd))),endw=p0.clone().add(transformVector(end.sub(neutralEnd)));
   for(let j=1;j<=tailSegments;j++){const u=j/tailSegments,w=1-u,q=i*per+surfaceSegments+j,pp=p0.clone().multiplyScalar(w*w*w).addScaledVector(c1w,3*w*w*u).addScaledVector(c2w,3*w*u*u).addScaledVector(endw,u*u*u);pp.toArray(centerline,q*3);endNormal.toArray(normals,q*6);endNormal.toArray(normals,q*6+3);}
  }
  for(let i=0;i<count;i++)for(let j=0;j<per;j++){const q=i*per+j,pa=pt(centerline,i*per+Math.max(0,j-1)),pb=pt(centerline,i*per+Math.min(segments,j+1)),t=pb.sub(pa);for(let k=0;k<2;k++){positions.set(centerline.subarray(q*3,q*3+3),q*6+k*3);t.toArray(tangents,q*6+k*3);}if(j>0)maxSegment=Math.max(maxSegment,pt(centerline,q).distanceTo(pt(centerline,q-1)));}
  for(const key of['position','tangent','scalpNormal'])geometry.attributes[key].needsUpdate=true;mesh.matrixAutoUpdate=false;mesh.matrix.copy(v.mesh.matrix);lastVersion=m.revision;updates++;lastUpdateMs=performance.now()-begun;
 }
 const oldRender=v.render;v.render=function(...args){update();return oldRender.apply(this,args);};update(true);v.render();const constructionMs=performance.now()-start;
 return{mesh,binding,update,report(){return{kind:'kaopu-pulled-back-long-static/1',count,active,segments,surfaceSegments,tailSegments,usedFaces:faces.size,usedVertices:used.size,missingSupports:0,rootLiftMax,finite:centerline.every(Number.isFinite),maxSegment,geometryBytes:Object.values(geometry.attributes).reduce((n,a)=>n+a.array.byteLength,0)+indices.byteLength,constructionMs,lastUpdateMs,updates,headFrame:frameData,rootFrame:'final displayed common surface',physics:false,bodyCollision:false,faceArchiveModified:false,fiber:fiberMaterialDiagnostics(fiber.material)};},dispose(){v.render=oldRender;v.scene.remove(mesh);fiber.dispose();geometry.dispose();}};
}
