import * as THREE from '/native/kaopu-unified-human-workbench/full/source/registration-vendor/three.module.js';
/** Actual displayed common mesh, rendered hair centreline segments. This is
 * an offline/static collision diagnostic, not a physics solver or radius test. */
export function probeStaticContacts(viewer,hair,{stride=1}={}){
 viewer.scene.updateMatrixWorld(true);
 const started=performance.now(),p=viewer.geometry.attributes.position.array,faces=viewer.geometry.index.array,h=hair.mesh.geometry.attributes.position.array,{count,surfaceSegments,segments}=hair.report(),per=segments+1,cell=.025,grid=new Map(),triangles=[];
 for(let t=0;t<faces.length/3;t++){const ids=Array.from(faces.subarray(t*3,t*3+3)),ps=ids.map(i=>new THREE.Vector3().fromArray(p,i*3).applyMatrix4(viewer.mesh.matrixWorld));triangles[t]=ps;const lo=[0,1,2].map(k=>Math.floor(Math.min(...ps.map(v=>v.getComponent(k)))/cell)),hi=[0,1,2].map(k=>Math.floor(Math.max(...ps.map(v=>v.getComponent(k)))/cell));for(let x=lo[0];x<=hi[0];x++)for(let y=lo[1];y<=hi[1];y++)for(let z=lo[2];z<=hi[2];z++){const key=[x,y,z].join(',');if(!grid.has(key))grid.set(key,[]);grid.get(key).push(t);}}
 const frame=hair.report().headFrame,byRegion={scalpPrefix:0,ear:0,neck:0,shoulderChest:0,back:0};const regionOf=(point,segment)=>{if(segment<=surfaceSegments)return 'scalpPrefix';const rel=point.toArray().map((x,k)=>x-frame.currentOrigin[k]),coords=frame.currentAxes.map(axis=>axis.reduce((s,x,k)=>s+x*rel[k],0)/frame.scale),local=frame.sourceOrigin.map((x,k)=>x+frame.sourceAxes.reduce((s,axis,j)=>s+axis[k]*coords[j],0)),[x,y,z]=local;if(Math.abs(x)>.058&&y>.24&&y<.33&&z>-.04&&z<.07)return 'ear';if(y>.135)return 'neck';return z<-.02?'back':'shoulderChest';};
 const ray=new THREE.Ray(),hit=new THREE.Vector3(),examples=[];let testedSegments=0,triangleTests=0,surfaceCrossings=0,tailCrossings=0;const crossedStrands=new Set();
 for(let i=0;i<count;i+=stride)for(let j=1;j<=segments;j++){const a=new THREE.Vector3().fromArray(h,(i*per+j-1)*6).applyMatrix4(hair.mesh.matrixWorld),b=new THREE.Vector3().fromArray(h,(i*per+j)*6).applyMatrix4(hair.mesh.matrixWorld),d=b.clone().sub(a),length=d.length();if(length<1e-8)continue;ray.set(a,d.divideScalar(length));testedSegments++;const lo=[0,1,2].map(k=>Math.floor(Math.min(a.getComponent(k),b.getComponent(k))/cell)),hi=[0,1,2].map(k=>Math.floor(Math.max(a.getComponent(k),b.getComponent(k))/cell)),seen=new Set();let crossed=false;
  for(let x=lo[0];x<=hi[0]&&!crossed;x++)for(let y=lo[1];y<=hi[1]&&!crossed;y++)for(let z=lo[2];z<=hi[2]&&!crossed;z++)for(const t of grid.get([x,y,z].join(','))||[]){if(seen.has(t))continue;seen.add(t);triangleTests++;if(ray.intersectTriangle(...triangles[t],false,hit)){const distance=hit.distanceTo(a);if(distance>1e-5&&distance<length-1e-5){crossed=true;crossedStrands.add(i);const region=regionOf(hit,j);byRegion[region]++;if(j<=surfaceSegments)surfaceCrossings++;else tailCrossings++;if(examples.length<40)examples.push({strand:i,segment:j,triangle:t,region,point:hit.toArray()});break;}}}
 }
 return{kind:'static-rendered-centreline/common-surface',stride,testedSegments,triangleTests,surfaceCrossings,tailCrossings,byRegion,regionInterpretation:'diagnostic head-local bounds, not anatomical labels',crossedStrands:crossedStrands.size,examples,elapsedMs:performance.now()-started,includesBody:true,includesStrandRadius:false,continuousCurve:false,physics:false};
}
