import * as THREE from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {GNMHeadModel,parseContainer} from './GNMModel.js';
import {HairLayer} from './HairLayer.js';
import * as Fiber from './FiberMaterial.js';
import {createHairOpacityShadows} from './HairOpacityShadows.js';
const status=document.querySelector('#status'), errors=[];let ready=false,mode='',raf=0,phase=0,last=0;
const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.setClearColor(0x252d37);renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.001,10),target=new THREE.Vector3(0,.28,.018),orbit=new OrbitControls(camera,renderer.domElement);orbit.target.copy(target);orbit.minDistance=.2;orbit.maxDistance=1.1;camera.position.set(.28,.32,.55);orbit.update();
const lights=['#ffb473','#7caaff'].map((c,i)=>{const l=new THREE.DirectionalLight(c,i?3:3.2);l.position.copy(new THREE.Vector3(...(i?[-1,.35,.55]:[1,.45,.75])).normalize().multiplyScalar(1.3).add(target));l.target.position.copy(target);l.castShadow=true;l.shadow.mapSize.set(1536,1536);Object.assign(l.shadow.camera,{left:-.29,right:.29,top:.30,bottom:-.30,near:.05,far:2.5});l.shadow.camera.updateProjectionMatrix();l.shadow.bias=-.00008;l.shadow.normalBias=.00012;l.shadow.radius=1.5;scene.add(l,l.target);return l;});scene.add(new THREE.HemisphereLight(0xffffff,0x393130,.35));
let model,head,hair,fiber,opacity,baseHead,baseHair,capability,assetHash,poseAngle=0;
function draw(){if(!ready)return;opacity.update();renderer.render(scene,camera);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();draw();}addEventListener('resize',resize);resize();orbit.addEventListener('change',draw);orbit.addEventListener('start',()=>stop());
function snapshots(){baseHair={};for(const k of ['position','tangent','scalpNormal'])baseHair[k]=hair.geometry.attributes[k].array.slice();}
function pose(angle){poseAngle=angle;const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),angle),v=new THREE.Vector3(),pivot=new THREE.Vector3(0,.22,0);for(let i=0;i<baseHead.length;i+=3){v.fromArray(baseHead,i).sub(pivot).applyQuaternion(q).add(pivot).toArray(head.geometry.attributes.position.array,i);}head.geometry.attributes.position.needsUpdate=true;head.geometry.computeVertexNormals();for(const k of ['position','tangent','scalpNormal']){const a=hair.geometry.attributes[k].array,b=baseHair[k];for(let i=0;i<a.length;i+=3){v.fromArray(b,i);if(k==='position')v.sub(pivot);v.applyQuaternion(q);if(k==='position')v.add(pivot);v.toArray(a,i);}hair.geometry.attributes[k].needsUpdate=true;}opacity.markDirty('head-local rigid pose');renderer.shadowMap.needsUpdate=true;draw();}
function stop(){mode='';if(raf)cancelAnimationFrame(raf);raf=0;document.querySelectorAll('#orbit,#pose').forEach(b=>b.classList.remove('active'));}
function tick(t){if(!mode)return;phase+=Math.min(.05,last?(t-last)/1000:0);last=t;if(mode==='pose')pose(Math.sin(phase*.9)*.22);else{const p=new THREE.Vector3(.28,.04,.55).applyAxisAngle(new THREE.Vector3(0,1,0),phase*.3);camera.position.copy(target).add(p);camera.lookAt(target);draw();}raf=requestAnimationFrame(tick);}
function animate(m){if(mode===m){stop();return;}stop();mode=m;last=0;document.querySelector('#'+m).classList.add('active');raf=requestAnimationFrame(tick);}
function style(s){stop();pose(0);hair.mesh.material=hair.material;hair.setAppearance({style:s});hair.mesh.material=fiber.material;snapshots();opacity.markDirty('style');renderer.shadowMap.needsUpdate=true;document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===s));draw();}
function bytes(){return Object.values(hair.geometry.attributes).reduce((n,a)=>n+a.array.byteLength,0)+hair.geometry.index.array.byteLength;}
function diagnostics(){return{ready,errors,version:'isolated-draft-r01',sourceCommit:'0b4703359efbae10ffc6c0e5fe3fc081e7eca4fe',assetHash,teacherIncluded:false,physics:false,productionAcceptance:false,poseAngle,geometryBytes:hair?bytes():0,groom:hair?.diagnostics(),optics:capability,opacity:opacity?.diagnostics(),renderer:{memory:{...renderer.info.memory},render:{...renderer.info.render}},context:renderer.getContext().getParameter(renderer.getContext().RENDERER)};}
window.hairDraft={diagnostics,style,pose,stop,draw,renderer,scene,camera};
try{let r=await fetch('./gnm_head_web.bin');if(!r.ok)r=await fetch('https://raw.githubusercontent.com/xrblocks/assets-gnm/134feb02b11fa642a43ff5e7e880246255a74e86/gnm_head_web.bin');if(!r.ok)throw Error('GNM asset HTTP '+r.status);const buffer=await r.arrayBuffer();assetHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join('');if(assetHash!=='fd19f46eef6f8bfb725fceab581e1bc8837209997ca3fd43f3c1735003c86961')throw Error('GNM SHA256 mismatch');const data=parseContainer(buffer);model=new GNMHeadModel(data.meta,data.sections);baseHead=new Float32Array(model.numVertices*3);model.computeVertices(baseHead);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(baseHead.slice(),3));g.setIndex(new THREE.BufferAttribute(model.triangles,1));g.computeVertexNormals();head=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:'#b9b2aa',roughness:.58,metalness:.02}));head.castShadow=head.receiveShadow=true;scene.add(head);status.textContent='建立真实三角形发根…';await new Promise(r=>setTimeout(r,10));hair=new HairLayer(model,baseHead,g.attributes.normal.array,{count:18000,segments:18,seed:724,volume:.008,density:.95});const along=hair.geometry.attributes.along.array,rand=hair.geometry.attributes.strandRandom.array,radii=new Float32Array(along.length);for(let i=0;i<radii.length;i++)radii[i]=.00028*(.72+.55*rand[i])*(1-.87*along[i]**4);hair.geometry.setAttribute('strandRadius',new THREE.BufferAttribute(radii,1));fiber=Fiber.attachFiberMaterial(hair.mesh,{renderer,color:'#291c12',roughness:.46,specular:.095});scene.add(hair.mesh);snapshots();opacity=createHairOpacityShadows({renderer,scene,lights});capability=opacity.init();opacity.attachFiber(hair.mesh);opacity.attachHead(head);opacity.setEnabled(capability.supported);ready=true;renderer.shadowMap.needsUpdate=true;resize();status.textContent=capability.supported?'拖动环视 · 滚轮近看 · 分层投影':'分层投影不可用，当前为随机投影对照';document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>style(b.dataset.style));document.querySelector('#orbit').onclick=()=>animate('orbit');document.querySelector('#pose').onclick=()=>animate('pose');document.querySelector('#reset').onclick=()=>{stop();phase=0;style('side-sweep');camera.position.set(.28,.32,.55);orbit.target.copy(target);orbit.update();draw();};}catch(e){errors.push(String(e));status.textContent='载入失败：'+e.message;console.error(e);}
