from pathlib import Path
import json, hashlib
R=Path(__file__).resolve().parents[1]
core=(R/'src/natural-swim.js').read_text()
profile=(R/'profiles/yellowfin-steady.json').read_text()
html='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ocean Life Mother N01 · 自然运动验证</title><style>
*{box-sizing:border-box}body{margin:0;background:#101e27;color:#e6f0ef;font:15px system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:24px}header{border-bottom:1px solid #425765;padding-bottom:18px}.eyebrow{font-size:12px;letter-spacing:2px;color:#9bc7c7}h1{font-size:28px;margin:12px 0}p{line-height:1.7;color:#bdd0d4}.controls{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}button{font:inherit;border:1px solid #4d6c79;border-radius:6px;background:#203c4a;color:#ecf6f5;padding:10px 14px;cursor:pointer}button.active{background:#37665f;border-color:#8abca8}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.metric{padding:18px;background:#182e27;border:1px solid #324954;border-radius:8px}.metric span{display:block;color:#adbec7;font-size:13px}.metric strong{font-size:29px;font-variant-numeric:tabular-nums;display:block;margin:8px 0}.panel{margin-top:20px;padding:18px;background:#162a34;border-radius:8px}canvas{display:block;width:100%;height:240px}h2{font-size:18px;margin:0 0 12px}.note{font-size:13px}#warning{color:#f8d18f;min-height:30px}#detail{font-variant-numeric:tabular-nums}.small{font-size:12px;color:#a3bec9}footer{margin-top:20px;border-top:1px solid #354852;padding-top:12px;font-size:12px;line-height:1.7;color:#9fb8c3}@media(max-width:620px){main{padding:14px}h1{font-size:22px}.metrics{gap:6px}.metric{padding:10px 6px}.metric strong{font-size:21px}.metric span{font-size:11px}button{padding:8px;font-size:13px}canvas{height:200px}}
</style></head><body><main><header><div class="eyebrow">OCEAN LIFE MOTHER / N01</div><h1>自然数据驱动的游速与摆尾时钟</h1><p>同一物种、同一叉长。水流改变世界位移；摆尾节奏读取相对水体的游速。<br>这是独立运动内核验证，不是已经完成的鱼体、材质或生态场景。</p></header><div class="controls"><button id="cruise">静水 · 1 叉长/秒</button><button id="fast">变速到 2 叉长/秒</button><button id="hold">逆流定点</button><button id="adult">检查成体外推</button><button id="pause">暂停</button></div><div class="metrics"><div class="metric"><span>相对水体游速</span><strong id="speed">—</strong><span>米/秒</span></div><div class="metric"><span>摆尾频率估计</span><strong id="frequency">—</strong><span>次/秒</span></div><div class="metric"><span>世界坐标移动速度</span><strong id="world">—</strong><span>米/秒</span></div></div><p id="warning" role="status"></p><section class="panel"><h2>连续相位记录</h2><canvas id="signal"></canvas><p id="detail" class="note"></p><p class="small">曲线是时钟的正弦显示，不是测得的尾鳍位移。加速度是明确标注的工程试验值；没有复用原模型的动作轨迹。</p></section><section class="panel"><h2>这条观测能支持什么</h2><p class="note">依据：Shadwick 与 Syme，2008 年，对活体黄鳍金枪鱼的实验研究。叉长 0.39–0.54 米；本试验采用 0.45 米、25°C。稳定游动回归：f = 1.22 × U/L + 0.85。</p><p class="note">不能据此宣布：帕劳野外游速已经标定、逃逸极限已经测得，或者幼鱼与成鱼仅需缩放。超出物种、叉长、温度和游速范围时拒绝套用此回归。</p></section><footer>没有载入第三方 GLB、贴图、骨架、关键帧或 R03 拟合系数。测量记录与独立代码保留；旧研究文件没有在这里使用，也没有从仓库历史中删除。<br>此页为内部验证样件，尚未通过总工作台公网交付验收。</footer></main><script>'''
html+='const PROFILE='+profile+';\n'+core+'''\n
(()=>{'use strict';const $=id=>document.getElementById(id),P=PROFILE;
const cfg={id:'nature-observation-1',species:P.species,lengthM:.45,lengthMeasure:'fork-length',initialSpeedFLps:1,waterTemperatureC:25,forward:[1,0,0],positionM:[0,0,0],timeS:0,phaseCycles:0};
const clock=NaturalSwim.create(P,cfg);let state=clock.initialState(),target=1,current=0,paused=false,last=null,history=[],scenario='cruise',warning='';
function update(dt){if(dt<=0)return;const r=clock.advance(state,state.timeS+dt,{targetSpeedFLps:target,accelerationFLps2:.5},{timeS:state.timeS,frame:'metre-y-up',flowStatus:'known',constantOverInterval:true,currentMps:[current,0,0],waterTemperatureC:25});if(!r.accepted)throw Error(r.reasons.join(','));state=r.state;history.push([state.timeS,Math.sin(state.phaseCycles*2*Math.PI)]);while(history.length&&history[0][0]<state.timeS-4)history.shift();}
function reset(mode){scenario=mode;state=clock.initialState();history=[];target=1;current=mode==='hold'?-.45:0;warning=mode==='hold'?'逆流定点：世界位置不变，鱼仍以 0.45 米/秒相对水体游动。':'';paused=false;$('pause').textContent='暂停';last=null;render();}
function draw(){const cv=$('signal'),r=cv.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);cv.width=Math.round(r.width*d);cv.height=Math.round(r.height*d);const c=cv.getContext('2d'),w=r.width,h=r.height;c.scale(d,d);c.strokeStyle='#3a505c';c.lineWidth=1;for(let i=0;i<5;i++){const x=24+(w-48)*i/4;c.beginPath();c.moveTo(x,15);c.lineTo(x,h-15);c.stroke();}c.beginPath();c.moveTo(20,h/2);c.lineTo(w-20,h/2);c.stroke();c.strokeStyle='#8fc9b2';c.lineWidth=2;c.beginPath();history.forEach((a,i)=>{const x=w-24-(state.timeS-a[0])/4*(w-48),y=h/2-a[1]*(h*.34);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.fillStyle='#edc682';const phase=Math.sin(state.phaseCycles*2*Math.PI);c.beginPath();c.arc(w-24,h/2-phase*h*.34,5,0,Math.PI*2);c.fill();}
function render(){const q=clock.query(state);$('speed').textContent=q.speedThroughWaterMps.toFixed(3);$('frequency').textContent=q.frequencyHz.toFixed(3);$('world').textContent=(q.speedThroughWaterMps+current).toFixed(3);$('warning').textContent=warning;$('detail').textContent=`时间 ${state.timeS.toFixed(2)} 秒 · 累积 ${state.phaseCycles.toFixed(3)} 周期 · 位移 ${state.positionM[0].toFixed(3)} 米 · ${state.lastRegime==='steady-model'?'稳定游动回归':'工程变速试验，非实测逃逸'}`;draw();}
$('cruise').onclick=()=>reset('cruise');$('fast').onclick=()=>{scenario='acceleration';current=0;target=2;warning='变速时积分频率，相位不从零重新播放。';render()};$('hold').onclick=()=>reset('hold');$('adult').onclick=()=>{const r=NaturalSwim.estimate(P,{species:P.species,lengthM:1,lengthMeasure:'fork-length',speedFLps:1,waterTemperatureC:25,speedFrame:'relative-to-water',regime:'steady'});warning=r.supported?'错误：不应外推':'已拒绝把此样本回归套到 1 米成鱼。需要对应阶段的自然证据。';render()};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'继续':'暂停';last=null;render()};
window.NatureLab={reset,advanceSeconds:(t)=>{if(!Number.isFinite(t)||t<0||t>60)throw Error('Invalid diagnostic interval');paused=true;const end=state.timeS+t;while(state.timeS<end-1e-12)update(Math.min(1/120,end-state.timeS));render();return clock.query(state)},getState:()=>({...clock.query(state),worldSpeedMps:state.speedFLps*state.lengthM+current,paused,scenario}),freeze:()=>{paused=true;last=null},getHistory:()=>history.map(a=>a.slice())};
function frame(now){if(last!==null&&!paused){const dt=(now-last)/1000;if(dt>60){paused=true;warning='长时间中断需要明确接续，未静默压缩时间。'}else update(dt)}last=now;render();requestAnimationFrame(frame)}render();requestAnimationFrame(frame);
})();</script></body></html>'''
(R/'qa/NATURE_MOTION_INTERNAL.html').write_text(html)
(R/'qa/BUILD.json').write_text(json.dumps({'htmlBytes':len(html.encode()),'htmlSha256':hashlib.sha256(html.encode()).hexdigest(),'rawModelDependencies':[],'rawTextureDependencies':[],'sourceAnimationDependencies':[],'fittedAssetCoefficientDependencies':[],'runtimeEntry':'qa/NATURE_MOTION_INTERNAL.html','publicNavigationTested':False},indent=2))
print(len(html.encode()), hashlib.sha256(html.encode()).hexdigest())
