/* Same-origin case lifecycle. Inactive iframe documents are unloaded, not left holding GPU contexts. */
(()=>{'use strict';
const config={young:['youngFrame','young-coral-r01/?embedded=1&v=IOS-R03-20261005'],branch:['branchFrame','branch-growth-r01/?embedded=1&v=IOS-R03-20261005'],'branch-repro':['branchReproFrame','branch-reproduction-r01/?embedded=1&v=IOS-R03-20261005'],spiky:['spikyFrame','spiky-teacher-r01/?embedded=1&v=IOS-R03-20261005']};
const entries={},state=window.CoralFrameHostState={version:'coral-frame-lifetime-r03',externalTreeManaged:false,current:'home',loaded:[],restores:0,unloads:0,recoveries:0,errors:{}};let current='home';
const copy=x=>x==null?x:JSON.parse(JSON.stringify(x));
function api(id,w){return id==='spiky'?w.SpikyStudy:id==='young'?w.YoungStudy:id==='branch'?w.BranchReplay:id==='branch-repro'?w.BranchStudy:null}
function inputs(d){return [...d.querySelectorAll('input[id],select[id]')].filter(x=>x.type!=='file').map(x=>({id:x.id,value:x.value,checked:x.checked,type:x.type}))}
function save(e){try{const w=e.frame.contentWindow,d=w.document,a=api(e.id,w);if(e.pendingRestore&&e.saved)return;if(!a&&e.id!=='tree')return;const value={state:copy(a?.state),inputs:inputs(d),scroll:[w.scrollX,w.scrollY],hash:w.location.hash,referenceHidden:d.querySelector('#teacherPanel,#reference')?.hidden};const file=d.querySelector('#textureFile')?.files?.[0];if(value.state?.texture==='local-unverified'&&file)e.file=file;else if(value.state?.texture!=='local-unverified')e.file=null;e.saved=value;sessionStorage.setItem('coral-frame-observation-v3:'+e.id,JSON.stringify(value))}catch(_){}}
function announce(e,message){e.notice.textContent=message;e.notice.hidden=!message}
function refresh(){state.loaded=Object.values(entries).filter(e=>e.frame.hasAttribute('src')).map(e=>e.id);state.current=current}
function park(e){if(e.timer){clearTimeout(e.timer);e.timer=0}if(e.frame.hasAttribute('src')){save(e);try{api(e.id,e.frame.contentWindow)?.setActive(false)}catch(_){}e.generation++;e.frame.removeAttribute('src');e.frame.src='about:blank';e.frame.removeAttribute('src');state.unloads++;e.pendingRestore=!!e.saved;e.restored=false}announce(e,'');refresh()}
function zoomControls(e,w,a){if(!a)return;const d=w.document;if(e.id==='young'||e.id==='spiky')return;const label=d.getElementById(e.id==='branch'?'zoomLabel':'zoom');if(!label||d.getElementById('caseZoomIn'))return;const minus=d.createElement('button'),plus=d.createElement('button');minus.id='caseZoomOut';plus.id='caseZoomIn';minus.textContent='−';plus.textContent='＋';minus.setAttribute('aria-label','缩小100个百分点');plus.setAttribute('aria-label','放大100个百分点');label.before(minus);label.after(plus);const bounds=e.id==='branch'?[.4,100]:[.35,20];function change(step){const old=e.id==='branch'?a.state.camera.zoom:a.state.zoom,next=Math.max(bounds[0],Math.min(bounds[1],old+step));if(e.id==='branch')a.setCamera({zoom:next});else{a.state.zoom=next;a.draw()}label.textContent=Math.round(next*100)+'%';minus.disabled=next<=bounds[0];plus.disabled=next>=bounds[1]}minus.onclick=()=>change(-1);plus.onclick=()=>change(1)}
function restoreInputs(d,records,ids=[]){for(const x of records||[]){if(!ids.includes(x.id))continue;const n=d.getElementById(x.id);if(!n)continue;if(x.type==='checkbox')n.checked=!!x.checked;else n.value=x.value;n.dispatchEvent(new Event('change',{bubbles:true}))}}
function expectedDocument(e){try{const u=new URL(e.frame.contentWindow.location.href);return u.origin===location.origin&&u.searchParams.get('coralLease')===String(e.generation)}catch(_){return false}}
function restore(e){if(e.restored||current!==e.id||document.hidden||!e.frame.hasAttribute('src')||!expectedDocument(e))return;try{const w=e.frame.contentWindow,d=w.document,a=api(e.id,w);if(e.id==='tree'){if(d.readyState!=='complete')return;if(e.saved){for(const x of e.saved.inputs||[]){const n=d.getElementById(x.id);if(!n||n.type==='file')continue;if(x.type==='checkbox')n.checked=!!x.checked;else n.value=x.value;n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}))}w.scrollTo(...(e.saved.scroll||[0,0]))}e.restored=true;e.pendingRestore=false;announce(e,'');refresh();return}if(!a||!a.state.ready)return;e.restored=true;e.pendingRestore=false;const v=e.saved,s=v?.state;if(s){if(e.id==='spiky'){a.seek(s.time);if(s.inspection)a.setInspection(s.inspection);if(s.color)a.setColor(s.color);if(s.ratio)a.setRatio(s.ratio);a.showReference(s.reference!==false);restoreInputs(d,v.inputs,['quality','wrapMode','filterMode','flipY']);if(e.file&&a.restoreTexture)a.restoreTexture(e.file)}else if(e.id==='young'){const phase=d.getElementById('phase');if(phase&&Number.isFinite(s.phase)){phase.value=s.phase;phase.dispatchEvent(new Event('change',{bubbles:true}))}a.seek(s.time);if(s.inspection)a.setInspection(s.inspection);if(s.colorSettings)a.setColor(s.colorSettings);if(s.ratio)a.setRatio(s.ratio);a.showReference(s.reference!==false);restoreInputs(d,v.inputs,['quality'])}else if(e.id==='branch'){if(s.params){a.setParams(s.params);a.setGrowth(s.params.growth)}a.setMode(s.mode);if(s.camera)a.setCamera(s.camera)}else{a.changeOutput(s.output);Object.assign(a.state,{yaw:s.yaw,pitch:s.pitch,zoom:s.zoom,pan:s.pan?.slice()||[0,0],skeleton:!!s.skeleton,material:s.material||0});a.seek(s.growth);restoreInputs(d,v.inputs,['quality'])}if(typeof v.referenceHidden==='boolean'){const panel=d.querySelector('#teacherPanel,#reference');if(panel&&panel.hidden!==v.referenceHidden){const button=d.getElementById(e.id==='branch'?'reference':e.id==='branch-repro'?'teacher':'refToggle');if(button)button.click()}}state.restores++;w.scrollTo(...(v.scroll||[0,0]))}zoomControls(e,w,a);a.setActive(true);announce(e,'');refresh()}catch(error){state.errors[e.id]='恢复观察状态失败：'+error.message;announce(e,state.errors[e.id])}}
function activate(e){if(document.hidden||current!==e.id)return;if(e.frame.hasAttribute('src')){restore(e);return}e.generation++;e.restored=false;e.pendingRestore=!!e.saved;announce(e,'正在重建本例图形资源，保留上次观察状态…');const target=new URL(e.url,location.href);target.searchParams.set('coralLease',String(e.generation));if(e.id==='tree'&&e.saved?.hash)target.hash=e.saved.hash;e.frame.src=target.href;refresh()}
function recover(e,error){if(current!==e.id||document.hidden||e.timer||!expectedDocument(e))return;if(e.budget<=0){announce(e,'图形资源仍不可用。观察状态已保留；可切回本例重试，或在工作台入口重新打开。');return;}const w=e.frame.contentWindow,a=api(e.id,w),currentState=a?.state||w.BranchReplayState||w.BranchStudyState||w.YoungStudyState||w.SpikyStudyState;if(!currentState?.error)return;state.errors[e.id]=String(error||currentState.error);e.budget--;park(e);state.recoveries++;announce(e,'图形资源中断，正在保留姿态重新载入…');e.timer=setTimeout(()=>{e.timer=0;if(current===e.id&&!document.hidden)activate(e)},250)}
for(const[id,[frameId,url]]of Object.entries(config)){const frame=document.getElementById(frameId),notice=document.createElement('div');notice.className='frame-runtime-notice';notice.hidden=true;notice.setAttribute('role','status');frame.before(notice);let saved=null;try{saved=JSON.parse(sessionStorage.getItem('coral-frame-observation-v3:'+id)||'null')}catch(_){}const e=entries[id]={id,frame,url,notice,saved,restored:false,pendingRestore:!!saved,budget:1,timer:0,generation:0,file:null};frame.addEventListener('load',()=>{if(current===id&&frame.hasAttribute('src'))restore(e)})}
function select(id){current=id;for(const e of Object.values(entries))if(e.id!==id)park(e);if(entries[id]){entries[id].budget=1;activate(entries[id])}refresh()}
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const item=Object.values(entries).find(x=>x.frame.contentWindow===e.source);if(!item||item.id!==current||!item.frame.hasAttribute('src'))return;if(e.data?.error)recover(item,e.data.error);else restore(item)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){for(const e of Object.values(entries))park(e)}else if(entries[current]){entries[current].budget=1;activate(entries[current])}});window.addEventListener('pagehide',()=>{for(const e of Object.values(entries))park(e)});window.addEventListener('pageshow',()=>{if(entries[current])activate(entries[current])});
window.CoralFrameHost={select,state,retry(id=current){if(!entries[id])return;park(entries[id]);entries[id].budget=1;activate(entries[id])}};
})();
