/* Generic private-original viewer. No original shader, recording, or packed payload is published here. */
(()=>{'use strict';
const VERSION='original-replay-r03-20261005',config={
 color:{sha256:'69951768c5a49b0404d0308e24628f99f03a7ad1fae2dc63d99fcaded524082a',bytes:9295,time:53.79,title:'彩色珊瑚',aa:2},
 rosette:{sha256:'49301f182d0e0b06baa3a79aa3f4a7a2cdb30c3ccbe4da2a227522f64f906407',bytes:5352,time:45,title:'花盘卷层珊瑚',aa:2},
 transparent:{sha256:'4962c9f650fd9a8415f51b8300433d06478d6b896fa578e1a6d76514d825383c',bytes:8386,time:46.355,title:'07 透明浮游体',aa:1}
};
const initialHash=new URLSearchParams(location.hash.slice(1));let packed=initialHash.get('originals');const key=id=>'coral-private-original-v2:'+id+':'+config[id].sha256,instances={};let current=initialHash.get('view')||'home',sources={};
const vertex='#version 300 es\nprecision highp float;const vec2 P[3]=vec2[3](vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));void main(){gl_Position=vec4(P[gl_VertexID],0.,1.);}';
const header='#version 300 es\nprecision highp float;precision highp int;uniform vec3 iResolution;uniform vec4 iMouse;uniform float iTime;uniform int iFrame;out vec4 outColor;\n#define HW_PERFORMANCE 1\n';
const inspectHeader='uniform float uZoom;uniform int uInspect;uniform vec2 uOrbit;vec3 inspectCamera(vec3 v){float r=length(v);float a=atan(v.x,v.z)+uOrbit.x;float e=clamp(asin(clamp(v.y/r,-1.,1.))+uOrbit.y,-1.3962634,1.3962634);return r*vec3(cos(e)*sin(a),sin(e),cos(e)*cos(a));}\n';
const baselineTail='\nvoid main(){mainImage(outColor,gl_FragCoord.xy);}';
const inspectTail='\nvoid main(){vec2 p=gl_FragCoord.xy;if(uZoom!=1.0)p=(p-iResolution.xy*.5)/uZoom+iResolution.xy*.5;mainImage(outColor,p);}';
function observeSource(source){const mark=/(^[ \t]*mat3\s+ca\s*=)/gm;const count=[...source.matchAll(mark)].length;if(count!==1)throw Error('相机观察接点不唯一；保留原版，不替换算法');return source.replace(mark,'    if(uInspect!=0) ro=ta+inspectCamera(ro-ta);\n$1')}
async function digest(text){if(!crypto.subtle)throw Error('需要安全浏览器环境进行原码SHA256校验');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),x=>x.toString(16).padStart(2,'0')).join('')}
async function verified(record){const c=config[record?.id];if(!c||typeof record.source!=='string')throw Error('案例载荷身份无效');const bytes=new TextEncoder().encode(record.source).length;if(bytes!==c.bytes||record.sha256!==c.sha256||await digest(record.source)!==c.sha256)throw Error(record.id+' 原码SHA256或字节数不匹配');return record}
async function unpack(text){if(text.length>60000)throw Error('私人载荷超长');if(!('DecompressionStream'in window))throw Error('当前浏览器不支持私人载荷解压');let b=text.replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';const data=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const body=await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('gzip'))).text();if(body.length>60000)throw Error('私人载荷解压超长');const bundle=JSON.parse(body);if(bundle.schema!=='coral-case-originals/1'||!Array.isArray(bundle.cases)||bundle.cases.length>3)throw Error('私人载荷格式无效');const records=await Promise.all(bundle.cases.map(verified));if(new Set(records.map(x=>x.id)).size!==records.length)throw Error('载荷含重复案例');return records}
function shader(gl,type,source){return window.CoralGL.shader(gl,type,source)}
function program(canvas,source,student,owner){const gl=window.CoralGL.context(canvas,owner.id);owner.pendingContexts.push(gl);const p=gl.createProgram();if(!p)throw window.CoralGL.problem('程序对象创建失败','create-program');const v=shader(gl,gl.VERTEX_SHADER,vertex),f=shader(gl,gl.FRAGMENT_SHADER,header+(student?inspectHeader+observeSource(source)+inspectTail:source+baselineTail));gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(gl.isContextLost())throw window.CoralGL.problem('链接期间上下文失效','program-link');if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'程序链接失败');gl.deleteShader(v);gl.deleteShader(f);const vao=gl.createVertexArray();if(!vao)throw window.CoralGL.problem('顶点资源创建失败','vao-create');const uniforms={};for(const n of ['iResolution','iMouse','iTime','iFrame','uInspect','uZoom','uOrbit'])uniforms[n]=gl.getUniformLocation(p,n);return{gl,p,vao,uniforms,canvas,student,fence:null}}
class Replay{
 constructor(id){this.id=id;this.c=config[id];this.root=document.querySelector('[data-original="'+id+'"]');this.q=s=>this.root.querySelector(s);this.role=n=>this.q('[data-role="'+n+'"]');this.control=n=>this.q('[data-control="'+n+'"]');this.action=n=>this.q('[data-action="'+n+'"]');this.state={version:VERSION,case:id,ready:false,error:null,sourceSHA256:this.c.sha256,sourceBytes:this.c.bytes,originalBytesVerified:false,teacherOriginalUnmodified:true,inspectionChanges:'camera and framing only',time:this.c.time,playing:false,yaw:0,pitch:0,zoom:1,reference:true,ratio:.25,quality:'native',draws:0,gpuCompleted:0,active:false,resolution:[0,0],storage:'unavailable',baselineComparison:null};this.views=[];this.pendingContexts=[];this.pendingDraw=0;this.generation=0;this.recoveryTimer=0;this.recoveryBudget=1;this.pending=0;this.dirty=true;this.lastWall=0;this.drag=null;this.pointers=new Map();this.restoreState();this.bind();this.ui();}
 mark(text){document.getElementById(this.id+'-state').textContent=text}
 report(){this.state.contextGeneration=this.generation;this.state.liveContexts=this.views.length;this.role('diagnostics').textContent=JSON.stringify(this.state,null,2);this.root.dataset.ready=String(this.state.ready);this.root.dataset.version=VERSION;this.root.dataset.case=this.id;this.state.contextGeneration=this.generation;this.state.liveContexts=this.views.length;this.persist()}
 warning(message){this.role('warning').hidden=!message;this.role('warning').textContent=message}
 fail(err){this.stop();this.releaseGPU();this.state.ready=false;this.state.error=String(err?.message||err);this.role('error').textContent='原程序运行失败：'+this.state.error+'。没有用图片或其它形状替代。';this.q('.original-student').classList.remove('ready');this.role('teacher-error').textContent='原版基线未绘制：'+this.state.error;this.mark('等待恢复 · 可重试');this.report();if(err?.gpuRecoverable)this.recover()}
 recover(){if(!this.state.active||document.hidden||this.recoveryTimer||this.recoveryBudget<=0)return;this.recoveryBudget--;this.recoveryTimer=setTimeout(()=>{this.recoveryTimer=0;if(this.state.active&&!document.hidden){this.state.error=null;this.setup()}},250)}
 persist(){try{const s=this.state;sessionStorage.setItem('coral-observation-v3:'+this.id,JSON.stringify({time:s.time,yaw:s.yaw,pitch:s.pitch,zoom:s.zoom,quality:s.quality,reference:s.reference,ratio:s.ratio}))}catch(_){}}
 restoreState(){try{const v=JSON.parse(sessionStorage.getItem('coral-observation-v3:'+this.id)||'null');if(v){for(const k of ['time','yaw','pitch','zoom','ratio'])if(Number.isFinite(v[k]))this.state[k]=v[k];if(typeof v.reference==='boolean')this.state.reference=v.reference;if(['native','hq','720','480'].includes(v.quality))this.state.quality=v.quality}}catch(_){}}
 releaseGPU(){this.generation++;this.pendingDraw=0;this.pointers.clear();this.drag=null;this.pinch=null;this.q('.original-student').classList.remove('ready');this.q('.original-teacher').classList.remove('ready');if(this.recoveryTimer){clearTimeout(this.recoveryTimer);this.recoveryTimer=0}const contexts=new Set([...this.views.map(v=>v.gl),...this.pendingContexts]);this.views=[];this.pendingContexts=[];for(const gl of contexts)window.CoralGL.dispose(gl,this.id);this.state.ready=false}

 load(record,storage){this.source=record.source;this.state.originalBytesVerified=true;this.state.storage=storage;this.role('provenance').textContent=JSON.stringify({case:this.id,originalSHA256:this.c.sha256,originalBytes:this.c.bytes,sourceBytePreserved:true,sourceInPublicRepository:false,texturesRequired:false,AA:this.c.aa,defaultTime:this.c.time,privateTransport:'URL fragment only; per-case local browser storage'},null,2);if(this.state.active)this.setup();this.report()}
 setup(){if(this.views.length||!this.source||!this.state.active||document.hidden)return;try{this.releaseGPU();this.state.error=null;this.mark('重建原码图形资源…');for(const suffix of ['canvas','teacher']){const c=document.getElementById(this.id+'-'+suffix);window.CoralGL.fresh(c)}this.bindCanvas();const generation=this.generation;for(const suffix of ['canvas','teacher'])document.getElementById(this.id+'-'+suffix).addEventListener('webglcontextlost',e=>{e.preventDefault();if(generation===this.generation&&this.views.some(v=>v.canvas===e.target&&window.CoralGL.alive(v.gl)))this.fail(window.CoralGL.problem('图形上下文中断，保留姿态重建','context-lost'))});this.views=[program(document.getElementById(this.id+'-canvas'),this.source,true,this)];if(this.state.reference)this.views.push(program(document.getElementById(this.id+'-teacher'),this.source,false,this));this.pendingContexts=[];this.state.error=null;this.dirty=true;this.reference(this.state.reference);this.ratio(this.state.ratio,false);this.control('quality').value=this.state.quality;this.request()}catch(e){this.fail(e)}}
 setActive(value){const changed=this.state.active!==value;this.state.active=value;if(!value){this.stop();this.releaseGPU()}else{if(changed)this.recoveryBudget=1;this.state.error=null;if(this.source)this.setup();this.dirty=true;this.request()}this.report()}
 stop(){this.state.playing=false;this.lastWall=0;if(this.pending){cancelAnimationFrame(this.pending);this.pending=0}this.ui()}
 request(){if(!this.pending&&this.state.active&&!document.hidden&&!this.state.error&&this.views.length)this.pending=requestAnimationFrame(ms=>this.tick(ms))}
 gpuReady(){for(const v of this.views){if(!v.fence)continue;window.CoralGL.check(v.gl,'fence-before-wait');const n=v.gl.clientWaitSync(v.fence,0,0);if(n===v.gl.WAIT_FAILED)throw window.CoralGL.problem('GPU 同步失效','fence-wait');if(n===v.gl.TIMEOUT_EXPIRED)return false;v.gl.deleteSync(v.fence);v.fence=null}if(this.pendingDraw){this.state.lastCompletedSubmission=this.pendingDraw;this.pendingDraw=0;this.state.gpuCompleted++;this.state.ready=true;this.q('.original-student').classList.add('ready');if(this.state.reference)this.q('.original-teacher').classList.add('ready');this.mark('原码已校验 · 实时运行');this.role('frame').textContent='实绘帧 '+this.state.gpuCompleted;this.report()}return true}
 tick(ms){this.pending=0;if(!this.state.active||document.hidden||this.state.error)return;try{if(this.state.playing){if(this.lastWall)this.state.time+=(ms-this.lastWall)/1000;this.dirty=true}this.lastWall=ms;const ready=this.gpuReady();if(this.dirty&&ready){this.dirty=false;this.draw()}if(this.state.playing||this.dirty||this.views.some(v=>v.fence))this.request()}catch(e){this.fail(e)}}
 resize(){const rect=this.q('.original-student .original-screen').getBoundingClientRect();const dpr=devicePixelRatio||1,mul=this.state.quality==='hq'?1.5:1;let w=Math.max(1,Math.round(rect.width*dpr*mul)),h=Math.max(1,Math.round(rect.height*dpr*mul));if(/^\d+$/.test(this.state.quality)){const f=Math.min(1,Number(this.state.quality)/w);w=Math.round(w*f);h=Math.round(h*f)}let limit=Infinity;for(const v of this.views){window.CoralGL.check(v.gl,'resize-capabilities');const max=v.gl.getParameter(v.gl.MAX_VIEWPORT_DIMS);if(!max)throw window.CoralGL.problem('画布能力查询失效','resize-capabilities');limit=Math.min(limit,max[0]/w,max[1]/h,v.gl.getParameter(v.gl.MAX_RENDERBUFFER_SIZE)/Math.max(w,h))}const f=Math.min(1,limit);w=Math.max(1,Math.floor(w*f));h=Math.max(1,Math.floor(h*f));this.state.resolution=[w,h];this.state.devicePixelRatio=dpr;this.state.viewportCSS=[rect.width,rect.height];this.state.hardwareLimited=f<1;for(const v of this.views){if(v.canvas.width!==w||v.canvas.height!==h){v.canvas.width=w;v.canvas.height=h}v.gl.viewport(0,0,w,h)}this.role('resolution').textContent='WebGL2 · '+w+'×'+h+' · AA='+this.c.aa;}
 draw(){this.resize();const s=this.state,[w,h]=s.resolution;for(const v of this.views){if(!v.student&&!s.reference)continue;const {gl,p,vao,uniforms:u}=v;window.CoralGL.check(gl,'frame-start');if(!gl.isProgram(p)||!gl.isVertexArray(vao))throw window.CoralGL.problem('绘制资源已失效','resource-validation');gl.useProgram(p);gl.bindVertexArray(vao);gl.uniform3f(u.iResolution,w,h,1);gl.uniform4f(u.iMouse,0,0,0,0);gl.uniform1f(u.iTime,s.time);gl.uniform1i(u.iFrame,s.draws);if(v.student){gl.uniform1f(u.uZoom,s.zoom);gl.uniform1i(u.uInspect,s.yaw!==0||s.pitch!==0?1:0);gl.uniform2f(u.uOrbit,s.yaw*Math.PI/180,s.pitch*Math.PI/180)}window.CoralGL.check(gl,'uniforms');gl.drawArrays(gl.TRIANGLES,0,3);window.CoralGL.check(gl,'draw');v.fence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);if(!v.fence)throw window.CoralGL.problem('GPU提交标记创建失败','fence-create');window.CoralGL.check(gl,'fence-create');gl.flush()}s.draws++;this.pendingDraw=s.draws;this.ui();}
 ui(){const s=this.state;this.action('play').textContent=s.playing?'暂停':'连续播放';this.role('time').textContent='原码 '+s.time.toFixed(3)+' s';this.control('time').max=String(this.id==='transparent'?48:Math.max(126,Math.ceil((s.time+1)/126)*126));this.control('time').value=this.id==='transparent'?s.time%48:s.time;if(document.activeElement!==this.control('jump'))this.control('jump').value=s.time.toFixed(3);this.control('zoom').value=String(s.zoom);if(!this.control('zoom').value){let o=this.control('zoom').querySelector('[data-current]');if(!o){o=document.createElement('option');o.dataset.current='1';this.control('zoom').append(o)}o.value=String(s.zoom);o.textContent=Math.round(s.zoom*100)+'%';this.control('zoom').value=o.value}this.role('angles').textContent='水平 '+s.yaw.toFixed(0)+'° · 垂直 '+s.pitch.toFixed(0)+'°';const modified=s.yaw!==0||s.pitch!==0||s.zoom!==1;this.role('mode').textContent=modified?'观察镜头 · 原形态原色':'原版基线 · 未改变镜头';this.action('original').classList.toggle('active',!modified);this.action('zoom-out').disabled=s.zoom<=1;this.action('zoom-in').disabled=s.zoom>=100;this.action('reference').setAttribute('aria-expanded',String(s.reference));this.action('reference').classList.toggle('active',s.reference);this.action('focus').classList.toggle('active',!s.reference);this.role('ratio').textContent=Math.round(s.ratio*100)+'%';this.action('smaller').disabled=s.ratio<=.25;this.action('larger').disabled=s.ratio>=1;this.report()}
 seek(t){this.stop();this.state.time=Math.max(0,Number(t)||0);this.dirty=true;this.ui();this.request()}
 inspect(yaw,pitch,zoom){this.state.yaw=((Number(yaw)+180)%360+360)%360-180;this.state.pitch=Math.max(-75,Math.min(75,Number(pitch)||0));this.state.zoom=Math.max(1,Math.min(100,Number(zoom)||1));this.dirty=true;this.ui();this.request()}
 reference(value){this.state.reference=!!value;this.q('.original-grid').dataset.reference=value?'open':'closed';this.q('.original-teacher').hidden=!value;if(this.views.length){if(!value){const removed=this.views.filter(v=>!v.student);this.views=this.views.filter(v=>v.student);for(const v of removed)window.CoralGL.dispose(v.gl,this.id+'-teacher')}else if(!this.views.some(v=>!v.student)){try{const c=window.CoralGL.fresh(document.getElementById(this.id+'-teacher')),generation=this.generation;c.addEventListener('webglcontextlost',e=>{e.preventDefault();if(generation===this.generation&&this.views.some(v=>v.canvas===c&&window.CoralGL.alive(v.gl)))this.fail(window.CoralGL.problem('老师参考图形上下文中断','context-lost'))});this.views.push(program(c,this.source,false,this));this.pendingContexts=[]}catch(e){this.fail(e)}}}this.dirty=true;this.ui();this.request()}

 ratio(v,reopen=true){this.state.ratio=Math.max(.25,Math.min(1,v));this.q('.original-grid').style.setProperty('--original-ratio',this.state.ratio+'fr');this.q('.original-grid').style.setProperty('--original-mobile',Math.max(55,this.state.ratio*100)+'%');if(reopen)this.reference(true);else this.ui()}
 bind(){const on=(name,fn)=>this.action(name).addEventListener('click',fn),s=this.state;on('play',()=>{if(!s.ready)return;s.playing=!s.playing;this.lastWall=0;this.ui();this.request()});on('previous',()=>this.seek(s.time-3));on('next',()=>this.seek(s.time+3));on('reset-time',()=>this.seek(this.c.time));on('jump',()=>this.seek(this.control('jump').value));this.control('time').oninput=e=>this.seek(e.target.value);this.control('quality').onchange=e=>{s.quality=e.target.value;this.dirty=true;this.request()};on('original',()=>this.inspect(0,0,1));on('retry',()=>{this.recoveryBudget=1;this.state.error=null;this.releaseGPU();this.setup()});for(const [name,y,p] of [['left',-15,0],['right',15,0],['up',0,15],['down',0,-15]])on(name,()=>this.inspect(s.yaw+y,s.pitch+p,s.zoom));on('zoom-in',()=>this.inspect(s.yaw,s.pitch,s.zoom+1));on('zoom-out',()=>this.inspect(s.yaw,s.pitch,s.zoom-1));this.control('zoom').onchange=e=>this.inspect(s.yaw,s.pitch,e.target.value);on('reference',()=>this.reference(!s.reference));on('close-reference',()=>this.reference(false));on('focus',()=>this.reference(false));on('equal',()=>this.ratio(1));on('smaller',()=>this.ratio(s.ratio-.25));on('larger',()=>this.ratio(s.ratio+.25));on('layout',()=>{s.quality='native';this.control('quality').value='native';this.ratio(.25)});on('fullscreen',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await this.q('.original-student').requestFullscreen()}catch(e){this.warning('此浏览器全屏未成功：'+e.message)}});
 this.bindCanvas();new ResizeObserver(()=>{this.dirty=true;this.request()}).observe(this.q('.original-student .original-screen'));}
 bindCanvas(){const s=this.state;const canvas=document.getElementById(this.id+'-canvas');canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,yaw:s.yaw,pitch:s.pitch,zoom:s.zoom};if(this.pointers.size===2){const [a,b]=[...this.pointers.values()];this.pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:s.zoom}}});canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2&&this.pinch){const[a,b]=[...this.pointers.values()];this.inspect(s.yaw,s.pitch,Math.round(this.pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,this.pinch.distance)));return}if(this.drag&&this.pointers.size===1){const r=canvas.getBoundingClientRect();this.inspect(this.drag.yaw+(e.clientX-this.drag.x)/r.width*180,this.drag.pitch+(e.clientY-this.drag.y)/r.height*120,s.zoom)}});const up=e=>{this.pointers.delete(e.pointerId);this.drag=null;this.pinch=null};canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',up);canvas.addEventListener('wheel',e=>{e.preventDefault();this.inspect(s.yaw,s.pitch,s.zoom+(e.deltaY<0?1:-1))},{passive:false});}
}
for(const id of ['color','transparent'])instances[id]=new Replay(id);let resolveSources;window.CoralPrivateSources={ready:new Promise(r=>resolveSources=r),get:id=>sources[id]||null};
function select(id){current=id;for(const [key,instance]of Object.entries(instances))if(key!==id)instance.setActive(false);if(instances[id])instances[id].setActive(true)}
window.addEventListener('coral:view',e=>select(e.detail.id));document.addEventListener('visibilitychange',()=>{for(const instance of Object.values(instances)){if(document.hidden){instance.stop();instance.releaseGPU()}else if(instance.state.active){instance.recoveryBudget=1;instance.state.error=null;instance.setup();instance.dirty=true;instance.request()}}});window.addEventListener('pagehide',()=>{for(const instance of Object.values(instances)){instance.stop();instance.releaseGPU()}});document.addEventListener('fullscreenchange',()=>{for(const instance of Object.values(instances)){instance.dirty=true;instance.request()}});
async function boot(){let incoming=[];try{if(packed)incoming=await unpack(packed)}catch(e){for(const instance of Object.values(instances))instance.fail(e);resolveSources(sources);return}for(const record of incoming)sources[record.id]=record;for(const id of Object.keys(config)){let storage='this-visit-only';try{if(sources[id]){localStorage.setItem(key(id),JSON.stringify(sources[id]));storage='saved-per-case-and-hash'}else{const cached=localStorage.getItem(key(id));if(cached){sources[id]=await verified(JSON.parse(cached));storage='restored-per-case-and-hash'}}}catch(e){instances[id]?.warning('此浏览器无法保存或恢复私人原码；本次私人链接仍可运行。'+e.message)}if(sources[id]&&instances[id])instances[id].load(sources[id],storage);else if(instances[id]){instances[id].mark('当前浏览器尚无此例原码');instances[id].role('error').textContent='请从发给你的私人工作台链接打开一次。它会直接装入原码，并在这里显示可旋转的实时画面。无需粘贴或另行导入。';instances[id].role('teacher-error').textContent='等待同一案例的私人原码';instances[id].report()}}resolveSources(sources);window.dispatchEvent(new CustomEvent('coral:sources-ready'));select(current)}
window.addEventListener('hashchange',()=>{const value=new URLSearchParams(location.hash.slice(1)).get('originals');if(value&&value!==packed){packed=value;boot()}});
window.addEventListener('pageshow',()=>{select(current)});select(current);boot();
})();

