import * as THREE from 'three';
// Read-only source-tail study. Helpers never replace source geometry or invent a swim.
export function installTailStudy(ctx){
 const {compiled,meshes,state,qa,scenes,cam,controls,preset,regionTool,getSurfaces,readSurface}=ctx,$=s=>document.querySelector(s);
 const el=$('#tailEvidence'),data=JSON.parse(el.textContent);el.remove();const selection={id:'none',trail:false,isolated:false};
 const panel=document.createElement('div');panel.className='section';panel.id='tailPanel';panel.innerHTML='<h2>01G　尾部与原连接处 · R010</h2><p class="sub">保留 750 个原尾部面、14 对原接口边和 12 个作者控制。接口不直接当作已核准尾柄边界。</p><select id="tailSelect" class="w100" aria-label="尾部源观测点"><option value="none">全鱼 · 选择尾部源观测点</option><option value="upper">源静息上端点</option><option value="lower">源静息下端点</option><option value="aft">源静息后端点</option></select><div class="row"><button id="tailFocus">放大尾部</button><button id="tailIsolate">单独看原尾部</button></div><div class="row"><button id="tailMin">原样本较小侧偏</button><button id="tailMax">原样本较大侧偏</button></div><div class="row"><button id="tailTrail">原表面点轨迹</button><button id="tailClear">恢复全鱼</button></div><pre id="tailLive">观察原尾部曲面和连接处怎样随 Swim 运动，不另编动作。</pre><details><summary>源身份与测量定义</summary><pre id="tailSource"></pre><p class="sub">观测点取原静息尾部的 Y 上下极值和 X 后端极值，始终保留同一原索引。接口平均点与作者控制枢轴不是解剖中心。长度为归一鱼长比例，面积为其平方；随动参考系侧偏不是推进力或真实生物学摆幅。</p></details>';
 $('#headPanel').before(panel);
 const makeLines=color=>{const o=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color,depthTest:false}));o.frustumCulled=false;o.renderOrder=48;o.visible=false;scenes[1].add(o);return o;};
 const edge=makeLines(0x73e6d3),span=makeLines(0xffc679),rig=makeLines(0xc2cfff);
 const points=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffc679,size:7,sizeAttenuation:false,depthTest:false}));points.frustumCulled=false;points.renderOrder=50;points.visible=false;scenes[1].add(points);
 const trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xffb56c,depthTest:false,transparent:true,opacity:.8}));trail.frustumCulled=false;trail.renderOrder=47;trail.visible=false;scenes[1].add(trail);const overlays=[edge,span,rig,points,trail];
 const vec=(s,i)=>new THREE.Vector3().fromArray(s.p,i*3),position=o=>new THREE.Vector3().setFromMatrixPosition(o.matrixWorld);
 function fill(o,a){const old=o.geometry.getAttribute('position');if(old&&old.array.length===a.length){old.array.set(a);old.needsUpdate=true;}else{o.geometry.dispose();o.geometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(a,3));}}
 function rotation(m){const a=new THREE.Matrix3().setFromMatrix4(m),e=a.elements;for(let c=0;c<3;c++){const d=Math.hypot(e[c*3],e[c*3+1],e[c*3+2]);for(let r=0;r<3;r++)e[c*3+r]/=d;}return a;}
 const restAxes=rotation(new THREE.Matrix4().fromArray(data.restRootMatrix));
 function measure(surfs,rootMatrix){const s=surfs[data.mesh],a=data.anchors.map(x=>vec(s,x.sourceVertex)),ip=data.interfaceVertices.map(x=>vec(s,x.sourceVertex)),mean=ip.reduce((m,v)=>m.add(v),new THREE.Vector3()).divideScalar(ip.length),r=rotation(rootMatrix).multiply(restAxes.clone().transpose()),offsets=a.map(v=>v.clone().sub(mean).applyMatrix3(r.clone().transpose()));let area=0,gap=0;const ab=new THREE.Vector3(),ac=new THREE.Vector3();for(const f of data.sourceTriangles){const ids=s.idx.subarray(f*3,f*3+3),x=vec(s,ids[0]),y=vec(s,ids[1]),z=vec(s,ids[2]);area+=ab.subVectors(y,x).cross(ac.subVectors(z,x)).length()*.5;}for(const e of data.interfaceEdges)for(let k=0;k<2;k++)gap=Math.max(gap,vec(s,e.tailVertices[k]).distanceTo(vec(s,e.trunkVertices[k])));
 return {anchors:a,interfacePoints:ip,mean,metrics:{upperLowerSpan:a[0].distanceTo(a[1]),interfaceMeanToUpper:a[0].distanceTo(mean),interfaceMeanToLower:a[1].distanceTo(mean),upperFrameLateral:offsets[0].z,lowerFrameLateral:offsets[1].z,sourceTailSurfaceArea:area,interfaceMaxGap:gap}};}
 function update(){if(selection.id==='none'||!getSurfaces()?.length)return;const s=getSurfaces()[data.mesh],obs=measure(getSurfaces(),compiled.nodes[data.rootNode].matrixWorld),i=data.anchors.findIndex(a=>a.id===selection.id);fill(points,[...obs.anchors.flatMap(v=>v.toArray()),...obs.mean.toArray()]);fill(span,[...obs.mean.toArray(),...obs.anchors[i].toArray()]);fill(edge,data.interfaceEdges.flatMap(e=>e.tailVertices.flatMap(i=>vec(s,i).toArray())));fill(rig,data.controls.flatMap(n=>[...position(compiled.nodes[n.parent]).toArray(),...position(compiled.nodes[n.node]).toArray()]));edge.visible=span.visible=rig.visible=points.visible=true;trail.visible=selection.trail;
 qa.tailCurrent={id:selection.id,time:state.time,rest:state.rest,sourceVertex:data.anchors[i].sourceVertex,metrics:obs.metrics,isolated:selection.isolated};const q=obs.metrics;$('#tailLive').textContent=(state.rest?'原静息态':'原 Swim '+state.time.toFixed(4)+' s')+'\n原索引 '+data.anchors[i].sourceVertex+' · '+(selection.isolated?'仅显示完整源尾部':'全鱼对照')+'\n上下端跨度 '+q.upperLowerSpan.toFixed(6)+'\n接口均点→上端 '+q.interfaceMeanToUpper.toFixed(6)+'\n接口均点→下端 '+q.interfaceMeanToLower.toFixed(6)+'\n上端随动侧偏 '+q.upperFrameLateral.toFixed(6)+'\n下端随动侧偏 '+q.lowerFrameLateral.toFixed(6)+'\n源尾部表面积 '+q.sourceTailSurfaceArea.toFixed(6)+'\n接口最大间距 '+q.interfaceMaxGap.toExponential(2);}
 function hide(){selection.id='none';selection.isolated=false;$('#tailSelect').value='none';$('#tailIsolate').classList.remove('active');overlays.forEach(o=>o.visible=false);qa.tailEnabled=false;}
 function choose(id){if(id==='none'){clear();return;}const i=data.anchors.findIndex(a=>a.id===id);if(i<0)throw Error('Unknown source tail anchor');ctx.clearOther();regionTool.restore();window.FISH_CANONICAL.choose(-1);selection.id=id;selection.isolated=false;$('#tailSelect').value=id;$('#tailIsolate').classList.remove('active');qa.tailEnabled=true;fill(trail,data.samples.flatMap(s=>s.anchorPoints[i]));$('#tailSource').textContent=JSON.stringify({anchor:data.anchors[i],frameNode:data.rootNode,frameSourceName:data.rootName,sourceControls:data.controls.map(c=>c.sourceName),sourceTracks:36,biologicalApproval:false},null,2);update();}
 function focus(){if(selection.id==='none')choose('upper');const s=getSurfaces()[data.mesh],box=new THREE.Box3();for(const i of data.sourceVertices)box.expandByPoint(vec(s,i));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),dir=cam.position.clone().sub(controls.target).normalize();controls.target.copy(center);cam.position.copy(center).addScaledVector(dir,3);cam.zoom=Math.max(1,Math.min(5,.72/Math.max(size.x,size.y,size.z)));cam.updateProjectionMatrix();controls.update();}
 function clear(){hide();regionTool.restore();preset('side');}
 function peak(kind){if(selection.id==='none')choose('upper');const key=selection.id==='lower'?'lowerFrameLateral':'upperFrameLateral',index=data.summary[key][kind+'Index'];ctx.jumpExact(data.samples[index].time);$('#time').value=state.time;$('#timeLabel').textContent=state.time.toFixed(3)+' s · 原尾部样本';qa.tailSelectedSample={kind,index,key};focus();update();}
 function audit(){const saved=selection.id;selection.id='none';overlays.forEach(o=>o.visible=false);let pointMax=0,matrixMax=0,lengthMax=0,areaMax=0;const ids=compiled.pkg.skeletonGraphs[0].jointNodes;ctx.beginExact();try{for(const sample of [data.restSample,...data.samples]){ctx.seekExact(sample.time??0,sample.rest);for(const rt of [0,1]){const bone=id=>rt===0?meshes[0][0].skeleton.bones[ids.indexOf(id)]:compiled.nodes[id];const obs=measure(rt===0?readSurface(0):getSurfaces(),bone(data.rootNode).matrixWorld);sample.controlMatrices.forEach(n=>n.matrix.forEach((v,k)=>matrixMax=Math.max(matrixMax,Math.abs(v-bone(n.node).matrixWorld.elements[k]))));obs.anchors.forEach((p,i)=>pointMax=Math.max(pointMax,p.distanceTo(new THREE.Vector3().fromArray(sample.anchorPoints[i]))));obs.interfacePoints.forEach((p,i)=>pointMax=Math.max(pointMax,p.distanceTo(new THREE.Vector3().fromArray(sample.interfacePoints[i]))));for(const [key,value]of Object.entries(obs.metrics)){const error=Math.abs(value-sample.metrics[key]);if(key==='sourceTailSurfaceArea')areaMax=Math.max(areaMax,error);else lengthMax=Math.max(lengthMax,error);}}}}finally{ctx.endExact();selection.id=saved;if(saved!=='none')update();}
 return {restSamples:1,clampedTimes:data.samples.length,comparedRuntimes:2,controls:data.controls.length,sourceTailTriangles:data.sourceTriangles.length,sourceAttachmentEdges:data.interfaceEdges.length,pointMaxError:pointMax,matrixMaxError:matrixMax,lengthMaxError:lengthMax,surfaceAreaMaxError:areaMax,lengthTolerance:1e-6,areaTolerance:1e-8,passed:Math.max(pointMax,matrixMax,lengthMax)<1e-6&&areaMax<1e-8,anatomicalApproval:false};}
 $('#tailSelect').onchange=e=>choose(e.target.value);$('#tailFocus').onclick=focus;$('#tailMin').onclick=()=>peak('min');$('#tailMax').onclick=()=>peak('max');$('#tailClear').onclick=clear;$('#tailTrail').onclick=()=>{if(selection.id==='none')choose('upper');selection.trail=!selection.trail;$('#tailTrail').classList.toggle('active',selection.trail);update();};$('#tailIsolate').onclick=()=>{if(selection.id==='none')choose('upper');selection.isolated=!selection.isolated;regionTool.selection.isolate=selection.isolated;regionTool.choose('tail');if(!selection.isolated){regionTool.restore();window.FISH_CANONICAL.choose(-1);}$('#tailIsolate').classList.toggle('active',selection.isolated);update();};
 for(const id of ['#featureSelect','#headSelect','#regionSelect','#groupSelect','#jointSelect','#interfaceSelect'])$(id)?.addEventListener('change',hide);
 for(const id of ['#oralShow','#oralMin','#oralMax','#oralFront','#headFocus','#headPeak','#featureMin','#featureMax','#featureFocus','#regionClear','#boundaryClear'])$(id)?.addEventListener('click',()=>{if(selection.id!=='none'){hide();regionTool.restore();}},true);
 qa.tailStudy=data.qa;qa.tailEnabled=false;const api={data,selection,choose,hide,clear,focus,peak,update,audit};window.FISH_TAIL=api;return api;
}
