/** Exhaustive parameter route audit. Positive response is not visual acceptance. */
import fs from 'node:fs';import assert from 'node:assert/strict';import{createCommon}from'../create-common.mjs';import{defaultState}from'../src/State.mjs';
const model=createCommon({headDriver:true}),rows=[],started=performance.now();let count=0;
function test(source,group,key,s,base,description){const v=model.compute(s);assert(v.every(Number.isFinite),source+group+key+' nonfinite');let max=0,changed=0,at=0;for(let i=0;i<v.length;i++){const d=Math.abs(v[i]-base[i]);if(d>max){max=d;at=i;}if(d>1e-8)changed++;}rows.push({source,group,key,value:description,maxMetres:max,changedCoordinatesAbove10nm:changed,maximumVertex:Math.floor(at/3),activeOwners:{...s.owners},response:max>1e-8});if(++count%50===0){fs.writeFileSync(new URL('../research/all-parameter-audit-progress.json',import.meta.url),JSON.stringify({count,elapsedSeconds:(performance.now()-started)/1000,last:{source,group,key}}));console.log(count,source,group,key);}}
for(const[group,n,val]of[['identity',253,.5],['expression',383,.5],['rotation',12,.15],['translation',3,.004]]){const s=defaultState(),base=model.compute(s).slice();for(let i=0;i<n;i++){const t=structuredClone(s);t.gnm[group][i]=val;test('gnm',group,i,t,base,val);}}
const a=defaultState();a.owners.headShape='anny';a.owners.expression='anny';a.owners.headRig='body';a.owners.gaze='rig';
for(const group of['phenotypes','localChanges','facialActions','pose','translations']){const s=structuredClone(a);if(group==='facialActions')s.owners.gaze='expression';const base=model.compute(s).slice();const labels=group==='phenotypes'?model.anny.phenotypeLabels:group==='localChanges'?model.anny.localChangeLabels:group==='facialActions'?model.anny.facialActionLabels:model.anny.boneLabels;
 for(const key of labels){if(['pose','translations'].includes(group)){for(let axis=0;axis<3;axis++){const t=structuredClone(s),v=[0,0,0];v[axis]=group==='pose'?15:.003;t.anny[group][key]=v;test('anny',group,key+':'+axis,t,base,v);}}else{const t=structuredClone(s);t.anny[group][key]=group==='phenotypes'?.8:.5;test('anny',group,key,t,base,t.anny[group][key]);}}}
const m=defaultState();m.owners.rig='mhr';m.owners.headRig='body';m.owners.headShape='mhr';m.owners.expression='mhr';m.owners.gaze='expression';
for(const[group,n]of[['identity',45],['pose',204],['expression',72]]){const s=structuredClone(m),base=model.compute(s).slice();for(let i=0;i<n;i++){let value=.5;if(group==='pose'){const[lo,hi]=model.mhrMeta.pose_limits[i];if(lo===hi){rows.push({source:'mhr',group,key:i,locked:true,value:lo,response:false,reason:'Official fixed parameter'});continue;}value=hi>0?Math.min(.2,hi*.5):Math.max(-.2,lo*.5);}const t=structuredClone(s);t.mhr[group][i]=value;test('mhr',group,i,t,base,value);}}
assert.equal(rows.length,1908);assert.equal(rows.filter(x=>x.locked).length,37);assert.equal(rows.filter(x=>!x.locked&&!x.response).length,0,'A variable parameter lacks a canonical response');const report={fingerprint:model.adapterFingerprint,numericalOnly:true,visualAcceptance:false,nominalScalarCatalog:1596,extraAnnyBoneTranslations:312,records:rows.length,locked:rows.filter(x=>x.locked).length,activeWithoutMeshResponse:rows.filter(x=>!x.locked&&!x.response),elapsedSeconds:(performance.now()-started)/1000,rows};fs.writeFileSync(new URL('../research/all-parameter-audit.json',import.meta.url),JSON.stringify(report,null,2));console.log({records:rows.length,locked:report.locked,activeWithoutMeshResponse:report.activeWithoutMeshResponse.map(x=>[x.source,x.group,x.key]),elapsedSeconds:report.elapsedSeconds});
