'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const base=path.resolve(__dirname,'..'),out=path.resolve(process.env.HAIYU_POINTFIELD_OUT||'haiyu-pointfield-results');fs.mkdirSync(out,{recursive:true});
const frames=[1,60,120,240,480,960],reports=[];
function runtime(id){const trace={points:[],background:[],stroke:[],sizes:[]};const c={Math,PI:Math.PI,sin:Math.sin,cos:Math.cos,mag:(x,y)=>Math.sqrt(x*x+y*y),point:(x,y)=>trace.points.push([x,y]),createCanvas:(...x)=>trace.sizes.push(x),stroke:(...x)=>trace.stroke.push(x),background:(...x)=>{trace.background.push(x);return c;}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(base,`source${id}.js`),'utf8'),c);return {c,trace};}
const oracle=path.join(out,'oracle08.bin');cp.execFileSync('java',[path.join(__dirname,'ProcessingOracle.java'),oracle]);const binary=fs.readFileSync(oracle),r8=runtime('08');let pos=0,max8=0;
for(let f=1;f<=960;f++){if(!frames.includes(f)){vm.runInContext('t=Math.fround(t+Math.fround(.1))',r8.c);continue;}r8.trace.points=[];vm.runInContext('draw()',r8.c);assert.equal(binary.readInt32BE(pos),f);pos+=4;assert.equal(binary.readFloatBE(pos),vm.runInContext('t',r8.c));pos+=4;assert.equal(r8.trace.points.length,40000);let max=0;for(const point of r8.trace.points)for(const v of point){const expected=binary.readFloatBE(pos);pos+=4;max=Math.max(max,Math.abs(v-expected));assert.equal(v,expected);}max8=Math.max(max8,max);reports.push({source:'08',frame:f,points:40000,t:vm.runInContext('t',r8.c),maxCoordinateError:max,oracle:'Java 21 Processing float operations'});}
assert.equal(pos,binary.length);assert.deepEqual(r8.trace.sizes,[[400,400]]);assert.ok(r8.trace.background.every(x=>x[0]===6));assert.ok(r8.trace.stroke.every(x=>x[0]===255));
const r9=runtime('09');let t=0;
for(let f=1;f<=960;f++){t+=Math.PI/240;if(!frames.includes(f)){vm.runInContext('t+=PI/240',r9.c);continue;}r9.trace.points=[];vm.runInContext('draw()',r9.c);assert.equal(r9.trace.points.length,10000);assert.equal(vm.runInContext('t',r9.c),t);let n=0,max=0;for(let i=9999;i>=0;i--){const x=i,y=i/235,k=(4+Math.sin(y*2-t)*3)*Math.cos(x/29),e=y/8-13,d=Math.sqrt(k*k+e*e),q=3*Math.sin(k*2)+.3/k+Math.sin(y/25)*k*(9+4*Math.sin(e*9-d*3+t*2)),c=d-t,p=[q+30*Math.cos(c)+200,q*Math.sin(c)+d*39-220];for(let j=0;j<2;j++){max=Math.max(max,Math.abs(r9.trace.points[n][j]-p[j]));assert.equal(r9.trace.points[n][j],p[j]);}n++;}reports.push({source:'09',frame:f,points:10000,t,maxCoordinateError:max,oracle:'Independently expanded screenshot expression; descending i and fractional y'});}
assert.deepEqual(r9.trace.sizes,[[400,400]]);assert.ok(r9.trace.background.every(x=>x[0]===9));assert.ok(r9.trace.stroke.every(x=>x[0]===400&&x[1]===96));
const report={ok:true,source08Float32Preserved:true,source08IntegerDivisionPreserved:true,source09NoSingularityClamp:true,sourceFrameAdvanceNotWallSeconds:true,realVideoReferenceReviewed:false,totalComparedPoints:300000,checks:reports};fs.writeFileSync(path.join(out,'fidelity.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
