import * as T from 'three';
import {rng} from './world.js';
function smokeTexture(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,.72)');g.addColorStop(.35,'rgba(242,242,242,.60)');g.addColorStop(.7,'rgba(216,216,216,.25)');g.addColorStop(1,'rgba(200,200,200,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);return new T.CanvasTexture(c);}
export class Effects {
 constructor(scene,audio){this.scene=scene;this.audio=audio;this.bombs=[];this.blasts=[];this.scars=[];this.impactCount=0;this.target=null;this.lastImpact=-100;this.texture=smokeTexture();this.geo=new T.SphereGeometry(1,16,10);this.bodyMat=new T.MeshStandardMaterial({color:0x535734,metalness:.45,roughness:.55});this.root=new T.Group();this.root.name='MISSION_EFFECTS';scene.add(this.root);}
 release(position,velocity,time,side,quiet=false){const o=new T.Group();o.name='RELEASED_BOMB';const body=new T.Mesh(this.geo,this.bodyMat);body.scale.set(.19,.19,.70);o.add(body);for(let i=0;i<2;i++){const f=new T.Mesh(new T.BoxGeometry(.70,.025,.34),this.bodyMat);f.position.z=-.53;f.rotation.z=i*Math.PI/2;o.add(f);}o.position.copy(position);o.position.x+=side;this.root.add(o);this.bombs.push({o,p:o.position.clone(),v:velocity.clone(),time,hit:false,quiet});}
 explode(position,time,quiet=false){this.impactCount++;this.target=position.clone();this.lastImpact=time;if(!quiet)this.audio.oneShot('explosion');const group=new T.Group();group.position.copy(position);group.name='GROUND_EXPLOSION';this.root.add(group);const random=rng(1450+this.impactCount),parts=[];
  for(let i=0;i<10;i++){const mat=new T.MeshBasicMaterial({color:i%2?0xff8d2e:0xffce69,transparent:true,opacity:.95,depthWrite:false});const mesh=new T.Mesh(this.geo,mat);mesh.position.set((random()-.5)*5,random()*4,(random()-.5)*5);group.add(mesh);parts.push({mesh,offset:mesh.position.clone(),speed:1+random()});}
  const ring=new T.Mesh(new T.RingGeometry(.86,1,80),new T.MeshBasicMaterial({color:0xc2b396,transparent:true,opacity:.42,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.07;group.add(ring);
  const smoke=[];for(let i=0;i<28;i++){const s=new T.Sprite(new T.SpriteMaterial({map:this.texture,color:i%3?0x57574c:0x777269,transparent:true,opacity:0,depthWrite:false}));s.position.set((random()-.5)*10,random()*6,(random()-.5)*10);group.add(s);smoke.push({s,base:s.position.clone(),v:new T.Vector3((random()-.2)*1.2,1.8+random()*2.1,(random()-.5)*1.2),delay:random()*2,size:4+random()*7});}
  const debris=[];for(let i=0;i<18;i++){const d=new T.Mesh(new T.BoxGeometry(.12,.11,.21),new T.MeshStandardMaterial({color:0x4d422d,roughness:1}));group.add(d);debris.push({mesh:d,v:new T.Vector3((random()-.5)*26,10+random()*15,(random()-.5)*26)});}
  const light=new T.PointLight(0xffa74b,90,45,2);light.position.y=5;group.add(light);
  const scar=new T.Mesh(new T.CircleGeometry(6.7,48),new T.MeshBasicMaterial({map:this.texture,color:0x201b12,transparent:true,opacity:.76,depthWrite:false}));scar.rotation.x=-Math.PI/2;scar.position.copy(position);scar.position.y=.016;this.root.add(scar);this.scars.push(scar);
  this.blasts.push({group,time,parts,ring,smoke,debris,light});
 }
 update(time,quiet=false){for(const b of this.bombs){const a=Math.max(0,time-b.time);if(b.hit)continue;b.o.position.copy(b.p).addScaledVector(b.v,a);b.o.position.y-=4.905*a*a;const vel=b.v.clone();vel.y-=9.81*a;b.o.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),vel.normalize());if(b.o.position.y<=.15){const impactAge=(b.v.y+Math.sqrt(b.v.y*b.v.y+19.62*(b.p.y-.15)))/9.81;const p=b.p.clone().addScaledVector(b.v,impactAge);p.y=.03;b.hit=true;b.o.visible=false;this.explode(p,b.time+impactAge,quiet||b.quiet);}}
  for(const e of this.blasts){const age=Math.max(0,time-e.time);e.group.visible=age<26;if(!e.group.visible)continue;for(const p of e.parts){const a=age*p.speed;const scale=Math.max(.01,(1-Math.exp(-a*4))*5.0);p.mesh.scale.setScalar(scale);p.mesh.position.copy(p.offset);p.mesh.position.y+=age*2;p.mesh.material.opacity=Math.max(0,1-age/2.4);p.mesh.visible=age<2.4;}
    e.ring.scale.setScalar(1+age*19);e.ring.material.opacity=Math.max(0,.4*(1-age/2.7));e.ring.visible=age<2.7;e.light.intensity=90*Math.exp(-age*3.3);
    for(const p of e.smoke){const a=Math.max(0,age-p.delay);p.s.position.copy(p.base).addScaledVector(p.v,a);p.s.scale.setScalar(p.size+a*1.8);p.s.material.opacity=(1-Math.exp(-a*3))*.65*Math.max(0,1-a/25);}
    for(const d of e.debris){d.mesh.position.copy(d.v).multiplyScalar(age);d.mesh.position.y-=4.905*age*age;d.mesh.visible=age<4&&d.mesh.position.y>=0;d.mesh.rotation.set(age*2,age,age*3);}
  }
 }
 reset(){for(const c of [...this.root.children]){this.root.remove(c);c.traverse(o=>{if(o.material&&o.material!==this.bodyMat)o.material.dispose();if(o.geometry&&o.geometry!==this.geo)o.geometry.dispose();});}this.bombs=[];this.blasts=[];this.scars=[];this.impactCount=0;this.lastImpact=-100;this.target=null;}
}
