/* Original06 XY preserved; explicit quadrature lift, not an anatomical claim. */
(()=>{'use strict';
const $=id=>document.getElementById(id),panel=$('sourceSpace'),canvas=$('phaseCanvas'),sin=Math.sin,cos=Math.cos;
const state={active:false,frame:1,playing:false,yaw:.58,pitch:.22,zoom:1,depth:1,lit:true,size:2.2,dirty:true,points:[],sourceReady:false,drag:null,last:0,pending:false,token:0};
const clock=[0];for(let n=1;n<=480;n++)clock.push(clock[n-1]+Math.PI/120);
function sourcePoint(i,t){const y=i/885,k=(6+3*sin(y+4))*cos(i/7),e=y/5-13,d=Math.hypot(k,e)-6.6,q=3*sin(k*2)+k*y/25*(9+2*sin(e*6-d*5+t*2)),c=d-t;return{x:q+30*cos(c)+200,y:q*sin(c)+d*39,z:q*cos(c),q,c,d};}
function evaluate(frame,depth=1){const t=clock[frame],p=[];for(let i=19999;i>=0;i--){const a=sourcePoint(i,t);p.push([a.x-200,200-a.y,a.z*depth]);}return p;}
function rotate(p){const cy=cos(state.yaw),sy=sin(state.yaw),cp=cos(state.pitch),sp=sin(state.pitch),x=p[0]*cy+p[2]*sy,z=-p[0]*sy+p[2]*cy;return[x,p[1]*cp-z*sp,p[1]*sp+z*cp]}
let gl=canvas.getContext('webgl',{alpha:false,antialias:true,preserveDrawingBuffer:true}),ctx,program,buffer,position,sizeUniform,lightUniform;
if(gl){const shader=(k,s)=>{const x=gl.createShader(k);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x};program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;uniform float size;void main(){gl_Position=vec4(p,1.);gl_PointSize=size;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform float lit;void main(){vec2 uv=gl_PointCoord*2.-1.;float rr=dot(uv,uv);if(rr>1.)discard;vec3 n=vec3(uv.x,-uv.y,sqrt(1.-rr));float w=max(0.,dot(n,normalize(vec3(-.9,.45,.65)))),c=max(0.,dot(n,normalize(vec3(.9,.1,.6))));vec3 dual=vec3(.13)+w*vec3(.95,.52,.20)+c*vec3(.18,.48,.90);vec3 neutral=vec3(.25+.7*n.z);gl_FragColor=vec4(mix(neutral,dual,lit),1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));buffer=gl.createBuffer();position=gl.getAttribLocation(program,'p');sizeUniform=gl.getUniformLocation(program,'size');lightUniform=gl.getUniformLocation(program,'lit');gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);
}else ctx=canvas.getContext('2d');
function render(){if(!state.active)return;const start=performance.now();state.points=evaluate(state.frame,state.depth);const vertices=state.points.map(rotate),scale=state.zoom/200;
 if(gl){gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.035,.035,.035,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices.flatMap(p=>[p[0]*scale,p[1]*scale,-p[2]/500])),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,3,gl.FLOAT,false,12,0);gl.uniform1f(sizeUniform,state.size*canvas.width/400);gl.uniform1f(lightUniform,state.lit?1:0);gl.drawArrays(gl.POINTS,0,vertices.length);panel.dataset.glError=gl.getError();panel.dataset.depthTest=gl.isEnabled(gl.DEPTH_TEST);
 }else{ctx.fillStyle='#090909';ctx.fillRect(0,0,800,800);vertices.sort((a,b)=>a[2]-b[2]);const r=state.size;for(const p of vertices){const x=400+p[0]*scale*400,y=400-p[1]*scale*400;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(state.lit){const g=ctx.createLinearGradient(x-r,y,x+r,y);g.addColorStop(0,'#ddad79');g.addColorStop(.48,'#abb5b4');g.addColorStop(1,'#6f9fcd');ctx.fillStyle=g}else ctx.fillStyle='#c7cece';ctx.fill();}}
 const zs=state.points.map(p=>p[2]);panel.dataset.frame=state.frame;panel.dataset.time=clock[state.frame];panel.dataset.depthSpan=Math.max(...zs)-Math.min(...zs);panel.dataset.renderer=gl?'WebGL':'Canvas3D-fallback';panel.dataset.lit=state.lit;panel.dataset.yaw=state.yaw;panel.dataset.pitch=state.pitch;panel.dataset.renderCount=String(Number(panel.dataset.renderCount||0)+1);panel.dataset.renderMs=(performance.now()-start).toFixed(2);$('phaseStatus').textContent='20,000点 · '+(gl?'三维深度渲染':'软件三维预览');$('phaseTime').value=state.frame;$('phaseClock').textContent='源帧 '+state.frame+' · t='+clock[state.frame].toFixed(4);$('phaseState').textContent=state.playing?'播放中':'暂停';$('phasePlay').textContent=state.playing?'暂停':'播放';state.dirty=false;}
function seekReference(){if(!state.sourceReady)return;state.pending=true;$('phaseReference').contentWindow.postMessage({phaseSeek:true,frame:state.frame,before:clock[state.frame-1]},'*')}
function setFrame(n){state.frame=Math.max(1,Math.min(480,n));state.dirty=true;seekReference()}
$('phaseTime').oninput=e=>{state.playing=false;setFrame(Number(e.target.value))};$('phasePlay').onclick=()=>{state.playing=!state.playing;state.last=performance.now();state.dirty=true};$('phaseReset').onclick=()=>{state.playing=false;setFrame(1)};$('phaseView').onclick=()=>{state.yaw=state.pitch=0;state.zoom=1;state.dirty=true};$('phaseOrbit').onclick=()=>{state.yaw=.58;state.pitch=.22;state.zoom=1;state.dirty=true};$('phaseLight').onclick=()=>{state.lit=!state.lit;$('phaseLight').setAttribute('aria-pressed',String(state.lit));$('phaseLight').textContent=state.lit?'冷暖光':'中性光';state.dirty=true};$('phaseDepth').oninput=e=>{state.depth=Number(e.target.value)/100;$('phaseDepthValue').textContent=state.depth.toFixed(2);state.dirty=true};$('phaseSize').oninput=e=>{state.size=Number(e.target.value)/10;$('phaseSizeValue').textContent=state.size.toFixed(1);state.dirty=true};
canvas.addEventListener('pointerdown',e=>{state.drag=[e.clientX,e.clientY,state.yaw,state.pitch];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw=state.drag[2]+(e.clientX-state.drag[0])*.008;state.pitch=Math.max(-1.5,Math.min(1.5,state.drag[3]+(e.clientY-state.drag[1])*.008));state.dirty=true});for(const type of['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>state.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(3,state.zoom*Math.exp(-e.deltaY*.001)));state.dirty=true},{passive:false});
window.addEventListener('message',e=>{if(e.source!==$('phaseReference').contentWindow||!e.data?.phase06)return;if(e.data.ready){state.sourceReady=true;seekReference()}else if(e.data.frame===state.frame){state.pending=false;panel.dataset.referenceFrame=e.data.frame;}});
window.HaiyuSourceSpace={sourcePoint,evaluate,clock,setSource(p5,source){state.p5=p5;state.source=source;},setActive(value,frame=1){state.active=!!value;state.playing=false;if(!value)return;state.yaw=.58;state.pitch=.22;state.zoom=1;state.frame=frame;state.dirty=true;if(!$('phaseReference').srcdoc){$('phaseReference').srcdoc='<!doctype html><html><head><style>html,body{margin:0;background:#090909;overflow:hidden}canvas{display:block!important;width:100%!important;height:100%!important}</style></head><body><script src="'+state.p5+'"><\/script><script>'+state.source+'\nconst originalDraw=draw;setup=()=>{pixelDensity(1);noLoop()};draw=()=>{originalDraw();parent.postMessage({phase06:true,ready:true},"*")};window.addEventListener("message",e=>{if(e.source!==parent||!e.data.phaseSeek)return;t=e.data.before;originalDraw();document.body.dataset.frame=e.data.frame;document.body.dataset.time=t;parent.postMessage({phase06:true,frame:e.data.frame},"*")});<\/script></body></html>';}else seekReference();render();}};
function tick(now){if(state.active&&!document.hidden){if(state.playing&&!state.pending&&now-state.last>1000/30){state.last=now;setFrame(state.frame%480+1)}if(state.dirty)render()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
})();
