import {LifeEpoch} from './LifeEpoch.mjs';
import {CASES,STAGE_LABELS,defaults,checkControls} from './cases.mjs';
import {Viewer} from './viewer.mjs';
import {example} from '../structured/compiler.mjs';
import {validate,fingerprint} from '../src/core.mjs';
const $=id=>document.getElementById(id),fmt=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const life=new LifeEpoch(),saved=new Map(),downloadUrls=new Map();let viewer=null,contextsCreated=0,contextsReleased=0,lastRelease=null,returnView=null,returnCase=null;let config,worker,controller,caseEpoch=0,revision=0,requestId=0,bodyCache=null,paperModule=null,hotspot=null,state={ready:false,phase:'loading'},importedPattern=null,measurements=null,sourceDirty=false;
const communication={messages:0,positionBytes:0,handlerMs:0};
const params=()=>Object.fromEntries(config.params.map(([k])=>[k,+document.querySelector('[data-param="'+k+'"]').value]));
const flags=()=>({gravity:$('gravity').checked,obstacle:$('obstacle').checked,pull:$('pull').checked});
const send=(type,data={})=>life.active&&worker?.postMessage({type,requestId,...data});
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function clearError(){delete document.documentElement.dataset.error;state.error=null;}
function fail(error){state.error=error.message||String(error);state.running=false;state.phase='error';document.documentElement.dataset.error=state.error;message(state.error,true);updateButtons();}
async function fetchJSON(url,signal){let last;for(let i=0;i<3;i++){try{const r=await fetch(url,{signal});if(!r.ok)throw Error('HTTP '+r.status+' · '+url);return await r.json();}catch(e){if(signal.aborted)throw e;last=e;if(i<2)await new Promise(r=>setTimeout(r,250*(i+1)));}}throw last;}
function clearCurrent(){state.spec=null;state.record=null;state.regions=null;state.intersections=null;state.metrics=null;state.solverProfile=null;state.timings=null;state.activeWallMs=0;state.frozen=false;state.hadRun=false;state.running=false;hotspot=null;viewer.clear();$('paper').replaceChildren();$('regional').textContent='当前尺寸尚无最终应变报告';$('metrics').textContent='等待本轮材料';$('performance').textContent='等待本轮计算';$('save-state').disabled=$('svg').disabled=true;}
function invalidate({compileNow=false}={}){requestId++;revision++;clearError();send('pause');clearCurrent();state.phase='dirty';state.dirty=true;importedPattern=null;$('view-label').textContent='尺寸已修改 · 旧成衣已清除';$('view-note').textContent='先重新裁片，再启动本轮缝合';$('result-notice').textContent='当前改动尚未通过求解与穿插检查';$('progress').value=0;$('stage-status').textContent='等待新纸样';$('time-status').textContent='';message(config.kind==='structured'?'规范已修改，请重新编译':'旧结果已失效，请重新裁片');updateButtons();if(compileNow&&state.ready)preview();}
function inputPayload(){return{controls:params(),flags:flags(),example:$('example').value,source:config.kind==='structured'?readSource():undefined,imported:importedPattern,revision:revision||1};}
function readSource(){const s=$('source').value;if(s.length>200000)throw Error('规范超过 200 KB 小样限制');return JSON.parse(s);}
function preview(){if(!state.ready)return;try{clearError();sourceDirty=false;send('preview',inputPayload());message('正在校验当前纸样…');}catch(e){fail(e);}}
function requestCut(){if(!state.ready)return;try{clearError();requestId++;state.dirty=true;clearCurrent();state.phase='cutting';send('cut',inputPayload());$('view-label').textContent='从本轮尺寸生成平面材料';message('正在裁片与校验材料…');updateButtons();}catch(e){fail(e);}}
function updateButtons(){const valid=!!state.spec&&!state.dirty&&!state.error,small=config?.kind!=='garment';$('cut').disabled=!state.ready||state.phase==='cutting'||(config?.kind==='structured'&&(!valid||sourceDirty));$('run').disabled=!state.frozen||state.dirty||state.running||state.phase==='complete'||state.phase==='pausing'||(config?.kind==='structured'&&!state.hadRun);$('pause').disabled=!state.running;$('run').textContent=state.hadRun?'继续当前求解':'开始缝合';$('save').disabled=!state.ready||(!valid&&small);$('save-state').disabled=(!state.frozen&&state.phase!=='historical')||state.dirty||state.running;$('svg').disabled=!valid;$('release').disabled=!state.frozen||!state.metrics?.pins;$('detach').disabled=!state.frozen||!state.activeSeams?.length;updateStageButtons();}
function renderControls(values){$('parameters').replaceChildren();for(const[k,title,min,max,step,initial]of config.params){const label=document.createElement('label'),row=document.createElement('span'),text=document.createElement('span'),out=document.createElement('output'),input=document.createElement('input');text.textContent=title;input.type='range';input.min=min;input.max=max;input.step=step;input.value=values[k]??initial;input.dataset.param=k;input.id='param-'+k;label.htmlFor=input.id;out.id='out-'+k;out.textContent=input.value+' mm';row.append(text,out);label.append(row,input);input.addEventListener('input',()=>{out.textContent=input.value+' mm';invalidate({compileNow:config.kind==='swatch'});});$('parameters').append(label);} }
async function selectCase(id,{push=false}={}){if(!life.active||!viewer)return;if(!CASES[id])id='swatch';if(config?.id===id&&state.ready)return;if(config){saved.set(config.id,{controls:params(),source:$('source').value,example:$('example').value,flags:flags(),importedPaper:importedPattern?JSON.stringify(importedPattern):null});}const token=++caseEpoch,ticket=life.begin();requestId++;controller?.abort();controller=new AbortController();worker?.terminate();worker=null;config=CASES[id];document.title=config.title+' · 裁缝工作台';state={ready:false,phase:'loading',dirty:false,caseId:id};importedPattern=null;measurements=null;paperModule=null;sourceDirty=false;clearCurrent();clearError();const memory=saved.get(id),values=memory?.controls||defaults(config);renderControls(values);if(memory?.importedPaper){importedPattern=JSON.parse(memory.importedPaper);for(const el of $('parameters').querySelectorAll('input'))el.disabled=true;}document.querySelector('.wb-controls-scroll').scrollTop=0;$('case-select').value=id;$('control-title').textContent=config.title;$('case-hint').textContent=config.hint;$('example-row').hidden=config.kind!=='swatch';$('structured-editor').hidden=config.kind!=='structured';$('small-options').hidden=config.kind==='garment';$('obstacle-row').hidden=config.kind!=='swatch';$('baseline').hidden=config.kind!=='garment';$('measurements-visible').checked=false;$('measurements-visible').disabled=config.kind!=='garment';$('measurement-details').hidden=config.kind!=='garment';$('example').disabled=!!importedPattern;$('example').value=memory?.example||'straight';$('source').value=memory?.source||JSON.stringify(example(),null,2);for(const k of['gravity','obstacle','pull'])$(k).checked=memory?.flags?.[k]||false;$('case-source').href=config.source||'./'+config.dir+'/SOURCES.md';$('scope-note').textContent=config.kind==='garment'?'固定成人合成人体和标明的尺寸范围；完整成衣仍有局部应变和褶皱。真实缝份、厚度、包边、活动人体及物理穿脱未实现。':'原创小布片材料实验，未实现人体试穿、自碰撞或完整成衣验证。原材料与缝份参与网格，不生成衣壳。';$('stage-buttons').replaceChildren();$('stages').replaceChildren();$('performance').textContent='等待本轮计算';$('view-label').textContent='加载 '+config.title;$('view-note').textContent='只启用当前实验';$('stage-status').textContent='准备当前模式';$('progress').value=0;message('加载当前模式…');viewer.case(config);for(const b of document.querySelectorAll('[data-camera]'))b.setAttribute('aria-pressed',String(b.dataset.camera==='angle'));viewer.sphere.visible=config.kind==='swatch'&&$('obstacle').checked;showPaper(false);updateButtons();if(push){const u=new URL(location.href);u.searchParams.set('case',id);history.pushState({caseId:id},'',u);}document.documentElement.dataset.case=id;
 try{let data={};if(config.kind==='garment'){const prefix='./'+config.dir+'/assets/';const [base,record,audit,meta,body,paper]=await Promise.all([fetchJSON(prefix+'teacher-paper-base.json',controller.signal),fetchJSON(prefix+'verified-own-solve.json',controller.signal),fetchJSON(prefix+'baseline-audit.json',controller.signal),fetchJSON(prefix+'body-sdf-grid.json',controller.signal),bodyCache?Promise.resolve(bodyCache):fetchJSON('./garments-r04/assets/body-anny-adult.json',controller.signal),import('../'+config.dir+'/src/paper-view.mjs')]);if(token!==caseEpoch||!life.owns(ticket))return;bodyCache=body;paperModule=paper;state.base=base;state.baseline=record;state.audit=audit;state.body=body;viewer.setBody(body);const modified=config.params.some(([k,,,,,v])=>values[k]!==v);state.restoreModified=modified;if(!modified)showBaseline(false);else{state.dirty=true;$('view-label').textContent='已恢复此款尺寸 · 等待重算';}data={base,body,sdfMeta:meta,sdfUrl:new URL('../'+config.dir+'/assets/'+meta.transport.file,import.meta.url).href,kernelUrl:new URL('./physics/kernel.wasm',import.meta.url).href};}if(token!==caseEpoch||!life.owns(ticket))return;worker=new Worker(new URL('./worker.bundle.mjs',import.meta.url),{type:'module'});worker.onmessage=e=>{if(token===caseEpoch&&life.owns(ticket))onWorker(e.data);};worker.onerror=e=>{if(token===caseEpoch&&life.owns(ticket))fail(Error('计算线程：'+e.message));};send('init',{caseId:id,...data});}catch(e){if(token===caseEpoch&&life.owns(ticket)&&!controller.signal.aborted)fail(e);} }
function onWorker(d){if(!life.active||!viewer)return;const begin=performance.now();communication.messages++;if(d.type==='ready'){state.ready=true;state.backend=d.backend;state.timings=d.timings;if(config.kind!=='garment')preview();else if(state.restoreModified)requestCut();else{message('基准记录已载入；调整尺寸后重新裁片');updateButtons();}return;}if(d.type==='warning'){message(d.message);return;}if(d.requestId!==requestId)return;if(d.type==='error'){clearCurrent();fail(Error(d.message));return;}
 if(['preview','cut'].includes(d.type)){state={...state,spec:d.spec,metrics:d.metrics,timings:d.timings,report:d.report,summary:d.summary,topology:d.topology,activeSeams:d.activeSeams,completedStages:d.completedStages,gaps:d.gaps,frozen:d.frozen,phase:d.type==='cut'?'cut':'draft',dirty:false,error:null,running:false,hadRun:false};viewer.setGeometry(d.spec,d.positionsM,paperModule?.colors);communication.positionBytes+=d.positionsM.byteLength;setPaperOptions();showMetrics();renderStages();$('paper-totals').textContent=`${d.spec.panels.length} 片 · ${d.spec.seams.length} 组缝边 · ${d.metrics.vertexCount} 材料点 / ${d.metrics.triangleCount} 三角形`;$('view-label').textContent=d.frozen?'本轮新裁片 · 尚未缝合':'当前纸样 · 尚未冻结';$('view-note').textContent='显示直接来自二维材料';$('result-notice').textContent=config.kind==='garment'?`拓扑：${d.topology.boundaryLoops} 个边界环，非流形边 ${d.topology.nonManifoldEdges}；最终穿插尚待检查`:'保持原有接缝间隙与材料应变门槛';message(d.frozen?'真实材料已冻结，可以开始本轮缝合':'纸样校验通过，先冻结裁片');$('stage-status').textContent=d.frozen?'裁片已就绪':'纸样已校验';$('time-status').textContent='';$('progress').value=0;updateButtons();}
 else if(['progress','stage','paused','stepped','auditing'].includes(d.type)){state={...state,metrics:d.metrics,activeSeams:d.activeSeams,completedStages:d.completedStages,gaps:d.gaps,running:d.running,frozen:d.frozen,frame:d.frame,activeWallMs:d.activeWallMs,timings:d.timings,backend:d.backend};if(d.positionsM){viewer.update(d.positionsM);communication.positionBytes+=d.positionsM.byteLength;}state.hadRun=state.hadRun||d.frame>0;if(d.type==='paused')state.phase='paused';else if(d.type==='auditing')state.phase='auditing';else if(d.running)state.phase='running';showMetrics();renderStages(d.stage);const simulation=config.kind==='garment'?`${fmt(d.frame/60)} / ${fmt(d.totalFrames/60)} 模拟秒`:`${fmt(d.metrics.elapsed)} 模拟秒`;$('stage-status').textContent=(d.type==='auditing'?'最终几何检查':d.type==='paused'?'已暂停':STAGE_LABELS[d.stage]||'材料求解')+' · '+simulation;const wall=(d.activeWallMs||0)/1000,remaining=d.progress>0?wall*(1/d.progress-1):0;$('time-status').textContent=d.type==='auditing'?'检查穿插与应变':`已算 ${fmt(wall,0)} 秒${d.progress>.025&&d.progress<1?' · 预计余 '+fmt(remaining,0)+' 秒':''}`;if(d.progress!==null)$('progress').value=d.progress;if(config.kind!=='garment')smallNotice();else if(d.type==='paused')message('已暂停；尺寸与本轮材料保留');else message(d.type==='auditing'?'正在检查原 UV 应变与严格三角交叉':'本轮新纸样正在求解，中间态尚未验收');showPerformance();updateButtons();}
 else if(d.type==='done'){state={...state,record:d.record,spec:d.record.snapshot.spec,metrics:d.record.metrics,regions:d.regions,intersections:d.intersections,phase:'complete',running:false,frozen:true,hadRun:true,timings:d.timings,solverProfile:d.solverProfile,activeWallMs:d.activeWallMs};const p=toMetres(d.record.positionsMm);viewer.update(p);if(viewer.mode==='strain')viewer.display('strain',d.regions);showMetrics();showRegions();renderStages();$('progress').value=1;$('stage-status').textContent='本轮计算与最终检查完成';$('time-status').textContent='实际计算 '+fmt(d.activeWallMs/1000,0)+' 秒';$('view-label').textContent='本轮新纸样 · 求解完成';$('view-note').textContent='请检查前后视角和局部应变';const bad=d.intersections.bodyIntersectingFaceCount+d.intersections.selfStrictTriangleIntersectionCount+d.record.metrics.bodyInsideVertexCount;message(bad?'本轮存在穿插，保留诊断':'本轮严格交叉检查完成');$('result-notice').textContent=`面积 P95 应变 ${fmt(d.regions.all.p95AreaWeightedPercent)}%，局部最大 ${fmt(d.regions.all.maximumPercent)}%。${bad?'结果未通过交叉检查。':'人体面交叉和严格自交为 0；共面/连续碰撞与真实缝份仍未验证。'}`;showPerformance();updateButtons();}
 else if(d.type==='export')download('kaopu-'+config.id+'-result.json',d.record);
 if(d.stitchPairs||d.pinIds)viewer.fixtures?.(d.stitchPairs||[],d.pinIds||[]);document.documentElement.dataset.state=state.phase;communication.handlerMs+=performance.now()-begin;}
function toMetres(positions){const p=new Float32Array(positions.length*3);for(let i=0;i<positions.length;i++)for(let k=0;k<3;k++)p[i*3+k]=positions[i][k]/1000;return p;}
function showBaseline(cancel=true){if(!state.baseline)return;if(cancel){requestId++;send('pause');clearError();renderControls(defaults(config));}state={...state,spec:state.baseline.snapshot.spec,record:state.baseline,metrics:state.baseline.metrics,regions:state.audit.regions,intersections:state.audit.intersections,phase:'historical',running:false,frozen:false,dirty:false,hadRun:false};viewer.setGeometry(state.spec,toMetres(state.baseline.positionsMm),paperModule?.colors);setPaperOptions();showMetrics();showRegions();renderStages();$('paper-totals').textContent=`${state.spec.panels.length} 片 · ${state.spec.seams.length} 组缝边 · ${state.metrics.vertexCount} 材料点`;$('view-label').textContent='历史基准样例';$('view-note').textContent='历史记录，不计为本机刚完成的求解';$('stage-status').textContent='查看基准 · 调参后会清除旧成衣';$('time-status').textContent='';$('result-notice').textContent=`基准面积 P95 ${fmt(state.regions.all.p95AreaWeightedPercent)}%，局部最大 ${fmt(state.regions.all.maximumPercent)}%。本机重算请先重新裁片。`;$('progress').value=0;message('查看历史基准；重新裁片才能开始本轮计算');updateButtons();document.documentElement.dataset.state=state.phase;}
function renderStages(current){const s=config.kind==='garment'?[...(config.stages||state.spec?.source.assemblyExperiment||[]),'release']:state.spec?.stages.map(x=>x.id)||[];$('stages').replaceChildren(...s.map(id=>{const li=document.createElement('li');li.textContent=STAGE_LABELS[id]||id;li.classList.toggle('done',state.phase==='complete'||state.completedStages?.includes(id));li.classList.toggle('current',id===current);return li;}));}
function stageAllowed(s){if(!state.frozen||state.dirty||!state.metrics)return false;if(state.completedStages?.includes(s.id))return false;if(config.kind==='swatch')return true;if(s.requires.some(x=>!state.completedStages?.includes(x)))return false;const required=new Set(s.requires.flatMap(id=>state.spec.stages.find(x=>x.id===id)?.seams||[]));return(state.gaps||[]).filter(g=>required.has(g.id)).every(g=>g.active&&g.maxMm<=1.2)&&state.metrics.maxPrincipalStrain<=.05;}
function updateStageButtons(){if(config?.kind==='garment'){$('stage-buttons').replaceChildren();return;}const stages=state.spec?.stages.filter(s=>s.seams.length)||[];if($('stage-buttons').children.length!==stages.length||[...$('stage-buttons').children].some((x,i)=>x.dataset.stage!==stages[i]?.id)){$('stage-buttons').replaceChildren(...stages.map(s=>{const b=document.createElement('button');b.dataset.stage=s.id;b.textContent=(STAGE_LABELS[s.id]||s.id)+' · '+s.seams.join(' + ');b.onclick=()=>startStage(s.id);return b;}));}for(const b of $('stage-buttons').children)b.disabled=!stageAllowed(stages.find(s=>s.id===b.dataset.stage));}
function startStage(id){if(state.running&&state.completedStages?.includes(id))return;state.running=true;state.hadRun=true;state.phase='running';send('stage',{stageId:id});updateButtons();}
function smallNotice(){const m=state.metrics,active=(state.gaps||[]).filter(x=>x.active),gap=active.length?Math.max(...active.map(x=>x.maxMm)):null;if(!m.finite){send('pause');fail(Error('出现非有限值，已停止真实求解'));return;}if(m.maxPrincipalStrain>.05)message(`材料门槛失败：${fmt(m.maxPrincipalStrain*100)}% > 5%；后续工序保持阻止`,true);else if(!active.length)message('当前没有接缝约束；可以释放、轻拉检查分离');else message(`已激活 ${active.length} 条缝 · 最大间隙 ${fmt(gap,2)} mm${gap<=1.2?'，达到小样间隙门槛':''}`);$('result-notice').textContent='小样数值门槛不代表人体试穿或完整成衣通过';}
function showMetrics(){const m=state.metrics;if(!m){$('metrics').textContent='等待本轮检查';return;}const rows=config.kind==='garment'?[['接缝最大间隙',fmt(m.activeMaxGapMm,2)+' mm'],['人体最小间距',fmt(m.bodySignedDistanceMinMm,2)+' mm'],['工装支撑',m.temporarySupportCount??m.pins],['人体 / 严格自交',state.intersections?state.intersections.bodyIntersectingFaceCount+' / '+state.intersections.selfStrictTriangleIntersectionCount:'待最终检查']]:[['接缝间隙',fmt(m.maxSeamGapMm,2)+' mm'],['最大应变',fmt(m.maxPrincipalStrain*100)+'%'],['临时托持',m.pins],['已激活针点',m.activeStitches]];$('metrics').innerHTML=rows.map(([a,b])=>`<div><strong>${esc(b)}</strong><span>${esc(a)}</span></div>`).join('');}
function showRegions(){const r=state.regions;if(!r){$('regional').textContent='本轮完成后报告';return;}const labels={ordinary_interior:'普通内部',ordinary_seam_band:'普通缝口',free_edge_band:'自由边',planned_ease_band:'吃势缝口',dart_band:'省道'};$('regional').innerHTML='<div class="region-row"><span>原 UV 区域</span><span>最大</span><span>面积 P95</span></div>'+Object.entries(r.regions).map(([k,v])=>`<div class="region-row"><button data-hot="${k}" ${v?'':'disabled'}>${labels[k]}</button><span>${fmt(v?.maximumPercent)}%</span><span>${fmt(v?.p95AreaWeightedPercent)}%</span></div>`).join('');for(const b of $('regional').querySelectorAll('button'))b.onclick=()=>{hotspot=r.regions[b.dataset.hot].worst[0];const seam=state.spec.seams.find(s=>[s.a,s.b].some(e=>e.panelId===hotspot.panelId));if(seam)$('seam-select').value=seam.id;showPaper(true);renderPaper();$('seam-detail').textContent=`热点 ${hotspot.panelId} · 三角形 ${hotspot.triangle} · 材料 (${hotspot.uvCentroidMm.map(x=>fmt(x)).join(', ')}) mm · ${fmt(hotspot.strain*100)}%`;};}
function showPerformance(){const t=state.timings||{},p=state.solverProfile||{},v=viewer.profile;const rows=[['当前计算',state.backend||'—'],['物理步进',fmt(t.solveMs/1000,2)+' s'],['距离场读取 / 解压',fmt(t.decodeMs/1000,3)+' s'],['指标采样',fmt(t.metricsMs/1000,3)+' s'],['最终应变 / 自交',fmt(((t.regionalAuditMs||0)+(t.intersectionAuditMs||0))/1000,3)+' s'],['绘制提交 CPU',fmt(v.renderMs/1000,3)+' s'],['网格更新 CPU',fmt(v.uploadMs/1000,3)+' s'],['消息处理（含更新）',fmt(communication.handlerMs/1000,3)+' s'],['显示数据传输',fmt(communication.positionBytes/1048576,2)+' MiB']];if(p.distanceMs!==undefined)rows.push(['距离约束 / 主应变',fmt(p.distanceMs/1000,2)+' / '+fmt(p.strainMs/1000,2)+' s'],['人体点 / 面采样',fmt(p.bodyVertexMs/1000,2)+' / '+fmt(p.bodySurfaceMs/1000,2)+' s']);$('performance').innerHTML='<dl>'+rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')+'</dl><p>绘制项是 CPU 提交耗时，不是 GPU 计时；只统计当前页面的实际工作。</p>';}
function genericSVG(spec){const panels=$('paper-focus').checked?spec.panels.filter(p=>{const s=spec.seams.find(s=>s.id===$('seam-select').value);return !s||s.a.panelId===p.id||s.b.panelId===p.id;}):spec.panels;let x=20,h=0,content='';for(const p of panels){const xs=p.uvMm.map(q=>q[0]),ys=p.uvMm.map(q=>q[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),color={A:'#d9b978',B:'#94a6d6',C:'#83bba7'}[p.id]||'#b6c5c3',points=ids=>ids.map(i=>p.uvMm[i].join(',')).join(' ');content+=`<g transform="translate(${x-xmin} ${35-ymin})"><polygon points="${points(p.boundary)}" fill="${color}" fill-opacity=".5" stroke="#4a6067"/><text x="${xmin}" y="${ymin-10}" fill="#243840" font-size="10">${esc(p.id)}</text>`;for(const[k,ids]of Object.entries(p.edges)){content+=`<polyline points="${points(ids)}" fill="none" stroke="#4d6655" stroke-dasharray="3 2"/>`;for(const mark of p.edgeNotches?.[k]||[]){const i=Math.round(mark.t*(ids.length-1)),q=p.uvMm[ids[i]];content+=`<circle cx="${q[0]}" cy="${q[1]}" r="2" fill="#724830"/><text x="${q[0]+3}" y="${q[1]-3}" font-size="6" fill="#243840">${esc(mark.id)}</text>`;}}content+='</g>';x+=xmax-xmin+35;h=Math.max(h,ymax-ymin);}return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${x} ${h+85}" width="${x}mm" height="${h+85}mm">${content}<text x="20" y="${h+70}" fill="#243840" font-size="8">原始毫米材料 · 实线裁边，虚线净缝边；缝份材料真实参与网格</text></svg>`;}
function svg(download=false){if(!state.spec)return'';if(!paperModule)return genericSVG(state.spec);let s=state.spec;if(!download&&$('paper-focus').checked){const seam=s.seams.find(x=>x.id===$('seam-select').value);if(seam)s={...s,panels:s.panels.filter(p=>p.id===seam.a.panelId||p.id===seam.b.panelId)};}return paperModule.paperSVG(s,{selectedSeamId:$('seam-select').value,hotspot,download});}
function setPaperOptions(){$('seam-select').replaceChildren(...(state.spec?.seams||[]).map(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=`${s.id} · ${paperModule?.names?.[s.a.panelId]||s.a.panelId} / ${paperModule?.names?.[s.b.panelId]||s.b.panelId}`;return o;}));renderPaper();}
function renderPaper(){$('paper').innerHTML=svg();const s=state.spec?.seams.find(x=>x.id===$('seam-select').value);if(!s){$('seam-detail').textContent='';return;}const len=e=>{const p=state.spec.panels.find(p=>p.id===e.panelId),ids=p.edges[e.edge];return ids.slice(1).reduce((n,id,j)=>n+Math.hypot(...p.uvMm[id].map((x,k)=>x-p.uvMm[ids[j]][k])),0);};$('seam-detail').textContent=`${s.a.panelId}.${s.a.edge} ${s.a.reverse?'反向':'正向'} ↔ ${s.b.panelId}.${s.b.edge} ${s.b.reverse?'反向':'正向'}；${fmt(len(s.a))} / ${fmt(len(s.b))} mm，声明吃势 ${fmt(s.easeMm,2)} mm`;}
function showPaper(on){$('paper-view').hidden=!on;$('scene').hidden=on;$('show-paper').setAttribute('aria-pressed',String(on));$('show-cloth').setAttribute('aria-pressed',String(!on));if(on)renderPaper();else{viewer.resize();viewer.dirty=true;}}
async function loadMeasurements(){if(!life.active||!config||!viewer||config.kind!=='garment')return;const token=caseEpoch;if(!measurements){$('measurements').textContent='加载量体证据…';try{const loaded=await fetchJSON('./'+(config.id==='shorts'?'garments-r03':'garments-r04')+'/assets/measurements.json',controller.signal);if(token!==caseEpoch)return;measurements=loaded;}catch(e){if(token===caseEpoch)$('measurements').textContent=e.message;return;}}if(token!==caseEpoch)return;viewer.measurements(measurements,$('measurements-visible').checked);const m=measurements,t=m.teacher?.body,rows=m.bust?[['胸围软尺线',fmt(m.bust.tapeCircumferenceMm)+' mm','Y='+fmt(m.bust.heightMm)+' mm'],['肩宽',fmt(t.shoulder_w*10)+' mm','肩点三维距离'],['袖窿深度',fmt(t.armscye_depth*10)+' mm','肩点至后腋下点直线距离'],['肩斜',fmt(t.shoulder_incl,2)+'°','颈侧至肩点'],['人体高度',fmt(t.height*10)+' mm','公开成人合成模型']]:[['腰围软尺线',fmt(m.waist.circumferenceMm)+' mm','Y='+fmt(m.waist.heightMm)+' mm'],['臀峰软尺线',fmt(m.hip.circumferenceMm)+' mm','Y='+fmt(m.hip.heightMm)+' mm；皮肤截面 '+fmt(m.hip.skinCircumferenceMm)+' mm'],['会阴高度',fmt(m.crotchMergeHeightMm)+' mm','地面 Y=0'],['人体高度',fmt(m.heightMm)+' mm','公开成人合成模型']];$('measurements').innerHTML=rows.map(([a,b,c])=>`<div class="reading">${esc(a)}<strong>${esc(b)}</strong><small>${esc(c)}</small></div>`).join('')+'<p>材料 200 g/m²，各向同性；伸长柔度 1e−7 m/N，弯曲距离近似柔度 20 m/N。未实测标定。</p>';}
function download(name,data,mime='application/json'){const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();const timer=setTimeout(()=>{URL.revokeObjectURL(url);downloadUrls.delete(url);},1000);downloadUrls.set(url,timer);}
$('case-select').onchange=()=>selectCase($('case-select').value,{push:true});window.addEventListener('popstate',()=>selectCase(new URL(location.href).searchParams.get('case')||'swatch'));
$('cut').onclick=requestCut;$('run').onclick=()=>{if(!state.frozen||state.dirty||state.running)return;if(config.kind==='swatch'&&!state.hadRun)startStage('join');else{state.running=true;state.hadRun=true;state.phase='running';send('run');updateButtons();}$('view-label').textContent='本轮新纸样 · 实时求解中';$('view-note').textContent='持续显示当前材料，中间态未验收';};$('pause').onclick=()=>{state.running=false;state.phase='pausing';message('正在暂停当前计算…');send('pause');updateButtons();};$('release').onclick=()=>send('release');$('detach').onclick=()=>send('detach');
$('baseline').onclick=()=>showBaseline();$('reset').onclick=()=>{saved.delete(config.id);const id=config.id;config=null;selectCase(id);};$('example').onchange=()=>invalidate({compileNow:true});for(const k of['gravity','obstacle','pull'])$(k).onchange=()=>{viewer.sphere.visible=config.kind==='swatch'&&$('obstacle').checked;viewer.dirty=true;send('flags',{flags:flags()});};$('source').oninput=()=>{sourceDirty=true;invalidate();};$('compile').onclick=()=>preview();$('restore-source').onclick=()=>{$('source').value=JSON.stringify(example(),null,2);invalidate();preview();};
function editSource(fn){try{const s=readSource();fn(s);s.revision++;$('source').value=JSON.stringify(s,null,2);invalidate();preview();}catch(e){fail(e);}}$('deeper').onclick=()=>editSource(s=>{const a=s.panels.find(p=>p.id==='A'),b=s.panels.find(p=>p.id==='B');if(!a||!b)throw Error('预设需要 A、B 两片');a.right.control[0]-=10;b.left.control[0]-=10;});$('remove-c').onclick=()=>editSource(s=>{s.panels=s.panels.filter(p=>p.id!=='C');const removed=new Set(s.stitches.filter(x=>[x.a.panelId,x.b.panelId].includes('C')).map(x=>x.id));s.stitches=s.stitches.filter(x=>!removed.has(x.id));s.stages=s.stages.map(x=>({...x,seams:x.seams.filter(id=>!removed.has(id))})).filter(x=>x.id==='cut'||x.seams.length);const ids=new Set(s.stages.map(x=>x.id));s.stages.forEach(x=>x.requires=x.requires.filter(id=>ids.has(id)));});$('bad-direction').onclick=()=>editSource(s=>s.stitches[0].b.reverse=!s.stitches[0].b.reverse);
$('display').onchange=()=>viewer.display($('display').value,state.phase==='complete'?state.regions:null);for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>{viewer.cameraView(b.dataset.camera);for(const other of document.querySelectorAll('[data-camera]'))other.setAttribute('aria-pressed',String(other===b));};$('show-paper').onclick=$('open-paper').onclick=()=>showPaper(true);$('show-cloth').onclick=()=>showPaper(false);$('paper-focus').onchange=renderPaper;$('seam-select').onchange=()=>{hotspot=null;renderPaper();};$('measurements-visible').onchange=loadMeasurements;$('measurement-details').ontoggle=()=>{if($('measurement-details').open)loadMeasurements();};
$('save').onclick=()=>{try{if(config.kind==='garment')download('kaopu-'+config.id+'-recipe.json',{schema:config.schema,sourcePaperFingerprint:fingerprint(state.base),bodyId:state.body.id,bodyModelSha256:state.body.source.modelFileSha256,controls:checkControls(config,params()),solver:{program:'garment-small-step-r1',substeps:12,iterations:6,stageFrames:360,releaseFrames:480,originalUVPreserved:true},note:'Load rebuilds flat material. No solved garment is used for new parameters.'});else download('kaopu-'+config.id+'-paper.json',config.kind==='structured'?readSource():state.spec);}catch(e){fail(e);}};
$('save-state').onclick=()=>{if(state.record&&['complete','historical'].includes(state.phase))download('kaopu-'+config.id+'-result.json',{...state.record,displaySource:state.phase});else send('export');};$('svg').onclick=()=>{const focus=$('paper-focus').checked;$('paper-focus').checked=false;download('kaopu-'+config.id+'-paper-mm.svg',svg(true),'image/svg+xml');$('paper-focus').checked=focus;};
$('load').onchange=async e=>{const file=e.target.files[0];let pageTicket=life.value;if(!file||!life.active)return;try{if(file.size>1500000)throw Error('文件超过 1.5 MB 限制');const text=await file.text();if(!life.owns(pageTicket))return;const data=JSON.parse(text),c=Object.values(CASES).find(c=>c.schema===data.schema);if(c){if(file.size>64000)throw Error('配方超过 64 KB');checkControls(c,data.controls);if(config.id!==c.id){const next=selectCase(c.id,{push:true});pageTicket=life.value;await next;}if(!life.owns(pageTicket))return;const token=caseEpoch,deadline=performance.now()+30000;while(!state.ready&&!state.error&&token===caseEpoch&&performance.now()<deadline)await new Promise(r=>setTimeout(r,20));if(token!==caseEpoch||!state.ready)throw Error('当前案例已切换或尚未就绪');if(data.sourcePaperFingerprint!==fingerprint(state.base)||data.bodyId!==state.body.id||data.bodyModelSha256!==state.body.source.modelFileSha256)throw Error('配方纸样或人体版本不匹配');renderControls(data.controls);invalidate();requestCut();}else if(config.kind==='structured'){if(file.size>200000)throw Error('规范超过 200 KB');$('source').value=JSON.stringify(data,null,2);invalidate();preview();}else if(config.kind==='swatch'){validate(data);invalidate();importedPattern=data;for(const el of $('parameters').querySelectorAll('input'))el.disabled=true;$('example').disabled=true;preview();}else throw Error('请选择原布片模式导入该纸样格式');}catch(err){if(life.owns(pageTicket))message('读取失败：'+err.message,true);}finally{if(life.owns(pageTicket))e.target.value='';}};
window.__TAILOR_UNIFIED_QA__={getState:()=>({caseId:config?.id,ready:state.ready,phase:state.phase,dirty:state.dirty,running:state.running,controls:config?params():{},specFingerprint:state.spec?fingerprint(state.spec):null,panelCount:state.spec?.panels.length,vertexCount:state.metrics?.vertexCount,metrics:state.metrics,intersections:state.intersections,backend:state.backend,activeWorkerCount:worker?1:0,rendererCount:viewer?1:0,garmentMeshCount:viewer?.meshes.length||0,geometries:viewer?.renderer.info.memory.geometries||0,active:life.active,generation:life.value,contextsCreated,contextsReleased,rafScheduled:!!viewer?.rafId,bodyCached:!!bodyCache,lastRelease,renderPrecision:'float32 metres only; solver/export f64',error:state.error}),getSpec:()=>structuredClone(state.spec),getRecord:()=>structuredClone(state.record),getPositions:()=>viewer?.positions()||[],getProfile:()=>({worker:state.timings,solver:state.solverProfile,viewer:viewer?.profile,communication}),step:n=>send('step',{count:n}),renderCount:()=>viewer?.profile.renderCount||0,selectCase:id=>selectCase(id,{push:true})};

function releasePage(event){
 if(!life.active)return;
 returnCase=config?.id||new URL(location.href).searchParams.get('case')||'swatch';
 if(config)saved.set(config.id,{controls:params(),source:$('source').value,example:$('example').value,flags:flags(),importedPaper:importedPattern?JSON.stringify(importedPattern):null});
 returnView=viewer?.snapshotView();life.hide();caseEpoch++;requestId++;controller?.abort();controller=null;
 if(worker){worker.onmessage=null;worker.onerror=null;worker.terminate();worker=null;}
 for(const[url,timer]of downloadUrls){clearTimeout(timer);URL.revokeObjectURL(url);}downloadUrls.clear();
 const report=viewer?.dispose();if(viewer)contextsReleased++;viewer=null;
 const canvas=$('scene');canvas.replaceWith(canvas.cloneNode(false));
 bodyCache=paperModule=hotspot=importedPattern=measurements=config=null;sourceDirty=false;
 state={ready:false,phase:'inactive',dirty:false,running:false};
 for(const id of ['paper','regional','stage-buttons','stages','seam-select','measurements'])$(id).replaceChildren();
 $('load').value='';$('view-label').textContent='页面已释放';$('view-note').textContent='返回后从当前尺寸重新载入';
 lastRelease={...report,persisted:!!event?.persisted,activeWorkerCount:0,rendererCount:0,bodyCached:false};
 window.dispatchEvent(new CustomEvent('tailor-lifecycle',{detail:{kind:'released',generation:life.value,...lastRelease}}));
}
function restorePage(event){
 life.show();if(viewer)return;
 viewer=new Viewer($('scene'),$('viewport'));contextsCreated++;
 const id=returnCase||new URL(location.href).searchParams.get('case')||'swatch',view=returnView;
 const pending=selectCase(id),ticket=life.value;
 pending.then(()=>{if(life.owns(ticket)&&viewer&&view){viewer.restoreView(view);$('display').value=view.mode;}});
 window.dispatchEvent(new CustomEvent('tailor-lifecycle',{detail:{kind:'started',persisted:!!event?.persisted,generation:life.value,contextsCreated,contextsReleased}}));
}
window.addEventListener('pagehide',releasePage);
window.addEventListener('pageshow',restorePage);
restorePage();
