import {createExample,validate,cut,ClothLab,directedEdge} from '../src/core.mjs';
import {example,compile} from '../structured/compiler.mjs';
import * as shorts from '../garments-r03/src/paper-program.mjs';
import * as vest from '../garments-r04/src/paper-program.mjs';
import * as shirt from '../garments-r05/src/paper-program.mjs';
import {BodySDF,GarmentLab as SlowLab} from '../garments-r04/src/solver.mjs';
import {GarmentLab as FastLab,configureWasm} from './physics/fast-solver.mjs';
import {decodeSDF} from '../garments-r04/src/sdf-transport.mjs';
import {regionalStrain,topology} from '../garments-r04/src/diagnostics.mjs';
import {prepareBodyAudit,strictIntersectionAudit} from '../garments-r04/src/intersection-audit.mjs';
import {CASES,checkControls} from './cases.mjs';
let config,base,bodyAudit,sdf,lab,spec,built,requestId=0,epoch=0,running=false,frozen=false,stageIndex=0,stageFrame=0,stages=[],totalFrames=0,lastEmit=0,backend='JS reference',activeWallMs=0,runStarted=0;
const timings={decodeMs:0,bodyBVHMs:0,compileMs:0,solveMs:0,metricsMs:0,packetMs:0,regionalAuditMs:0,intersectionAuditMs:0};
const emit=(type,data={},transfer=[])=>postMessage({type,requestId,...data},transfer);
const measure=(key,fn)=>{const start=performance.now(),out=fn();timings[key]+=performance.now()-start;return out;};
async function asset(url,binary=false){let last;for(let i=0;i<3;i++){try{const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status+' · '+url);return binary?await r.arrayBuffer():await r.json();}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,250*(i+1)));}}throw last;}
function gaps(){return spec.seams.map(s=>{const a=directedEdge(spec,s.a),b=directedEdge(spec,s.b),oa=lab.offsets.get(a.panel.id),ob=lab.offsets.get(b.panel.id);return{id:s.id,active:lab.active.has(s.id),maxMm:Math.max(...a.ids.map((v,i)=>Math.hypot(...lab.positions[oa+v].map((x,k)=>x-lab.positions[ob+b.ids[i]][k]))*1000))};});}
function packet(type,extra={}){const begin=performance.now(),positionsM=new Float32Array(lab.positions.length*3);for(let i=0;i<lab.positions.length;i++)positionsM.set(lab.positions[i],i*3);timings.packetMs+=performance.now()-begin;const metrics=measure('metricsMs',()=>lab.metrics());emit(type,{positionsM,metrics,frame:lab.frameCount??Math.round(lab.elapsed*60),stage:stages[stageIndex]||'complete',frozen,running,backend,completedStages:[...lab.completed],activeSeams:[...lab.active],gaps:config.kind==='garment'?undefined:gaps(),stitchPairs:config.kind==='garment'?undefined:lab.seamConstraints.map(c=>[c.a,c.b]),pinIds:config.kind==='garment'?undefined:[...lab.pins.keys()],progress:totalFrames?(lab.frameCount/totalFrames):null,totalFrames,activeWallMs:elapsedWall(),timings:{...timings},...extra},[positionsM.buffer]);}
function elapsedWall(){return activeWallMs+(running?performance.now()-runStarted:0);}
function stop(){if(running)activeWallMs=elapsedWall();epoch++;running=false;}
function makePaper(data){checkControls(config,data.controls||{});if(config.kind==='swatch'){const mode=data.example||'straight';spec=data.imported||createExample({width:data.controls.width,height:data.controls.height,ease:mode==='ease'?.08:0,invalid:{direction:'direction',easeError:'ease',reference:'reference'}[mode]||'none',revision:data.revision||1});validate(spec);built=null;}
 else if(config.kind==='structured'){built=compile(data.source||example());spec=built.spec;}
 else{const program={shorts,sleeveless:vest,shortsleeve:shirt}[config.id],graded=program.gradePaper(base,data.controls);spec=program.meshPaper?program.meshPaper(graded):graded;built={summary:program.paperSummary(spec)};}return spec;}
function construct(data,freeze){stop();requestId=data.requestId;lab=null;frozen=false;timings.compileMs=0;spec=measure('compileMs',()=>makePaper(data));lab=config.kind==='garment'?new (backend==='f64 kernel'?FastLab:SlowLab)(spec,sdf,{substeps:12,iterations:6}):new ClothLab(cut(spec));if(config.kind==='garment'){lab.orientationGuides=false;lab.selfCollisionEnabled=false;lab.stitchEqualityElimination=true;lab.strainGuard=true;stages=[...(config.stages||spec.source.assemblyExperiment),'release'];totalFrames=(stages.length-1)*360+480;}else{lab.gravity=!!data.flags?.gravity;lab.obstacle=!!data.flags?.obstacle;lab.pull=!!data.flags?.pull;stages=[];totalFrames=0;}frozen=freeze;stageIndex=stageFrame=activeWallMs=0;timings.solveMs=timings.metricsMs=timings.packetMs=timings.regionalAuditMs=timings.intersectionAuditMs=0;packet(freeze?'cut':'preview',{spec,report:built?.report,summary:built?.summary,topology:config.kind==='garment'?topology(spec):null});}
function prerequisites(stage){const m=lab.metrics();if(stage.requires.some(s=>!lab.completed.has(s)))return false;const required=new Set(stage.requires.flatMap(id=>spec.stages.find(x=>x.id===id)?.seams||[]));return gaps().filter(s=>required.has(s.id)).every(s=>s.active&&s.maxMm<=1.2)&&m.maxPrincipalStrain<=.05;}
function finish(){activeWallMs=elapsedWall();running=false;const auditStart=performance.now();packet('auditing');const record=lab.export();record.positionsMm=lab.positions.map(p=>Array.from(p,x=>x*1000));const regions=measure('regionalAuditMs',()=>regionalStrain(spec,record.positionsMm)),intersections=measure('intersectionAuditMs',()=>strictIntersectionAudit(spec,record.positionsMm,record.materialToSolverGroup,bodyAudit));activeWallMs+=performance.now()-auditStart;emit('done',{record,regions,intersections,backend,timings,solverProfile:lab.profile,activeWallMs,frozen:true});}
function tick(token){if(token!==epoch||!running)return;try{const begin=performance.now(),budget=config.kind==='garment'?22:10;let steps=0;
 do{if(config.kind==='garment'&&stageFrame===0){if(stages[stageIndex]==='release'){lab.releasePins();lab.setGravity(1);}else lab.activate(stages[stageIndex]);}measure('solveMs',()=>lab.step());steps++;if(config.kind==='garment'){stageFrame++;const required=stages[stageIndex]==='release'?480:360;if(stageFrame===required){packet('stage',{completedStage:stages[stageIndex]});stageFrame=0;stageIndex++;if(stageIndex===stages.length){finish();return;}}}}while(steps<(config.kind==='garment'?8:1)&&performance.now()-begin<budget);
 if(performance.now()-lastEmit>=100){packet('progress');lastEmit=performance.now();}setTimeout(()=>tick(token),config.kind==='garment'?0:16);
 }catch(e){stop();emit('error',{message:e.message});}}
function run(){if(!lab||!frozen)throw Error('先冻结本轮真实裁片');if(config.kind==='garment'&&stageIndex>=stages.length)throw Error('本轮已完成；请重新裁片再算');if(!running)runStarted=performance.now();running=true;tick(++epoch);}
self.onmessage=async({data:d})=>{try{if(d.type==='init'){requestId=d.requestId;config=CASES[d.caseId];base=d.base;if(config.kind==='garment'){const t=performance.now(),raw=await asset(d.sdfUrl,true),buffer=await decodeSDF(new Blob([raw]),d.sdfMeta);timings.decodeMs=performance.now()-t;sdf=new BodySDF(d.sdfMeta,new Int16Array(buffer));bodyAudit=measure('bodyBVHMs',()=>prepareBodyAudit(d.body));try{configureWasm(await asset(d.kernelUrl,true));backend='f64 kernel';}catch(e){backend='JS reference';emit('warning',{message:'加速内核未就绪，使用相同数学的兼容计算：'+e.message});}}emit('ready',{backend,timings});}
 else if(d.type==='preview')construct(d,false);else if(d.type==='cut')construct(d,true);
 else if(d.type==='run')run();else if(d.type==='pause'){stop();if(lab)packet('paused');}
 else if(d.type==='stage'){if(!lab||!frozen)throw Error('先冻结材料');const stage=spec.stages.find(s=>s.id===d.stageId);if(config.kind==='structured'&&!prerequisites(stage))throw Error('前置曲缝尚未通过原有间隙/应变门槛');lab.activate(stage.id,spec);lab.seamDetached=false;run();}
 else if(d.type==='flags'){if(lab){Object.assign(lab,{gravity:!!d.flags.gravity,obstacle:!!d.flags.obstacle,pull:!!d.flags.pull});if(frozen)run();else packet('preview');}}
 else if(d.type==='release'){if(lab){lab.releasePins();run();}}else if(d.type==='detach'){if(lab){lab.detach();run();}}
 else if(d.type==='export'){if(!lab||!frozen)throw Error('没有已冻结结果');const record=lab.export();record.positionsMm=lab.positions.map(p=>Array.from(p,x=>x*1000));emit('export',{record,timings});}
 else if(d.type==='step'){stop();for(let i=0;i<d.count;i++)lab.step();packet('stepped');}
 }catch(e){stop();emit('error',{message:e.message});}};
