const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),{chromium}=require('playwright');
const commit=process.env.PUBLIC_COMMIT,out=commit?'qa-face-et12/public':'qa-face-et12/source';fs.mkdirSync(out,{recursive:true});const root=commit?'https://raw.githubusercontent.com/haihao0307/guilin-dem-pipeline/'+commit+'/kaopu-unified-human-workbench/face-transfer/':null,url=commit?'https://htmlpreview.github.io/?'+root+'preview.html':'http://127.0.0.1:8765/kaopu-unified-human-workbench/face-transfer/preview.html';
const report={version:'ET12-F1',commit,url,checks:[],presets:[],parameters:[],layers:[],errors:[],mobileRealDevice:false};let browser,page;
function check(name,pass,detail){report.checks.push({name,pass:!!pass,detail});assert(pass,name+': '+JSON.stringify(detail));}
async function capture(name){await page.screenshot({path:out+'/'+name+'.png'});}
async function pixel(){const b=await page.locator('#canvas').screenshot();return crypto.createHash('sha256').update(b).digest('hex');}
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Shader|WebGLProgram|GL_INVALID/.test(m.text()))report.errors.push(m.text());});
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.fullFaceTransfer?.report()?.face&&fullCommonWorkbench.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:300000});await page.evaluate(()=>fullFaceTransfer.ready());await page.evaluate(()=>fullFaceTransfer.view());
 await page.evaluate(()=>{window.__F_HASH__=a=>{let h=2166136261;for(const v of new Uint8Array(a.buffer,a.byteOffset,a.byteLength))h=Math.imul(h^v,16777619);return(h>>>0).toString(16);};});
 report.initial=await page.evaluate(()=>({report:fullFaceTransfer.report(),capture:fullFaceTransfer.capture(),diagnostics:fullCommonWorkbench.diagnostics()}));
 check('correct original character system and 36 current / 36 legacy presets',await page.evaluate(()=>fullCommonWorkbench.presets().length===36&&fullCommonWorkbench.allPresets().length===72));
 const fields=report.initial.capture.face.fields;check('full face masks cover multiple facial organs, not just canthus',fields.counts.face>2000&&fields.counts.lips>50&&fields.counts.nose>100&&fields.counts.forehead>100&&fields.counts.cheek>100&&fields.counts.thin>100,fields);check('body has zero face-texture mask',fields.bodyWeight===0);check('source frequency atlas actually loaded',report.initial.report.skin.ready&&!report.initial.report.skin.errors.length);
 await capture('01-full-face');await page.click('#faceGray');await capture('02-gray-structure');await page.focus('#faceBefore');await page.keyboard.down('Space');await capture('03-before-structure');check('held face layer disabled without replacing native skin',await page.evaluate(()=>!fullFaceTransfer.capture().faceSettings.enabled));await page.keyboard.up('Space');check('release restores full-face layer',await page.evaluate(()=>fullFaceTransfer.capture().faceSettings.enabled));await page.click('#faceBeauty');
 const fieldHash=await page.evaluate(()=>JSON.stringify(fullFaceTransfer.fieldArrays()));const ids=await page.evaluate(()=>fullCommonWorkbench.presets().map(p=>p.id));
 for(let i=0;i<ids.length;i++){
  await page.evaluate(id=>fullCommonWorkbench.applyPreset(id),ids[i]);const row=await page.evaluate(()=>{const p=fullCommonWorkbench.positions(),old=fullFaceTransfer.nativeBeforeFace(),native=eyeTransferredHuman.nativePositions(),B=fullCommonWorkbench.diagnostics().bodyVertices;let bodyError=0,faceDelta=0;for(let k=0;k<p.length;k++){if(k<B*3)bodyError=Math.max(bodyError,Math.abs(p[k]-native[k]));else faceDelta=Math.max(faceDelta,Math.abs(p[k]-old[k]));}return{id:fullCommonWorkbench.presetRecord().presetId,bodyError,faceDelta,finite:p.every(Number.isFinite),hash:__F_HASH__(p),report:fullFaceTransfer.capture().face,fixed:fullCommonWorkbench.diagnostics().fixedPositionBuffer&&fullCommonWorkbench.diagnostics().fixedIndexBuffer};});report.presets.push(row);
  check(ids[i]+' original preset / fixed buffers',row.id===ids[i]&&row.fixed&&row.finite);check(ids[i]+' original body and active full-face composition',row.bodyError===0&&row.faceDelta>1e-8&&row.faceDelta<.001,{bodyError:row.bodyError,faceDelta:row.faceDelta});
  if([0,12,20,27,35].includes(i)){await page.evaluate(()=>fullFaceTransfer.view());await capture('preset-'+i);}
 }
 check('36 distinct generated characters remain',new Set(report.presets.map(r=>r.hash)).size===36);check('no remapping / swimming of rest attributes across presets',await page.evaluate(()=>JSON.stringify(fullFaceTransfer.fieldArrays()))===fieldHash);
 await page.evaluate(()=>fullCommonWorkbench.applyPreset('r02-adult-male-sturdy'));await page.evaluate(()=>fullFaceTransfer.view());
 const cases=[['gnm.identity:0',.8],['gnm.expression:0',.65],['gnm.rotation:4',.2],['gnm.rotation:7',.15],['anny.localChanges:head-scale-horiz-incr',.3],['anny.localChanges:l-eye-corner1-up',.25],['anny.phenotypes:weight',.35],['anny.phenotypes:height',.7]];
 for(const[key,value]of cases){const row=await page.evaluate(({key,value})=>{const saved=fullCommonWorkbench.archive(),before=fullCommonWorkbench.positions();fullCommonWorkbench.set(key,value);const p=fullCommonWorkbench.positions(),face=fullFaceTransfer.capture().face;const changed=__F_HASH__(p)!==__F_HASH__(before),finite=p.every(Number.isFinite);fullCommonWorkbench.restore(saved);return{key,changed,finite,restored:__F_HASH__(fullCommonWorkbench.positions())===__F_HASH__(before),face};},{key,value});report.parameters.push(row);check(key+' controls composed face and restores',row.changed&&row.finite&&row.restored,row);}
 const uuid=await page.evaluate(()=>fullFaceTransfer.capture().materialUUID);const nativeSkin=await page.evaluate(()=>fullCommonWorkbench.archive());const basePixels=await pixel();await page.evaluate(()=>fullCommonWorkbench.setSkin({tone:.3,lipMix:.9,lipColor:'#854f58',roughness:.74}));const changedPixels=await pixel();check('original skin drawing controls still change final face',changedPixels!==basePixels);check('same original skin material instance is extended',await page.evaluate(()=>fullFaceTransfer.capture().materialUUID)===uuid);await page.evaluate(a=>fullCommonWorkbench.restore(a),nativeSkin);
 for(const layer of ['beauty','color','normal','roughness','regions']){await page.evaluate(layer=>fullFaceTransfer.set({layer}),layer);const h=await pixel();report.layers.push({layer,hash:h});await capture('layer-'+layer);}check('five inspection layers have actual different output',new Set(report.layers.map(p=>p.hash)).size===5);await page.evaluate(()=>fullFaceTransfer.set({layer:'beauty'}));
 const diffusionOn=await pixel();await page.evaluate(()=>fullFaceTransfer.set({diffusion:0}));const diffusionOff=await pixel();await page.evaluate(()=>fullFaceTransfer.set({diffusion:.42}));report.diffusion=await page.evaluate(()=>fullFaceTransfer.report().diffusion);check('real RGB diffusion pass changes the image',diffusionOn!==diffusionOff&&report.diffusion.frames>0,report.diffusion);
 const archive=await page.evaluate(()=>{const original=fullCommonWorkbench.archive();fullFaceTransfer.set({structure:1.1,detail:.6,meso:1.2,blood:.65,oil:.24,diffusion:.3});eyeTransferredHuman.set({resolution:2});const saved=fullCommonWorkbench.archive(),hash=__F_HASH__(fullCommonWorkbench.positions()),dense=__F_HASH__(eyeTransferredHuman.exportSurface().positions);fullFaceTransfer.set({enabled:false,detail:0});eyeTransferredHuman.set({resolution:0});fullCommonWorkbench.restore(JSON.parse(JSON.stringify(saved)));const exact=hash===__F_HASH__(fullCommonWorkbench.positions())&&dense===__F_HASH__(eyeTransferredHuman.exportSurface().positions);const before=__F_HASH__(fullCommonWorkbench.positions()),bad=structuredClone(saved);bad.faceSurface.settings.detail=50;let rejected=false;try{fullCommonWorkbench.restore(bad);}catch{rejected=true;}const atomic=before===__F_HASH__(fullCommonWorkbench.positions());const legacy=structuredClone(original);delete legacy.faceSurface;fullCommonWorkbench.restore(legacy);const legacyDisabled=!fullFaceTransfer.capture().faceSettings.enabled;fullCommonWorkbench.restore(original);return{exact,rejected,atomic,legacyDisabled,settings:saved.faceSurface,view:fullFaceTransfer.report()};});report.archive=archive;check('complete native + eye + full face + skin archive restores exactly',archive.exact);check('invalid face archive rejected before mutation',archive.rejected&&archive.atomic);check('legacy face-free archives do not silently acquire new appearance',archive.legacyDisabled);
 const blink=await page.evaluate(()=>{const saved=fullCommonWorkbench.archive();fullCommonWorkbench.setOwner('expression','anny');const rows=[];for(const v of[0,.5,1]){fullCommonWorkbench.set('anny.facialActions:eyeBlinkLeft',v);fullCommonWorkbench.set('anny.facialActions:eyeBlinkRight',v);rows.push({v,hash:__F_HASH__(fullCommonWorkbench.positions()),finite:fullCommonWorkbench.positions().every(Number.isFinite)});}fullCommonWorkbench.restore(saved);return rows;});report.blink=blink;check('original semantic blink still drives combined face',new Set(blink.map(r=>r.hash)).size===3&&blink.every(r=>r.finite));
 const mhr=await page.evaluate(()=>{const s=fullCommonWorkbench.archive();fullCommonWorkbench.setOwner('rig','mhr');const before=__F_HASH__(fullCommonWorkbench.positions());fullCommonWorkbench.set('mhr.identity:0',.35);const r={owner:fullCommonWorkbench.state().owners.rig,changed:before!==__F_HASH__(fullCommonWorkbench.positions()),finite:fullCommonWorkbench.positions().every(Number.isFinite)};fullCommonWorkbench.restore(s);return r;});report.mhr=mhr;check('MHR is still the original generator and rig',mhr.owner==='mhr'&&mhr.changed&&mhr.finite);
 const motion=await page.evaluate(async()=>{const studio=fullCommonWorkbench.motion();await studio.setMode('activity');const actor=studio.actors[0].human;await actor.skin.faceReady;const p=fullCommonWorkbench.positions();let error=0;for(let i=0;i<p.length;i++)error=Math.max(error,Math.abs(p[i]-actor.positions[i]));studio.advanceSteps(24);const r={error,faceShaderAttached:!!actor.skin.faceExtension,faceTexturesLoaded:actor.skin.faceExtension?.ready,rig:studio.diagnostics()};await studio.setMode('shape');return r;});report.motion=motion;check('existing skinned actor receives both composed geometry and face shading',motion.error<1e-7&&motion.faceShaderAttached&&motion.faceTexturesLoaded&&!motion.rig.errors.length,motion);
 await page.evaluate(()=>fullCommonWorkbench.view('three'));await capture('04-whole-platform');await page.evaluate(()=>fullFaceTransfer.view());await page.evaluate(()=>eyeTransferredHuman.set({resolution:2}));await capture('05-high-detail');await page.evaluate(()=>eyeTransferredHuman.set({resolution:1}));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>fullFaceTransfer.view());await capture('06-mobile-viewport');check('mobile viewport horizontal fit',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check('only one active canvas',await page.evaluate(()=>document.querySelectorAll('canvas').length===1));check('no runtime / shader errors',!report.errors.length,report.errors);
 if(commit){const[r,m]=await Promise.all([fetch(root+'preview.html'),fetch(root+'BUILD.json')]);assert(r.ok&&m.ok);const bytes=Buffer.from(await r.arrayBuffer()),manifest=await m.json();report.publicBuild=manifest;check('real immutable public bytes match manifest',bytes.length===manifest.previewBytes&&crypto.createHash('sha256').update(bytes).digest('hex')===manifest.previewSHA256);}
 report.pass=true;
})().catch(e=>{report.pass=false;report.error=e.stack;process.exitCode=1;console.error(e);}).finally(async()=>{if(page&&!report.pass)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});if(browser)await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log('ET12',report.pass,report.checks.length,report.error||'');});
