import * as THREE from '../../../vendor/three.module.js';
export const PLANT_SEGMENT=Object.freeze({id:'native-musa-two-nodes-r03',fromStation:0,toStation:1,sceneMetres:700,groundY:.081,railHalfClearance:1.6,visibilityRadius:175,sourceSpecies:'Musa balbisiana',units:'metre',timeSource:'host.elapsed',placementStatus:'source-crown-clearance-audited-browser-review-pending',windClearanceMarginM:.15,quality:'Complete native78 establishing Musa; independent KAOPU Musa adapter; visual review pending'});
export const PLANT_PLACEMENTS=Object.freeze([Object.freeze({id:'station-rear-establishing-musa',chainage:-35.32316911636920,z:-10.5,yaw:0,seed:761014,developmentStage:'establishing'}),Object.freeze({id:'street-rear-establishing-musa',chainage:405.24741793906245,z:-10.5,yaw:0,seed:761014,developmentStage:'establishing'})]);
const paths=Object.freeze({'plant-operator':'rules/plant-operator.mjs','native-equivalence':'rules/native78-equivalence.mjs','generation-worker':'rules/native78-generation-worker.mjs','mother-author':'rules/native78-musa-author.mjs','mother-runtime':'rules/native78-runtime.mjs','three-module':'vendor/three.module.min.js','three-core':'vendor/three.core.min.js'});
const defaultRead=async url=>{const r=await fetch(url);if(!r.ok)throw Error('Plant dependency HTTP '+r.status+' at '+url+' ['+(r.headers.get('content-type')||'unknown content-type')+']');return new Uint8Array(await r.arrayBuffer());};
/** Clone only Object3D nodes. Geometry, material, six PBR resources and original
 * native wind uniforms have one owner and are generated once per replacement.
 */
function sharedNativeClone(source){
 const clone=source.clone(true),originalNodes=[],clonedNodes=[];source.traverse(o=>originalNodes.push(o));clone.traverse(o=>clonedNodes.push(o));
 if(originalNodes.length!==clonedNodes.length)throw Error('Native clone hierarchy changed');
 for(let i=0;i<originalNodes.length;i++){const a=originalNodes[i],b=clonedNodes[i];if(a.isMesh){if(a.geometry!==b.geometry||a.material!==b.material&&(!Array.isArray(a.material)||!Array.isArray(b.material)||a.material.length!==b.material.length||a.material.some((m,j)=>m!==b.material[j])))throw Error('Native clone duplicated render ownership');b.customDepthMaterial=a.customDepthMaterial;b.customDistanceMaterial=a.customDistanceMaterial;}}
 return clone;
}
export function createNativePlantSegment({onChange=()=>{},readBytes=defaultRead,loadCodec=()=>import('./native-codec/codec.mjs'),loadOperator=()=>import('./rules/plant-operator.mjs')}={}){
 const root=new THREE.Group();root.name='KAOPU native Musa two nodes R03';let current=null,instances=[],recipe=null,disposed=false,distance=0,elapsed=0,status='uninitialized',error=null,revision=0,initPromise=null,buildPending=false,loadProof=null,stage='uninitialized',failure=null,buildAbort=null,generationProgress=null;
 function emit(){onChange(snapshot());}
 function apply(){root.position.x=-distance;if(current){for(const item of instances)item.root.visible=Math.abs(item.position[0]-distance+8)<=PLANT_SEGMENT.visibilityRadius;current.update(elapsed);}}
 function release(owner,list){for(const item of list){item.root.removeFromParent();if(item.root!==owner?.root)item.root.clear();}owner?.dispose();}
 async function replaceFromBytes(input){if(disposed)throw Error('Plant segment disposed');const token=++revision;buildAbort?.abort();const controller=new AbortController();buildAbort=controller;buildPending=true;status=current?'ready':'loading';error=null;failure=null;generationProgress=null;stage='codec-import';emit();let candidate=null,candidateInstances=[];const begin=performance.now();
  try{const codec=await loadCodec();stage='sqlite-decode';const decoded=await codec.decode(input);if(token!==revision||disposed)throw Error('Plant load superseded');const dependencies=codec.pinnedDependencies(),bytes={};stage='dependency-fetch';await Promise.all(dependencies.map(async d=>{if(!Object.hasOwn(paths,d.id))throw Error('Unregistered plant dependency id');bytes[d.id]=await readBytes(new URL(paths[d.id],import.meta.url));}));stage='dependency-integrity';await codec.verifyDependencyBytes(bytes);const verifiedAt=performance.now();if(token!==revision||disposed)throw Error('Plant load superseded');stage='operator-import';const operator=await loadOperator();stage='native-generation';candidate=await operator.buildNativeMusa(decoded,{verifyResources:codec.verifyResourceBytes,signal:controller.signal,onProgress:p=>{if(token===revision&&!disposed)generationProgress={...p};}});if(token!==revision||disposed)throw Error('Plant load superseded');
   stage='shared-instance-construction';candidateInstances=PLANT_PLACEMENTS.map((placement,i)=>({id:i===0?(decoded.instance.id??decoded.instance.instanceId):placement.id,root:i===0?candidate.root:sharedNativeClone(candidate.root),position:i===0?[...decoded.instance.positionM]:[placement.chainage,PLANT_SEGMENT.groundY,placement.z],yaw:i===0?decoded.instance.yawRadians:placement.yaw}));
   for(const item of candidateInstances){item.root.position.fromArray(item.position);item.root.rotation.y=item.yaw;item.root.scale.set(1,1,1);}candidate.update(elapsed);
   if(token!==revision||disposed)throw Error('Plant load superseded');if(buildAbort===controller)buildAbort=null;stage='scene-install';const prior=current,priorInstances=instances;for(const item of candidateInstances)root.add(item.root);current=candidate;instances=candidateInstances;candidate=null;candidateInstances=[];recipe=structuredClone(decoded);release(prior,priorInstances);status='ready';stage='ready';buildPending=false;loadProof={containerFormat:'SQLite KAOPU prototype envelope',profile:decoded.schema??decoded.profile,actualKaoPuByteLength:input.byteLength,dependencyBytes:Object.values(bytes).reduce((n,b)=>n+b.byteLength,0),containerAndDependencyValidationMs:verifiedAt-begin,totalLoadMs:performance.now()-begin,rollback:'old pair retained until verified new shared source ready',replacementRevision:token,generationCount:1,instanceCount:2,sharedGeometry:true,sharedMaterials:true,sharedWindUniforms:true};apply();emit();return snapshot();
  }catch(e){if(buildAbort===controller)buildAbort=null;release(candidate,candidateInstances);if(token===revision&&!disposed){buildPending=false;status=current?'ready':'error';error=String(e?.message||e);failure={stage,message:error,stack:String(e?.stack||''),cause:e?.cause?String(e.cause):null,workerStack:e?.workerStack?String(e.workerStack):null};stage=current?'ready':'error';emit();}throw e;}
 }
 function initialize(){if(disposed)return Promise.reject(Error('Plant segment disposed'));if(!initPromise)initPromise=readBytes(new URL('./native-codec/objects/establishing-musa.KaoPu',import.meta.url)).then(replaceFromBytes).catch(e=>{if(!current&&!disposed&&!failure){status='error';error=String(e?.message||e);failure={stage:'container-fetch',message:error,stack:String(e?.stack||''),cause:e?.cause?String(e.cause):null,workerStack:e?.workerStack?String(e.workerStack):null};stage='error';emit();}throw e;});return initPromise;}
 function update(view){if(disposed)return;if(!Number.isFinite(view?.distance)||!Number.isFinite(view?.elapsed)||view.elapsed<0)throw Error('Plants require authoritative finite Session distance and nonnegative elapsed');distance=view.distance;elapsed=view.elapsed;apply();}
 function snapshot(){const proof=current?.snapshot();return{...PLANT_SEGMENT,status,stage,error,failure,generationProgress,buildPending,disposed,distance,elapsed,count:instances.length,active:instances.filter(x=>x.root.visible).length,worldGeometryScale:1,ownAnimationLoop:false,externalMeshes:false,containsDeclaredImageMaterials:true,generationCount:current?1:0,sharedGeometry:true,sharedMaterials:true,loadProof,plants:instances.map((item,i)=>({id:item.id,species:'Musa balbisiana',chainage:item.position[0],position:[item.position[0]-distance,item.position[1],item.position[2]],visible:item.root.visible,seed:recipe.profile.seed,recipe:{...recipe,instance:{...recipe.instance,instanceId:item.id,positionM:[...item.position],yawRadians:item.yaw}},sharedSourceInstance:instances[0].id,proof:{...proof,instanceCopy:i,sharedGeometry:true,sharedMaterials:true}}))};}
 function dispose(){if(disposed)return;disposed=true;revision++;buildAbort?.abort();buildAbort=null;release(current,instances);current=null;instances=[];root.clear();root.removeFromParent();status='disposed';}
 return{root,initialize,replaceFromBytes,update,snapshot,dispose};
}
