/** Dependency-free worker boundary. No photos, fit records or identity metadata. */
import data from '../../data/teacher-groom.js';
import {TeacherGroomBinding,TeacherSkinBVH} from './TeacherGroomBinding.js';
import {LashBinding} from './LashBinding.js';
export function modelSnapshot(model){return {numVertices:model.numVertices,template:model.template,triangles:model.triangles,componentId:model.componentId,landmarkIndices:model.landmarkIndices,landmarkWeights:model.landmarkWeights};}
export function snapshotModel(raw){return {...raw,computeLandmarks(vertices,out){const count=this.landmarkIndices.length/3;for(let i=0;i<count;i++)for(let d=0;d<3;d++){let sum=0;for(let k=0;k<3;k++)sum+=vertices[this.landmarkIndices[i*3+k]*3+d]*this.landmarkWeights[i*3+k];out[i*3+d]=sum;}return count;}};}
export function createBinding(model,region,height=0){if(region==='lashes')return new LashBinding(model);let source=data;if(region==='brows'&&height!==0){source={...data,groups:{...data.groups,brows:structuredClone(data.groups.brows)}};const bvh=new TeacherSkinBVH(model);for(const guide of source.groups.brows){const hit=bvh.nearest([guide.root[0],guide.root[1]+height/1000,guide.root[2]]),delta=hit.p.map((x,k)=>x-guide.root[k]);guide.root=hit.p;guide.triangle=hit.t;guide.barycentric=hit.b;guide.points=guide.points.map(p=>p.map((x,k)=>x+delta[k]));}}return new TeacherGroomBinding(model,source,{region:region==='hair'?'scalp':'brows',count:region==='hair'?14000:1000,segments:region==='hair'?24:10,seed:724});}
export function dehydrateBinding(binding){const out={};for(const [key,value]of Object.entries(binding))if(!['model','data','guides'].includes(key)&&!key.endsWith('BVH'))out[key]=value;return out;}
export function hydrateBinding(raw,model,region){const binding=Object.assign(Object.create(region==='lashes'?LashBinding.prototype:TeacherGroomBinding.prototype),raw);binding.model=model;if(region!=='lashes'){binding.data=data;binding.guides=region==='brows'?data.groups.brows:[...data.groups.main,...data.groups.independent];}return binding;}
