'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),zlib=require('zlib'),{execFileSync}=require('child_process'),{pathToFileURL}=require('url');
function pngSolid(r,g,b){const crc=a=>{let c=0xffffffff;for(const v of a){c^=v;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0},chunk=(s,b)=>{let t=Buffer.from(s),n=Buffer.alloc(4),c=Buffer.alloc(4);n.writeUInt32BE(b.length);c.writeUInt32BE(crc(Buffer.concat([t,b])));return Buffer.concat([n,t,b,c])},h=Buffer.alloc(13),a=Buffer.alloc(32*(1+32*4));h.writeUInt32BE(32,0);h.writeUInt32BE(32,4);h[8]=8;h[9]=6;for(let y=0;y<32;y++)for(let x=0;x<32;x++)a.set([r,g,b,255],y*129+1+x*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',zlib.deflateSync(a)),chunk('IEND',Buffer.alloc(0))])}
module.exports=async function(browser,inputUrl,out,group='core'){
 const root=path.resolve(__dirname,'..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');fs.mkdirSync(out,{recursive:true});const report={passed:false,group,scope:'Unified one-instance profiles / skin / hair browser '+group,fullRegressionPassed:false,contactAcceptance:false,physicalIPhoneTested:false,checks:[],errors:[],frames:[]};let context,temp,page;
 const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));const check=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});save();console.log('[Unified]',pass?'PASS':'FAIL',name);if(!pass)throw Error(name+' '+JSON.stringify(detail))};
 try{
  let url=inputUrl;if(url.startsWith('file:')){temp=fs.mkdtempSync(path.join(os.tmpdir(),'gnm-unified-'));const target=path.join(temp,'workbench.html');report.offline=JSON.parse(execFileSync('python3',[path.join(root,'tools/build-experiment-offline.py'),'--output',target,'--assets-dir',process.env.GNM_ASSETS_DIR||path.join(temp,'assets'),'--download'],{encoding:'utf8',timeout:240000,maxBuffer:2000000}));url=pathToFileURL(target).href;}
  context=await browser.newContext({viewport:{width:1000,height:900},deviceScaleFactor:1,hasTouch:true});page=await context.newPage();page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
  if(url.startsWith('http')){const files=['experiment.html','experiment.css',...fs.readdirSync(path.join(root,'src')).filter(f=>f.endsWith('.js')).map(f=>'src/'+f),'data/teacher-groom.js'];report.sourceHashes=Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]));report.served=Object.fromEntries(await Promise.all(files.map(async f=>{let r=await context.request.get(new URL(f,url).href);return[f,{status:r.status(),sha256:sha(await r.body())}]})));check('public source bytes match exact candidate',files.every(f=>report.served[f].status===200&&report.served[f].sha256===report.sourceHashes[f]),report.served);}
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:180000});await page.waitForFunction(()=>window.groomStudy?.ready||!document.getElementById('error').hidden,null,{timeout:300000});check('real unified WebGL starts',await page.evaluate(()=>!!window.groomStudy?.ready),await page.locator('#error').textContent());
  const act=(name,arg)=>page.evaluate(({name,arg})=>groomStudy[name](arg),{name,arg});const diag=()=>page.evaluate(()=>groomStudy.diagnostics());
  const sample=async(name,screenshot=true)=>{let a=await page.evaluate(()=>{const d=groomStudy.diagnostics(),c=document.getElementById('canvas'),gl=c.getContext('webgl2'),p=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,p);let hash=2166136261;for(const v of p)hash=Math.imul(hash^v,16777619)>>>0;return{d,hash,gl:gl.getError()}});if(screenshot)await page.locator('#canvas').screenshot({path:path.join(out,name+'.png')});report.frames.push({name,...a});save();return a};
  const base=await sample('01-default-female-a');const ids=base.d.instances;const stable=d=>Object.entries(d.instances).filter(([k])=>k.startsWith('same')).every(([,v])=>v===true)&&d.instances.sourceGeometryUuid===ids.sourceGeometryUuid&&d.instances.renderGeometryUuid===ids.renderGeometryUuid&&d.instances.skinMaterialUuid===ids.skinMaterialUuid&&d.instances.weightsLoaded.length===3&&new Set(d.instances.weightsLoaded).size===3;
  const valid=d=>stable(d)&&d.uvRender.maxPositionError===0&&d.uvRender.maxNormalError===0&&d.uvRender.triangleCornerMismatch===0&&d.rootBinding.every(b=>b.maxRootBarycentricError<1e-6&&b.maxRootNormalOffsetError<1e-6)&&d.bindings.every(b=>b.finite);
  check('female-a default and skin shader active',base.d.identityProfile.id==='female-a'&&base.d.state.case==='neutral'&&base.d.skin.compiled>0&&base.gl===0,base.d.identityProfile);check('one model UV skin and real scalp instances',valid(base.d),{instances:base.d.instances,uv:base.d.uvRender});check('only official separated skin eye mouth regions',base.d.skin.regions.skinVertices===12608&&base.d.skin.regions.eyeVertices>0&&base.d.skin.skinMapsOnly,base.d.skin.regions);
  const cert=JSON.parse(fs.readFileSync(path.join(root,'EAR-RUNTIME-CERTIFICATE.json')));
  if(group==='core'){
   await page.locator('[data-identity-profile="neutral"]').click();const neutral=await sample('02-original-head');check('original head and R9 curves exactly restored',neutral.d.model.positionHash===cert.states.neutral.modelPositionHash&&JSON.stringify(neutral.d.geometryHashes)===JSON.stringify(cert.states.neutral.geometryHashes)&&valid(neutral.d),{head:neutral.d.model,curves:neutral.d.geometryHashes});
   const neutralSkin=JSON.stringify(neutral.d.skin.parameters),neutralCamera=JSON.stringify(neutral.d.camera);
   for(let round=0;round<2;round++)for(const profile of ['female-a','female-b','neutral']){
    await page.locator('[data-identity-profile="'+profile+'"]').click();const d=await diag();check('repeat '+round+' '+profile+' preserves single instances UV roots skin camera',d.identityProfile.id===profile&&valid(d)&&JSON.stringify(d.skin.parameters)===neutralSkin&&JSON.stringify(d.camera)===neutralCamera,{identity:d.identityProfile,instances:d.instances});
    if(profile==='neutral')check('round '+round+' exact original curves',d.model.positionHash===cert.states.neutral.modelPositionHash&&JSON.stringify(d.geometryHashes)===JSON.stringify(cert.states.neutral.geometryHashes));
   }
   await act('setCase','smile');for(const profile of ['female-a','female-b','neutral']){await act('setIdentityProfile',profile);const d=await diag();check(profile+' identity switch preserves smile',d.state.case==='smile'&&d.identityProfile.id===profile&&valid(d));}
   await act('setIdentityProfile','female-a');for(const expression of ['neutral','smile','surprise']){await act('setCase',expression);const d=await diag();check(expression+' preserves female-a identity and current instances',d.state.case===expression&&d.identityProfile.id==='female-a'&&valid(d));}
   await act('setCase','neutral');await act('setIdentityProfile','female-b');await sample('03-female-b');await act('setIdentityProfile','female-a');await act('setCamera','front');await sample('04-female-a-front');await act('setEyeCamera');await sample('05-female-a-eye');
   check('legacy ambiguous identity case cannot silently change profile',await page.evaluate(()=>{const before=groomStudy.getState().identityProfile;try{groomStudy.setCase('identity');return false}catch{return groomStudy.getState().identityProfile===before}}));check('invalid profile rejected atomically',await page.evaluate(()=>{const before=JSON.stringify(groomStudy.getState());try{groomStudy.setIdentityProfile('invalid');return false}catch{return JSON.stringify(groomStudy.getState())===before}}));
  }else{
   await act('setSkinParameters',{roughness:.72,detail:.5});const editedSkin=JSON.stringify((await diag()).skin.parameters);await act('setIdentityProfile','female-b');check('skin parameter edits survive identity switch',JSON.stringify((await diag()).skin.parameters)===editedSkin);await act('resetSkin');
   const mapBaseline=await sample('maps-program-baseline',false);let lastMapFrame=mapBaseline;
   await page.locator('#skinMapImport > summary').click();temp ||=fs.mkdtempSync(path.join(os.tmpdir(),'gnm-unified-maps-'));
   for(const[kind,rgb,space]of [['color',[150,125,113],'srgb'],['normal',[170,105,245],''],['roughness',[180,180,180],'']]){const file=path.join(temp,kind+'.png');fs.writeFileSync(file,pngSolid(...rgb));await page.locator('#skinMap-'+kind).setInputFiles(file);await page.waitForFunction(k=>!!groomStudy.diagnostics().skin.maps[k],kind);const mapped=await sample('map-'+kind);check(kind+' local map changes real pixels with correct encoding',mapped.d.skin.maps[kind].colorSpace===space&&mapped.hash!==lastMapFrame.hash&&mapped.d.model.positionHash===mapBaseline.d.model.positionHash&&JSON.stringify(mapped.d.geometryHashes)===JSON.stringify(mapBaseline.d.geometryHashes)&&mapped.gl===0,{map:mapped.d.skin.maps[kind],before:lastMapFrame.hash,after:mapped.hash});lastMapFrame=mapped;}
   const maps=JSON.stringify((await diag()).skin.maps);await act('setIdentityProfile','female-a');await act('setIdentityProfile','neutral');await act('setIdentityProfile','female-b');check('all local maps stay on same skin instance across profiles',JSON.stringify((await diag()).skin.maps)===maps&&valid(await diag()));
   await page.locator('#skinMap-color').setInputFiles([]);check('cancelled file picker preserves current map',JSON.stringify((await diag()).skin.maps)===maps);await page.locator('#skinMap-color').setInputFiles(path.join(temp,'color.png'));await page.waitForFunction(()=>document.getElementById('skinMap-color').value==='');check('repeat same local file works',JSON.stringify((await diag()).skin.maps)===maps);
   for(const kind of ['color','normal','roughness'])await page.locator('[data-clear-map="'+kind+'"]').click();const cleared=await sample('maps-cleared-exact');check('clear maps restores exact same-profile same-camera program pixels',Object.values(cleared.d.skin.maps).every(x=>x===null)&&cleared.d.identityProfile.id==='female-b'&&cleared.hash===mapBaseline.hash&&JSON.stringify(cleared.d.camera)===JSON.stringify(mapBaseline.d.camera),{before:mapBaseline.hash,after:cleared.hash});
   await act('setIdentityProfile','female-a');const before=await diag();await act('setGroom',{hairColor:'#63341e',hairLength:72,hairDensity:70,browsDensity:65});const edited=await sample('06-hair-edits');check('hair controls leave chosen head UV and skin intact',edited.d.model.positionHash===before.model.positionHash&&edited.d.identityProfile.id==='female-a'&&valid(edited.d));await act('resetAll');check('groom reset keeps chosen identity',(await diag()).identityProfile.id==='female-a');
   await page.locator('#turnLeft').click();const camera=JSON.stringify((await diag()).camera);await act('setIdentityProfile','female-b');check('identity switch retains manual camera',JSON.stringify((await diag()).camera)===camera);await act('setZoom',6);check('600 percent zoom works',(await diag()).state.zoom===6);await act('setZoom',1);
   const start=(await diag()).frameCount;await page.locator('#rotate').click();await page.waitForFunction(n=>groomStudy.diagnostics().frameCount>n+2,start,{timeout:180000});await page.locator('#rotate').click();const stopped=await diag();await page.waitForTimeout(250);check('automatic orbit advances and pauses',stopped.frameCount>start+2&&(await diag()).frameCount===stopped.frameCount&&!stopped.state.turntable);
   for(const mode of ['clay','uv','skin']){await act('setSkinMode',mode);const d=await diag();check(mode+' display preserves profile and UV topology',d.identityProfile.id==='female-b'&&valid(d));}
   await act('setIdentityProfile','female-a');await act('setCase','neutral');for(const size of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await act('setCamera','three');await page.evaluate(()=>scrollTo(0,0));check(size.width+' profile and orbit controls fit first screen',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll('[data-identity-profile]'),...['rotate','turnLeft','turnRight','reset'].map(x=>document.getElementById(x))].every(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.top>=0&&r.bottom<=innerHeight})));await page.screenshot({path:path.join(out,'mobile-'+size.width+'.png')});await page.locator('[data-identity-profile="female-b"]').tap();await page.locator('[data-identity-profile="female-a"]').tap();check(size.width+' touch profile repeat works',(await diag()).identityProfile.id==='female-a'&&valid(await diag()));}
  }
  check('no browser shader or sampled GL errors',report.errors.length===0&&report.frames.every(x=>x.gl===0),report.errors);report.passed=true;save();return report;
 }catch(e){report.errors.push(e.stack||String(e));if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true})}catch{};save();throw e}finally{await context?.close();if(temp)fs.rmSync(temp,{recursive:true,force:true})}
};
