/* KAOPU R06. Viewer changes and reference study. IQ/TDM derivatives: CC BY-NC-SA 3.0. */
'use strict';
const ROOT=new URL('./',document.currentScript.src),REPO=new URL('../../',ROOT);
(async()=>{
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o));
const palette=[['暖褐','#73513b','#bf9e78'],['砂米','#a49578','#e3d4b6'],['冷灰','#636d75','#bdc6cf'],['炭黑','#22272c','#626b72'],['铁锈红','#7f3324','#cf8660'],['赭黄','#8b601c','#d8b661'],['青绿','#285f52','#8fba98'],['蓝灰','#334c72','#96b1ce'],['灰紫','#65455f','#b7a0b8'],['象牙白','#b1ac9c','#ece5d5']];
const effects={dry:{wet:0,roughness:.9,crack:0,moss:0,lichen:0},wet:{wet:.9,roughness:.65,crack:0,moss:0,lichen:0},cracked:{wet:.12,roughness:.86,crack:.04,moss:0,lichen:0},moss:{wet:.2,roughness:.82,crack:.01,moss:.70,lichen:0},lichen:{wet:.05,roughness:.88,crack:.015,moss:0,lichen:.9},forest:{wet:.78,roughness:.72,crack:.045,moss:.63,lichen:.6}};
const meta={wet:{title:'01 / 湿石：十色、裂纹、青苔与 PBR',sub:'继承已认可 R04 的几何与材质程序。仅补统一观察操作，不重做石头。',left:'已认可的湿石复刻基线',note:'颜色与表面状态独立。裂纹深度、苔层厚度接入表面求交；原老师的细颗粒仍为法线层。普通石材金属度固定为 0。',relation:'原球体 → 九次球体削切 → 低频位移 → 裂纹 / 苔层高度 → 表面属性 → GGX 或老师光照\n颜色参数、裂纹场、青苔场共用对象坐标。左侧基线不受右侧材质修改影响。'},smooth:{title:'02 / 参考图石头：形体和质感一起看',sub:'现在默认演示粗糙岩石，不再用白模布尔练习替代目标效果。',left:'用户提供的石头参考图',note:'以参考图中的暗灰岩石、坑洼颗粒、冷暖侧光为目标。几何由平滑裁切与真实 fBm 位移产生；底色为显式的程序近似，原图贴图与相机尚未完全标定，不标成 100% 复刻通过。',relation:'母球 → 28 个平面 → Smooth Maximum → fBm 实际位移 → 表面法线 → 程序矿物底色 → 云母反射区域 → 冷暖双灯 / 自阴影\n平方根平滑：smax(a,b,k)=(a+b+sqrt((a-b)^2+k^2))/2\n与参考图相同的公式，不等于仅凭公式就能确定参考图全部材质；当前外观拟合与原始证据分开保存。'},iq:{title:'03 / IQ 岩石：保留你认可的效果',sub:'原来的形体、位移和光照不改。新增可逆缩放、平移、关闭老师与统一导航。',left:'老师原始录屏',note:'默认保留 R05 的 IQ 参数和 1×1 中性输入。iChannel0 原贴图未提供；不把当前输入冒充原贴图。原片可按需载入，关闭窗口不会删除原片或出处。',relation:'IQ 原码：母球 → 28 个平面平滑裁切 → fBm 位移 → 四点法线 → iChannel0 三向采样 → 云母区域 → 双灯与阴影 → 色调输出\n观察适配：只增加射线视野缩放与屏幕中心偏移；缩放=1、平移=0 时恢复旧输入。\n原始源码不被覆盖；iChannel0 原贴图仍待补。'}};
const initial={wet:{yaw:1.155,pitch:.2,time:3.85,palette:0,pbr:1,view:0,baseline:false,roughness:.72,wet:.65,crack:0,crackWidth:.018,crackScale:1.35,moss:0,relief:.014,lichen:0,exposure:1.2,seed:11,light:-.65},smooth:{yaw:.20,pitch:-.04,time:0,k:.0125,method:2,displacement:1,planes:28,view:0,tone:1},iq:{yaw:0,pitch:0,time:0,k:.0125,method:2,displacement:1,planes:28,view:0,tone:1}};
const states=clone(initial),inspect={};for(const id of Object.keys(meta))inspect[id]={teacher:{zoom:1,pan:[0,0],hidden:id!=='wet'},result:{zoom:1,pan:[0,0],hidden:false}};
let active='smooth',ready=false,running=false,dirty=true,last=0,renderers=[],sources={},programs={},media={},loads={},thumbs={},referenceReady=false;
const ranges={wet:[['roughness','基底粗糙度',.1,.95,.01],['wet','湿润 / 水膜',0,1,.01],['crack','裂纹深度',0,.075,.001],['crackWidth','裂纹宽度',.004,.04,.001],['crackScale','裂纹密度',.65,3,.01],['moss','青苔覆盖',0,1,.01],['relief','苔层厚度',0,.035,.001],['lichen','地衣斑点',0,1,.01],['exposure','曝光',.4,2.5,.01],['light','光源方向',-3.14,3.14,.01],['seed','分布种子',1,99,1]],smooth:[['k','平滑范围 k',0,.1,.0025],['displacement','几何表面起伏',0,1,.02],['time','石头朝向 / 时间',0,157,.5],['tone','矿物底色亮度',.4,2,.02]],iq:[['planes','裁切平面',0,28,1],['displacement','几何表面起伏',0,1,.02],['k','平滑范围 k',0,.1,.0025],['time','原码时间',0,157,.5]]};
function fail(e){$('error').hidden=false;$('error').textContent=e.message||String(e);$('status').textContent='加载 / 操作未完成';console.error(e);}
async function read(url){const r=await fetch(url);if(!r.ok)throw Error('资源加载失败 '+url+' HTTP '+r.status);return r.text();}
async function sha(text){if(!crypto.subtle)return 'unavailable';return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
const VS='#version 300 es\nprecision highp float;const vec2 P[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(P[gl_VertexID],0,1);}';
// A ray-coordinate transform: no mesh replacement, screenshot enlargement or material changes.
function zoomShader(s){s=s.replace(/gl_FragCoord\.xy/g,'((gl_FragCoord.xy-0.5*iResolution.xy)/uInspectZoom+0.5*iResolution.xy+uInspectPan*iResolution.y)');return s.replace('#version 300 es','#version 300 es\nuniform highp float uInspectZoom;uniform highp vec2 uInspectPan;');}
function renderer(canvas){const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('浏览器未启用 WebGL2');const cache=new Map(),vao=gl.createVertexArray();let program,locs;const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([180,180,180,255]));for(const[p,v]of [[gl.TEXTURE_MIN_FILTER,gl.LINEAR],[gl.TEXTURE_MAG_FILTER,gl.LINEAR],[gl.TEXTURE_WRAP_S,gl.REPEAT],[gl.TEXTURE_WRAP_T,gl.REPEAT]])gl.texParameteri(gl.TEXTURE_2D,p,v);
function compile(type,s){const h=gl.createShader(type);gl.shaderSource(h,s);gl.compileShader(h);if(!gl.getShaderParameter(h,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(h));return h;}
function use(key){if(!cache.has(key)){const v=compile(gl.VERTEX_SHADER,VS),f=compile(gl.FRAGMENT_SHADER,zoomShader(programs[key])),p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(v);gl.deleteShader(f);cache.set(key,{p,locs:{}});}const entry=cache.get(key);program=entry.p;locs=entry.locs;gl.useProgram(program);gl.bindVertexArray(vao);}
function l(k){return Object.prototype.hasOwnProperty.call(locs,k)?locs[k]:(locs[k]=gl.getUniformLocation(program,k));}function f(k,v){gl.uniform1f(l(k),v);}function i(k,v){gl.uniform1i(l(k),v);}function v3(k,v){gl.uniform3fv(l(k),v);}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;fail(Error('WebGL 上下文丢失，请刷新页面。'));});
return {canvas,gl,draw(key,s,view,isTeacher=false){use(key);gl.viewport(0,0,canvas.width,canvas.height);gl.uniform3f(l('iResolution'),canvas.width,canvas.height,1);f('iTime',s.time);i('iFrame',Math.max(0,Math.floor(s.time*30)));f('uInspectZoom',view.zoom);gl.uniform2fv(l('uInspectPan'),view.pan);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);i('iChannel0',0);f('uYaw',s.yaw);f('uPitch',s.pitch);f('uIQK',s.k||0);f('uDisp',s.displacement??1);f('uTone',s.tone??1);i('uPlanes',s.planes??28);i('uMethod',s.method??2);i('uChannel',s.view||0);
if(key.startsWith('wet')){gl.uniform4f(l('iMouse'),s.yaw*100,(2-s.pitch)*100,1,0);const vals={uRoughness:s.roughness,uWet:s.wet,uCrack:s.crack,uCrackWidth:s.crackWidth,uCrackScale:s.crackScale,uMoss:s.moss,uRelief:s.relief,uLichen:s.lichen,uSeed:s.seed,uExposure:s.exposure,uLight:s.light,uZoom:1};for(const[k,n]of Object.entries(vals))f(k,n);i('uBaseline',isTeacher||s.baseline?1:0);i('uPBR',s.pbr);i('uView',[0,5,3,1,2,4,6][s.view]||0);v3('uBase',linear(palette[s.palette][1]));v3('uGrain',linear(palette[s.palette][2]));}gl.drawArrays(gl.TRIANGLES,0,3);},pixels(){const b=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,b);return b;}};}
function linear(hex){return [1,3,5].map(j=>{const x=parseInt(hex.slice(j,j+2),16)/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});}
function replaceOne(s,a,b){if(!s.includes(a))throw Error('原码适配签名不匹配：'+a.slice(0,40));return s.replace(a,b);}
function iqShader(raw,reference=false){let s=raw;
s=replaceOne(s,'const float h = 0.0125;','float h = uIQK;');
s=replaceOne(s,'float dp = (dot(q,rp)-1.0)/length(rp);','if(i>uPlanes)break;float dp = (dot(q,rp)-1.0)/length(rp);');
s=replaceOne(s,'d += 0.06*dis;','d += 0.06*uDisp*dis;');
s=replaceOne(s,'const vec3 po = vec3(0.0,0.3,1.5);','vec3 po = vec3(0.0,0.3,1.5);po.yz=mat2(cos(uPitch),-sin(uPitch),sin(uPitch),cos(uPitch))*po.yz;po.xz=mat2(cos(uYaw),-sin(uYaw),sin(uYaw),cos(uYaw))*po.xz;');
s=s.replace('const vec3 ww','vec3 ww').replace('const vec3 uu','vec3 uu').replace('const vec3 vv','vec3 vv');
s=replaceOne(s,'vec3 nor = calc_normal(pos,1.0,time);','vec3 nor = calc_normal(pos,1.0,time);if(uChannel==2)return nor*.5+.5;if(uChannel==1)return pow(vec3(.62)*(.2+.8*max(dot(nor,normalize(vec3(-.6,1.,1.))),0.0)),vec3(.4545));');
if(reference){
s=s.replace('vec3(1.0,0.6,0.1)','vec3(1.0,0.8,-0.3)').replace('vec3(-1.0,0.3,-0.3)','vec3(-1.0,0.5,0.45)').replace('2.5*vec3(16.0,12.0,8.0)','0.65*vec3(16.0,12.0,8.0)').replace('0.7*vec3(8.0,12.0,18.0)','1.0*vec3(8.0,12.0,18.0)').replace('col += spe*dif*mate_ks*3.0;','col += spe*dif*mate_ks*0.45;');
s=replaceOne(s,'return (a+b+sqrt((a-b)*(a-b)+h*h))/2.0;','if(h<=0.0||uMethod==0)return max(a,b);if(uMethod==1){float w=clamp(.5+.5*(b-a)/h,0.,1.);return mix(a,b,w)+h*w*(1.-w);}return (a+b+sqrt((a-b)*(a-b)+h*h))/2.0;');
s=replaceOne(s,'vec3 mate_alb = pow(box_mapped_texture(iChannel0,opos*0.2,onor).xyz,vec3(3.0,3.2,3.0));','float mineral=clamp(.5+.6*fbm(opos*7.0,4),0.0,1.0);float patina=smoothstep(.0,.5,fbm(opos*3.1+8.0,4));vec3 mate_alb=mix(vec3(.018,.024,.031),vec3(.057,.063,.070),mineral);mate_alb=mix(mate_alb,vec3(.078,.048,.026),patina*.4);mate_alb*=uTone;');
}
return '#version 300 es\nprecision highp float;precision highp int;uniform vec3 iResolution;uniform float iTime;uniform int iFrame;uniform sampler2D iChannel0;uniform float uIQK,uDisp,uYaw,uPitch,uTone;uniform int uPlanes,uChannel,uMethod;out vec4 fragColor;\n'+s+'\nvoid main(){mainImage(fragColor,gl_FragCoord.xy);}';}
function mediaKind(){if(media[active])return media[active].type;return active==='wet'?'live':active==='smooth'&&window.KP_REFERENCE?'image':'empty';}
function draw(){if(!ready)return;const p=inspect[active],s=states[active];if(!p.teacher.hidden&&mediaKind()==='live')renderers[0].draw('wetTeacher',s,p.teacher,true);if(!p.result.hidden)renderers[1].draw(active==='wet'?'wetMaterial':active,s,p.result);dirty=false;}
function thumbnail(id){if(!ready)return;const r=renderers[1],w=r.canvas.width,h=r.canvas.height;r.canvas.width=320;r.canvas.height=180;r.draw(id==='wet'?'wetMaterial':id,states[id],{zoom:1,pan:[0,0]});$("thumb-"+id).getContext('2d').drawImage(r.canvas,0,0);r.canvas.width=w;r.canvas.height=h;thumbs[id]=true;dirty=true;}
function layout(){const p=inspect[active];for(const side of ['teacher','result']){$(side+'Pane').hidden=p[side].hidden;$(side+'Zoom').textContent=Math.round(p[side].zoom*100)+'%';}const n=Number(!p.teacher.hidden)+Number(!p.result.hidden);$('stage').classList.toggle('single',n===1);$('allClosed').hidden=n!==0;$('showTeacher').textContent=p.teacher.hidden?'显示老师 / 对照':'隐藏老师 / 对照';$('showResult').textContent=p.result.hidden?'显示作品':'隐藏作品';applyMediaTransform();dirty=true;}
function applyMediaTransform(){const q=inspect[active].teacher;for(const id of ['reference','teacherVideo']){$(id).style.transform=`translate(${-q.pan[0]*100*q.zoom}%,${q.pan[1]*100*q.zoom}%) scale(${q.zoom})`;}}
function updateMedia(){const kind=mediaKind();$('teacherVideo').pause();$('teacherCanvas').hidden=kind!=='live';$('reference').hidden=kind!=='image';$('teacherVideo').hidden=kind!=='video';$('teacherEmpty').hidden=kind!=='empty';$('teacherLive').hidden=active!=='wet';$('loadVideoEmpty').textContent=active==='smooth'?'载入原始参考图':'载入原始录屏';$('teacherTitle').textContent=meta[active].left;
$('teacherStamp').textContent=kind==='live'?'R03 源码复刻基线 · 非原视频':kind==='image'?'参考图 · 浏览显示':'老师原片 · 未转码';
if(kind==='image'){$('reference').src=media[active]?.url||window.KP_REFERENCE;$('teacherInfo').textContent=media[active]?'用户原图 · 仅显示缩放':'用户上传参考原图 · 仅显示缩放';}else if(kind==='video'){$('teacherVideo').src=media[active].url;$('teacherInfo').textContent=media[active].name+' · 原片未转码';}else $('teacherInfo').textContent=kind==='live'?'960 × 540 · 实时计算':'老师原片未在网页托管，可载入已有原件';
$('reference').onerror=()=>{if(active==='smooth'){ $('reference').hidden=true;$('teacherEmpty').hidden=false;$('teacherInfo').textContent='参考图显示资源尚未载入，可选择原始参考图';}};}
function update(){const s=states[active];$('title').textContent=meta[active].title;$('subtitle').textContent=meta[active].sub;$('teacherTitle').textContent=meta[active].left;$('resultTitle').textContent=active==='wet'?(s.baseline?'已还原湿石复刻基线':'湿石 · '+palette[s.palette][0]):active==='smooth'?'暗灰粗糙岩石 · 参考外观复述':'IQ 岩石 · 保留认可效果';$('resultStamp').textContent=active==='smooth'?'LIVE 3D · 参考外观拟合 / 待验收':'LIVE 3D · 拖动旋转 / 滚轮缩放';$('caseNote').textContent=meta[active].note;$('channel').value=s.view;$('lighting').value=s.pbr?'pbr':'legacy';$('lightingField').hidden=active!=='wet';$('baselineButton').hidden=active!=='wet';$('relation').textContent=meta[active].relation;$('formula').textContent=active==='wet'?'surface = base − relief + cracks；material → light → color':'smax(a,b) = (a + b + √((a − b)² + k²)) / 2     ·     λ = k²';$('code').textContent=active==='wet'?sources.material:programs[active];$('sourceInfo').textContent=active==='wet'?'继承 R04 teacher.frag + material.glsl。相机观察适配与材质程序分离。':'IQ 原始上传文本 SHA-256：'+sources.iqHash+'。适配源码单独保留；03 不改矿物底色。';$('curve').hidden=active==='wet';document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===active));document.querySelectorAll('[data-palette]').forEach(b=>b.classList.toggle('on',+b.dataset.palette===s.palette));for(const[key]of ranges[active]){const input=$('p-'+key),out=$('o-'+key);if(input)input.value=s[key];if(out)out.textContent=key==='planes'||key==='seed'?s[key]:s[key].toFixed(key==='k'?4:2);}drawCurve();layout();}
function buildControls(){$('channel').replaceChildren();const channels=active==='wet'?['材质 / 灯光','白模 / 几何起伏','表面法线','底色 / 无光照','粗糙度','裂纹 / 青苔分布','环境遮蔽']:['材质 / 灯光','白模 / 几何起伏','表面法线'];channels.forEach((text,i)=>$('channel').add(new Option(text,i)));$('swatches').replaceChildren();$('effects').replaceChildren();$('controls').replaceChildren();$('swatches').hidden=active!=='wet';if(active==='wet'){palette.forEach((p,i)=>{const b=document.createElement('button');b.dataset.palette=i;const span=document.createElement('span');span.style.background=`linear-gradient(90deg,${p[1]},${p[2]})`;b.append(span,document.createTextNode(p[0]));b.onclick=()=>{states.wet.palette=i;states.wet.baseline=false;update();};$('swatches').append(b);});for(const[id,name]of [['dry','干燥粗石'],['wet','雨后湿石'],['cracked','开裂石'],['moss','青苔覆盖'],['lichen','地衣风化'],['forest','潮湿苔裂叠层']]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{Object.assign(states.wet,effects[id],{baseline:false});update();};$('effects').append(b);}}else if(active==='smooth'){for(const[i,name]of [[2,'平方根 Smooth Max'],[1,'多项式 Smooth Max'],[0,'硬 max 对照']]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{states.smooth.method=i;update();};$('effects').append(b);}}
for(const[key,name,min,max,step]of ranges[active]){const l=document.createElement('label');l.className='control';l.innerHTML=`<span>${name}</span><input id="p-${key}" type="range" min="${min}" max="${max}" step="${step}"><output id="o-${key}"></output>`;$('controls').append(l);$('p-'+key).oninput=e=>{states[active][key]=Number(e.target.value);states[active].baseline=false;update();};}}
function setURL(id){if(location.protocol==='http:'||location.protocol==='https:')history.pushState({},'',new URL('?case='+id,location.href));}
function selectCase(id,push=true){if(id==='home'){$('catalog').classList.add('overview');$('catalog').scrollIntoView({behavior:'smooth',block:'start'});if(push)setURL('home');return;}if(!meta[id])id='smooth';running=false;$('rotate').textContent='开始旋转';if(ready&&active!==id)thumbnail(active);active=id;$('catalog').classList.remove('overview');if(push)setURL(id);buildControls();updateMedia();update();if(ready)draw();}
function drawCurve(){if(active==='wet')return;const g=$('curve').getContext('2d'),w=960,h=220,s=states[active];g.fillStyle='#0a1115';g.fillRect(0,0,w,h);const a=t=>.16*(t-1)**2-.3,b=t=>.55*Math.sin(2.4*t),k=s.k;const mx=(x,y)=>{if(!k||s.method===0)return Math.max(x,y);if(s.method===1){const z=Math.max(0,Math.min(1,.5+.5*(y-x)/k));return x*(1-z)+y*z+k*z*(1-z);}return (x+y+Math.sqrt((x-y)**2+k*k))/2;};for(const[fn,col]of [[a,'#6ebae9'],[b,'#e864a4'],[t=>mx(a(t),b(t)),'#dfc493']]){g.strokeStyle=col;g.lineWidth=2;g.beginPath();for(let i=0;i<950;i++){const t=-2.5+5*i/950,x=i+5,y=175-fn(t)*55;i?g.lineTo(x,y):g.moveTo(x,y);}g.stroke();}}
function zoom(side,factor,x=0,y=0){const v=inspect[active][side],old=v.zoom;v.zoom=Math.max(.35,Math.min(5,old*factor));v.pan[0]+=x*(1/old-1/v.zoom);v.pan[1]+=y*(1/old-1/v.zoom);layout();}
for(const side of ['teacher','result']){const view=$(side+'View');const pointers=new Map();let drag=null,pinch=0;
view.addEventListener('wheel',e=>{e.preventDefault();const r=view.getBoundingClientRect();zoom(side,Math.exp(-e.deltaY*.0015),(e.clientX-r.left-r.width/2)/r.height,(-e.clientY+r.top+r.height/2)/r.height);},{passive:false});
view.addEventListener('pointerdown',e=>{if(e.target.closest('button,video'))return;running=false;pointers.set(e.pointerId,[e.clientX,e.clientY]);view.setPointerCapture(e.pointerId);const v=inspect[active][side];drag={x:e.clientX,y:e.clientY,yaw:states[active].yaw,pitch:states[active].pitch,pan:[...v.pan],panOnly:e.shiftKey||e.button===2||side==='teacher'&&mediaKind()!=='live'};if(pointers.size===2){const[a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);}});
view.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const[a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)zoom(side,d/pinch);pinch=d;drag=null;return;}if(!drag)return;const r=view.getBoundingClientRect(),dx=e.clientX-drag.x,dy=e.clientY-drag.y,v=inspect[active][side];if(drag.panOnly){v.pan=[drag.pan[0]-dx/r.height/v.zoom,drag.pan[1]+dy/r.height/v.zoom];applyMediaTransform();}else{states[active].yaw=drag.yaw+dx*.006;const lo=active==='wet'?.015:-1.2,hi=active==='wet'?2.5:1.2;states[active].pitch=Math.max(lo,Math.min(hi,drag.pitch+dy*.005));}dirty=true;});
for(const ev of ['pointerup','pointercancel'])view.addEventListener(ev,e=>{pointers.delete(e.pointerId);drag=null;pinch=0;update();});view.addEventListener('dblclick',()=>{Object.assign(inspect[active][side],{zoom:1,pan:[0,0]});layout();});view.addEventListener('contextmenu',e=>e.preventDefault());}
function action(side,act){const v=inspect[active][side];if(act==='in')zoom(side,1.25);if(act==='out')zoom(side,.8);if(act==='reset'){v.zoom=1;v.pan=[0,0];}if(act==='close'){v.hidden=true;if(side==='teacher')$('teacherVideo').pause();}if(act==='focus'){v.hidden=false;inspect[active][side==='teacher'?'result':'teacher'].hidden=true;}layout();}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.side,b.dataset.action));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>selectCase(b.dataset.go));window.addEventListener('popstate',()=>selectCase(new URLSearchParams(location.search).get('case')||'home',false));
$('showTeacher').onclick=()=>{inspect[active].teacher.hidden=!inspect[active].teacher.hidden;layout();};$('showResult').onclick=()=>{inspect[active].result.hidden=!inspect[active].result.hidden;layout();};$('restoreWindows').onclick=()=>{inspect[active].teacher.hidden=false;inspect[active].result.hidden=false;layout();};$('focusResult').onclick=()=>action('result','focus');$('rotate').onclick=()=>{running=!running;$('rotate').textContent=running?'暂停旋转':'开始旋转';};$('homeCamera').onclick=()=>{const s=states[active],p=initial[active];s.yaw=p.yaw;s.pitch=p.pitch;for(const side of ['teacher','result'])Object.assign(inspect[active][side],{zoom:1,pan:[0,0]});running=false;update();};$('channel').onchange=e=>{states[active].view=+e.target.value;states[active].baseline=false;update();};$('lighting').onchange=e=>{states.wet.pbr=e.target.value==='pbr'?1:0;states.wet.baseline=false;update();};$('resetMaterial').onclick=()=>{states[active]=clone(initial[active]);update();};$('baselineButton').onclick=()=>{states.wet.baseline=true;states.wet.view=0;update();};
function save(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function getScore(){return {schema:'kaopu.stone-viewer/2',case:active,parameters:clone(states[active]),inspection:clone(inspect[active]),teacherSHA256:active==='wet'?sources.wetHash:sources.iqHash,status:active==='smooth'?'REFERENCE_APPEARANCE_STUDY_NOT_PIXEL_VERIFIED':'INHERITED_BASELINE_WITH_VIEW_CONTROLS'};}
function setScore(o){if(o.schema!=='kaopu.stone-viewer/2'||!meta[o.case])throw Error('参数文件版本或案例无效');const id=o.case,s=o.parameters;if(o.teacherSHA256!==(id==='wet'?sources.wetHash:sources.iqHash))throw Error('老师源码指纹不匹配');for(const key of Object.keys(initial[id])){if(typeof initial[id][key]==='number'&&!Number.isFinite(s[key]))throw Error('参数无效 '+key);}for(const[k,,lo,hi]of ranges[id])if(s[k]<lo||s[k]>hi)throw Error('参数越界 '+k);if(s.view<0||s.view>(id==='wet'?6:2)||!Number.isInteger(s.view)||Math.abs(s.yaw)>10000||Math.abs(s.pitch)>3.15)throw Error('观察参数越界');if(id==='wet'&&(!Number.isInteger(s.palette)||s.palette<0||s.palette>9||![0,1].includes(s.pbr)))throw Error('配色 / 光照参数无效');if(id!=='wet'&&(![0,1,2].includes(s.method)||!Number.isInteger(s.planes)))throw Error('函数参数无效');for(const side of ['teacher','result']){const v=o.inspection?.[side];if(!v||!Number.isFinite(v.zoom)||v.zoom<.35||v.zoom>5||!Array.isArray(v.pan)||v.pan.length!==2||v.pan.some(x=>!Number.isFinite(x)||Math.abs(x)>100)||typeof v.hidden!=='boolean')throw Error('窗口参数无效');}states[id]=clone(s);inspect[id]=clone(o.inspection);selectCase(id);}
$('export').onclick=()=>save('KAOPU_'+active+'_R06.json',new Blob([JSON.stringify(getScore(),null,2)],{type:'application/json'}));$('import').onclick=()=>$('scoreFile').click();$('scoreFile').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>100000)throw Error('参数文件过大或为空');setScore(JSON.parse(await f.text()));}catch(err){fail(err);}finally{e.target.value='';}};$('capture').onclick=()=>{inspect[active].result.hidden=false;draw();$('resultCanvas').toBlob(b=>{if(b)save('KAOPU_'+active+'_R06.png',b);});};
$('loadTeacher').onclick=$('loadVideoEmpty').onclick=()=>$('teacherFile').click();$('teacherFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const id=active,type=f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':null;if(!type){fail(Error('请选择原图片或原视频'));return;}if(media[id]?.url)URL.revokeObjectURL(media[id].url);media[id]={type,url:URL.createObjectURL(f),name:f.name};inspect[id].teacher.hidden=false;updateMedia();layout();e.target.value='';};$('teacherLive').onclick=()=>{if(media[active]?.url)URL.revokeObjectURL(media[active].url);delete media[active];updateMedia();layout();};
function tick(t){if(ready){if(running&&!inspect[active].result.hidden){const dt=Math.min((t-last)/1000,.1);if(active==='wet')states[active].yaw+=dt*.16;else states[active].time+=dt*8;dirty=true;}if(dirty)draw();}last=t;requestAnimationFrame(tick);}
try{const wetURL=new URL('kaopu-wet-stone-material-workbench/r04-20261002/',REPO);[sources.teacher,sources.material,sources.iq]=await Promise.all([read(new URL('teacher.frag',wetURL)),read(new URL('material.glsl',wetURL)),read(new URL('iq-teacher.txt',ROOT))]);sources.wetHash=await sha(sources.teacher);sources.iqHash=await sha(sources.iq);if(sources.wetHash!=='unavailable'&&sources.wetHash!=='f03a5c354f54bef8d9c7d3e9b1b406e34e8a93759e592fb4d30ef1558a09e4db')throw Error('湿石老师基线指纹变化，停止运行');const entry='void main(){mainImage(outColor,gl_FragCoord.xy);}';if(!sources.teacher.includes(entry))throw Error('旧老师入口未找到');programs.wetTeacher=sources.teacher;programs.wetMaterial=sources.teacher.replace(entry,'')+'\n'+sources.material;programs.iq=iqShader(sources.iq,false);programs.smooth=iqShader(sources.iq,true);renderers=[renderer($('teacherCanvas')),renderer($('resultCanvas'))];ready=true;window.KP6={ready:true,selectCase,getScore,setScore,states,inspect,draw,action,zoom,reset:()=>$('homeCamera').click(),pixels:side=>Array.from(renderers[side==='teacher'?0:1].pixels()),glErrors:()=>renderers.map(r=>r.gl.getError()),programs,sources,setResolution:w=>{for(const r of renderers){r.canvas.width=w;r.canvas.height=w*9/16;}dirty=true;}};const requested=new URLSearchParams(location.search).get('case')||'smooth';selectCase(requested==='home'?'smooth':requested,false);if(requested==='home')selectCase('home',false);$('status').textContent='R06 · 三个案例就绪 · 960 × 540';requestAnimationFrame(tick);let j=0;const ids=['wet','smooth','iq'];function nextThumb(){if(j<3){thumbnail(ids[j++]);draw();setTimeout(nextThumb,100);}else{window.KP6.thumbnailsReady=true;}}setTimeout(nextThumb,150);}catch(e){fail(e);}
})();
