import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';import {GNMHeadModel,parseContainer} from '../src/GNMModel.js';const refined=process.env.GROOM==='refined';const {HairLayer}=await import(refined?'../src/RefinedHairLayer.js':'../src/HairLayer.js');
const file=fs.readFileSync(new URL('../gnm_head_web.bin',import.meta.url)),sha=crypto.createHash('sha256').update(file).digest('hex');assert.equal(sha,'fd19f46eef6f8bfb725fceab581e1bc8837209997ca3fd43f3c1735003c86961');const data=parseContainer(file.buffer.slice(file.byteOffset,file.byteOffset+file.byteLength)),model=new GNMHeadModel(data.meta,data.sections),p=new Float32Array(model.numVertices*3);model.computeVertices(p);const original=crypto.createHash('sha256').update(p).digest('hex'),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setIndex(new THREE.BufferAttribute(model.triangles,1));g.computeVertexNormals();const start=performance.now(),hair=new HairLayer(model,p,g.attributes.normal.array,{count:18000,segments:18,seed:724,volume:.008,density:.95}),buildMs=performance.now()-start;
const bytes=()=>Object.values(hair.geometry.attributes).reduce((n,a)=>n+a.array.byteLength,0)+hair.geometry.index.array.byteLength;
const cases=[];for(const style of ['side-sweep','swept-back','short-crop','side-sweep']){hair.setAppearance({style});const d=hair.diagnostics();assert(d.finite);assert.equal(d.invalidTriangles,0);assert(d.maxSumError<1e-6);assert(d.maxRootSurfaceDistance<.00036);cases.push(d);}
const fullBytes=bytes(),fullDraw=hair.geometry.drawRange.count;hair.setAppearance({density:.2});assert.equal(bytes(),fullBytes);assert(hair.geometry.drawRange.count<fullDraw);const reducedDraw=hair.geometry.drawRange.count;hair.setAppearance({density:.95});assert.equal(hair.geometry.drawRange.count,fullDraw);assert.equal(cases[0].rootHash,cases[3].rootHash);assert.equal(crypto.createHash('sha256').update(p).digest('hex'),original);
const rotations=[];const per=hair.options.segments+1;
for(const angle of [0,Math.PI/2,Math.PI,-Math.PI/2]){const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),angle),pivot=new THREE.Vector3(0,.22,0),moved=p.slice(),v=new THREE.Vector3();for(let j=0;j<moved.length;j+=3)v.fromArray(p,j).sub(pivot).applyQuaternion(q).add(pivot).toArray(moved,j);let maxGap=0;for(let i=0;i<hair.options.count;i++){const b=hair.binding.rootBarycentrics.subarray(i*3,i*3+3),root=hair.binding.point(hair.binding.rootTriangles[i],b,moved),tip=v.fromArray(hair.latestPoints,i*per*3).sub(pivot).applyQuaternion(q).add(pivot);maxGap=Math.max(maxGap,tip.distanceTo(new THREE.Vector3(...root)));}assert(maxGap<.00036);rotations.push({angle,maxGap});}
const seen=new Set(),buffers=new Set();function memory(o){if(!o||typeof o!=='object'||seen.has(o))return;seen.add(o);if(ArrayBuffer.isView(o)){buffers.add(o.buffer);return;}if(o instanceof ArrayBuffer){buffers.add(o);return;}if(o instanceof Map){for(const [k,v]of o){memory(k);memory(v);}return;}if(o instanceof Set){for(const v of o)memory(v);return;}for(const v of Object.values(o))memory(v);}memory({model,hair,g,p,data});const reachableTypedArrayBytes=[...buffers].reduce((n,b)=>n+b.byteLength,0);
const output={rotations,reachableTypedArrayBytes,passed:true,assetSha256:sha,modelVertices:model.numVertices,buildMs,cases,geometryBytesWithoutRadius:fullBytes,geometryBytesWithRadius:fullBytes+hair.geometry.attributes.along.count*4,density:{fullDraw,reducedDraw,sameAllocation:true},limits:['Node geometry tests do not validate shader compilation, pixels, GPU budget, body collision or physics.','Root surface distance includes the existing clearance policy.','Head pose UI is rigid local-frame following, not physical simulation.']};fs.writeFileSync(new URL(refined?'../evidence/geometry-refined.json':'../evidence/geometry.json',import.meta.url),JSON.stringify(output,null,2));console.log(JSON.stringify({passed:true,buildMs,fullBytes,rootGap:cases[0].maxRootSurfaceDistance,active:cases[0].activeCount}));hair.dispose();
