(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('featherCanvas');
const defaults=Object.freeze({seed:1247,width:1,asymmetry:.22,bend:.13,twist:.12,density:1,separation:.48,down:.68,roughness:.48,wind:.45,tone:'graphite',view:'beauty',showBarbules:true,showDown:true});
let state={...defaults},camera={yaw:.12,pitch:.035,zoom:1},running=false,hostActive=true,active=true,disposed=false,contextLost=false,ready=false,t=0,last=0,raf=0,frames=0,fps=0,lastFps=0,frameCounter=0;
const errors=[],events=new AbortController(),gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
function emit(type,detail={}){const data={kaopuFeather:true,type,...detail};if(parent!==window)parent.postMessage(data,location.origin==='null'?'*':location.origin);window.dispatchEvent(new CustomEvent('feather:'+type,{detail:data}));}
function fail(message){ready=false;errors.push(message);$('error').hidden=false;$('error').textContent=message;$('status').textContent='画面未能启动';emit('error',{message});}
if(!gl){fail('此设备未能建立 WebGL 2，请使用支持 WebGL 2 的浏览器');return;}
const deform=`uniform float uBend,uTwist,uTime,uWind;vec3 deform(vec3 p){float s=clamp((p.y+1.70)/3.4,0.,1.);float a=uTwist*(s-.25)+uWind*.20*sin(uTime*1.8-s*3.)*s;float x=p.x*cos(a)-p.z*sin(a),z=p.x*sin(a)+p.z*cos(a);float q=s*s;return vec3(x+uBend*q*.66+uWind*.045*sin(uTime*1.4-s*2.)*q,p.y,z+uBend*q*.34+uWind*.15*sin(uTime*1.7-s*3.1)*q+uWind*.055*sin(uTime*2.7+p.y*5.+p.x*3.)*abs(p.x));}`;
const VS=`#version 300 es
precision highp float;precision highp int;
layout(location=0)in vec3 aP0;layout(location=1)in vec3 aP1;layout(location=2)in vec3 aP2;layout(location=3)in vec3 aP3;layout(location=4)in vec4 aMeta;
uniform mat4 uVP;uniform vec3 uEye;uniform float uPixel;uniform int uSegments,uView;
${deform}
out vec3 vP,vTangent,vView,vSide;out float vAcross,vRand,vCover,vS,vKind,vAlong;
vec3 curve(float s){float q=1.-s;return deform(q*q*q*aP0+3.*q*q*s*aP1+3.*q*s*s*aP2+s*s*s*aP3);}
void main(){float s=float(gl_VertexID/2)/float(uSegments),side=gl_VertexID%2==1?1.:-1.;vec3 p=curve(s),T=normalize(curve(min(1.,s+.005))-curve(max(0.,s-.005))),V=normalize(uEye-p),R=normalize(cross(T,V));float taper=aMeta.y<1.5?.62:.16;float rad=aMeta.x*mix(1.,taper,pow(s,4.));if(uView==1)rad*=1.5;float minR=uPixel*.5,displayR=max(rad,minR);vCover=min(1.,rad/minR);vAcross=side;vTangent=T;vSide=R;vView=V;vP=p;vRand=aMeta.z;vS=s;vKind=aMeta.y;vAlong=aMeta.w;gl_Position=uVP*vec4(p+R*side*displayR,1.);}`;
const FS=`#version 300 es
precision highp float;precision highp int;
in vec3 vP,vTangent,vView,vSide;in float vAcross,vRand,vCover,vS,vKind,vAlong;uniform vec3 uColor;uniform float uRoughness;uniform int uView,uMSAA;out vec4 outColor;
void main(){float alpha=(1.-smoothstep(.68,1.,abs(vAcross)))*vCover;if(alpha<.002)discard;vec3 T=normalize(vTangent),V=normalize(vView),L=normalize(vec3(-.7,1.1,1.6)),B=normalize(vec3(1.2,.2,-1.6));float diff=sqrt(max(0.,1.-pow(dot(T,L),2.))),ht=dot(T,normalize(L+V)),spec=pow(max(0.,1.-ht*ht),mix(110.,18.,uRoughness));float highlight=.55+.45*sin(vAlong*17.+vRand*.13);float edge=(vKind<1.5?smoothstep(.82,1.,vS):0.);vec3 base=uColor*(.72+.38*vRand);base=mix(base,vec3(.25,.24,.21),edge*.22);if(vKind>2.5)base=vec3(.53,.52,.45)*(.75+.28*vRand);float shading=.56+.34*diff+.10*max(0.,V.z);vec3 col=base*shading+vec3(.35,.33,.28)*spec*(.12+.12*highlight)+base*.16*pow(max(0.,1.-pow(dot(T,normalize(B+V)),2.)),30.);if(uView==2){col=(vKind<1.5?vec3(.13,.42,.29):vKind<2.5?vec3(.16,.35,.60):vec3(.51,.27,.35))*(.65+.35*diff);}if(uView==1)col=vec3(.12,.22,.18)*(.60+.4*diff);col=pow(max(col,vec3(0.)),vec3(1./2.2));float d=fract(52.9829189*fract(dot(gl_FragCoord.xy+vec2(vRand*913.),vec2(.06711056,.00583715))));if(uMSAA==0){if(alpha<d)discard;alpha=1.;}else{alpha=floor(alpha*float(uMSAA)+d)/float(uMSAA);if(alpha<=0.)discard;}outColor=vec4(col,alpha);}`;
const MVS=`#version 300 es
precision highp float;layout(location=0)in vec3 aP;layout(location=1)in vec3 aN;uniform mat4 uVP;${deform}
out vec3 P,N;void main(){P=deform(aP);vec3 n=normalize(aN),axis=abs(n.y)<.8?vec3(0.,1.,0.):vec3(1.,0.,0.);vec3 tu=normalize(cross(axis,n)),tv=cross(n,tu);vec3 du=deform(aP+tu*.001)-deform(aP-tu*.001),dv=deform(aP+tv*.001)-deform(aP-tv*.001);N=normalize(cross(du,dv));gl_Position=uVP*vec4(P,1.);}`;
const MFS=`#version 300 es
precision highp float;in vec3 P,N;uniform vec3 uEye;uniform int uView;out vec4 outColor;void main(){vec3 n=normalize(N),v=normalize(uEye-P),l=normalize(vec3(-.8,1.3,1.7));float d=max(0.,dot(n,l)),spec=pow(max(0.,dot(n,normalize(l+v))),58.);vec3 base=uView==2?vec3(.65,.43,.12):vec3(.48,.44,.33);vec3 c=base*(.45+.55*d)+vec3(.25)*spec;outColor=vec4(pow(c,vec3(1./2.2)),1.);}`;
const BVS=`#version 300 es
precision highp float;out vec2 uv;void main(){vec2 p=vec2(gl_VertexID==1?3.:-1.,gl_VertexID==2?3.:-1.);uv=p*.5+.5;gl_Position=vec4(p,1.,1.);}`;
const BFS=`#version 300 es
precision highp float;in vec2 uv;out vec4 col;void main(){float vignette=length((uv-vec2(.46,.58))*vec2(.8,.65));vec3 c=mix(vec3(.90,.89,.85),vec3(.61,.65,.60),smoothstep(.06,.68,vignette));col=vec4(c,1.);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function program(v,f){const p=gl.createProgram(),a=shader(gl.VERTEX_SHADER,v),b=shader(gl.FRAGMENT_SHADER,f);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);gl.deleteShader(a);gl.deleteShader(b);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
let hair,mesh,bg;try{hair=program(VS,FS);mesh=program(MVS,MFS);bg=program(BVS,BFS);}catch(e){fail('着色程序编译失败：'+e.message);return;}
function uniforms(p,names){return Object.fromEntries(names.split(' ').map(x=>[x,gl.getUniformLocation(p,x)]));}
const H=uniforms(hair,'uVP uEye uBend uTwist uTime uWind uPixel uSegments uView uColor uRoughness uMSAA'),M=uniforms(mesh,'uVP uEye uBend uTwist uTime uWind uView'),samples=gl.getParameter(gl.SAMPLES),emptyVAO=gl.createVertexArray();
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const d=Math.hypot(...a)||1;return a.map(x=>x/d);},dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),sub=(a,b)=>a.map((x,i)=>x-b[i]),add=(a,b)=>a.map((x,i)=>x+b[i]),mul=(a,b)=>a.map(x=>x*b),mix=(a,b,t)=>a.map((x,i)=>x*(1-t)+b[i]*t),clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
function rng(seed){let n=seed>>>0;return ()=>{n+=0x6D2B79F5;let a=n;a=Math.imul(a^(a>>>15),a|1);a^=a+Math.imul(a^(a>>>7),a|61);return ((a^(a>>>14))>>>0)/4294967296;};}
function bez(c,s){const q=1-s;return c[0].map((v,i)=>q*q*q*v+3*q*q*s*c[1][i]+3*q*s*s*c[2][i]+s*s*s*c[3][i]);}
function shaft(u){return [.045*Math.sin(u*3.1)*u,-1.7+3.4*u,.027*Math.sin(u*5.4)];}
const hairVAO=gl.createVertexArray(),curveBuffer=gl.createBuffer(),meshVAO=gl.createVertexArray(),meshBuffer=gl.createBuffer(),meshIndex=gl.createBuffer();let batches=[],curveCount=0,meshIndices=0,geometryRevision=0,curveData=new Float32Array();
function makeGeometry(){const r=rng(state.seed),curves=[[],[],[]];function curve(c,w,kind,rand,along){curves[kind-1].push(...c.flat(),w,kind,rand,along);}
 const n=Math.round(420*state.density);for(const side of [-1,1])for(let i=0;i<n;i++){
 const u=Math.min(.9996,.16+.8395*(i+.28*r())/(n-1)),s=(u-.16)/.8395,root=shaft(u);const envelope=Math.pow(Math.sin(Math.PI*clamp(s,0,1)),.69)*(.97-.18*s);const spread=.68*state.width*envelope*(side<0?1-state.asymmetry:1+state.asymmetry*.34);const clump=Math.sin(s*36+side*1.7)*.55+Math.sin(s*71+side)*.25;const cuts=side<0?[.23,.61,.84]:[.37,.72,.91];const splits=.80*Math.exp(-Math.pow((s-cuts[0])/.010,2))+.55*Math.exp(-Math.pow((s-cuts[1])/.015,2))+.35*Math.exp(-Math.pow((s-cuts[2])/.008,2));const rise=(.22+.24*(1-s))*envelope+state.separation*clump*.045;let reach=spread*(1-state.separation*splits*.10);const z=.065*Math.sin(s*6+side*.7)+.0015*Math.sin(s*81+side+state.seed*.01);const tip=add(root,[side*reach,rise,z]);const c=[root,add(root,[side*reach*.29,rise*.53,z*.20]),add(root,[side*reach*.76,rise*.89+.0025*Math.sin(s*58+side+state.seed*.013),z*.72]),tip];
 curve(c,.00435*(.88+.24*r()),1,r(),u);
 const steps=Math.round(14+8*spread);for(let j=1;j<steps;j++){const q=(j+(r()-.5)*.84)/steps,p=bez(c,q),ta=norm(sub(bez(c,Math.min(1,q+.01)),bez(c,q-.01)));for(const branch of [-1,1]){const len=(.009+.008*r())*(1-q*.32),v=[side*(.12+.25*r())*len,branch*len,.001*Math.sin(j*.71+i)];const end=add(p,add(v,mul(ta,.009)));const c1=add(p,mul(v,.43)),c2=mix(c1,end,.64);curve([p,c1,c2,end],.00064*(.65+.6*r()),2,r(),u);}}
 }
 const dn=Math.round(150*state.down);for(let i=0;i<dn;i++){const side=r()<.5?-1:1,u=.085+r()*.22,p=shaft(u),len=(.15+r()*.35)*state.down,phase=r()*6.28,end=add(p,[side*len*(.6+.4*r()),(.16+r()*.20)*len,.035*Math.sin(phase)]),c=[p,add(p,[side*len*.20,len*.44,.016]),add(p,[side*len*.73,len*.60,.035*Math.cos(phase)]),end];curve(c,.00105,3,r(),u);for(let j=2;j<9;j++){const q=j/10,root=bez(c,q),tip=add(root,[side*(.02+r()*.048),.019+r()*.055,.02*(r()-.5)]);curve([root,mix(root,tip,.3),add(mix(root,tip,.7),[0,.012,0]),tip],.00070,3,r(),u);}}
 let off=0;const all=[];batches=[];curves.forEach((data,i)=>{batches.push({kind:i+1,offset:off,count:data.length/16,segments:i===0?18:i===1?3:10});off+=data.length/16;for(const v of data)all.push(v);});curveCount=off;curveData=new Float32Array(all);gl.bindVertexArray(hairVAO);gl.bindBuffer(gl.ARRAY_BUFFER,curveBuffer);gl.bufferData(gl.ARRAY_BUFFER,curveData,gl.STATIC_DRAW);for(let k=0;k<5;k++){gl.enableVertexAttribArray(k);gl.vertexAttribPointer(k,k===4?4:3,gl.FLOAT,false,64,k===4?48:k*12);gl.vertexAttribDivisor(k,1);}
 const verts=[],idx=[],rings=120,sides=10;for(let j=0;j<=rings;j++){const u=j/rings,p=shaft(u),tan=norm(sub(shaft(Math.min(1,u+.001)),shaft(Math.max(0,u-.001)))),a=norm(cross(tan,[0,0,1])),b=cross(tan,a),rad=.0132*Math.pow(1-u,.80)+.00045;for(let k=0;k<=sides;k++){const angle=k/sides*Math.PI*2,normVec=add(mul(a,Math.cos(angle)),mul(b,Math.sin(angle)));verts.push(...add(p,mul(normVec,rad)),...normVec);}}for(let j=0;j<rings;j++)for(let k=0;k<sides;k++){const a=j*(sides+1)+k,b=a+sides+1;idx.push(a,b,a+1,a+1,b,b+1);}meshIndices=idx.length;gl.bindVertexArray(meshVAO);gl.bindBuffer(gl.ARRAY_BUFFER,meshBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);for(let k=0;k<2;k++){gl.enableVertexAttribArray(k);gl.vertexAttribPointer(k,3,gl.FLOAT,false,24,k*12);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,meshIndex);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(idx),gl.STATIC_DRAW);geometryRevision++;
}
makeGeometry();
function multiply(a,b){const c=new Float32Array(16);for(let col=0;col<4;col++)for(let row=0;row<4;row++)for(let k=0;k<4;k++)c[col*4+row]+=a[k*4+row]*b[col*4+k];return c;}
function matrices(){const aspect=canvas.width/canvas.height;let half=1.92/camera.zoom;if(aspect<.65)half*=.65/aspect;const target=[.04,0,0],e=[target[0]+Math.sin(camera.yaw)*Math.cos(camera.pitch)*7,Math.sin(camera.pitch)*7,Math.cos(camera.yaw)*Math.cos(camera.pitch)*7],z=norm(sub(e,target)),x=norm(cross([0,1,0],z)),y=cross(z,x),view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]),proj=new Float32Array([1/(half*aspect),0,0,0,0,1/half,0,0,0,0,-2/30,0,0,0,-1,1]);return {vp:multiply(proj,view),eye:e,pixel:half*2/canvas.height};}
function deformUniforms(U,m){gl.uniformMatrix4fv(U.uVP,false,m.vp);gl.uniform3fv(U.uEye,m.eye);gl.uniform1f(U.uBend,state.bend);gl.uniform1f(U.uTwist,state.twist);gl.uniform1f(U.uTime,t);gl.uniform1f(U.uWind,t===0?0:state.wind);gl.uniform1i(U.uView,['beauty','barbs','structure'].indexOf(state.view));}
function draw(){if(!active||disposed||contextLost)return;gl.viewport(0,0,canvas.width,canvas.height);gl.bindVertexArray(emptyVAO);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.disable(gl.SAMPLE_ALPHA_TO_COVERAGE);gl.useProgram(bg);gl.drawArrays(gl.TRIANGLES,0,3);gl.depthMask(true);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);const m=matrices();gl.useProgram(mesh);gl.bindVertexArray(meshVAO);deformUniforms(M,m);gl.drawElements(gl.TRIANGLES,meshIndices,gl.UNSIGNED_SHORT,0);gl.useProgram(hair);gl.bindVertexArray(hairVAO);gl.bindBuffer(gl.ARRAY_BUFFER,curveBuffer);deformUniforms(H,m);if(samples>0)gl.enable(gl.SAMPLE_ALPHA_TO_COVERAGE);gl.uniform1f(H.uPixel,m.pixel);gl.uniform1f(H.uRoughness,state.roughness);gl.uniform1i(H.uMSAA,samples);gl.uniform3fv(H.uColor,{graphite:[.066,.061,.052],ivory:[.62,.59,.48],copper:[.20,.092,.038]}[state.tone]);let shown=0;for(const b of batches){if(b.kind===2&&(!state.showBarbules||state.view==='barbs')||b.kind===3&&!state.showDown)continue;for(let k=0;k<5;k++)gl.vertexAttribPointer(k,k===4?4:3,gl.FLOAT,false,64,b.offset*64+(k===4?48:k*12));gl.uniform1i(H.uSegments,b.segments);gl.drawArraysInstanced(gl.TRIANGLE_STRIP,0,(b.segments+1)*2,b.count);shown+=b.count;}gl.disable(gl.SAMPLE_ALPHA_TO_COVERAGE);frames++;$('count').textContent=shown.toLocaleString()+' 条曲线';}
function resize(){if(disposed)return;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(w!==canvas.width||h!==canvas.height){canvas.width=w;canvas.height=h;}draw();}
function loop(now){raf=0;if(!active||disposed||!running)return;if(last)t+=Math.min(.1,(now-last)/1000);else if(t===0)t=.001;last=now;draw();frameCounter++;if(now-lastFps>1000){fps=Math.round(frameCounter*1000/(now-lastFps));lastFps=now;frameCounter=0;$('fps').textContent=fps+' FPS';}raf=requestAnimationFrame(loop);}
function schedule(){if(active&&running&&!disposed&&!contextLost&&!raf){last=0;lastFps=performance.now();frameCounter=0;raf=requestAnimationFrame(loop);}}
function stop(){if(raf)cancelAnimationFrame(raf);raf=0;last=0;}
function pause(){if(disposed)return;hostActive=false;active=false;stop();emit('paused');}
function resume(){if(disposed||contextLost)return;hostActive=true;active=!document.hidden;resize();schedule();emit('resumed');}
const ranges={seed:[1,1e7],width:[.65,1.4],asymmetry:[0,.55],bend:[-.5,.5],twist:[-.8,.8],density:[.6,1.3],separation:[0,1],down:[0,1],roughness:[.18,.8],wind:[0,1]},flags=['showBarbules','showDown'];
function updateUI(){for(const k of Object.keys(ranges).filter(k=>k!=='seed')){$(k).value=state[k];$(k+'Out').textContent=Number(state[k]).toFixed(2);}$('tone').value=state.tone;for(const k of flags)$(k).checked=state[k];document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));$('beautyLabel').textContent={beauty:'成稿 · 细羽枝受光',barbs:'羽枝 · 隐去细羽枝观察支撑曲线',structure:'结构 · 羽轴 / 羽枝 / 细羽枝 / 绒羽'}[state.view];$('seed').textContent=state.seed;$('play').textContent=running?'暂停风动':'播放风动';if(!running)$('fps').textContent='静态';}
function validState(s){if(!s||typeof s!=='object')throw Error('参数文件不完整');for(const[k,[a,b]]of Object.entries(ranges))if(!Number.isFinite(s[k])||s[k]<a||s[k]>b)throw Error('无效参数：'+k);if(!Number.isInteger(s.seed))throw Error('种子必须为整数');if(!['graphite','ivory','copper'].includes(s.tone)||!['beauty','barbs','structure'].includes(s.view))throw Error('无效视图或颜色');for(const k of flags)if(typeof s[k]!=='boolean')throw Error('无效显示设置');}
function set(p){if(disposed)return;const next={...state,...p};validState(next);const rebuild=['seed','width','asymmetry','density','separation','down'].some(k=>next[k]!==state[k]);state=next;if(rebuild)makeGeometry();updateUI();draw();}
function reset(){if(disposed)return;stop();state={...defaults};camera={yaw:.12,pitch:.035,zoom:1};t=0;running=false;makeGeometry();updateUI();resize();emit('reset');}
function exportState(){return {format:'kaopu-feather-study',version:1,instrument:'rachis-barbs-barbules',state:{...state},camera:{...camera},time:t,running};}
function importState(data){if(disposed)throw Error('模块已释放');if(data?.format!=='kaopu-feather-study'||data.version!==1)throw Error('请选择本模块导出的参数文件');validState(data.state);const c=data.camera;if(!c||!Number.isFinite(c.yaw)||Math.abs(c.yaw)>Math.PI||!Number.isFinite(c.pitch)||Math.abs(c.pitch)>1.1||!Number.isFinite(c.zoom)||c.zoom<.65||c.zoom>2.8||!Number.isFinite(data.time)||data.time<0||data.time>1e7||typeof data.running!=='boolean')throw Error('无效相机或时间参数');stop();state={...data.state};camera={...c};t=data.time;running=data.running;makeGeometry();updateUI();resize();schedule();emit('imported');return exportState();}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
for(const k of Object.keys(ranges).filter(k=>k!=='seed'))$(k).addEventListener('input',e=>set({[k]:+e.target.value}),{signal:events.signal});for(const k of flags)$(k).onchange=e=>set({[k]:e.target.checked});$('tone').onchange=e=>set({tone:e.target.value});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>set({view:b.dataset.view}));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const presets={flight:{width:1,asymmetry:.22,separation:.48,down:.68},contour:{width:1.4,asymmetry:.02,separation:.20,down:.8},downy:{width:.78,asymmetry:.08,separation:.85,down:1}};set(presets[b.dataset.preset]);});
$('play').onclick=()=>{running=!running;if(running)schedule();else stop();updateUI();draw();};$('reset').onclick=reset;$('resetCamera').onclick=()=>{camera={yaw:.12,pitch:.035,zoom:1};draw();};for(const[id,yaw]of [['front',0],['profile',Math.PI*.42],['back',Math.PI]])$(id).onclick=()=>{camera={yaw,pitch:.035,zoom:1};draw();};$('macro').onclick=()=>{camera={yaw:.26,pitch:.11,zoom:2.6};draw();};
$('export').onclick=()=>download(new Blob([JSON.stringify(exportState(),null,2)],{type:'application/json'}),'KAOPU-羽毛参数.json');$('capture').onclick=()=>{draw();canvas.toBlob(b=>{if(b)download(b,'KAOPU-羽毛.png');});};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>50000)throw Error('文件过大');importState(JSON.parse(await f.text()));$('notice').textContent='参数已恢复';}catch(err){$('notice').textContent=err.message;}e.target.value='';};$('reseed').onclick=()=>set({seed:(((state.seed*1664525+1013904223)>>>0)%1000000)+1});
const pointers=new Map();let pinch=0;canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);pinch=0;};canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(pinch)camera.zoom=clamp(camera.zoom*d/pinch,.65,2.8);pinch=d;}else{camera.yaw=clamp(camera.yaw+(e.clientX-old[0])*.006,-Math.PI,Math.PI);camera.pitch=clamp(camera.pitch+(e.clientY-old[1])*.004,-1.1,1.1);}draw();};function endPointer(e){pointers.delete(e.pointerId);pinch=0;}canvas.onpointerup=endPointer;canvas.onpointercancel=endPointer;canvas.onlostpointercapture=endPointer;canvas.onwheel=e=>{e.preventDefault();camera.zoom=clamp(camera.zoom*Math.exp(-e.deltaY*.001),.65,2.8);draw();};
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(disposed)return;contextLost=true;stop();active=false;fail('图形上下文暂时中断，请重新打开此模块');},{signal:events.signal});const observer=new ResizeObserver(resize);observer.observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.hidden){active=false;stop();}else if(hostActive&&!contextLost){active=true;resize();schedule();}},{signal:events.signal});
function dispose(){if(disposed)return;stop();hostActive=false;active=false;disposed=true;observer.disconnect();events.abort();for(const el of [canvas,...document.querySelectorAll('button,input,select')])for(const n of ['onclick','onchange','onpointerdown','onpointermove','onpointerup','onpointercancel','onlostpointercapture','onwheel'])el[n]=null;pointers.clear();for(const p of [hair,mesh,bg])gl.deleteProgram(p);for(const b of [curveBuffer,meshBuffer,meshIndex])gl.deleteBuffer(b);for(const v of [meshVAO,hairVAO,emptyVAO])gl.deleteVertexArray(v);emit('disposed');}
window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin||!e.data?.kaopuFeather)return;const d=e.data;try{if(d.type==='pause')pause();else if(d.type==='resume')resume();else if(d.type==='resize')resize();else if(d.type==='reset')reset();else if(d.type==='dispose')dispose();else if(d.type==='export')emit('state',{requestId:d.requestId,data:exportState()});else if(d.type==='import'){importState(d.data);emit('state',{requestId:d.requestId,data:exportState()});}}catch(err){emit('error',{requestId:d.requestId,message:err.message});}},{signal:events.signal});
window.FeatherStudy={pause,resume,resize,dispose,reset,exportState,importState,set,diagnostics(){const bytes=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,bytes);let hash=2166136261,darkPixels=0;for(let i=0;i<bytes.length;i+=4){hash=Math.imul(hash^bytes[i],16777619)>>>0;if(bytes[i]<125)darkPixels++;}return {glError:gl.getError(),hash,darkPixels,samples,curveCount,batches:batches.map(b=>({...b})),rachisTriangles:meshIndices/3,geometryRevision,finiteGeometry:curveData.every(Number.isFinite)};},get ready(){return ready;},get errors(){return [...errors];},get stats(){return {frames,fps,active,running,raf,disposed,width:canvas.width,height:canvas.height,curveCount,geometryRevision};},renderAt(time){if(disposed)throw Error('模块已释放');if(!Number.isFinite(time)||time<0||time>1e7)throw RangeError('时间超出有效范围');t=time;draw();}};
updateUI();ready=true;resize();$('status').textContent='原创三维羽毛 · WebGL 2';emit('ready',{version:1,capabilities:['pause','resume','resize','dispose','reset','export','import']});
})();
