/* Generic private shader runner. Original shader and texture are not hosted here. */
(()=>{'use strict';
const VERSION='haiyu-radial-r01',PATCH='reentry-cleanup-20261005',EXPECTED={"sourceBytes":3957,"sourceSha256":"27eecc41c69b28e4b3e4ad429d26869d8dd572c68c14ec979df1972695285ca0","textureBytes":87562,"textureSha256":"81c28c65b034a4cd924f4254d82d7fe1ba451c8a7c735dc9da73ee782bd885ac","textureURL":"https://raw.githubusercontent.com/Acry/Shade-it-/788a824005feb5a7deb2e32e973a7f03fb32879e/assets/textures/e6e5631ce1237ae4c05b3563eda686400a401df4548d0f9fad40ecac1659c46c.jpg"},TAU4=4*Math.PI,$=id=>document.getElementById(id);
const vertex='#version 300 es\nprecision highp float;const vec2 P[3]=vec2[3](vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));void main(){gl_Position=vec4(P[gl_VertexID],0.,1.);}';
const header='#version 300 es\nprecision highp float;precision highp int;uniform vec3 iResolution;uniform float iTime;uniform sampler2D iChannel0;out vec4 outputColor;\n';
const observeHeader='uniform vec2 uOrbit;uniform float uZoom;uniform int uInspect;vec3 inspectCamera(vec3 p){float co=cos(uOrbit.x),si=sin(uOrbit.x);p.xz=mat2(co,-si,si,co)*p.xz;co=cos(uOrbit.y);si=sin(uOrbit.y);p.yz=mat2(co,-si,si,co)*p.yz;return p;}\n';
const teacherTail='\nvoid main(){mainImage(outputColor,gl_FragCoord.xy);}';
const observeTail='\nvoid main(){vec2 p=gl_FragCoord.xy;if(uZoom!=1.0)p=(p-iResolution.xy*.5)/uZoom+iResolution.xy*.5;mainImage(outputColor,p);}';
const injection='    if(uInspect!=0){ro=inspectCamera(ro);ta=inspectCamera(ta);}\n';
const S={version:VERSION,patch:PATCH,case:'teacher-radial',sourceBytesVerified:false,textureBytesVerified:false,ready:false,draws:0,gpuCompleted:0,error:null,time:0,playing:false,yaw:0,pitch:0,zoom:1,reference:true,quality:'960',sourceHash:null,textureHash:null,teacherOriginalUnmodified:true,neutralUsesUnmodifiedProgram:true,observation:'camera and framing only',storage:'none',browserGPUVerified:false};
let views=[],source='',textureImage=null,frameRequest=0,lastWall=0,dirty=true,packed='',loadGeneration=0;
const cacheKey=()=>VERSION+':'+EXPECTED.sourceSha256+':'+EXPECTED.textureSha256;
function report(){$('diagnostics').textContent=JSON.stringify(S,null,2);$('viewer').dataset.ready=String(S.ready);$('viewer').dataset.version=VERSION;}
function ui(){$('play').textContent=S.playing?'暂停':'播放';$('play').disabled=!S.ready;$('time').value=S.time%TAU4;$('clock').textContent=S.time.toFixed(3)+' s';$('zoom').value=String(S.zoom);$('angles').textContent='水平 '+S.yaw.toFixed(0)+'° · 垂直 '+S.pitch.toFixed(0)+'°';const neutral=S.yaw===0&&S.pitch===0&&S.zoom===1;$('mode').textContent=neutral?'原版镜头':'观察镜头 · 原形态原色';$('original').setAttribute('aria-pressed',String(neutral));$('reference').setAttribute('aria-pressed',String(S.reference));report();}
function warn(s){$('warning').hidden=!s;$('warning').textContent=s;}
function stop(){S.playing=false;lastWall=0;if(frameRequest){cancelAnimationFrame(frameRequest);frameRequest=0;}ui();}
function fail(err){stop();destroy();for(const id of ['canvas','teacher'])$(id).style.visibility='hidden';S.ready=false;S.error=String(err?.message||err);$('status').textContent='未能实时绘制';$('error').textContent='原程序运行失败：'+S.error+'。没有用截图、录像或其它形状替代。';$('teacherError').textContent='原版基线未绘制：'+S.error;for(const id of ['mainPanel','teacherPanel'])$(id).classList.remove('ready');ui();}
function observeSource(raw){const mark=/(^[ \t]*vec3[ \t]+ww[ \t]*=[ \t]*normalize[ \t]*\([ \t]*ta[ \t]*-[ \t]*ro[ \t]*\))/gm;if([...raw.matchAll(mark)].length!==1)throw Error('原相机接点不唯一，未替换程序');return raw.replace(mark,injection+'$1');}
async function hash(data){const bytes=typeof data==='string'?new TextEncoder().encode(data):data;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');}
function from64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function verify(record){if(record?.schema!=='haiyu-private-radial/1'||typeof record.source!=='string')throw Error('私人载荷格式无效');if(new TextEncoder().encode(record.source).length!==EXPECTED.sourceBytes||await hash(record.source)!==EXPECTED.sourceSha256)throw Error('原码字节校验失败');if(record.texture?.sha256!==EXPECTED.textureSha256||record.texture?.bytes!==EXPECTED.textureBytes)throw Error('纹理身份不匹配');return record;}
async function unpack(value){if(value.length>220000)throw Error('私人载荷超长');if(!('DecompressionStream'in window))throw Error('浏览器不支持载荷解压');let b=value.replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';const stream=new Blob([from64(b)]).stream().pipeThrough(new DecompressionStream('gzip'));const text=await new Response(stream).text();if(text.length>180000)throw Error('解压载荷超长');return verify(JSON.parse(text));}
async function loadTexture(record){let data;if(record.texture.base64){data=from64(record.texture.base64);}else{if(record.texture.url!==EXPECTED.textureURL)throw Error('纹理来源不匹配');const response=await fetch(record.texture.url,{credentials:'omit',referrerPolicy:'no-referrer',cache:'force-cache'});if(!response.ok)throw Error('原纹理下载失败 HTTP '+response.status);data=new Uint8Array(await response.arrayBuffer());}if(data.byteLength!==EXPECTED.textureBytes||await hash(data)!==EXPECTED.textureSha256)throw Error('原纹理字节校验失败');const blob=new Blob([data],{type:'image/jpeg'}),url=URL.createObjectURL(blob);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('原纹理解码失败'));img.src=url;});if(img.naturalWidth!==512||img.naturalHeight!==512)throw Error('原纹理尺寸不匹配');return{img,base64:record.texture.base64||btoa(Array.from(data,x=>String.fromCharCode(x)).join(''))};}finally{URL.revokeObjectURL(url);}}
function compile(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const err=gl.getShaderInfoLog(s);gl.deleteShader(s);throw Error(err||'着色器编译失败');}return s;}
function make(canvas,student){let reason='';canvas.addEventListener('webglcontextcreationerror',e=>reason=e.statusMessage||'',{once:true});const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('浏览器未提供 WebGL2'+(reason?'：'+reason:''));
function build(inspect){const p=gl.createProgram();let v=null,f=null;try{v=compile(gl,gl.VERTEX_SHADER,vertex);f=compile(gl,gl.FRAGMENT_SHADER,header+(inspect?observeHeader+observeSource(source)+observeTail:source+teacherTail));gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'程序链接失败');const uniforms={};for(const name of ['iResolution','iTime','iChannel0','uOrbit','uInspect','uZoom'])uniforms[name]=gl.getUniformLocation(p,name);return{p,uniforms};}catch(err){gl.deleteProgram(p);throw err;}finally{if(v)gl.deleteShader(v);if(f)gl.deleteShader(f);}}
let original=null,observed=null,vao=null,texture=null;try{original=build(false);observed=student?build(true):null;vao=gl.createVertexArray();texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL,gl.NONE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,textureImage);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.generateMipmap(gl.TEXTURE_2D);return{gl,original,observed,vao,texture,canvas,student,fence:null};}catch(err){if(texture)gl.deleteTexture(texture);if(vao)gl.deleteVertexArray(vao);if(observed)gl.deleteProgram(observed.p);if(original)gl.deleteProgram(original.p);throw err;}}
function destroy(){for(const v of views){const gl=v.gl;if(v.fence)gl.deleteSync(v.fence);gl.deleteProgram(v.original.p);if(v.observed)gl.deleteProgram(v.observed.p);gl.deleteTexture(v.texture);gl.deleteVertexArray(v.vao);}views=[];}
function request(){if(!frameRequest&&!document.hidden&&!S.error&&views.length)frameRequest=requestAnimationFrame(tick);}
function gpuReady(){for(const v of views){if(!v.fence)continue;const r=v.gl.clientWaitSync(v.fence,0,0);if(r===v.gl.WAIT_FAILED)throw Error('GPU 同步失败');if(r===v.gl.TIMEOUT_EXPIRED)return false;v.gl.deleteSync(v.fence);v.fence=null;}if(S.draws>S.gpuCompleted){S.gpuCompleted=S.draws;S.ready=true;S.browserGPUVerified=true;for(const v of views)v.canvas.style.visibility='visible';$('mainPanel').classList.add('ready');if(S.reference)$('teacherPanel').classList.add('ready');$('status').textContent='原码与原纹理已校验 · 实时运行';$('frame').textContent='实绘帧 '+S.gpuCompleted;ui();}return true;}
function draw(){const rect=$('canvas').getBoundingClientRect();let w=S.quality==='native'?Math.round(rect.width*(devicePixelRatio||1)):Number(S.quality);let h=Math.round(w*9/16),limit=1;for(const v of views){const m=v.gl.getParameter(v.gl.MAX_VIEWPORT_DIMS);limit=Math.min(limit,m[0]/w,m[1]/h);}w=Math.max(1,Math.floor(w*limit));h=Math.max(1,Math.floor(h*limit));S.resolution=[w,h];for(const v of views){if(!v.student&&!S.reference)continue;const{gl,vao,canvas}=v;const useObservation=v.student&&(S.yaw!==0||S.pitch!==0||S.zoom!==1);const{p,uniforms:u}=useObservation?v.observed:v.original;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.useProgram(p);gl.bindVertexArray(vao);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,v.texture);gl.uniform1i(u.iChannel0,0);gl.uniform3f(u.iResolution,w,h,1);gl.uniform1f(u.iTime,S.time);if(useObservation){gl.uniform2f(u.uOrbit,S.yaw*Math.PI/180,S.pitch*Math.PI/180);gl.uniform1i(u.uInspect,S.yaw!==0||S.pitch!==0?1:0);gl.uniform1f(u.uZoom,S.zoom);}gl.drawArrays(gl.TRIANGLES,0,3);if(gl.getError()!==gl.NO_ERROR)throw Error('WebGL绘制错误');v.fence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);gl.flush();}S.draws++;$('resolution').textContent='WebGL2 · '+w+'×'+h;ui();}
function tick(ms){frameRequest=0;if(document.hidden||S.error)return;try{if(S.playing){if(lastWall)S.time+=(ms-lastWall)/1000;dirty=true;}lastWall=ms;if(gpuReady()&&dirty){dirty=false;draw();}if(S.playing||dirty||views.some(v=>v.fence))request();}catch(e){fail(e);}}
function inspect(yaw,pitch,zoom){S.yaw=((Number(yaw)+180)%360+360)%360-180;S.pitch=Math.max(-75,Math.min(75,Number(pitch)||0));S.zoom=Math.max(1,Math.min(4,Number(zoom)||1));dirty=true;ui();request();}
function seek(t){stop();S.time=Math.max(0,Number(t)||0);dirty=true;ui();request();}
function reference(value,equal=false){S.reference=value;$('teacherPanel').hidden=!value;$('grid').classList.toggle('focus',!value);$('grid').classList.toggle('equal',equal);dirty=true;ui();request();}
const on=(id,fn)=>$(id).addEventListener('click',fn),zooms=[1,1.5,2,3,4];
on('play',()=>{if(!S.ready)return;S.playing=!S.playing;lastWall=0;ui();request();});on('resetTime',()=>seek(0));$('time').oninput=e=>seek(e.target.value);$('quality').onchange=e=>{S.quality=e.target.value;dirty=true;request();};on('original',()=>inspect(0,0,1));for(const[id,y,p]of [['left',-15,0],['right',15,0],['up',0,15],['down',0,-15]])on(id,()=>inspect(S.yaw+y,S.pitch+p,S.zoom));on('zoomIn',()=>inspect(S.yaw,S.pitch,zooms.find(z=>z>S.zoom)||4));on('zoomOut',()=>inspect(S.yaw,S.pitch,[...zooms].reverse().find(z=>z<S.zoom)||1));$('zoom').onchange=e=>inspect(S.yaw,S.pitch,e.target.value);on('reference',()=>reference(!S.reference));on('focus',()=>reference(false));on('closeReference',()=>reference(false));on('equal',()=>reference(true,true));on('fullscreen',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('mainPanel').requestFullscreen();}catch(e){warn('未进入全屏：'+e.message);}});
const pointers=new Map();let drag=null,pinch=null;const canvas=$('canvas');canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,yaw:S.yaw,pitch:S.pitch};if(pointers.size===2){const[a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:S.zoom};}});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const[a,b]=[...pointers.values()];inspect(S.yaw,S.pitch,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance));}else if(pointers.size===1&&drag){const r=canvas.getBoundingClientRect();inspect(drag.yaw+(e.clientX-drag.x)/r.width*180,drag.pitch+(e.clientY-drag.y)/r.height*120,S.zoom);}});const release=e=>{pointers.delete(e.pointerId);drag=null;pinch=null;};for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,release);canvas.addEventListener('wheel',e=>{e.preventDefault();inspect(S.yaw,S.pitch,S.zoom*(e.deltaY<0?1.1:1/1.1));},{passive:false});for(const id of ['canvas','teacher'])$(id).addEventListener('webglcontextlost',e=>{e.preventDefault();fail(Error('WebGL上下文丢失，请刷新后从保存的原码重建'));});new ResizeObserver(()=>{dirty=true;request();}).observe($('mainPanel'));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else{dirty=true;request();}});window.addEventListener('pagehide',stop);document.addEventListener('fullscreenchange',()=>{dirty=true;request();});
async function boot(){const generation=++loadGeneration;try{stop();S.error=null;S.ready=false;S.sourceBytesVerified=false;S.textureBytesVerified=false;S.sourceHash=null;S.textureHash=null;S.storage='none';S.browserGPUVerified=false;S.draws=0;S.gpuCompleted=0;destroy();for(const id of ['mainPanel','teacherPanel'])$(id).classList.remove('ready');for(const id of ['canvas','teacher'])$(id).style.visibility='hidden';$('error').textContent='正在校验私人原码与原纹理…';$('teacherError').textContent='等待同一原版材料';warn('');ui();let record=null;const value=new URLSearchParams(location.hash.slice(1)).get('replay')||$('privateOriginal')?.textContent.trim();if(value){packed=value;record=await unpack(value);}else{try{const cached=localStorage.getItem(cacheKey());if(cached){record=await verify(JSON.parse(cached));S.storage='restored-per-source-and-texture';}}catch(e){warn('浏览器内存储读取失败：'+e.message);}}if(!record){$('status').textContent='等待私人原始材料';$('error').textContent='请从发给你的私人工作台链接打开一次。原码与原纹理会在本页装入，以后可直接从海羽首页进入。';$('teacherError').textContent='尚未装入原始材料';report();return;}S.sourceBytesVerified=true;S.sourceHash=EXPECTED.sourceSha256;$('status').textContent='原码已校验 · 装入原背景纹理';const tex=await loadTexture(record);if(generation!==loadGeneration)return;source=record.source;textureImage=tex.img;S.textureBytesVerified=true;S.textureHash=EXPECTED.textureSha256;try{record.texture.base64=tex.base64;localStorage.setItem(cacheKey(),JSON.stringify(record));if(S.storage==='none')S.storage='saved-per-source-and-texture';}catch(e){S.storage='this-visit-only';warn('浏览器不能保存材料，本次私人链接仍可运行。'+e.message);} $('provenance').textContent=JSON.stringify({sourceBytes:EXPECTED.sourceBytes,sourceSHA256:EXPECTED.sourceSha256,sourceBytePreserved:true,textureBytes:EXPECTED.textureBytes,textureSHA256:EXPECTED.textureSha256,textureSize:[512,512],sampler:{filter:'mipmap',wrap:'repeat',vflip:false,srgb:false},sourceInPublicRepository:false,textureInPublicRepository:false,defaultTime:0,defaultCamera:'original',textureProvenance:'pinned public archive; original Shadertoy binding XdfGRn / tex03.jpg'},null,2);views.push(make($('canvas'),true));views.push(make($('teacher'),false));dirty=true;ui();request();}catch(e){if(generation===loadGeneration)fail(e);}}
window.addEventListener('hashchange',()=>{const next=new URLSearchParams(location.hash.slice(1)).get('replay');if(next&&next!==packed)boot();});ui();boot();
})();
