/* Run only where real Chromium/WebGL is allowed. No user images: synthetic fixture. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
let chromium;try{({chromium}=require('playwright'))}catch{({chromium}=require('/opt/codex/cua_node/lib/node_modules/playwright'))}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});const base=process.env.FACE_URL||'http://localhost:8000/kaopu-face-workbench/';let firstModelRequest=true;await page.route('https://raw.githubusercontent.com/xrblocks/assets-gnm/**/gnm_head_web.bin',async route=>{if(firstModelRequest){firstModelRequest=false;await route.fulfill({status:503,body:'Synthetic QA one-shot failure'});}else await route.continue();});await page.goto(base);await page.click('#enter');await page.waitForSelector('#retry:not([hidden])');await page.click('#retry');await page.click('#back');await page.click('#enter');await page.waitForFunction(()=>window.faceWorkbench?.diagnostics().ready,{},{timeout:180000});
const geometry=()=>page.evaluate(()=>Array.from(window.faceWorkbench.positions()));let original=await geometry();assert.equal(original.length,17821*3);assert.ok((await page.evaluate(()=>window.faceWorkbench.diagnostics())).frameCount>0);
const initialPixels=await page.evaluate(()=>window.faceWorkbench.pixelAudit());assert.ok(initialPixels.colors>20);await page.screenshot({path:'face-desktop.png',fullPage:true});
await page.locator('summary').click();await page.locator('#coefficient').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});assert.notDeepEqual(await geometry(),original);await page.click('#baseline');assert.deepEqual(await geometry(),original);
for(let i=0;i<20;i++){await page.click('#back');await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().active);await page.click('#enter');await page.waitForFunction(()=>window.faceWorkbench.diagnostics().active);assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).contextCount,1);}assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).loadCount,2);
await page.click('#rotate');await page.waitForTimeout(150);await page.click('#back');await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().active);let before=await page.evaluate(()=>window.faceWorkbench.diagnostics().frameCount);await page.waitForTimeout(150);assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).frameCount,before);await page.click('#enter');await page.locator('#rotate').evaluate(el=>{if(el.getAttribute('aria-pressed')==='true')el.click();});
await page.evaluate(()=>window.faceWorkbench.loseContext());await page.waitForFunction(()=>window.faceWorkbench.diagnostics().lost);await page.evaluate(()=>window.faceWorkbench.restoreContext());await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().lost);assert.deepEqual(await geometry(),original);const restoredPixels=await page.evaluate(()=>window.faceWorkbench.pixelAudit());assert.ok(restoredPixels.colors>20);assert.deepEqual(restoredPixels.background,initialPixels.background);await page.screenshot({path:'face-restored.png'});
assert.equal(await page.locator('#media').isDisabled(),true);await page.fill('#person','Synthetic QA only');await page.check('#samePerson');assert.equal(await page.locator('#media').isDisabled(),false);const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="320" height="320"><rect width="320" height="320" fill="orange"/></svg>');await page.setInputFiles('#media',{name:'synthetic-qa.svg',mimeType:'image/svg+xml',buffer:svg});await page.waitForFunction(()=>window.faceWorkbench.diagnostics().records===1);assert.deepEqual(await geometry(),original);await page.fill('#observation','Synthetic observation, not a real person');
const videoBytes=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const c=canvas.getContext('2d');const stream=canvas.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start();for(let i=0;i<5;i++){c.fillStyle=i%2?'blue':'orange';c.fillRect(0,0,128,128);await new Promise(r=>setTimeout(r,100));}recorder.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer()));});await page.setInputFiles('#media',{name:'synthetic-motion.webm',mimeType:'video/webm',buffer:Buffer.from(videoBytes)});await page.waitForFunction(()=>document.querySelector('#video').readyState>=2);await page.evaluate(async()=>{const v=document.querySelector('#video');await v.play();await new Promise(r=>setTimeout(r,150));v.pause();});await page.click('#capture');await page.waitForFunction(()=>window.faceWorkbench.diagnostics().records===3);assert.ok((await page.evaluate(()=>window.faceWorkbench.profile())).observations.some(r=>r.type==='frame'&&r.timeSeconds>=0));
let dl=page.waitForEvent('download');await page.click('#exportProfile');let d=await dl;const json=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(json.fitStatus,'not-fitted');assert.equal(json.sharedRuntimeRequired,true);assert.equal(json.observations.length,3);assert.ok(!JSON.stringify(json).includes('blob:'));await page.setInputFiles('#importProfile',{name:'profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(json))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已恢复'));
dl=page.waitForEvent('download');await page.click('#exportObj');d=await dl;assert.equal(fs.readFileSync(await d.path(),'utf8').split('\n').filter(s=>s.startsWith('v ')).length,17821);await page.click('#clearMedia');assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).records,0);
await page.setViewportSize({width:390,height:844});await page.click('[data-view=front]');await page.screenshot({path:'face-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(posts,[]);assert.deepEqual(errors,[]);const result={passed:true,cycles:20,contextLossRestore:true,backgroundColorPreserved:true,initialFailureRetry:true,syntheticVideoFrame:true,nonGetRequests:posts,screenshots:['face-desktop.png','face-restored.png','face-mobile.png'],actualIPhone:false};fs.writeFileSync('face-qa-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
