import fs from 'node:fs';import assert from 'node:assert/strict';import {GNMHeadModel,parseContainer} from '../src/GNMModel.js';import {prepareFitModel,fitMultiPhoto,fittingInternals as I} from '../src/MultiPhotoFit.js';
const bytes=fs.readFileSync(process.env.GNM_ASSET||'../../face-workbench-20261005/qa-assets/gnm_head_web.bin');const {meta,sections}=parseContainer(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));const model=new GNMHeadModel(meta,sections),m=prepareFitModel(model);
const id=new Float64Array(24);id[1]=.9;id[3]=-.7;id[7]=1.1;id[10]=-.6;id[19]=.5;
function frame(index){const expr=new Float64Array(m.exprDim);expr[8]=[0,.5,-.4][index];expr[0]=[.2,0,-.2][index];const camera=[[.03,0,-.05,1.3,.58,1.3],[0,.32,.04,1.4,.45,1.4],[-.08,-.3,0,1.2,.65,1.2]][index];camera[5]=-1.3;
 const p=I.shape(m,id,expr),r=I.rotation(camera),s=Math.exp(camera[3]),lm=Array.from({length:478},()=>({x:.5,y:.5,z:0})),aspect=1.25;
 for(let i=0;i<m.count;i++){const q=[];for(let a=0;a<3;a++)q[a]=s*(r[a*3]*p[i*3]+r[a*3+1]*p[i*3+1]+r[a*3+2]*p[i*3+2]);lm[m.landmarks[i]]={x:(q[0]+camera[4])/aspect,y:-(q[1]+camera[5]),z:-q[2]/aspect};}
 return {id:'synthetic-'+index,width:1000,height:800,landmarks:lm};}
const frames=[0,1,2].map(frame),beforeIdentity=model.identity.slice(),result=fitMultiPhoto(m,frames);
console.log(JSON.stringify({elapsedMs:result.elapsedMs,validation:result.validation,images:result.images.map(x=>({id:x.id,heldOut:x.heldOutRmsPx,baseline:x.baseline.heldOutRmsPx,train:x.trainingRmsPx})),identity:result.identity.slice(0,24)},null,2));
assert.ok(result.validation.improvesHeldOut);assert.ok(result.validation.heldOutRmsPx<result.validation.baselineHeldOutRmsPx*.8);assert.equal(result.identity.length,253);assert.equal(result.images.length,3);assert.equal(result.images[0].expression.length,383);assert.equal(result.validation.crossView.length,3);assert.ok(result.validation.crossView.every(x=>x.heldOutRmsPx<x.baselineRmsPx));assert.notDeepEqual(result.images[0].expression,result.images[1].expression);assert.deepEqual(model.identity,beforeIdentity);
// The headline RMS pools squared point residuals, rather than averaging per-image RMS.
const pooled=values=>Math.sqrt(values.reduce((sum,f)=>sum+f.heldOutRmsPx**2*f.heldOutPoints,0)/values.reduce((sum,f)=>sum+f.heldOutPoints,0));
assert.ok(Math.abs(result.validation.heldOutRmsPx-pooled(result.images))<1e-12);assert.ok(Math.abs(result.validation.baselineHeldOutRmsPx-pooled(result.images.map(f=>f.baseline)))<1e-12);assert.ok(Math.abs(result.validation.heldOutRmsPx-result.images.reduce((sum,f)=>sum+f.heldOutRmsPx,0)/3)>1e-6);assert.match(result.validation.aggregation,/pooled RMS/);
// Only held-out observations change: arithmetic mean improves, but pooled error worsens.
const imbalanced=structuredClone(frames);for(let i=0;i<imbalanced.length;i++)for(let k=0;k<m.count;k++)if(k%5===0){const fit=result.images[i].projected,base=result.images[i].baseline.projected,p=imbalanced[i].landmarks[m.landmarks[k]];p.x=i<2?fit[k*2]:base[k*2]+10*(base[k*2]-fit[k*2]);p.y=i<2?fit[k*2+1]:base[k*2+1]+10*(base[k*2+1]-fit[k*2+1]);}
const imbalanceResult=fitMultiPhoto(m,imbalanced,{crossValidate:false}),mean=values=>values.reduce((sum,f)=>sum+f.heldOutRmsPx,0)/values.length;assert.ok(mean(imbalanceResult.images)<mean(imbalanceResult.images.map(f=>f.baseline)));assert.ok(pooled(imbalanceResult.images)>pooled(imbalanceResult.images.map(f=>f.baseline)));assert.equal(imbalanceResult.validation.improvesHeldOut,false);assert.deepEqual(imbalanceResult.identity,result.identity);assert.deepEqual(imbalanceResult.images.map(f=>f.camera),result.images.map(f=>f.camera));console.log('Pooled RMS aggregation and improvement classification passed');
const reversed=fitMultiPhoto(m,frames.slice().reverse(),{crossValidate:false});result.identity.forEach((x,k)=>assert.ok(Math.abs(x-reversed.identity[k])<1e-7));
const bad=structuredClone(frames);bad[0].landmarks[1].x=NaN;assert.throws(()=>fitMultiPhoto(m,bad));assert.equal(fitMultiPhoto(m,[frames[0]]).validation.singleImageUnderconstrained,true);assert.throws(()=>fitMultiPhoto(m,[frames[0],frames[0]]));
assert.ok(result.identity.every(Number.isFinite));model.setIdentityVector(result.identity);model.setExpressionVector(result.images[0].expression);let out=new Float32Array(model.numVertices*3);model.computeVertices(out);assert.ok(out.every(Number.isFinite));model.resetIdentity();model.resetExpression();model.computeVertices(out);const original=new GNMHeadModel(meta,sections),baseline=new Float32Array(out.length);original.computeVertices(baseline);assert.deepEqual(out,baseline);console.log('Shared identity, distinct expressions/cameras, held-out points/views, input checks, order invariance, non-mutation and exact reset passed');
