/* Real browser/GPU integration gate. Synthetic model parameters only; no user images. */
const assert=require('node:assert/strict'),fs=require('node:fs');
let playwright;try{playwright=require('playwright')}catch{playwright=require('/opt/codex/cua_node/lib/node_modules/playwright')}
const engine=process.env.FACE_BROWSER||'chromium';
(async()=>{
  const browser=await playwright[engine].launch(engine==='webkit'?{headless:true}:{executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],posts=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/shader|WebGLProgram/i.test(m.text()))errors.push(m.text())});page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});
  if(process.env.GNM_ASSET)await page.route('https://raw.githubusercontent.com/xrblocks/assets-gnm/**/gnm_head_web.bin',route=>route.fulfill({path:process.env.GNM_ASSET,contentType:'application/octet-stream'}));
  await page.goto(process.env.FACE_URL||'http://127.0.0.1:8765/kaopu-face-workbench/');await page.click('#enter');
  await page.waitForFunction(()=>!!window.faceWorkbench?.groom());assert.equal((await page.evaluate(()=>window.faceWorkbench.groomDiagnostics())).ready,false);await page.click('[data-groom-toggle]');await page.click('[data-groom-toggle]');assert.equal((await page.evaluate(()=>window.faceWorkbench.groomDiagnostics())).meshCount,0);await page.click('[data-groom-toggle]');
  await page.waitForFunction(()=>window.faceWorkbench?.groomDiagnostics()?.ready,{},{timeout:300000});
  const diag=()=>page.evaluate(()=>window.faceWorkbench.groomDiagnostics()),positions=()=>page.evaluate(()=>Array.from(window.faceWorkbench.positions()));
  const basePositions=await positions(),initial=await diag();assert.equal(initial.meshCount,3);assert.equal(initial.bindings.hair.count,14000);assert.equal(initial.bindings.brows.count,1000);assert.equal(initial.bindings.lashes.count,224);assert.ok(initial.editors.hair.rootBindingsPreserved);assert.equal(initial.error,null);
  function valid(d){for(const b of Object.values(d.bindings)){assert.equal(b.finite,true);assert.equal(b.invalidTriangles,0);assert.ok(b.maxRootGap<.00012);}for(const e of Object.values(d.editors)){assert.ok(e.attributesExact);assert.ok(e.rootBindingsPreserved);assert.ok(e.partingPreserved);}}
  valid(initial);for(const id of ['warm','cool','warm','cool'])await page.click('#'+id);assert.equal((await diag()).error,null);await page.screenshot({path:'groom-front.png',fullPage:false});
  await page.click('[data-view=three]');await page.screenshot({path:'groom-three.png'});await page.click('[data-view=side]');await page.screenshot({path:'groom-side.png'});await page.click('[data-view=front]');
  for(let i=0;i<4;i++)await page.click('#zoomIn');await page.screenshot({path:'groom-eyelids.png'});await page.click('[data-view=front]');
  for(const style of ['chin-trim','cropped-trim','original']){await page.evaluate(s=>window.faceWorkbench.groom().setOptions({style:s}),style);const d=await diag();assert.equal(d.editors.hair.style,style);valid(d);assert.deepEqual(await positions(),basePositions);}
  await page.evaluate(()=>window.faceWorkbench.groom().setOptions({hairColor:'#63341e',hairLength:.7,hairDensity:.6,browsDensity:.65,browHeight:1,lashesLength:1.3,lashesDensity:.5,lashesCurl:1.3,lowerLashes:false}));valid(await diag());assert.equal((await diag()).editors.hair.activeStrands,8400);assert.deepEqual(await positions(),basePositions);await page.screenshot({path:'groom-controls.png'});
  await page.evaluate(()=>window.faceWorkbench.groom().reset());valid(await diag());
  const summary=page.locator('#parameters').locator('xpath=ancestor::details/summary');if(!await page.locator('#coefficient').isVisible())await summary.click();
  await page.locator('#coefficient').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});const id=await diag();assert.notEqual(id.geometryHashes.hair,initial.geometryHashes.hair);assert.notEqual(id.geometryHashes.brows,initial.geometryHashes.brows);assert.notEqual(id.geometryHashes.lashes,initial.geometryHashes.lashes);valid(id);
  await page.selectOption('#kind','expression');await page.locator('#coefficient').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});valid(await diag());
  if(await page.evaluate(()=>typeof window.faceWorkbench.setPose==='function')){await page.evaluate(()=>window.faceWorkbench.setPose(0,.1,.2,-.08));valid(await diag());await page.screenshot({path:'groom-pose.png'});}else throw Error('Missing head pose QA hook');
  await page.click('#baseline');assert.deepEqual(await positions(),basePositions);assert.equal((await diag()).options.enabled,false);const baselinePixels=await page.evaluate(()=>window.faceWorkbench.pixelAudit());await page.screenshot({path:'groom-r01-bare.png'});
  await page.evaluate(()=>window.faceWorkbench.groom().reset());assert.deepEqual((await diag()).geometryHashes,initial.geometryHashes);valid(await diag());
  for(let i=0;i<20;i++){await page.click('#back');await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().active);await page.click('#enter');await page.waitForFunction(()=>window.faceWorkbench.diagnostics().active);assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).contextCount,1);assert.equal((await diag()).meshCount,3);}
  const beforeRestore=await diag();await page.evaluate(()=>window.faceWorkbench.loseContext());await page.waitForFunction(()=>window.faceWorkbench.diagnostics().lost);await page.evaluate(()=>window.faceWorkbench.restoreContext());await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().lost&&window.faceWorkbench.groomDiagnostics()?.ready,{},{timeout:120000});await page.waitForTimeout(1000);assert.deepEqual((await diag()).geometryHashes,beforeRestore.geometryHashes);valid(await diag());assert.ok((await page.evaluate(()=>window.faceWorkbench.pixelAudit())).colors>20);await page.screenshot({path:'groom-restored.png'});
  await page.evaluate(()=>window.faceWorkbench.groom().hide());assert.deepEqual((await page.evaluate(()=>window.faceWorkbench.pixelAudit())).background,baselinePixels.background);assert.deepEqual(await positions(),basePositions);await page.evaluate(()=>window.faceWorkbench.groom().reset());
  await page.setViewportSize({width:390,height:844});await page.click('[data-view=front]');await page.screenshot({path:'groom-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(posts,[]);assert.deepEqual(errors,[]);
  const result={passed:true,engine,version:browser.version(),cycles:20,actualIPhone:false,modelVertices:17821,contextLossRestore:true,headExactRestore:true,nonGetRequests:posts,initial,final:await diag(),screenshots:['groom-front.png','groom-three.png','groom-side.png','groom-eyelids.png','groom-controls.png','groom-pose.png','groom-r01-bare.png','groom-restored.png','groom-mobile.png']};fs.writeFileSync('groom-browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({passed:true,engine,version:browser.version()}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
