/* Real browser/GPU integration gate. Synthetic model parameters only; no user images. */
const assert=require('node:assert/strict'),fs=require('node:fs');
let playwright;try{playwright=require('playwright')}catch{playwright=require('/opt/codex/cua_node/lib/node_modules/playwright')}
const engine=process.env.FACE_BROWSER||'chromium';
// The accepted 14k-strand groom harness gives software GPU work 120s and
// synchronizes readback. This changes only the test budget, never runtime quality.
const GPU_TIMEOUT=Number(process.env.FACE_GPU_TIMEOUT_MS)||120000;
let result={passed:false,engine,phase:'starting',phases:[],frames:[],gpuTimings:[],actualIPhone:false},activeBrowser;
const save=()=>fs.writeFileSync('groom-browser-result.json',JSON.stringify(result,null,2));
function phase(name,extra={}){result.phase=name;result.phases.push({name,at:new Date().toISOString(),...extra});save();console.log('GROOM PHASE '+name+' '+JSON.stringify(extra));}
async function bounded(promise,label){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label+' exceeded '+GPU_TIMEOUT+'ms software-GPU budget')),GPU_TIMEOUT)})]);}finally{clearTimeout(timer);}}
(async()=>{
  const browser=activeBrowser=await playwright[engine].launch(engine==='webkit'?{headless:true}:{executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],posts=[];
  page.setDefaultTimeout(GPU_TIMEOUT);
  async function settle(label,{pixels=false}={}){phase(label+' / GPU wait');const observed=await bounded(page.evaluate(wantPixels=>{const gl=document.querySelector('#canvas').getContext('webgl2');if(!gl)throw Error('No real WebGL2 context');const start=performance.now();const pixel=wantPixels?window.faceWorkbench.pixelAudit():null;gl.finish();return {syncMs:performance.now()-start,pixel,glError:gl.getError(),renderer:gl.getParameter(gl.RENDERER),drawingBuffer:[gl.drawingBufferWidth,gl.drawingBufferHeight],frameCount:window.faceWorkbench.diagnostics().frameCount};},pixels),label+' GPU synchronization');assert.equal(observed.glError,0,label);if(pixels){assert.ok(observed.pixel.colors>20,label+' actual rendered pixels');assert.equal(observed.pixel.error,0,label);}result.gpuTimings.push({label,...observed});save();return observed;}
  async function shot(name,{fullPage=false}={}){await page.evaluate(()=>scrollTo(0,0));const probe=await settle(name,{pixels:true});phase(name+' / screenshot');const started=Date.now();await page.screenshot({path:name+'.png',fullPage,timeout:GPU_TIMEOUT});const bytes=fs.statSync(name+'.png').size;assert.ok(bytes>1000,name+' screenshot bytes');result.frames.push({name:name+'.png',bytes,screenshotMs:Date.now()-started,...probe});phase(name+' captured',{bytes,screenshotMs:Date.now()-started});}
  async function clickAndSettle(selector,label=selector){await page.click(selector);await settle(label);}
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/shader|WebGLProgram/i.test(m.text()))errors.push(m.text())});page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});
  if(process.env.GNM_ASSET)await page.route('https://raw.githubusercontent.com/xrblocks/assets-gnm/**/gnm_head_web.bin',route=>route.fulfill({path:process.env.GNM_ASSET,contentType:'application/octet-stream'}));
  phase('load clean head');await page.goto(process.env.FACE_URL||'http://127.0.0.1:8765/kaopu-face-workbench/');await page.click('#enter');
  await page.waitForFunction(()=>!!window.faceWorkbench?.groom());assert.equal((await page.evaluate(()=>window.faceWorkbench.groomDiagnostics())).ready,false);await page.click('[data-groom-toggle]');await page.click('[data-groom-toggle]');assert.equal((await page.evaluate(()=>window.faceWorkbench.groomDiagnostics())).meshCount,0);await page.click('[data-groom-toggle]');
  phase('worker bind pending');await page.waitForFunction(()=>window.faceWorkbench?.groomDiagnostics()?.ready,{},{timeout:300000});
  const diag=()=>page.evaluate(()=>window.faceWorkbench.groomDiagnostics()),positions=()=>page.evaluate(()=>Array.from(window.faceWorkbench.positions()));
  const basePositions=await positions(),initial=await diag();assert.equal(initial.meshCount,3);assert.equal(initial.bindings.hair.count,14000);assert.equal(initial.bindings.brows.count,1000);assert.equal(initial.bindings.lashes.count,224);assert.ok(initial.editors.hair.rootBindingsPreserved);assert.equal(initial.error,null);
  function valid(d){for(const b of Object.values(d.bindings)){assert.equal(b.finite,true);assert.equal(b.invalidTriangles,0);assert.ok(b.maxRootGap<.00012);}for(const e of Object.values(d.editors)){assert.ok(e.attributesExact);assert.ok(e.rootBindingsPreserved);assert.ok(e.partingPreserved);}}
  result.initial=initial;valid(initial);phase('bindings and source invariants passed',{hair:initial.bindings.hair.count,brows:initial.bindings.brows.count,lashes:initial.bindings.lashes.count});await shot('groom-front');for(const [i,id]of ['warm','cool','warm','cool'].entries())await clickAndSettle('#'+id,'light '+i+' '+id);assert.equal((await diag()).error,null);phase('all light visibility transitions passed');
  await page.click('[data-view=three]');await shot('groom-three');await page.click('[data-view=side]');await shot('groom-side');await clickAndSettle('[data-view=front]','return front');
  for(let i=0;i<4;i++)await clickAndSettle('#zoomIn','eye zoom '+i);await shot('groom-eyelids');await clickAndSettle('[data-view=front]','reset eye zoom');
  for(const style of ['chin-trim','cropped-trim','original']){await page.evaluate(s=>window.faceWorkbench.groom().setOptions({style:s}),style);const d=await diag();assert.equal(d.editors.hair.style,style);valid(d);assert.deepEqual(await positions(),basePositions);await settle('style '+style);}
  phase('source-curve style controls passed');await page.evaluate(()=>window.faceWorkbench.groom().setOptions({hairColor:'#63341e',hairLength:.7,hairDensity:.6,browsDensity:.65,browHeight:1,lashesLength:1.3,lashesDensity:.5,lashesCurl:1.3,lowerLashes:false}));valid(await diag());assert.equal((await diag()).editors.hair.activeStrands,8400);assert.deepEqual(await positions(),basePositions);await shot('groom-controls');
  await page.evaluate(()=>window.faceWorkbench.groom().reset());valid(await diag());await settle('restore groom controls');
  const summary=page.locator('#parameters').locator('xpath=ancestor::details/summary');if(!await page.locator('#coefficient').isVisible())await summary.click();
  await page.locator('#coefficient').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});const id=await diag();assert.notEqual(id.geometryHashes.hair,initial.geometryHashes.hair);assert.notEqual(id.geometryHashes.brows,initial.geometryHashes.brows);assert.notEqual(id.geometryHashes.lashes,initial.geometryHashes.lashes);valid(id);await settle('identity deformation');
  await page.selectOption('#kind','expression');await page.locator('#coefficient').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input',{bubbles:true}))});valid(await diag());await settle('expression deformation');
  if(await page.evaluate(()=>typeof window.faceWorkbench.setPose==='function')){await page.evaluate(()=>window.faceWorkbench.setPose(0,.1,.2,-.08));valid(await diag());await shot('groom-pose');}else throw Error('Missing head pose QA hook');
  await page.click('#baseline');assert.deepEqual(await positions(),basePositions);assert.equal((await diag()).options.enabled,false);const baselinePixels=await page.evaluate(()=>window.faceWorkbench.pixelAudit());await shot('groom-r01-bare');
  await page.evaluate(()=>window.faceWorkbench.groom().reset());assert.deepEqual((await diag()).geometryHashes,initial.geometryHashes);valid(await diag());await settle('exact groom restoration');
  for(let i=0;i<20;i++){await page.click('#back');await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().active);await page.click('#enter');await page.waitForFunction(()=>window.faceWorkbench.diagnostics().active);assert.equal((await page.evaluate(()=>window.faceWorkbench.diagnostics())).contextCount,1);assert.equal((await diag()).meshCount,3);await settle('navigation cycle '+(i+1));}phase('20 navigation cycles passed');
  const beforeRestore=await diag();await page.evaluate(()=>window.faceWorkbench.loseContext());await page.waitForFunction(()=>window.faceWorkbench.diagnostics().lost);await page.evaluate(()=>window.faceWorkbench.restoreContext());await page.waitForFunction(()=>!window.faceWorkbench.diagnostics().lost&&window.faceWorkbench.groomDiagnostics()?.ready,{},{timeout:120000});await page.waitForTimeout(1000);assert.deepEqual((await diag()).geometryHashes,beforeRestore.geometryHashes);valid(await diag());assert.ok((await page.evaluate(()=>window.faceWorkbench.pixelAudit())).colors>20);await shot('groom-restored');phase('WebGL restore passed');
  await page.evaluate(()=>window.faceWorkbench.groom().hide());assert.deepEqual((await page.evaluate(()=>window.faceWorkbench.pixelAudit())).background,baselinePixels.background);assert.deepEqual(await positions(),basePositions);await page.evaluate(()=>window.faceWorkbench.groom().reset());
  await page.setViewportSize({width:390,height:844});await page.click('[data-view=front]');await shot('groom-mobile',{fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(posts,[]);assert.deepEqual(errors,[]);
  Object.assign(result,{passed:true,phase:'complete',engine,version:browser.version(),cycles:20,actualIPhone:false,modelVertices:17821,contextLossRestore:true,headExactRestore:true,nonGetRequests:posts,initial,final:await diag(),screenshots:['groom-front.png','groom-three.png','groom-side.png','groom-eyelids.png','groom-controls.png','groom-pose.png','groom-r01-bare.png','groom-restored.png','groom-mobile.png']});save();console.log(JSON.stringify({passed:true,engine,version:browser.version()}));await browser.close();
})().catch(async e=>{result.passed=false;result.failure={phase:result.phase,message:e.message,stack:e.stack};save();console.error(e);try{await Promise.race([activeBrowser?.close(),new Promise(resolve=>setTimeout(resolve,3000))]);}catch{}process.exit(1)});
