const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const url=process.env.QA_URL||'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-unified-human-workbench/skin-r02/',out='/tmp/uh-pages-evidence';fs.mkdirSync(out,{recursive:true});
const report={url,scope:'Actual public GitHub Pages; desktop Chromium software WebGL, not physical mobile or user GPU',checks:[],errors:[],failed:[],shots:[]};let b,p;
const check=(name,pass)=>{report.checks.push({name,pass:!!pass});assert.ok(pass,name);};
async function fingerprint(){return p.evaluate(async()=>{const hash=async a=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).join(',');return {positions:await hash(fullCommonWorkbench.positions()),faces:await hash(fullCommonWorkbench.faces()),archive:JSON.stringify(fullCommonWorkbench.archive())};});}
async function pixelHash(){return p.evaluate(async()=>{const v=commonSkin._viewer();v.render();const gl=v.renderer.getContext(),a=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,a);return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).join(',');});}
async function shot(name){await p.screenshot({path:out+'/'+name+'.png'});report.shots.push(name+'.png');}
(async()=>{b=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});p=await b.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))report.errors.push(m.text());});p.on('requestfailed',r=>report.failed.push({url:r.url(),error:r.failure()?.errorText}));
await p.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await p.waitForFunction(()=>window.fullCommonWorkbench,null,{timeout:60000});await p.click('#load-model');await p.waitForFunction(()=>window.commonSkin?.report().ready&&window.uhSkin?.report().version,null,{timeout:180000});check('correct published UH study version',await p.evaluate(()=>uhSkin.version==='unified-human-skin/r02-uh-study'));check('one original 25417-vertex 50624-triangle human',await p.evaluate(()=>fullCommonWorkbench.diagnostics().vertices===25417&&fullCommonWorkbench.diagnostics().triangles===50624&&document.querySelectorAll('canvas').length===1));const original=await fingerprint();
await p.evaluate(()=>fullCommonWorkbench.view('face'));const enhanced=await pixelHash();await shot('new-face');await p.click('[data-uh-mode="0"]');const previous=await pixelHash();await shot('previous-face');check('same-frame new and old processing differ',enhanced!==previous);await p.click('[data-skin-mode="white"]');const white=await pixelHash();await shot('white-face');check('white mode distinct from skin',white!==previous);await p.click('[data-skin-mode="skin"]');check('return to previous processing stable',previous===await pixelHash());await p.click('[data-uh-mode="1"]');check('return to learned processing stable',enhanced===await pixelHash());check('all material modes preserve geometry and archive',JSON.stringify(original)===JSON.stringify(await fingerprint()));
await p.click('.uh-details>summary');await p.locator('#uh-micro').evaluate(e=>{e.value=1.5;e.dispatchEvent(new Event('input',{bubbles:true}));});check('layer parameter changes actual rendered pixels',enhanced!==await pixelHash());await p.click('#uh-save');await p.evaluate(()=>uhSkin.set({micro:.4}));await p.click('#uh-restore');check('saved material restores separately from model',await p.evaluate(()=>uhSkin.report().settings.micro===1.5));check('material edit keeps native archive',JSON.stringify(original)===JSON.stringify(await fingerprint()));await shot('layer-controls');await p.click('.uh-details>summary');
await p.evaluate(()=>uhSkin.set(uhSkin.presets.natural));await p.click('#uh-macro');await shot('macro');await p.evaluate(()=>uhSkin.set({layer:'normal'}));await shot('normal-detail');await p.evaluate(()=>uhSkin.set({layer:'regions'}));await shot('region-masks');await p.evaluate(()=>uhSkin.set({layer:'beauty'}));check('RGB profile sums are unity',await p.evaluate(()=>uhSkin.report().kernelSums.every(s=>Math.abs(s-1)<1e-6)));
await p.evaluate(()=>fullCommonWorkbench.set('anny.phenotypes:height',.64));check('shape neutral tension recalibrated',await p.evaluate(()=>uhSkin.report().tension.calibrated&&uhSkin.report().tension.maxCompression===0&&uhSkin.report().tension.maxStretch===0));await p.evaluate(()=>fullCommonWorkbench.set('anny.pose:lowerarm01.L.X',55));await p.evaluate(()=>fullCommonWorkbench.set('anny.phenotypes:weight',.70));check('posed body shape invalidates tension safely',await p.evaluate(()=>!uhSkin.report().tension.calibrated&&uhSkin.report().tension.maxCompression===0));await p.evaluate(a=>fullCommonWorkbench.restore(JSON.parse(a)),original.archive);check('original solver archive restore',JSON.stringify(original)===JSON.stringify(await fingerprint()));
await p.evaluate(()=>fullCommonWorkbench.view('three'));await shot('whole-body');await p.click('#neck-band');check('old neck inspection retained',await p.locator('#neck-band').getAttribute('aria-pressed')==='true');await p.click('#neck-band');await p.click('#wireframe');check('old wireframe retained',await p.locator('#wireframe').getAttribute('aria-pressed')==='true');await p.click('#wireframe');await p.setViewportSize({width:1280,height:800});await p.evaluate(()=>fullCommonWorkbench.view('face'));await shot('desktop1280');
report.skin=await p.evaluate(()=>uhSkin.report());report.pixels=await p.evaluate(()=>fullCommonWorkbench.pixelAudit());check('nonblank WebGL without errors',report.pixels.colors>100&&report.pixels.error===0);check('unvalidated transmission stays disabled',await p.evaluate(()=>commonSkin.report().thinTransmissionEnabled===false));check('zero JavaScript or shader errors',report.errors.length===0);check('zero failed public resources',report.failed.length===0);report.success=true;
})().catch(e=>{report.success=false;report.failure=e.stack;process.exitCode=1;console.error(e);}).finally(async()=>{if(p)try{await shot('last-state');}catch{}fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({success:report.success,checks:report.checks,failure:report.failure,errors:report.errors}));await b?.close();});
