const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root='http://127.0.0.1:8765/kaopu-unified-human-workbench/',url=process.env.QA_URL||root+'skin-r02/index.html',out=process.env.QA_OUT||'/tmp/uh-evidence/local';fs.mkdirSync(out,{recursive:true});
const report={url,checks:[],errors:[],failed:[],screenshots:[],scope:'Desktop Chromium SwiftShader; not user GPU and not phone hardware'};let browser,p;
const check=(name,pass)=>{report.checks.push({name,pass:!!pass});assert.ok(pass,name);};
async function hash(){return p.evaluate(async()=>{const h=async a=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).join(',');return{p:await h(fullCommonWorkbench.positions()),i:await h(fullCommonWorkbench.faces()),archive:JSON.stringify(fullCommonWorkbench.archive())};});}
async function pix(){return p.evaluate(async()=>{const v=commonSkin._viewer();v.render();const gl=v.renderer.getContext(),a=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,a);return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).join(',');});}
async function shot(name){await p.screenshot({path:path.join(out,name+'.png')});report.screenshots.push(name+'.png');}
async function load(page,u){await page.goto(u,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.fullCommonWorkbench,null,{timeout:60000});await page.click('#load-model');await page.waitForFunction(()=>fullCommonWorkbench.diagnostics().ready||document.getElementById('load-status').textContent.startsWith('载入失败'),null,{timeout:180000});assert.ok(await page.evaluate(()=>fullCommonWorkbench.diagnostics().ready),'original common model loaded');await page.waitForFunction(()=>window.commonSkin?.report().ready,null,{timeout:60000});}
(async()=>{
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});p=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))report.errors.push(m.text());});p.on('requestfailed',r=>report.failed.push(r.url()));await load(p,url);
 check('new learned layer version',await p.evaluate(()=>uhSkin.version==='unified-human-skin/r02-uh-study'));check('original single 25417-vertex model',await p.evaluate(()=>fullCommonWorkbench.diagnostics().vertices===25417&&document.querySelectorAll('canvas').length===1));const ref=await hash();
 await p.evaluate(()=>fullCommonWorkbench.view('face'));await shot('new-face');const newPixels=await pix();await p.click('[data-uh-mode="0"]');await shot('previous-processing');check('learned processing changes actual pixels',newPixels!==await pix());check('mode switch leaves geometry and archive intact',JSON.stringify(ref)===JSON.stringify(await hash()));await p.click('[data-uh-mode="1"]');check('mode roundtrip stable',newPixels===await pix());
 await p.click('.uh-details>summary');for(const[k,v]of [['tone',.3],['albedoMix',0],['regionRoughness',0],['micro',0],['roughCoupling',0],['radiusR',.45],['lipMix',.8]]){const before=await pix();await p.locator('#uh-'+k).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},v);check(k+' controls actual material pixels',before!==await pix());check(k+' does not mutate model',JSON.stringify(ref)===JSON.stringify(await hash()));await p.evaluate(()=>uhSkin.set(uhSkin.presets.natural));}
 await shot('controls');await p.evaluate(()=>uhSkin.set({...uhSkin.presets.warm,layer:'beauty'}));await p.click('#uh-save');await p.evaluate(()=>uhSkin.set(uhSkin.presets.dry));await p.click('#uh-restore');check('material save restore',await p.evaluate(()=>uhSkin.report().settings.tone===.36));const recipe=await p.evaluate(()=>uhSkin.recipe());await p.evaluate(()=>uhSkin.set(uhSkin.presets.natural));await p.evaluate(r=>uhSkin.restore(r),recipe);check('export/import API roundtrip',await p.evaluate(()=>uhSkin.report().settings.tone===.36));await p.click('.uh-details>summary');await shot('warm-face');
 await p.evaluate(()=>uhSkin.set(uhSkin.presets.natural));await p.click('#uh-macro');await shot('new-macro');await p.evaluate(()=>uhSkin.set({layer:'normal'}));await shot('normal-macro');await p.evaluate(()=>uhSkin.set({layer:'regions'}));await shot('semantic-regions');await p.evaluate(()=>uhSkin.set({layer:'beauty',lipMix:.8,lipGloss:.5}));await shot('lip-layer-stress');await p.evaluate(()=>uhSkin.set(uhSkin.presets.natural));check('all RGB kernel channels conserve energy',await p.evaluate(()=>uhSkin.report().kernelSums.every(s=>Math.abs(s-1)<1e-6)));
 const archive=await p.evaluate(()=>fullCommonWorkbench.archive());await p.evaluate(()=>fullCommonWorkbench.set('anny.phenotypes:height',.65));let r=await p.evaluate(()=>uhSkin.report());check('neutral shape change recalibrates tension without wrinkles',r.tension.calibrated&&r.tension.maxCompression===0&&r.tension.maxStretch===0);
 await p.evaluate(()=>fullCommonWorkbench.set('anny.pose:lowerarm01.L.X',55));r=await p.evaluate(()=>uhSkin.report());report.bent=r.tension;check('pose deformation measured without new geometry',r.tension.calibrated&&r.geometryChanged===false&&r.tension.activeVertices>0&&r.tension.maxCompression>.05&&r.tension.maxStretch>.05);await p.evaluate(()=>fullCommonWorkbench.view('three'));await shot('arm-bend');
 await p.evaluate(()=>fullCommonWorkbench.set('anny.phenotypes:weight',.72));r=await p.evaluate(()=>uhSkin.report());check('shape changed while posed disables old tension reference',!r.tension.calibrated&&r.tension.maxCompression===0&&r.tension.maxStretch===0);await p.evaluate(a=>fullCommonWorkbench.restore(a),archive);check('restore recovers original parameter body',JSON.stringify(ref)===JSON.stringify(await hash()));
 const original=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});await load(original,root+'skin-r01/index.html');
 const prepareCompare=async page=>{await page.evaluate(()=>{const v=commonSkin._viewer();v.container.style.flex='none';v.container.style.width='960px';v.container.style.height='720px';v.resize();fullCommonWorkbench.view('face');});await page.waitForTimeout(100);};await prepareCompare(original);await prepareCompare(p);await p.evaluate(()=>uhSkin.set({mode:0,layer:'beauty'}));
 const sample=page=>page.evaluate(()=>{const v=commonSkin._viewer();v.render();const gl=v.renderer.getContext(),a=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,a);const sample=[];for(let i=0;i<a.length;i+=64)sample.push(a[i],a[i+1],a[i+2]);return{sample,width:gl.drawingBufferWidth,height:gl.drawingBufferHeight};});
 const a=await sample(original),b=await sample(p);check('reference uses identical drawing dimensions',a.width===b.width&&a.height===b.height);report.baselinePixelMeanError=a.sample.reduce((sum,x,i)=>sum+Math.abs(x-b.sample[i]),0)/a.sample.length;check('previous-processing matches actual prior shader',report.baselinePixelMeanError<.5);await original.close();
 await p.evaluate(()=>{const v=commonSkin._viewer();v.container.style.flex='';v.container.style.width='';v.container.style.height='';v.resize();uhSkin.set(uhSkin.presets.natural);fullCommonWorkbench.view('three');});await shot('whole-body');await p.setViewportSize({width:1280,height:800});await p.evaluate(()=>fullCommonWorkbench.view('face'));await shot('desktop1280');report.skin=await p.evaluate(()=>uhSkin.report());report.pixelAudit=await p.evaluate(()=>fullCommonWorkbench.pixelAudit());
 const leaks=await p.evaluate(()=>{const g=commonSkin._viewer().geometry,mask=g.attributes.skinCoverage.array,region=g.attributes.uhRegion.array;let count=0;for(let i=0;i<mask.length;i++)if(mask[i]===0&&region.slice(i*4,i*4+4).some(v=>v>1e-6))count++;return count;});report.nonSkinRegionLeakVertices=leaks;check('skin remains excluded from eye and internal meshes',leaks===0&&report.skin.regions.counts[0]>0&&report.skin.regions.counts[2]>0);check('nonblank GPU output',report.pixelAudit.colors>100&&report.pixelAudit.error===0);check('no shader/JS errors',report.errors.length===0);check('no failed resources',report.failed.length===0);report.success=true;
})().catch(e=>{report.success=false;report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{if(p)try{await shot('last-state');}catch{}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({success:report.success,checks:report.checks,failure:report.failure,errors:report.errors,baselinePixelMeanError:report.baselinePixelMeanError}));await browser?.close();});

// uh-render-review-observed-strain
