import fs from 'node:fs';import vm from 'node:vm';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');vm.runInThisContext(fs.readFileSync(path.join(root,'src/instrument.js'),'utf8'));
const A=globalThis.KaopuFishContinuousSkin,h=await A.build(new Uint8Array(fs.readFileSync(path.join(root,'data/MUSKELLUNGE_RESOLVED_TAIL_DRIVE_SCORE_R08.kfc8')))),L=h.metadata.continuum.body.endXM-h.metadata.continuum.body.sourceXM;
const options=(amplitude=1)=>({mode:'CRUISE',amplitude,finGains:Array(7).fill(1),speed:1});
function measure(drive){const opt=options(drive);A.reset(h,'CRUISE',opt);for(let i=0;i<1200;i++)A.update(h,1/60,opt);const hz=h.state.beatFrequencyHz,locations=[0,.2,.4,.5,.6,.7,.8,h.metadata.continuum.axialGait.peduncleU,.95,1],data=locations.map(u=>({u,angle:[],z:[]})),tailInputs=[],speeds=[];let couplingError=0;
 for(let i=0;i<1200;i++){A.update(h,10/(hz*1200),opt);const phase=h.state.beatPhase;for(const q of data){const f=A.readField(h,0,q.u);q.angle.push([phase,f[3]]);q.z.push([phase,f[2]]);}tailInputs.push(h.state.caudalInput);speeds.push(h.state.swimSpeedMps);const g=h.metadata.continuum.axialGait,expected=Math.max(-.45,Math.min(.45,-g.caudalAngleGain*h.state.peduncle.angle-g.caudalVelocitySeconds*h.state.peduncle.angularVelocity))*h.state.response[11];couplingError=Math.max(couplingError,Math.abs(expected-h.state.caudalInput));}
 const fit=arr=>{const mean=arr.reduce((s,x)=>s+x[1],0)/arr.length;let a=0,b=0;for(const [phase,v]of arr){a+=(v-mean)*Math.sin(phase);b+=(v-mean)*Math.cos(phase);}a*=2/arr.length;b*=2/arr.length;return {amplitude:Math.hypot(a,b),phaseRad:Math.atan2(b,a)};};
 return {drive,hz,meanSpeedMps:speeds.reduce((a,b)=>a+b,0)/speeds.length,couplingError,locations:data.map(q=>({u:q.u,angle:fit(q.angle),lateral:fit(q.z)})),maxTailInput:Math.max(...tailInputs.map(Math.abs))};}
const cruise=measure(1),low=measure(.5),high=measure(1.5),head=cruise.locations[0],ped=cruise.locations[7],posterior=cruise.locations.filter(p=>p.u>=.4),phase=posterior.map(p=>p.lateral.phaseRad);
for(let i=1;i<phase.length;i++){while(phase[i]-phase[i-1]>Math.PI)phase[i]-=Math.PI*2;while(phase[i]-phase[i-1]<-Math.PI)phase[i]+=Math.PI*2;}
const checks={posteriorDominates:ped.angle.amplitude>head.angle.amplitude*3,posteriorLateralIncreases:posterior.every((p,i)=>i===0||p.lateral.amplitude>posterior[i-1].lateral.amplitude),posteriorPhaseTravels:phase.every((p,i)=>i===0||p<phase[i-1]),caudalConsumesPeduncle:cruise.couplingError<1e-12&&cruise.maxTailInput>1e-4,driveControlsBeatFrequency:high.hz>cruise.hz&&cruise.hz>low.hz,driveControlsAmplitude:high.locations.at(-1).lateral.amplitude>cruise.locations.at(-1).lateral.amplitude&&cruise.locations.at(-1).lateral.amplitude>low.locations.at(-1).lateral.amplitude,driveControlsSpeedResponse:high.meanSpeedMps>cruise.meanSpeedMps&&cruise.meanSpeedMps>low.meanSpeedMps};
for(let i=0;i<1200;i++)A.update(h,1/60,options(0));checks.zeroDriveRelaxes=Math.max(...h.state.body.q.map(Math.abs))<1e-6&&h.state.swimSpeedMps<.01;
const report={verifiedAt:new Date().toISOString(),cruise,low,high,posteriorUnwrappedPhase:phase,checks,zeroDrive:{maxBodyAngle:Math.max(...h.state.body.q.map(Math.abs)),speedMps:h.state.swimSpeedMps},passed:Object.values(checks).every(Boolean),biomechanicalCalibration:false};fs.writeFileSync(path.join(root,'evidence/GAIT_REGRESSION_REPORT.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({checks,passed:report.passed,headAngleRad:head.angle.amplitude,peduncleAngleRad:ped.angle.amplitude,phase,amplitudes:posterior.map(p=>p.lateral.amplitude),frequencies:[low.hz,cruise.hz,high.hz],speeds:[low.meanSpeedMps,cruise.meanSpeedMps,high.meanSpeedMps],zeroDrive:report.zeroDrive},null,2));if(!report.passed)process.exitCode=1;
