/** Same-model, same-light cast-shadow experiment. Original code; no eyelid geometry edits.
 * Uses the existing Three renderer's shadow map, restricted to native eye receivers.
 * Transparent native corneal covers are excluded from the depth caster to avoid
 * turning a clear shell into a false opaque occluder of the iris/sclera.
 */
export function attachNativeEyeShadowDiagnostic(skin,{THREE}={}){
 if(skin.eyeShadowDiagnostic)return skin.eyeShadowDiagnostic;if(!skin.cornealBridge)throw Error('Recover native optical layers before shadow diagnosis');
 const v=skin.viewer,m=skin.material,mesh=v.mesh,renderer=v.renderer,light=v.scene.children.find(o=>o.isDirectionalLight&&o.position.z>0);
 if(!light)throw Error('Existing front key light required');if(v.scene.children.some(o=>o.isLight&&o!==light&&o.castShadow))throw Error('Diagnostic requires only the existing key to cast shadows');if(light.shadow.map)throw Error('Do not replace an existing owned shadow map');
 const old={render:mesh.onBeforeRender,dispose:skin.dispose,needsUpdate:light.shadow.needsUpdate,compile:m.onBeforeCompile,key:m.customProgramCacheKey,cast:mesh.castShadow,receive:mesh.receiveShadow,depth:mesh.customDepthMaterial,shadowSide:m.shadowSide,enabled:renderer.shadowMap.enabled,type:renderer.shadowMap.type,lightCast:light.castShadow,mapSize:light.shadow.mapSize.clone(),bias:light.shadow.bias,normalBias:light.shadow.normalBias,radius:light.shadow.radius,camera:light.shadow.camera.clone()};
 const U={uE3Enabled:{value:0},uE3ShadowMatrix:{value:light.shadow.matrix},uE3NormalBias:{value:.00004}},depth=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking});let disposed=false,compiles=0;
 depth.onBeforeCompile=s=>{s.vertexShader='attribute float e2Layer;varying float vE3Layer;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvE3Layer=e2Layer;');s.fragmentShader='varying float vE3Layer;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('void main() {','void main() {\nif(vE3Layer>1.5)discard;');};depth.customProgramCacheKey=()=> 'kaopu-eye-shadow-exclude-clear-cover-v1';
 m.onBeforeCompile=s=>{old.compile.call(m,s);Object.assign(s.uniforms,U);s.fragmentShader='uniform float uE3Enabled,uE3NormalBias;uniform mat4 uE3ShadowMatrix;\n'+s.fragmentShader;
 const helper=`vec4 e3ShadowCoordinate(vec4 exterior){if(e2Refracted<.5)return exterior;vec3 p=e2HitView+e2InnerNormal*uE3NormalBias;vec3 world=cameraPosition+vec3(dot(viewMatrix[0].xyz,p),dot(viewMatrix[1].xyz,p),dot(viewMatrix[2].xyz,p));return uE3ShadowMatrix*vec4(world,1.);}`;s.fragmentShader=s.fragmentShader.replace('vec3 e1IrisColor()',helper+'\nvec3 e1IrisColor()');const chunk=THREE.ShaderChunk.lights_fragment_begin.replaceAll('receiveShadow','(receiveShadow && vE2Layer>.5 && uE3Enabled>.5)').replaceAll('vDirectionalShadowCoord[ i ]','e3ShadowCoordinate(vDirectionalShadowCoord[ i ])');if(!s.fragmentShader.includes('#include <lights_fragment_begin>'))throw Error('Missing native direct lighting stage');s.fragmentShader=s.fragmentShader.replace('#include <lights_fragment_begin>',chunk);compiles++;};m.customProgramCacheKey=()=>old.key.call(m)+'/native-eye-shadow-diagnostic-v1';
 mesh.onBeforeRender=function(...args){old.render.apply(this,args);this.receiveShadow=this.material===m;};
 mesh.castShadow=true;mesh.receiveShadow=true;mesh.customDepthMaterial=depth;m.shadowSide=THREE.DoubleSide;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;light.castShadow=true;
 light.shadow.mapSize.set(2048,2048);light.shadow.bias=-.00001;light.shadow.normalBias=.00004;light.shadow.radius=1;
 // Shift the shadow frustum, not the key light or its target. The lighting remains identical.
 v.scene.updateMatrixWorld(true);light.shadow.updateMatrices(light);const center=new THREE.Vector3();let n=0;for(const eye of v.model.eyeSurface.eyes)for(const i of eye.vertices){const f=v.nativeGeometry.attributes.fEye;if(f.getZ(i)>.9&&Math.hypot(f.getX(i),f.getY(i))<.2){center.add(new THREE.Vector3().fromBufferAttribute(v.nativeGeometry.attributes.position,i));n++;}}center.multiplyScalar(1/n).applyMatrix4(mesh.matrixWorld).applyMatrix4(light.shadow.camera.matrixWorldInverse);
 const c=light.shadow.camera;c.left=center.x-.08;c.right=center.x+.08;c.bottom=center.y-.055;c.top=center.y+.055;c.near=Math.max(.001,-center.z-.35);c.far=-center.z+.35;c.updateProjectionMatrix();light.shadow.needsUpdate=true;m.needsUpdate=true;
 const report=()=>({activeOnCurrentMaterial:mesh.material===m,supportedMaterial:'beauty only; gray/grid reception disabled',enabled:U.uE3Enabled.value===1,disposed,compiles,receiver:'native eye layers only',caster:'same existing head/lids/inner eyes; clear corneal exterior discarded',lightPosition:light.position.toArray(),lightIntensity:light.intensity,shadowMap:light.shadow.mapSize.toArray(),normalBiasMM:light.shadow.normalBias*1000,normalizedDepthBias:light.shadow.bias,filter:'PCFSoft; numerical filter, not a measured light source size',frustumMM:{width:(c.right-c.left)*1000,height:(c.top-c.bottom)*1000},irisReceiver:'fitted refracted iris hit, inverse-view projected into key shadow map; incident-light refraction not simulated; clearcoat shares direct-light shadow approximation',ambientOcclusionAdded:false,geometryChanged:false});
 const api={report,enabled(on){if(disposed)throw Error('Shadow diagnostic disposed');U.uE3Enabled.value=on?1:0;v.render();return report();},dispose(){if(disposed)return;disposed=true;mesh.onBeforeRender=old.render;m.onBeforeCompile=old.compile;m.customProgramCacheKey=old.key;m.shadowSide=old.shadowSide;mesh.castShadow=old.cast;mesh.receiveShadow=old.receive;mesh.customDepthMaterial=old.depth;renderer.shadowMap.enabled=old.enabled;renderer.shadowMap.type=old.type;light.castShadow=old.lightCast;light.shadow.mapSize.copy(old.mapSize);light.shadow.bias=old.bias;light.shadow.normalBias=old.normalBias;light.shadow.radius=old.radius;light.shadow.camera.copy(old.camera);light.shadow.needsUpdate=old.needsUpdate;light.shadow.map?.dispose();light.shadow.map=null;depth.dispose();m.needsUpdate=true;skin.dispose=old.dispose;delete skin.eyeShadowDiagnostic;}};
 skin.eyeShadowDiagnostic=api;skin.dispose=function(){api.dispose();return old.dispose.call(this);};v.render();return api;
}
