import {test} from 'node:test';import assert from 'node:assert/strict';import {snapshot} from './weather-bridge.mjs';
function fixture(overrides={},qa={}){const s={wind:12,direction:270,cloudSpeed:4,hour:16,haze:.16,sunlight:1,skylight:1,fog:.1,rain:.2,humidity:80,windOffset:[1,0,-2],blend:1,seed:4217,weather:'coast',kind:'Sc',playing:true,...overrides};return{api:{qa:{version:'1.1.0-hq',ready:true,frames:9,errors:[],seed:4217,weatherCase:'coast',simulationTimeS:5,motionLinked:false,renderSize:[500,400],...qa},getState:()=>s},loading:false};}
test('native API fixture: west wind blows east in metres',()=>{const f=snapshot(fixture());assert.ok(Math.abs(f.wind.velocityMps[0]-12)<1e-10);assert.ok(Math.abs(f.wind.velocityMps[2])<1e-10);assert.equal(f.cloud.speedMps,4);});
test('kilometres convert once and result cannot mutate source',()=>{let x=fixture();const f=snapshot(x);assert.deepEqual(f.cloud.offsetMetres,[1000,0,-2000]);assert.throws(()=>f.cloud.offsetMetres[0]=4);assert.equal(x.api.getState().windOffset[0],1);});
test('source time scale is never applied again',()=>{const f=snapshot(fixture({timeScale:60}));const b=snapshot(fixture({}, {simulationTimeS:6}),f);assert.equal(b.clock.deltaSeconds,1);});
test('reverse time signals a discontinuity without negative integration',()=>{const f=snapshot(fixture());const b=snapshot(fixture({}, {simulationTimeS:2}),f);assert.equal(b.clock.deltaSeconds,0);assert.equal(b.clock.discontinuity,true);});
test('north wind blows south',()=>assert.deepEqual(snapshot(fixture({direction:0})).wind.velocityMps,[-0,0,12]));
test('east wind blows west',()=>assert.ok(snapshot(fixture({direction:90})).wind.velocityMps[0]<0));
test('independent cloud speed does not modify wind',()=>{assert.equal(snapshot(fixture({cloudSpeed:33})).wind.speedMps,12);});
test('explicit wind link uses wind for drift',()=>{assert.equal(snapshot(fixture({}, {motionLinked:true})).cloud.speedMps,12);});
for(const [name,x]of[['not ready',fixture({}, {ready:false})],['source error',fixture({}, {errors:['GPU']})],['loading',{...fixture(),loading:true}],['blend',fixture({blend:.5})],['seed mismatch',fixture({seed:42})],['weather mismatch',fixture({weather:'rain'})],['invalid clock',fixture({}, {simulationTimeS:NaN})],['invalid wind',fixture({wind:Infinity})],['negative speed',fixture({wind:-1})],['bad offset',fixture({windOffset:[1]})],['wrong API version',fixture({}, {version:'1.0.0-clean'})]])test('reject '+name,()=>assert.throws(()=>snapshot(x)));
test('no legacy interface used',()=>{const f=fixture();f.api.getEnvironment=()=>{throw Error('legacy called')};assert.equal(snapshot(f).identity.weather,'coast');});
test('render light derived convention is unit-length and uncalibrated',()=>{const s=snapshot(fixture());assert.ok(Math.abs(Math.hypot(...s.solar.directionENU)-1)<1e-12);assert.equal(s.solar.calibrated,false);});
test('capabilities and approvals remain explicitly incomplete',()=>{const s=snapshot(fixture());assert.equal(s.capabilities.sharedDepth,false);assert.equal(s.productionApproved,false);});
