import fs from 'node:fs';
import * as K from './r045_round70_kernel.mjs';
import * as R68 from '../round-68/r045_round68_kernel.mjs';
import * as R47 from '../round-47/r045_round47_kernel.mjs';
import * as R30 from '../round-30/r045_round30_kernel.mjs';
const checks=[];const add=(name,pass,value,limit)=>checks.push({name,pass:Boolean(pass),value,limit});
const xs=[];for(let x=-216;x<=114;x+=6)xs.push(x);const zs=[];for(let z=-126;z<=6;z+=6)zs.push(z);
function receiverBand(x,z){return Math.abs(z-R30.riverZ(x))<=R30.riverW(x)+12}
let activeN=0,activeP=0,maskErr=0,stepErr=0,phaseErr=0,indexErr=0,baseErr=0,groupErr=0,thresholdCross=0;
let candidateTotal=0,acceptedNode=0,changed=0,unsupportedChanged=0,inactiveChanged=0,hardChanged=0,receiverChanged=0,strongChanged=0,maxChange=0;
const groups=[0,0,0],changedGroups=new Set(),changedPts=[];
for(const x of xs)for(const z of zs){
 const n=K.terraceStateAt(x,z),p=R68.terraceStateAt(x,z),b=R47.terraceStateAt(x,z),ev=K.r70NodeEvidenceAt(x,z),comp=K.r70ComponentAt(x,z),d=Math.abs(n.delta-p.delta),dd=R30.nearestExtendedDrainageDistance(x,z);
 if(n.mask>.12){activeN++;if(n.groupIndex>=0&&n.groupIndex<3)groups[n.groupIndex]++}if(p.mask>.12)activeP++;if((n.mask>.12)!==(p.mask>.12))thresholdCross++;
 maskErr=Math.max(maskErr,Math.abs(n.mask-b.mask));stepErr=Math.max(stepErr,Math.abs(n.step-b.step));phaseErr=Math.max(phaseErr,Math.abs(n.phase-b.phase));indexErr=Math.max(indexErr,Math.abs(n.index-b.index));baseErr=Math.max(baseErr,Math.abs(n.base-b.base));if(n.groupIndex!==b.groupIndex)groupErr++;
 if(ev.ok){candidateTotal++;if(comp.accepted)acceptedNode++}
 if(d>1e-6){changed++;maxChange=Math.max(maxChange,d);if(!ev.ok||!comp.accepted||K.r70AcceptanceWeightAt(x,z)<.999999)unsupportedChanged++;if(b.mask<=.12)inactiveChanged++;if(dd<=12)hardChanged++;if(receiverBand(x,z))receiverChanged++;if(b.mask>=.82)strongChanged++;changedGroups.add(b.groupIndex);changedPts.push({x,z,change:n.delta-p.delta,mask:b.mask,groupIndex:b.groupIndex,index:b.index,componentSize:comp.size,componentSpan:comp.span,coherence:ev.ev?.coherence||0,runSpan:ev.ev?.span||0,dd})}
}
const summary=K.r70GraphSummary(),acceptedComponents=summary.components.filter(c=>c.accepted),largestEvidence=acceptedComponents[0]||{size:0,span:0},acceptedFamilies=new Set(summary.acceptedFamilies||[]);
const key=(x,z)=>`${x},${z}`,map=new Map(changedPts.map((p,i)=>[key(p.x,p.z),i])),seen=new Set(),changeComps=[];for(let i=0;i<changedPts.length;i++){if(seen.has(i))continue;const q=[i],ids=[];seen.add(i);while(q.length){const a=q.pop(),p=changedPts[a];ids.push(a);for(const dx of [-6,0,6])for(const dz of [-6,0,6]){if(!dx&&!dz)continue;const j=map.get(key(p.x+dx,p.z+dz));if(j===undefined||seen.has(j))continue;const r=changedPts[j];if(r.groupIndex!==p.groupIndex||r.index!==p.index)continue;seen.add(j);q.push(j)}}changeComps.push(ids)}changeComps.sort((a,b)=>b.length-a.length);
const physicalSpan=ids=>{let m=0;for(const i of ids)for(const j of ids){const a=changedPts[i],b=changedPts[j];m=Math.max(m,Math.hypot(a.x-b.x,a.z-b.z))}return m};const largestChanged=changeComps[0]?.length||0,largestChangedSpan=changeComps[0]?physicalSpan(changeComps[0]):0,cellsInRuns=changeComps.filter(c=>c.length>=3&&physicalSpan(c)>=12).reduce((s,c)=>s+c.length,0);
let maxInc=0,maxIncAt=null;for(const p of changedPts){const c=K.terraceDelta(p.x,p.z);for(const[xx,zz]of[[p.x+3,p.z],[p.x-3,p.z],[p.x,p.z+3],[p.x,p.z-3]]){const inc=Math.abs(K.terraceDelta(xx,zz)-c);if(inc>maxInc){maxInc=inc;maxIncAt={x:p.x,z:p.z,xx,zz,inc}}}}
let outside=0,hard=0,receiver=0;for(let x=-216;x<=216;x+=36){for(const z of [-300,-220,-170,-145,30,70,130])outside=Math.max(outside,Math.abs(K.terraceDelta(x,z)-R68.terraceDelta(x,z)));for(let z=-126;z<=6;z+=18)if(R30.nearestExtendedDrainageDistance(x,z)<=12)hard=Math.max(hard,Math.abs(K.terraceDelta(x,z)-R68.terraceDelta(x,z)));const rz=R30.riverZ(x);for(const dz of [-8,0,8])receiver=Math.max(receiver,Math.abs(K.terraceDelta(x,rz+dz)-R68.terraceDelta(x,rz+dz)))}
const sourceSha=process.env.GITHUB_SHA||null;
add('version',K.VERSION==='R045.70',K.VERSION,'R045.70');add('qa_contract',K.R70_CONTRACT==='R045.70-quantized-contour-ribbon-union-v1',K.R70_CONTRACT,'exact contract id');add('source_sha_present',typeof sourceSha==='string'&&sourceSha.length>=7,sourceSha,'workflow source commit recorded');
add('water_graph_identity',JSON.stringify(K.nodes)===JSON.stringify(R68.nodes)&&JSON.stringify(K.edges)===JSON.stringify(R68.edges),{nodes:K.nodes.length,edges:K.edges.length},'exact inherited graph');add('plan_frame_exact',maskErr===0&&stepErr===0&&phaseErr===0&&indexErr===0&&baseErr===0&&groupErr===0,{maskErr,stepErr,phaseErr,indexErr,baseErr,groupErr},'exact frozen R47/R68 mask/group/step/phase/index/base');add('active_footprint_exact',activeN===activeP&&thresholdCross===0,{activeN,activeP,thresholdCross},'exact R68 active footprint');
add('macro_evidence_material',candidateTotal>=20&&acceptedNode>=12&&acceptedComponents.length>=2&&acceptedFamilies.size>=2,{candidateTotal,acceptedNode,acceptedComponents:acceptedComponents.length,acceptedFamilies:[...acceptedFamilies]},'>=20 frozen candidates, >=12 accepted nodes, >=2 accepted same-index ribbons across >=2 families');add('macro_evidence_span',largestEvidence.size>=4&&largestEvidence.span>=24,largestEvidence,'largest frozen same-index ribbon >=4 nodes and >=24m physical span');
add('profile_change_material',changed>=8&&maxChange>.010,{changed,maxChange},'>=8 physical changes and max change >10mm');add('multi_family_change',changedGroups.size>=2,[...changedGroups],'>=2 terrace families participate');add('changed_run_material',largestChanged>=3&&largestChangedSpan>=12&&cellsInRuns>=6,{largestChanged,largestChangedSpan,cellsInRuns,changeComponents:changeComps.length},'physical changes include compatible same-index runs; >=6 changed cells in >=3-cell/12m runs');
add('all_changes_supported',unsupportedChanged===0,unsupportedChanged,'every changed 6m node belongs to precomputed accepted same-index ribbon evidence');add('inactive_exact',inactiveChanged===0,inactiveChanged,'zero change at inherited mask <=0.12');add('strong_exact',strongChanged===0,strongChanged,'zero change at inherited mask >=0.82');add('hard_drainage_exact',hardChanged===0&&hard<1e-12,{hardChanged,hard},'zero change in <=12m drainage core');add('foreground_receiver_exact',receiverChanged===0&&receiver<1e-12,{receiverChanged,receiver},'zero change in receiver +12m band');add('outside_exact',outside<1e-9,outside,'zero outside terrace support domain');add('height_change_bounded',maxChange<=.0700001,maxChange,'R70-R68 <=0.070m per authoritative node');add('three_meter_cliff_gate',maxInc<1.05,{maxInc,maxIncAt},'<1.05m terrace increment / 3m at every changed 6m node');add('three_groups_retained',groups.every(v=>v>20),groups,'three terrace families retained');
add('locks_retained',K.snapshot.visualAcceptance===false&&K.snapshot.parcelGenerationEnabled===false&&K.snapshot.waterStateKnown===false&&K.snapshot.productionReady===false,{visual:K.snapshot.visualAcceptance,parcel:K.snapshot.parcelGenerationEnabled,water:K.snapshot.waterStateKnown,production:K.snapshot.productionReady},'all false pending fixed-view review');add('logic_fallacy_explicit',K.snapshot.round70?.logicCorrection?.includes('double-filter')&&K.snapshot.round70?.logicCorrection?.includes('does not'),K.snapshot.round70?.logicCorrection,'quantized edge misalignment != missing contour evidence; more nodes != visual acceptance');add('field_constraint_explicit',K.snapshot.round70?.constraint?.includes('synthetic morphology/QA')&&K.snapshot.round70?.constraint?.includes('cannot recover'),K.snapshot.round70?.constraint,'field truth missing');add('xiaoma_boundary_retained',K.snapshot.round70?.xiaomaBoundary?.includes('do not establish'),K.snapshot.round70?.xiaomaBoundary,'geometry != hydraulic truth');add('mrrolord_ordering_only',K.snapshot.round70?.mrRolordUse?.includes('hydrology-first ordering')&&K.snapshot.round70?.mrRolordUse?.includes('not agricultural truth'),K.snapshot.round70?.mrRolordUse,'ordering only');add('reference_reread_honest',K.snapshot.round70?.referenceUse?.includes('re-resolved and reread')&&K.snapshot.round70?.referenceUse?.includes('non-metric'),K.snapshot.round70?.referenceUse,'exact image reread; non-metric use only');
const result={version:K.VERSION,qaContract:K.R70_CONTRACT,sourceSha,passed:checks.every(c=>c.pass),gateCount:checks.length,passedCount:checks.filter(c=>c.pass).length,checks,metrics:{activeN,activeP,groups,candidateTotal,acceptedNode,acceptedComponents:acceptedComponents.length,acceptedFamilies:[...acceptedFamilies],largestEvidence,changed,changedGroups:[...changedGroups],largestChanged,largestChangedSpan,cellsInRuns,changeComponentCount:changeComps.length,maxChange,maxInc,maxIncAt,inactiveChanged,unsupportedChanged,hardChanged,receiverChanged,strongChanged,outside,hard,receiver,changedPoints:changedPts,graphSummary:{candidateNodes:summary.candidateNodes,acceptedNodes:summary.acceptedNodes,rejectedNodes:summary.rejectedNodes,acceptedComponents:summary.acceptedComponents,acceptedFamilies:summary.acceptedFamilies,components:summary.components.slice(0,24)},qaScope:'authoritative 6m whole-slope same-family + exact-index quantized contour-ribbon union over frozen R47/R68 footprint; frozen bilateral run evidence + bounded full-phase profile expression + exact drainage/footprint locks + 3m local cliff checks + source provenance'}};fs.writeFileSync(new URL('./r045_round70_qa_result.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.passed)process.exitCode=2;
