import fs from 'node:fs';
import * as K from './r045_round70_kernel.mjs';
import * as B from '../round-68/r045_round68_kernel.mjs';
import * as R47 from '../round-47/r045_round47_kernel.mjs';
import {AUDIT as A58} from '../round-58/r045_round58_audit_cache.mjs';
const src=A58.terrain,x0=src.x0,x1=src.x1,z0=src.z0,z1=src.z1,nx=Math.max(12,Math.floor(src.nx/2)),nz=Math.max(8,Math.floor(src.nz/2)),dx=(x1-x0)/nx,dz=(z1-z0)/nz,before=[],after=[];
for(let j=0;j<=nz;j++){const z=z0+j*dz,ra=[],rb=[];for(let i=0;i<=nx;i++){const x=x0+i*dx;ra.push(B.height(x,z));rb.push(K.height(x,z))}before.push(ra);after.push(rb)}
const rivers=[];for(let x=x0;x<=x1+.01;x+=24){const z=K.riverZ(x);rivers.push([x,z,B.height(x,z)+.28,K.height(x,z)+.28])}
const plan=[];for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const x=x0+(i+.5)*dx,z=z0+(j+.5)*dz,n=K.terraceStateAt(x,z),p=B.terraceStateAt(x,z),r=R47.terraceStateAt(x,z),ev=K.r70NodeEvidenceAt(x,z),comp=K.r70ComponentAt(x,z);plan.push({i,j,mask:n.mask,groupIndex:n.groupIndex,frac:n.frac,dd:K.nearestExtendedDrainageDistance(x,z),change:n.delta-p.delta,priorMask:r.mask,candidate:ev.ok,accepted:comp.accepted,componentSize:comp.size,componentSpan:comp.span})}
let qr={metrics:{changedPoints:[]}};try{qr=JSON.parse(fs.readFileSync(new URL('./r045_round70_qa_result.json',import.meta.url),'utf8'))}catch{}
const exactChanges=(qr.metrics?.changedPoints||[]).filter(p=>Math.abs(p.change)>1e-6);
function qAt(x,z){const s=R47.terraceStateAt(x,z);return s.base+s.phase}function normalAt(x,z){const e=.75,gx=(qAt(x+e,z)-qAt(x-e,z))/(2*e),gz=(qAt(x,z+e)-qAt(x,z-e))/(2*e),m=Math.hypot(gx,gz)||1;return[gx/m,gz/m]}
const centers=[...exactChanges].sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,2).map(p=>[p.x,p.z]);const profiles=centers.map(([x,z])=>{const[nx_,nz_]=normalAt(x,z),samples=[];for(let d=-4.8;d<=4.8001;d+=.60){const xx=x+d*nx_,zz=z+d*nz_;samples.push([d,B.height(xx,zz),K.height(xx,zz),B.terraceDelta(xx,zz),K.terraceDelta(xx,zz)])}return{x,z,nx:nx_,nz:nz_,samples}});
let changeMax=0,coarseChanged=0,active=0,acceptedPlan=0,candidatePlan=0;for(const c of plan){changeMax=Math.max(changeMax,Math.abs(c.change));if(Math.abs(c.change)>.002)coarseChanged++;if(c.mask>.12)active++;if(c.candidate)candidatePlan++;if(c.accepted)acceptedPlan++}
const data={version:K.VERSION,qaContract:K.R70_CONTRACT,sourceSha:qr.sourceSha||null,terrain:{x0,x1,z0,z1,nx,nz,before,after},rivers,planSpec:{x0,x1,z0,z1,nx,nz},plan,exactChanges,profiles,state:{changeMax,coarseChanged,exactChanged:exactChanges.length,active,candidatePlan,acceptedPlan,qaPassed:qr.passed===true},generatedAt:new Date().toISOString(),source:'R045.70 fixed view: A evaluates accepted R68; B strengthens only frozen bilateral contour evidence joined by exact inherited family+terrace-index identity. The visual cache is deliberately coarser than authoritative numeric QA for runtime only; all acceptance numbers remain the 6 m whole-slope QA. Orange markers are exact changed QA nodes; no footprint growth or hydraulic truth is claimed.'};
fs.writeFileSync(new URL('./r045_round70_audit_cache.mjs',import.meta.url),`export const AUDIT=${JSON.stringify(data)};\n`);console.log(JSON.stringify({version:data.version,vertices:(nx+1)*(nz+1),planCells:plan.length,profiles:profiles.length,state:data.state},null,2));
