import fs from 'node:fs';
import * as K from './r045_round51_kernel.mjs';
import * as B from '../round-47/r045_round47_kernel.mjs';
const x0=-222,x1=120,z0=-132,z1=12,nx=38,nz=16,dx=(x1-x0)/nx,dz=(z1-z0)/nz;
const before=[],after=[];for(let j=0;j<=nz;j++){const z=z0+j*dz,rb=[],ra=[];for(let i=0;i<=nx;i++){const x=x0+i*dx;rb.push(B.height(x,z));ra.push(K.height(x,z))}before.push(rb);after.push(ra)}
const rivers=[];for(let x=x0;x<=x1;x+=12){const z=K.riverZ(x);rivers.push([x,z,B.height(x,z)+.28,K.height(x,z)+.28])}
const plan=[];for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const x=x0+(i+.5)*dx,z=z0+(j+.5)*dz,n=K.terraceStateAt(x,z),o=B.terraceStateAt(x,z);plan.push({i,j,mask:n.mask,oldMask:o.mask,groupIndex:n.groupIndex,frac:n.frac,dd:K.nearestExtendedDrainageDistance(x,z),delta:n.delta,gain:n.mask-o.mask,support:n.contourFrontShellSupport})}
let dmax=0,active=0,gains=0,cross=0,gc=[0,0,0],gg=[0,0,0],minA=1,minAQ=1,maxTurn=0;const dirs=new Set();for(let x=x0;x<=x1;x+=6)for(let z=z0;z<=z1;z+=6){const st=K.terraceStateAt(x,z),old=B.terraceStateAt(x,z);dmax=Math.max(dmax,Math.abs(st.delta));if(st.mask>.12){active++;if(st.groupIndex>=0&&st.groupIndex<3)gc[st.groupIndex]++}if(st.mask-old.mask>.004){gains++;if(st.groupIndex>=0&&st.groupIndex<3)gg[st.groupIndex]++;if(st.contourFrontShellSupport){dirs.add(st.contourFrontShellSupport.direction);minA=Math.min(minA,st.contourFrontShellSupport.alignment);minAQ=Math.min(minAQ,st.contourFrontShellSupport.supportAlignment);maxTurn=Math.max(maxTurn,st.contourFrontShellSupport.tangentTurnDeg)}}if(old.mask<=.12&&st.mask>.12)cross++}
const data={version:K.VERSION,terrain:{x0,x1,z0,z1,nx,nz,before,after},rivers,planSpec:{x0,x1,z0,z1,nx,nz},plan,state:{dmax,active,gains,cross,groups:gc,gainGroups:gg,directions:[...dirs],minAlignment:Number.isFinite(minA)?minA:null,minSupportAlignment:Number.isFinite(minAQ)?minAQ:null,maxTurn},generatedAt:new Date().toISOString(),source:'R045.51 frozen-R47 contour-tangent one-shell / R045.47 accepted predecessor; reduced fixed-view mesh only, authoritative QA remains 6m'};
fs.writeFileSync(new URL('./r045_round51_audit_cache.mjs',import.meta.url),`export const AUDIT=${JSON.stringify(data)};\n`);console.log(JSON.stringify({version:data.version,terrainVertices:(nx+1)*(nz+1),planCells:plan.length,state:data.state},null,2));
