import * as THREE from '../source/registration-vendor/three.module.js';
import {OrbitControls} from '../ui/vendor/OrbitControls.js';
import {loadCommon} from '../ui/load-common.mjs';
import {defaultState} from '../src/State.mjs';
import {PRESETS,createPresetState} from '../ui/PresetCatalogueR2.mjs';
import {AnimatedHuman} from '../boxing/AnimatedHuman.mjs';
import {HandBodyCoordinator,TASKS} from './HandBodyCoordinator.mjs';
import {calibrateSphereGrasp,measurePropVertexClearance} from './SurfaceGraspCalibration.mjs';
const $=id=>document.getElementById(id),labels=['张手','握拳','捏握','抓物','双手抱物','伸手转身'];let loaded,human,rig,scene,camera,renderer,orbit,group,prop,ball,graspCalibration,builtShape=null,ready=false,busy=false,playing=false,t=3,last=0,close=false,azimuth=0,handAngle='front';
for(let i=0;i<PRESETS.length;i++){const o=document.createElement('option');o.value=i;o.textContent=PRESETS[i].label;$('shape').append(o)}$('shape').value=12;
TASKS.forEach((task,i)=>{const o=document.createElement('option');o.value=task;o.textContent=labels[i];$('task').append(o)});$('task').value='fist';
function rebuild(){human?.dispose();group?.clear();const state=createPresetState(PRESETS[+$('shape').value].id,defaultState);loaded.model.compute(state);human=new AnimatedHuman(loaded.model,state);rig=new HandBodyCoordinator({...human.rig,stature:human.height,floorOffset:human.floorOffset});graspCalibration=calibrateSphereGrasp(human,rig);builtShape=+$('shape').value;group.add(human.mesh);group.position.y=human.floorOffset;render();view();}
function view(){if(!human)return;const h=human.height,m=rig.result.hands?.L?.position,asView=v=>new THREE.Vector3(v[0],v[2],-v[1]);let center,direction;
if(close&&m){const j=rig.index.get('wrist.L'),r=rig.skinMatrices[j],rot=v=>[r[0]*v[0]+r[1]*v[1]+r[2]*v[2],r[4]*v[0]+r[5]*v[1]+r[6]*v[2],r[8]*v[0]+r[9]*v[1]+r[10]*v[2]],f=asView(rot(rig.hand.L.forward)).normalize(),p=asView(rot(rig.hand.L.palm)).normalize(),across=new THREE.Vector3().crossVectors(f,p).normalize();center=new THREE.Vector3(m[0],m[2]+human.floorOffset,-m[1]).addScaledVector(f,h*.046);direction=handAngle==='palm'?p:handAngle==='side'?across.clone().negate():f.clone().addScaledVector(p,-.2).normalize();camera.up.copy(handAngle==='palm'?f:p.clone().negate());camera.position.copy(center).addScaledVector(direction,h*.245);}
else{center=new THREE.Vector3(0,h*.52,0);camera.up.set(0,1,0);camera.position.copy(center).add(new THREE.Vector3(Math.sin(azimuth)*h*1.9,h*.38,Math.cos(azimuth)*h*1.9));}orbit.target.copy(center);orbit.update();renderer.render(scene,camera);}

function render(){if(!rig)return;const r=rig.evaluate(t,{task:$('task').value,fistTension:$('tension').value,contactOffsets:$('task').value==='grasp'?{L:graspCalibration.offset}:null});human.animate(r.skinMatrices);prop.visible=$('task').value==='carry';ball.visible=$('task').value==='grasp';const p=r.object.position;prop.position.set(p[0],p[2]+human.floorOffset,-p[1]);prop.scale.setScalar(human.height/1.7);ball.position.copy(prop.position);ball.scale.setScalar(r.object.radius);$('time').value=t;$('stats').textContent=`${human.N} vertices / ${human.faces.length/3} triangles / ${human.names.length} bones / CSR max ${human.report.maxInfluences}\n${r.state.phase} · ${t.toFixed(2)} s · wrist target error ${(r.metrics.maxHandErrorM*1000).toFixed(2)} mm\nthumb/index skeleton-tip gap ${(r.hands.L.thumbIndexGapM*1000).toFixed(2)} mm · proxy only, not skin contact\nprop shown as authored target; Jolt adapter is separate, no physical load feedback`;renderer.render(scene,camera);}
async function start(){if(ready||busy)return;busy=true;$('status').textContent='校验现有资产';try{loaded=await loadCommon({onProgress:p=>$('status').textContent=`载入 ${Math.round(p.fraction*100)}%`});renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true});renderer.setPixelRatio(1);renderer.setSize(innerWidth,$('canvas').clientHeight,false);scene=new THREE.Scene();scene.background=new THREE.Color('#17252f');camera=new THREE.PerspectiveCamera(35,innerWidth/$('canvas').clientHeight,.01,50);orbit=new OrbitControls(camera,$('canvas'));orbit.addEventListener('change',()=>renderer.render(scene,camera));scene.add(new THREE.HemisphereLight(0xe1efff,0x665040,2.5));const sun=new THREE.DirectionalLight(0xffe0c8,3);sun.position.set(-3,5,4);scene.add(sun);group=new THREE.Group();scene.add(group);const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshStandardMaterial({color:0x344a51,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.005;scene.add(floor);prop=new THREE.Mesh(new THREE.BoxGeometry(.23,.18,.16),new THREE.MeshStandardMaterial({color:0xcc9856,transparent:true,opacity:.55}));scene.add(prop);ball=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshStandardMaterial({color:0xcc9856,roughness:.65}));scene.add(ball);rebuild();ready=true;$('status').textContent='原人物已载入';$('start').disabled=true;requestAnimationFrame(tick);}catch(e){$('status').textContent=e.message;window.handError=e.stack;}finally{busy=false;}}
function tick(now){if(playing){t+=Math.min((now-last)/1000,.04);if(t>6){t=0;rig.previousGrip=false;}render();if(close)view();}last=now;requestAnimationFrame(tick);}
$('start').onclick=start;$('play').onclick=()=>playing=!playing;$('task').onchange=()=>{rig&&(rig.previousGrip=false);render();view()};$('shape').onchange=()=>ready&&rebuild();$('time').oninput=e=>{playing=false;t=+e.target.value;render();if(close)view()};$('body').onclick=()=>{close=false;view()};$('hand').onclick=()=>{close=true;view()};$('front').onclick=()=>{azimuth=0;handAngle='front';view()};$('side').onclick=()=>{azimuth=Math.PI*.5;handAngle='side';view()};$('palm').onclick=()=>{close=true;handAngle='palm';view()};$('tension').onchange=()=>{render();view()};
window.handWorkbench={start,get ready(){return ready},get human(){return human},get rig(){return rig},set({shape,task,time=3,hand=false,side=false,angle=null,tension='tight'}){playing=false;if(shape!==undefined&&shape!==builtShape){$('shape').value=shape;rebuild()}if(task)$('task').value=task;t=time;close=hand;azimuth=side?Math.PI*.5:0;handAngle=angle||(side?'side':'front');$('tension').value=tension;render();view();},diagnostics(){return{ready,shape:PRESETS[+$('shape').value].id,...human?.report,...rig?.validate(),state:rig?.result.state,hands:rig?.result.hands,graspCalibration,propClearance:human&&['grasp','carry'].includes(rig.result.state.task)?measurePropVertexClearance(human,rig.result.object):null}}};
