import{installBonyLandmarkLayer}from'./BonyLandmarkLayer.mjs';
import{loadCommon}from'../ui/load-common.mjs';import{CommonViewer}from'../ui/Viewer.mjs';import{defaultState}from'../src/State.mjs';import{installNativeAdiposeLayer}from'../shape-r03/NativeAdiposeLayer.mjs';import{CASES,createState,oldState}from'./Catalogue.mjs';
const $=id=>document.getElementById(id);let model,viewer,current=CASES.find(c=>c.id==='long_narrow'),version='new',camera=null,viewName='face',faceAction='neutral',active=true,loading=false,generation=0,aborter,resume=false;
for(const c of CASES){const o=document.createElement('option');o.value=c.id;o.textContent=c.label;$('preset').append(o)}
$('preset').value=current.id;
function apply(){if(!model)return;model.r03Adipose.set(-.45);model.r031Bony.set(version==='old'?0:1);const s=version==='old'?oldState(defaultState):createState(current.id,defaultState);if(faceAction!=='neutral'){s.owners.expression='anny';s.anny.facialActions=faceAction==='blink'?{eyeBlinkLeft:1,eyeBlinkRight:1}:{jawOpen:.55};}model.compute(s);viewer.update();if(camera)viewer.restoreCamera(camera);$('old').setAttribute('aria-pressed',String(version==='old'));$('new').setAttribute('aria-pressed',String(version==='new'));$('metrics').textContent=current.id+'\n'+(version==='old'?'已交R03瘦体':'R03.1研究候选')+'\n25417顶点 / 50624三角 / 104 Anny骨';}
function view(name){viewName=name;if(!viewer)return;viewer.view(name.startsWith('face')?'face':name.startsWith('detail')?'front':name);camera=viewer.cameraState();let angle=name.endsWith('side')?Math.PI/2:name.endsWith('three')?.55:0;
 if(name.startsWith('detail')){let lo=Infinity,hi=-Infinity;for(let i=2;i<model.positions.length;i+=3){lo=Math.min(lo,model.positions[i]);hi=Math.max(hi,model.positions[i]);}camera.target[1]=lo+(hi-lo)*(name==='detail-leg'?.32:.70);const d=(hi-lo)*(name==='detail-leg'?.66:.75);camera.position=[camera.target[0]+Math.sin(angle)*d,camera.target[1],camera.target[2]+Math.cos(angle)*d];}
 else if(name.startsWith('face')&&angle){const d=camera.position[2]-camera.target[2];camera.position=[camera.target[0]+Math.sin(angle)*d,camera.position[1],camera.target[2]+Math.cos(angle)*d];}viewer.restoreCamera(camera);return camera;}
async function load(){if(model||loading||!active)return;loading=true;const ticket=++generation;aborter=new AbortController();$('load').disabled=true;try{const r=await loadCommon({signal:aborter.signal,onProgress:p=>$('status').textContent='载入校验 '+Math.round(p.fraction*100)+'%'});if(!active||ticket!==generation)return;model=r.model;installNativeAdiposeLayer(model);installBonyLandmarkLayer(model);model.r031Bony.set(1);model.r03Adipose.set(-.45);model.compute(createState(current.id,defaultState));viewer=new CommonViewer({canvas:$('canvas'),container:$('stage'),model,onStatus:t=>$('status').textContent=t});const saved=camera;apply();if(saved)viewer.restoreCamera(saved);else view(viewName);$('status').textContent='脸身份阶段已验 · 骨性表达仍未完成';}catch(e){if(ticket!==generation||e.name==='AbortError')return;$('status').textContent=e.message;$('load').disabled=false;throw e;}finally{if(ticket===generation){loading=false;aborter=null}}}
function select(id){current=CASES.find(x=>x.id===id);if(!current)throw Error('Unknown case');$('preset').value=id;version='new';faceAction='neutral';camera=null;apply();view(viewName)}
$('load').onclick=load;$('preset').onchange=()=>select($('preset').value);$('old').onclick=()=>{version='old';apply()};$('new').onclick=()=>{version='new';apply()};for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>{faceAction=b.dataset.action;apply()};
function study(enabled){if(!viewer)return;viewer.skin.set({enabled:!enabled});const lights=viewer.scene.children.filter(x=>x.isLight);for(const light of lights){if(!light.userData.original)light.userData.original={intensity:light.intensity,position:light.position.toArray()};}if(enabled){lights[0].intensity=.28;lights[1].intensity=3.1;lights[1].position.set(-3,2,1);lights[2].intensity=.3;}else for(const light of lights){light.intensity=light.userData.original.intensity;light.position.fromArray(light.userData.original.position);}viewer.render();}
$('study').onchange=()=>study($('study').checked);
window.shapeR31={study,action:a=>{faceAction=a;apply()},load,ready:()=>!!viewer,cases:()=>CASES,select,version:v=>{version=v;apply()},view,camera:()=>viewer.cameraState(),positions:()=>Array.from(model.positions),metrics:()=>model.metrics(),pixels:()=>viewer.pixelAudit(),recipe:()=>({schema:'r03.1-native-identity-probe/1',caseId:current.id,common:model.archive(),adipose:{schema:model.r03Adipose.schema,amount:-.45},bony:{schema:model.r031Bony.schema,amount:model.r031Bony.settings.amount,report:model.r031Bony.last}})};
addEventListener('pagehide',()=>{resume=!!viewer;if(viewer)camera=viewer.cameraState();active=false;generation++;aborter?.abort();loading=false;viewer?.dispose();viewer=null;model=null;const c=$('canvas');c.replaceWith(c.cloneNode(false));$('load').disabled=false});addEventListener('pageshow',e=>{active=true;if(e.persisted&&resume)void load()});
