from pathlib import Path
import hashlib
src=Path('workbenches/landscape-function/index.html')
out=Path('workbenches/landscape-surface-r5/index.html')
s=src.read_text()
def rep(a,b):
 global s
 if a not in s: raise SystemExit('missing anchor: '+a[:80])
 s=s.replace(a,b,1)
rep('<title>Landscape Mother · 水蚀石灰岩</title>','<title>Landscape Mother · 水蚀石灰岩 R5 表面显微层</title>')
rep('<h1>葡萄峰丛 · 水蚀岩壁</h1>','<h1>葡萄峰丛 · 水蚀岩壁 R5</h1>')
rep('<span id="seedlabel">种子 83</span> · 79.2 KB','<span id="seedlabel">种子 83</span> · 表面显微层')
rep('</details><h4>表面 / 不改变几何</h4><div class="row"><label for="micro">微表面</label><output id="microOut">1.00</output></div><input id="micro" type="range" min="0" max="1.4" step=".05" value="1"><div class="row"><label for="moss">苔藓覆盖</label>', '</details><h4>表面 / 不改变宏观几何</h4><div class="row"><label for="scope">Microscope 壳层</label><output id="scopeOut">0.82</output></div><input id="scope" type="range" min="0" max="1.35" step=".05" value=".82"><small>只在现有岩石表面采样并改变微法线与粗糙度，不参与峰体、洞口、峰脚和落石位置。</small><div class="row"><label for="micro">Brick 微表面</label><output id="microOut">0.70</output></div><input id="micro" type="range" min="0" max="1.4" step=".05" value=".70"><div class="row"><label for="moss">苔藓覆盖</label>')
rep('<button data-mode="3">法线</button><button data-mode="4">来水</button>','<button data-mode="3">法线</button><button data-mode="4">来水</button><button data-mode="5">显微壳层</button>')
rep('<p>延续 Brick Mother 的石材配方及本线原岩布局。新增的分叉裂隙、嵌套孔腔和表面下行沟道均参与三维体积；显微凹凸仅改变着色法线。孔腔尺寸与形成阶段为构造假设，未映射成年数。</p>','<p>延续此前已获有限正向反馈的水蚀岩体主形。R5 将 Macroscopic microscope 严格限制在现有岩石表面层：峰体轮廓、主洞口、峰脚、落石和土体缓冲完全沿用基线；显微层只读取固定世界坐标并改变微法线、粗糙度与极小尺度表面响应。</p><p>显微层采用对数半径、方向比值、方位角与17级倍频的尺度组织，再通过位置相关连续空间弯折打散明显重复。它不会进入宏观体积场，也不会重新造山。调节“Microscope 壳层”时，几何缓冲保持逐字节不变。</p>')
rep('<p id="details"></p>','<p><b>层级约束：</b>宏观主形层负责峰体与洞口；结构层负责裂隙、溶蚀和来水；Microscope 只在表面显示层工作；岩性色彩、湿痕与苔藓最后读取同一固定表面。各层职责不互相越界。</p><p id="details"></p>')
rep('uniform vec3 uEye;uniform float uExposure,uWet,uMicro,uMoss;uniform int uMode,uSection,uSelect;uniform float uStage;','uniform vec3 uEye;uniform float uExposure,uWet,uMicro,uMoss,uScope;uniform int uMode,uSection,uSelect;uniform float uStage;')
rep('float noise(vec3 p){return bmN(p);}\n','float noise(vec3 p){return bmN(p);}\nvec3 mmAxisRotate(vec3 v,vec3 axis,float a){axis=normalize(axis);float c=cos(a),ss=sin(a);return c*v+ss*cross(axis,v)+(1.-c)*axis*dot(axis,v);}\nvec3 mmFrame(vec3 rawQ){vec3 q=rawQ*.155+vec3(5.7,-3.9,2.6);float R=max(length(q),1e-5),lr=log2(R);vec3 w=vec3(bmN(q*.41+vec3(3.1,7.2,-2.4)),bmN(q*.37+vec3(-8.3,2.7,4.6)),bmN(q*.43+vec3(1.5,-6.4,9.1)))-.5;q+=.38*w;float a=.24*(.62*sin(lr*2.15+q.y*.31)+.38*sin(q.z*.47-q.x*.29));q=mmAxisRotate(q-vec3(.8,-.4,.3),normalize(vec3(.31,.86,.39)),a)+vec3(.8,-.4,.3);float b=.10*sin(lr*3.4+q.x*.21-q.z*.17);q=mmAxisRotate(q-vec3(-1.2,.7,-.6),normalize(vec3(-.72,.18,.67)),b)+vec3(-1.2,.7,-.6);return q;}\nfloat mmCore(vec3 q){float R=max(length(q),1e-6);vec3 z=vec3(log2(R)-2.2,-q.z/R,atan(q.x,q.y));z.y-=1.;float e=z.y,sc=1.;for(int j=0;j<17;j++){e+=cos(dot(cos(z.zyy*sc),cos(z.xyx*sc)))/sc;sc+=sc;}return e;}\nfloat mmSurface(vec3 rawQ){vec3 q=mmFrame(rawQ);float a=mmCore(q);vec3 q2=mmFrame(rawQ+vec3(11.3,-7.1,5.9));float b=mmCore(mmAxisRotate(q2,normalize(vec3(.27,.61,-.74)),.37));return .67*a+.33*b;}\n')
rep('float pore=smoothstep(.66,.86,grain)*smoothstep(.41,.65,drift);float height=field*.012+(grain-.5)*.0035-pore*.006;\nrough=clamp','float pore=smoothstep(.66,.86,grain)*smoothstep(.41,.65,drift);float mmv=mmSurface(q),mmLo=tanh(mmv*.70),mmFine=tanh(mmSurface(q*1.73+vec3(2.9,-1.7,4.1))*.62);float shell=(d.x<2.5?1.:0.)*uScope;float height=field*.010+(grain-.5)*.0030-pore*.005+shell*(mmLo*.0085+mmFine*.0038);\nrough=clamp')
rep('rough=clamp((family==1?.92:family==2?.91:family==5?.88:.80)+.12*(drift-.5)-mineral*fresh*.08,.62,.99);','rough=clamp((family==1?.92:family==2?.91:family==5?.88:.80)+.12*(drift-.5)-mineral*fresh*.08+shell*.055*mmFine,.58,.99);albedo*=1.+shell*.035*mmLo;')
rep('if(uMode==3){frag=vec4(normalize(n0)*.5+.5,1.);return;}if(uMode==4){frag=vec4(mix(vec3(.22,.25,.22),vec3(.19,.66,.89),clamp(e.z,0.,1.)),1.);return;}','if(uMode==3){frag=vec4(normalize(n0)*.5+.5,1.);return;}if(uMode==4){frag=vec4(mix(vec3(.22,.25,.22),vec3(.19,.66,.89),clamp(e.z,0.,1.)),1.);return;}if(uMode==5){float v=.5+.34*tanh(mmSurface(q)*.70);frag=vec4(vec3(v),1.);return;}')
s=s.replace('state={theta:.50,phi:1.26,radius:116,target:[-3,20,0],mode:0,section:false,micro:1,wet:0,exposure:1.05,moss:1,grass:true,selected:0}','state={theta:.50,phi:1.26,radius:116,target:[-3,20,0],mode:0,section:false,scope:.82,micro:.70,wet:0,exposure:1.08,moss:1,grass:true,selected:0}')
s=s.replace("['uVP','uEye','uExposure','uWet','uMicro','uMoss','uMode'", "['uVP','uEye','uExposure','uWet','uMicro','uMoss','uScope','uMode'")
s=s.replace('gl.uniform1f(U.uMicro,state.micro);gl.uniform1f(U.uMoss,state.moss);','gl.uniform1f(U.uMicro,state.micro);gl.uniform1f(U.uMoss,state.moss);gl.uniform1f(U.uScope,state.scope);')
s=s.replace("for(let k of ['micro','wet','exposure','moss'])", "for(let k of ['scope','micro','wet','exposure','moss'])")
s=s.replace("'exposure,grass,micro,mode,moss,phi,radius,section,selected,target,theta,wet'", "'exposure,grass,micro,mode,moss,phi,radius,scope,section,selected,target,theta,wet'")
s=s.replace("for(let k of ['theta','phi','radius','micro','wet','exposure','moss'])", "for(let k of ['theta','phi','radius','scope','micro','wet','exposure','moss'])")
s=s.replace('v.micro<0||v.micro>1.4||v.wet<0','v.scope<0||v.scope>1.35||v.micro<0||v.micro>1.4||v.wet<0')
s=s.replace('!Number.isInteger(v.mode)||v.mode<0||v.mode>4','!Number.isInteger(v.mode)||v.mode<0||v.mode>5')
s=s.replace("for(let k of ['micro','wet','exposure','moss'])$('#'+k).oninput", "for(let k of ['scope','micro','wet','exposure','moss'])$('#'+k).oninput")
s=s.replace('micro:1,wet:0,exposure:1.05,moss:1','scope:.82,micro:.70,wet:0,exposure:1.08,moss:1')
s=s.replace("for(let k of ['micro','wet','exposure','moss'])if(k in o)", "for(let k of ['scope','micro','wet','exposure','moss'])if(k in o)")
s=s.replace("release:'karst-water-2'", "release:'karst-surface-shell-r5'")
s=s.replace('水蚀岩壁 · 拖动旋转 / 滚轮缩放','水蚀岩壁 · microscope 仅表面 · 拖动旋转 / 滚轮缩放')
out.parent.mkdir(parents=True,exist_ok=True); out.write_text(s)
b=out.read_bytes(); print(len(b),hashlib.sha256(b).hexdigest())
assert len(b)==81724 and hashlib.sha256(b).hexdigest()=='989ca4f976daa205f8e87699d23b1bf68f94b12a486395c7272df6b38d8304e7'
