/* Weather Mother 1.1.0. Numerical optics, no imported or persisted image assets.
   Multi-band diffraction appearance approximation; not a full Mie solver. */
(function(root){'use strict';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hash(n){n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return((n^(n>>>16))>>>0)/4294967296;}
function j1(x){if(Math.abs(x)<8){let term=x*.5,sum=term;for(let k=1;k<32;k++){term*=-(x*x*.25)/(k*(k+1));sum+=term;if(Math.abs(term)<1e-14)break;}return sum;}const y=1/x,phase=x-3*Math.PI/4,amp=Math.sqrt(2/(Math.PI*x));return amp*(Math.cos(phase)*(1+15*y*y/128)-Math.sin(phase)*(3*y/8-315*y*y*y/3072));}
function airy(x){if(Math.abs(x)<1e-5)return 1;const v=2*j1(x)/x;return v*v;}
function diffractionRGB(theta,radius){const rgb=[0,0,0],norm=[0,0,0];for(let k=0;k<9;k++){const nm=420+k*35,lambda=nm*.001,weight=[Math.exp(-Math.pow((nm-612)/48,2)),Math.exp(-Math.pow((nm-542)/43,2)),Math.exp(-Math.pow((nm-454)/36,2))];let value=0;for(let j=-1;j<=1;j++){let r=radius*(1+j*.027),x=4*Math.PI*r*Math.sin(theta*.5)/lambda;value+=airy(x)*(j===0?.5:.25);}for(let c=0;c<3;c++){rgb[c]+=value*weight[c];norm[c]+=weight[c];}}for(let c=0;c<3;c++)rgb[c]/=norm[c];let lum=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];if(lum<1e-12)return[1,1,1,0];return[...rgb.map(v=>clamp(v/lum,.035,3.8)),clamp(lum*5e3)];}
function makeDiffractionLUT(){const width=384,height=96,data=new Float32Array(width*height*4);let i=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const v=diffractionRGB((x+.5)/width*(40*Math.PI/180),1+(y+.5)/height*15);for(let k=0;k<4;k++)data[i++]=v[k];}return{width,height,data,angleDegrees:[0,40],radiusMicrometres:[1,16],method:'nine-band circular-aperture diffraction appearance LUT; three-size averaging'};}
function strokes(seed,id){let starts=[.018],t=.018,count=2+Math.floor(hash(seed+id*997)*3);for(let k=1;k<count;k++){t+=.045+.06*hash(seed+id*811+k*79);starts.push(t);}return starts;}
function pulse(age,seed,id){if(age<0||age>.65)return 0;let value=0,ss=strokes(seed,id);for(let k=0;k<ss.length;k++){let t=age-ss[k];if(t>=0)value+=(1-Math.exp(-t/.0015))*Math.exp(-t/(k===0?.028:.016))*Math.pow(.73,k);}return value;}
function lightning(time,seed,rate,power,enabled,trigger=-1e9,mode='auto',manualId=0){const interval=rate>0?Math.max(2,60/rate):1e12;let id=manualId+100000,start=trigger,age=time-start,manual=age>=0&&age<.65;if(!manual){if(!enabled||rate<=0)return{strength:0,eventId:-1,age:1,start:-1e9,origin:[0,4.7,0],kind:'none',key:'none'};const slot=Math.floor(time/interval);id=slot+1;start=(slot+.19+.38*hash(seed+slot*1171))*interval;age=time-start;if(age<0){id=slot;start=(slot-1+.19+.38*hash(seed+(slot-1)*1171))*interval;age=time-start;}}
const kind=mode==='auto'?(hash(seed+id*733)<.62?'intra':'ground'):mode,origin=[(hash(seed+id*77)-.5)*1.25,4.5+hash(seed+id*107)*1.1,(hash(seed+id*311)-.5)*1.0];return{strength:pulse(age,seed,id)*power*1.45,eventId:id,age,start,origin,kind,key:[seed,id,kind].join(':'),returnStrokes:strokes(seed,id)};}
function channel(seed,eventId,origin,mode='ground'){let n=0;const rnd=()=>hash(seed^Math.imul(eventId+139,19349663)^Math.imul(++n,83492791));
function sub(a,b,levels,rough){if(!levels)return[a,b];let d=b.map((v,k)=>v-a[k]),len=Math.hypot(...d),u=[d[2],0,-d[0]],ul=Math.hypot(...u);u=ul<1e-6?[1,0,0]:u.map(v=>v/ul);let v=[d[1]*u[2]-d[2]*u[1],d[2]*u[0]-d[0]*u[2],d[0]*u[1]-d[1]*u[0]],vl=Math.hypot(...v)||1;v=v.map(x=>x/vl);const aa=(rnd()-.5)*rough*len,bb=(rnd()-.5)*rough*len,mid=a.map((x,k)=>(x+b[k])*.5+u[k]*aa+v[k]*bb),l=sub(a,mid,levels-1,rough*.86),r=sub(mid,b,levels-1,rough*.86);return l.slice(0,-1).concat(r);}
let end=mode==='intra'?[origin[0]+(rnd()>.5?1:-1)*(2.1+rnd()*.9),origin[1]+.35+rnd()*.55,origin[2]-.8-rnd()*1.0]:[origin[0]+(rnd()-.5)*1.8,.018,origin[2]+.45+(rnd()-.5)*.8],pts=sub(origin,end,6,.29),segments=[];
function add(points,weight){let m=points.length-1;for(let k=0;k<m;k++)segments.push([...points[k],...points[k+1],weight*(1-k/m*.22)]);}
add(pts,1);const forks=[8,17,26,36,45,54];for(let j=0;j<forks.length;j++){let k=forks[j],a=pts[k],f=1-k/(pts.length-1),side=j%2?-1:1,b=[a[0]+side*(.35+.75*rnd())*(.4+f),Math.max(.14,a[1]-(mode==='ground'?.35+.75*rnd():-.2+.7*rnd())),a[2]+(rnd()-.5)*(.5+f)];add(sub(a,b,3,.36),.18+.24*f);}for(let j=0;j<3;j++){let a=pts[2+j*2],b=[a[0]+(rnd()-.5)*1.35,a[1]+.35+rnd()*.5,a[2]+(rnd()-.5)*1.2];add(sub(a,b,3,.34),.12);}let data=new Float32Array(160*8);segments.forEach((a,k)=>data.set([a[0],a[1],a[2],a[6],a[3],a[4],a[5],k/segments.length],k*8));let nodes=[origin,pts[16],pts[32],pts[48]],nodeData=new Float32Array(nodes.flatMap((a,k)=>[...a,k===0?1:.55]));return{segments,data,count:segments.length,nodes,nodeData,kind:mode,topology:'attached, correlated, tapered 3D branches; graphical, no electric-field solver'};}
const api={j1,airy,diffractionRGB,makeDiffractionLUT,pulse,lightning,channel};root.WeatherOptics=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
