const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),pw=require('playwright');
const engine=process.env.COMMON_UI_BROWSER||'chromium',url=process.env.COMMON_UI_URL||'http://127.0.0.1:8765/.github/qa/unified-full-20261007/qa/full-workbench.html',out=process.env.COMMON_UI_OUT||'common-ui-'+engine;fs.mkdirSync(out,{recursive:true});
let browser,page;const modelRequests=[];const report={engine,url,passed:false,checks:[],errors:[],screens:[],pendingInterfacesNotCompleted:true};const save=()=>fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));
const digest=()=>page.evaluate(async()=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',fullCommonWorkbench.positions().buffer))].map(x=>x.toString(16).padStart(2,'0')).join(''));
async function edit(key,value){const row=page.locator('[data-parameter='+JSON.stringify(key)+']'),input=row.locator('input[type=number]');await input.scrollIntoViewIfNeeded();const rev=await page.evaluate(()=>fullCommonWorkbench.diagnostics().revision);await input.fill(String(value));await input.press('Tab');await page.waitForFunction(r=>fullCommonWorkbench.diagnostics().revision>r,rev,{timeout:180000});assert.equal(await page.evaluate(()=>scrollY),0);return row;}
async function group(id){await page.locator('.group-select').selectOption(id);}
(async()=>{
 browser=await pw[engine].launch(engine==='webkit'?{headless:true}:{headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:2048,height:1040}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.url().includes('gnm_head_web.bin'))modelRequests.push(r.url());});
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#load-model').click();await page.waitForFunction(()=>fullCommonWorkbench.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});
 let d=await page.evaluate(()=>fullCommonWorkbench.diagnostics());assert.equal(d.vertices,25417);assert.equal(d.triangles,50624);assert(d.fixedPositionBuffer&&d.fixedIndexBuffer);assert.equal(d.canvasCount,1);assert.equal(await page.locator('iframe').count(),0);assert.equal(d.catalog.catalogScalars,1596);assert.equal(d.catalog.extraBoneTranslationScalars,312);assert.equal(d.catalog.locked,37);report.initial=d;const neutral=await digest();
 for(const size of [{width:2048,height:1040},{width:1440,height:900}]){await page.setViewportSize(size);await group('anny.phenotypes');await page.locator('[data-parameter="anny.phenotypes:weight"] input[type=number]').scrollIntoViewIfNeeded();const bounds=await page.evaluate(()=>{const stage=document.querySelector('#stage').getBoundingClientRect(),panel=document.querySelector('#parameters').getBoundingClientRect(),input=document.querySelector('[data-parameter="anny.phenotypes:weight"] input[type=number]').getBoundingClientRect();return{stage:{x:stage.x,right:stage.right,top:stage.top,bottom:stage.bottom,width:stage.width},panel:{x:panel.x,right:panel.right},input:{top:input.top,bottom:input.bottom},scrollY,width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth}});assert(bounds.stage.width>size.width*.6);assert(bounds.stage.right<=bounds.panel.x);assert(bounds.input.top>=0&&bounds.input.bottom<size.height);assert.equal(bounds.scrollY,0);assert(bounds.scrollWidth<=size.width);await page.screenshot({path:path.join(out,'body-'+size.width+'.png')});report.screens.push({size,bounds});}
 await group('mhr.pose');assert.equal(await page.locator('[data-parameter-state=locked]').count(),37);await edit('mhr.pose:7',.2);assert.equal(await digest(),neutral,'Inactive MHR pose must be retained without geometry effect');assert.equal(await page.locator('[data-parameter="mhr.pose:7"] .state-badge').textContent(),'仅保存');
 await page.locator('[data-owner=rig]').selectOption('mhr');assert.notEqual(await digest(),neutral);await page.screenshot({path:path.join(out,'mhr-saved-pose-active.png')});await page.locator('[data-owner=rig]').selectOption('anny');assert.equal(await digest(),neutral);report.checks.push('real owner selector activates saved MHR pose and restores Anny');
 await group('anny.localChanges');assert.equal(await page.locator('.parameter-row[data-parameter-state=inactive]').count(),114);assert.equal(await page.locator('.state-badge').filter({hasText:'身体部分生效'}).count(),34);await page.locator('.parameter-search').fill('l-cheek-trans-up');assert.equal(await page.locator('.parameter-row').count(),1);assert(!(await page.locator('.parameter-row input[type=number]').isDisabled()));await page.locator('.parameter-search').fill('');
 await group('anny.pose');assert(!(await page.locator('[data-parameter="anny.pose:eye.L.X"] input[type=number]').isDisabled()));assert(!(await page.locator('[data-owner=headShape]').isDisabled()));assert(!(await page.locator('[data-owner=gaze]').isDisabled()));report.checks.push('all head fields editable, explicit inactive region/owner state,37 native locks retained');
 await group('gnm.identity');await edit('gnm.identity:0',.2);assert.notEqual(await digest(),neutral);await page.locator('[data-view=face]').click();await page.screenshot({path:path.join(out,'gnm-identity-live.png')});
 await group('gnm.rotation');await edit('gnm.rotation:3',.08);const poseHash=await digest();await page.screenshot({path:path.join(out,'gnm-native-pose-live.png')});
 const[download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-action=save]').click()]);const archive=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(archive.state.mhr.pose[7],.2);assert.equal(archive.state.gnm.rotation[3],.08);await page.locator('[data-action=reset-all]').click();assert.equal(await digest(),neutral);await page.locator('#common-profile-file').setInputFiles({name:'synthetic-common-profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(archive))});await page.waitForFunction(()=>fullCommonWorkbench.state().gnm.rotation[3]===.08);assert.equal(await digest(),poseHash);report.checks.push('actual downloaded archive restores all source arrays and same canonical geometry');
 const dormant=structuredClone(archive);dormant.state.anny.facialActions.browDownLeft=.4;dormant.state.mhr.expression[0]=.3;await page.locator('#common-profile-file').setInputFiles({name:'synthetic-dormant-profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(dormant))});await page.waitForFunction(()=>fullCommonWorkbench.state().anny.facialActions.browDownLeft===.4);assert.equal(await digest(),poseHash);await group('anny.facialActions');assert(!(await page.locator('[data-parameter="anny.facialActions:browDownLeft"] input[type=number]').isDisabled()));assert.equal(Number(await page.locator('[data-parameter="anny.facialActions:browDownLeft"] input[type=number]').inputValue()),.4);report.checks.push('inactive facial values retained in archive and remain inert');
 await page.locator('[data-owner=headShape]').selectOption('anny');await page.locator('[data-owner=expression]').selectOption('anny');await edit('anny.facialActions:jawOpen',.35);await page.screenshot({path:path.join(out,'anny-head-and-expression-live.png')});const annyHash=await digest();assert.notEqual(annyHash,poseHash);await page.locator('[data-owner=gaze]').selectOption('rig');await group('anny.pose');await edit('anny.pose:eye.L.X',10);assert.notEqual(await digest(),annyHash);await page.screenshot({path:path.join(out,'anny-native-eye-live.png')});
 await page.locator('[data-owner=headShape]').selectOption('mhr');await page.locator('[data-owner=expression]').selectOption('mhr');await group('mhr.expression');const jaw=await page.evaluate(()=>fullCommonWorkbench.catalog().find(r=>r.group==='mhr.expression'&&r.label==='jawDrop').key);await edit(jaw,.35);await page.screenshot({path:path.join(out,'mhr-head-and-expression-live.png')});await page.locator('#common-profile-file').setInputFiles({name:'restore-before-head-probe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(dormant))});await page.waitForFunction(()=>fullCommonWorkbench.state().owners.expression==='gnm'&&fullCommonWorkbench.state().owners.headShape==='gnm');assert.equal(await digest(),poseHash);report.checks.push('same-buffer real Anny/MHR head,expression,native eye controls and exact source archive return');

 await group('__exports');report.exports=[];
 const currentExportPositions=await page.evaluate(()=>Array.from(fullCommonWorkbench.positions()));
 const toY=[];for(let i=0;i<currentExportPositions.length;i+=3)toY.push(currentExportPositions[i],currentExportPositions[i+2],-currentExportPositions[i+1]);
 for(const format of ['obj','glb','usda','snapshot','png']){
  const[download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-export-format='+format+']').click()]);const data=fs.readFileSync(await download.path());assert(data.length>1000);let details={};
  if(format==='obj'){const v=Float32Array.from(data.toString().split('\n').filter(x=>x.startsWith('v ')).flatMap(x=>x.slice(2).split(' ').map(Number)));assert.deepEqual(v,Float32Array.from(toY));details.vertices=v.length/3;}
  if(format==='glb'){assert.equal(data.readUInt32LE(0),0x46546c67);const len=data.readUInt32LE(12),j=JSON.parse(data.subarray(20,20+len)),a=j.accessors[j.meshes[0].primitives[0].attributes.POSITION],bv=j.bufferViews[a.bufferView],v=new Float32Array(data.buffer,data.byteOffset+20+len+8+(bv.byteOffset||0),a.count*3);assert.deepEqual(v,Float32Array.from(toY));details.vertices=a.count;details.joints=j.skins[0].joints.length;}
  if(format==='usda'){const text=data.toString();assert(text.startsWith('#usda 1.0'));assert(text.includes('rel skel:skeleton = </CommonPerson/Skeleton>'));details.independentParser='OpenUSD CPU paired three-state test';}
  if(format==='snapshot'){const j=JSON.parse(data);assert.deepEqual(Float32Array.from(j.positions),Float32Array.from(toY));assert(j.fullWeights.values.length>25417);details.completeWeights=j.fullWeights.values.length;}
  if(format==='png'){assert.equal(data.subarray(1,4).toString(),'PNG');details.width=data.readUInt32BE(16);details.height=data.readUInt32BE(20);assert(details.width>200&&details.height>200);}
  assert.equal(await digest(),poseHash);report.exports.push({format,bytes:data.length,filename:download.suggestedFilename(),...details});
 }
 await page.screenshot({path:path.join(out,'actual-export-controls.png')});report.checks.push('actual OBJ/GLB/USD/full-weight JSON/PNG downloads; parsed positions unchanged and no model mutation');
 await group('__interfaces');assert.equal(await page.locator('.interface-row').count(),9);await page.screenshot({path:path.join(out,'additional-interface-ledger.png')});
 const before=await page.evaluate(()=>fullCommonWorkbench.diagnostics());await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));let released=await page.evaluate(()=>fullCommonWorkbench.diagnostics());assert.equal(released.ready,false);assert.equal(released.contextsCreated,released.contextsReleased);await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForFunction(()=>fullCommonWorkbench.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});assert.equal(await digest(),poseHash);d=await page.evaluate(()=>fullCommonWorkbench.diagnostics());assert.equal(d.contextsCreated,before.contextsCreated+1);assert.equal(d.contextsCreated-d.contextsReleased,1);assert.equal(d.canvasCount,1);report.syntheticReturn={released,restored:d,nativeBFCacheClaim:false};
 const returnURL=await page.locator('#overview-back').getAttribute('href');assert.equal(returnURL,'https://haihao0307.github.io/guilin-dem-pipeline/kaopu-human-overview/');await page.locator('#overview-back').click();await page.waitForURL(returnURL,{waitUntil:'domcontentloaded'});assert.equal(context.pages().length,1);await page.goBack({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.fullCommonWorkbench);if(!(await page.evaluate(()=>fullCommonWorkbench.diagnostics().ready))){if(!(await page.evaluate(()=>fullCommonWorkbench.diagnostics().busy)))await page.locator('#load-model').click();await page.waitForFunction(()=>fullCommonWorkbench.diagnostics().ready&&!fullCommonWorkbench.diagnostics().busy,null,{timeout:240000});}assert.equal(await page.locator('canvas').count(),1);report.realHistoryReturn=true;
 const pixels=await page.evaluate(()=>fullCommonWorkbench.pixelAudit());assert.equal(pixels.error,0);assert(pixels.colors>30);assert.deepEqual(report.errors,[]);if(url.includes('/deployment/')){assert(modelRequests.includes('https://raw.githubusercontent.com/xrblocks/assets-gnm/134feb02b11fa642a43ff5e7e880246255a74e86/gnm_head_web.bin'));assert(!modelRequests.some(x=>x.includes('/kaopu-face-workbench/assets/')));report.officialGNMURLVerified=true;}report.passed=true;report.version=browser.version();report.final=await page.evaluate(()=>fullCommonWorkbench.diagnostics());report.pixels=pixels;save();await browser.close();
})().catch(async error=>{report.failure=error.stack||String(error);save();console.error(error);try{await page?.screenshot({path:path.join(out,'failure.png'),timeout:5000})}catch{}await Promise.race([browser?.close(),new Promise(r=>setTimeout(r,5000))]);process.exit(1)});
