import fs from 'node:fs';
import * as K from './r045_round35_kernel.mjs';
import * as R34 from '../round-34/r045_round34_kernel.mjs';
import * as R30 from '../round-30/r045_round30_kernel.mjs';
const checks=[];const add=(name,pass,value,limit)=>checks.push({name,pass:Boolean(pass),value,limit});
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};
add('version',K.VERSION==='R045.35',K.VERSION,'R045.35');
add('water_graph_identity_preserved',JSON.stringify(K.nodes)===JSON.stringify(R34.nodes)&&JSON.stringify(K.edges)===JSON.stringify(R34.edges),{nodes:[R34.nodes.length,K.nodes.length],edges:[R34.edges.length,K.edges.length]},'exact inherited planimetric graph');
add('terrain_carriers_identity_preserved',JSON.stringify(K.terrainChannels)===JSON.stringify(R34.terrainChannels)&&JSON.stringify(K.outletContinuum)===JSON.stringify(R34.outletContinuum),{terrainChannels:K.terrainChannels.length,outlets:K.outletContinuum.length},'exact inherited carrier arrays');

const rows=[];for(let z=-132;z<=10;z+=6){const row=[];for(let x=-220;x<=120;x+=6){row.push({x,z,n:K.terraceStateAt(x,z),o:R34.terraceStateAt(x,z),dd:R30.nearestExtendedDrainageDistance(x,z)})}rows.push(row)}
function rowShape(row,key){const a=row.map(c=>c[key].mask>.12);let runs=0,best=0,cur=0;for(const v of a){if(v){if(cur===0)runs++;cur++;best=Math.max(best,cur)}else cur=0}return{runs,best:best*6}}
let dmax=0,dsum=0,dn=0,change=0,active=0,oldActive=0,core=0,oldCore=0,bridgeCells=0,newFromZero=0,thresholdCross=0,unsafeBridge=0,hardCoreActive=0,hardCoreDelta=0,maxBridge=0;const groupCounts=[0,0,0];let rowRunsN=0,rowRunsO=0;const longestN=[],longestO=[];
for(const row of rows){const sn=rowShape(row,'n'),so=rowShape(row,'o');rowRunsN+=sn.runs;rowRunsO+=so.runs;if(sn.best)longestN.push(sn.best);if(so.best)longestO.push(so.best);for(const c of row){const n=c.n,o=c.o,a=Math.abs(n.delta),lift=n.mask-o.mask;dmax=Math.max(dmax,a);dsum+=a;dn++;change=Math.max(change,Math.abs(n.delta-o.delta));if(n.mask>.12){active++;groupCounts[n.groupIndex]++}if(o.mask>.12)oldActive++;if(n.mask>.60)core++;if(o.mask>.60)oldCore++;if(lift>.006){bridgeCells++;maxBridge=Math.max(maxBridge,n.bridgeStrength||0);if(o.mask<=1e-12)newFromZero++;if(o.mask<=.12&&n.mask>.12)thresholdCross++;const broad=R34.broadTerraceEligibility(c.x,c.z),group=R34.terraceGroupEnvelope(c.x,c.z),riverGap=Math.abs(c.z-R30.riverZ(c.x));const riverClear=riverGap>R30.riverW(c.x)+18;if(c.dd<=12||broad<.075||group<.10||!riverClear)unsafeBridge++;}if(c.dd<=12){if(n.mask>.01)hardCoreActive++;hardCoreDelta=Math.max(hardCoreDelta,a)}}}
const burdenN=rowRunsN/(active||1),burdenO=rowRunsO/(oldActive||1);const geom={deltaMax:dmax,deltaMean:dsum/(dn||1),active,oldActive,core,oldCore,changeFrom34:change,bridgeCells,newFromZero,thresholdCross,unsafeBridge,hardCoreActive,hardCoreDelta,maxBridge,groupCounts,rowRunsN,rowRunsO,fragmentationBurdenN:burdenN,fragmentationBurdenO:burdenO,medianLongestN:median(longestN),medianLongestO:median(longestO),maxLongestN:Math.max(...longestN),maxLongestO:Math.max(...longestO)};
add('terrace_geometry_remains_substantive_but_bounded',dmax>.20&&dmax<.95,geom,'.20 m < max terrace delta < .95 m');
add('r35_is_a_real_but_bounded_change_from_r34',change>.0015&&change<.28,change,'.0015 m < sampled max R35-R34 surface change < .28 m');
add('short_gap_bridge_is_material',bridgeCells>6,{bridgeCells,maxBridge},'>6 sampled cells gain >0.006 mask');
add('short_gap_bridge_changes_threshold_topology',thresholdCross>1,{thresholdCross},'>1 inherited weak/gap sample crosses the 0.12 active threshold');
add('bridges_may_close_real_low_support_gaps',newFromZero>=0,{newFromZero},'reported explicitly; zero is allowed because weak-positive gaps can be the valid target');
add('bridge_candidates_stay_inside_safe_terrain_zone',unsafeBridge===0,{unsafeBridge},'no sampled bridge inside hard drainage core, outside broad slope/family eligibility, or in receiver exclusion');
add('active_support_does_not_shrink',active>=oldActive,{active,oldActive,ratio:active/(oldActive||1)},'R35 active support >= R34');
add('terrace_core_does_not_shrink',core>=oldCore,{core,oldCore,ratio:core/(oldCore||1)},'R35 core support >= R34');
add('row_run_count_does_not_materially_worsen',rowRunsN<=rowRunsO+1,{rowRunsN,rowRunsO},'threshold-level row runs <= R34 + 1');
add('fragmentation_burden_improves_or_holds',burdenN<=burdenO*1.01,{fragmentationBurdenN:burdenN,fragmentationBurdenO:burdenO},'row runs per active sample <= 1.01x R34');
add('longest_ribbons_do_not_shorten',median(longestN)>=median(longestO),{medianNew:median(longestN),medianOld:median(longestO),maxNew:Math.max(...longestN),maxOld:Math.max(...longestO)},'median longest row run >= R34');
add('hard_drainage_core_stays_empty',hardCoreActive===0&&hardCoreDelta<1e-9,{hardCoreActive,hardCoreDelta},'zero terrace support/delta at <=12 m drainage distance');
add('all_three_nested_groups_remain_material',groupCounts.every(n=>n>20),groupCounts,'each dominant terrace group has >20 active samples on coarse grid');

let frameN=0,maxStepDiff=0,maxPhaseDiff=0,maxRawDiff=0;for(let x=-210;x<=110;x+=14)for(let z=-128;z<=6;z+=10){const n=K.terraceStateAt(x,z),o=R34.terraceStateAt(x,z);frameN++;maxStepDiff=Math.max(maxStepDiff,Math.abs(n.step-o.step));maxPhaseDiff=Math.max(maxPhaseDiff,Math.abs(n.phase-o.phase));maxRawDiff=Math.max(maxRawDiff,Math.abs(n.raw-o.raw))}const frameIdentity={samples:frameN,maxStepDiff,maxPhaseDiff,maxRawDiff};add('r34_quantization_frame_is_exactly_preserved',maxStepDiff<1e-12&&maxPhaseDiff<1e-12&&maxRawDiff<1e-12,frameIdentity,'step, phase and raw stair response exactly inherited from R34');

const benchRat=[],riserRat=[],benchSlope=[],riserSlope=[];let benchN=0,riserN=0;for(let x=-204;x<=108;x+=12)for(let z=-126;z<=2;z+=8){const st=K.terraceStateAt(x,z);if(st.mask<.68||R30.nearestExtendedDrainageDistance(x,z)<18)continue;const bg=R30.gradient(x,z).mag,ng=K.gradient(x,z).mag;if(bg<.03||bg>.60)continue;if(st.frac<.25||st.frac>.75){benchN++;benchRat.push(ng/bg);benchSlope.push(ng)}if(st.frac>.46&&st.frac<.54){riserN++;riserRat.push(ng/bg);riserSlope.push(ng)}}const terrMetrics={benchN,riserN,benchRatioMedian:median(benchRat),riserRatioMedian:median(riserRat),benchSlopeMedian:median(benchSlope),riserSlopeMedian:median(riserSlope)};add('bench_and_riser_samples_exist',benchN>10&&riserN>3,terrMetrics,'>10 bench and >3 riser coarse core samples');add('benches_are_flatter_than_r30_substrate',median(benchRat)<.90,terrMetrics,'median bench/base gradient ratio <.90');add('risers_are_steeper_than_benches',median(riserSlope)>median(benchSlope)*1.25,terrMetrics,'median riser slope >1.25x median bench slope');add('risers_steepen_relative_to_r30',median(riserRat)>1.08,terrMetrics,'median riser/base gradient ratio >1.08');

let farUp=0,nearDrain=0,receiver=0,outside=0;for(let x=-216;x<=216;x+=18){for(const z of [-300,-220,-170,-145,30,70,130])outside=Math.max(outside,Math.abs(K.terraceDelta(x,z)));for(const z of [-300,-220,-170,-145])farUp=Math.max(farUp,Math.abs(K.terraceDelta(x,z)));for(let z=-126;z<=0;z+=12)if(R30.nearestExtendedDrainageDistance(x,z)<=12)nearDrain=Math.max(nearDrain,Math.abs(K.terraceDelta(x,z)));const rz=R30.riverZ(x);for(const dz of [-8,-2,0,2,8])receiver=Math.max(receiver,Math.abs(K.terraceDelta(x,rz+dz)))}add('far_upstream_work_untouched',farUp<1e-9,farUp,'zero sampled terrace change far upstream');add('support_is_localized_to_agricultural_slope',outside<1e-9,outside,'zero sampled terrace change outside support');add('drainage_axis_cores_are_protected',nearDrain<1e-9,nearDrain,'zero sampled terrace change within 12 m inherited drainage axes');add('foreground_receiver_is_unchanged',receiver<1e-9,receiver,'zero sampled terrace change around receiver river');
let maxAddedStep=0,maxAddedAt=null;for(let x=-210;x<=110;x+=12)for(let z=-126;z<=0;z+=6){const s=Math.abs(K.terraceDelta(x,z+6)-K.terraceDelta(x,z));if(s>maxAddedStep){maxAddedStep=s;maxAddedAt=[x,z]}}add('terrace_increment_is_not_a_cliff',maxAddedStep<1.25,{maxAddedStep,maxAddedAt},'<1.25 m added-delta change per 6 m');

add('terrace_geometry_enabled_only_as_pilot',K.snapshot.terraceGeometryEnabled===true&&K.snapshot.terracePilotPreviewEnabled===true,{terraceGeometryEnabled:K.snapshot.terraceGeometryEnabled,terracePilotPreviewEnabled:K.snapshot.terracePilotPreviewEnabled},'synthetic terrace morphology ON');add('global_visual_acceptance_remains_locked',K.snapshot.visualAcceptance===false,K.snapshot.visualAcceptance,false);add('parcel_generator_locked',K.snapshot.parcelGenerationEnabled===false,K.snapshot.parcelGenerationEnabled,false);add('water_state_unknown',K.snapshot.waterStateKnown===false,K.snapshot.waterStateKnown,false);add('production_locked',K.snapshot.productionReady===false,K.snapshot.productionReady,false);add('logic_errors_explicitly_corrected',K.snapshot.round35?.logicCorrection?.includes('Support strength and support topology are different variables')&&K.snapshot.round35?.logicCorrection?.includes('unrestricted morphological closing'),K.snapshot.round35?.logicCorrection,'reject higher-riser/global-inflation and unrestricted closing shortcuts');add('real_world_constraint_is_explicit',K.snapshot.round35?.constraint?.includes('cannot be reconstructed quickly')&&K.snapshot.round35?.constraint?.includes('management boundaries'),K.snapshot.round35?.constraint,'state missing real-world evidence that blocks fast reconstruction');add('xiaoma_truth_boundary_retained',K.snapshot.round35?.xiaomaBoundary?.includes('unknown')&&K.snapshot.round35?.xiaomaBoundary?.includes('does not establish'),K.snapshot.round35?.xiaomaBoundary,'no visual-continuity -> hydraulic-truth error');add('mrrolord_ordering_only',K.snapshot.round35?.mrRolordUse?.includes('drainage hierarchy')&&K.snapshot.round35?.mrRolordUse?.includes('does not copy'),K.snapshot.round35?.mrRolordUse,'process ordering only');add('user_reference_reopened_without_metric_inference',K.snapshot.round35?.referenceUse?.includes('reopened this round')&&K.snapshot.round35?.referenceUse?.includes('No metric terrace width'),K.snapshot.round35?.referenceUse,'morphology only');add('survey_claims_forbidden',Array.isArray(K.snapshot.round35?.forbiddenClaims)&&K.snapshot.round35.forbiddenClaims.length>=16,K.snapshot.round35?.forbiddenClaims,'explicit evidence boundary');
const result={version:K.VERSION,passed:checks.every(c=>c.pass),gateCount:checks.length,passedCount:checks.filter(c=>c.pass).length,checks,metrics:{geometry:geom,frameIdentity,terraceMorphology:terrMetrics,farUp,nearDrain,receiver,outside,maxAddedStep,maxAddedAt}};fs.writeFileSync(new URL('./r045_round35_qa_result.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.passed)process.exitCode=2;
