import * as THREE from 'three';import {OrbitControls} from '../vendor/OrbitControls.js';import {AnnyModel} from './AnnyModel.js';import {GNMHeadModel,parseContainer} from './GNMModel.js';import {UnifiedModel,DEFAULT_STATE,validateProfile} from './UnifiedModel.js';import {R01Assets} from './R01Assets.js';import {LifeEpoch} from './LifeEpoch.mjs';
const $=id=>document.getElementById(id),state=DEFAULT_STATE(),life=new LifeEpoch();let model,renderer,scene,camera,orbit,mesh,geometry,wire=false,seam=false,busy=false,loadCount=0,lost=false,assetLoad=null,resizeObserver=null,savedView=null;let contextsCreated=0,contextsReleased=0;
const GNM_URL=new URLSearchParams(location.search).get('local')==='1'?'../kaopu-face-workbench/assets/gnm_head_web.bin':'https://raw.githubusercontent.com/xrblocks/assets-gnm/134feb02b11fa642a43ff5e7e880246255a74e86/gnm_head_web.bin';
const render=()=>{if(life.active&&renderer&&model&&!lost)renderer.render(scene,camera);};
function init(){if(renderer)return;contextsCreated++;renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x242c32);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(31,1,.01,50);orbit=new OrbitControls(camera,$('canvas'));orbit.enableDamping=false;orbit.addEventListener('change',render);scene.add(new THREE.HemisphereLight(0xdfefff,0x353945,1.6));const key=new THREE.DirectionalLight(0xffdac1,3.2);key.position.set(-2,3,4);scene.add(key);const rim=new THREE.DirectionalLight(0xa3c2df,2.6);rim.position.set(2,2,-2);scene.add(rim);resizeObserver=new ResizeObserver(resize);resizeObserver.observe($('stage'));}
function resize(){if(!renderer)return;const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render();}
function view(which='front'){if(!model)return;let box=new THREE.Box3().setFromBufferAttribute(geometry.attributes.position);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());let distance=Math.max(size.y,size.x/camera.aspect)/(2*Math.tan(camera.fov*Math.PI/360))*1.16;const angle=which==='side'?Math.PI/2:which==='three'?.48:0;if(which==='face'){center.set(0,box.max.y-.18,0);distance=1.0;}camera.position.copy(center).add(new THREE.Vector3(Math.sin(angle)*distance,0,Math.cos(angle)*distance));orbit.target.copy(center);camera.zoom=1;camera.updateProjectionMatrix();orbit.update();render();}
const toDisplay=v=>{const p=new Float32Array(v.length);for(let i=0;i<v.length;i+=3){p[i]=v[i];p[i+1]=v[i+2];p[i+2]=-v[i+1];}return p;};
function update(){if(!model)return;model.compute(state);geometry.attributes.position.array.set(toDisplay(model.positions));geometry.attributes.position.needsUpdate=true;geometry.computeVertexNormals();geometry.computeBoundingSphere();const m=model.metrics();$('metrics').textContent=`角色 ${state.personId}\n顶点 ${m.vertices.toLocaleString()} · 三角形 ${m.triangles.toLocaleString()}\n颈缝 ${m.seamTriangles} 面 · 边界边全部双侧相接\n最大颈缝边长 ${m.maxSeamEdgeMM.toFixed(2)} mm\n最小颈缝面面积 ${m.minSeamTriangleAreaMM2.toFixed(3)} mm²\n下颈轮廓调整最大 ${m.neckContourMaxMM.toFixed(2)} mm\n局部平顺最大 ${m.neckFairingMaxMM.toFixed(2)} mm\n头部统一尺寸倍率 ${m.headScale.toFixed(3)}\n拓扑 SHA-256 ${m.topologySha256.slice(0,24)}…`;$('status').textContent='固定网格与身份 · Anny + GNM 已执行 · MHR 躯干投影可用（1/45 通道）';render();}
function current(ticket){return life.owns(ticket);}
async function load(){if(busy||model||!life.active)return;const ticket=life.begin();busy=true;loadCount++;$('retry').hidden=true;$('loading').hidden=false;$('loading').firstChild.textContent='载入共用模型…';const ownLoader=new R01Assets(location.href,fetch,value=>{if(current(ticket))$('progress').value=value;});assetLoad=ownLoader;try{const {am,ab,gb,c,mhr,fingerprint}=await ownLoader.load(GNM_URL);if(!current(ticket))return;init();const g=parseContainer(gb);model=new UnifiedModel(new AnnyModel(am,ab),new GNMHeadModel(g.meta,g.sections),c,mhr,fingerprint);model.compute(state);geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(toDisplay(model.positions),3));geometry.setIndex(new THREE.BufferAttribute(model.faces,1));geometry.computeVertexNormals();const colors=new Float32Array(model.vertexCount*3);const base=new THREE.Color(0xbab3a5);for(let i=0;i<model.vertexCount;i++)colors.set([base.r,base.g,base.b],i*3);geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.72,metalness:0,side:THREE.FrontSide}));scene.add(mesh);$('loading').hidden=true;update();resize();if(savedView){camera.position.fromArray(savedView.position);orbit.target.fromArray(savedView.target);camera.zoom=savedView.zoom;camera.updateProjectionMatrix();orbit.update();render();}else view('three');if(wire)mesh.material.wireframe=true;if(seam){seam=false;$('seam').onclick();}render();}catch(e){if(current(ticket)&&e.name!=='AbortError'){$('loading').firstChild.textContent='载入失败：'+e.message;$('retry').hidden=false;$('status').textContent='未就绪，可重试';}}finally{if(current(ticket)){busy=false;assetLoad=null;}}}
function release(){assetLoad?.cancel();assetLoad=null;busy=false;if(model&&camera&&orbit)savedView={position:camera.position.toArray(),target:orbit.target.toArray(),zoom:camera.zoom};resizeObserver?.disconnect();resizeObserver=null;orbit?.dispose();geometry?.dispose();mesh?.material.dispose();if(renderer){renderer.forceContextLoss();renderer.dispose();contextsReleased++;const old=$('canvas');old.replaceWith(old.cloneNode(false));bindCanvas();}model=null;geometry=null;mesh=null;scene=null;camera=null;orbit=null;renderer=null;lost=false;$('loading').hidden=false;$('loading').firstChild.textContent='返回后重新载入同一角色…';}
addEventListener('pagehide',()=>{life.hide();release();});addEventListener('pageshow',()=>{life.show();if(!model&&!busy)load();});
const controls=['age','weight','muscle','arms','turn','knee','expression','eye','identity','mhr'];function sync(){for(const id of controls){const v=['age','weight','muscle'].includes(id)?state.phenotypes[id]:id==='expression'?state.headExpression[200]:id==='eye'?state.headExpression[0]:id==='identity'?state.headIdentity[0]:id==='mhr'?state.mhr.amount:id==='arms'?-(state.pose['upperarm01.L']?.[2]||0):id==='turn'?(state.pose.head?.[2]||0):id==='knee'?(state.pose['lowerleg01.L']?.[0]||0):0;$(id).value=v;$(id+'Value').value=Number(v).toFixed(2);}}
for(const id of controls)$(id).oninput=()=>{const v=Number($(id).value);$(id+'Value').value=v.toFixed(2);if(['age','weight','muscle'].includes(id))state.phenotypes[id]=v;else if(id==='expression')state.headExpression[200]=v;else if(id==='eye')state.headExpression[0]=v;else if(id==='identity')state.headIdentity[0]=v;else if(id==='mhr')state.mhr={amount:v,channel:'identity_000'};else if(id==='arms'){state.pose['upperarm01.L']=[0,0,-v];state.pose['upperarm01.R']=[0,0,v];}else if(id==='turn')state.pose.head=[0,0,v];else if(id==='knee')state.pose['lowerleg01.L']=[v,0,0];update();};
$('baseline').onclick=()=>{Object.assign(state,DEFAULT_STATE());sync();update();view('three');};$('retry').onclick=load;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('wire').onclick=()=>{wire=!wire;if(mesh)mesh.material.wireframe=wire;$('wire').setAttribute('aria-pressed',wire);render();};$('seam').onclick=()=>{seam=!seam;if(!model)return;const c=geometry.attributes.color,base=new THREE.Color(0xbab3a5),highlight=new Set([...model.canonical.bodyRing,...model.canonical.headRing]);for(let i=0;i<model.vertexCount;i++)c.setXYZ(i,...(seam&&highlight.has(i)?[.9,.32,.08]:[base.r,base.g,base.b]));c.needsUpdate=true;$('seam').setAttribute('aria-pressed',seam);render();};
function download(name,s,type='text/plain'){const u=URL.createObjectURL(new Blob([s],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
$('exportProfile').onclick=()=>download('kaopu-unified-person.json',JSON.stringify({...state,topologySha256:model?.canonical.topologySha256,adapterFingerprint:model?.adapterFingerprint},null,2),'application/json');$('exportObj').onclick=()=>{if(!model)return;const l=['# KAOPU unified person | metres, Z-up | experimental fixed stitched neck'];for(let i=0;i<model.positions.length;i+=3)l.push('v '+Array.from(model.positions.subarray(i,i+3)).join(' '));for(let i=0;i<model.faces.length;i+=3)l.push('f '+Array.from(model.faces.subarray(i,i+3),x=>x+1).join(' '));download('kaopu-unified-person.obj',l.join('\n'));};
window.unifiedWorkbench={diagnostics:()=>({ready:!!model,loadCount,lost,busy,active:life.active,generation:life.value,contextsCreated,contextsReleased,pendingAssetRequests:assetLoad?.requests.length||0,...model?.metrics()}),positions:()=>model?.positions.slice(),state:()=>structuredClone(state),setState:s=>{Object.assign(state,s);update();},view,pixelAudit:()=>{render();const gl=renderer.getContext(),p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);const colors=new Set();for(let i=0;i<p.length;i+=128)colors.add(p[i]+','+p[i+1]+','+p[i+2]);return {colors:colors.size,background:Array.from(p.subarray(0,4)),error:gl.getError()};}};sync();load();

function bindCanvas(){const canvas=$('canvas');canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(!life.active||canvas!==$('canvas'))return;lost=true;$('status').textContent='图形上下文中断，角色参数与网格保持';});canvas.addEventListener('webglcontextrestored',()=>{requestAnimationFrame(()=>{if(!life.active||!renderer||canvas!==$('canvas'))return;renderer.setClearColor(0x242c32);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;lost=false;resize();update();});});}bindCanvas();
$('importProfile').onchange=async()=>{const ticket=life.value,f=$('importProfile').files[0];if(!f)return;try{if(f.size>100000)throw Error('档案超过100KB');const text=await f.text();if(!current(ticket))throw new DOMException('Stale file import cancelled','AbortError');const candidate=validateProfile(JSON.parse(text),model);Object.assign(state,candidate);sync();update();$('status').textContent='已恢复同一角色档案';}catch(e){if(current(ticket)&&e.name!=='AbortError')$('status').textContent='未导入：'+e.message;}finally{if(current(ticket))$('importProfile').value='';}};
