/** R01 lifecycle-only loader. Original data, hashes and model math are unchanged.
 * A single cancel signal covers metadata, parts, reads and decompression. */
const hash=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
export class R01Assets {
  constructor(base,fetcher=fetch,progress=()=>{}){this.base=new URL(base);this.fetcher=fetcher.bind(globalThis);this.progress=progress;this.controller=new AbortController();this.requests=[];}
  check(){if(this.controller.signal.aborted)throw new DOMException('Model loading cancelled','AbortError');}
  cancel(){this.controller.abort();}
  async bytes(url,sha=null,length=null){this.check();const absolute=new URL(url,this.base);this.requests.push(String(absolute));const timer=setTimeout(()=>this.cancel(),120000);try{const r=await this.fetcher(absolute,{signal:this.controller.signal});this.check();if(!r.ok)throw Error('HTTP '+r.status+' '+absolute);const b=await r.arrayBuffer();this.check();if(length!==null&&b.byteLength!==length)throw Error('资产长度不一致');if(sha&&await hash(b)!==sha)throw Error('资产校验不一致');this.check();return b;}finally{clearTimeout(timer);}}
  async json(url){return JSON.parse(new TextDecoder().decode(await this.bytes(url)));}
  async inflate(packed,length,sha){this.check();if(!Number.isSafeInteger(length)||length<0||length>128*1048576)throw Error('解压长度超出限制');const input=new ReadableStream({start(c){c.enqueue(new Uint8Array(packed));c.close();}}),reader=input.pipeThrough(new DecompressionStream('gzip'),{signal:this.controller.signal}).getReader(),out=new Uint8Array(length);let offset=0;try{while(true){this.check();const {value,done}=await reader.read();if(done)break;if(offset+value.byteLength>length)throw Error('解压超出声明长度');out.set(value,offset);offset+=value.byteLength;}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}this.check();if(offset!==length)throw Error('解压资产长度不一致');if(await hash(out)!==sha)throw Error('解压资产校验不一致');this.check();return out.buffer;}
  async gzipJSON(url,compressedSHA,rawSHA,rawBytes){return JSON.parse(new TextDecoder().decode(await this.inflate(await this.bytes(url,compressedSHA),rawBytes,rawSHA)));}
  async anny(meta){const info=meta.binary.compressed;if(!info.parts)return this.bytes('../kaopu-anny-workbench/assets/anny-model.bin.gz',info.sha256,info.byteLength);const joined=new Uint8Array(info.byteLength);let offset=0;for(const part of info.parts){const b=await this.bytes(new URL(part.url,new URL('../kaopu-anny-workbench/',this.base)),part.sha256,part.byteLength);if(offset+b.byteLength>joined.length)throw Error('Anny分片超出总长度');joined.set(new Uint8Array(b),offset);offset+=b.byteLength;this.progress(offset/joined.length);}if(offset!==joined.length)throw Error('Anny分片不完整');if(await hash(joined)!==info.sha256)throw Error('Anny完整压缩包校验失败');this.check();return joined.buffer;}
  async load(gnmURL){try{const fingerprint=await this.json('./assets/adapter-fingerprint.json'),[am,c,mhr]=await Promise.all([this.json('../kaopu-anny-workbench/assets/anny-model.json'),this.gzipJSON('./assets/canonical.json.gz',fingerprint.inputs.canonicalCompressed,fingerprint.inputs.canonical,1835277),this.gzipJSON('./assets/mhr-torso-delta.json.gz',fingerprint.inputs.mhrProjectionCompressed,fingerprint.inputs.mhrProjection,422148)]);if(am.binary.sha256!==fingerprint.inputs.annyBinary)throw Error('Anny adapter version mismatch');const[gz,gb]=await Promise.all([this.anny(am),this.bytes(gnmURL,'fd19f46eef6f8bfb725fceab581e1bc8837209997ca3fd43f3c1735003c86961',34937952)]),ab=await this.inflate(gz,am.binary.byteLength,am.binary.sha256);this.check();return{am,ab,gb,c,mhr,fingerprint};}catch(e){this.cancel();throw e;}}
}
