from pathlib import Path
B=Path(__file__).parent
math=(B/'curve-math.mjs').read_text().replace('export ','')
geometry='\n'.join(x for x in (B/'geometry.mjs').read_text().splitlines() if not x.startswith('import ')).replace('export ','')
html='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>海羽 · 稀疏结构独立候选</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#0d171e;color:#dce7ed;font:14px system-ui,-apple-system,sans-serif}main{max-width:1450px;margin:auto;padding:16px}h1{font-size:20px;margin:0 0 7px}p{color:#9bafbc;line-height:1.65;margin:6px 0 12px}.toolbar{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}button,select{border:1px solid #395262;background:#152732;color:#e4eff4;border-radius:8px;padding:8px 12px;min-height:38px;font:inherit}button[aria-pressed=true]{border-color:#cca874;background:#394235}button:focus-visible{outline:2px solid #ddb270}canvas{width:100%;height:440px;min-height:300px;background:#0a141b;border:1px solid #294451;border-radius:12px;touch-action:none}.time{display:flex;align-items:center;gap:9px}.time input{flex:1}label{display:flex;gap:7px;align-items:center}output{min-width:94px;font-variant-numeric:tabular-nums}.small{font-size:11px}.status{padding:10px 0;color:#b6ccd6}details{margin-top:10px}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#9fb6c5}.mini{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mini canvas{height:150px;min-height:0;border-radius:8px}.mini figure{margin:8px 0}.mini figcaption{font-size:11px;color:#9bafbc;margin:5px} @media(max-width:600px){main{padding:10px}h1{font-size:17px}canvas{height:330px;min-height:270px}.toolbar{gap:5px}button,select{padding:6px 8px;font-size:12px}.mini{grid-template-columns:1fr}.mini canvas{height:135px}.mini figure{margin:3px 0}}
</style></head><body><main><h1>稀疏主轴 · 成对支架</h1><p>独立结构候选。X 根→尖，Y 左右展开，Z 深度。不是作者模型或真实解剖；运动为显式函数，不是受力仿真。</p><div class="toolbar" aria-label="观察方向"><button data-view="orbit" aria-pressed="true">自由观察</button><button data-view="front">XY · 沿 Z 看</button><button data-view="top">XZ · 沿 Y 看</button><button data-view="side">YZ · 沿 X 看</button><button id="resetView">重置视角</button><button id="frames" aria-pressed="false">局部坐标架</button><button id="neutral" aria-pressed="false">中性色</button></div><canvas id="scene" width="1200" height="620" aria-label="同一三维主轴和成对支架的可旋转投影"></canvas><div class="toolbar"><button id="play">播放</button><button id="reset">回到起点</button><label>运动<select id="amplitude"><option value="0">静止</option><option value="0.4">轻摆</option><option value="1" selected>正常</option><option value="2">较强</option></select></label><label>对数<select id="ribCount"><option>2</option><option>6</option><option selected>12</option><option>24</option></select></label><button id="axisOnly" aria-pressed="false">只看轴与站点</button></div><div class="time"><label for="time">时间</label><input id="time" type="range" min="0" max="4" step="0.01" value="0"><output id="clock">0.00 / 4.00 s</output></div><div class="status" id="status" role="status"></div><p class="small">拖动改变相机，滚轮缩放。下方三投影始终使用同一份世界坐标；轴与根部不随相机重新生成。颜色只区分左右支架，不冒充光照。</p><div class="mini"><figure><canvas id="front"></canvas><figcaption>XY · 沿 Z 看</figcaption></figure><figure><canvas id="top"></canvas><figcaption>XZ · 沿 Y 看</figcaption></figure><figure><canvas id="side"></canvas><figcaption>YZ · 沿 X 看</figcaption></figure></div><details><summary>检查数据与边界</summary><pre id="diagnostics"></pre></details><p class="small">当前仅对选定状态和已列边界测试。闭合路径与大于60°的单步尖折未支持；无表皮、厚壳和全局碰撞保证。这是结构研究候选，不代表真实解剖或物理力学；验收范围以报告为准。</p></main><script>(function(){'use strict';
'''+math+'\n'+geometry+'\n'+(B/'preview-ui.js').read_text()+'''\n})();</script></body></html>'''
(B/'preview.html').write_text(html)
