const el=id=>document.getElementById(id),s={active:true,playing:false,time:0,amplitude:1,ribCount:12,view:'orbit',yaw:.45,pitch:-.65,zoom:1,frames:false,neutral:false,axisOnly:false},canvases=['scene','front','top','side'].map(el);
let geometryRevision=0,viewEvidence={};
let packet=evaluate({time:s.time,amplitude:s.amplitude,ribCount:s.ribCount}),request=0,last=0,dirty=true,geometryDirty=false,disposed=false,drag=null;
function schedule(){if(!request&&s.active&&!document.hidden&&!disposed)request=requestAnimationFrame(tick)}
function geometry(){geometryRevision++;packet=evaluate({time:s.time,amplitude:s.amplitude,ribCount:s.ribCount});geometryDirty=false;dirty=true}
function projected(v,view,w,h,zoom=1){const q=project(v,view,s.yaw,s.pitch),scale=(view==='side'?.86:.8)*Math.min(w,h*1.7)*zoom;return[w/2+q[0]*scale,h/2+q[1]*scale,q[2]]}
function draw(canvas,view){const world=JSON.stringify([packet.axis,packet.ribs.map(r=>r.points)]);let fingerprint=2166136261;for(let i=0;i<world.length;i++){fingerprint^=world.charCodeAt(i);fingerprint=Math.imul(fingerprint,16777619)}viewEvidence[canvas.id]={geometryRevision,time:packet.parameters.time,worldFingerprint:(fingerprint>>>0).toString(16),vertices:packet.vertexCount};const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext('2d');if(!c)throw Error('Canvas 2D unavailable');c.fillStyle='#0a141b';c.fillRect(0,0,w,h);
 const line=(points,color,width)=>{c.strokeStyle=color;c.lineWidth=width*dpr;c.lineCap='round';c.lineJoin='round';c.beginPath();points.forEach((p,i)=>{const q=projected(p,view,w,h,canvas.id==='scene'?s.zoom:1);i?c.lineTo(q[0],q[1]):c.moveTo(q[0],q[1])});c.stroke()};
 if(!s.axisOnly){const ribs=[...packet.ribs].sort((a,b)=>project(a.points[12],view,s.yaw,s.pitch)[2]-project(b.points[12],view,s.yaw,s.pitch)[2]);for(const r of ribs)line(r.points,s.neutral?'#cad4d8':r.side<0?'#c6a574':'#88b2bc',canvas.id==='scene'?1.8:1)}
 line(packet.axis,s.neutral?'#f3f3ee':'#b2764c',canvas.id==='scene'?4:2);for(const st of packet.stations){const q=projected(st.root,view,w,h,canvas.id==='scene'?s.zoom:1);c.fillStyle='#eedcb4';c.beginPath();c.arc(q[0],q[1],(canvas.id==='scene'?3.8:2)*dpr,0,Math.PI*2);c.fill();if(s.frames&&st.id%3===0)for(const[key,col]of[['T','#df9d8e'],['N','#81c29f'],['B','#76a8df']])line([st.root,add(st.root,mul(st.frame[key],.06))],col,1)}
}
function render(){for(const canvas of canvases)draw(canvas,canvas.id==='scene'?s.view:canvas.id);const m=inspect(packet);el('status').textContent=`${m.stations} 个站点 · ${m.ribCount} 根支架 · 根部误差 ${m.rootError} · ${m.vertexCount} 个三维点`;el('clock').value=s.time.toFixed(2)+' / 4.00 s';el('time').value=s.time;el('play').textContent=s.playing?'暂停':'播放';el('diagnostics').textContent=JSON.stringify({parameters:packet.parameters,checks:m,frameMethod:'discrete minimal rotation; selected tests only',camera:{view:s.view,yaw:s.yaw,pitch:s.pitch,zoom:s.zoom},geometryDoesNotUseCamera:true,verificationScope:'Runtime geometry diagnostics; browser acceptance is recorded separately'},null,2);document.body.dataset.time=s.time;document.body.dataset.ready='true';dirty=false}
function stop(){s.playing=false;last=0;if(request){cancelAnimationFrame(request);request=0}dirty=true;if(s.active)schedule()}
function tick(now){request=0;if(!s.active||document.hidden||disposed)return;try{if(s.playing&&last){s.time=(s.time+Math.min(.05,(now-last)/1000))%4;geometryDirty=true}last=now;if(geometryDirty)geometry();if(dirty)render();if(s.playing)schedule()}catch(e){stop();s.active=false;el('status').textContent='未能绘制：'+e.message;document.body.dataset.error=e.message}}
function chooseView(view){s.view=view;for(const x of document.querySelectorAll('[data-view]'))x.setAttribute('aria-pressed',String(x.dataset.view===view));dirty=true;schedule()}
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>chooseView(b.dataset.view);el('resetView').onclick=()=>{s.yaw=.45;s.pitch=-.65;s.zoom=1;chooseView('orbit')};
for(const id of['frames','neutral','axisOnly'])el(id).onclick=()=>{s[id]=!s[id];el(id).setAttribute('aria-pressed',String(s[id]));dirty=true;schedule()};
el('play').onclick=()=>{s.playing=!s.playing;last=0;dirty=true;schedule()};el('reset').onclick=()=>{stop();s.time=0;geometryDirty=true;schedule()};el('time').oninput=e=>{stop();s.time=Number(e.target.value);geometryDirty=true;schedule()};for(const id of['amplitude','ribCount'])el(id).onchange=e=>{s[id]=Number(e.target.value);geometryDirty=true;schedule()};
const scene=el('scene');scene.onpointerdown=e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,yaw:s.yaw,pitch:s.pitch};scene.setPointerCapture(e.pointerId)};scene.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;chooseView('orbit');s.yaw=drag.yaw+(e.clientX-drag.x)*.006;s.pitch=clamp(drag.pitch+(e.clientY-drag.y)*.006,-1.4,1.4);dirty=true;schedule()};for(const name of['pointerup','pointercancel','lostpointercapture'])scene.addEventListener(name,()=>drag=null);scene.addEventListener('wheel',e=>{e.preventDefault();s.zoom=clamp(s.zoom*Math.exp(-e.deltaY*.001),.5,3);dirty=true;schedule()},{passive:false});
const observer=new ResizeObserver(()=>{dirty=true;schedule()});for(const c of canvases)observer.observe(c);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else{dirty=true;schedule()}});window.addEventListener('pagehide',()=>{s.active=false;stop();observer.disconnect()});
window.HaiyuSparseCandidate={getPacket:()=>JSON.parse(JSON.stringify(packet)),getState:()=>({...s,pendingRAF:request?1:0}),getRenderEvidence:()=>JSON.parse(JSON.stringify(viewEvidence)),setActive(active){s.active=!!active;stop();if(s.active){dirty=true;schedule()}},dispose(){s.active=false;disposed=true;stop();observer.disconnect()}};schedule();
