const {chromium,webkit}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
(async()=>{
 const kind=process.env.STORM_BROWSER||'chromium',dir=process.env.STORM_QA_DIR||'storm-qa';fs.mkdirSync(dir,{recursive:true});
 const browser=await ({chromium,webkit}[kind]).launch({headless:true,...(kind==='chromium'?{args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{} )});
 const sceneAnchor=crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../scene.mjs'))).digest('hex');assert.equal(sceneAnchor,'0cef6ab02300a55ab52e27797fed6e286d4d308b5c7f290dc755d226dafa68ec');
 const results={sceneAnchor,browser:kind,url:process.env.STORM_URL||'http://127.0.0.1:8765/kaopu-minigame-workbench/storm-orb-study/',checks:[],errors:[],metrics:[]};
 try{const page=await browser.newPage({viewport:{width:720,height:882},deviceScaleFactor:1});page.on('pageerror',e=>results.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')results.errors.push(m.text());});
 async function seek(t){const prior=await page.evaluate(t=>{const prior=__storm.getState().renderFrame;__storm.setTime(t);return prior;},t);await page.waitForFunction(({t,prior})=>{const s=__storm.getState();return s.renderFrame>prior&&Math.abs(s.renderedTime-t)<1e-9;},{t,prior},{timeout:60000});}
 await page.goto(results.url);await page.waitForFunction(()=>window.__storm,null,{timeout:60000});await page.waitForTimeout(500);assert.equal(await page.locator('canvas').count(),1);
 for(const t of [0,2,2.5,5.5,9,9.91,10.8]){await seek(t);await page.locator('#stage').screenshot({path:path.join(dir,`scene-${String(t).replace('.','_')}.png`)});results.metrics.push(await page.evaluate(()=>__storm.getState()));}
 results.checks.push('Seven actual WebGL phases captured');
 await page.setViewportSize({width:720,height:882});await page.evaluate(()=>{document.querySelector('.caption').style.visibility='hidden';});await seek(2.5);await page.locator('#stage').screenshot({path:path.join(dir,'preview.png')});
 await page.evaluate(()=>{document.querySelector('.caption').style.visibility='';});await page.setViewportSize({width:1100,height:950});
 await page.locator('#scrub').fill('6.25');await page.locator('#scrub').dispatchEvent('input');await page.waitForTimeout(250);assert.equal((await page.evaluate(()=>__storm.getState())).playing,false);assert.equal((await page.evaluate(()=>__storm.getState())).time,6.25);results.checks.push('Timeline pauses at exact time');
 await page.locator('#play').click();await page.waitForFunction(()=>__storm.getState().playing);await page.waitForTimeout(300);assert.equal((await page.evaluate(()=>__storm.getState())).playing,true);await page.locator('#play').click();await page.waitForFunction(()=>!__storm.getState().playing);const paused=(await page.evaluate(()=>__storm.getState())).time;await page.waitForTimeout(200);assert.equal((await page.evaluate(()=>__storm.getState())).time,paused);results.checks.push('Play/pause');
 await page.locator('#camera').click();await page.waitForFunction(()=>__storm.getState().free);assert.equal((await page.evaluate(()=>__storm.getState())).free,true);const before=(await page.evaluate(()=>__storm.getState())).camera;await page.mouse.move(500,400);await page.mouse.down();await page.mouse.move(670,440,{steps:12});await page.mouse.up();await page.waitForTimeout(300);assert.notDeepEqual((await page.evaluate(()=>__storm.getState())).camera,before);await page.locator('#stage').screenshot({path:path.join(dir,'free-camera.png')});await page.evaluate(()=>{__storm.setTime(2.5);__storm.camera.position.set(8,-1,12);__storm.camera.lookAt(0,1.3,0);});await page.waitForTimeout(500);await page.locator('#stage').screenshot({path:path.join(dir,'low-angle-depth.png')});await page.locator('#camera').click();await page.waitForFunction(()=>!__storm.getState().free);assert.equal((await page.evaluate(()=>__storm.getState())).free,false);results.checks.push('Free camera drag and reference-camera return');
 await page.locator('#info').click();await page.locator('#notes').waitFor({state:'visible'});assert.equal(await page.locator('#notes').isVisible(),true);await page.locator('#closeInfo').click();await page.locator('#notes').waitFor({state:'hidden'});assert.equal(await page.locator('#notes').isVisible(),false);await page.locator('#info').click();await page.keyboard.press('Escape');await page.locator('#notes').waitFor({state:'hidden'});assert.equal(await page.locator('#notes').isVisible(),false);results.checks.push('Disclosure close and repeated open/Escape');
 for(const [w,h,label] of [[390,844,'phone'],[844,390,'landscape'],[1365,768,'desktop']]){await page.setViewportSize({width:w,height:h});await page.waitForFunction(()=>Math.abs(document.querySelector('canvas').width-document.querySelector('#stage').clientWidth*__storm.getState().pixelRatio)<1.01);await seek(5.5);const v=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,iw:innerWidth,sh:document.documentElement.scrollHeight,ih:innerHeight,canvas:document.querySelector('canvas').getBoundingClientRect().toJSON()}));assert(v.sw<=v.iw+1);assert(v.canvas.width>50&&v.canvas.height>50);assert(v.sh<=v.ih+2);await page.screenshot({path:path.join(dir,`${label}.png`)});await page.locator('#info').click();await page.locator('#notes').waitFor({state:'visible'});const notesBox=await page.locator('#notes').boundingBox();assert(notesBox.y>=0&&notesBox.y+notesBox.height<=h+1);await page.keyboard.press('Escape');await page.locator('#notes').waitFor({state:'hidden'});results.checks.push(`${label} viewport visible without page overflow`);}
 await page.locator('#reset').click();await page.waitForFunction(()=>__storm.getState().playing&&!__storm.getState().free);assert.equal((await page.evaluate(()=>__storm.getState())).free,false);assert.equal((await page.evaluate(()=>__storm.getState())).playing,true);results.checks.push('Reset restores playback and reference camera');
 await seek(3);await page.locator('#play').click();await page.waitForFunction(()=>__storm.getState().playing);const perf=await page.evaluate(()=>new Promise(resolve=>{let start=performance.now(),n=0;function frame(){if(++n===30)resolve({sampleFrames:n,milliseconds:performance.now()-start,fps:n*1000/(performance.now()-start)});else requestAnimationFrame(frame);}requestAnimationFrame(frame);}));results.performance=perf;
 const hub=new URL('../',results.url).href;await page.goto(hub,{waitUntil:'networkidle'});assert.equal(await page.locator('a.launch').count(),2);assert.equal(await page.locator('a.back').getAttribute('href'),'https://chatgpt.com/g/g-p-6aabf1adc22c81919829812355cd4eec-game/project');assert(await page.locator('img').evaluateAll(is=>is.every(i=>i.complete&&i.naturalWidth>0)));for(const size of [{width:1280,height:900},{width:390,height:844}]){await page.setViewportSize(size);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(dir,`hub-${size.width}.png`),fullPage:true});}assert.equal(await page.locator('a.launch[href^="./voxel-train-study/"]').count(),1);await page.locator('a.launch[href="./storm-orb-study/"]').click();await page.waitForFunction(()=>window.__storm,null,{timeout:60000});await seek(2.5);await page.locator('header a[href="../"]').click();await page.waitForURL(hub);await page.goBack({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__storm,null,{timeout:60000});await seek(2.5);await page.goForward({waitUntil:'networkidle'});await page.waitForURL(hub);assert.equal(page.context().pages().length,1);results.checks.push('Two real hub cards, loaded artwork, same-tab return and Back/Forward');
 assert.equal(results.errors.length,0,results.errors.join('\n'));results.status='pass';await page.close();
 }catch(e){results.status='fail';results.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results,null,2));}
})();
