import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateFixedCard,ruler} from '../src/fixed-card.mjs';
const card=JSON.parse(fs.readFileSync(new URL('../profiles/amphiprion_ocellaris_71mm_fixed.json',import.meta.url),'utf8'));
const v=validateFixedCard(card);
assert.equal(v.status,'VALID_FIXED_MEASURED_CARD');
assert(v.depthInSL>=2.1&&v.depthInSL<=2.4);
const r=ruler(card);
assert.equal(r.totalLengthMm,71);
assert.equal(r.standardLengthMm,55.38);
assert(Math.abs(r.bodyDepthMm-23.714)<1e-12);
assert(Math.abs(r.headLengthMm-16.543)<1e-12);
assert(Math.abs(r.eyeDiameterMm-3.110084)<1e-12);
assert(Math.abs(r.anchors.dorsalOriginU-0.24)<1e-12);
assert(Math.abs(r.anchors.analOriginU-0.476)<1e-12);
assert(Math.abs(r.anchors.eyeCenterU-0.081084)<1e-12);
assert.equal(r.topWidthStatus,'UNKNOWN_NOT_MEASURED');
assert.equal(card.readiness.full3D,false);
console.log('A. ocellaris 71 mm fixed card: 11 assertions passed');