const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium,webkit}=require('playwright');
const engine=process.env.TRAIN_BROWSER||'chromium',out='fullscreen-ui-'+engine,base=process.env.TRAIN_GAME_URL||'http://127.0.0.1:8765/kaopu-minigame-workbench/voxel-train-study/game/';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await({chromium,webkit})[engine].launch(),context=await browser.newContext({viewport:{width:700,height:390},deviceScaleFactor:1,hasTouch:true}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/game/app.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\n'+fs.readFileSync(__dirname+'/browser-harness.mjs','utf8')});});const freeze=async()=>{await page.evaluate(()=>{window.requestAnimationFrame=()=>0;});await page.waitForTimeout(100);await page.evaluate(()=>{__trainDriver.test.session().paused=false;__trainDriver.test.stepTicks(0);__trainDriver.test.render();});};
try{await page.goto(base);await page.waitForFunction(()=>window.__trainDriver?.test);await page.locator('#startGame').click();await freeze();
for(const size of [{width:700,height:390,layout:'landscape'},{width:844,height:390,layout:'landscape'},{width:390,height:844,layout:'landscape'},{width:390,height:700,layout:'portrait'},{width:320,height:690,layout:'portrait'}]){await page.setViewportSize({width:size.width,height:size.height});await page.locator('#'+size.layout+'View').click();await freeze();const layout=await page.evaluate(()=>{const main=document.getElementById('driverGame'),root=main.getBoundingClientRect(),rotated=__trainDriver.getState().viewSettings.rotated,rect=id=>{const r=document.getElementById(id).getBoundingClientRect();return rotated?{x:r.y-root.y,y:root.right-r.right,width:r.height,height:r.width}:{x:r.x-root.x,y:r.y-root.y,width:r.width,height:r.height};};return{root:{width:main.clientWidth,height:main.clientHeight},scene:rect('sceneWrap'),left:rect('leftHud'),right:rect('instrumentPanel'),drive:rect('drivePanel')};});let layoutError=null;try{assert.equal(Math.round(layout.scene.height),Math.round(layout.root.height),'The scene must use the full logical screen height');assert(layout.left.x+layout.left.width<layout.right.x,'Auxiliary information and instruments occupy separate sides');
for(const id of ['landscapeView','portraitView','lockView','resetView','cameraView','pause','accelerate','decelerate','brake','stationAction']){const b=await page.locator('#'+id).boundingBox();assert(b&&b.x>=-1&&b.y>=-1&&b.x+b.width<=size.width+1&&b.y+b.height<=size.height+1,JSON.stringify({id,b,size}));}
for(const id of ['accelerate','decelerate','brake','stationAction']){const touch=await page.locator('#'+id).evaluate(el=>{const b=el.getBoundingClientRect();return{width:b.width,height:b.height,background:getComputedStyle(el).backgroundColor,select:getComputedStyle(el).userSelect||getComputedStyle(el).webkitUserSelect};});assert(Math.min(touch.width,touch.height)>=60);assert.equal(touch.background,'rgba(0, 0, 0, 0)');assert.equal(touch.select,'none');}
assert.equal(await page.locator('#mapStations>g').count(),6);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}catch(error){layoutError=String(error);}await page.screenshot({path:out+'/'+size.width+'-'+size.height+'-'+size.layout+'.png',timeout:30000});checks.push({size,...layout,error:layoutError});}assert(checks.every(check=>!check.error),JSON.stringify(checks.filter(check=>check.error)));
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({status:'passed',engine,url:base,checks,errors},null,2));
}catch(error){fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),checks,errors,state:await page.evaluate(()=>__trainDriver?.getState()).catch(()=>null)},null,2));try{await page.screenshot({path:out+'/failure.png',timeout:5000});}catch{}throw error;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
