import assert from 'node:assert/strict';
import * as THREE from '../../vendor/three.module.js';
import {CAMERA_PRESETS,CAMERA_PRESET_IDS,CAMERA_LIMITS,TRAIN_FOCUS_BOUNDS,getCameraPreset,getFocusBounds,boundCameraPose} from '../camera-presets.mjs';
import {VIEW_STORAGE_KEY,VIEW_REVISION,DEFAULT_VIEWS,prepareViewProfiles,selectCameraPreset,recommendView,restoreView,validView} from '../view-profile-storage.mjs';
import {createViewControls} from '../view-controls.mjs';
import {verticalFov} from '../anchored-zoom.mjs';
import {projectFrame} from '../bounds-zoom.mjs';
let passed=0;
function test(name,run){run();passed++;console.log('PASS '+name);}
function corners(bounds){const points=[];for(const x of [bounds.min[0],bounds.max[0]])for(const y of [bounds.min[1],bounds.max[1]])for(const z of [bounds.min[2],bounds.max[2]])points.push(new THREE.Vector3(x,y,z));return points;}
function cameraFor(p,aspect){const camera=new THREE.PerspectiveCamera(verticalFov(aspect,p.projection),aspect,.1,240);camera.position.fromArray(p.position);camera.zoom=p.zoom;camera.lookAt(new THREE.Vector3(...p.target));camera.updateProjectionMatrix();camera.updateMatrixWorld();return camera;}
function nearly(a,b,tolerance=1e-8){assert(Math.abs(a-b)<tolerance,`${a} differs from ${b}`);}

test('R09 has its own stable storage key and flat-world revision',()=>{assert.equal(VIEW_STORAGE_KEY,'kaopu.train-driver.views.r09');assert.notEqual(VIEW_STORAGE_KEY,'kaopu.train-driver.views.v1');assert.equal(VIEW_REVISION,'flat-platform-r09');});
test('both moderate-angle overview views fit the whole steam train',()=>{for(const[mode,aspect]of [['landscape',2048/1016],['landscape',16/9],['portrait',390/844],['portrait',430/932]]){const p=getCameraPreset('overview',mode),camera=cameraFor(p,aspect),b=projectFrame(camera,corners(TRAIN_FOCUS_BOUNDS));assert(b);assert(b.left.x>-.94&&b.right.x<.94,`${mode} horizontal fit ${b.left.x}..${b.right.x}`);assert(b.bottom.y>-.65&&b.top.y<.65,`${mode} vertical fit ${b.bottom.y}..${b.top.y}`);const dy=p.position[1]-p.target[1],horizontal=Math.hypot(p.position[0]-p.target[0],p.position[2]-p.target[2]);assert(Math.atan2(dy,horizontal)<.48,'A natural lower viewing angle');}});

test('new default is the lower platform-side view, with cab and waiting area visible',()=>{for(const [mode,aspect]of [['landscape',16/9],['portrait',390/844]]){const p=DEFAULT_VIEWS[mode];assert.equal(p.presetId,'platform');assert.equal(p.focus,'platform');assert.deepEqual(p.target,[-1.5,2.2,0]);assert(p.position[2]>=8&&p.position[2]<=14);assert(p.position[1]<5);const camera=cameraFor(p,aspect);for(const point of [[-1.5,2.7,1],[-7,1.6,3.5],[3.8,2.1,0],[-12,2,0]]){const projected=new THREE.Vector3(...point).project(camera);assert(Math.abs(projected.x)<1&&Math.abs(projected.y)<.8,`${mode} train/cab/platform point ${point} stays visible`);}}});
test('front, rear and detail are genuinely different physical observer positions',()=>{assert.deepEqual(CAMERA_PRESET_IDS,['overview','front','rear','detail','platform']);for(const id of CAMERA_PRESET_IDS)for(const layout of ['landscape','portrait']){const p=getCameraPreset(id,layout);assert(validView(p));assert.equal(p.focus,id);assert.equal(p.presetId,id);assert(p.position[1]>=CAMERA_LIMITS.minHeight);assert(Math.hypot(...p.position.map((v,i)=>v-p.target[i]))>=CAMERA_LIMITS.minRadius);const b=projectFrame(cameraFor(p,layout==='landscape'?16/9:390/844),corners(p.focusBounds));assert(b,'focus is in front of lens');assert(b.left.x> -1 && b.right.x<1,`${id} ${layout} focus horizontally visible ${b.left.x}..${b.right.x}`);assert(b.top.y<1&&b.bottom.y>-1,`${id} focus vertically visible`);}assert(getCameraPreset('front').position[0]>20);assert(getCameraPreset('rear').position[0]<-30);assert(getCameraPreset('detail').position[2]<12);assert.equal(getCameraPreset('missing'),null);assert.equal(getCameraPreset('__proto__'),null);assert.equal(getCameraPreset('constructor'),null);assert.equal(getCameraPreset('front','invalid'),null);});
test('preset objects and bounds never expose mutable shared state',()=>{const p=getCameraPreset('front');p.position[0]=0;p.focusBounds.min[0]=-999;assert.equal(getCameraPreset('front').position[0],23);assert.equal(getFocusBounds('front').min[0],-8);assert(Object.isFrozen(CAMERA_PRESETS.overview.landscape.position));});
test('presets preserve original customized view through repeated selections and reset',()=>{const data=prepareViewProfiles(null);const custom={position:[8,12,24],target:[-5,1.5,0],zoom:1.35,manual:true,locked:false,focus:'overview'};data.profiles.landscape=structuredClone(custom);assert(selectCameraPreset(data,'front'));assert(selectCameraPreset(data,'rear'));assert(selectCameraPreset(data,'detail'));assert.deepEqual(data.backups.landscape,custom);recommendView(data,'landscape');assert.deepEqual(data.backups.landscape,custom);assert(restoreView(data,'landscape'));assert.deepEqual(data.profiles.landscape,custom);assert.equal(restoreView(data,'landscape'),false);});
test('portrait and landscape presets, manual flags, locks and restored views survive reload independently',()=>{const data=prepareViewProfiles(null);assert(selectCameraPreset(data,'front'));assert(selectCameraPreset(data,'rear','portrait'));data.profiles.portrait.locked=true;assert.equal(selectCameraPreset(data,'detail','portrait'),false);const reopened=prepareViewProfiles(JSON.stringify(data));assert.deepEqual(reopened,data);assert.equal(reopened.profiles.landscape.focus,'front');assert.equal(reopened.profiles.portrait.focus,'rear');assert.equal(reopened.profiles.portrait.locked,true);assert(restoreView(reopened,'landscape'));assert.equal(reopened.profiles.landscape.presetId,'platform');assert.equal(reopened.profiles.portrait.presetId,'rear');});
test('invalid storage and invalid preset IDs leave valid recoverable profiles',()=>{for(const raw of [null,'broken',{version:99},'{"version":1,"profiles":{"landscape":{"position":[null,0,0]}}}']){const data=prepareViewProfiles(raw);assert(validView(data.profiles.landscape));assert(validView(data.profiles.portrait));const before=JSON.stringify(data);assert.equal(selectCameraPreset(data,'nope'),false);assert.equal(JSON.stringify(data),before);}});
test('free camera guard stays above ground, outside train, and at bounded orbit radius',()=>{for(const[position,target]of [[[0,-20,0],[0,0,0]],[[0,1,0],[0,1,0]],[[1,1,1],[0,1,0]],[[1000,1000,1000],[0,1,0]],[[-8,1,1.5],[-8,1,7]],[[0,5,20],[0,-100,0]],[[999,200,800],[999,150,799]]]){const safe=boundCameraPose(position,target);assert(safe);assert(safe.position[1]>=CAMERA_LIMITS.minHeight);assert(safe.target[1]>=CAMERA_LIMITS.minTargetHeight);assert(safe.target[0]>=CAMERA_LIMITS.minTargetX&&safe.target[0]<=CAMERA_LIMITS.maxTargetX);assert(Math.abs(safe.target[2])<=CAMERA_LIMITS.maxTargetZ);const radius=Math.hypot(...safe.position.map((v,i)=>v-safe.target[i]));assert(radius>=CAMERA_LIMITS.minRadius-1e-9&&radius<=CAMERA_LIMITS.maxRadius+1e-9,`radius ${radius}`);const box=CAMERA_LIMITS.trainClearance;assert(!safe.position.every((v,i)=>v>box.min[i]&&v<box.max[i]));}assert.equal(boundCameraPose([NaN,0,0],[0,0,0]),null);assert.equal(boundCameraPose(null,[0,0,0]),null);});

function mockedControls(initial={},viewport={width:1280,height:720}){
 const elements=new Map(),reads=[],writes=[],storage=new Map(Object.entries(initial));
 function element(id){if(!elements.has(id))elements.set(id,{dataset:{},listeners:{},setAttribute(key,value){this[key]=value;},addEventListener(type,fn){(this.listeners[type]||=[]).push(fn);},fire(type,extra={}){for(const fn of this.listeners[type]||[])fn({preventDefault(){},button:0,deltaMode:0,...extra});}});return elements.get(id);}
 globalThis.document={getElementById:element};globalThis.localStorage={getItem(key){reads.push(key);return storage.get(key)||null;},setItem(key,value){writes.push(key);storage.set(key,value);}};
 globalThis.innerWidth=viewport.width;globalThis.innerHeight=viewport.height;globalThis.addEventListener=()=>{};globalThis.requestAnimationFrame=fn=>fn();
 const rotated=viewport.height>viewport.width,width=rotated?viewport.height:viewport.width,height=rotated?viewport.width:viewport.height;
 const canvas=element('canvas');Object.assign(canvas,{clientWidth:width,clientHeight:height,setPointerCapture(){},getBoundingClientRect:()=>({left:0,top:0,right:viewport.width,width:viewport.width,height:viewport.height})});
 const camera=new THREE.PerspectiveCamera(32,width/height,.1,240),target=new THREE.Vector3();
 let controls;
 controls=createViewControls({camera,target,canvas,root:element('root'),getZoomPoints:()=>corners(controls?.focusBounds()||TRAIN_FOCUS_BOUNDS),onChange:p=>{camera.fov=verticalFov(camera.aspect,p.projection);camera.updateProjectionMatrix();}});
 return {controls,camera,target,canvas,element,reads,writes,storage};
}
test('control initialization, presets and reload never read or write the frozen R08 key',()=>{const oldKey='kaopu.train-driver.views.v1',oldValue=JSON.stringify({frozen:'R08 camera'}),h=mockedControls({[oldKey]:oldValue});assert.deepEqual(h.reads,[VIEW_STORAGE_KEY]);assert(h.writes.every(key=>key===VIEW_STORAGE_KEY));assert(h.controls.applyPreset('front'));assert(h.controls.applyPreset('rear'));assert.equal(h.storage.get(oldKey),oldValue);assert.equal(h.controls.state().focus,'rear');assert.equal(h.controls.activePreset(),'rear');const reopened=mockedControls(Object.fromEntries(h.storage));assert.equal(reopened.controls.activePreset(),'rear');assert.deepEqual(reopened.controls.state().position,h.controls.state().position);assert.equal(reopened.storage.get(oldKey),oldValue);});
test('wheel zoom keeps selected focus anchored and manual orbit preserves that focus',()=>{const h=mockedControls();h.controls.applyPreset('detail');const points=corners(h.controls.focusBounds()),before=projectFrame(h.camera,points);h.canvas.fire('wheel',{deltaY:-100});const after=projectFrame(h.camera,points);nearly(before.x,after.x);nearly(before.y,after.y);assert.equal(h.controls.activePreset(),null);assert.equal(h.controls.state().focus,'detail');h.canvas.fire('pointerdown',{pointerId:1,clientX:500,clientY:350});h.canvas.fire('pointermove',{pointerId:1,clientX:780,clientY:700});h.canvas.fire('pointerup',{pointerId:1});assert(h.camera.position.y>=CAMERA_LIMITS.minHeight);assert.equal(h.controls.state().manual,true);assert.equal(h.controls.state().focus,'detail');});
test('fixed camera resists presets, wheel and drag; layout choices remain independent',()=>{const h=mockedControls();h.controls.applyPreset('front');h.element('lockView').fire('click');const locked=h.controls.state();assert.equal(h.controls.applyPreset('rear'),false);h.canvas.fire('wheel',{deltaY:-100});h.canvas.fire('pointerdown',{pointerId:1,clientX:200,clientY:100});h.canvas.fire('pointermove',{pointerId:1,clientX:800,clientY:500});assert.deepEqual(h.controls.state().position,locked.position);assert.equal(h.controls.state().zoom,locked.zoom);assert(h.controls.setLayout('portrait'));assert.equal(h.controls.activePreset(),'platform');assert(h.controls.applyPreset('rear'));assert(h.controls.setLayout('landscape'));assert.equal(h.controls.activePreset(),'front');assert.equal(h.controls.locked(),true);assert.deepEqual(h.controls.state().position,locked.position);globalThis.innerWidth=390;globalThis.innerHeight=844;assert.equal(h.controls.state().rotated,true);assert.equal(h.controls.setLayout('invalid'),false);});

test('rotated mobile pinch preserves exact pan with either finger event order',()=>{
 for(const order of [[1,2],[2,1]]){
  const h=mockedControls({}, {width:390,height:844}),cx=390*.55,cy=844*.55;
  const points=corners(h.controls.focusBounds());
  const center=()=>{const b=projectFrame(h.camera,points);return [(b.x+1)*h.canvas.clientWidth/2,(1-b.y)*h.canvas.clientHeight/2];};
  h.canvas.fire('pointerdown',{pointerId:10,clientX:cx,clientY:cy});
  for(let i=1;i<=5;i++)h.canvas.fire('pointermove',{pointerId:10,clientX:cx+24*i/5,clientY:cy-18*i/5});
  h.canvas.fire('pointerup',{pointerId:10});
  for(const deltaY of [-35,-35,-35,-35,-35,20,20])h.canvas.fire('wheel',{deltaY});
  const touch=(type,d,dx=0,dy=0)=>{for(const id of order)h.canvas.fire(type,{pointerId:id,clientX:cx+(id===1?-d:d)+dx,clientY:cy+dy});};
  touch('pointerdown',30);
  const beforePinch=center();
  for(const distance of [34,38,42,46]){touch('pointermove',distance);const after=center();nearly(after[0],beforePinch[0],.000001);nearly(after[1],beforePinch[1],.000001);}
  const before=center();
  touch('pointermove',46,15,12);
  const after=center();
  nearly(after[0],before[0]+12,.000001);nearly(after[1],before[1]-15,.000001);
  assert(h.camera.position.y>=CAMERA_LIMITS.minHeight);
  assert(h.target.y>CAMERA_LIMITS.minTargetHeight+.5,'The ordinary gesture never approaches the target guard');
 }
});
console.log(JSON.stringify({status:'passed',tests:passed,storageKey:VIEW_STORAGE_KEY,presets:CAMERA_PRESET_IDS}));
