const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium,webkit}=require('playwright');
const engine=process.env.TRAIN_BROWSER||'chromium',out='railway-ui-'+engine,base=process.env.TRAIN_GAME_URL||'http://127.0.0.1:8765/kaopu-minigame-workbench/voxel-train-study/game/';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await({chromium,webkit})[engine].launch(),context=await browser.newContext({viewport:{width:844,height:390},deviceScaleFactor:1,hasTouch:true}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/game/app.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\n'+fs.readFileSync(__dirname+'/browser-harness.mjs','utf8')});});const freeze=async()=>{await page.evaluate(()=>{window.requestAnimationFrame=()=>0;});await page.waitForTimeout(150);await page.evaluate(()=>{const g=__trainDriver.test.session();g.paused=false;__trainDriver.test.stepTicks(0);__trainDriver.test.render();});},state=()=>page.evaluate(()=>__trainDriver.getState());
try{await page.goto(base);await page.waitForFunction(()=>window.__trainDriver?.test);await page.locator('#startGame').click();await freeze();
assert.equal(await page.locator('.masthead h1').isVisible(),false);assert.equal(await page.locator('#mapStations>g').count(),6);assert.equal((await state()).viewSettings.zoom,1.14);assert.deepEqual((await state()).viewSettings.position,[4,20,32]);
for(const size of [{width:844,height:390,layout:'landscape'},{width:700,height:390,layout:'landscape'},{width:390,height:844,layout:'landscape'},{width:390,height:700,layout:'portrait'},{width:320,height:690,layout:'portrait'}]){await page.setViewportSize({width:size.width,height:size.height});await page.locator('#'+size.layout+'View').click();await freeze();for(const id of ['landscapeView','portraitView','lockView','resetView','cameraView','pause','accelerate','decelerate','brake','stationAction']){const r=await page.locator('#'+id).boundingBox();assert(r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=size.width+1&&r.y+r.height<=size.height+1,JSON.stringify({id,r,size}));}
const distanceFont=await page.locator('#stationDistance').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));assert(distanceFont>=(size.width===320?28:31));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const overlap=await page.evaluate(()=>{const a=document.querySelector('.view-tools').getBoundingClientRect(),b=document.querySelector('.masthead nav').getBoundingClientRect();return Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));});assert.equal(overlap,0,'View and game controls must not overlap');if(size.layout==='landscape'&&size.width>size.height){const hero=await page.evaluate(()=>__trainDriver.test.heroRect()),map=await page.locator('#routeMap').boundingBox(),area=Math.max(0,Math.min(hero.right,map.x+map.width)-Math.max(hero.left,map.x))*Math.max(0,Math.min(hero.bottom,map.y+map.height)-Math.max(hero.top,map.y));assert.equal(area,0,'Recommended train framing must stay clear of the route map');}await page.screenshot({path:out+'/'+size.width+'-'+size.height+'-'+size.layout+'.png',timeout:30000});checks.push({size,distanceFont,controlsInBounds:true,toolbarOverlap:overlap});}
// Explicit preservation fixture: old user-authored and locked views survive this UI update.
const legacy={version:1,layout:'landscape',profiles:{landscape:{position:[19,24,38],target:[-8.8,-.8,1],zoom:1.21,manual:true,locked:true},portrait:{position:[30,22,17],target:[-7,-.5,1],zoom:1.31,manual:true,locked:true}}};await page.evaluate(d=>localStorage.setItem('kaopu.train-driver.views.v1',JSON.stringify(d)),legacy);await page.reload();await page.waitForFunction(()=>window.__trainDriver?.test);assert.deepEqual((await state()).viewSettings.position,legacy.profiles.landscape.position);assert.equal((await state()).viewSettings.zoom,1.21);assert.equal((await state()).viewSettings.locked,true);await page.locator('#continueSaved').click();await freeze();await page.locator('#resetView').click();await freeze();assert.deepEqual((await state()).viewSettings.position,[4,20,32]);assert.equal(await page.locator('#restoreView').isVisible(),true);await page.locator('#restoreView').click();await freeze();assert.deepEqual((await state()).viewSettings.position,legacy.profiles.landscape.position);assert.equal((await state()).viewSettings.zoom,1.21);assert.equal((await state()).viewSettings.locked,true);await page.locator('#portraitView').click();await freeze();assert.deepEqual((await state()).viewSettings.position,legacy.profiles.portrait.position);assert.equal((await state()).viewSettings.zoom,1.31);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({status:'passed',engine,url:base,checks,oldLockedViewsPreserved:true,recommendedViewCanBeUndone:true,errors},null,2));
}catch(error){fs.writeFileSync(out+'/failure.json',JSON.stringify({error:String(error),checks,errors,state:await state().catch(()=>null)},null,2));try{await page.screenshot({path:out+'/failure.png',timeout:5000});}catch{}throw error;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
