import fs from 'node:fs';
import * as K from './r045_round66_kernel.mjs';
import * as R58 from '../round-58/r045_round58_kernel.mjs';
import * as R47 from '../round-47/r045_round47_kernel.mjs';
import * as R30 from '../round-30/r045_round30_kernel.mjs';
const checks=[];const add=(name,pass,value,limit)=>checks.push({name,pass:Boolean(pass),value,limit});
const C=(x,a,b)=>Math.max(a,Math.min(b,x));const S=(a,b,x)=>{const t=C((x-a)/(b-a),0,1);return t*t*(3-2*t)};
const xs=[];for(let x=-216;x<=114;x+=6)xs.push(x);const zs=[];for(let z=-126;z<=6;z+=6)zs.push(z);
const med=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
function macroNormal(x,z){const e=2,gx=(R30.height(x+e,z)-R30.height(x-e,z))/(2*e),gz=(R30.height(x,z+e)-R30.height(x,z-e))/(2*e),m=Math.hypot(gx,gz);return m<1e-9?{nx:1,nz:0}:{nx:gx/m,nz:gz/m}}
function dirAbs(fn,x,z,h=.6){const n=macroNormal(x,z);return Math.abs((fn(x+h*n.nx,z+h*n.nz)-fn(x-h*n.nx,z-h*n.nz))/(2*h))}
function receiverBand(x,z){return Math.abs(z-R30.riverZ(x))<=R30.riverW(x)+12}
function sharpResidual(b){const u=(b.base+b.phase)/b.step,n=Math.floor(u),f=u-n,sharp=(n+S(.46,.54,f))*b.step-b.phase-b.base;return{f,full:.84*b.mask*Math.abs(sharp-b.raw)}}
let activeN=0,activeP=0,thresholdCross=0,maskErr=0,stepErr=0,phaseErr=0,indexErr=0,baseErr=0,groupErr=0;
let eligible=0,changed=0,changedEligible=0,opportunity=0,changedOpportunity=0,inactiveChanged=0,hardChanged=0,receiverChanged=0,unsupportedChanged=0,strongErr=0,maxChange=0,maxGain=0,sumGain=0;
const groups=[0,0,0],changedGroups=new Set(),changedPts=[],benchN=[],benchP=[],riserN=[],riserP=[];
for(const x of xs)for(const z of zs){
 const n=K.terraceStateAt(x,z),p=R58.terraceStateAt(x,z),b=R47.terraceStateAt(x,z),blend=K.coverageBlendAt(x,z),d=Math.abs(n.delta-p.delta),dd=R30.nearestExtendedDrainageDistance(x,z),res=sharpResidual(b);
 if(n.mask>.12){activeN++;if(n.groupIndex>=0&&n.groupIndex<3)groups[n.groupIndex]++}if(p.mask>.12)activeP++;if((p.mask>.12)!==(n.mask>.12))thresholdCross++;
 maskErr=Math.max(maskErr,Math.abs(n.mask-b.mask));stepErr=Math.max(stepErr,Math.abs(n.step-b.step));phaseErr=Math.max(phaseErr,Math.abs(n.phase-b.phase));indexErr=Math.max(indexErr,Math.abs(n.index-b.index));baseErr=Math.max(baseErr,Math.abs(n.base-b.base));if(n.groupIndex!==b.groupIndex)groupErr++;
 if(b.mask>=.55)strongErr=Math.max(strongErr,d);
 const isEligible=b.mask>.12&&b.mask<.55&&blend.gain>1e-7&&dd>12&&!receiverBand(x,z);if(isEligible){eligible++;sumGain+=blend.gain;maxGain=Math.max(maxGain,blend.gain)}
 const isOpportunity=isEligible&&res.full>.015&&blend.gain>.005;if(isOpportunity)opportunity++;
 if(d>1e-6){changed++;maxChange=Math.max(maxChange,d);if(isEligible)changedEligible++;else unsupportedChanged++;if(isOpportunity)changedOpportunity++;if(b.mask<=.12)inactiveChanged++;if(dd<=12)hardChanged++;if(receiverBand(x,z))receiverChanged++;changedGroups.add(b.groupIndex);changedPts.push({x,z,change:n.delta-p.delta,mask:b.mask,groupIndex:b.groupIndex,coverageGain:blend.gain,fullResidual:res.full,phaseFrac:res.f,dd});if(res.f<=.34||res.f>=.66){benchN.push(dirAbs(K.height,x,z));benchP.push(dirAbs(R58.height,x,z))}if(res.f>=.44&&res.f<=.56){riserN.push(dirAbs(K.terraceDelta,x,z));riserP.push(dirAbs(R58.terraceDelta,x,z))}}
}
const meanGain=eligible?sumGain/eligible:0;let maxInc=0,maxIncAt=null;for(const p of changedPts){const c=K.terraceDelta(p.x,p.z);for(const[xx,zz]of[[p.x+3,p.z],[p.x-3,p.z],[p.x,p.z+3],[p.x,p.z-3]]){const inc=Math.abs(K.terraceDelta(xx,zz)-c);if(inc>maxInc){maxInc=inc;maxIncAt={x:p.x,z:p.z,xx,zz,inc}}}}
let outside=0,hard=0,receiver=0;for(let x=-216;x<=216;x+=36){for(const z of [-300,-220,-170,-145,30,70,130])outside=Math.max(outside,Math.abs(K.terraceDelta(x,z)));for(let z=-126;z<=6;z+=18)if(R30.nearestExtendedDrainageDistance(x,z)<=12)hard=Math.max(hard,Math.abs(K.terraceDelta(x,z)-R58.terraceDelta(x,z)));const rz=R30.riverZ(x);for(const dz of [-8,0,8])receiver=Math.max(receiver,Math.abs(K.terraceDelta(x,rz+dz)-R58.terraceDelta(x,rz+dz)))}
const bench={n:benchN.length,newMedian:med(benchN),priorMedian:med(benchP)};bench.ratio=bench.n&&bench.priorMedian>1e-9?bench.newMedian/bench.priorMedian:null;const riser={n:riserN.length,newMedian:med(riserN),priorMedian:med(riserP)};riser.ratio=riser.n&&riser.priorMedian>1e-9?riser.newMedian/riser.priorMedian:null;
add('version',K.VERSION==='R045.66',K.VERSION,'R045.66');add('water_graph_identity',JSON.stringify(K.nodes)===JSON.stringify(R58.nodes)&&JSON.stringify(K.edges)===JSON.stringify(R58.edges),{nodes:K.nodes.length,edges:K.edges.length},'exact R58 inherited graph');
add('plan_frame_exact',maskErr===0&&stepErr===0&&phaseErr===0&&indexErr===0&&baseErr===0&&groupErr===0,{maskErr,stepErr,phaseErr,indexErr,baseErr,groupErr},'exact R47/R58 mask/group/step/phase/index/base');add('active_footprint_exact',activeN===activeP&&thresholdCross===0,{activeN,activeP,thresholdCross},'exact accepted R58 active footprint');
add('profile_opportunity_material',opportunity>=12,{opportunity,eligible},'>=12 physically non-trivial existing-active profile opportunities');add('profile_opportunity_realized',changedOpportunity>=10&&changedOpportunity/Math.max(1,opportunity)>=.65,{opportunity,changedOpportunity,ratio:changedOpportunity/Math.max(1,opportunity)},'>=10 changed opportunities and >=65% realization');add('whole_slope_change_material',changedEligible>=20,{changedEligible,eligible},'>=20 changed existing-active cells');
add('coverage_gain_material',meanGain>.01&&maxGain>.04,{meanGain,maxGain},'mean >0.01 and max >0.04 blend gain');add('all_three_families_change',changedGroups.size===3,[...changedGroups],'all three terrace families participate');add('inactive_cells_exact',inactiveChanged===0,inactiveChanged,'zero change where inherited mask <=0.12');add('strong_profile_exact',strongErr<1e-12,strongErr,'exact R58 at inherited mask >=0.55');add('all_changes_supported',unsupportedChanged===0,unsupportedChanged,'every changed 6m cell belongs to eligible existing-active profile band');
add('hard_drainage_exact',hardChanged===0&&hard<1e-12,{hardChanged,hard},'zero R66-R58 change in <=12m drainage core');add('foreground_receiver_exact',receiverChanged===0&&receiver<1e-12,{receiverChanged,receiver},'zero R66-R58 change in receiver +12m band');add('support_localized',outside<1e-9,outside,'0 outside terrace support domain');add('height_change_bounded',maxChange>.003&&maxChange<.10,maxChange,'0.003m < max R66-R58 delta <0.10m');add('three_meter_cliff_gate',maxInc<1.05,{maxInc,maxIncAt},'<1.05m terrace increment / 3m at every changed 6m cell');add('three_groups_retained',groups.every(v=>v>20),groups,'three terrace families material');
add('directional_profile_not_degraded',(bench.n<3||bench.ratio<=1.15)&&(riser.n<3||riser.ratio>=.88),{bench,riser},'where sampled: composed bench <=115% R58 and terrace riser >=88% R58');add('locks_retained',K.snapshot.visualAcceptance===false&&K.snapshot.parcelGenerationEnabled===false&&K.snapshot.waterStateKnown===false&&K.snapshot.productionReady===false,{visual:K.snapshot.visualAcceptance,parcel:K.snapshot.parcelGenerationEnabled,water:K.snapshot.waterStateKnown,production:K.snapshot.productionReady},'all false pending fixed-view review');
add('denominator_fallacy_corrected',K.snapshot.round66?.logicCorrection?.includes('denominator fallacy')&&K.snapshot.round66?.logicCorrection?.includes('non-trivial cross-profile residual'),K.snapshot.round66?.logicCorrection,'blend eligibility != geometric correction opportunity');add('field_constraint_explicit',K.snapshot.round66?.constraint?.includes('synthetic morphology/QA scales')&&K.snapshot.round66?.constraint?.includes('cannot supply'),K.snapshot.round66?.constraint,'field truth missing');add('xiaoma_boundary_retained',K.snapshot.round66?.xiaomaBoundary?.includes('do not establish'),K.snapshot.round66?.xiaomaBoundary,'geometry != hydraulic truth');add('mrrolord_ordering_only',K.snapshot.round66?.mrRolordUse?.includes('ordering discipline')&&K.snapshot.round66?.mrRolordUse?.includes('not agricultural truth'),K.snapshot.round66?.mrRolordUse,'ordering only');add('reference_nonmetric',K.snapshot.round66?.referenceUse?.includes('non-metric')&&K.snapshot.round66?.referenceUse?.includes('No width'),K.snapshot.round66?.referenceUse,'nonmetric only');
const result={version:K.VERSION,passed:checks.every(c=>c.pass),gateCount:checks.length,passedCount:checks.filter(c=>c.pass).length,checks,metrics:{activeN,activeP,thresholdCross,groups,eligible,opportunity,changed,changedEligible,changedOpportunity,changedGroups:[...changedGroups],meanGain,maxGain,changedPoints:changedPts,inactiveChanged,unsupportedChanged,hardChanged,receiverChanged,strongErr,maxChange,maxInc,maxIncAt,outside,hard,receiver,bench,riser,qaScope:'authoritative 6m whole-slope existing-active profile sweep + physical residual opportunity gate + exact plan/footprint/drainage locks + 3m local cliff checks'}};fs.writeFileSync(new URL('./r045_round66_qa_result.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.passed)process.exitCode=2;
