import {DEFAULT_EYE,EYE_RANGES,NATURAL_PRESETS,validateEyes} from './NaturalEyeState.mjs';
const FIELDS=[['虹膜与瞳孔','irisScale','虹膜直径比例'],['虹膜与瞳孔','pupil','瞳孔直径 / 虹膜'],['虹膜与瞳孔','brightness','虹膜明度'],['虹膜与瞳孔','tintAmount','虹膜改色比例'],['虹膜与瞳孔','innerAmount','内环改色比例'],['虹膜与瞳孔','limbal','虹膜外缘深浅'],['虹膜与瞳孔','contrast','虹膜色彩层次'],['虹膜与瞳孔','rotation','虹膜纹理角度'],['眼白与血丝','scleraWhite','眼白柔和明度'],['眼白与血丝','yellow','眼白泛黄'],['眼白与血丝','redness','眼白泛红'],['眼白与血丝','veinAmount','血丝强度'],['眼白与血丝','veinDensity','血丝覆盖密度'],['湿润与光学','wetness','表面湿润'],['湿润与光学','corneaRoughness','角膜反射宽度'],['湿润与光学','scleraRoughness','眼白反射宽度'],['湿润与光学','parallax','虹膜折射层深度']];
export function mountNaturalEyeUI({model,viewer,controller}){
 const api=model.naturalEyes,panel=document.getElementById('identityPanel'),tabs=document.getElementById('identityTabs'),fields=document.getElementById('identityFields');if(!api||!panel)throw Error('缺少原生眼球工作台接口');
 let side='both',active=false,history=[],editing=false,disposed=false;
 const tab=document.createElement('button');tab.id='naturalEyesTab';tab.textContent='自然眼球';tab.setAttribute('aria-selected','false');tabs.prepend(tab);
 panel.querySelector('.identity-count').textContent='ET15 / NATURAL EYES · SAME CHARACTER';
 const style=document.createElement('style');style.textContent='#naturalEyeControls .eye-meta{font-size:11px;color:#b7c9ce}#naturalEyeControls details{margin:10px 0;border-top:1px solid #46606a;padding-top:7px}#naturalEyeControls summary{cursor:pointer;color:#dceaaa}#naturalEyeControls .eye-check{display:flex;gap:8px;margin:8px 0}#naturalEyeControls .eye-check input{width:auto}#naturalEyeControls .eye-source a{color:#c9dea6}#naturalEyesTab[aria-selected=true]{background:#d5eaa5;color:#1b292d}#identityPanel:has(#naturalEyeControls){height:67%;min-height:400px}';panel.append(style);
 const status=text=>{const e=document.getElementById('identityStatus');if(e)e.textContent=text;};
 function syncStatus(){if(active)status(`ET15 · ${api.settings.reference?'原始贴图对照':api.settings.enabled?'自然眼球':'旧版对照'} · 原图1024²，不冒充8K扫描 · 左右独立保存`);}
 function render(){if(disposed||!active)return;const s=api.settings,e=s[side==='both'?'right':side];let html='<div id="naturalEyeControls"><div class="identity-tools"><button data-eye-action="eyes">双眼近看</button><button data-eye-action="macro">虹膜特写</button><button data-eye-action="face">整脸</button><button data-eye-action="undo">撤回眼球修改</button></div><p class="eye-meta">保留同一人物、眼睑、注视和体型。只有两套自然原纹；其余颜色由原纹派生。</p><div class="identity-recipes">';
  html+=Object.entries(NATURAL_PRESETS).map(([id,p])=>`<button data-eye-preset="${id}">${p.label}</button>`).join('')+'</div>';
  html+=`<label class="eye-check">修改对象 <select id="naturalEyeSide"><option value="both">左右一起</option><option value="left">人物左眼</option><option value="right">人物右眼</option></select></label><label class="eye-check"><input type="checkbox" data-eye-global="enabled" ${s.enabled?'checked':''}>使用新自然眼球（取消看旧版）</label><label class="eye-check"><input type="checkbox" data-eye-global="reference" ${s.reference?'checked':''}>直接看原始贴图，暂不叠加改色和血丝调整</label>`;
  for(const g of ['虹膜与瞳孔','眼白与血丝','湿润与光学']){
   html+=`<details ${g!=='湿润与光学'?'open':''}><summary>${g}</summary>`;
   if(g==='虹膜与瞳孔')html+=`<label><span>虹膜纹理来源</span><select data-eye-key="source"><option value="0" ${e.source===0?'selected':''}>Harvey 01</option><option value="1" ${e.source===1?'selected':''}>Harvey 02</option></select><span></span></label><label><span>虹膜主色</span><input type="color" data-eye-key="tint" value="${e.tint}"><span></span></label><label><span>虹膜内环色</span><input type="color" data-eye-key="innerColor" value="${e.innerColor}"><span></span></label>`;
   for(const[group,k,label]of FIELDS.filter(r=>r[0]===g)){const[lo,hi]=EYE_RANGES[k];html+=`<label><span>${label}</span><input type="range" data-eye-key="${k}" min="${lo}" max="${hi}" step="${k==='rotation'?1:.01}" value="${e[k]}"><output>${e[k].toFixed(2)}</output></label>`;}
   if(g==='虹膜与瞳孔')html+=`<label class="eye-check"><input type="checkbox" data-eye-global="autoPupil" ${s.autoPupil?'checked':''}>按模拟环境明暗调节瞳孔</label><label><span>模拟环境明度</span><input type="range" min="0" max="1" step=".01" data-eye-global="illumination" value="${s.illumination}"><output>${s.illumination.toFixed(2)}</output></label><small>彩色部分是虹膜；瞳孔保持暗色。明暗输入是测试控制，不读取你的摄像头。</small>`;
   if(g==='眼白与血丝')html+='<small>泛黄、泛红与血丝分别控制外观，不代表健康程度或医疗诊断。</small>';
   html+='</details>';
  }
  html+='<div class="identity-tools"><button data-eye-action="reset">恢复选中眼球</button><button data-eye-action="save">保存完整人物</button><button data-eye-action="import">恢复人物档案</button></div><input id="naturalEyeImport" type="file" accept=".json,application/json" hidden><p class="eye-source eye-meta">原始纹理：callharvey3d · Harvey_eye1 / Harvey_eye2 · MakeHuman system_eye_materials03 · CC-BY。原始PNG字节保留；新参数、眼白分层和光学代码独立实现。<a href="https://static.makehumancommunity.org/assets/assetpacks/system_eye_materials03.html" target="_blank" rel="noopener noreferrer">查看作者与来源</a></p><small>原图每个虹膜约243像素直径；极端微距不等于影视扫描。光学为实时近似，不是体积眼球仿真。</small></div>';
  fields.innerHTML=html;fields.querySelector('#naturalEyeSide').value=side;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-selected',String(b===tab)));syncStatus();
 }
 function saveUndo(){history.push(structuredClone(api.settings));if(history.length>24)history.shift();}
 function transact(fn,{rebuild=true}={}){saveUndo();editing=true;try{const result=fn();if(rebuild)controller.changed();else viewer.render();syncStatus();return result;}catch(e){const old=history.pop();if(old){api.settings=old;api.update();}status('眼球修改失败：'+e.message);throw e;}finally{editing=false;}}
 function set(patch,target=side){return transact(()=>api.set(patch,target),{rebuild:target==='global'&&Object.hasOwn(patch,'enabled')});}
 function preset(id,target=side){const result=transact(()=>{api.set({enabled:true,reference:false},'global');return api.preset(id,target);});render();return result;}
 function view(mode='eyes'){
  model.eyeSurface.set({gray:false,grid:false});model.faceSurface.set({layer:'beauty'});controller.changed();if(mode==='face'){viewer.view('face');return;}
  model.eyeSurface.viewEyes();
  if(mode==='macro'){const a=model.eyeSurface.landmark(side==='left'?42:36),b=model.eyeSurface.landmark(side==='left'?45:39),c=a.map((v,i)=>(v+b[i])*.5),center=[c[0],c[2],-c[1]],target=viewer.orbit.target;viewer.camera.position.x+=center[0]-target.x;viewer.camera.position.y+=center[1]-target.y;viewer.camera.position.z+=center[2]-target.z;target.set(...center);viewer.camera.lookAt(target);}
  viewer.camera.zoom=mode==='macro'?3.25:1.8;viewer.camera.updateProjectionMatrix();viewer.render();
 }
 function open(){active=true;render();}
 const click=event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.group){active=false;tab.setAttribute('aria-selected','false');return;}try{if(b===tab){open();view();return;}if(b.dataset.eyePreset){preset(b.dataset.eyePreset);return;}const action=b.dataset.eyeAction;if(!action)return;if(['eyes','macro','face'].includes(action))view(action);else if(action==='undo'&&history.length){api.settings=validateEyes(history.pop());api.update();controller.changed();render();}else if(action==='reset'){transact(()=>api.set({...DEFAULT_EYE},side));render();}else if(action==='save'){const url=URL.createObjectURL(new Blob([JSON.stringify(controller.archive(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kaopu-et15-person.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else if(action==='import')fields.querySelector('#naturalEyeImport').click();}catch(e){status(e.message);}};
 const input=event=>{const el=event.target;if(el.dataset.eyeKey){try{const k=el.dataset.eyeKey,v=el.type==='color'?el.value:Number(el.value);const patch={[k]:v};if(k==='tint')patch.tintAmount=1;if(k==='innerColor')patch.innerAmount=1;set(patch);const out=el.parentElement.querySelector('output');if(out)out.textContent=Number(v).toFixed(2);}catch(e){status(e.message);}}else if(el.dataset.eyeGlobal){try{set({[el.dataset.eyeGlobal]:el.type==='checkbox'?el.checked:Number(el.value)},'global');const out=el.parentElement.querySelector('output');if(out)out.textContent=Number(el.value).toFixed(2);}catch(e){status(e.message);}}};
 const change=async event=>{const el=event.target;if(el.id==='naturalEyeSide'){side=el.value;render();}else if(el.id==='naturalEyeImport'&&el.files?.[0]){try{if(el.files[0].size>5e6)throw Error('档案过大');const archive=JSON.parse(await el.files[0].text());validateEyes(archive.naturalEyes||{});controller.restore(archive);history=[];render();status('人物及左右眼球参数已恢复');}catch(e){status('未恢复：'+e.message);}}};
 const changed=()=>{if(!editing&&active)render();syncStatus();};panel.addEventListener('click',click);panel.addEventListener('input',input);panel.addEventListener('change',change);controller.addEventListener('change',changed);
 const originalPreset=controller.applyPreset;controller.applyPreset=function(id){const prior=structuredClone(api.settings);try{api.assign(id);return originalPreset.call(this,id);}catch(e){api.settings=prior;api.update();throw e;}};
 api.disposeUI=()=>{disposed=true;controller.applyPreset=originalPreset;controller.removeEventListener('change',changed);panel.removeEventListener('click',click);panel.removeEventListener('input',input);panel.removeEventListener('change',change);tab.remove();style.remove();};
 window.naturalEyeWorkbench={version:'ET15-E1',settings:()=>structuredClone(api.settings),set,preset,presets:()=>Object.entries(NATURAL_PRESETS).map(([id,p])=>({id,label:p.label})),report:()=>({eyes:api.report(),geometry:viewer.report()}),archive:()=>controller.archive(),restore:a=>{controller.restore(a);render();},open,view,side:value=>{if(!['both','left','right'].includes(value))throw Error('未知侧别');side=value;render();},ready:()=>viewer.skin.naturalEyesReady};
 open();Promise.all([viewer.skin.naturalEyesReady,viewer.skin.faceReady].filter(Boolean)).then(()=>{if(!disposed){view('eyes');syncStatus();}});
}
