const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{chromium}=require('playwright'),{PNG}=require('pngjs');
const out=process.env.EYE_EVIDENCE||path.resolve('eye-evidence');fs.mkdirSync(out,{recursive:true});
const url=process.env.EYE_URL||'http://127.0.0.1:8765/kaopu-unified-human-workbench/eye-materials/preview.html';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function difference(a,b,region){const A=PNG.sync.read(a),B=PNG.sync.read(b);assert.equal(A.width,B.width);assert.equal(A.height,B.height);const r=region||{x:0,y:0,width:A.width,height:A.height};let changed=0,sum=0;for(let y=Math.max(0,Math.floor(r.y));y<Math.min(A.height,Math.ceil(r.y+r.height));y++)for(let x=Math.max(0,Math.floor(r.x));x<Math.min(A.width,Math.ceil(r.x+r.width));x++){const i=(y*A.width+x)*4,d=Math.abs(A.data[i]-B.data[i])+Math.abs(A.data[i+1]-B.data[i+1])+Math.abs(A.data[i+2]-B.data[i+2]);if(d>6)changed++;sum+=d;}return{changedPixels:changed,sumChannelDelta:sum};}
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,acceptDownloads:true}),page=await context.newPage();page.setDefaultTimeout(90000);
 const errors=[],shaderErrors=[],warnings=[],failed=[],tests=[];let report={},failure;
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&/shader|webglprogram|validate_status|undeclared|compile/i.test(m.text()))shaderErrors.push(m.text());else if(m.type()==='warning'||m.type()==='error')warnings.push(m.text());});page.on('requestfailed',r=>failed.push({url:r.url().slice(0,300),error:r.failure()}));
 async function test(name,fn){const start=Date.now(),data=await fn();tests.push({name,passed:true,ms:Date.now()-start,data});console.log('PASS',name);fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify({tests,errors,shaderErrors},null,2));return data;}
 try{
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.naturalEyeWorkbench?.version==='ET16-E1'&&__IDENTITY_QA__.viewer().skin.naturalEyeExtension.ready,{timeout:120000});await page.waitForTimeout(1500);
  await page.evaluate(()=>{naturalEyeWorkbench.open();naturalEyeWorkbench.preset('harveyHazel');naturalEyeWorkbench.view('eyes');__IDENTITY_QA__.viewer().renderer.domElement.dataset.et16Canvas='true';window.__EYE_TEST_BASE=naturalEyeWorkbench.archive();});
  const canvas=page.locator('canvas[data-et16-canvas]');
  async function snap(name){await page.evaluate(()=>__IDENTITY_QA__.viewer().render());await page.waitForTimeout(100);const rect=await canvas.boundingBox();assert.ok(rect&&rect.width>100&&rect.height>100);const b=await page.screenshot({clip:rect,timeout:90000});if(name)fs.writeFileSync(path.join(out,name+'.png'),b);return b;}
  await page.screenshot({path:path.join(out,'desktop-natural-eyes.png')});assert.equal(shaderErrors.length,0);
  await test('native buffers and nonocular triangles preserved',()=>page.evaluate(()=>{const m=__IDENTITY_QA__.model(),v=__IDENTITY_QA__.viewer(),c=__IDENTITY_QA__.controller(),r=v.report(),src=v.currentOcular.source.attributes.position.array,dst=v.geometry.attributes.position.array;let delta=0;for(let i=0;i<src.length;i++)delta=Math.max(delta,Math.abs(src[i]-dst[i]));if(delta!==0||m.positions!==c.positionReference||m.faces!==c.faceReference||r.ocular.nonOcularTrianglesChanged!==0)throw Error('Native geometry changed');for(const x of dst)if(!Number.isFinite(x))throw Error('Nonfinite geometry');return{...r.ocular,retainedPrefixDelta:delta,nativeVertices:r.nativeVertices,displayVertices:r.displayVertices,displayTriangles:r.displayTriangles};}));
  await test('contact is measured from current skin and ocular intersections',()=>page.evaluate(()=>{const v=__IDENTITY_QA__.viewer(),r=v.eyeContact.report;if(r.eyes.some(e=>e.contactSegments<10)||r.addedGeometry!==0||r.nativePositionsChanged!==0)throw Error('Missing measured contact');const n=r.updates;naturalEyeWorkbench.set({tearWetness:.52},'both');if(v.eyeContact.report.updates!==n)throw Error('Material input rebuilt contact');return r;}));
  await test('six natural presets produce distinct actual images',async()=>{const rows=[];for(const p of await page.evaluate(()=>naturalEyeWorkbench.presets())){await page.evaluate(id=>naturalEyeWorkbench.preset(id),p.id);const img=await snap('preset-'+p.id);rows.push({id:p.id,pixelSHA256:hash(img)});}assert.equal(new Set(rows.map(r=>r.pixelSHA256)).size,6);return rows;});
  await test('left and right labels address the matching anatomical eye pixels',async()=>{
   await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.view('eyes');});
   const boxes=await page.evaluate(()=>{const m=__IDENTITY_QA__.model(),v=__IDENTITY_QA__.viewer(),rect=v.renderer.domElement.getBoundingClientRect(),result={};for(const e of m.eyeSurface.eyes){const q=e.vertices.map(i=>v.camera.position.clone().set(m.positions[i*3],m.positions[i*3+2],-m.positions[i*3+1]).project(v.camera)),xs=q.map(p=>(p.x+1)*rect.width/2),ys=q.map(p=>(1-p.y)*rect.height/2);result[e.side]={x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)};}return result;});
   const rows=[];for(const side of ['left','right']){await page.evaluate(()=>naturalEyeWorkbench.preset('harveyHazel','both'));const a=await snap();await page.evaluate(side=>naturalEyeWorkbench.set({tint:'#3260a0',tintAmount:1},side),side);const b=await snap('anatomical-'+side),own=difference(a,b,boxes[side]),other=difference(a,b,boxes[side==='left'?'right':'left']);assert.ok(own.changedPixels>100);assert.equal(other.changedPixels,0,'Opposite anatomical eye changed');rows.push({side,own,other});}return{boxes,rows};
  });
  await test('pupil sclera vessels optics and new transitions change actual pixels',async()=>{const rows=[];for(const[k,a,b]of [['pupil',.24,.59],['yellow',0,.75],['redness',0,.8],['veinAmount',0,1],['veinDensity',0,1],['wetness',0,1],['limbusSoftness',.015,.16],['pupilFeather',.003,.035],['contactShadow',0,1],['tearWetness',0,1]]){await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.set({veinAmount:1,veinDensity:1},'both');});await page.evaluate(([k,v])=>naturalEyeWorkbench.set({[k]:v},'both'),[k,a]);const x=await snap();await page.evaluate(([k,v])=>naturalEyeWorkbench.set({[k]:v},'both'),[k,b]);const y=await snap('control-'+k),d=difference(x,y);assert.ok(d.changedPixels>0,k+' had no rendered effect');rows.push({key:k,...d});}return rows;});
  await test('original-source mode bypasses iris and sclera edits',async()=>{await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.set({reference:true},'global');});const a=await snap('original-source');await page.evaluate(()=>naturalEyeWorkbench.set({tint:'#998844',tintAmount:1,pupil:.58,redness:.9,veinAmount:1},'both'));const b=await snap(),d=difference(a,b);assert.equal(d.changedPixels,0);return d;});
  await test('no imaginary catchlight remains when scene direct lights are off',async()=>{await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.light('off');naturalEyeWorkbench.set({wetness:0},'both');});const a=await snap();await page.evaluate(()=>naturalEyeWorkbench.set({wetness:1},'both'));const b=await snap('lamps-off'),d=difference(a,b);assert.equal(d.changedPixels,0);await page.evaluate(()=>naturalEyeWorkbench.light('left'));await snap('light-left');await page.evaluate(()=>naturalEyeWorkbench.light('right'));await snap('light-right');await page.evaluate(()=>naturalEyeWorkbench.light('original'));return d;});
  await test('ET15 archives migrate with named eye parameters retained',()=>page.evaluate(()=>{const api=naturalEyeWorkbench,now=api.archive(),old=structuredClone(now);old.naturalEyes.schema='kaopu/natural-eyes@1';for(const side of ['left','right'])for(const k of ['limbusWidth','limbusSoftness','pupilFeather','vesselSoftness','contactShadow','tearWetness'])delete old.naturalEyes[side][k];api.restore(old);const s=api.settings();if(s.schema!=='kaopu/natural-eyes@2'||s.left.tint!==old.naturalEyes.left.tint||!Number.isFinite(s.left.limbusSoftness))throw Error('Migration failed');api.restore(now);return{schema:s.schema,oldLabelsPreserved:true,newDefaultsAdded:true};}));
  await test('complete archive round trip and invalid archive rollback',()=>page.evaluate(()=>{const a=naturalEyeWorkbench.archive(),s=JSON.stringify(a.naturalEyes);naturalEyeWorkbench.preset('slate','both');naturalEyeWorkbench.restore(a);if(JSON.stringify(naturalEyeWorkbench.settings())!==s)throw Error('Eye archive lost');const bad=structuredClone(a);bad.naturalEyes.left.pupil=5;let rejected=false;try{naturalEyeWorkbench.restore(bad);}catch{rejected=true;}if(!rejected||JSON.stringify(naturalEyeWorkbench.settings())!==s)throw Error('Invalid archive rollback failed');return{roundTrip:true,invalidRejected:true};}));
  await test('36 character presets retain finite geometry and fixed buffers',async()=>{const rows=await page.evaluate(()=>fullCommonWorkbench.presets());assert.equal(rows.length,36);const result=[];for(const p of rows){const id=typeof p==='string'?p:p.id;result.push(await page.evaluate(id=>{const c=__IDENTITY_QA__.controller(),m=__IDENTITY_QA__.model();c.applyPreset(id);if(!m.positions.every(Number.isFinite)||m.positions!==c.positionReference||m.faces!==c.faceReference)throw Error('Preset topology failure '+id);return{id,eyeProfile:JSON.stringify(m.naturalEyes.settings),contact:__IDENTITY_QA__.viewer().eyeContact.report};},id));}assert.equal(new Set(result.map(r=>r.eyeProfile)).size,36);return result;});
  await page.evaluate(()=>{naturalEyeWorkbench.restore(window.__EYE_TEST_BASE);naturalEyeWorkbench.open();naturalEyeWorkbench.view('eyes');});
  await test('gaze and open half-closed closed paths retain material attachment',async()=>{const rows=[];for(const[axis,value]of [[6,.16],[6,-.16],[7,.16],[7,-.16]]){rows.push(await page.evaluate(([axis,value])=>{const c=__IDENTITY_QA__.controller(),m=__IDENTITY_QA__.model();c.restore(window.__EYE_TEST_BASE);const s=c.state();s.gnm.rotation[axis]=s.gnm.rotation[axis+3]=value;c.commit(s);if(!m.positions.every(Number.isFinite))throw Error('Nonfinite gaze');const p=Array.from(m.positions);naturalEyeWorkbench.set({redness:.17},'both');if(p.some((v,i)=>v!==m.positions[i]))throw Error('Material altered pose');return{axis,value,contact:__IDENTITY_QA__.viewer().eyeContact.report};},[axis,value]));}
   const blinks=[];for(const t of [0,.5,1]){blinks.push(await page.evaluate(t=>{const c=__IDENTITY_QA__.controller();c.restore(window.__EYE_TEST_BASE);naturalEyeWorkbench.blink(t);return{t,contact:naturalEyeWorkbench.contactReport()};},t));await snap('blink-'+t);}await page.evaluate(()=>naturalEyeWorkbench.restore(window.__EYE_TEST_BASE));return{gaze:rows,blinks,anatomicalClosureCertified:false};});
  await test('actual UI fields and new transition sliders write selected parameters',async()=>{await page.locator('#naturalEyeSide').selectOption('left');await page.locator('input[data-eye-key="tint"]').evaluate(el=>{el.value='#6b785c';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('input[data-et16-key="limbusSoftness"]').evaluate(el=>{el.value='.12';el.dispatchEvent(new Event('input',{bubbles:true}));});const s=await page.evaluate(()=>naturalEyeWorkbench.settings());assert.equal(s.left.tint,'#6b785c');assert.equal(s.left.limbusSoftness,.12);assert.notEqual(s.right.limbusSoftness,.12);return{left:s.left,right:s.right,nativeColorDialogTested:false};});
  await test('save button exports complete ET16 person',async()=>{const promise=page.waitForEvent('download');await page.locator('[data-eye-action="save"]').click();const d=await promise,f=path.join(out,'saved-person.json');await d.saveAs(f);const a=JSON.parse(fs.readFileSync(f));assert.equal(a.naturalEyes.schema,'kaopu/natural-eyes@2');assert.ok(a.faceIdentity&&a.state&&a.surface);return{bytes:fs.statSync(f).size};});
  await page.evaluate(()=>{naturalEyeWorkbench.restore(window.__EYE_TEST_BASE);naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.view('macro');});await snap('iris-macro');
  await page.evaluate(()=>{naturalEyeWorkbench.view('eyes');const v=__IDENTITY_QA__.viewer();v.camera.position.x+=.034;v.camera.lookAt(v.orbit.target);v.render();});await snap('oblique-eyes');
  await page.evaluate(()=>naturalEyeWorkbench.view('face'));await page.screenshot({path:path.join(out,'whole-face.png')});await page.evaluate(()=>{naturalEyeWorkbench.open();naturalEyeWorkbench.view('eyes');});await page.screenshot({path:path.join(out,'desktop-final.png')});
  assert.equal(errors.length,0);assert.equal(shaderErrors.length,0);report=await page.evaluate(()=>naturalEyeWorkbench.report());
 }catch(e){failure=String(e.stack||e);console.error(failure);try{await page.screenshot({path:path.join(out,'failure.png')});report=await page.evaluate(()=>({body:document.body.innerText,report:window.naturalEyeWorkbench?.report()}));}catch{}}
 fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({version:'ET16-E1',url,passed:!failure,desktop:{width:1440,height:900,deviceScaleFactor:1,renderer:'Chromium SwiftShader; not consumer GPU performance',capture:'actual page pixels clipped to canvas; normal full skin rendering'},mobileTested:false,tests,failure,errors,shaderErrors,warnings,failed,report},null,2));await context.close();await browser.close();if(failure)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
