const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{chromium}=require('playwright'),{PNG}=require('pngjs');
const out=process.env.EYE_EVIDENCE||path.resolve('eye-evidence');fs.mkdirSync(out,{recursive:true});
const url=process.env.EYE_URL||'http://127.0.0.1:8765/kaopu-unified-human-workbench/eye-materials/preview.html';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function difference(a,b){const x=PNG.sync.read(a),y=PNG.sync.read(b);assert.equal(x.width,y.width);assert.equal(x.height,y.height);let changed=0,sum=0;for(let i=0;i<x.data.length;i+=4){const d=Math.abs(x.data[i]-y.data[i])+Math.abs(x.data[i+1]-y.data[i+1])+Math.abs(x.data[i+2]-y.data[i+2]);if(d>6)changed++;sum+=d;}return{changedPixels:changed,meanChannelDelta:sum/(x.width*x.height*3)};}
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox']}),context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1,acceptDownloads:true}),page=await context.newPage();const errors=[],shaderErrors=[],warnings=[],failed=[],tests=[];let report={},failure;
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&/shader|webglprogram|validate_status|undeclared|compile/i.test(m.text()))shaderErrors.push(m.text());else if(m.type()==='warning'||m.type()==='error')warnings.push(m.text());});page.on('requestfailed',r=>failed.push({url:r.url().slice(0,300),error:r.failure()}));
 async function test(name,fn){const start=Date.now();const data=await fn();tests.push({name,passed:true,ms:Date.now()-start,data});console.log('PASS',name);return data;}
 try{
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.naturalEyeWorkbench&&__IDENTITY_QA__.viewer().skin.naturalEyeExtension.ready,{timeout:120000});await page.waitForTimeout(1800);
  await page.evaluate(()=>{naturalEyeWorkbench.open();naturalEyeWorkbench.preset('harveyHazel');naturalEyeWorkbench.view('eyes');__IDENTITY_QA__.viewer().renderer.domElement.dataset.et15Canvas='true';});await page.waitForTimeout(300);
  const canvas=page.locator('canvas[data-et15-canvas]'),snap=async name=>{await page.evaluate(()=>__IDENTITY_QA__.viewer().render());await page.waitForTimeout(120);const b=await canvas.screenshot();if(name)fs.writeFileSync(path.join(out,name+'.png'),b);return b;};
  await page.screenshot({path:path.join(out,'desktop-natural-eyes.png')});assert.equal(shaderErrors.length,0,'Shader must compile before visual tests');
  await test('native geometry and body preserved',()=>page.evaluate(()=>{const m=__IDENTITY_QA__.model(),v=__IDENTITY_QA__.viewer(),c=__IDENTITY_QA__.controller(),r=v.report(),src=v.currentOcular.source.attributes.position.array,dst=v.geometry.attributes.position.array;let delta=0;for(let i=0;i<src.length;i++)delta=Math.max(delta,Math.abs(src[i]-dst[i]));if(delta!==0||m.positions!==c.positionReference||m.faces!==c.faceReference||r.ocular.nonOcularTrianglesChanged!==0)throw Error('Native geometry changed');for(const x of dst)if(!Number.isFinite(x))throw Error('Nonfinite geometry');window.__EYE_TEST_BASE=c.archive();return{...r.ocular,nativeVertices:r.nativeVertices,displayVertices:r.displayVertices,displayTriangles:r.displayTriangles,retainedPrefixDelta:delta};}));
  await test('six natural presets produce distinct rendered eyes',async()=>{const results=[];for(const p of await page.evaluate(()=>naturalEyeWorkbench.presets())){await page.evaluate(id=>naturalEyeWorkbench.preset(id),p.id);const img=await snap('preset-'+p.id);results.push({id:p.id,pixelSHA256:hash(img)});}assert.equal(new Set(results.map(r=>r.pixelSHA256)).size,6);return results;});
  await test('left/right parameter independence',()=>page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');const right=JSON.stringify(naturalEyeWorkbench.settings().right);naturalEyeWorkbench.set({tint:'#777f90',tintAmount:.9,pupil:.3},'left');if(JSON.stringify(naturalEyeWorkbench.settings().right)!==right)throw Error('Right eye changed');return naturalEyeWorkbench.settings();}));await snap('left-right-independent');
  await test('pupil sclera vessels and optics alter actual canvas pixels',async()=>{const results=[];for(const[key,a,b]of [['pupil',.24,.59],['yellow',0,.75],['redness',0,.8],['veinAmount',0,1],['veinDensity',0,1],['wetness',0,1]]){await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.set({veinAmount:1,veinDensity:1},'both');});await page.evaluate(([k,v])=>naturalEyeWorkbench.set({[k]:v},'both'),[key,a]);const x=await snap();await page.evaluate(([k,v])=>naturalEyeWorkbench.set({[k]:v},'both'),[key,b]);const y=await snap('control-'+key);const d=difference(x,y);assert.ok(d.changedPixels>10,key+' did not alter rendered eye pixels');results.push({key,...d});}return results;});
  await test('original source mode bypasses tint pupil and vessel modifications',async()=>{await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.set({reference:true},'global');});const a=await snap('original-source');await page.evaluate(()=>naturalEyeWorkbench.set({tint:'#998844',tintAmount:1,pupil:.58,redness:.9,veinAmount:1},'both'));const b=await snap();const d=difference(a,b);assert.equal(d.changedPixels,0);return d;});
  await test('archive round trip and invalid archive rollback',()=>page.evaluate(()=>{const a=naturalEyeWorkbench.archive(),s=JSON.stringify(a.naturalEyes);naturalEyeWorkbench.preset('slate','both');naturalEyeWorkbench.restore(a);if(JSON.stringify(naturalEyeWorkbench.settings())!==s)throw Error('Eye settings lost on restore');const bad=structuredClone(a);bad.naturalEyes.left.pupil=5;let rejected=false;try{naturalEyeWorkbench.restore(bad);}catch{rejected=true;}if(!rejected||JSON.stringify(naturalEyeWorkbench.settings())!==s)throw Error('Invalid archive was not rolled back');return{roundTrip:true,invalidRejected:true};}));
  await test('36 existing presets preserve canonical topology and receive eye profiles',async()=>{const presets=await page.evaluate(()=>fullCommonWorkbench.presets);const rows=Array.isArray(presets)?presets:[];assert.equal(rows.length,36);const results=[];for(const p of rows){const id=typeof p==='string'?p:p.id;results.push(await page.evaluate(id=>{const c=__IDENTITY_QA__.controller(),m=__IDENTITY_QA__.model();c.applyPreset(id);for(const x of m.positions)if(!Number.isFinite(x))throw Error('Nonfinite preset '+id);if(m.positions!==c.positionReference||m.faces!==c.faceReference)throw Error('Topology lost');return{id,vertices:m.vertexCount,eyeProfile:JSON.stringify(m.naturalEyes.settings),ocular:__IDENTITY_QA__.viewer().report().ocular};},id));}assert.ok(new Set(results.map(r=>r.eyeProfile)).size>10);return results;});
  await page.evaluate(()=>{naturalEyeWorkbench.restore(window.__EYE_TEST_BASE);naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.open();naturalEyeWorkbench.view('eyes');});
  await test('native gaze and blink paths remain usable with fixed eye material coordinates',async()=>{const rows=[];for(const [name,axis,value]of [['gaze-a',6,.16],['gaze-b',6,-.16],['gaze-c',7,.16],['gaze-d',7,-.16]]){const r=await page.evaluate(([name,axis,value])=>{const c=__IDENTITY_QA__.controller(),m=__IDENTITY_QA__.model();c.restore(window.__EYE_TEST_BASE);const s=c.state();s.gnm.rotation[axis]=s.gnm.rotation[axis+3]=value;c.commit(s);for(const p of m.positions)if(!Number.isFinite(p))throw Error('Nonfinite gaze');const before=Array.from(m.positions);naturalEyeWorkbench.set({redness:.17},'both');if(before.some((v,i)=>v!==m.positions[i]))throw Error('Material edited native gaze geometry');return{name,canonicalUnchangedByMaterial:true};},[name,axis,value]);rows.push(r);await snap(name);}await page.evaluate(()=>{const c=__IDENTITY_QA__.controller();c.restore(window.__EYE_TEST_BASE);const s=c.state();s.owners.expression='anny';s.anny.facialActions.eyeBlinkLeft=.65;s.anny.facialActions.eyeBlinkRight=.65;c.commit(s);});await snap('inherited-blink-65');await page.evaluate(()=>naturalEyeWorkbench.restore(window.__EYE_TEST_BASE));return{gaze:rows,blink:'existing Anny expression path at0.65; visual evidence only, not anatomical closure certification'};});
  await test('real UI color input writes selected iris',async()=>{await page.locator('#naturalEyeSide').selectOption('left');await page.locator('input[data-eye-key="tint"]').fill('#6b785c');const s=await page.evaluate(()=>naturalEyeWorkbench.settings());assert.equal(s.left.tint,'#6b785c');assert.equal(s.left.tintAmount,1);return{left:s.left.tint,right:s.right.tint};});
  await test('real save button exports complete person including eyes',async()=>{const promise=page.waitForEvent('download');await page.locator('[data-eye-action="save"]').click();const d=await promise;const file=path.join(out,'saved-person.json');await d.saveAs(file);const a=JSON.parse(fs.readFileSync(file));assert.equal(a.naturalEyes.schema,'kaopu/natural-eyes@1');assert.ok(a.faceIdentity&&a.state&&a.surface);return{filename:d.suggestedFilename(),bytes:fs.statSync(file).size};});
  await page.evaluate(()=>{naturalEyeWorkbench.preset('harveyHazel','both');naturalEyeWorkbench.view('macro');});await snap('iris-macro');
  await page.evaluate(()=>{naturalEyeWorkbench.view('eyes');const v=__IDENTITY_QA__.viewer();v.camera.position.x+=.034;v.camera.lookAt(v.orbit.target);v.render();});await snap('oblique-eyes');
  await page.evaluate(()=>naturalEyeWorkbench.view('face'));await page.screenshot({path:path.join(out,'whole-face.png')});
  await page.evaluate(()=>{naturalEyeWorkbench.open();naturalEyeWorkbench.view('eyes');});await page.screenshot({path:path.join(out,'desktop-final.png')});
  assert.equal(errors.length,0,'Browser exceptions');assert.equal(shaderErrors.length,0,'Shader compilation failures');report=await page.evaluate(()=>naturalEyeWorkbench.report());
 }catch(e){failure=String(e.stack||e);console.error(failure);try{await page.screenshot({path:path.join(out,'failure.png')});report=await page.evaluate(()=>({body:document.body.innerText,report:window.naturalEyeWorkbench?.report()}));}catch{}}
 fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({url,passed:!failure,desktop:{width:1600,height:1000,deviceScaleFactor:1,renderer:'GitHub Actions Chromium SwiftShader; not a consumer GPU benchmark'},mobileTested:false,tests,failure,errors,shaderErrors,warnings,failed,report},null,2));
 await context.close();await browser.close();if(failure)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
