'use strict';
const KFS8_SCORE_B64="__KFC8_SCORE_BASE64__";
const WORKBENCH_MODE=true;
const A=globalThis.KaopuFishContinuousSkin;
const CHANNEL_LABELS=['躯干','头部','下颌','鳃盖','眼窝','胸鳍 +Z','胸鳍 −Z','前背鳍','后背鳍','腹鳍','臀鳍','尾鳍'];
const CHANNEL_KEYS=['body','head','jaw','gill','eyeSocket','pectoralPositive','pectoralNegative','dorsalAnterior','dorsalPosterior','pelvic','anal','caudal'];
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function setLoad(t,p){document.getElementById('loadText').textContent=t;if(p!=null)document.getElementById('loadBarFill').style.width=(p*100)+'%';}
function fromB64(t){const s=atob(t),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a;}
function compileShader(gl,type,source){const sh=gl.createShader(type);gl.shaderSource(sh,source);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(sh);gl.deleteShader(sh);throw Error('Shader compile failed: '+log);}return sh;}
function createProgram(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,compileShader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,compileShader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const log=gl.getProgramInfoLog(p);gl.deleteProgram(p);throw Error('Program link failed: '+log);}return p;}
function bufferData(gl,target,data,usage=gl.STATIC_DRAW){const b=gl.createBuffer();gl.bindBuffer(target,b);gl.bufferData(target,data,usage);return b;}
function mat4Identity(){const o=new Float32Array(16);o[0]=o[5]=o[10]=o[15]=1;return o;}
function mat4Multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++){const b0=b[c*4],b1=b[c*4+1],b2=b[c*4+2],b3=b[c*4+3];o[c*4]=a[0]*b0+a[4]*b1+a[8]*b2+a[12]*b3;o[c*4+1]=a[1]*b0+a[5]*b1+a[9]*b2+a[13]*b3;o[c*4+2]=a[2]*b0+a[6]*b1+a[10]*b2+a[14]*b3;o[c*4+3]=a[3]*b0+a[7]*b1+a[11]*b2+a[15]*b3;}return o;}
function mat4Ortho(l,r,b,t,n,f){const o=mat4Identity();o[0]=2/(r-l);o[5]=2/(t-b);o[10]=-2/(f-n);o[12]=-(r+l)/(r-l);o[13]=-(t+b)/(t-b);o[14]=-(f+n)/(f-n);return o;}
function normalize3(v){const l=Math.hypot(v[0],v[1],v[2])||1;return [v[0]/l,v[1]/l,v[2]/l];}
function cross3(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
function mat4LookAt(eye,target,up){const z=normalize3([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=normalize3(cross3(up,z)),y=cross3(z,x),o=mat4Identity();o[0]=x[0];o[1]=y[0];o[2]=z[0];o[4]=x[1];o[5]=y[1];o[6]=z[1];o[8]=x[2];o[9]=y[2];o[10]=z[2];o[12]=-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]);o[13]=-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]);o[14]=-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]);return o;}
class OrbitCamera{
 constructor(canvas){this.canvas=canvas;this.target=[0,.14,0];this.yaw=-.45;this.pitch=.75;this.zoom=1;this.distance=1.55;this.upMode='Y';this.drag=null;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,button:e.button,shift:e.shiftKey};});canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.drag.x=e.clientX;this.drag.y=e.clientY;if(this.drag.button===2||this.drag.shift)this.pan(dx,dy);else{this.yaw-=dx*.006;this.pitch=clamp(this.pitch-dy*.006,-1.54,1.54);this.upMode='Y';}});const clear=()=>this.drag=null;canvas.addEventListener('pointerup',clear);canvas.addEventListener('pointercancel',clear);canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=clamp(this.zoom*Math.exp(-e.deltaY*.0012),.45,15);},{passive:false});}
 eye(){const cp=Math.cos(this.pitch);return [this.target[0]+this.distance*cp*Math.sin(this.yaw),this.target[1]+this.distance*Math.sin(this.pitch),this.target[2]+this.distance*cp*Math.cos(this.yaw)];}
 up(){return this.upMode==='NEG_Z'?[0,0,-1]:this.upMode==='POS_Z'?[0,0,1]:[0,1,0];}
 matrices(aspect){const eye=this.eye(),view=mat4LookAt(eye,this.target,this.up()),halfW=.58/this.zoom,halfH=halfW/Math.max(aspect,.05);return{view,projection:mat4Ortho(-halfW,halfW,-halfH,halfH,.01,20),eye};}
 mvp(aspect){const m=this.matrices(aspect);return{...m,mvp:mat4Multiply(m.projection,m.view)};}
 pan(dx,dy){const eye=this.eye(),f=normalize3([this.target[0]-eye[0],this.target[1]-eye[1],this.target[2]-eye[2]]),right=normalize3(cross3(f,this.up())),up=cross3(right,f),s=.0011/this.zoom;for(let i=0;i<3;i++)this.target[i]+=(-dx*right[i]+dy*up[i])*s;}
 setView(id){this.upMode='Y';this.zoom=1;if(id==='left'){this.yaw=0;this.pitch=0;}else if(id==='right'){this.yaw=Math.PI;this.pitch=0;}else if(id==='head'){this.yaw=-Math.PI/2;this.pitch=0;this.zoom=1.25;}else if(id==='tail'){this.yaw=Math.PI/2;this.pitch=0;this.zoom=1.25;}else if(id==='top'){this.yaw=0;this.pitch=Math.PI/2-.0001;this.upMode='NEG_Z';}else if(id==='bottom'){this.yaw=0;this.pitch=-Math.PI/2+.0001;this.upMode='POS_Z';}else{this.yaw=-.72;this.pitch=.23;}this.target=[0,.14,0];}
}
const MESH_VERTEX=`#version 300 es
precision highp float;precision highp int;
layout(location=0) in vec3 aPosition;
layout(location=1) in vec2 aNormalOct;
layout(location=2) in vec2 aUv;
layout(location=3) in vec4 aW0;
layout(location=4) in vec4 aW1;
layout(location=5) in vec4 aW2;
layout(location=6) in uvec2 aPartInfo;
layout(location=7) in vec3 aPartRoot;
uniform mat4 uMvp,uView;
uniform highp sampler2D uField;
uniform vec2 uBodyRange;
uniform vec3 uJawPivot;
uniform vec3 uPartBend[7];
uniform vec4 uResponse0,uResponse1,uResponse2;
uniform float uJaw,uGill,uEyeRecess;
uniform int uSamples;
uniform bool uAnimate;
out vec3 vNormal,vViewPos,vWorldPos;
out vec4 vW0,vW1,vW2;
out vec2 vUv;
flat out uint vPartId;
vec4 field(int row,float t){float f=clamp(t,0.0,1.0)*float(uSamples-1);int i=int(floor(f));return mix(texelFetch(uField,ivec2(i,row),0),texelFetch(uField,ivec2(min(i+1,uSamples-1),row),0),fract(f));}
vec3 octNormal(vec2 e){vec3 n=vec3(e,1.0-abs(e.x)-abs(e.y));if(n.z<0.0)n.xy=(1.0-abs(n.yx))*sign(n.xy+1e-8);return normalize(n);}
vec3 rotateAxis(vec3 n,vec3 axis,float a){return n*cos(a)+cross(axis,n)*sin(a)+axis*dot(axis,n)*(1.0-cos(a));}
float partWeight(uint id){if(id==1u)return aW1.y;if(id==2u)return aW1.z;if(id==3u)return aW1.w;if(id==4u)return aW2.x;if(id==5u)return aW2.y;if(id==6u)return aW2.z;if(id==7u)return aW2.w;return 0.0;}
// Spine angles are guarded to +/-1.35 radians. Polynomial evaluation avoids
// driver-specific native sin/cos approximations displacing complete sections.
float spineSin(float x){float q=x*x;return x*(1.0+q*(-1.0/6.0+q*(1.0/120.0+q*(-1.0/5040.0+q*(1.0/362880.0-q/39916800.0)))));}
float spineCos(float x){float q=x*x;return 1.0+q*(-1.0/2.0+q*(1.0/24.0+q*(-1.0/720.0+q*(1.0/40320.0+q*(-1.0/3628800.0+q/479001600.0)))));}
void main(){
 vec3 p=aPosition,n=octNormal(aNormalOct);
 p-=n*(uEyeRecess*aW1.x);
 if(uAnimate){
  float j=uJaw*aW0.z;vec3 q=p-uJawPivot;p=uJawPivot+vec3(cos(j)*q.x-sin(j)*q.y,sin(j)*q.x+cos(j)*q.y,q.z);n=rotateAxis(n,vec3(0,0,1),j);
  p.z+=sign(p.z+1e-8)*uGill*aW0.w;
  uint pid=aPartInfo.x;
  if(pid>0u&&pid<=7u){float t=float(aPartInfo.y)/65535.0;vec4 f=field(int(pid)+1,t);vec3 ray=p-aPartRoot;float L=length(ray);vec3 T=ray/max(L,1e-9),U=normalize(uPartBend[int(pid)-1]);float w=partWeight(pid);vec3 pd=aPartRoot+ray*f.x+U*L*f.y;p=mix(p,pd,w);vec3 rawAxis=cross(T,U);float axisLength=length(rawAxis);if(w>0.0&&abs(f.z)>1e-8&&axisLength>1e-8)n=rotateAxis(n,rawAxis/axisLength,f.z*w);}
  float anchorX=clamp(aPosition.x,uBodyRange.x,uBodyRange.y);float s=(anchorX-uBodyRange.x)/(uBodyRange.y-uBodyRange.x);vec4 f=field(0,s),g=field(1,s);float ca=spineCos(f.w),sa=spineSin(f.w),cb=spineCos(g.x),sb=spineSin(g.x);vec3 T=vec3(ca*cb,sb,sa*cb),U=vec3(-ca*sb,cb,-sa*sb),N=vec3(-sa,0,ca);mat3 frame=mat3(T,U,N);p=vec3(anchorX+f.x,g.y+f.y,g.z+f.z)+frame*(p-vec3(anchorX,g.y,g.z));n=normalize(frame*n);
 }
 vNormal=normalize(mat3(uView)*n);vViewPos=(uView*vec4(p,1)).xyz;vWorldPos=p;vUv=aUv;vW0=aW0;vW1=aW1;vW2=aW2;vPartId=aPartInfo.x;gl_Position=uMvp*vec4(p,1);
}`;
const MESH_FRAGMENT=`#version 300 es
precision highp float;precision highp int;
in vec3 vNormal,vViewPos,vWorldPos;
in vec4 vW0,vW1,vW2;
in vec2 vUv;flat in uint vPartId;
uniform sampler2D uBase,uNormal,uRm;
uniform vec4 uResponse0,uResponse1,uResponse2;
uniform bool uNormalMap;
uniform int uMode,uWeightChannel;
out vec4 outColor;
vec3 toLinear(vec3 c){return mix(c/12.92,pow((c+.055)/1.055,vec3(2.4)),step(vec3(.04045),c));}
vec3 toSRGB(vec3 c){return mix(c*12.92,1.055*pow(max(c,0.0),vec3(1.0/2.4))-.055,step(vec3(.0031308),c));}
float weight(int i){if(i==0)return vW0.x;if(i==1)return vW0.y;if(i==2)return vW0.z;if(i==3)return vW0.w;if(i==4)return vW1.x;if(i==5)return vW1.y;if(i==6)return vW1.z;if(i==7)return vW1.w;if(i==8)return vW2.x;if(i==9)return vW2.y;if(i==10)return vW2.z;if(i==11)return vW2.w;return 0.0;}
float response(int i){if(i==0)return uResponse0.x;if(i==1)return uResponse0.y;if(i==2)return uResponse0.z;if(i==3)return uResponse0.w;if(i==4)return uResponse1.x;if(i==5)return uResponse1.y;if(i==6)return uResponse1.z;if(i==7)return uResponse1.w;if(i==8)return uResponse2.x;if(i==9)return uResponse2.y;if(i==10)return uResponse2.z;if(i==11)return uResponse2.w;return 0.0;}
vec3 heat(float x){x=clamp(x,0.0,1.0);return clamp(vec3(1.5-abs(4.0*x-3.0),1.5-abs(4.0*x-2.0),1.5-abs(4.0*x-1.0)),0.0,1.0);}
vec3 weightComposite(){vec3 c=vec3(0);float s=0.0;for(int i=5;i<12;i++){float w=weight(i);vec3 k=i==0?vec3(.15,.75,1.0):i==1?vec3(.75,.95,1.0):i==2?vec3(1,.32,.12):i==3?vec3(.2,1,.65):i==4?vec3(1,.72,.15):i==5?vec3(.15,.85,.95):i==6?vec3(.75,.35,1):i==7?vec3(1,.18,.55):i==8?vec3(.95,.55,.12):i==9?vec3(.2,.85,.2):i==10?vec3(.1,.55,1):vec3(1,.85,.1);c+=w*k;s+=w;}return c/max(s,.0001);}
vec3 mappedNormal(){vec3 N=normalize(vNormal);if(uNormalMap&&uMode==0){vec3 dx=dFdx(vViewPos),dy=dFdy(vViewPos);vec2 tx=dFdx(vUv),ty=dFdy(vUv);float det=tx.x*ty.y-tx.y*ty.x;if(abs(det)>1e-12){vec3 T=(dx*ty.y-dy*tx.y)*sign(det),rawB=(-dx*ty.x+dy*tx.x)*sign(det);T=normalize(T-N*dot(N,T));vec3 B=normalize(cross(N,T));if(dot(B,rawB)<0.0)B=-B;vec3 sampleN=texture(uNormal,vUv).xyz*2.0-1.0;N=normalize(mat3(T,B,N)*sampleN);}}return gl_FrontFacing?N:-N;}
void main(){
 vec3 tex=texture(uBase,vUv).rgb;float eyeMask=smoothstep(.26,.88,vW1.x);tex=mix(tex,vec3(.055,.065,.06),eyeMask*.92);
 if(uMode==4){outColor=vec4(tex,1);return;}if(uMode==3){outColor=vec4(fract(vUv),.25,1);return;}if(uMode==5){outColor=vec4(weightComposite(),1);return;}if(uMode==6){outColor=vec4(heat(weight(uWeightChannel)),1);return;}if(uMode==7){outColor=vec4(mix(vec3(.025,.035,.04),vec3(1,.65,.13),eyeMask),1);return;}if(uMode==8){float a=0.0;for(int i=5;i<12;i++)a+=weight(i)*response(i);outColor=vec4(heat(clamp(a*.72,0.0,1.0)),1);return;}
 vec3 N=mappedNormal();if(uMode==2){outColor=vec4(N*.5+.5,1);return;}vec3 base=uMode==1?vec3(.56):toLinear(tex),rm=texture(uRm,vUv).rgb;float rough=uMode==1?.66:clamp(rm.g,.18,.98),metal=uMode==1?0.0:clamp(rm.b,0.,1.);vec3 L=normalize(vec3(-.4,.75,.8)),L2=normalize(vec3(.7,.3,-.45)),V=normalize(-vViewPos);float diff=max(dot(N,L),0.),fill=max(dot(N,L2),0.),spec=pow(max(dot(N,normalize(V+L)),0.),mix(110.,7.,rough));vec3 lit=base*(.38+.58*diff+.22*fill)+mix(vec3(.028),base,metal)*spec*(1.-rough)*.8;outColor=vec4(toSRGB(clamp(lit,0.,1.)),1);
}`;
const EYE_VERTEX=`#version 300 es
precision highp float;precision highp int;
layout(location=0) in vec3 aPosition;layout(location=1) in vec3 aNormal;layout(location=2) in uint aComponent;layout(location=3) in vec2 aUv;
uniform mat4 uMvp,uView;uniform vec3 uCenter,uTangent,uUp,uOutward;uniform float uGazeYaw,uGazePitch,uPupil,uGlobeRadius;
out vec3 vNormal,vViewPos,vLocal;out vec2 vUv;flat out uint vComponent;
void main(){vec3 local=aPosition,n=aNormal;if(aComponent==2u||aComponent==3u){vec3 dir=normalize(vec3(sin(uGazeYaw),sin(uGazePitch),cos(uGazeYaw)*cos(uGazePitch)));vec3 gx=normalize(vec3(cos(uGazeYaw),0.0,-sin(uGazeYaw)));vec3 gy=normalize(cross(dir,gx));float scale=aComponent==3u?mix(.78,1.34,clamp(uPupil,0.0,1.0)):1.0;float lx=aPosition.x*scale,ly=aPosition.y*scale,lz=sqrt(max(uGlobeRadius*uGlobeRadius-lx*lx-ly*ly,0.0))+(aComponent==3u?.00032:.00022);local=dir*lz+gx*lx+gy*ly;n=normalize(dir*lz+gx*lx+gy*ly);}vec3 world=uCenter+uTangent*local.x+uUp*local.y+uOutward*local.z;vec3 wn=normalize(uTangent*n.x+uUp*n.y+uOutward*n.z);vNormal=normalize(mat3(uView)*wn);vViewPos=(uView*vec4(world,1)).xyz;vLocal=local;vUv=aUv;vComponent=aComponent;gl_Position=uMvp*vec4(world,1);}`;
const EYE_FRAGMENT=`#version 300 es
precision highp float;precision highp int;
in vec3 vNormal,vViewPos,vLocal;in vec2 vUv;flat in uint vComponent;out vec4 outColor;
void main(){vec3 N=gl_FrontFacing?normalize(vNormal):-normalize(vNormal),V=normalize(-vViewPos),L=normalize(vec3(-.35,.8,.7));float d=.25+.75*max(dot(N,L),0.0),s=pow(max(dot(N,normalize(V+L)),0.0),80.0);if(vComponent==0u){vec3 c=mix(vec3(.035,.040,.034),vec3(.23,.24,.17),d);outColor=vec4(c+s*.20,1.0);return;}if(vComponent==1u){vec3 c=mix(vec3(.012,.014,.012),vec3(.075,.064,.035),d);outColor=vec4(c+s*.08,1);return;}if(vComponent==2u){vec2 p=vUv-.5;float r=length(p)*2.0,ang=atan(p.y,p.x);float rays=.5+.5*sin(ang*39.0+r*17.0);float fleck=.5+.5*sin(ang*13.0-r*31.0);vec3 dark=vec3(.11,.075,.018),gold=vec3(.74,.50,.09),pale=vec3(.96,.80,.30);vec3 c=mix(dark,gold,smoothstep(.06,.86,r));c=mix(c,pale,(rays*.13+fleck*.07)*(1.0-r));c*=.62+.62*d;outColor=vec4(c+s*.22,1);return;}if(vComponent==3u){float h=pow(max(dot(N,normalize(V+vec3(-.2,.7,.8))),0.0),160.0);outColor=vec4(vec3(.0015)+h*.12,1);return;}float fres=pow(1.0-max(dot(N,V),0.0),3.0);float h1=pow(max(dot(N,normalize(V+vec3(-.35,.85,.55))),0.0),210.0);float h2=pow(max(dot(N,normalize(V+vec3(.55,.3,.75))),0.0),260.0);outColor=vec4(vec3(.11,.25,.28)*(.08+fres*.34)+h1*.65+h2*.18,.10+fres*.22);}`;
const WIRE_FRAGMENT=`#version 300 es
precision highp float;out vec4 outColor;void main(){outColor=vec4(.2,.85,1.,.34);}`;
const LINE_VERTEX=`#version 300 es
precision highp float;layout(location=0) in vec3 aPosition;uniform mat4 uMvp;void main(){gl_Position=uMvp*vec4(aPosition,1);}`;
const LINE_FRAGMENT=`#version 300 es
precision highp float;uniform vec4 uColor;out vec4 outColor;void main(){outColor=uColor;}`;
async function texture(gl,b,mime){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);const bitmap=await createImageBitmap(new Blob([b],{type:mime}),{imageOrientation:'flipY',premultiplyAlpha:'none',colorSpaceConversion:'none'});gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);const format=mime==='image/png'?gl.RGBA:gl.RGB;gl.texImage2D(gl.TEXTURE_2D,0,format,format,gl.UNSIGNED_BYTE,bitmap);bitmap.close();gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return tex;}
class Renderer{
 constructor(canvas,h,gl,textures){this.canvas=canvas;this.h=h;this.gl=gl;this.textures=textures;this.camera=new OrbitCamera(canvas);this.state={mode:'CRUISE',playing:true,speed:1,amplitude:1,finGains:Array(7).fill(1),eyeYawOffset:0,eyePitchOffset:0,pupilBias:0,compare:false,renderMode:0,weightChannel:5,normalMap:true,wire:false,paths:false,eyes:true};this.last=0;this.frames=0;this.setup();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas.parentElement);this.resize();}
 setup(){const gl=this.gl,h=this.h;gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);this.program=createProgram(gl,MESH_VERTEX,MESH_FRAGMENT);this.wireProgram=createProgram(gl,MESH_VERTEX,WIRE_FRAGMENT);this.eyeProgram=createProgram(gl,EYE_VERTEX,EYE_FRAGMENT);this.lineProgram=createProgram(gl,LINE_VERTEX,LINE_FRAGMENT);
  this.buffers=[bufferData(gl,gl.ARRAY_BUFFER,h.positions),bufferData(gl,gl.ARRAY_BUFFER,h.normalOct),bufferData(gl,gl.ARRAY_BUFFER,h.uv),bufferData(gl,gl.ARRAY_BUFFER,h.weights),bufferData(gl,gl.ARRAY_BUFFER,h.partInfo),bufferData(gl,gl.ARRAY_BUFFER,h.partRoot)];this.index=bufferData(gl,gl.ELEMENT_ARRAY_BUFFER,h.indices);const edges=[];for(let i=0;i<h.indices.length;i+=3*42){const a=h.indices[i],b=h.indices[i+1],c=h.indices[i+2];edges.push(a,b,b,c,c,a);}this.edgeCount=edges.length;this.edge=bufferData(gl,gl.ELEMENT_ARRAY_BUFFER,new Uint32Array(edges));
  const vao=index=>{const v=gl.createVertexArray();gl.bindVertexArray(v);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[0]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[1]);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,2,gl.SHORT,true,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[2]);gl.enableVertexAttribArray(2);gl.vertexAttribPointer(2,2,gl.UNSIGNED_SHORT,true,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[3]);for(let i=0;i<3;i++){gl.enableVertexAttribArray(3+i);gl.vertexAttribPointer(3+i,4,gl.UNSIGNED_BYTE,true,12,i*4);}gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[4]);gl.enableVertexAttribArray(6);gl.vertexAttribIPointer(6,2,gl.UNSIGNED_SHORT,4,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[5]);gl.enableVertexAttribArray(7);gl.vertexAttribPointer(7,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bindVertexArray(null);return v;};this.vao=vao(this.index);this.wireVao=vao(this.edge);
  this.fieldTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.fieldTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,h.metadata.continuum.body.samples,9,0,gl.RGBA,gl.FLOAT,h.state.field);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
  const eg=A.buildEyeGeometry(h.metadata.continuum.eyes.eyes[0]);this.eyeGeometry=eg;this.eyeBuffers=[bufferData(gl,gl.ARRAY_BUFFER,eg.positions),bufferData(gl,gl.ARRAY_BUFFER,eg.normals),bufferData(gl,gl.ARRAY_BUFFER,eg.components),bufferData(gl,gl.ARRAY_BUFFER,eg.uv)];this.eyeIndex=bufferData(gl,gl.ELEMENT_ARRAY_BUFFER,eg.indices);this.eyeVao=gl.createVertexArray();gl.bindVertexArray(this.eyeVao);gl.bindBuffer(gl.ARRAY_BUFFER,this.eyeBuffers[0]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.eyeBuffers[1]);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.eyeBuffers[2]);gl.enableVertexAttribArray(2);gl.vertexAttribIPointer(2,1,gl.UNSIGNED_BYTE,1,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.eyeBuffers[3]);gl.enableVertexAttribArray(3);gl.vertexAttribPointer(3,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.eyeIndex);gl.bindVertexArray(null);
  this.lineBuffer=bufferData(gl,gl.ARRAY_BUFFER,new Float32Array(4096*3),gl.DYNAMIC_DRAW);this.lineVao=gl.createVertexArray();gl.bindVertexArray(this.lineVao);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.bindVertexArray(null);this.uniformCache=new Map();this.preparePartPaths();
 }
 preparePartPaths(){this.partTips={};for(let i=0;i<this.h.partInfo.length/2;i++){const id=this.h.partInfo[i*2],t=this.h.partInfo[i*2+1];if(id&&(!this.partTips[id]||t>this.partTips[id].t))this.partTips[id]={i,t};}}
 u(p,name){let c=this.uniformCache.get(p);if(!c){c={};this.uniformCache.set(p,c);}if(!(name in c))c[name]=this.gl.getUniformLocation(p,name);return c[name];}
 resize(){const r=this.canvas.getBoundingClientRect();this.dpr=Math.min(devicePixelRatio||1,1.35);this.canvas.width=Math.max(1,Math.round(r.width*this.dpr));this.canvas.height=Math.max(1,Math.round(r.height*this.dpr));}
 applyMesh(program,m,animated){const gl=this.gl,r=this.h.metadata.continuum,u=n=>this.u(program,n);gl.useProgram(program);gl.uniformMatrix4fv(u('uMvp'),false,m.mvp);gl.uniformMatrix4fv(u('uView'),false,m.view);gl.uniform1i(u('uAnimate'),animated?1:0);gl.uniform2f(u('uBodyRange'),r.body.sourceXM,r.body.endXM);gl.uniform3fv(u('uJawPivot'),r.jaw.pivotM);gl.uniform1f(u('uJaw'),animated?this.h.state.jaw:0);gl.uniform1f(u('uGill'),animated?this.h.state.gill:0);gl.uniform1f(u('uEyeRecess'),r.eyes.socketRecessM);gl.uniform1i(u('uSamples'),r.body.samples);for(let i=0;i<7;i++)gl.uniform3fv(u('uPartBend['+i+']'),r.parts[i].bendDirection);const resp=animated?this.h.state.response:new Float32Array([0,0,0,0,1,0,0,0,0,0,0,0]);gl.uniform4fv(u('uResponse0'),resp.subarray(0,4));gl.uniform4fv(u('uResponse1'),resp.subarray(4,8));gl.uniform4fv(u('uResponse2'),resp.subarray(8,12));for(const [i,key,name] of [[0,'base','uBase'],[1,'normal','uNormal'],[2,'rm','uRm']]){const loc=u(name);if(loc!==null){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,this.textures[key]);gl.uniform1i(loc,i);}}gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,this.fieldTexture);gl.uniform1i(u('uField'),3);const mode=u('uMode');if(mode!==null)gl.uniform1i(mode,this.state.renderMode);const wc=u('uWeightChannel');if(wc!==null)gl.uniform1i(wc,this.state.weightChannel);const nm=u('uNormalMap');if(nm!==null)gl.uniform1i(nm,this.state.normalMap?1:0);}
 applyEye(m,frame){const gl=this.gl,u=n=>this.u(this.eyeProgram,n);gl.useProgram(this.eyeProgram);gl.uniformMatrix4fv(u('uMvp'),false,m.mvp);gl.uniformMatrix4fv(u('uView'),false,m.view);gl.uniform3fv(u('uCenter'),frame.center);gl.uniform3fv(u('uTangent'),frame.tangent);gl.uniform3fv(u('uUp'),frame.up);gl.uniform3fv(u('uOutward'),frame.outward);gl.uniform1f(u('uGazeYaw'),frame.gazeYaw);gl.uniform1f(u('uGazePitch'),frame.gazePitch);gl.uniform1f(u('uPupil'),frame.pupil);gl.uniform1f(u('uGlobeRadius'),frame.parameters.globeRadiusM);}
 path(m,points,color){if(!points.length)return;const gl=this.gl;gl.useProgram(this.lineProgram);gl.uniformMatrix4fv(this.u(this.lineProgram,'uMvp'),false,m.mvp);gl.uniform4fv(this.u(this.lineProgram,'uColor'),color);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,points);gl.bindVertexArray(this.lineVao);gl.drawArrays(gl.LINE_STRIP,0,points.length/3);}
 drawEyes(m,animated){if(!this.state.eyes)return;const gl=this.gl;gl.bindVertexArray(this.eyeVao);for(const side of [1,-1]){const frame=A.eyeFrame(this.h,side,animated);this.applyEye(m,frame);gl.disable(gl.BLEND);gl.depthMask(true);for(const c of [0,1,2,3]){const r=this.eyeGeometry.ranges[c];gl.drawElements(gl.TRIANGLES,r.count,gl.UNSIGNED_INT,r.offset*4);}const r=this.eyeGeometry.ranges[4];gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawElements(gl.TRIANGLES,r.count,gl.UNSIGNED_INT,r.offset*4);gl.depthMask(true);gl.disable(gl.BLEND);}gl.bindVertexArray(null);}
 drawPaths(m){const gl=this.gl;gl.disable(gl.DEPTH_TEST);this.path(m,this.h.state.worldCenters,[1,.68,.15,1]);const colors=[[.1,.9,1,1],[.75,.35,1,1],[1,.25,.5,1],[1,.55,.1,1],[.2,.9,.2,1],[.1,.55,1,1],[1,.9,.1,1]];for(const part of this.h.metadata.continuum.parts){const tip=this.partTips[part.id]?.i;if(tip==null)continue;const o=tip*3,root=this.h.partRoot.subarray(o,o+3),rest=this.h.positions.subarray(o,o+3),pts=[];for(let j=0;j<=36;j++){const q=j/36,p=[root[0]+q*(rest[0]-root[0]),root[1]+q*(rest[1]-root[1]),root[2]+q*(rest[2]-root[2])],w=new Uint8Array(12);w[part.id===1?5:part.id===2?6:part.id===3?7:part.id===4?8:part.id===5?9:part.id===6?10:11]=255;const bodyT=clamp((p[0]+.38)/.24),s=bodyT*bodyT*(3-2*bodyT);w[0]=Math.round(s*255);w[1]=255-w[0];const pi=new Uint16Array([part.id,Math.round(q*65535)]),pd=A.deformMaterial(this.h,p,[0,0,1],null,w,pi,root,true).position;pts.push(...pd);}this.path(m,new Float32Array(pts),colors[part.id-1]);}for(const side of [1,-1]){const f=A.eyeFrame(this.h,side,true),d=[Math.sin(f.gazeYaw),Math.sin(f.gazePitch),Math.cos(f.gazeYaw)*Math.cos(f.gazePitch)],world=[f.tangent[0]*d[0]+f.up[0]*d[1]+f.outward[0]*d[2],f.tangent[1]*d[0]+f.up[1]*d[1]+f.outward[1]*d[2],f.tangent[2]*d[0]+f.up[2]*d[1]+f.outward[2]*d[2]];this.path(m,new Float32Array([...f.center,f.center[0]+world[0]*.055,f.center[1]+world[1]*.055,f.center[2]+world[2]*.055]),[1,.75,.15,1]);}gl.enable(gl.DEPTH_TEST);}
 draw(x,y,w,h,animated){const gl=this.gl;gl.viewport(x,y,w,h);gl.scissor(x,y,w,h);gl.clearColor(.035,.055,.072,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const m=this.camera.mvp(w/h);this.applyMesh(this.program,m,animated);gl.bindVertexArray(this.vao);gl.drawElements(gl.TRIANGLES,this.h.indices.length,gl.UNSIGNED_INT,0);this.drawEyes(m,animated);if(this.state.wire){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.applyMesh(this.wireProgram,m,animated);gl.bindVertexArray(this.wireVao);gl.drawElements(gl.LINES,this.edgeCount,gl.UNSIGNED_INT,0);gl.disable(gl.BLEND);}if(this.state.paths&&animated)this.drawPaths(m);gl.bindVertexArray(null);}
 frame(now){const dt=this.last?Math.min(.08,(now-this.last)/1000):0;this.last=now;if(this.state.playing)A.update(this.h,dt,this.state);const gl=this.gl;gl.activeTexture(gl.TEXTURE3);gl.bindTexture(gl.TEXTURE_2D,this.fieldTexture);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,this.h.metadata.continuum.body.samples,9,gl.RGBA,gl.FLOAT,this.h.state.field);const w=this.canvas.width,h=this.canvas.height,compare=this.state.compare&&w/this.dpr>780;gl.enable(gl.SCISSOR_TEST);if(compare){const half=w>>1;this.draw(0,0,half,h,false);this.draw(half,0,w-half,h,true);}else this.draw(0,0,w,h,true);gl.disable(gl.SCISSOR_TEST);if(++this.frames%10===0){document.getElementById('fps').textContent=(dt?Math.round(1/dt):0)+' FPS';document.getElementById('clock').textContent=this.h.state.time.toFixed(2)+' s';document.getElementById('drive').textContent=this.h.state.drive.toFixed(3);updateResponseUI(this);}document.getElementById('teacherLabel').style.display=compare?'block':'none';document.getElementById('activeLabel').style.left=this.canvas.parentElement.classList.contains('reference-on')&&innerWidth>920?(compare?'calc(70% + 14px)':'calc(40% + 14px)'):(compare?'calc(50% + 14px)':'14px');this.raf=requestAnimationFrame(t=>this.frame(t));}
 dispose(){cancelAnimationFrame(this.raf);this.observer.disconnect();const gl=this.gl;for(const b of [...this.buffers,...this.eyeBuffers,this.index,this.edge,this.eyeIndex,this.lineBuffer])gl.deleteBuffer(b);for(const v of [this.vao,this.wireVao,this.eyeVao,this.lineVao])gl.deleteVertexArray(v);for(const p of [this.program,this.wireProgram,this.eyeProgram,this.lineProgram])gl.deleteProgram(p);for(const t of [...Object.values(this.textures),this.fieldTexture])gl.deleteTexture(t);A.dispose(this.h);}
}
function buildWeightUI(renderer){const host=document.getElementById('weightSliders');CHANNEL_LABELS.forEach((label,i)=>{if(i<5)return;const row=document.createElement('div');row.className='weight-row';row.innerHTML=`<label><span>${String(i+1).padStart(2,'0')} · ${label}</span><b id="wgVal${i}">1.00×</b></label><input id="wg${i}" type="range" min="0" max="1.8" step=".05" value="1"><div class="bar"><i id="resp${i}"></i></div>`;host.appendChild(row);row.querySelector('input').oninput=e=>{renderer.state.finGains[i-5]=+e.target.value;document.getElementById('wgVal'+i).textContent=(+e.target.value).toFixed(2)+'×';};});const sel=document.getElementById('weightChannel');CHANNEL_LABELS.forEach((x,i)=>{if(i<5)return;const o=document.createElement('option');o.value=i;o.textContent=String(i+1).padStart(2,'0')+' · '+x;sel.appendChild(o);});sel.value=5;sel.onchange=e=>renderer.state.weightChannel=+e.target.value;}
function updateResponseUI(renderer){const state=renderer.h.state,L=renderer.h.metadata.continuum.body.endXM-renderer.h.metadata.continuum.body.sourceXM;document.getElementById("gaitNow").textContent=`尾摆 ${state.beatFrequencyHz.toFixed(2)} Hz · 推进估计 ${(state.swimSpeedMps/L).toFixed(2)} 体长／秒`;const s=state.response;for(let i=0;i<12;i++){const bar=document.getElementById('resp'+i);if(bar){const v=clamp(s[i]/1.6);bar.style.width=(v*100)+'%';bar.title='当前动作响应 '+s[i].toFixed(3);}}document.getElementById('eyeNow').textContent=`眼球 yaw ${renderer.h.state.eyeYaw.toFixed(3)} · pitch ${renderer.h.state.eyePitch.toFixed(3)} · pupil ${renderer.h.state.pupil.toFixed(3)}`;}
function bindUi(renderer){
 const ref=document.getElementById('herringReference'),toggle=document.getElementById('showReference');ref.srcdoc=new TextDecoder().decode(fromB64('__HERRING_REF_HTML_BASE64__'));toggle.checked=innerWidth>920;renderer.canvas.parentElement.classList.toggle('reference-on',toggle.checked);toggle.onchange=()=>{renderer.canvas.parentElement.classList.toggle('reference-on',toggle.checked);renderer.resize();};const by=id=>document.getElementById(id),h=renderer.h;buildWeightUI(renderer);const modeHost=by('motions');for(const [id,p] of Object.entries(h.metadata.motion.modes)){const b=document.createElement('button');b.textContent=p.label;b.dataset.motion=id;b.classList.toggle('active',id===renderer.state.mode);modeHost.appendChild(b);b.onclick=()=>{renderer.state.mode=id;A.setMode(h,id,renderer.state);modeHost.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));by('modeNow').textContent=p.label;updateResponseUI(renderer);};}by('play').onclick=()=>{renderer.state.playing=!renderer.state.playing;by('play').textContent=renderer.state.playing?'暂停':'播放';};by('step').onclick=()=>{renderer.state.playing=false;by('play').textContent='播放';A.update(h,1/30,renderer.state);};by('resetTime').onclick=()=>A.reset(h,renderer.state.mode,renderer.state);
 for(const [id,key,out] of [['speed','speed','speedValue'],['amplitude','amplitude','amplitudeValue'],['eyeYaw','eyeYawOffset','eyeYawValue'],['eyePitch','eyePitchOffset','eyePitchValue'],['pupil','pupilBias','pupilValue']])by(id).oninput=e=>{renderer.state[key]=+e.target.value;by(out).textContent=(+e.target.value).toFixed(2);};for(const [id,key]of[['wire','wire'],['paths','paths'],['normalMap','normalMap'],['compare','compare'],['eyes','eyes']])by(id).onchange=e=>renderer.state[key]=e.target.checked;by('renderMode').onchange=e=>renderer.state.renderMode=+e.target.value;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{renderer.camera.target=[0,.14,0];renderer.camera.zoom=1;const v=b.dataset.view;if(v==='eyePos'){renderer.camera.setView('left');renderer.camera.target=[-.343,.159,.061];renderer.camera.zoom=11.5;}else if(v==='eyeNeg'){renderer.camera.setView('right');renderer.camera.target=[-.344,.159,-.059];renderer.camera.zoom=11.5;}else if(v==='eyes'){renderer.camera.setView('head');renderer.camera.target=[-.344,.159,0];renderer.camera.zoom=5.8;}else if(v==='jaw'){renderer.camera.setView('left');renderer.camera.target=[-.41,.124,0];renderer.camera.zoom=4.8;}else if(v==='finPos'){renderer.camera.setView('left');renderer.camera.target=[-.155,.124,.08];renderer.camera.zoom=5.5;renderer.camera.pitch=.35;}else if(v==='finNeg'){renderer.camera.setView('right');renderer.camera.target=[-.155,.124,-.08];renderer.camera.zoom=5.5;renderer.camera.pitch=.35;}else renderer.camera.setView(v);});
 by('eyeIsolate').onclick=()=>{renderer.state.renderMode=7;by('renderMode').value='7';renderer.camera.setView('left');renderer.camera.target=[-.343,.159,.061];renderer.camera.zoom=11.5;};by('eyeTrack').onclick=()=>{[...modeHost.children].find(x=>x.dataset.motion==='EYE_TRACK')?.click();renderer.camera.setView('left');renderer.camera.target=[-.343,.159,.061];renderer.camera.zoom=11.5;};by('resetWeights').onclick=()=>{renderer.state.finGains.fill(1);for(let i=5;i<12;i++){by('wg'+i).value='1';by('wgVal'+i).textContent='1.00×';}};
 by('export').onclick=()=>{const state={version:'R08',mode:renderer.state.mode,time:h.state.time,finGains:renderer.state.finGains,eye:{yawOffset:renderer.state.eyeYawOffset,pitchOffset:renderer.state.eyePitchOffset,pupilBias:renderer.state.pupilBias},note:'Central spine full-section transport; only seven fin response gains; separate measured-position eyes; visual approval remains false.'},url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='R08-weight-eye-test-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};window.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|SELECT/.test(e.target.tagName)){e.preventDefault();by('play').click();}});window.addEventListener('pagehide',()=>renderer.dispose(),{once:true});}
async function boot(){try{setLoad('读取 KFC8 中心脊椎与 7 组鱼鳍',.03);const h=await A.build(fromB64(KFS8_SCORE_B64),p=>setLoad('重演完整表面 '+Math.round(p*100)+'%',.08+.56*p));setLoad('解码原始 4K 表面图与独立眼球',.7);const canvas=document.getElementById('gl'),gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});if(!gl)throw Error('此浏览器未提供 WebGL2。请开启图形加速。');const textures={base:await texture(gl,h.textures.base,'image/jpeg'),normal:await texture(gl,h.textures.normal,'image/png'),rm:await texture(gl,h.textures.rm,'image/jpeg')};const renderer=new Renderer(canvas,h,gl,textures);bindUi(renderer);document.body.classList.toggle('player',!WORKBENCH_MODE);byReady(h);window.__KAOPU_R08__={ready:true,renderer,handle:h,instrument:A,shaders:{meshVertex:MESH_VERTEX,meshFragment:MESH_FRAGMENT,eyeVertex:EYE_VERTEX,eyeFragment:EYE_FRAGMENT}};document.getElementById('loader').classList.add('done');requestAnimationFrame(t=>renderer.frame(t));}catch(e){console.error(e);setLoad('启动失败：'+e.message,1);document.getElementById('loader').classList.add('failed');window.__KAOPU_R08__={ready:false,error:String(e.stack||e)};}}
function byReady(h){document.getElementById('stats').textContent=h.metadata.counts.vertices.toLocaleString()+' 点 · '+h.metadata.counts.triangles.toLocaleString()+' 三角 · 7 组鱼鳍权重';document.getElementById('version').textContent='R08 · KFC8 · posterior wave + coupled tail + KFE1 eye';document.getElementById('eyeEvidence').textContent=`+Z 眼 ${h.metadata.continuum.eyes.eyes[0].sourceEyeSamples.toLocaleString()} 源样本 · −Z 眼 ${h.metadata.continuum.eyes.eyes[1].sourceEyeSamples.toLocaleString()} 源样本`;}
boot();
