import * as THREE from '../vendor/three.module.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {paperSVG,names,colors} from './paper-view.mjs';
import {fingerprint,validate} from './core.mjs';
import {regionalStrain} from './diagnostics.mjs';
import {decodeSDF} from './sdf-transport.mjs';
const $=id=>document.getElementById(id),fmt=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—';
let base,body,measurements,baseline,audit,currentSpec,currentPositions,currentRecord,currentRegions,currentIntersections,worker,ready=false,dirty=false,activeRun=false,paused=false,mode='loading',bodyGeometry,clothMeshes=[],currentSummary,hotspot=null;
let renderDirty=true;const garment=new THREE.Group(),landmarks=new THREE.Group();
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.add(garment,landmarks);scene.add(new THREE.HemisphereLight(0xcfe5f2,0x625443,2));const key=new THREE.DirectionalLight(0xffefd4,2.6);key.position.set(-2,3,4);scene.add(key);const rim=new THREE.DirectionalLight(0xabcde2,1.6);rim.position.set(2,1,-3);scene.add(rim);
const camera=new THREE.PerspectiveCamera(34,1,.01,20),orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.31,0);orbit.enableDamping=true;orbit.addEventListener('change',()=>renderDirty=true);orbit.minDistance=.5;orbit.maxDistance=4;camera.position.set(.65,1.37,1.82);
const grid=new THREE.GridHelper(4,40,0x354851,0x29383f);grid.position.y=-.005;scene.add(grid);
new ResizeObserver(()=>{const b=$('canvas-wrap').getBoundingClientRect();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();renderDirty=true;}).observe($('canvas-wrap'));
(function render(){requestAnimationFrame(render);orbit.update();if(renderDirty){renderer.render(scene,camera);renderDirty=false;}})();
function error(message){$('status').textContent=message;$('status').classList.add('error');activeRun=false;$('pause').disabled=true;document.documentElement.dataset.error=message;}
function status(message){$('status').classList.remove('error');$('status').textContent=message;}
function controls(){return{bodyLengthDeltaMm:+$('length').value,hemEaseMm:+$('hem').value};}
function clearGarment(){renderDirty=true;for(const m of clothMeshes){m.geometry.dispose();m.material.dispose();garment.remove(m);}clothMeshes=[];}
function setGeometry(spec,positions){clearGarment();currentSpec=spec;currentPositions=positions;let offset=0;
 for(const p of spec.panels){const g=new THREE.BufferGeometry(),points=positions.slice(offset,offset+p.uvMm.length).flatMap(v=>v.map(x=>x/1000));g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));g.setIndex(p.triangles.flat());g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:colors[p.id],roughness:.87,metalness:0,side:THREE.DoubleSide,flatShading:false}));m.userData={panel:p,offset};garment.add(m);clothMeshes.push(m);offset+=p.uvMm.length;}
 updateDisplay();renderPaper();}
function setPositions(positions){renderDirty=true;currentPositions=positions;for(const m of clothMeshes){const a=m.geometry.attributes.position.array,{panel,offset}=m.userData;for(let i=0;i<panel.uvMm.length;i++)for(let k=0;k<3;k++)a[i*3+k]=positions[offset+i][k]/1000;m.geometry.attributes.position.needsUpdate=true;m.geometry.computeVertexNormals();m.geometry.computeBoundingSphere();}if($('display').value==='strain')updateDisplay();}
function updateDisplay(){renderDirty=true;let ti=0;const heat=$('display').value==='strain',wire=$('display').value==='wire';if(heat&&currentSpec&&currentPositions)currentRegions=regionalStrain(currentSpec,currentPositions);for(const m of clothMeshes){const{panel}=m.userData;m.material.wireframe=wire;m.material.vertexColors=heat;m.material.color.set(heat?'#ffffff':colors[panel.id]);if(heat){const sums=new Float32Array(panel.uvMm.length),counts=new Float32Array(panel.uvMm.length);for(const t of panel.triangles){const s=currentRegions.perTriangle[ti++];for(const i of t){sums[i]+=s;counts[i]++;}}const a=[];for(let i=0;i<sums.length;i++){const s=sums[i]/Math.max(1,counts[i]),color=new THREE.Color().setHSL(.48*(1-Math.min(1,s/.2)),.75,.48);a.push(color.r,color.g,color.b);}m.geometry.setAttribute('color',new THREE.Float32BufferAttribute(a,3));}m.material.needsUpdate=true;}}
function renderPaper(){if(!currentSpec)return;$('paper').innerHTML=paperSVG(currentSpec,{selectedSeamId:$('seam-select').value,hotspot});seamDetail();}
function seamDetail(){if(!currentSpec)return;const s=currentSpec.seams.find(s=>s.id===$('seam-select').value);if(!s)return;const len=e=>{const p=currentSpec.panels.find(p=>p.id===e.panelId),ids=p.edges[e.edge];return ids.slice(1).reduce((n,id,j)=>n+Math.hypot(...p.uvMm[id].map((x,k)=>x-p.uvMm[ids[j]][k])),0);};$('seam-detail').textContent=`缝组 ${s.sourceStitchIndex} · ${names[s.a.panelId]} ${s.a.edge} → ${names[s.b.panelId]} ${s.b.edge}（反向配对） · A ${fmt(len(s.a))} mm / B ${fmt(len(s.b))} mm · B−A ${fmt(s.easeMm,2)} mm · ${s.a.panelId===s.b.panelId?'省道':Math.abs(s.easeMm)/len(s.a)>=.02?'预设吃势':'普通缝边'}`;}
function setupPaperOptions(){const selected=$('seam-select').value;$('seam-select').replaceChildren(...currentSpec.seams.map(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=`${s.sourceStitchIndex} · ${names[s.a.panelId]} ${s.a.edge} / ${names[s.b.panelId]} ${s.b.edge}`;return o;}));if(currentSpec.seams.some(s=>s.id===selected))$('seam-select').value=selected;renderPaper();}
function setMetrics(m,intersections=null){$('metrics').innerHTML=`<div><strong>${fmt(m.activeMaxGapMm,2)}<small> mm</small></strong><span>已缝边最大间隙</span></div><div><strong>${fmt(m.bodySignedDistanceMinMm,2)}<small> mm</small></strong><span>顶点最小人体间距 · SDF</span></div><div><strong>${m.temporarySupportCount??m.pins}</strong><span>剩余工装支撑</span></div><div><strong>${intersections?intersections.bodyIntersectingFaceCount+' / '+intersections.selfStrictTriangleIntersectionCount:'待检'}</strong><span>人体面穿插 / 严格自交</span></div>`;}
function showRegions(regions){const r=regions;if(!r){$('regional').textContent='完成求解后报告；修改尺寸会清除旧报告';return;}const labels={ordinary_interior:'普通内部',ordinary_seam_band:'普通缝口',free_edge_band:'自由边带',planned_ease_band:'吃势缝口',dart_band:'省道附近'};$('regional').innerHTML='<div class="region-head"><span>原 UV 区域</span><span>最大</span><span>面积 P95</span><span>超 5% 面积</span></div>'+Object.entries(r.regions).map(([k,v])=>`<div class="region-row"><button data-hot="${k}" ${v?'':'disabled'} title="在纸样上定位本区最大应变">${labels[k]}</button><span>${fmt(v?.maximumPercent)}%</span><span>${fmt(v?.p95AreaWeightedPercent)}%</span><span>${fmt(v?.areaOver5Percent)}%</span></div>`).join('')+'<div class="region-row"><span>缝份层</span><span>未建模</span><span>—</span><span>—</span></div>';for(const b of $('regional').querySelectorAll('button'))b.onclick=()=>{hotspot=r.regions[b.dataset.hot].worst[0];renderPaper();$('seam-detail').textContent=`热点 ${names[hotspot.panelId]} · 三角形 ${hotspot.triangle} · 原纸样 (${hotspot.uvCentroidMm.map(x=>fmt(x)).join(', ')}) mm · 主应变 ${fmt(hotspot.strain*100)}%`;$('paper').scrollIntoView({behavior:'smooth',block:'center'});};}
function setStage(completed,current){for(const li of $('stages').children){const id=li.dataset.stage;li.classList.toggle('done',completed.includes(id));li.classList.toggle('current',id===current);}}
function displayMeasurementLines(){const makeLine=(points,color)=>{const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p.map(x=>x/1000)))),m=new THREE.Line(g,new THREE.LineBasicMaterial({color,depthTest:false,transparent:true,opacity:.9}));m.renderOrder=3;landmarks.add(m);};const m=measurements,bust=m.bust.tapeHullWorldMm;makeLine([...bust,bust[0]],'#8fd6d5');for(let j=0;j<2;j++){const a=m.landmarks.shoulderCaps[j].positionMm,b=m.landmarks.backUnderarmBottoms[j].positionMm,n=m.teacher.neckSideLandmarks[j].positionMm;makeLine([a,b],'#ec9dbb');makeLine([n,a],'#a5d788');}makeLine(m.surfacePaths.backWaistLine.pointsMm,'#e6b47c');for(const p of [m.landmarks.nape,...m.landmarks.shoulderCaps,...m.landmarks.backUnderarmBottoms,...m.teacher.neckSideLandmarks]){const dot=new THREE.Mesh(new THREE.SphereGeometry(.0035,8,6),new THREE.MeshBasicMaterial({color:0xf0c791,depthTest:false}));dot.position.set(...p.positionMm.map(x=>x/1000));dot.renderOrder=4;landmarks.add(dot);}landmarks.visible=$('measurements-visible').checked;}
function showMeasurements(){const m=measurements,t=m.teacher.body;const rows=[['胸围软尺外包络',`${fmt(m.bust.tapeCircumferenceMm)} mm`,`Y=${fmt(m.bust.heightMm)} mm；前 ${fmt(m.bust.frontArcMm)} / 后 ${fmt(m.bust.backArcMm)} mm`],['肩宽',`${fmt(t.shoulder_w*10)} mm`,'左右肩点三维直线距离；源皮肤位置可见'],['袖窿深度',`${fmt(t.armscye_depth*10)} mm`,'肩点到后腋下点的三维直线距离；不是表面路径'],['肩斜',`${fmt(t.shoulder_incl,2)}°`,'颈侧到肩点相对水平面的倾角'],['后背腰节',`${fmt(t.waist_line*10)} mm`,'颈后点至腰线的皮肤网格路径近似'],['材料模型','200 g/m²','数字坯布：各向同性，未实测标定；伸长柔度1e−7，弯曲距离柔度20，单位见导出数据'],['人体高度',`${fmt(t.height*10)} mm`,'固定 Anny 成人合成参数；不是用户真人扫描']];$('measurements').innerHTML=rows.map(([label,value,note])=>`<div class="reading"><div>${label}<small>${note}</small></div><strong>${value}</strong></div>`).join('');}
function paperTotals(summary){currentSummary=summary;$('paper-totals').innerHTML=`${summary.panels} 片 · ${summary.seams} 组缝边 · 4 个开口<br>下摆净长 ${fmt(summary.hemCircumferenceMm)} mm · 净材料 ${fmt(summary.netMaterialAreaMm2/1e6,3)} m²<br>${summary.particleCount} 材料点 · ${summary.triangleCount} 三角形`;}
function invalidate(){if(mode==='loading')return;dirty=true;activeRun=false;paused=false;worker?.postMessage({type:'pause'});clearGarment();currentRecord=null;currentRegions=null;currentIntersections=null;hotspot=null;showRegions(null);$('metrics').textContent='纸样参数已更改，旧成衣与旧检查结果已清除';$('run').disabled=true;$('pause').disabled=true;$('save-state').disabled=true;$('svg').disabled=true;$('view-label').textContent='尺寸已修改 · 等待重新裁片';$('view-subtitle').textContent='不会变形或重用上一件三维成衣';status('先生成新纸样，再开始缝合');$('progress-bar').style.width='0%';setStage([],null);document.documentElement.dataset.state='dirty';}
function requestCut(){if(!ready)return;delete document.documentElement.dataset.error;activeRun=false;paused=false;dirty=true;currentRecord=null;$('run').disabled=true;$('cut').disabled=true;$('length').disabled=true;$('hem').disabled=true;status('正在更新二维纸样并重新三角化…');worker.postMessage({type:'cut',controls:controls()});}
function onWorker({data:d}){if(d.type==='ready'){ready=true;$('cut').disabled=false;return;}if(d.type==='error'){error(d.message);$('cut').disabled=false;$('length').disabled=$('hem').disabled=false;return;}if(d.type==='cut'){dirty=false;mode='cut';currentRecord=null;currentRegions=null;currentIntersections=null;setGeometry(d.spec,d.positionsMm);setupPaperOptions();paperTotals(d.summary);setMetrics(d.metrics);showRegions(null);$('run').disabled=false;$('run').textContent='从裁片开始缝合';$('cut').disabled=false;$('length').disabled=$('hem').disabled=false;$('save-state').disabled=true;$('svg').disabled=false;$('view-label').textContent='本机新裁片 · 尚未缝合';$('view-subtitle').textContent='真实二维材料点与网格，原休止长度已锁定';$('result-notice').textContent=`拓扑预检：缝合后 ${d.topology.boundaryLoops} 个边界环（领口、下摆和两袖口），非流形边 ${d.topology.nonManifoldEdges}。这不是穿体检查结果。`;status('新纸样已裁好，可以开始缝合');setStage(['cut'],null);document.documentElement.dataset.state='cut';return;}
 if(d.type==='paused'){if(paused)status('已暂停；恢复后继续当前真实求解');return;}if(dirty)return;if(!activeRun&&!(d.type==='done'&&currentSpec&&d.record.snapshot.signature===fingerprint(currentSpec)))return;
 if(d.type==='progress'||d.type==='stage'||d.type==='auditing'){setPositions(d.positionsMm);setMetrics(d.metrics);const stageIds=[...base.source.assemblyExperiment,'release'],index=stageIds.indexOf(d.stage),done=['cut',...stageIds.slice(0,index)];if(d.completedStage)done.push(d.completedStage);setStage(done,d.stage);$('progress-bar').style.width=fmt(Math.min(100,d.frame/(base.source.assemblyExperiment.length*360+480)*100))+'%';status(d.type==='auditing'?'模拟结束，正在独立检查三角面交叉…':`正在${{centers:'缝前后衣身中线',sleeve_tubes:'合左右袖筒',shoulders:'合肩缝',armholes:'装配袖窿',sides:'合左右侧缝',release:'释放工装并观察重力'}[d.stage]||'求解'} · ${fmt(d.frame/60)} / ${fmt(base.source.assemblyExperiment.length*6+8)} 模拟秒`);return;}
 if(d.type==='done'){activeRun=false;mode='live-done';currentRecord=d.record;currentRegions=d.regions;currentIntersections=d.intersections;setPositions(d.record.positionsMm);setMetrics(d.record.metrics,d.intersections);showRegions(d.regions);$('pause').disabled=true;$('run').disabled=true;$('save-state').disabled=false;setStage(['cut',...base.source.assemblyExperiment,'release'],null);$('progress-bar').style.width='100%';$('view-label').textContent='本机求解完成 · 请检查各视角';$('view-subtitle').textContent='这件网格由本轮纸样实时重建，不是预计算替换';const bad=d.intersections.bodyIntersectingFaceCount+d.intersections.selfStrictTriangleIntersectionCount+d.record.metrics.bodyInsideVertexCount;status(bad?'本轮存在穿插，结果仅作诊断':'本轮严格交叉检查完成；区域应变见下方');$('result-notice').textContent=`普通材料面积 P95 应变 ${fmt(d.regions.ordinaryMaterial.p95AreaWeightedPercent)}%，局部最大 ${fmt(d.regions.all.maximumPercent)}%。${bad?'检测到交叉，不作为成衣验收。':'严格三角交叉为 0；共面重叠、连续碰撞和真实缝份尚未验证。'}`;document.documentElement.dataset.state='complete';window.__TAILOR_QA__.completed=structuredClone({metrics:d.record.metrics,intersections:d.intersections,regions:d.regions,controls:controls()});}
}
function showBaseline(){activeRun=false;dirty=false;paused=false;worker?.postMessage({type:'pause'});$('length').value=0;$('hem').value=0;$('length-value').textContent='0 mm';$('hem-value').textContent='0 mm';currentRecord=baseline;currentRegions=audit.regions;currentIntersections=audit.intersections;mode='baseline';setGeometry(baseline.snapshot.spec,baseline.positionsMm);setupPaperOptions();paperTotals(audit.paperSummary);setMetrics(baseline.metrics,audit.intersections);showRegions(audit.regions);$('view-label').textContent='自有引擎 · 已求解基准样例';$('view-subtitle').textContent='读取经过检查的原始求解记录；本机重算请先重新裁片';$('run').disabled=true;$('pause').disabled=true;$('save-state').disabled=false;$('svg').disabled=false;$('progress-bar').style.width='100%';setStage(['cut',...base.source.assemblyExperiment,'release'],null);status('自有基准记录已载入。改尺寸后重新裁片，或使用原尺寸重算');$('result-notice').textContent=`基准人体交叉 ${audit.intersections.bodyIntersectingFaceCount}、严格自交 ${audit.intersections.selfStrictTriangleIntersectionCount}；普通材料面积 P95 应变 ${fmt(audit.regions.ordinaryMaterial.p95AreaWeightedPercent)}%，局部最大 ${fmt(audit.regions.all.maximumPercent)}%。共面重叠与真实缝份未验证，局部热点待改进。`;document.documentElement.dataset.state='baseline';}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('length').oninput=()=>{$('length-value').textContent=$('length').value+' mm';invalidate();};$('hem').oninput=()=>{$('hem-value').textContent=$('hem').value+' mm';invalidate();};$('cut').onclick=requestCut;
$('run').onclick=()=>{activeRun=true;dirty=false;paused=false;mode='running';$('run').disabled=true;$('pause').disabled=false;$('view-label').textContent='本机 XPBD 求解中';$('view-subtitle').textContent='每一帧从材料约束与人体接触算出';worker.postMessage({type:'run'});document.documentElement.dataset.state='running';};
$('pause').onclick=()=>{paused=true;activeRun=false;$('run').disabled=false;$('run').textContent='继续当前求解';$('pause').disabled=true;worker.postMessage({type:'pause'});};$('baseline').onclick=showBaseline;$('display').onchange=updateDisplay;$('seam-select').onchange=()=>{hotspot=null;renderPaper();};$('measurements-visible').onchange=()=>{landmarks.visible=$('measurements-visible').checked;renderDirty=true;};
for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>{const kind=b.dataset.camera;orbit.target.set(0,kind==='full'?.95:1.31,0);camera.position.set(...({front:[0,1.36,1.92],back:[0,1.36,-1.92],angle:[.90,1.40,1.78],full:[1.1,1.2,3.55]}[kind]));orbit.update();};
$('save').onclick=()=>download('kaopu-basic-top-recipe.json',{schema:'kaopu-basic-top-recipe@1',sourcePaperFingerprint:fingerprint(base),bodyId:body.id,bodyModelSha256:body.source.modelFileSha256,controls:controls(),solver:{program:'garment-small-step-r1',substeps:12,iterations:6,stages:base.source.assemblyExperiment,stageFrames:360,releaseFrames:480,originalUVPreserved:true},note:'Load rebuilds flat pattern. No solved mesh is substituted.'});
$('load').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>64000)throw Error('配方文件过大');const r=JSON.parse(await file.text());if(r.schema!=='kaopu-basic-top-recipe@1'||r.sourcePaperFingerprint!==fingerprint(base)||r.bodyId!==body.id||r.bodyModelSha256!==body.source.modelFileSha256)throw Error('配方底版或人体版本不匹配');const{bodyLengthDeltaMm,hemEaseMm}=r.controls||{};if(!Number.isFinite(bodyLengthDeltaMm)||bodyLengthDeltaMm< -50||bodyLengthDeltaMm>80||!Number.isFinite(hemEaseMm)||hemEaseMm<0||hemEaseMm>120)throw Error('配方尺寸超出本例范围');$('length').value=bodyLengthDeltaMm;$('hem').value=hemEaseMm;$('length-value').textContent=bodyLengthDeltaMm+' mm';$('hem-value').textContent=hemEaseMm+' mm';invalidate();requestCut();}catch(e){error(e.message);}finally{$('load').value='';}};
$('save-state').onclick=()=>{if(currentRecord)download('kaopu-basic-top-state.json',{...currentRecord,displaySource:mode,independentIntersections:currentIntersections,regionalStrain:currentRegions});};$('svg').onclick=()=>{if(!dirty&&currentSpec)download('kaopu-basic-top-net-pattern-mm.svg',paperSVG(currentSpec,{download:true}),'image/svg+xml');};
window.__TAILOR_QA__={renderCount:()=>renderer.info.render.frame,getState:()=>({ready,dirty,mode,controls:controls(),panelCount:currentSpec?.panels.length,particleCount:currentPositions?.length,garmentMeshCount:clothMeshes.length,bodyVertexCount:body?.positionsMm.length,specFingerprint:currentSpec&&fingerprint(currentSpec)}),cut:requestCut,getSpec:()=>currentSpec,getPositions:()=>currentPositions};
try{[base,body,measurements,baseline,audit]=await Promise.all(['teacher-paper-base.json','body-anny-adult.json','measurements.json','verified-own-solve.json','baseline-audit.json'].map(name=>fetch('./assets/'+name).then(r=>{if(!r.ok)throw Error(name+' 加载失败');return r.json();})));validate(baseline.snapshot.spec);if(baseline.snapshot.signature!==fingerprint(baseline.snapshot.spec))throw Error('基准纸样校验失败');bodyGeometry=new THREE.BufferGeometry();bodyGeometry.setAttribute('position',new THREE.Float32BufferAttribute(body.positionsMm.flatMap(p=>p.map(x=>x/1000)),3));bodyGeometry.setIndex(body.triangles.flat());bodyGeometry.computeVertexNormals();scene.add(new THREE.Mesh(bodyGeometry,new THREE.MeshStandardMaterial({color:'#64858a',roughness:.83,metalness:.05})));displayMeasurementLines();showMeasurements();showBaseline();const meta=await fetch('./assets/body-sdf-grid.json').then(r=>r.json()),blob=await fetch('./assets/'+meta.transport.file).then(r=>r.blob()),buffer=await decodeSDF(blob,meta);worker=new Worker(new URL('./worker.bundle.mjs',import.meta.url),{type:'module'});worker.onmessage=onWorker;worker.onerror=e=>error('计算线程失败：'+e.message);worker.postMessage({type:'init',base,body,sdfMeta:meta,sdfBuffer:buffer},[buffer]);}catch(e){error(e.message);console.error(e);}
