const config={morph:'table',nutrient:1,current:.72,density:1,roughness:.68,age:1,debug:false};
let rebuildTimer=0;
function rebuild(){clearTimeout(rebuildTimer);rebuildTimer=setTimeout(()=>{habitat=new CoralHabitatObject(config.morph,config);upload(staticGpu,habitat.mesh.data);resetLine();resetFishTargets();qa.morphology=config.morph;qa.objectId=habitat.objectId;qa.triangleCount=habitat.mesh.triangles;qa.collisionProbeCount=habitat.collisionProbes.length;qa.hideNodeCount=habitat.hideNodes.length;qa.renderSource=habitat.objectId;qa.fishHideSource=habitat.objectId;qa.lineQuerySource=habitat.objectId;qa.sharedObjectIdentity=qa.renderSource===qa.fishHideSource&&qa.fishHideSource===qa.lineQuerySource;updateUiIdentity();setEvent(`已由 ${habitat.kernel} 重建 ${morphNames[config.morph]}；不是导入参考模型。`)},35)}
function updateUiIdentity(){$('objectId').textContent=habitat.objectId;$('morphName').textContent=morphNames[habitat.type];$('tRender').textContent='same field';$('tFish').textContent='same field';$('tLine').textContent='same field';$('tKernel').textContent=habitat.kernel;$('tNodes').textContent=habitat.nodes.length;$('tEdges').textContent=habitat.edges.length;$('tHide').textContent=habitat.hideNodes.length;$('tProbe').textContent=habitat.collisionProbes.length;$('tTri').textContent=habitat.mesh.triangles.toLocaleString();$('identityPass').textContent=qa.sharedObjectIdentity?'PASS · one authoritative field':'FAIL'}

const fish=[];
const fishColors=[palette.fish1,palette.fish2,palette.fish3,c4('#d46a54'),c4('#7fc5a0')];
for(let i=0;i<12;i++)fish.push({id:`reef-fish-${String(i+1).padStart(2,'0')}`,phase:i/12*TAU,speed:.30+.025*(i%4),radius:4.2+(i%5)*.52,height:1.15+(i%4)*.42,pos:[0,0,0],prev:[0,0,0],mode:'roam',hideNode:null,color:fishColors[i%fishColors.length],scale:.34+.04*(i%3),source:null});
function resetFishTargets(){fish.forEach(f=>{f.mode='roam';f.hideNode=null;f.source=habitat?.objectId||null})}
function sendFishHome(){fish.forEach((f,i)=>{f.mode='hide';f.hideNode=habitat.nearestHide(f.pos,i);f.source=habitat.objectId});$('tFishState').textContent='seeking shared hide nodes';setEvent(`鱼群开始读取 ${habitat.objectId} 的 hideNodes；没有另造“视觉之外”的藏点。`)}
function roamFish(){resetFishTargets();$('tFishState').textContent='roaming';setEvent('鱼群恢复巡游；珊瑚对象仍保留统一的躲藏节点。')}
function updateFish(dt,time){let hidden=0;for(let i=0;i<fish.length;i++){const f=fish[i];f.prev=[...f.pos];if(f.mode==='roam'){f.phase+=dt*f.speed;const wob=.4*Math.sin(time*.72+i),target=[Math.cos(f.phase)*f.radius,f.height+wob,Math.sin(f.phase)*f.radius*.76];const k=1-Math.exp(-dt*3.2);f.pos=lerp3(f.pos,target,k)}else if(f.hideNode){const offset=[.08*Math.sin(time*1.8+i),.05*Math.sin(time*2.1+i*.7),.08*Math.cos(time*1.5+i)],target=add(f.hideNode.p,offset),k=1-Math.exp(-dt*1.55);f.pos=lerp3(f.pos,target,k);if(len(sub(f.pos,target))<.22)hidden++}}if(fish.some(f=>f.mode==='hide'))$('tFishState').textContent=`${hidden}/${fish.length} at shared nodes`}
function fishBasis(dir){const z=norm([dir[0],0,dir[2]]),x=norm(cross([0,1,0],z)),y=[0,1,0];return[x,y,z]}
function addFishMesh(m,f,time){let d=sub(f.pos,f.prev);if(len(d)<1e-4)d=[Math.sin(f.phase),0,Math.cos(f.phase)];const B=fishBasis(d),s=f.scale,bodyCenter=f.pos;addSphere(m,bodyCenter,[s*.72,s*.32,s*1.35],f.color,5,8,(th,ph)=>1+.04*Math.sin(ph*3+time*3+iSafe(f.id)),null,B);const back=add(bodyCenter,mul(B[2],-s*1.25)),tip=add(back,mul(B[2],-s*.72)),u=mul(B[0],s*.62),v=mul(B[1],s*.42),tc=cmix(f.color,palette.groove,.3);m.tri(add(back,u),tip,sub(back,u),tc,tc,tc);m.tri(add(back,v),tip,sub(back,v),tc,tc,tc);const finBase=add(bodyCenter,mul(B[2],-.08)),finL=add(finBase,mul(B[0],s*.66)),finR=add(finBase,mul(B[0],-s*.66)),finTip=add(add(finBase,mul(B[1],-.10)),mul(B[2],-.44*s));m.tri(finBase,finL,finTip,cmix(f.color,palette.tip,.28));m.tri(finBase,finTip,finR,cmix(f.color,palette.tip,.28))}
function iSafe(id){return Number(id.slice(-2))||0}

const lineState={active:false,casting:false,contact:false,progress:0,anchor:[-6.3,5.6,7.8],target:[2,1,-2],lure:[-6.3,5.6,7.8],contactPoint:null,source:null,tension:0,customTarget:null};
function resetLine(){lineState.active=false;lineState.casting=false;lineState.contact=false;lineState.progress=0;lineState.lure=[...lineState.anchor];lineState.contactPoint=null;lineState.source=habitat?.objectId||null;lineState.tension=0;qa.lineContact=false;$('tLineState').textContent='idle'}
function castLine(){if(!habitat)return;let targetProbe=habitat.collisionProbes.slice().sort((a,b)=>b.c[1]-a.c[1])[Math.floor(habitat.collisionProbes.length*.22)]||habitat.collisionProbes[0],target=lineState.customTarget||targetProbe.c,dir=norm(sub(target,lineState.anchor));lineState.target=add(target,mul(dir,4.2));lineState.progress=0;lineState.active=true;lineState.casting=true;lineState.contact=false;lineState.contactPoint=null;lineState.source=habitat.objectId;lineState.tension=0;$('tLineState').textContent='casting';setEvent(`抛线查询已绑定 ${habitat.objectId}；沿线逐步检查它的碰撞代理。`)}
function releaseLine(){resetLine();setEvent('钓线已释放。')}
function updateLine(dt,time){if(!lineState.active)return;if(lineState.casting&&!lineState.contact){lineState.progress=clamp(lineState.progress+dt*1.35,0,1);const e=1-Math.pow(1-lineState.progress,3),next=lerp3(lineState.anchor,lineState.target,e),hit=habitat.segmentHit(lineState.anchor,next);if(hit){lineState.contact=true;lineState.casting=false;lineState.contactPoint=hit.point;lineState.lure=hit.point;lineState.tension=2.8;qa.lineContact=true;$('tLineState').textContent='CONTACT · shared object';setEvent(`钓线接触 ${hit.objectId}（${hit.probe.role}）；接触点来自同一 Coral Habitat Object。`)}else{lineState.lure=next;if(lineState.progress>=1){lineState.casting=false;$('tLineState').textContent='clear · no contact'}}}else if(lineState.contact){lineState.tension=3.1+.9*Math.sin(time*2.4);$('tLineState').textContent=`contact · ${lineState.tension.toFixed(1)} N`}}
function segmentTargetFromPointer(clientX,clientY){const rect=canvas.getBoundingClientRect(),x=(clientX-rect.left)/rect.width*2-1,y=1-(clientY-rect.top)/rect.height*2,tan=Math.tan(camera.fov/2),dir=norm(add(add(camera.forward,mul(camera.right,x*tan*camera.aspect)),mul(camera.up,y*tan))),den=dir[1];if(Math.abs(den)<1e-5)return null;const t=(.65-camera.eye[1])/den;if(t<=0)return null;return add(camera.eye,mul(dir,t))}

function addDebug(m){if(!config.debug||!habitat)return;for(const p of habitat.collisionProbes)addSphere(m,p.c,[p.r*.15,p.r*.15,p.r*.15],[.27,.95,.91,.55],4,6);for(const h of habitat.hideNodes)addSphere(m,h.p,[.12,.12,.12],[1,.45,.75,.8],5,7)}
function addLineMesh(m){if(!lineState.active)return;const col=lineState.contact?[1,.69,.35,.96]:[.88,.94,.86,.88];addCylinder(m,lineState.anchor,lineState.lure,.025,.017,col,col,6,false);addSphere(m,lineState.lure,[.09,.09,.09],lineState.contact?[1,.38,.16,1]:[.95,.89,.67,1],6,8);if(lineState.contactPoint)addSphere(m,lineState.contactPoint,[.17,.17,.17],[1,.28,.10,.72],7,9)}

const camera={target:[0,1.45,0],yaw:.78,pitch:.28,distance:16.8,fov:50*PI/180,aspect:1,eye:[0,0,0],forward:[0,0,-1],right:[1,0,0],up:[0,1,0],view:null,proj:null};
function updateCamera(){camera.aspect=canvas.width/canvas.height;const cp=Math.cos(camera.pitch);camera.eye=[camera.target[0]+camera.distance*cp*Math.sin(camera.yaw),camera.target[1]+camera.distance*Math.sin(camera.pitch),camera.target[2]+camera.distance*cp*Math.cos(camera.yaw)];camera.forward=norm(sub(camera.target,camera.eye));camera.right=norm(cross(camera.forward,[0,1,0]));camera.up=norm(cross(camera.right,camera.forward));camera.view=mat4LookAt(camera.eye,camera.target,[0,1,0]);camera.proj=mat4Perspective(camera.fov,camera.aspect,.1,120)}
function setView(name){if(name==='close')Object.assign(camera,{target:[0,1.45,0],yaw:.70,pitch:.18,distance:10.8,fov:48*PI/180});if(name==='habitat')Object.assign(camera,{target:[0,1.45,0],yaw:.78,pitch:.25,distance:13.4,fov:49*PI/180});if(name==='top')Object.assign(camera,{target:[0,.8,0],yaw:.12,pitch:1.34,distance:18.5,fov:48*PI/180})}
const pointers=new Map();let pinch=0,moved=false;
canvas.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);pinch=0;moved=false});
canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;if(Math.hypot(dx,dy)>2)moved=true;if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)camera.distance=clamp(camera.distance*pinch/Math.max(10,d),6,38);pinch=d}else{camera.yaw-=dx*.005;camera.pitch=clamp(camera.pitch-dy*.004,-.05,1.48)}});
const release=e=>{const p=pointers.get(e.pointerId);pointers.delete(e.pointerId);pinch=0;if(!moved&&p){const target=segmentTargetFromPointer(e.clientX,e.clientY);if(target){lineState.customTarget=target;setEvent('已把下一次抛线方向设到点击位置；按“抛线接触”执行共享对象查询。')}}};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
canvas.addEventListener('wheel',e=>{e.preventDefault();camera.distance=clamp(camera.distance*Math.exp(e.deltaY*.001),6,38)},{passive:false});
canvas.addEventListener('contextmenu',e=>e.preventDefault());

function bindUi(){document.querySelectorAll('[data-morph]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-morph]').forEach(x=>x.classList.toggle('active',x===b));config.morph=b.dataset.morph;rebuild()});for(const key of ['nutrient','current','density','roughness','age']){const el=$(key),out=el.parentElement.querySelector('output');el.oninput=()=>{config[key]=Number(el.value);out.value=Number(el.value).toFixed(2);rebuild()}}$('hideFish').onclick=sendFishHome;$('roamFish').onclick=roamFish;$('castLine').onclick=castLine;$('releaseLine').onclick=releaseLine;$('debug').onclick=()=>{config.debug=!config.debug;$('debug').classList.toggle('active',config.debug);setEvent(config.debug?'青点=碰撞代理，粉点=鱼躲藏节点；两者都属于当前对象。':'交互骨架已隐藏。')};$('viewClose').onclick=()=>setView('close');$('viewHabitat').onclick=()=>setView('habitat');$('viewTop').onclick=()=>setView('top')}
function setEvent(s){$('event').textContent=s}

let last=performance.now(),fpsFrames=0,fpsClock=last;
function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(canvas.clientWidth*dpr)),h=Math.max(1,Math.round(canvas.clientHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function drawGpu(gpu){if(!gpu.count)return;bindGpu(gpu);gl.drawArrays(gl.TRIANGLES,0,gpu.count)}
function frame(now){resize();const dt=Math.min(.04,(now-last)/1000||1/60),time=now/1000;last=now;updateCamera();updateFish(dt,time);updateLine(dt,time);const d=new MeshBuilder();for(const f of fish)addFishMesh(d,f,time);addLineMesh(d);addDebug(d);upload(dynamicGpu,d.data,gl.DYNAMIC_DRAW);
 gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.008,.105,.15,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(U.view,false,camera.view);gl.uniformMatrix4fv(U.proj,false,camera.proj);gl.uniform1f(U.time,time);gl.uniform3fv(U.camera,camera.eye);drawGpu(staticGpu);drawGpu(dynamicGpu);
 fpsFrames++;if(now-fpsClock>700){const fps=fpsFrames*1000/(now-fpsClock);$('tFps').textContent=fps.toFixed(0);fpsFrames=0;fpsClock=now}requestAnimationFrame(frame)}

try{bindUi();rebuild();setTimeout(()=>{qa.ready=true;$('loading').classList.add('done');setView('habitat')},520);requestAnimationFrame(frame)}catch(e){fail(e)}
