import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('playwright');
const target=process.env.WZ1942_URL||'http://127.0.0.1:8768/site/dist/r3-8/history-1942.html';
const out=process.env.WZ1942_OUT||'/tmp/wz1942-refine';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1536,height:960},reducedMotion:'reduce'});if(target.includes('githack'))await context.setExtraHTTPHeaders({Cookie:'__Http-phish=1'});const page=await context.newPage();const failures=[],consoleErrors=[];const check=(v,m)=>{if(!v)failures.push(m);};page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('pageerror',e=>consoleErrors.push(e.stack||String(e)));
try{
  await page.goto(target,{waitUntil:'domcontentloaded',timeout:120000});
  await page.waitForFunction(()=>window.__wenzhouMapMother1940sRefine?.schema==='wenzhou-map-mother/1940s-refine-r28'||document.querySelector('#terrain')?.dataset.history1940sRefineError,{},{timeout:45000});
  await page.waitForFunction(()=>document.querySelector('#terrain')?.dataset.osmLoaded==='true',{},{timeout:120000});
  await page.waitForFunction(()=>Number(document.querySelector('#terrain')?.dataset.history1940sRefineOsmObjects||0)>0,{},{timeout:30000});
  await page.waitForFunction(()=>window.__wenzhouNg51IslandRelief?.ready===true||document.querySelector('#terrain')?.dataset.ng51IslandReliefError,{},{timeout:120000});
  await page.waitForFunction(()=>window.__wenzhouFullBathymetry?.ready===true||document.querySelector('#terrain')?.dataset.ng51BathymetryError,{},{timeout:120000});
  await page.waitForTimeout(700);
  const r=await page.evaluate(()=>window.__wenzhouMapMother1940sRefine||null),ir=await page.evaluate(()=>window.__wenzhouNg51IslandRelief||null),br=await page.evaluate(()=>window.__wenzhouFullBathymetry||null);const ds=await page.locator('#terrain').evaluate(c=>({...c.dataset}));
  check(!ds.history1940sRefineError,`refine runtime error: ${ds.history1940sRefineError||''}`);
  check(r?.schema==='wenzhou-map-mother/1940s-refine-r28','R28 refine state missing');
  check(r?.mask?.[0]>=1500&&r?.mask?.[1]>=1500,'refined mask resolution too low');
  check(r?.highGroundSeeds>0,'no base-land high-ground island seeds');
  check(r?.islandPixelsRestored>0,'no base-land high-ground land restored');
  check(r?.terrainHeightUnchanged===true,'historical mask modified terrain elevation');
  check(Number(r?.landAlphaTest)>=.5,'land alpha threshold can expand blurred land into water');
  check(Number.isFinite(Number(r?.blurLandGrowthPixelsClamped)),'blur land-growth guard did not publish diagnostics');
  check(r?.xuanmenForcedWaterPixels>0,'Xuanmen Bay override opened no historical water');
  check(r?.seaMaskUpdated===true,'refined mask not connected to sea renderer');check(r?.strictWaterProtectionActive===true,'strict NG51-1 water protection not active during refinement');
  check((r?.osm?.objects||0)>0,'refined OSM remask found no loaded OSM objects');
  check((r?.osm?.roadHidden||0)>0,'refined historical water hid no modern roads');check((r?.roadMapSupport?.points||0)>=1000,'NG51-1 road support not loaded');check((r?.osm?.majorRoadUnsupportedHidden||0)>0,'NG51-1 map removed no unsupported major roads');
  check(ds.history1940sRefine==='r28','R28 dataset marker missing');
  check(ds.history1940sTerrainHeightUnchanged==='true','terrain-height invariant dataset marker missing');
  check(!ds.ng51IslandReliefError,`NG51 island relief runtime error: ${ds.ng51IslandReliefError||''}`);
  check(ir?.schema==='wenzhou-ng51-island-relief-runtime/v2','NG51 canonical island relief v2 missing');
  check(ir?.ready===true,'NG51 canonical island relief missing');
  check(ir?.source==='canonical-dem-r1','NG51 island relief not sourced from canonical DEM');
  check(ir?.sourceSpacingM===12.5&&ir?.runtimeSpacingM===50,'NG51 island relief spacing contract wrong');
  check(ir?.islandHoleCount>=90,'NG51 island relief lost historical island holes');
  check((ir?.islandCells||0)>0&&(ir?.triangles||0)>0,'NG51 island relief produced no geometry');
  check((ir?.baseIslandMaskPixelsCut||0)>0,'200m base island layer was not cut before 50m replacement');
  check(Number(ir?.buildMs)>0&&Number(ir?.buildMs)<60000,'NG51 island relief build time out of bound');
  check(Number(ir?.maxScanChunkMs)>=0&&Number(ir?.maxScanChunkMs)<250,'NG51 island scan blocked the main thread too long');
  check(Number(ir?.maxGeometryChunkMs)>=0&&Number(ir?.maxGeometryChunkMs)<250,'NG51 island geometry blocked the main thread too long');
  check(String(ir?.replacementPolicy||'').includes('Unsupported island pixels remain on the base layer'),'unsupported island fallback policy missing');
  check(String(ir?.registrationGuard||'').includes('cannot emit a terrain-added event'),'NG51 island terrain-identity guard missing');
  check(!ds.ng51BathymetryError,`full bathymetry runtime error: ${ds.ng51BathymetryError||''}`);
  check(br?.schema==='wenzhou-full-bathymetry-runtime/v2'&&br?.ready===true,'full-domain bathymetry runtime missing');
  check(br?.sourceCrs==='EPSG:9518','full bathymetry CRS identity missing');
  check(Array.isArray(br?.heightRangeM)&&br.heightRangeM[0]<0,'full bathymetry has no below-sea relief');
  check((br?.waterCells||0)>0&&(br?.triangles||0)>0,'full bathymetry generated no historical-water geometry');
  check(br?.runtimeStride===2&&br?.effectiveArcSeconds===30,'full bathymetry runtime sampling contract wrong');
  check(br?.sourceBoundsContainPatch===true&&Array.isArray(br?.sourceBufferM)&&br.sourceBufferM.every(x=>x>0),'full bathymetry source boundary crosses the active terrain view');
  check(String(br?.displayBoundaryPolicy||'').includes('buffered beyond the active terrain window'),'full bathymetry buffered-boundary policy missing');
  check(String(br?.cellPolicy||'').includes('final historical water mask'),'full bathymetry is not clipped by the final historical water mask');
  check(Number(br?.buildMs)>0&&Number(br?.buildMs)<60000,'full bathymetry build time out of bound');
  check(Number(br?.maxChunkMs)>=0&&Number(br?.maxChunkMs)<250,'full bathymetry blocked the main thread too long');
  check(String(br?.registrationGuard||'').includes('cannot emit a terrain-added event'),'seabed terrain-identity guard missing');
  check(String(br?.role||'').includes('independent of the dynamic sea surface'),'seabed/sea-surface separation missing');
  check(ds.ng51BathymetrySourceBuffered==='true','full bathymetry buffered-source dataset marker missing');
  await page.screenshot({path:`${out}/desktop-refine-r28.png`,fullPage:true});
  console.log(JSON.stringify({passed:!failures.length,target,refinement:r,islandRelief:ir,bathymetry:br,dataset:{history1940sRefine:ds.history1940sRefine,history1940sRefineMask:ds.history1940sRefineMask,history1940sIslandPixelsRestored:ds.history1940sIslandPixelsRestored,history1940sBlurLandGrowthClamped:ds.history1940sBlurLandGrowthClamped,history1940sTerrainHeightUnchanged:ds.history1940sTerrainHeightUnchanged,history1940sXuanmenForcedWaterPixels:ds.history1940sXuanmenForcedWaterPixels,history1940sRefineOsmObjects:ds.history1940sRefineOsmObjects,history1940sRefineRoadHidden:ds.history1940sRefineRoadHidden,ng51IslandReliefBuildMs:ds.ng51IslandReliefBuildMs,ng51BathymetryBuildMs:ds.ng51BathymetryBuildMs,ng51BathymetrySourceBuffered:ds.ng51BathymetrySourceBuffered,osmLoaded:ds.osmLoaded},consoleErrors,failures},null,2));
}catch(e){const ds=await page.locator('#terrain').count()?await page.locator('#terrain').evaluate(c=>({...c.dataset})):{};failures.push(e.stack||String(e));console.log(JSON.stringify({passed:false,target,dataset:ds,consoleErrors,failures},null,2));}finally{await browser.close();}if(failures.length)process.exit(1);
