import * as THREE from 'three';
const S=window.R42,{mobile,scene,MAT,mesh}=S;const W=window.W,{mix,fineDetail,baseNatural,terraceMask,terraceInfoFromNatural,plainFields,plainEdges,plainBundLines,plainFieldAt,terraceFields,fieldAt,riverZ,sourcePath,channelSpecs,channelSurface,terrainY,irrigation,irrigationValidation}=W;

const EXT={xmin:-220,xmax:220,zmin:-290,zmax:185,step:mobile?2.3:1.78},sx=Math.round((EXT.xmax-EXT.xmin)/EXT.step),sz=Math.round((EXT.zmax-EXT.zmin)/EXT.step),tg=new THREE.PlaneGeometry(EXT.xmax-EXT.xmin,EXT.zmax-EXT.zmin,sx,sz);tg.rotateX(-Math.PI/2);tg.translate((EXT.xmin+EXT.xmax)/2,0,(EXT.zmin+EXT.zmax)/2);const tp=tg.attributes.position,vc=new Float32Array(tp.count*3),C=new THREE.Color();for(let i=0;i<tp.count;i++){const x=tp.getX(i),z=tp.getZ(i),y=terrainY(x,z);tp.setY(i,y);const nat=baseNatural(x,z),tm=terraceMask(x,z),ff=plainFieldAt(x,z),fine=fineDetail(x,z);if(z>125&&Math.abs(z-riverZ(x))<14)C.set('#496b54');else if(ff)C.set(['#647a45','#6c8443','#788a42','#938149'][ff.stage]);else if(tm>.45){const ti=terraceInfoFromNatural(nat,x,z);C.set(ti.f>.76?'#745539':(ti.k%4===3?'#807740':ti.k%3===0?'#5f7f3e':'#6b8441'));}else if(nat>34)C.set('#354f40');else if(nat>18)C.set('#3e693e');else C.set('#5e8146');C.multiplyScalar(.92+fine*.05);vc[i*3]=C.r;vc[i*3+1]=C.g;vc[i*3+2]=C.b;}tg.setAttribute('color',new THREE.BufferAttribute(vc,3));tg.computeVertexNormals();const terrain=mesh(tg,MAT.terrain);terrain.receiveShadow=true;

function polylineRibbonGeometry(lines,widthFn,offset=.03,yFn=null){const pos=[],idx=[];let base=0;for(const line of lines){const points=line.points||line;if(!points||points.length<2)continue;for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],dx=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dx,dz)||1,nx=-dz/L,nz=dx/L,w=typeof widthFn==='function'?widthFn(line,i):widthFn;const yA=yFn?yFn(line,i,0,a):terrainY(a[0],a[1])+offset,yB=yFn?yFn(line,i,1,b):terrainY(b[0],b[1])+offset;pos.push(a[0]-nx*w*.5,yA,a[1]-nz*w*.5,a[0]+nx*w*.5,yA,a[1]+nz*w*.5,b[0]-nx*w*.5,yB,b[1]-nz*w*.5,b[0]+nx*w*.5,yB,b[1]+nz*w*.5);idx.push(base,base+2,base+1,base+1,base+2,base+3);base+=4;}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g;}
function resample(points,n=24){const lens=[];let total=0;for(let i=0;i<points.length-1;i++){const l=Math.hypot(points[i+1][0]-points[i][0],points[i+1][1]-points[i][1]);lens.push(l);total+=l;}const out=[];for(let q=0;q<=n;q++){let d=total*q/n;for(let i=0;i<lens.length;i++){if(d<=lens[i]||i===lens.length-1){const t=Math.min(1,d/(lens[i]||1));out.push([mix(points[i][0],points[i+1][0],t),mix(points[i][1],points[i+1][1],t),q/n]);break;}d-=lens[i];}}return out;}

const channelLines=[];for(const spec of channelSpecs){const pts=resample(spec.p,Math.max(8,spec.p.length*7));channelLines.push({points:pts.map(p=>[p[0],p[1]]),spec,sampled:pts});}
mesh(polylineRibbonGeometry(channelLines,l=>l.spec.w*2.05,.012),MAT.wet);
mesh(polylineRibbonGeometry(channelLines,l=>l.spec.w*.9,0,(l,i,end)=>channelSurface(l.spec,l.sampled[i+end][2])+.02),MAT.water);
const river=[];for(let i=0;i<=170;i++){const x=-215+i*430/170;river.push([x,riverZ(x)]);}mesh(polylineRibbonGeometry([river],21,.075),MAT.water);mesh(polylineRibbonGeometry([river.map(p=>[p[0],p[1]-12.4]),river.map(p=>[p[0],p[1]+12.4])],2.7,.02),MAT.wet);

function fieldSurfaceGeometry(fields,stage){const pos=[],idx=[];let base=0;for(const f of fields){if(f.stage!==stage)continue;const contour=f.poly.map(p=>new THREE.Vector2(p[0],-p[1])),tri=THREE.ShapeUtils.triangulateShape(contour,[]),constant=f.kind==='plain'?f.bed+(f.waterDepth||0)+.02:null;for(const p of f.poly){const y=constant!==null?constant:terrainY(p[0],p[1])+.025;pos.push(p[0],y,p[1]);}for(const t of tri)idx.push(base+t[0],base+t[2],base+t[1]);base+=f.poly.length;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g;}
const stageMats=[MAT.water,MAT.water,new THREE.MeshStandardMaterial({color:'#6d8441',roughness:.9}),new THREE.MeshStandardMaterial({color:'#95834b',roughness:.92})],fieldMeshes=[];for(let stage=0;stage<4;stage++)fieldMeshes.push(mesh(fieldSurfaceGeometry([...plainFields,...terraceFields],stage),stageMats[stage]));

function uniqueEdges(fields,scale=100){const m=new Map(),q=p=>`${Math.round(p[0]*scale)}:${Math.round(p[1]*scale)}`;for(const f of fields)for(let i=0;i<f.poly.length;i++){const a=f.poly[i],b=f.poly[(i+1)%f.poly.length],ka=q(a),kb=q(b),k=ka<kb?`${ka}|${kb}`:`${kb}|${ka}`;if(!m.has(k))m.set(k,{a,b,owners:[]});m.get(k).owners.push(f.id);}return[...m.values()];}
const terraceEdges=uniqueEdges(terraceFields,100),bundLines=[...plainBundLines.map(line=>({points:line.points,edge:{...line,terrace:false}})),...terraceEdges.map(e=>({points:[e.a,e.b],edge:{...e,terrace:true,kind:'terrace'}}))];
mesh(polylineRibbonGeometry(bundLines,l=>{const e=l.edge,outer=e.owners.length===1;if(e.terrace)return outer?1.16:.82;if(e.kind==='major')return 1.58;if(e.kind==='outer')return 1.72;return outer?1.42:.96;},.11),MAT.soil);
mesh(polylineRibbonGeometry(bundLines,l=>{const e=l.edge,outer=e.owners.length===1;if(e.terrace)return outer?.52:.34;if(e.kind==='major')return .64;if(e.kind==='outer')return .72;return outer?.62:.38;},.29),MAT.grass);

const irrigationLines=[];for(const e of irrigation.edges){if(!e.points||e.points.length<2)continue;const pts=e.points.map(p=>Array.isArray(p[0])?p[0]:p);irrigationLines.push({points:resample(pts,Math.max(3,pts.length*3)).map(p=>[p[0],p[1]]),edge:e});}
const waterGroup=new THREE.Group();scene.add(waterGroup);mesh(polylineRibbonGeometry(irrigationLines,l=>l.edge.kind.includes('terrace')?.46:.34,.008),MAT.wet,waterGroup);mesh(polylineRibbonGeometry(irrigationLines,l=>l.edge.kind.includes('terrace')?.22:.17,.035),MAT.water,waterGroup);

Object.assign(S,{terrain,river,fieldMeshes,waterGroup,irrigationLines,polylineRibbonGeometry,resample});
const stats=document.getElementById('stats');stats.textContent=`${irrigationValidation.fieldCount} 块田（平坝 ${irrigationValidation.plainCount} / 梯田 ${irrigationValidation.terraceCount}）· ${irrigationValidation.edgeCount} 条灌排关系 · 孤田 ${irrigationValidation.ok?0:irrigationValidation.errors.length}`;
import('./ecology.mjs');
