import * as THREE from 'three';
const S=window.R41,{mobile,scene,camera,controls,renderer,MAT,mesh,waterGroup}=S;const W=window.W,{mix,clamp,hash,rng,plainFields,terraceFields,allFields,fieldAt,plainFieldAt,terraceMask,riverZ,terrainY,irrigation,farmerDefs,buffaloDefs,shelterDefs,irrigationValidation}=W;const R=rng(411016),D=new THREE.Object3D();
const stageColors=['#55a047','#5f913c','#738c39','#b3a04e'],stageHeights=[.28,.56,.82,.96],cropMeshes=[];for(let stage=0;stage<4;stage++){const g=new THREE.PlaneGeometry(stage===0?.03:.045,stageHeights[stage]);g.translate(0,stageHeights[stage]*.5,0);const mat=new THREE.MeshStandardMaterial({color:stageColors[stage],roughness:.89,side:THREE.DoubleSide}),pts=[];for(let x=-138;x<116;x+=mobile?3.8:2.7)for(let z=-136;z<128;z+=mobile?3.8:2.7){const f=fieldAt(x,z);if(!f||f.stage!==stage||hash(x*.21,z*.19)<.17)continue;pts.push([x,terrainY(x,z)+.035,z,.72+.28*hash(x,z)]);}const inst=new THREE.InstancedMesh(g,mat,pts.length);pts.forEach(([x,y,z,s],i)=>{D.position.set(x,y,z);D.rotation.set(0,hash(x,z)*6.28,.055*Math.sin(x+z));D.scale.set(s,s,s);D.updateMatrix();inst.setMatrixAt(i,D.matrix);});inst.castShadow=!mobile;inst.receiveShadow=true;scene.add(inst);cropMeshes.push(inst);}
const treeSites=[],step=mobile?10:7.4;for(let x=-212;x<212;x+=step)for(let z=-282;z<174;z+=step){const f=fieldAt(x,z),tm=terraceMask(x,z),rd=Math.abs(z-riverZ(x));let p=z<-130?.75:f?.025:(z>122&&rd<30)?.68:.24;if(R()<p){if(f||tm>.55)continue;treeSites.push([x+(R()-.5)*4,terrainY(x,z),z+(R()-.5)*4,3.3+R()*8]);}}
const trunkG=new THREE.CylinderGeometry(.09,.17,1,6),crownG=new THREE.IcosahedronGeometry(1,1),trunks=new THREE.InstancedMesh(trunkG,MAT.trunk,treeSites.length),crowns=new THREE.InstancedMesh(crownG,MAT.leaf,treeSites.length*4),green=new THREE.Color();treeSites.forEach(([x,y,z,h],i)=>{D.position.set(x,y+h*.34,z);D.scale.set(h*.32,h*.68,h*.32);D.rotation.set(0,R()*6,0);D.updateMatrix();trunks.setMatrixAt(i,D.matrix);for(let j=0;j<4;j++){const a=j*1.57+R()*.42;D.position.set(x+Math.cos(a)*h*.17,y+h*(.6+R()*.25),z+Math.sin(a)*h*.17);D.scale.set(h*(.2+R()*.07),h*(.18+R()*.07),h*(.2+R()*.07));D.rotation.set(R(),R()*6,R());D.updateMatrix();crowns.setMatrixAt(i*4+j,D.matrix);green.setHSL(.23+R()*.08,.39+R()*.2,.17+R()*.09);crowns.setColorAt(i*4+j,green);}});trunks.castShadow=!mobile;crowns.castShadow=true;scene.add(trunks,crowns);
function shelter(def){const g=new THREE.Group();g.position.set(def.x,terrainY(def.x,def.z),def.z);scene.add(g);const pad=mesh(new THREE.CylinderGeometry(2.0,2.25,.24,16),MAT.soil,g);pad.position.y=.12;for(const sx of[-1,1])for(const sz of[-1,1]){const p=mesh(new THREE.CylinderGeometry(.07,.09,2.2,7),MAT.wood,g);p.position.set(sx*1.22,1.15,sz*.92);}const deck=mesh(new THREE.BoxGeometry(2.65,.14,1.82),MAT.wood,g);deck.position.y=.5;const roof=mesh(new THREE.ConeGeometry(2.2,.92,4),MAT.thatch,g);roof.rotation.y=Math.PI/4;roof.scale.z=.78;roof.position.y=2.52;return g;}const shelters=shelterDefs.map(shelter);
const sphere=new THREE.SphereGeometry(1,10,8),cyl=new THREE.CylinderGeometry(1,1,1,8),actors=new THREE.Group();scene.add(actors);function lm(g,m,p){const o=new THREE.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;p.add(o);return o;}function limb(p,a,b,r,m){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),o=lm(cyl,m,p);o.position.copy(A).add(B).multiplyScalar(.5);o.scale.set(r,A.distanceTo(B),r);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),B.sub(A).normalize());return o;}
function insetPath(field,scale=.34){const c=field.centroid,pts=[];for(const p of field.poly){pts.push([mix(c[0],p[0],scale),mix(c[1],p[1],scale)]);if(pts.length>=6)break;}if(pts.length<3)pts.push([c[0]-2,c[1]],[c[0]+2,c[1]],[c[0],c[1]+2]);return pts;}
function farmer(def){const field=allFields.find(f=>f.id===def.fieldId),g=new THREE.Group();g.userData={def,field,path:insetPath(field,.33),progress:def.phase};actors.add(g);const torso=new THREE.Group();g.add(torso);const hip=[0,.77,0],shoulder=[0,1.15,0];limb(torso,hip,shoulder,.15,MAT.cloth);const head=lm(sphere,MAT.skin,torso);head.scale.set(.11,.14,.115);head.position.set(0,1.35,-.02);const arms=[];for(const s of[-1,1]){limb(torso,[s*.1,.78,0],[s*.14,.38,.01],.052,MAT.dark);limb(torso,[s*.14,.38,.01],[s*.17,.07,.02],.038,MAT.skin);const arm=new THREE.Group();arm.position.set(s*.16,1.08,0);torso.add(arm);limb(arm,[0,0,0],[s*.07,-.43,-.28],.043,MAT.cloth);limb(arm,[s*.07,-.43,-.28],[s*.02,-.83,-.52],.031,MAT.skin);arms.push(arm);}const brim=lm(new THREE.CylinderGeometry(.34,.34,.035,24),MAT.thatch,torso);brim.position.set(0,1.5,-.02);const crown=lm(new THREE.ConeGeometry(.21,.18,20),MAT.thatch,torso);crown.position.set(0,1.6,-.03);g.userData.torso=torso;g.userData.arms=arms;return g;}
const farmers=farmerDefs.map(farmer);
function buffalo(def){const field=allFields.find(f=>f.id===def.fieldId),g=new THREE.Group();g.userData={def,field,path:insetPath(field,.28),progress:def.phase};actors.add(g);const body=lm(sphere,MAT.dark,g);body.scale.set(1.35,.68,.57);body.position.y=.94;const neck=lm(sphere,MAT.dark,g);neck.scale.set(.55,.58,.48);neck.position.set(-.86,1.01,0);const head=lm(sphere,MAT.dark,g);head.scale.set(.52,.4,.43);head.position.set(-1.28,1,0);const legs=[];for(const xx of[-.55,.48])for(const zz of[-.34,.34]){const leg=new THREE.Group();leg.position.set(xx,.75,zz);g.add(leg);limb(leg,[0,0,0],[0,-.67,0],.064,MAT.dark);legs.push(leg);}for(const zz of[-.23,.23]){const horn=lm(new THREE.ConeGeometry(.045,.42,8),MAT.horn,g);horn.position.set(-1.55,1.17,zz);horn.rotation.z=-1.15;horn.rotation.y=zz>0?.22:-.22;}if(def.state==='ploughing'){const beam=lm(new THREE.CylinderGeometry(.025,.025,2.7,7),MAT.wood,g);beam.position.set(.92,.62,0);beam.rotation.z=Math.PI/2;const plough=lm(new THREE.BoxGeometry(.08,.42,.3),MAT.wood,g);plough.position.set(2.15,.18,0);plough.rotation.z=-.35;}g.userData.legs=legs;return g;}
const buffaloes=buffaloDefs.map(buffalo);
function pathPoint(path,t){const n=path.length,u=((t%1)+1)%1*n,i=Math.floor(u)%n,j=(i+1)%n,f=u-Math.floor(u);return[mix(path[i][0],path[j][0],f),mix(path[i][1],path[j][1],f),i,j,f];}
const flowGroup=new THREE.Group();scene.add(flowGroup);const nodeLevel=Object.fromEntries(irrigation.nodes.map(n=>[n.id,n.level])),dotG=new THREE.SphereGeometry(.105,7,5),dotM=new THREE.MeshBasicMaterial({color:'#eff7a7',depthTest:false}),flows=[];for(const e of irrigation.edges){if(!e.points||e.points.length<2)continue;const pts=e.points.map(p=>Array.isArray(p[0])?p[0]:p),dot=new THREE.Mesh(dotG,dotM);dot.renderOrder=30;flowGroup.add(dot);flows.push({dot,e,pts,phase:hash(e.id.length,e.id.charCodeAt(0))});}
function edgePoint(flow,t){const pts=flow.pts,n=pts.length-1,u=clamp(t,0,.9999)*n,i=Math.floor(u),f=u-i,a=pts[i],b=pts[i+1],x=mix(a[0],b[0],f),z=mix(a[1],b[1],f),y0=nodeLevel[flow.e.from]??terrainY(a[0],a[1])+.1,y1=nodeLevel[flow.e.to]??terrainY(b[0],b[1])+.05;return[x,Math.max(terrainY(x,z)+.12,mix(y0,y1,(i+f)/n)+.08),z];}
const views={overview:{p:[190,70,215],t:[-10,13,-45]},cells:{p:[132,34,153],t:[0,.5,74]},water:{p:[92,28,132],t:[2,.6,76]},terrace:{p:[-92,30,38],t:[-38,10,-62]},workers:{p:[45,4.4,105],t:[4,.9,73]},buffalo:{p:[100,4.2,98],t:[48,.9,72]}};function go(k){camera.position.fromArray(views[k].p);controls.target.fromArray(views[k].t);controls.update();document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v===k));}go('overview');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>go(b.dataset.v));const toggle=document.getElementById('waterToggle');toggle.onclick=()=>{const on=!waterGroup.visible;waterGroup.visible=on;flowGroup.visible=on;toggle.setAttribute('aria-pressed',String(on));toggle.textContent=on?'水网开':'水网关';};
let last=performance.now(),elapsed=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;elapsed+=dt;for(const f of farmers){const d=f.userData,cycle=(elapsed*.12+d.def.phase)%1,walking=cycle<.68,p=pathPoint(d.path,d.progress);if(walking)d.progress=(d.progress+dt*.018)%1;const next=pathPoint(d.path,d.progress+.005),ang=Math.atan2(next[0]-p[0],next[1]-p[1]);f.position.set(p[0],terrainY(p[0],p[1]),p[1]);f.rotation.y=ang;const work=walking?0:Math.sin((cycle-.68)/.32*Math.PI);d.torso.rotation.x=work*.72;d.torso.position.z=-work*.18;d.arms[0].rotation.x=-work*.65+Math.sin(elapsed*7+d.def.phase*6)*.08;d.arms[1].rotation.x=-work*.65-Math.sin(elapsed*7+d.def.phase*6)*.08;f.position.y+=walking?Math.abs(Math.sin(elapsed*6+d.def.phase*9))*.018:0;}
for(const b of buffaloes){const d=b.userData,p=pathPoint(d.path,d.progress);d.progress=(d.progress+dt*(d.def.state==='resting'?.002:.008))%1;const next=pathPoint(d.path,d.progress+.004),ang=Math.atan2(next[0]-p[0],next[1]-p[1]);b.position.set(p[0],terrainY(p[0],p[1]),p[1]);b.rotation.y=ang;d.legs.forEach((leg,i)=>leg.rotation.x=d.def.state==='resting'?0:Math.sin(elapsed*2.4+i*Math.PI)*.16);}
for(const flow of flows){const p=edgePoint(flow,(elapsed*.08+flow.phase)%1);flow.dot.position.set(...p);}controls.update();renderer.render(scene,camera);}requestAnimationFrame(animate);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
window.__FARMLAND_R041__={fieldCount:allFields.length,plainCount:plainFields.length,terraceCount:terraceFields.length,farmerCount:farmers.length,buffaloCount:buffaloes.length,shelterCount:shelters.length,irrigationValidation};
