import {build} from 'esbuild';
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {VERSION} from '../src/instrument.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),out=resolve(root,'dist');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
const result=await build({entryPoints:[resolve(root,'src/instrument.js')],bundle:true,write:false,format:'iife',globalName:'KAOPUAnimal',minify:true,platform:'browser',target:'es2022',legalComments:'inline'});
const license=await readFile(resolve(root,'node_modules/three/LICENSE'),'utf8');
const pure='/* KAOPU ANIMAL INSTRUMENT '+VERSION+' | Reference-guided approximate reconstruction\n'+license+'\n*/\n'+result.outputFiles[0].text+'\n';
new Function(pure);
const script=s=>'<script>'+s.replaceAll('</script','<\\/script')+'</script>';
let template=(await readFile(resolve(root,'src/index.template.html'),'utf8')).replaceAll('K3.0.0',VERSION).replace('__SHA__',process.env.GITHUB_SHA||'local').replace('</head>',`<meta name="instrument-bytes" content="${Buffer.byteLength(pure)}"></head>`);
const app=await readFile(resolve(root,'src/app.js'),'utf8'),examples=await readFile(resolve(root,'src/examples.json'),'utf8');
const render=ex=>template.replace('<!--ENGINE-->',()=>script(pure)).replace('<!--EXAMPLES-->',()=>ex).replace('<!--APP-->',()=>script(app));
await writeFile(resolve(out,'index.html'),render(script('globalThis.KAOPU_EXAMPLES='+examples+';')));
await writeFile(resolve(out,'KAOPU_ANIMAL_PLAYER.html'),render('<style>.reference-only{display:none}</style>').replace('一个乐器<br>三份动物谱','独立乐器<br>输入动物谱'));
await writeFile(resolve(out,'KAOPU_ANIMAL_K3.js'),pure);await writeFile(resolve(out,'LICENSE_THREE.txt'),license);
for(const [kind,item] of Object.entries(JSON.parse(examples)))await writeFile(resolve(out,'KAOPU_'+kind+'_K3.score'),item.score+'\n');
await writeFile(resolve(out,'README.txt'),(await readFile(resolve(root,'README.md'),'utf8')).replaceAll('K3.0.0',VERSION));
let coreSourceBytes=0;for(const f of ['instrument.js','anatomy.js','covering.js'])coreSourceBytes+=Buffer.byteLength(await readFile(resolve(root,'src',f)));
const summary={version:VERSION,instrumentBytes:Buffer.byteLength(pure),coreSourceBytes,workbenchBytes:Buffer.byteLength(await readFile(resolve(out,'index.html'))),playerBytes:Buffer.byteLength(await readFile(resolve(out,'KAOPU_ANIMAL_PLAYER.html'))),scores:Object.fromEntries(Object.entries(JSON.parse(examples)).map(([k,v])=>[k,Buffer.byteLength(v.score)])),sourceSha:process.env.GITHUB_SHA||'local'};
await writeFile(resolve(out,'BUILD.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary,null,2));
