/* Branch replay R01: a real generated mesh, not a video on the student canvas. */
(()=>{'use strict';const $=s=>document.getElementById(s),VERSION='branch-replay-r01-20261004',defaults={growth:72,depth:4,angle:37,spatial:.85,thickness:1,resolution:132};
let params={...defaults},mode='blue',showBones=false,refRatio=.25,refOpen=true,mesh=null,playing=false,orbit=false,active=true,queued=null,busy=false,serial=0,last=0,raf=0,needsDraw=true,lastGrowthAt=0;
let camera={yaw:.12,pitch:.07,zoom:1,pan:[0,0]},ptr=new Map(),pinch=null;
const S=window.BranchReplayState={version:VERSION,ready:false,error:null,mode:'blue',generated:false,referenceIsSourceImage:true,geometryHash:null,draws:0,meshUpdates:0,playing:false,active:true,camera:{},metrics:null,sourceFrames:{blue:682,clear:620,early:655},sourceVideoHash:'b5bd4cedda00c23e1018108e0a69348dfab9c711ee8c2b937792a1e367e6ae89',generator:'three-seed local branching grammar + implicit tapered capsules + smooth union + marching tetrahedra',sourceSceneRecovered:false};
const cv=$('canvas'),gl=cv.getContext('webgl2',{alpha:false,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});
function fail(e){S.error=String(e?.message||e);S.ready=false;playing=false;$('fatal').hidden=false;$('fatal').textContent='三维生成失败：'+S.error+'。没有切换为截图。';report()}
function report(){if(parent!==window)parent.postMessage({type:'coral:branch-state',version:VERSION,ready:S.ready,error:S.error,draws:S.draws},location.origin)}
if(!gl){fail('WebGL2 不可用');return}
cv.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('WebGL 上下文丢失')});
const vs=`#version 300 es
precision highp float;layout(location=0) in vec3 aPosition;layout(location=1) in vec3 aNormal;layout(location=2) in vec2 aInfo;uniform mat4 uVP;out vec3 vP;out vec3 vN;out vec2 vInfo;void main(){vP=aPosition;vN=aNormal;vInfo=aInfo;gl_Position=uVP*vec4(aPosition,1.);}`;
const fs=`#version 300 es
precision highp float;in vec3 vP;in vec3 vN;in vec2 vInfo;uniform vec3 uEye;uniform int uMode;uniform int uPass;uniform float uBones;out vec4 outColor;
float sat(float x){return clamp(x,0.,1.);}vec3 env(vec3 r){vec3 e=vec3(.022,.035,.052);float a=pow(max(dot(r,normalize(vec3(-.8,1.2,1.))),0.),36.),b=pow(max(dot(r,normalize(vec3(1.1,.2,-.6))),0.),64.);e+=vec3(1.,.95,.88)*a*4.+vec3(.64,.83,1.)*b*5.;e+=vec3(.28,.38,.5)*pow(max(r.y,0.),5.);e+=vec3(1.3)*(1.-smoothstep(.02,.14,abs(r.x-.32)))*(1.-smoothstep(.65,.99,abs(r.y)));return e;}
void main(){if(uPass==1){outColor=vec4(.78,.87,.95,1);return;}
 vec3 N=normalize(vN);if(!gl_FrontFacing)N=-N;vec3 V=normalize(uEye-vP);
 vec3 n=vec3(sin(vP.y*70.+sin(vP.z*39.)),sin(vP.z*61.+sin(vP.x*28.)),sin(vP.x*76.+sin(vP.y*36.)));
 N=normalize(N+(n-N*dot(n,N))*.065);
 float facing=max(dot(N,V),0.),fres=pow(1.-facing,5.);
 float tips=smoothstep(.61,.97,vInfo.y)*(.48+.52*vInfo.x),depth=sat(.22+vInfo.x*.70);
 vec3 base=mix(vec3(.04,.09,.28),vec3(.39,.52,.83),depth);base=mix(base,vec3(.90,.96,1.),tips*.78);
 base*=.95+.05*sin(vP.x*19.+vP.y*12.)*sin(vP.z*23.+vP.y*14.);
 vec3 C=base*(.16+.18*max(N.y,0.));
 vec3 lights[3]=vec3[3](normalize(vec3(-1.6,2.2,2.5)),normalize(vec3(1.8,.6,1.5)),normalize(vec3(.4,1.2,-2.)));
 vec3 tint[3]=vec3[3](vec3(1.,.93,.85)*2.1,vec3(.55,.70,1.)*1.20,vec3(.70,.83,1.)*1.45);
 for(int i=0;i<3;i++){vec3 L=lights[i],H=normalize(L+V);float dif=max(dot(N,L),0.),NoH=max(dot(N,H),0.),a=.28,a2=a*a,den=NoH*NoH*(a2-1.)+1.;float spec=a2/(3.14159*den*den);C+=base*dif*tint[i]*.67+spec*mix(.045,.18,fres)*tint[i]*dif;C+=base*tint[i]*pow(max(dot(-N,L),0.),2.)*.085;}
 C+=env(reflect(-V,N))*(.035+.20*fres);
 if(uMode==1){vec3 R=env(reflect(-V,N));float edge=pow(1.-facing,1.15);C=vec3(.60,.69,.75)*(.12+.64*edge)+R*(.60+1.2*edge);C+=vec3(.60,.72,.77)*pow(edge,3.)*.30;float alpha=.28+.59*edge+min(max(R.r,max(R.g,R.b)),1.)*.19;outColor=vec4(pow(C/(1.+C*.55),vec3(.4545)),alpha*(uPass==2?.75:1.));}
 else{C=C/(1.+C*.42);outColor=vec4(pow(max(C,0.),vec3(.4545)),uBones>.5?.24:1.);}
}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
let prog,U={};try{prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));for(const u of ['uVP','uEye','uMode','uPass','uBones'])U[u]=gl.getUniformLocation(prog,u)}catch(e){fail(e);return}
function vaoFor(pos,nor,info){const vao=gl.createVertexArray(),buf=[];gl.bindVertexArray(vao);[pos,nor,info].forEach((a,i)=>{const b=gl.createBuffer();buf.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,a,gl.STATIC_DRAW);gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,i===2?2:3,gl.FLOAT,false,0,0)});gl.bindVertexArray(null);return {vao,buf,count:pos.length/3}}
function release(m){if(!m)return;for(const o of [m.surface,m.line]){o.buf.forEach(b=>gl.deleteBuffer(b));gl.deleteVertexArray(o.vao)}}
function floatHash(a){const b=new Uint8Array(a.buffer);let h=2166136261;for(let i=0;i<b.length;i+=7)h=Math.imul(h^b[i],16777619);return(h>>>0).toString(16)}
const worker=new Worker('branch-worker.js?v=branch-r01');worker.onerror=e=>fail(e.message);
function send(p){busy=true;S.pending=true;worker.postMessage({id:++serial,params:p});$('status').textContent='计算分叉 '+Math.round(p.growth)+'% …'}
function generate(){const p={...params,resolution:playing?100:params.resolution};if(busy)queued=p;else send(p);syncControls()}
worker.onmessage=e=>{const r=e.data;busy=false;S.pending=false;if(r.error){fail(r.error);return}if(!r.positions?.length){fail('未生成三角面');return}
 release(mesh);mesh={surface:vaoFor(r.positions,r.normals,r.attributes),line:vaoFor(r.skeleton,new Float32Array(r.skeleton.length),new Float32Array(r.skeleton.length/3*2))};
 S.geometryHash=floatHash(r.positions);S.metrics=r.metrics;S.graph=r.graph;S.completedGrowth=r.metrics.growth;S.meshUpdates++;S.ready=true;S.generated=true;S.error=null;
 $('fatal').hidden=true;$('stats').textContent=r.metrics.activeBranches+' 枝 / '+r.metrics.triangles.toLocaleString()+' 三角面';$('status').textContent='已生成 '+Math.round(r.metrics.growth)+'% · '+r.metrics.terminalFronts+' 个端部';$('geometryState').textContent='3 颗初芽 · '+r.metrics.ruleDepth+' 级分叉 · 连续融合表面';
 needsDraw=true;report();if(queued){const q=queued;queued=null;send(q)}else if(playing&&params.growth>=100){playing=false;S.playing=false;params.resolution=132;syncControls();generate()}schedule();};
function syncControls(){S.params={...params};S.mode=mode;S.playing=playing;S.camera={...camera,pan:camera.pan.slice()};$('growth').value=params.growth;$('growthLabel').textContent=Math.round(params.growth)+'%';$('angle').value=params.angle;$('angleLabel').textContent=params.angle+'°';$('depth').value=params.depth;$('thickness').value=params.thickness;$('thickLabel').textContent=params.thickness.toFixed(2);$('spatial').value=params.spatial;$('spatialLabel').textContent=params.spatial.toFixed(2);$('play').textContent=playing?'暂停生成':'播放生成过程';$('rotate').classList.toggle('on',orbit);$('blue').classList.toggle('on',mode==='blue');$('clear').classList.toggle('on',mode==='clear');$('skeleton').classList.toggle('on',showBones);$('reference').classList.toggle('on',refOpen);$('stage').classList.toggle('no-ref',!refOpen);$('teacherPanel').hidden=!refOpen;$('stage').style.setProperty('--ref',refRatio+'fr');$('refSize').textContent=Math.round(refRatio*100)+'%';$('zoomLabel').textContent=camera.zoom.toFixed(1)+'×';document.querySelectorAll('[data-growth]').forEach(b=>b.classList.toggle('on',Math.abs(Number(b.dataset.growth)-params.growth)<5));needsDraw=true;schedule()}
const norm=p=>{const l=Math.hypot(...p)||1;return p.map(v=>v/l)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function mul4(a,b){const r=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)r[i*4+j]+=a[k*4+j]*b[i*4+k];return r}
function cameraData(aspect){const target=[camera.pan[0],-.40+camera.pan[1],-.1],d=6.4,eye=[target[0]+d*Math.sin(camera.yaw)*Math.cos(camera.pitch),target[1]+d*Math.sin(camera.pitch),target[2]+d*Math.cos(camera.yaw)*Math.cos(camera.pitch)],z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x),v=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]),f=1/Math.tan(20*Math.PI/180)*camera.zoom,n=.01,far=50,p=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,-(far+n)/(far-n),-1,0,0,-2*far*n/(far-n),0]);return {vp:mul4(p,v),eye}}
function draw(){if(!S.ready||S.error||!mesh)return;const r=$('viewport').getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(1,Math.ceil(r.width*dpr)),h=Math.max(1,Math.ceil(r.height*dpr));if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h}S.resolution=[w,h];const {vp,eye}=cameraData(w/h);gl.viewport(0,0,w,h);gl.clearColor(.009,.017,.025,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.useProgram(prog);gl.uniformMatrix4fv(U.uVP,false,vp);gl.uniform3fv(U.uEye,eye);gl.uniform1i(U.uMode,mode==='clear'?1:0);gl.uniform1f(U.uBones,showBones?1:0);gl.bindVertexArray(mesh.surface.vao);
 if(mode==='clear'||showBones){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.cullFace(gl.FRONT);gl.uniform1i(U.uPass,2);gl.drawArrays(gl.TRIANGLES,0,mesh.surface.count);gl.cullFace(gl.BACK);gl.uniform1i(U.uPass,0);gl.drawArrays(gl.TRIANGLES,0,mesh.surface.count);gl.depthMask(true);gl.disable(gl.BLEND)}else{gl.disable(gl.BLEND);gl.cullFace(gl.BACK);gl.uniform1i(U.uPass,0);gl.drawArrays(gl.TRIANGLES,0,mesh.surface.count)}
 if(showBones){gl.disable(gl.DEPTH_TEST);gl.bindVertexArray(mesh.line.vao);gl.uniform1i(U.uPass,1);gl.drawArrays(gl.LINES,0,mesh.line.count)}
 const err=gl.getError();if(err!==gl.NO_ERROR){fail('GL '+err);return}S.draws++;S.camera={...camera,pan:camera.pan.slice()};needsDraw=false;}
function schedule(){if(!raf&&active&&!document.hidden&&!S.error)raf=requestAnimationFrame(tick)}
function tick(ms){raf=0;if(!active||document.hidden||S.error)return;const dt=last?Math.min((ms-last)/1000,.1):0;last=ms;if(orbit){camera.yaw+=dt*.17;needsDraw=true}if(playing&&!busy&&ms-lastGrowthAt>80){lastGrowthAt=ms;params.growth=Math.min(100,params.growth+2.5);generate()}if(needsDraw)draw();if(playing||orbit)schedule();}
function setGrowth(g){playing=false;S.playing=false;params.growth=Math.max(3,Math.min(100,Number(g)));generate()}
function setMode(m){mode=m==='clear'?'clear':'blue';$('teacherImage').src='teacher-'+(mode==='clear'?'clear':'blue')+'.webp';$('refFrame').textContent=mode==='clear'?'F0620 / 20.667s':'F0682 / 22.733s';$('outputTitle').textContent=mode==='clear'?'学生 · 透明延展生成':'学生 · 蓝白分叉生成';syncControls()}
$('blue').onclick=()=>setMode('blue');$('clear').onclick=()=>setMode('clear');$('skeleton').onclick=()=>{showBones=!showBones;syncControls()};$('reference').onclick=()=>{refOpen=!refOpen;syncControls()};$('closeRef').onclick=()=>{refOpen=false;syncControls()};$('refSmall').onclick=()=>{refRatio=Math.max(.18,refRatio-.1);syncControls()};$('refLarge').onclick=()=>{refRatio=Math.min(1,refRatio+.1);syncControls()};$('earlyRef').onclick=()=>{$('teacherImage').src='teacher-early.webp';$('refFrame').textContent='F0655 / 21.833s'};
$('play').onclick=()=>{playing=!playing;if(playing&&params.growth>=98)params.growth=5;S.playing=playing;syncControls();schedule()};$('restart').onclick=()=>setGrowth(5);$('growth').oninput=e=>setGrowth(e.target.value);document.querySelectorAll('[data-growth]').forEach(b=>b.onclick=()=>setGrowth(b.dataset.growth));$('rotate').onclick=()=>{orbit=!orbit;syncControls()};
for(const [id,key]of [['angle','angle'],['depth','depth'],['thickness','thickness'],['spatial','spatial']])$(id).oninput=e=>{playing=false;params[key]=Number(e.target.value);generate()};
function resetView(){camera={yaw:.12,pitch:.07,zoom:1,pan:[0,0]};syncControls()}$('resetView').onclick=resetView;$('resetAll').onclick=()=>{params={...defaults};playing=orbit=showBones=false;resetView();setMode('blue');generate()};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.student').requestFullscreen()}catch(e){$('status').textContent='浏览器不允许全屏'}};
$('back').onclick=()=>{playing=orbit=false;if(parent!==window)parent.postMessage({type:'coral:home'},location.origin);else location.href='../#view=home'};
$('save').onclick=()=>{draw();const a=document.createElement('a');a.href=cv.toDataURL('image/png');a.download='Coral-Branch-'+mode+'-'+Math.round(S.completedGrowth)+'.png';a.click()};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'coral-branch-score/1',params,mode,camera,source:S.sourceVideoHash,teacherSceneRecovered:false,graph:S.graph},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='CORAL_BRANCH_SCORE_R01.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
cv.addEventListener('contextmenu',e=>e.preventDefault());cv.addEventListener('pointerdown',e=>{if(e.button>2)return;e.preventDefault();cv.setPointerCapture(e.pointerId);ptr.set(e.pointerId,[e.clientX,e.clientY]);pinch=null;cv.style.cursor='grabbing'});
cv.addEventListener('pointermove',e=>{if(!ptr.has(e.pointerId))return;const old=ptr.get(e.pointerId);ptr.set(e.pointerId,[e.clientX,e.clientY]);const h=cv.getBoundingClientRect().height;
 if(ptr.size>1){const[a,b]=[...ptr.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]),m=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(pinch){camera.zoom=Math.max(.4,Math.min(100,camera.zoom*d/Math.max(1,pinch.d)));camera.pan[0]-=(m[0]-pinch.m[0])*.007/camera.zoom;camera.pan[1]+=(m[1]-pinch.m[1])*.007/camera.zoom}pinch={d,m};}
 else{const dx=e.clientX-old[0],dy=e.clientY-old[1];if(e.shiftKey||e.buttons===2){camera.pan[0]-=dx*4.6/(h*camera.zoom);camera.pan[1]+=dy*4.6/(h*camera.zoom)}else{camera.yaw+=dx*.007;camera.pitch=Math.max(-1.5,Math.min(1.5,camera.pitch+dy*.007))}}syncControls();});
for(const n of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(n,e=>{ptr.delete(e.pointerId);pinch=null;cv.style.cursor='grab'});
cv.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.4,Math.min(100,camera.zoom*Math.exp(-Math.max(-120,Math.min(120,e.deltaY))*.004)));syncControls()},{passive:false});cv.addEventListener('dblclick',resetView);
window.addEventListener('resize',()=>{needsDraw=true;schedule()});new ResizeObserver(()=>{needsDraw=true;schedule()}).observe($('viewport'));document.addEventListener('fullscreenchange',()=>{needsDraw=true;schedule()});
function setActive(v){active=!!v;S.active=active;if(!active){playing=false;orbit=false;S.playing=false;last=0}syncControls()}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='coral:active')setActive(e.data.active)});document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=orbit=false;S.playing=false;last=0}else{needsDraw=true;schedule()}});
function drawRule(g){let str='F',rule='F[+F][-F[-F]F]F[+F][-F]';for(let i=0;i<g;i++)str=str.replace(/F/g,rule);let x=0,y=0,a=-Math.PI/2,stack=[],segs=[];for(const s of str){if(s==='F'){const nx=x+Math.cos(a),ny=y+Math.sin(a);segs.push([x,y,nx,ny]);x=nx;y=ny}else if(s==='+')a+=Math.PI/6;else if(s==='-')a-=Math.PI/6;else if(s==='[')stack.push([x,y,a]);else if(s===']')[x,y,a]=stack.pop()}
 const c=$('ruleCanvas'),ctx=c.getContext('2d'),pts=segs.flatMap(s=>[[s[0],s[1]],[s[2],s[3]]]),lo=[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1]))],hi=[Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))],scale=Math.min((c.width-50)/(hi[0]-lo[0]||1),(c.height-25)/(hi[1]-lo[1]||1));ctx.fillStyle='#f1f3f3';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#20302e';ctx.lineWidth=1.4;ctx.beginPath();for(const s of segs){ctx.moveTo(25+(s[0]-lo[0])*scale,12+(s[1]-lo[1])*scale);ctx.lineTo(25+(s[2]-lo[0])*scale,12+(s[3]-lo[1])*scale)}ctx.stroke();$('ruleCount').textContent=segs.length+' 个 F 段';S.ruleDemo={growth:g,segments:segs.length,premise:'F',rule,sourceFrame:299};document.querySelectorAll('[data-rule]').forEach(b=>b.classList.toggle('on',+b.dataset.rule===g))}
document.querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>drawRule(+b.dataset.rule));drawRule(1);
window.BranchReplay={state:S,setGrowth,setMode,setActive,setParams(p){for(const k of ['angle','depth','spatial','thickness'])if(p[k]!==undefined)params[k]=p[k];generate()},setCamera(p){Object.assign(camera,p);syncControls()},resetView,pixelHash(){draw();const d=new Uint8Array(cv.width*cv.height*4);gl.readPixels(0,0,cv.width,cv.height,gl.RGBA,gl.UNSIGNED_BYTE,d);let h=2166136261;for(let i=0;i<d.length;i+=31)h=Math.imul(h^d[i],16777619);return(h>>>0).toString(16)},rule:drawRule};
syncControls();generate();report();})();
