(async()=>{'use strict';
const baseURL=new URL('.',document.currentScript.src),$=id=>document.getElementById(id),canvas=$('scene'),error=$('error'),loading=$('loading');
const qa={version:'0.6.0',ready:false,frames:0,errors:[],sourceAssets:0,storedImages:0,visualAcceptance:false,productionReady:false,weatherSource:'procedural presets',shadowMethod:'directional upwind optical-depth volume cache',temporalMethod:'world-space reprojection, depth/transmittance rejection and neighborhood clamp'};window.WeatherMother={qa};
function fail(e,stage='runtime'){const msg=stage+': '+(e?.stack||e?.message||String(e));qa.errors.push(msg);error.style.display='block';error.textContent='Weather Mother 运行中断\n'+msg;loading.textContent='请查看错误信息';console.error(msg);}
addEventListener('error',e=>fail(e.error||e.message,'javascript'));addEventListener('unhandledrejection',e=>fail(e.reason,'promise'));
const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl){fail('当前浏览器未提供 WebGL2','context');return;}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('WebGL context lost','gpu');});
const hdr=!!gl.getExtension('EXT_color_buffer_float');qa.hdr=hdr;const VS='#version 300 es\nvoid main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0.,1.);}';
let FS;try{const response=await fetch(new URL('cloud.glsl?v=060',baseURL));if(!response.ok)throw Error('Shader HTTP '+response.status);FS=await response.text();}catch(e){fail(e,'shader fetch');return;}
if(!hdr)FS=FS.replace('return s*uOpt.x;','return s*60.*uOpt.x;').replace('fragColor=vec4(max(col,0.),tr);fragInfo=vec4(depth,1.-tr,0.,1.);','fragColor=vec4(max(col,0.)/(1.+max(col,0.)),tr);fragInfo=vec4(depth/1024.,1.-tr,0.,1.);');
function shader(type,src){const x=gl.createShader(type);gl.shaderSource(x,src);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error((type===gl.VERTEX_SHADER?'vertex':'fragment')+' compile: '+(gl.getShaderInfoLog(x)||'empty GPU log'));return x;}
function program(fs){const p=gl.createProgram(),a=shader(gl.VERTEX_SHADER,VS),b=shader(gl.FRAGMENT_SHADER,fs);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error('program link: '+gl.getProgramInfoLog(p));gl.deleteShader(a);gl.deleteShader(b);return p;}
const RESOLVE=`#version 300 es
precision highp float;uniform sampler2D uCurrent,uInfo,uHistory,uHistoryInfo;uniform vec2 uSize;uniform vec3 uCamera,uTarget,uPreviousCamera,uPreviousTarget,uWindDelta;uniform float uValid;layout(location=0)out vec4 O;layout(location=1)out vec4 D;
void main(){vec2 uv=gl_FragCoord.xy/uSize;vec4 now=texture(uCurrent,uv),info=texture(uInfo,uv);vec3 low=now.rgb,high=now.rgb;for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){vec3 c=texture(uCurrent,uv+vec2(x,y)/uSize).rgb;low=min(low,c);high=max(high,c);}float weight=0.;vec4 hist=now;
if(uValid>.5){vec2 xy=(uv*2.-1.)*vec2(uSize.x/uSize.y,1);vec3 fw=normalize(uTarget-uCamera),right=normalize(cross(fw,vec3(0,1,0))),up=cross(right,fw),ray=normalize(fw+(xy.x*right+xy.y*up)*.48);vec3 world=uCamera+ray*info.x-uWindDelta*step(.015,info.y),prev=world-uPreviousCamera,pf=normalize(uPreviousTarget-uPreviousCamera),pr=normalize(cross(pf,vec3(0,1,0))),pu=cross(pr,pf);float z=dot(prev,pf);vec2 hp=vec2(dot(prev,pr)/(z*.48*uSize.x/uSize.y),dot(prev,pu)/(z*.48))*.5+.5;
if(z>.01&&all(greaterThan(hp,vec2(0)))&&all(lessThan(hp,vec2(1)))){hist=texture(uHistory,hp);vec4 hd=texture(uHistoryInfo,hp);float valid=1.-smoothstep(.25+.03*info.x,.85+.09*info.x,abs(hd.x-length(prev)));valid*=1.-smoothstep(.035,.25,abs(hist.a-now.a));vec3 margin=(high-low)*.08+vec3(.003);hist.rgb=clamp(hist.rgb,low-margin,high+margin);weight=.86*valid;}}
O=vec4(mix(now.rgb,hist.rgb,weight),now.a);D=info;}`;
const DISPLAY=`#version 300 es
precision highp float;uniform sampler2D uImage;uniform vec2 uSize,uScreen;uniform float uExposure,uHdr;out vec4 O;
void main(){vec2 uv=gl_FragCoord.xy/uScreen;vec4 center=texture(uImage,uv);vec3 sum=center.rgb*4.;float w=4.;for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){if(x==0&&y==0)continue;vec4 s=texture(uImage,uv+vec2(x,y)/uSize);float a=exp(-abs(s.a-center.a)*24.)*.34;sum+=s.rgb*a;w+=a;}vec3 c=sum/w;if(uHdr<.5)c=c/max(1.-c,vec3(.001));c=max(c*uExposure,0.);c=(c*(2.51*c+.03))/(c*(2.43*c+.59)+.14);O=vec4(pow(clamp(c,0.,1.),vec3(1./2.2)),1.);}`;
let prog,resolve,display;try{prog=program(FS);resolve=program(RESOLVE);display=program(DISPLAY);}catch(e){fail(e,'shaders');return;}gl.bindVertexArray(gl.createVertexArray());
const cache=new Map();function loc(p,n){let key=p===prog?'m':p===resolve?'r':'d';key+=n;if(!cache.has(key))cache.set(key,gl.getUniformLocation(p,n));return cache.get(key);}const f=(p,n,v)=>gl.uniform1f(loc(p,n),v),i=(p,n,v)=>gl.uniform1i(loc(p,n),v),v2=(p,n,a,b)=>gl.uniform2f(loc(p,n),a,b),v3=(p,n,a)=>gl.uniform3fv(loc(p,n),a),v4=(p,n,a)=>gl.uniform4fv(loc(p,n),a);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),normal=v=>{const l=Math.hypot(...v)||1;return v.map(x=>x/l);},keys=['hour','density','count','wind','direction','exposure','detail','rain','fog','humidity','instability','sunlight','skylight','scatter','haze','shear'];
const state={hour:14.1,density:.86,count:3,wind:12,direction:270,exposure:1,detail:.64,rain:0,fog:.03,humidity:68,instability:.45,snow:0,sunlight:1,skylight:1,scatter:1,haze:.22,shear:.18},target={...state};
let seed=4217,kind='Cu',weather='fair',time=0,playing=true,cycling=false,yaw=.14,pitch=-.055,distance=11.8,blend=1,job=0,last=performance.now(),dirty=true,historyValid=false,settled=0;
let windOffset=[0,0,0],previousWind=[0,0,0],previousCamera=[0,3,12],previousTarget=[0,3,0],groups=[],oldGroups=[],pending=null,pendingLight=null,shadowDims=[128,72,96],lastShadowData=null,lightRevision=0,lightBusy=false,shadowSun=null;
const min=[-19,-1,-16],max=[19,13,16],dims=innerWidth<650?[160,96,128]:[256,144,192];
const presets={fair:{kind:'Cu',density:.86,count:3,rain:0,fog:.03,humidity:68,instability:.45,snow:0},coast:{kind:'Sc',density:.70,count:6,rain:.04,fog:.12,humidity:83,instability:.22,snow:0},mountain:{kind:'Cu',density:.80,count:5,rain:.07,fog:.44,humidity:94,instability:.30,snow:0},rain:{kind:'Ns',density:1.12,count:7,rain:.70,fog:.20,humidity:97,instability:.18,snow:0},storm:{kind:'Cb',density:1.05,count:4,rain:.80,fog:.12,humidity:94,instability:.98,snow:0},rainbow:{kind:'Cu',density:.65,count:3,rain:.42,fog:.05,humidity:82,instability:.25,snow:0,hour:17.5},snow:{kind:'St',density:.72,count:6,rain:0,fog:.32,humidity:91,instability:.1,snow:1},high:{kind:'Ci',density:.5,count:6,rain:0,fog:.02,humidity:50,instability:.12,snow:0}};
const descriptions={fair:'层叠云峰、柔软边缘，云内冷暖光随时刻连续变化。',coast:'海岸湿流与低层云胞，共享来风方向与真实时间步长。',mountain:'演示山体附近的解析抬升与雾，保留云水连续过渡。',rain:'阴云、雨幕与湿润地表。光照控制仍然独立可调。',storm:'不同发展高度的对流云塔，顶部扩散、雨幕与内部闪光。',rainbow:'彩虹遵循反太阳方向，色带随日照角度变化。',snow:'低云、雪花与雾共同降低能见度。',high:'高空细长冰云，保留细丝与透光变化。'};
function set3D(tex,data,size,isNoise=false){gl.bindTexture(gl.TEXTURE_3D,tex);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);for(const n of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,n,gl.CLAMP_TO_EDGE);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texImage3D(gl.TEXTURE_3D,0,isNoise?gl.RG8:gl.R8,...size,0,isNoise?gl.RG:gl.RED,gl.UNSIGNED_BYTE,data);}
const macro=gl.createTexture(),oldMacro=gl.createTexture(),noise=gl.createTexture(),shadowTex=gl.createTexture(),oldShadowTex=gl.createTexture();let lastData=new Uint8Array(dims[0]*dims[1]*dims[2]);set3D(macro,lastData,dims);set3D(oldMacro,lastData,dims);set3D(noise,new Uint8Array(64**3*2),[64,64,64],true);

function setShadow(tex,data,size){gl.bindTexture(gl.TEXTURE_3D,tex);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);for(const n of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,n,gl.CLAMP_TO_EDGE);if(hdr)gl.texImage3D(gl.TEXTURE_3D,0,gl.RG16F,...size,0,gl.RG,gl.FLOAT,data);else{const q=new Uint8Array(data.length);for(let k=0;k<q.length;k++)q[k]=Math.round(Math.min(1,data[k]/60)*255);gl.texImage3D(gl.TEXTURE_3D,0,gl.RG8,...size,0,gl.RG,gl.UNSIGNED_BYTE,q);}}
function solar(hour){const a=(hour-12)/12*Math.PI,l=Math.PI/6,s=normal([-Math.sin(a),Math.cos(l)*Math.cos(a),Math.sin(l)*Math.cos(a)]);return s[1]<0?s.map(x=>-x):s;}

const worker=new Worker(new URL('field-worker.js?v=060',baseURL));worker.onerror=e=>fail(e.message,'volume worker');let volumeReady=false,noiseReady=false;
function invalidate(){historyValid=false;settled=0;dirty=true;}
worker.onmessage=({data:d})=>{if(d.error){fail(d.error,'volume worker');return;}if(d.light){lightBusy=false;if(d.id===job)pendingLight=d;return;}if(d.noise){set3D(noise,d.data,[64,64,64],true);for(const n of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T,gl.TEXTURE_WRAP_R])gl.texParameteri(gl.TEXTURE_3D,n,gl.REPEAT);noiseReady=true;}else if(d.id===job){if(d.borderMax!==0||!d.supportSafe){fail('密度边界检查失败，候选未启用','boundary');return;}pending=d;}qa.ready=noiseReady&&volumeReady;};
function rebuild(){job++;loading.style.display='block';loading.textContent='生成三维密度数据…';worker.postMessage({id:job,kind,seed,count:Math.round(target.count),instability:target.instability,dims,min,max,sun:solar(target.hour)});}
function fitView(){if(weather==='rainbow'){yaw=1.56;pitch=-.045;distance=18.;}else if(kind==='Cb'){yaw=.16;pitch=-.045;distance=19.;}else if(kind==='Cu'){yaw=.14;pitch=-.055;distance=11.8;}else{yaw=.1;pitch=-.22;distance=20.;}invalidate();}
function outputs(){for(const k of keys){const e=$(k),v=target[k];e.value=v;e.nextElementSibling.textContent=k==='hour'?String(Math.floor(v)%24).padStart(2,'0')+':'+String(Math.round(v%1*60)%60).padStart(2,'0'):k==='wind'?Math.round(v)+'m/s':k==='direction'?Math.round(v)+'°':k==='humidity'?Math.round(v)+'%':k==='count'?Math.round(v):v.toFixed(2);}}
const params=new URLSearchParams(location.search),boot=window.WeatherMotherBoot||{};let bw=boot.weather||params.get('weather');if(bw&&presets[bw]){weather=bw;kind=presets[bw].kind;Object.assign(target,presets[bw]);$('weather').value=weather;$('kind').value=kind;$('mountains').checked=weather==='mountain';$('rainbow').checked=weather==='rainbow';fitView();}const bh=boot.hour??(params.has('hour')?Number(params.get('hour')):null);if(bh!==null&&Number.isFinite(bh))target.hour=clamp(bh,0,24);if(boot.seed!==undefined)seed=boot.seed>>>0;if(boot.quality)$('quality').value=boot.quality;if(boot.still||params.has('still')){playing=false;$('pause').textContent='继续演化';}Object.assign(state,target);$('description').textContent=descriptions[weather];
let debounce;for(const k of keys)$(k).oninput=e=>{target[k]=+e.target.value;outputs();invalidate();if(k==='count'||k==='instability'){clearTimeout(debounce);debounce=setTimeout(rebuild,160);}};
function setWeather(id){if(!presets[id])throw Error('Unknown weather: '+id);weather=id;kind=presets[id].kind;Object.assign(target,presets[id]);$('weather').value=id;$('kind').value=kind;$('description').textContent=descriptions[id];$('mountains').checked=id==='mountain';$('rainbow').checked=id==='rainbow';fitView();outputs();rebuild();}
function setKind(k){if(!Array.from($('kind').options).some(o=>o.value===k))throw Error('Unknown cloud kind: '+k);kind=k;$('kind').value=k;fitView();rebuild();}
$('weather').onchange=e=>setWeather(e.target.value);$('kind').onchange=e=>setKind(e.target.value);document.querySelectorAll('[data-hour]').forEach(b=>b.onclick=()=>{target.hour=+b.dataset.hour;outputs();invalidate();});
$('seed').onclick=()=>{seed=(seed+7919)>>>0;rebuild();};function pause(){playing=false;$('pause').textContent='继续演化';dirty=true;}function play(){playing=true;last=performance.now();$('pause').textContent='暂停演化';dirty=true;}$('pause').onclick=()=>playing?pause():play();$('reset').onclick=fitView;canvas.ondblclick=fitView;
$('match').onclick=()=>{const r=target.rain,h=target.humidity,n=target.instability;setWeather(r>.5?(n>.65?'storm':'rain'):h>88?'mountain':h>75?'coast':'fair');};$('cycle').onchange=e=>{cycling=e.target.checked;invalidate();};$('collapse').onclick=()=>{$('collapse').textContent=$('panel').classList.toggle('collapsed')?'+':'−';};for(const k of['mountains','aircraft','rainbow','quality'])$(k).onchange=invalidate;
addEventListener('resize',invalidate);addEventListener('visibilitychange',()=>{last=performance.now();invalidate();});
let dragging=false,px=0,py=0;canvas.onpointerdown=e=>{dragging=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!dragging)return;yaw-=(e.clientX-px)*.005;pitch=clamp(pitch+(e.clientY-py)*.004,-.28,1.25);px=e.clientX;py=e.clientY;dirty=true;settled=0;};canvas.onpointerup=()=>dragging=false;canvas.onpointercancel=()=>dragging=false;canvas.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance*Math.exp(e.deltaY*.001),2.5,50.);dirty=true;settled=0;},{passive:false});
let w=0,h=0,steps=144,sceneRT=null,historyA=null,historyB=null,gpuFence=null;function destroy(rt){if(rt){gl.deleteTexture(rt.c);gl.deleteTexture(rt.d);gl.deleteFramebuffer(rt.f);}}
function texture2D(){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,hdr?gl.RGBA16F:gl.RGBA8,w,h,0,gl.RGBA,hdr?gl.HALF_FLOAT:gl.UNSIGNED_BYTE,null);return t;}
function makeRT(){const c=texture2D(),d=texture2D(),f=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,c,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT1,gl.TEXTURE_2D,d,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1]);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Incomplete volume framebuffer');return{c,d,f};}
function resize(){const q=$('quality').value,scale=q==='ultra'?1:q==='fine'?.83:.64;steps=q==='ultra'?208:q==='fine'?144:96;const dpr=Math.min(devicePixelRatio||1,1.5),cw=Math.min(2200,Math.round(innerWidth*dpr)),ch=Math.round(innerHeight*cw/innerWidth);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch;}const nw=Math.max(2,Math.round(cw*scale)),nh=Math.max(2,Math.round(ch*scale));if(w===nw&&h===nh)return;w=nw;h=nh;destroy(sceneRT);destroy(historyA);destroy(historyB);sceneRT=makeRT();historyA=makeRT();historyB=makeRT();invalidate();qa.renderSize=[w,h];qa.steps=steps;qa.gpuVolumeBytes=lastData.byteLength*2+64**3*2;qa.renderTargetBytes=w*h*(hdr?8:4)*6;qa.shadowVolumeBytes=shadowDims.reduce((a,b)=>a*b,1)*4*2;}
function bind2(unit,t){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,t);}
let fpsStart=performance.now(),fpsFrames=0,renderTimes=[],lastSun=null;
function render(now){requestAnimationFrame(render);try{
if(gpuFence){if(gl.getSyncParameter(gpuFence,gl.SYNC_STATUS)!==gl.SIGNALED)return;gl.deleteSync(gpuFence);gpuFence=null;}
if(pending){const d=pending;pending=null;set3D(oldMacro,lastData,dims);set3D(macro,d.data,dims);shadowDims=d.shadowSize;setShadow(oldShadowTex,lastShadowData&&lastShadowData.length===d.tau.length?lastShadowData:d.tau,shadowDims);setShadow(shadowTex,d.tau,shadowDims);lastShadowData=d.tau;shadowSun=solar(target.hour);qa.shadowReady=true;lastData=d.data;oldGroups=groups;groups=d.groups;blend=volumeReady?0:1;volumeReady=true;qa.ready=noiseReady&&volumeReady;qa.borderInputMax=d.borderMax;qa.supportSafe=d.supportSafe;qa.cloudVolumeBytes=d.data.byteLength;qa.lobes=d.lobes;qa.groups=d.groups.length;qa.activeCloudKind=d.kind;qa.seed=d.seed;qa.voxelSpacingKm=d.spacing;loading.style.display='none';invalidate();}
if(pendingLight){const d=pendingLight;pendingLight=null;setShadow(shadowTex,d.tau,d.shadowSize);lastShadowData=d.tau;invalidate();}
let dt=Math.max(0,(now-last)/1000);last=now;if(!qa.ready)return;if(playing&&!document.hidden){time+=dt;const a=state.direction*Math.PI/180;windOffset[0]+=-Math.sin(a)*state.wind*.001*dt;windOffset[2]+=Math.cos(a)*state.wind*.001*dt;if(cycling){target.hour=(target.hour+dt*.18)%24;outputs();}}
let changing=blend<1;if(window.__WEATHER_QA_SNAP__){Object.assign(state,target);blend=1;window.__WEATHER_QA_SNAP__=false;invalidate();}
for(const k of keys){let gap=target[k]-state[k];if(k==='hour')gap=((gap+36)%24)-12;if(k==='direction')gap=((gap+540)%360)-180;if(Math.abs(gap)>.001)changing=true;state[k]+=gap*(1-Math.exp(-dt*3));if(k==='hour')state[k]=(state[k]+24)%24;if(k==='direction')state[k]=(state[k]+360)%360;}
state.snow+=(target.snow-state.snow)*(1-Math.exp(-dt*3));blend=Math.min(1,blend+dt*.75);if(!playing&&!dirty&&!changing&&settled>=16)return;dirty=false;resize();const tick=performance.now();
const hourAngle=(state.hour-12)/12*Math.PI,lat=Math.PI/6,sun=normal([-Math.sin(hourAngle),Math.cos(lat)*Math.cos(hourAngle),Math.sin(lat)*Math.cos(hourAngle)]),elev=sun[1];let day=clamp((elev+.13)/.25,0,1);day=day*day*(3-2*day);const mass=1/(Math.max(elev,0)+.07),sunColor=[1.30*Math.exp(-(.012+.018*state.haze)*mass),1.27*Math.exp(-(.056+.021*state.haze)*mass),1.22*Math.exp(-(.145+.025*state.haze)*mass)];
const focus=kind==='Cb'?4.4:['Ci','Cc','Cs'].includes(kind)?6.2:['Ac','As'].includes(kind)?4.0:kind==='St'?1.45:kind==='Sc'?2.3:kind==='Ns'?3.:2.55,camera=[Math.sin(yaw)*Math.cos(pitch)*distance,Math.max(.18,focus+Math.sin(pitch)*distance),Math.cos(yaw)*Math.cos(pitch)*distance],cameraTarget=[0,focus,0];
const ls=solar(state.hour);if(!lightBusy&&blend>=1&&(!shadowSun||Math.hypot(...ls.map((v,k)=>v-shadowSun[k]))>.035)){lightBusy=true;shadowSun=ls;worker.postMessage({light:true,id:job,revision:++lightRevision,sun:ls});}
if(lastSun&&Math.hypot(...sun.map((v,k)=>v-lastSun[k]))>.0003)historyValid=false;if(changing)historyValid=false;gl.bindFramebuffer(gl.FRAMEBUFFER,sceneRT.f);gl.viewport(0,0,w,h);gl.useProgram(prog);
for(const[n,t]of[[0,macro],[1,oldMacro],[2,noise],[3,shadowTex],[4,oldShadowTex]]){gl.activeTexture(gl.TEXTURE0+n);gl.bindTexture(gl.TEXTURE_3D,t);}i(prog,'uMacro',0);i(prog,'uOld',1);i(prog,'uNoise',2);i(prog,'uShadow',3);i(prog,'uOldShadow',4);const activeGroups=blend<.999?[{lo:min,hi:max}]:groups;i(prog,'uGroups',activeGroups.length);gl.uniform3fv(loc(prog,'uLo[0]'),new Float32Array(activeGroups.flatMap(a=>a.lo)));gl.uniform3fv(loc(prog,'uHi[0]'),new Float32Array(activeGroups.flatMap(a=>a.hi)));v2(prog,'uRes',w,h);v3(prog,'uCamera',camera);v3(prog,'uTarget',cameraTarget);v3(prog,'uSun',sun);v3(prog,'uSunColor',sunColor);v3(prog,'uMoon',sun.map(v=>-v));v3(prog,'uWind',windOffset);v3(prog,'uMin',min);v3(prog,'uMax',max);
v4(prog,'uOpt',[state.density*(.78+state.humidity*.0032),state.detail,0,0]);v4(prog,'uWeather',[state.rain,state.fog,state.snow,state.humidity/100]);v4(prog,'uEffects',[$('mountains').checked?1:0,$('aircraft').checked?1:0,$('rainbow').checked?1:0,weather==='storm'?1:0]);v4(prog,'uLight',[state.sunlight,state.skylight,state.scatter,state.haze]);f(prog,'uBlend',blend);f(prog,'uTime',time);f(prog,'uDay',day);f(prog,'uExposure',state.exposure);f(prog,'uFrame',hdr?qa.frames%32:0);f(prog,'uShear',state.shear);f(prog,'uCloudBase',['Ci','Cc','Cs'].includes(kind)?5.5:1.2);f(prog,'uCloudTop',kind==='Cb'?9:['Ci','Cc','Cs'].includes(kind)?7:4.2);i(prog,'uSteps',steps);i(prog,'uKind',Array.from($('kind').options).findIndex(o=>o.value===kind));gl.drawArrays(gl.TRIANGLES,0,3);
gl.bindFramebuffer(gl.FRAMEBUFFER,historyB.f);gl.useProgram(resolve);bind2(3,sceneRT.c);bind2(4,sceneRT.d);bind2(5,historyA.c);bind2(6,historyA.d);i(resolve,'uCurrent',3);i(resolve,'uInfo',4);i(resolve,'uHistory',5);i(resolve,'uHistoryInfo',6);v2(resolve,'uSize',w,h);v3(resolve,'uCamera',camera);v3(resolve,'uTarget',cameraTarget);v3(resolve,'uPreviousCamera',previousCamera);v3(resolve,'uPreviousTarget',previousTarget);v3(resolve,'uWindDelta',windOffset.map((v,k)=>v-previousWind[k]));f(resolve,'uValid',hdr&&historyValid?1:0);gl.drawArrays(gl.TRIANGLES,0,3);
gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.useProgram(display);bind2(7,historyB.c);i(display,'uImage',7);v2(display,'uSize',w,h);v2(display,'uScreen',canvas.width,canvas.height);f(display,'uExposure',state.exposure);f(display,'uHdr',hdr?1:0);gl.drawArrays(gl.TRIANGLES,0,3);[historyA,historyB]=[historyB,historyA];previousCamera=camera;previousTarget=cameraTarget;previousWind=[...windOffset];lastSun=sun;historyValid=true;settled=changing?0:settled+1;
gpuFence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);gl.flush();qa.frames++;fpsFrames++;renderTimes.push(performance.now()-tick);if(renderTimes.length>120)renderTimes.shift();qa.renderSize=[w,h];qa.steps=steps;qa.currentHour=state.hour;qa.simulationTimeS=time;qa.windOffset=[...windOffset];qa.camera=[...camera];qa.temporalFrames=settled;qa.framebufferComplete=true;qa.lastGLerror=gl.getError();if(qa.lastGLerror)throw Error('WebGL error '+qa.lastGLerror);
if(now-fpsStart>=1000||qa.frames===1){qa.measuredFPS=Number((fpsFrames*1000/(now-fpsStart)).toFixed(1));fpsFrames=0;fpsStart=now;$('status').textContent='V0.6.0 · '+$('kind').selectedOptions[0].textContent+' · '+steps+' 步 · '+w+'×'+h+' · '+(playing?qa.measuredFPS+' FPS':'暂停检查');}
}catch(e){fail(e);}}
window.WeatherMother={qa,setWeather,setKind,set:(k,v)=>{if(keys.includes(k)&&Number.isFinite(v)){target[k]=clamp(v,+$(k).min,+$(k).max);outputs();if(k==='count'||k==='instability')rebuild();invalidate();}},setSeed:v=>{seed=v>>>0;rebuild();},setCamera:(y,p,d)=>{yaw=y;pitch=clamp(p,-.28,1.25);distance=clamp(d,2.5,50);invalidate();},pause,play,getState:()=>({...state,kind,weather,seed,playing,yaw,pitch,distance,blend}),reset:fitView};if(innerWidth<650){$('panel').classList.add('collapsed');$('collapse').textContent='+';}outputs();worker.postMessage({noise:true});rebuild();requestAnimationFrame(render);
})();
