/* Real-browser skin foundation QA. Screenshots still require human visual review. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');const {chromium}=require('playwright');
const URL=process.env.HUMAN_QA_URL||'http://127.0.0.1:8765/kaopu-unified-human-workbench/',OUT=process.env.SKIN_QA_OUT||'human-skin-qa-results';fs.mkdirSync(OUT,{recursive:true});
const report={schema:'human-skin-foundation-browser-qa/1',commit:process.env.GITHUB_SHA||null,url:URL,passed:false,visualAccepted:false,cases:[],errors:[],shaderErrors:[],screenshots:[]};
const hash=p=>crypto.createHash('sha256').update(Buffer.from(new Float32Array(p).buffer)).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1600,height:1200}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/shader|webgl|glsl/i.test(m.text()))report.shaderErrors.push(m.text());});
try{
 await page.goto(URL);await page.locator('#load-model').click();await page.waitForFunction(()=>window.fullCommonWorkbench?.diagnostics().ready,null,{timeout:360000});
 assert.equal(await page.evaluate(()=>typeof window.fullCommonWorkbench.skinReport),'function');
 const base=await page.evaluate(()=>window.fullCommonWorkbench.archive());report.initial=await page.evaluate(()=>window.fullCommonWorkbench.skinReport());assert.equal(report.initial.lipOnNonSkin,0);assert.ok(report.initial.counts.lips>100);assert.equal(report.initial.scanAssetsLoaded,false);assert.equal(report.initial.transmissionEnabled,false);
 const capture=async name=>{await page.locator('#canvas').screenshot({path:path.join(OUT,name+'.png')});report.screenshots.push(name+'.png');};
 const front=async()=>page.evaluate(()=>window.fullCommonWorkbench.view('face'));
 const side=async()=>{await front();const b=await page.locator('#canvas').boundingBox();await page.mouse.move(b.x+b.width*.68,b.y+b.height*.5);await page.mouse.down();await page.mouse.move(b.x+b.width*.68-b.height/4,b.y+b.height*.5,{steps:12});await page.mouse.up();};
 for(const [name,age]of[['child',1/3],['adult',2/3],['old',1]])for(const gender of[0,1]){
  await page.evaluate(({base,age,gender})=>{const a=structuredClone(base);a.state.anny.phenotypes.age=age;a.state.anny.phenotypes.gender=gender;window.fullCommonWorkbench.restore(a);window.fullCommonWorkbench.setSkin({enabled:true,layer:'beauty'});},{base,age,gender});
  await front();await capture(`${name}-gender-${gender}-front`);await side();await capture(`${name}-gender-${gender}-side`);
  const result=await page.evaluate(()=>({skin:window.fullCommonWorkbench.skinReport(),pixels:window.fullCommonWorkbench.pixelAudit(),p:Array.from(window.fullCommonWorkbench.positions()),state:window.fullCommonWorkbench.state()}));assert.equal(result.skin.lipOnNonSkin,0);assert.equal(result.skin.geometryUnchanged,true);assert.equal(result.pixels.error,0);assert.ok(result.pixels.colors>50);assert.deepEqual(result.skin.counts,report.initial.counts);report.cases.push({name,gender,geometryHash:hash(result.p),pixels:result.pixels,skin:result.skin});
 }
 assert.equal(new Set(report.cases.map(c=>c.geometryHash)).size,6,'New age/gender geometry must remain active');
 await page.evaluate(base=>window.fullCommonWorkbench.restore(base),base);await front();
 const before=await page.evaluate(()=>Array.from(window.fullCommonWorkbench.positions()));await page.evaluate(()=>window.fullCommonWorkbench.setSkin({enabled:false}));await capture('original-clay-comparison');assert.equal((await page.evaluate(()=>window.fullCommonWorkbench.skinReport())).enabled,false);await page.evaluate(()=>window.fullCommonWorkbench.setSkin({enabled:true}));assert.equal(hash(await page.evaluate(()=>Array.from(window.fullCommonWorkbench.positions()))),hash(before));report.toggleGeometryExact=true;
 for(const layer of['color','roughness','regions']){await page.evaluate(layer=>window.fullCommonWorkbench.setSkin({layer}),layer);await capture(layer+'-diagnostic');}await page.evaluate(()=>window.fullCommonWorkbench.setSkin({layer:'beauty'}));
 for(const source of['anny','mhr']){await page.evaluate(({base,source})=>{const a=structuredClone(base);a.state.owners.expression=source;if(source==='anny')a.state.anny.facialActions.jawOpen=.2;else{a.state.mhr.expression[24]=.2;a.state.mhr.expression[32]=.12;a.state.mhr.expression[33]=.12;}window.fullCommonWorkbench.restore(a);},{base,source});await front();await capture(source+'-light-open-front');await side();await capture(source+'-light-open-side');}
 // Preset switches must reuse the same surface fields and retain chosen skin.
 const presets=await page.evaluate(()=>window.fullCommonWorkbench.presets());for(const p of[presets[0],presets[17],presets[35],presets[0]]){await page.evaluate(id=>window.fullCommonWorkbench.applyPreset(id),p.id);assert.deepEqual((await page.evaluate(()=>window.fullCommonWorkbench.skinReport())).counts,report.initial.counts);}report.presetMappingStable=true;
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.fullCommonWorkbench.view('face'));await page.screenshot({path:path.join(OUT,'mobile-face.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);report.mobileNoOverflow=true;
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.shaderErrors,[]);report.passed=true;
}finally{fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify({passed:report.passed,visualAccepted:report.visualAccepted,cases:report.cases.length,errors:report.errors,shaderErrors:report.shaderErrors}));})().catch(e=>{report.failure=e.stack||String(e);fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2));console.error(e);process.exitCode=1});
