const canvas=document.getElementById('terrain'),fallback=document.getElementById('fallback'),fallbackImage=document.getElementById('fallbackImage'),statusEl=document.getElementById('status');
const [manifest,hydrology]=await Promise.all([
  fetch('manifest.json?v=3',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`manifest HTTP ${r.status}`);return r.json()}),
  fetch('hydrology.json?v=3',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`hydrology HTTP ${r.status}`);return r.json()})
]);
const truth=manifest.authoritative,viewer=manifest.viewer,worldWidth=truth.bounds[2]-truth.bounds[0],worldDepth=truth.bounds[3]-truth.bounds[1],minElevation=truth.elevationMeters.min,maxElevation=truth.elevationMeters.max,meanElevation=truth.elevationMeters.mean,elevationSpan=maxElevation-minElevation,meshCols=viewer.mesh[0],meshRows=viewer.mesh[1];
document.getElementById('textureStat').textContent=`${viewer.texture[0]} × ${viewer.texture[1]}`;
document.getElementById('hydroStat').textContent=`${manifest.hydrology.riverFeatureCount} 河段 / ${manifest.hydrology.lakeFeatureCount} 水面`;
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(`无法载入 ${src}`));img.src=src})}
function startFallback(message){canvas.hidden=true;fallback.hidden=false;statusEl.textContent=`${message} · 已切换二维预览`;let s=1,x=0,y=0,drag=false,px=0,py=0;function fit(){s=Math.min(innerWidth/fallbackImage.naturalWidth,innerHeight/fallbackImage.naturalHeight)*.92;x=0;y=0;draw()}function draw(){fallbackImage.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) scale(${s})`;fallbackImage.style.transformOrigin='center'}fallbackImage.onload=fit;if(fallbackImage.complete)fit();fallback.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;fallback.setPointerCapture(e.pointerId)});fallback.addEventListener('pointermove',e=>{if(!drag)return;x+=e.clientX-px;y+=e.clientY-py;px=e.clientX;py=e.clientY;draw()});fallback.addEventListener('pointerup',e=>{drag=false;fallback.releasePointerCapture(e.pointerId)});fallback.addEventListener('wheel',e=>{e.preventDefault();s=Math.max(.1,Math.min(12,s*Math.exp(-e.deltaY*.001)));draw()},{passive:false})}
const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,depth:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)startFallback('浏览器没有提供 WebGL2');else{try{await start3D(gl)}catch(e){console.error(e);startFallback(`三维载入失败：${e.message}`)}}
async function start3D(gl){
 statusEl.textContent='正在载入高精度显示纹理和水系知识…';
 const[heightImage,surfaceImage]=await Promise.all([loadImage('assets/height_rg16.png'),loadImage('assets/surface_satellite.png')]);
 const hc=document.createElement('canvas');hc.width=heightImage.width;hc.height=heightImage.height;const hctx=hc.getContext('2d',{willReadFrequently:true});hctx.drawImage(heightImage,0,0);const hp=hctx.getImageData(0,0,hc.width,hc.height).data;
 function dp(ix,iy){const x=Math.max(0,Math.min(hc.width-1,ix)),y=Math.max(0,Math.min(hc.height-1,iy)),i=(y*hc.width+x)*4;return((hp[i]<<8)|hp[i+1])/65535}
 function sh(u,v){const x=Math.max(0,Math.min(hc.width-1,u*(hc.width-1))),y=Math.max(0,Math.min(hc.height-1,v*(hc.height-1))),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(hc.width-1,x0+1),y1=Math.min(hc.height-1,y0+1),tx=x-x0,ty=y-y0,a=dp(x0,y0),b=dp(x1,y0),c=dp(x0,y1),d=dp(x1,y1);return a*(1-tx)*(1-ty)+b*tx*(1-ty)+c*(1-tx)*ty+d*tx*ty}
 function gy(x,z){const u=Math.max(0,Math.min(1,x/worldWidth+.5)),v=Math.max(0,Math.min(1,.5-z/worldDepth));return minElevation+sh(u,v)*elevationSpan-meanElevation}
 function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'shader');return s}
 function prog(vs,fs){const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'link');return p}
 const aniso=gl.getExtension('EXT_texture_filter_anisotropic')||gl.getExtension('MOZ_EXT_texture_filter_anisotropic')||gl.getExtension('WEBKIT_EXT_texture_filter_anisotropic');
 function tex(img,unit,anisotropic=false){const t=gl.createTexture();gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);if(anisotropic&&aniso)gl.texParameterf(gl.TEXTURE_2D,aniso.TEXTURE_MAX_ANISOTROPY_EXT,Math.min(8,gl.getParameter(aniso.MAX_TEXTURE_MAX_ANISOTROPY_EXT)));gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);return t}
 function lakeCanvas(){const w=1024,h=Math.round(w*worldDepth/worldWidth),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';for(const lake of hydrology.lakes||[]){for(const ring of lake.rings||[]){if(ring.length<3)continue;x.beginPath();ring.forEach((p,i)=>{const px=p[0]*w,py=p[1]*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fill()}}return c}
 const terrainVs=`#version 300 es
 precision highp float;layout(location=0)in vec2 aUV;uniform sampler2D uHeight;uniform mat4 uMVP;uniform vec2 uWorldSize;uniform float uMinElevation,uElevationSpan,uMeanElevation;out vec2 vUV;float dec(vec4 c){float hi=floor(c.r*255.0+.5),lo=floor(c.g*255.0+.5);return(hi*256.0+lo)/65535.0;}void main(){float e=uMinElevation+dec(texture(uHeight,aUV))*uElevationSpan;vec3 p=vec3((aUV.x-.5)*uWorldSize.x,e-uMeanElevation,(.5-aUV.y)*uWorldSize.y);vUV=aUV;gl_Position=uMVP*vec4(p,1.0);}`;
 const terrainFs=`#version 300 es
 precision highp float;in vec2 vUV;out vec4 outColor;uniform sampler2D uHeight,uSurface,uLake;uniform vec2 uTexel,uWorldSize;uniform float uMinElevation,uElevationSpan,uTime,uWaterColor,uWave,uRich;uniform int uMode;float dec(vec4 c){float hi=floor(c.r*255.0+.5),lo=floor(c.g*255.0+.5);return(hi*256.0+lo)/65535.0;}float h(vec2 uv){return dec(texture(uHeight,clamp(uv,vec2(0),vec2(1))))*uElevationSpan+uMinElevation;}vec3 elev(float t){vec3 a=vec3(.16,.34,.20),b=vec3(.38,.55,.25),c=vec3(.67,.57,.34),d=vec3(.64,.59,.54),e=vec3(.94,.94,.92);if(t<.22)return mix(a,b,t/.22);if(t<.54)return mix(b,c,(t-.22)/.32);if(t<.82)return mix(c,d,(t-.54)/.28);return mix(d,e,(t-.82)/.18);}float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){float ce=h(vUV),dx=(h(vUV+vec2(uTexel.x,0))-h(vUV-vec2(uTexel.x,0)))/(2.0*uTexel.x*uWorldSize.x),dz=(h(vUV+vec2(0,uTexel.y))-h(vUV-vec2(0,uTexel.y)))/(2.0*uTexel.y*uWorldSize.y);vec3 n=normalize(vec3(-dx,1,dz)),light=normalize(vec3(-.52,.80,.32));float dif=max(dot(n,light),0.0),illum=.60+.44*dif,t=clamp((ce-uMinElevation)/uElevationSpan,0.0,1.0);vec3 sat=texture(uSurface,vUV).rgb;float detail=(noise(vUV*37.0)-.5)*.10*uRich;sat*=1.0+detail;vec3 col=uMode==0?mix(sat,elev(t),.10):(uMode==1?sat:(uMode==2?elev(t):mix(vec3(.30,.35,.31),sat,.28)));col*=illum;float lake=texture(uLake,vUV).r;float waveA=sin(vUV.x*215.0+vUV.y*168.0+uTime*(.45+uWave*1.7));float waveB=sin(vUV.x*361.0-vUV.y*227.0-uTime*(.31+uWave*1.25));float wave=(waveA*.55+waveB*.45)*.5+.5;vec3 wc=mix(vec3(.035,.25,.42),vec3(.12,.61,.84),uWaterColor);wc+=vec3(.10,.16,.20)*wave*(.10+.30*uWave);col=mix(col,wc,lake*(uMode==3?.96:.82));float sparkle=pow(max(dot(normalize(vec3(.08*sin(uTime+vUV.x*80.0),1.0,.08*cos(uTime*.7+vUV.y*75.0))),light),0.0),18.0);col+=lake*sparkle*(.12+.35*uWave);outColor=vec4(clamp(col,0.0,1.0),1.0);}`;
 const terrainP=prog(terrainVs,terrainFs),TU=n=>gl.getUniformLocation(terrainP,n);gl.useProgram(terrainP);
 statusEl.textContent=`正在建立三维网格 ${meshCols} × ${meshRows}…`;await new Promise(r=>requestAnimationFrame(r));
 const verts=new Float32Array(meshCols*meshRows*2);let k=0;for(let r=0;r<meshRows;r++)for(let c=0;c<meshCols;c++){verts[k++]=c/(meshCols-1);verts[k++]=r/(meshRows-1)}const terrainCount=(meshCols-1)*(meshRows-1)*6,inds=new Uint32Array(terrainCount);k=0;for(let r=0;r<meshRows-1;r++)for(let c=0;c<meshCols-1;c++){const a=r*meshCols+c,b=a+1,cc=a+meshCols,d=cc+1;inds[k++]=a;inds[k++]=cc;inds[k++]=b;inds[k++]=b;inds[k++]=cc;inds[k++]=d}
 const terrainVao=gl.createVertexArray();gl.bindVertexArray(terrainVao);const tvb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,tvb);gl.bufferData(gl.ARRAY_BUFFER,verts,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);const tib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,tib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,inds,gl.STATIC_DRAW);
 tex(heightImage,0);tex(surfaceImage,1,true);tex(lakeCanvas(),2);gl.uniform1i(TU('uHeight'),0);gl.uniform1i(TU('uSurface'),1);gl.uniform1i(TU('uLake'),2);gl.uniform2f(TU('uWorldSize'),worldWidth,worldDepth);gl.uniform2f(TU('uTexel'),1/heightImage.width,1/heightImage.height);gl.uniform1f(TU('uMinElevation'),minElevation);gl.uniform1f(TU('uElevationSpan'),elevationSpan);gl.uniform1f(TU('uMeanElevation'),meanElevation);
 const riverVs=`#version 300 es
 precision highp float;layout(location=0)in vec3 aCenter;layout(location=1)in vec2 aNormal;layout(location=2)in float aSide;layout(location=3)in float aWidth;layout(location=4)in float aAlong;layout(location=5)in float aKind;uniform mat4 uMVP;uniform float uRiverScale;out float vSide;out float vAlong;out float vKind;void main(){vec3 p=aCenter;p.xz+=aNormal*aSide*aWidth*uRiverScale;vSide=aSide;vAlong=aAlong;vKind=aKind;gl_Position=uMVP*vec4(p,1.0);}`;
 const riverFs=`#version 300 es
 precision highp float;in float vSide;in float vAlong;in float vKind;out vec4 outColor;uniform float uTime,uWaterColor,uFlowSpeed;uniform int uMode;void main(){float edge=smoothstep(1.0,.74,abs(vSide));float phase=vAlong*.018-uTime*(.65+uFlowSpeed*3.6);float bands=.5+.5*sin(phase)+.22*sin(phase*2.3+1.1);bands=clamp(bands*.62,0.0,1.0);vec3 base=mix(vec3(.035,.27,.45),vec3(.11,.64,.88),uWaterColor);base+=vec3(.12,.18,.22)*bands*(.12+.28*uFlowSpeed);base=mix(base,vec3(.08,.50,.72),clamp(vKind*.18,0.0,.28));float alpha=edge*(uMode==3?.98:.82);outColor=vec4(clamp(base,0.0,1.0),alpha);}`;
 const riverP=prog(riverVs,riverFs),RU=n=>gl.getUniformLocation(riverP,n);
 function buildRivers(){const centers=[],normals=[],sides=[],widths=[],alongs=[],kinds=[],indices=[];let baseIndex=0;const kindValue={stream:0,canal:.55,river:1};for(const feature of hydrology.rivers||[]){const pts=(feature.points||[]).filter(p=>p.length>=2&&p[0]>-.05&&p[0]<1.05&&p[1]>-.05&&p[1]<1.05);if(pts.length<2)continue;const world=pts.map(p=>{const x=(p[0]-.5)*worldWidth,z=(.5-p[1])*worldDepth;return[x,gy(x,z)+2.5,z]});let along=0;for(let i=0;i<world.length;i++){const prev=world[Math.max(0,i-1)],next=world[Math.min(world.length-1,i+1)],tx=next[0]-prev[0],tz=next[2]-prev[2],len=Math.hypot(tx,tz)||1,nx=-tz/len,nz=tx/len;if(i>0)along+=Math.hypot(world[i][0]-world[i-1][0],world[i][2]-world[i-1][2]);const visualMin=feature.kind==='river'?42:(feature.kind==='canal'?28:14),half=Math.max(visualMin,(feature.widthMeters||visualMin)/2);for(const side of[-1,1]){centers.push(...world[i]);normals.push(nx,nz);sides.push(side);widths.push(half);alongs.push(along);kinds.push(kindValue[feature.kind]??0)}}for(let i=0;i<world.length-1;i++){const a=baseIndex+i*2,b=a+1,c=a+2,d=a+3;indices.push(a,c,b,b,c,d)}baseIndex+=world.length*2}return{centers:new Float32Array(centers),normals:new Float32Array(normals),sides:new Float32Array(sides),widths:new Float32Array(widths),alongs:new Float32Array(alongs),kinds:new Float32Array(kinds),indices:new Uint32Array(indices)}}
 const riverData=buildRivers(),riverVao=gl.createVertexArray();gl.bindVertexArray(riverVao);function attr(loc,size,data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0)}attr(0,3,riverData.centers);attr(1,2,riverData.normals);attr(2,1,riverData.sides);attr(3,1,riverData.widths);attr(4,1,riverData.alongs);attr(5,1,riverData.kinds);const rib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,rib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,riverData.indices,gl.STATIC_DRAW);
 function id(){const m=new Float32Array(16);m[0]=m[5]=m[10]=m[15]=1;return m}function persp(o,f,a,n,fa){const q=1/Math.tan(f/2),nf=1/(n-fa);o.fill(0);o[0]=q/a;o[5]=q;o[10]=(fa+n)*nf;o[11]=-1;o[14]=2*fa*n*nf;return o}function look(o,e,c,u){let zx=e[0]-c[0],zy=e[1]-c[1],zz=e[2]-c[2],ln=Math.hypot(zx,zy,zz)||1;zx/=ln;zy/=ln;zz/=ln;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx;ln=Math.hypot(xx,xy,xz)||1;xx/=ln;xy/=ln;xz/=ln;let yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;o[0]=xx;o[1]=yx;o[2]=zx;o[3]=0;o[4]=xy;o[5]=yy;o[6]=zy;o[7]=0;o[8]=xz;o[9]=yz;o[10]=zz;o[11]=0;o[12]=-(xx*e[0]+xy*e[1]+xz*e[2]);o[13]=-(yx*e[0]+yy*e[1]+yz*e[2]);o[14]=-(zx*e[0]+zy*e[1]+zz*e[2]);o[15]=1;return o}function mul(o,a,b){const rr=new Float32Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++)rr[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];o.set(rr);return o}
 let mode=0,params={waterColor:.58,riverWidth:.48,flowSpeed:.52,wave:.46,rich:.68},cam={yaw:-.61,pitch:.73,distance:104000,x:0,z:0},drag=false,pan=false,lx=0,ly=0;function overview(){cam={yaw:-.61,pitch:.73,distance:104000,x:0,z:0}}function top(){cam={yaw:0,pitch:1.555,distance:76000,x:0,z:0}}function low(){cam={yaw:-.80,pitch:.38,distance:41000,x:-9000,z:16000}}
 canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{drag=true;pan=e.button===2||e.shiftKey;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;if(pan){const s=Math.max(2,cam.distance*.00125),rx=Math.cos(cam.yaw),rz=-Math.sin(cam.yaw),fx=Math.sin(cam.yaw),fz=Math.cos(cam.yaw);cam.x-=dx*s*rx+dy*s*fx;cam.z-=dx*s*rz+dy*s*fz;cam.x=Math.max(-worldWidth/2,Math.min(worldWidth/2,cam.x));cam.z=Math.max(-worldDepth/2,Math.min(worldDepth/2,cam.z))}else{cam.yaw-=dx*.0055;cam.pitch=Math.max(.035,Math.min(1.555,cam.pitch-dy*.0047))}});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('wheel',e=>{e.preventDefault();cam.distance=Math.max(1.6,Math.min(240000,cam.distance*Math.exp(e.deltaY*.0011)))},{passive:false});
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=+b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))}));function bind(id,key,out){const el=document.getElementById(id),o=document.getElementById(out);el.addEventListener('input',()=>{params[key]=+el.value/100;o.textContent=el.value+'%'})}bind('waterColor','waterColor','waterColorOut');bind('riverWidth','riverWidth','riverWidthOut');bind('flowSpeed','flowSpeed','flowSpeedOut');bind('wave','wave','waveOut');bind('rich','rich','richOut');document.getElementById('overview').onclick=overview;document.getElementById('top').onclick=top;document.getElementById('low').onclick=low;document.getElementById('reset').onclick=()=>{overview();mode=0;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',+b.dataset.mode===0));const vals={waterColor:58,riverWidth:48,flowSpeed:52,wave:46,rich:68};for(const key in vals){const el=document.getElementById(key);el.value=vals[key];el.dispatchEvent(new Event('input'))}};document.getElementById('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();document.getElementById('screenshot').onclick=()=>{const a=document.createElement('a');a.download='KUNMING_DEM_TRUTH_FIRST_V003.png';a.href=canvas.toDataURL('image/png');a.click()};
 function resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(innerWidth*d)),h=Math.max(1,Math.floor(innerHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}const start=performance.now();function render(){resize();const ty=gy(cam.x,cam.z),cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),eye=[cam.x+cam.distance*cp*Math.sin(cam.yaw),ty+cam.distance*sp,cam.z+cam.distance*cp*Math.cos(cam.yaw)],near=Math.max(.05,Math.min(40,cam.distance*.00035)),far=Math.max(350000,cam.distance*4+250000),pr=id(),vw=id(),mvp=id();persp(pr,Math.PI/4,canvas.width/canvas.height,near,far);look(vw,eye,[cam.x,ty,cam.z],[0,1,0]);mul(mvp,pr,vw);gl.clearColor(.79,.85,.86,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);const time=(performance.now()-start)/1000;gl.useProgram(terrainP);gl.uniformMatrix4fv(TU('uMVP'),false,mvp);gl.uniform1i(TU('uMode'),mode);gl.uniform1f(TU('uTime'),time);gl.uniform1f(TU('uWaterColor'),params.waterColor);gl.uniform1f(TU('uWave'),params.wave);gl.uniform1f(TU('uRich'),params.rich);gl.bindVertexArray(terrainVao);gl.depthMask(true);gl.disable(gl.BLEND);gl.drawElements(gl.TRIANGLES,terrainCount,gl.UNSIGNED_INT,0);if(riverData.indices.length){gl.useProgram(riverP);gl.uniformMatrix4fv(RU('uMVP'),false,mvp);gl.uniform1f(RU('uRiverScale'),.42+params.riverWidth*2.25);gl.uniform1f(RU('uTime'),time);gl.uniform1f(RU('uWaterColor'),params.waterColor);gl.uniform1f(RU('uFlowSpeed'),params.flowSpeed);gl.uniform1i(RU('uMode'),mode);gl.bindVertexArray(riverVao);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawElements(gl.TRIANGLES,riverData.indices.length,gl.UNSIGNED_INT,0);gl.depthMask(true);gl.disable(gl.BLEND)}const eg=gy(Math.max(-worldWidth/2,Math.min(worldWidth/2,eye[0])),Math.max(-worldDepth/2,Math.min(worldDepth/2,eye[2]))),cl=Math.max(0,eye[1]-eg);statusEl.textContent=`真值优先 V003 · OSM 当代水系参考 · ${meshCols} × ${meshRows} 网格 · 镜头离地约 ${cl.toFixed(cl<100?1:0)} m`;requestAnimationFrame(render)}render();
}
