'use strict';
/* Isolated CI browser verification, not a physical-GPU/device certification. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),https=require('node:https'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const html=path.resolve(process.env.HAIYU_HTML||'kaopu-haiyu-workbench/r21/index.html');
const url='https://haihao0307.github.io/guilin-dem-pipeline/kaopu-haiyu-workbench/';
const out=path.resolve(process.env.HAIYU_QA_OUT||'haiyu-r21-browser-results');fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),expected=hash(fs.readFileSync(html));
const report={commit:process.env.GITHUB_SHA,expectedSha256:expected,source:'Official Playwright Chromium with SwiftShader software WebGL',physicalGPU:false,physicalMobileDevice:false,checks:[],errors:[],public:{},file:{}};
const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
function get(u){return new Promise((resolve,reject)=>{const req=https.get(u,r=>{let b=[];r.on('data',c=>b.push(c));r.on('end',()=>resolve({status:r.statusCode,body:Buffer.concat(b)}))});req.setTimeout(45000,()=>req.destroy(Error('HTTP timeout')));req.on('error',reject)})}
async function seek(p,frame){const count=Number(await p.locator('#axisLift').getAttribute('data-render-count'));await p.locator('#liftTime').fill(String(frame));await p.waitForFunction(({frame,count})=>Number(document.querySelector('#axisLift').dataset.renderCount)>count&&Math.abs(Number(document.querySelector('#axisLift').dataset.time)-frame*Math.PI/30)<1e-6,{frame,count})}
async function canvasHash(p){return p.locator('#liftCanvas').evaluate(c=>c.toDataURL('image/png')) .then(hash)}
async function pixelProbe(p){return p.locator('#liftCanvas').evaluate(c=>{const gl=c.getContext('webgl')||c.getContext('experimental-webgl');if(!gl)return {webgl:false};const b=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,b);let visible=0;for(let i=0;i<b.length;i+=4)if(b[i]+b[i+1]+b[i+2]>120)visible++;const ext=gl.getExtension('WEBGL_debug_renderer_info');return {webgl:true,depthTest:gl.isEnabled(gl.DEPTH_TEST),glError:gl.getError(),visiblePixels:visible,width:c.width,height:c.height,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'not-exposed'};})}
async function depthFixture(p){return p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;const r=window.HaiyuDepthRenderer.create(c);if(!r)throw Error('No fixture WebGL');const positions=[[10,10,-5],[54,10,-5],[32,56,-5],[10,10,5],[54,10,5],[32,56,5]];const options={project:p=>p,shade:(n,k)=>k==='front'?'#ff0000':'#0000ff',showSurface:true,showSpine:false,showSections:false,neutral:false};function draw(reverse){const faces=reverse?[[3,4,5],[0,1,2]]:[[0,1,2],[3,4,5]],faceKinds=reverse?['front','back']:['back','front'];r.draw({positions,faces,faceKinds,lines:[],spine:[],sections:[]},options);const b=new Uint8Array(4);r.gl.readPixels(32,32,1,1,r.gl.RGBA,r.gl.UNSIGNED_BYTE,b);return [...b]}return {normal:draw(false),reversed:draw(true),error:r.gl.getError()};})}
(async()=>{let browser;try{
 const deadline=Date.now()+12*60*1000;let response;while(Date.now()<deadline){response=await get(url);if(response.status===200&&hash(response.body)===expected)break;console.log('Waiting for Pages exact bytes',response.status,hash(response.body));await new Promise(r=>setTimeout(r,15000))}assert.equal(response.status,200);assert.equal(hash(response.body),expected);report.public={url,status:response.status,bytes:response.body.length,sha256:hash(response.body)};save();
 browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 for(const phase of ['file','public']){
  const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});const p=await context.newPage();const errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.text()))errors.push(m.text())});p.on('request',r=>requests.push(r.url()));
  await p.goto(phase==='file'?'file://'+html:url,{waitUntil:'load'});await p.waitForFunction(()=>document.querySelector('#axisLift')?.dataset.renderCount>0);
  assert.equal(await p.locator('meta[name="haiyu-build"]').getAttribute('content'),'R21-thorax-20261004');
  const probe=await pixelProbe(p);assert.equal(probe.webgl,true);assert.equal(probe.depthTest,true);assert.equal(probe.glError,0);assert.ok(probe.visiblePixels>1000);report[phase].pixelProbe=probe;
  const depth=await depthFixture(p);assert.deepEqual(depth.normal,[255,0,0,255]);assert.deepEqual(depth.reversed,depth.normal);assert.equal(depth.error,0);report[phase].depthOrderFixture=depth;
  for(const stage of [4,5]){
   await p.locator(`button[data-stage="${stage}"]`).click();await seek(p,0);const frames=[];for(const frame of [0,15,30,45]){await seek(p,frame);frames.push(await canvasHash(p));await p.locator('#liftCanvas').screenshot({path:path.join(out,`${phase}-stage${stage}-frame${frame}.png`)})}assert.ok(new Set(frames).size>=3);
   await p.locator('#liftMotion').fill('0');await seek(p,0);const frozen=await canvasHash(p);await seek(p,30);assert.equal(await canvasHash(p),frozen);await p.locator('#liftMotion').fill('100');
   await seek(p,0);await p.locator('#liftTop').screenshot({path:path.join(out,`${phase}-stage${stage}-axial-section.png`)});const sectionBefore=await p.locator('#liftTop').evaluate(c=>c.toDataURL());await p.locator('#liftSectionPosition').fill('60');await p.waitForTimeout(250);assert.notEqual(await p.locator('#liftTop').evaluate(c=>c.toDataURL()),sectionBefore);await p.locator('#liftSectionPosition').fill('42');await p.waitForTimeout(250);assert.equal(await p.locator('#liftSurface').count(),0);const before=await canvasHash(p),box=await p.locator('#liftCanvas').boundingBox();await p.mouse.move(box.x+box.width*.45,box.y+box.height*.4);await p.mouse.down();await p.mouse.move(box.x+box.width*.67,box.y+box.height*.48,{steps:12});await p.mouse.up();await p.waitForTimeout(250);assert.notEqual(await canvasHash(p),before);await p.locator('#liftCanvas').screenshot({path:path.join(out,`${phase}-stage${stage}-rotated.png`)});await p.locator('#liftView').click();
   const t0=Number(await p.locator('#axisLift').getAttribute('data-time'));await p.locator('#liftPlay').click();await p.waitForTimeout(1000);await p.locator('#liftPlay').click();const t1=Number(await p.locator('#axisLift').getAttribute('data-time'));assert.ok(t1>t0);const stopped=await canvasHash(p);await p.waitForTimeout(300);assert.equal(await canvasHash(p),stopped);
   report.checks.push({phase,stage,frameHashes:frames,motionFreeze:true,cameraRotation:true,playPause:true,renderer:(await p.locator('#axisLift').getAttribute('data-renderer')),renderMs:Number(await p.locator('#axisLift').getAttribute('data-render-ms'))});
  }
  for(const stage of [1,7,8,4]){await p.locator(`button[data-stage="${stage}"]`).click();if(stage===1)await p.frameLocator('#live').locator('canvas').waitFor();else await p.locator(stage===4?'#axisLift':'#experiment').waitFor({state:'visible'})}
  assert.equal(await p.locator('button[data-stage="6"]').count(),0);
  await p.locator('button[data-stage="9"]').click();await p.frameLocator('#live').locator('canvas').waitFor();await p.waitForFunction(()=>document.body.dataset.pending==='0');
  assert.equal(await p.locator('#title').textContent(),'06 新原式学习');assert.equal(await p.locator('#sourceVersion').textContent(),'新原式 / 2026.10.04');
  const originalFrames=[];for(const f of [1,60,120,180]){await p.locator('#timeline').fill(String(f));await p.waitForFunction(f=>document.body.dataset.pending==='0'&&Number(document.body.dataset.frame)===f,f);const time=Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'));assert.ok(Math.abs(time-f*Math.PI/120)<1e-10);const c=p.frameLocator('#live').locator('canvas');assert.equal(await c.getAttribute('width'),'400');assert.equal(await c.getAttribute('height'),'400');originalFrames.push(hash(await c.evaluate(c=>c.toDataURL())));await c.screenshot({path:path.join(out,`${phase}-source06-frame${f}.png`)});}
  assert.equal(new Set(originalFrames).size,4);report[phase].source06={sourceFrameStep:'PI/120',pointCount:20000,canvas:[400,400],frameHashes:originalFrames};
  await p.locator('button[data-stage="4"]').click();await seek(p,0);
const lit=await canvasHash(p);await p.locator('#liftLight').click();await p.waitForTimeout(100);assert.notEqual(await canvasHash(p),lit);await p.locator('#liftLight').click();await p.waitForTimeout(100);assert.equal(await canvasHash(p),lit);
  await p.setViewportSize({width:390,height:844});await p.locator('button[data-stage="5"]').click();await seek(p,15);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2));await p.screenshot({path:path.join(out,`${phase}-mobile-390x844.png`),fullPage:true});assert.equal((await pixelProbe(p)).webgl,true);report[phase].mobileViewport=true;
  const base=phase==='file'?'file://'+html:url;await p.goto(base+'?stage=4&frame=120',{waitUntil:'load'});await p.waitForFunction(()=>Math.abs(Number(document.querySelector('#axisLift')?.dataset.time)-4*Math.PI)<1e-7);assert.equal(await p.locator('button[data-stage="4"]').getAttribute('aria-pressed'),'true');await p.goto(base+'?module=source06&frame=60',{waitUntil:'load'});await p.waitForFunction(()=>document.body.dataset.stage==='9'&&document.body.dataset.pending==='0'&&document.body.dataset.frame==='60');assert.ok(Math.abs(Number(await p.frameLocator('#live').locator('body').getAttribute('data-time'))-Math.PI/2)<1e-10);report[phase].deepLinks={legacyStage4Frame120:true,newSource06Frame60:true};
  if(phase==='file'){const external=requests.filter(u=>/^https?:/.test(u));assert.deepEqual(external,[]);report.file.externalCoreRequests=external}
  assert.deepEqual(errors,[]);report[phase].pageErrors=errors;await context.close();save();
 }
 report.status='PASS';report.scope='Actual WebGL thoracic skeleton, true mesh cross-section, bone-only scope, exact original06 playback, exact public bytes and standalone file; not physical GPU/device or final morphology acceptance';save();console.log(JSON.stringify(report,null,2));
}catch(e){report.status='FAIL';report.errors.push(e.stack||String(e));save();console.error(e);process.exitCode=1}finally{if(browser)await browser.close()}})();
