const $=id=>document.getElementById(id),state={layout:'raw',fit:'measured',bend:1,width:1,spine:1,single:0,view:'orbit',az:-1.12,el:.30,source:false};let packet,proof={};
const colors={centrum:'#b7baa8','centrum-ring':'#e4e0c8',arch:'#ddc792',spine:'#f2e6c5','side-port':'#72b9b5',attachment:'#e6ae6c',source:'#cf8be0',gap:'#608a8b'};
function renderCanvas(canvas,view){const dpr=Math.min(devicePixelRatio,2),w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#151d1d';c.fillRect(0,0,w,h);const P=v=>project(v,view,state.az,state.el),all=[...packet.meshes.flatMap(m=>m.vertices),...packet.lines.flatMap(l=>l.points)].map(P);let min=[Infinity,Infinity],max=[-Infinity,-Infinity];for(const q of all)for(let i=0;i<2;i++){min[i]=Math.min(min[i],q[i]);max[i]=Math.max(max[i],q[i])}const span=max.map((v,i)=>v-min[i]),margin=view==='orbit'?42:24,scale=Math.min((w-2*margin)/span[0],(h-2*margin)/span[1]),mid=min.map((v,i)=>(v+max[i])/2),to=q=>[(q[0]-mid[0])*scale+w/2,(q[1]-mid[1])*scale+h/2],screen=v=>to(P(v));proof[canvas.id]={width:w,height:h,bounds:{min:to(min),max:to(max)},worldCount:packet.lines.reduce((s,l)=>s+l.points.length,0)};
 c.strokeStyle='#263130';c.lineWidth=1;for(let x=20;x<w;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=20;y<h;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}
 const faces=packet.meshes.flatMap(m=>m.faces.map(f=>({v:f.map(i=>m.vertices[i]),depth:f.reduce((sum,i)=>sum+P(m.vertices[i])[2],0)/3,ver:m.vertebra}))).sort((a,b)=>a.depth-b.depth);
 for(const f of faces){const q=f.v.map(screen),normal=cross(sub(f.v[1],f.v[0]),sub(f.v[2],f.v[0])),bright=.5+.45*Math.abs(dot(normal,[.3,.3,.7])/(Math.hypot(...normal)||1));c.beginPath();c.moveTo(...q[0]);c.lineTo(...q[1]);c.lineTo(...q[2]);c.closePath();c.fillStyle=`rgba(${Math.round(152*bright+40)},${Math.round(157*bright+40)},${Math.round(134*bright+40)},.97)`;c.fill();}
 const lines=[...packet.lines].sort((a,b)=>a.points.reduce((s,v)=>s+P(v)[2],0)/a.points.length-b.points.reduce((s,v)=>s+P(v)[2],0)/b.points.length);
 for(const l of lines){c.beginPath();l.points.map(screen).forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=colors[l.group]||'#ddd';c.lineWidth=l.width*(canvas.id==='mainCanvas'?1.5:1);c.lineJoin='round';c.lineCap='round';c.setLineDash(l.group==='gap'?[3,3]:[]);c.stroke();}c.setLineDash([]);
 for(const p of packet.points){if(p.group==='source'&&!state.source)continue;if(p.group==='source'&&state.single===0&&canvas.id!=='mainCanvas')continue;const q=screen(p.point);c.beginPath();c.arc(...q,p.group==='source'?3.1:2,0,2*Math.PI);c.fillStyle=colors[p.group]||'#aaa';c.fill();if(state.single&&state.source&&canvas.id==='mainCanvas'&&p.group==='source'){c.font='11px system-ui';c.fillText(p.label,q[0]+5,q[1]-5)}}
 if(canvas.id==='mainCanvas'&&!state.single){c.font='11px system-ui';c.fillStyle='#879d98';for(let i=0;i<packet.axis.length;i++){const q=screen(packet.axis[i]);c.fillText('v'+(i+2),q[0]-8,q[1]+25)}}
 // A scale bar is valid in orthographic screen coordinates; orbit is orthographic too.
 const mm=state.single?1:5;c.strokeStyle='#b7c8c0';c.lineWidth=2;c.beginPath();c.moveTo(25,h-24);c.lineTo(25+mm*scale,h-24);c.stroke();c.fillStyle='#879d98';c.font='11px system-ui';c.fillText(mm+' mm',25,h-32);
}
function chart(){const c=$('chart'),dpr=Math.min(devicePixelRatio,2),w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const keys=['length','height','half_width'],labels=['椎体长度','背腹高度','单侧半宽'],colors=['#e4c58e','#7dbbaf','#c18bd0'];keys.forEach((k,j)=>{const x0=j*w/3+18,x1=(j+1)*w/3-18,y0=30,y1=h-24;const all=SAMPLE.records.map(r=>r.params[k]),lo=Math.min(...all)*.94,hi=Math.max(...all)*1.04,xy=(r,v)=>[x0+r.s_in_sample*(x1-x0),y1-(v-lo)/(hi-lo)*(y1-y0)];ctx.strokeStyle='#647c74';ctx.setLineDash([4,3]);ctx.beginPath();SAMPLE.records.forEach((r,i)=>{const q=xy(r,r.sparse_params[k]);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle=colors[j];ctx.beginPath();SAMPLE.records.forEach((r,i)=>{const q=xy(r,r.params[k]);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke();for(const r of SAMPLE.records){ctx.fillStyle=colors[j];ctx.beginPath();ctx.arc(...xy(r,r.params[k]),2.2,0,6.3);ctx.fill()}ctx.font='11px system-ui';ctx.fillStyle='#c8d0c4';ctx.fillText(labels[j]+' / mm',x0,15);ctx.fillStyle='#779088';ctx.fillText('v2',x0,h-8);ctx.fillText('v12',x1-20,h-8);});}
function update(){packet=evaluate(SAMPLE,state);const r=inspect(packet);$('metric').textContent=`${state.single?'1椎':'11椎'} · ${r.triangles.toLocaleString()} 个椎体面 · ${r.lineVertices} 个曲线点`;$('modeLabel').textContent=state.single?'第 8 椎 · 局部骨形':state.layout==='raw'?'原坐标排列 · v2–v12 局部样本':'海羽主轴映射 · 设计变形';$('warning').hidden=state.fit!=='sparse';$('bend').disabled=state.layout!=='haiyu'||!!state.single;for(const [id,view]of [['mainCanvas',state.view],['xy','xy'],['xz','xz'],['yz','yz']])renderCanvas($(id),view);chart();$('design').textContent=state.layout==='haiyu'||state.width!==1||state.spine!==1?'当前含设计变形；不是实测姿态、运动范围或力学模型。':'尺寸取自实测点。灰色椎体、成对弓与棘是自写的低维示意。';document.body.dataset.ready='true';}
['layout','fit','single'].forEach(id=>$(id).onchange=()=>{state[id]=id==='single'?Number($(id).value):$(id).value;update()});['bend','width','spine'].forEach(id=>$(id).oninput=()=>{state[id]=Number($(id).value);$(id+'Value').textContent=Number($(id).value).toFixed(2);update()});$('source').onchange=()=>{state.source=$('source').checked;update()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(q=>q.classList.toggle('active',q===b));update()});$('reset').onclick=()=>{Object.assign(state,{layout:'raw',fit:'measured',bend:1,width:1,spine:1,single:0,view:'orbit',az:-1.12,el:.30,source:false});for(const id of['layout','fit','single','bend','width','spine'])$(id).value=state[id];for(const id of['bend','width','spine'])$(id+'Value').textContent='1.00';$('source').checked=false;update()};let drag=null;$('mainCanvas').onpointerdown=e=>{drag=[e.clientX,e.clientY,state.az,state.el];$('mainCanvas').setPointerCapture(e.pointerId)};$('mainCanvas').onpointermove=e=>{if(!drag)return;state.view='orbit';state.az=drag[2]+(e.clientX-drag[0])*.009;state.el=Math.max(-1.25,Math.min(1.25,drag[3]+(e.clientY-drag[1])*.008));update()};$('mainCanvas').onpointerup=$('mainCanvas').onpointercancel=()=>drag=null;window.addEventListener('resize',update);window.HaiyuRealSkeleton={getPacket:()=>packet,getState:()=>({...state}),getEvidence:()=>proof,getData:()=>SAMPLE};update();
