import fs from 'node:fs';
import{loadLocal}from'./load-model.mjs';import{PRESETS,createPresetState}from'../../ui/PresetCatalogueR2.mjs';import{AnimatedHuman}from'../AnimatedHuman.mjs';import{createBoxingRig,sampleBoxingPair,BOXING_VARIANTS}from'../Motion.mjs';
const{model,defaultState}=await loadLocal();const rows=[];
for(let pair=0;pair<18;pair++){
 const actors=[];for(let side=0;side<2;side++){const p=PRESETS[pair*2+side],st=createPresetState(p.id,defaultState);model.compute(st);const human=new AnimatedHuman(model,st),child=['child','teen'].includes(p.stage),rig=createBoxingRig({names:human.names,parents:human.rig.parents,restMatrices:human.rig.restMatrices,stature:human.height,child}),indices=[];for(let v=0;v<human.N;v++){let body=0;for(let n=0;n<human.range[v*2+1];n++){const k=(human.range[v*2]+n)*8,j=human.packed[k+3],w=human.packed[k+4];if(/spine|neck|head|eye/.test(human.names[j]))body+=w;}if(body>.65)indices.push(v);}actors.push({p,human,rig,child,indices});}
 const avg=actors.reduce((n,a)=>n+a.human.height,0)/2,child=actors[0].child,clearance=child?.12:.065,variant=BOXING_VARIANTS[pair%3],s0=sampleBoxingPair(0,pair,{child}),attacks=[];
 for(const e of variant.events){const peak=e.start+.43*(e.end-e.start),seconds=(((peak-s0.phaseOffset)%12+12)%12)/s0.speed,poses=actors.map(a=>{const p=a.rig.evaluate(seconds,{pairIndex:pair,fighter:actors.indexOf(a),child,opponentStature:actors[1-actors.indexOf(a)].human.height});a.human.animate(p.skinMatrices);return p;}),a=actors[e.actor],d=actors[1-e.actor],pose=poses[e.actor],opp=poses[1-e.actor],hand=e.kind==='cross'?'R':'L',wm=pose.posedMatrices[a.rig.index.get('wrist.'+hand)],km=pose.posedMatrices[a.rig.index.get('finger3-1.'+hand)],w=[3,7,11].map(k=>wm[k]+.75*(km[k]-wm[k])),gloveRadius=.081*1.25*a.human.height/1.75,targetRadius=gloveRadius+clearance;
  let sep=-Infinity,closestSide=Infinity,candidates=[],chosen=null;for(const index of d.indices){const p=d.human.sampleVertex(index),dy=p[2]+d.human.floorOffset-w[2]-a.human.floorOffset,dz=p[0]+w[0],off2=dy*dy+dz*dz;candidates.push(p);closestSide=Math.min(closestSide,Math.sqrt(off2));if(off2<=targetRadius*targetRadius){const required=-p[1]-w[1]+Math.sqrt(targetRadius*targetRadius-off2);if(required>sep){sep=required;chosen={vertex:index,worldHeight:p[2]+d.human.floorOffset,defenderFraction:(p[2]+d.human.floorOffset)/d.human.height};}}}
  if(!Number.isFinite(sep))sep=-w[1]-opp.posedMatrices[d.rig.index.get('head')][7]+gloveRadius+clearance;
  const defHead=opp.posedMatrices[d.rig.index.get('head')];attacks.push({actor:e.actor,kind:e.kind,counter:!!e.counter,cyclePeak:peak,seconds,gloveCenterNativeY:w[1],gloveCenterWorldZ:w[2]+a.human.floorOffset,actualWristNativeY:wm[7],actualWristWorldZ:wm[11]+a.human.floorOffset,opponentHeadNativeY:defHead[7],headOnlySeparation:-w[1]-defHead[7]+gloveRadius+clearance,recommendedSeparation:sep,gloveRadius,closestOrthogonalDistance:closestSide,target:chosen,candidates,w});
 }
 const recommended=Math.max(...attacks.map(a=>a.recommendedSeparation));for(const hit of attacks){const aa=actors[hit.actor],dd=actors[1-hit.actor];let nearest=Infinity;for(const p of hit.candidates){const dx=recommended+p[1]+hit.w[1],dy=p[2]+dd.human.floorOffset-hit.w[2]-aa.human.floorOffset,dz=p[0]+hit.w[0];nearest=Math.min(nearest,Math.hypot(dx,dy,dz));}hit.actualGloveGap=nearest-hit.gloveRadius;delete hit.candidates;delete hit.w;}
 const row={pairIndex:pair,ids:actors.map(a=>a.p.id),heights:actors.map(a=>a.human.height),variant:variant.id,child,oldSeparation:.64*avg,recommendedSeparation:recommended,recommendedHeightFactor:recommended/avg,desiredClearance:clearance,minPeakGloveGap:Math.min(...attacks.map(a=>a.actualGloveGap)),maxPeakGloveGap:Math.max(...attacks.map(a=>a.actualGloveGap)),attacks};rows.push(row);console.log(pair,variant.id,avg.toFixed(3),'old',row.oldSeparation.toFixed(3),'new',recommended.toFixed(3),'gaps',row.minPeakGloveGap.toFixed(3),row.maxPeakGloveGap.toFixed(3));for(const a of actors)a.human.dispose();
 fs.writeFileSync(new URL('../../research/boxing-r01/PAIR-RANGE-QA.json',import.meta.url),JSON.stringify({schema:'boxing-r01-pair-range/1',generatedAt:new Date().toISOString(),complete:rows.length===18,method:'Actual full-surface spine/neck/head vertices at all attack peaks, with current glove ellipsoid bounding spheres (0.081×1.25×height/1.75), centres at wrist→middle-knuckle interpolation 0.75; root separation selected to keep the closest attack clear. Defensive movement is included. Shorter opponents may target the torso.',rows},null,2)+'\n');
}
process.exit(0);
