import assert from 'node:assert/strict';
import fs from 'node:fs';
import {candidateDevelopmentStages,measuredMorphometricsFromSL,exactMeasuredAnchor,studyLocalGrowthRate,totalLengthFeedingEvidence,adultBound,lifecycleQuery,assertNoUnsafeBlend} from '../src/clownfish-evidence.mjs';

const profile = JSON.parse(fs.readFileSync(new URL('../profiles/amphiprion_ocellaris_evidence.json', import.meta.url), 'utf8'));
assert.equal(profile.evidenceTier, 'N1_SCIENTIFIC_NATURE');
assert.equal(profile.scope.adultAgeLengthCurveAvailable, false);
assert.equal(profile.adultBounds.maxTotalLengthMm, 110);
assert.equal(exactMeasuredAnchor(profile, 1).standardLengthMm.mean, 3.7);
assert.equal(exactMeasuredAnchor(profile, 30).standardLengthMm, null);
assert.equal(exactMeasuredAnchor(profile, 14).status, 'no_exact_measured_anchor');
assert.equal(studyLocalGrowthRate(profile, 5).standardLengthRateMmPerDay, 0.06);
assert.equal(studyLocalGrowthRate(profile, 12).standardLengthRateMmPerDay, 0.2);
assert.equal(studyLocalGrowthRate(profile, 25).status, 'unsupported_outside_reported_rate_window');
const m = measuredMorphometricsFromSL(profile, 3.7);
assert(Math.abs(m.eyeDiameterMm - 0.57) < 1e-12);
assert(Math.abs(m.snoutLengthMm - 0.47) < 1e-12);
const tl1 = totalLengthFeedingEvidence(profile, 1);
assert.equal(tl1.totalLengthMm, 4.1);
assert.equal(tl1.mouthGapeMm, 0.3);
const tl14 = totalLengthFeedingEvidence(profile, 14);
assert.equal(tl14.totalLengthMm, 7.9);
assert.equal(tl14.mouthGapeMm, 1.0);
assert.deepEqual(candidateDevelopmentStages(profile, 6).map(s=>s.stage), [2,3,4]);
assert.deepEqual(candidateDevelopmentStages(profile, 18).map(s=>s.stage), [6,7]);
const q = lifecycleQuery(profile, {ageDph:6});
assert(q.stageCandidates.length === 3);
assert(q.featureTiming.some(f=>f.feature==='pelvic_fin'));
assert(q.behaviorEvidence.some(b=>b.behavior.includes('near_surface')));
assert(q.behaviorEvidence.some(b=>b.behavior.includes('close_to_bottom')));
const bound = adultBound(profile);
assert.equal(bound.status, 'adult_bound_not_age_curve');
assert.equal(bound.maxTotalLengthMm, 110);
const gate = assertNoUnsafeBlend(profile);
assert.equal(gate.safeForFullAgeLengthInterpolation, false);
assert(gate.unresolvedConflicts.some(c=>c.id==='30DPH_STANDARD_LENGTH_CONFLICT'));
console.log('Clownfish evidence R02: 22 assertions passed; unsafe full-lifecycle interpolation remains blocked');