/* R19 controls and software triangle renderer. Geometry comes only from HaiyuAxisLift. */
(()=>{'use strict';
const by=id=>document.getElementById(id),main=by('liftCanvas'),panel=by('axisLift'),TAU=Math.PI*2;
const state={active:false,kind:'multifrequency',t:0,playing:false,yaw:.63,pitch:.28,zoom:1,showSpine:true,showSections:true,showSurface:true,neutral:false,dirty:true,geometryDirty:true,packet:null,last:0,drag:null};
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n)},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const params=()=>({thickness:Number(by('liftThickness').value)/100,depth:Number(by('liftDepth').value)/100,detail:.5,motion:Number(by('liftMotion').value)/100});
const warm=norm([-.55,.7,.6]),cool=norm([.6,.25,-.75]);
function transform(p,view){const[x,y,z]=p;if(view==='top')return[x,z,y];if(view==='front')return[x,y,z];const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch),a=x*cy+z*sy,b=-x*sy+z*cy;return[a,y*cp-b*sp,y*sp+b*cp]}
function makeProjector(packet,view,w,h){const pts=packet.positions.map(p=>transform(p,view));let loX=Infinity,hiX=-Infinity,loY=Infinity,hiY=-Infinity;for(const p of pts){loX=Math.min(loX,p[0]);hiX=Math.max(hiX,p[0]);loY=Math.min(loY,p[1]);hiY=Math.max(hiY,p[1])}const dx=Math.max(1e-4,hiX-loX),dy=Math.max(1e-4,hiY-loY),scale=Math.min(w*.82/dx,h*.77/dy)*state.zoom,cx=(loX+hiX)/2,cy=(loY+hiY)/2;return p=>{const a=transform(p,view);return[w/2+(a[0]-cx)*scale,h*.5-(a[1]-cy)*scale,a[2]]}}
function color(normal,kind,view){const n=norm(normal);if(kind==='spine')return state.neutral?'#d8b16f':'#e4af61';if(state.neutral){const v=Math.round(110+90*Math.abs(transform(n,view)[2]));return `rgb(${v},${v},${v})`}const a=Math.max(0,dot(n,warm)),b=Math.max(0,dot(n,cool)),back=.18*Math.max(0,-dot(n,warm)),base=kind?.includes('fin')?[122,170,180]:kind?.includes('left')?[168,170,151]:[139,161,163],light=.25+.58*a+.44*b+back;return`rgb(${Math.round(base[0]*light+39*a)},${Math.round(base[1]*light+13*a+12*b)},${Math.round(base[2]*light+46*b)})`}
function draw(target,view){const ctx=target.getContext('2d'),w=target.width,h=target.height,packet=state.packet,project=makeProjector(packet,view,w,h),screen=packet.positions.map(project);ctx.fillStyle=state.neutral?'#111315':'#090f11';ctx.fillRect(0,0,w,h);if(!state.neutral){const g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,'rgba(150,75,34,.14)');g.addColorStop(.5,'rgba(15,20,22,0)');g.addColorStop(1,'rgba(42,90,143,.18)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
const ordered=packet.faces.map((ids,i)=>({ids,i,z:ids.reduce((sum,k)=>sum+screen[k][2],0)/3})).sort((a,b)=>a.z-b.z);for(const f of ordered){const kind=packet.faceKinds[f.i]||'body';if(kind==='spine'?!state.showSpine:!state.showSurface)continue;const[a,b,c]=f.ids.map(i=>screen[i]),[x,y,z]=f.ids.map(i=>packet.positions[i]),n=cross(sub(y,x),sub(z,x));if(Math.hypot(...n)<1e-12)continue;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(c[0],c[1]);ctx.closePath();ctx.fillStyle=color(n,kind,view);ctx.fill()}
function line(points,stroke,width){if(!points?.length)return;ctx.beginPath();points.forEach((p,i)=>{const a=project(p);i?ctx.lineTo(a[0],a[1]):ctx.moveTo(a[0],a[1])});ctx.strokeStyle=stroke;ctx.lineWidth=width*(view==='orbit'?1:.7);ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke()}
if(state.showSections)for(const s of packet.sections||[])line(Array.isArray(s)?s:s.points,'rgba(180,211,217,.42)',1.0);
for(const l of packet.lines||[]){if(l.kind==='spine'||l.kind==='axis')continue;line(l.points,l.color||'rgba(191,213,206,.38)',Math.max(.55,Math.min(1.2,l.width||.7)))}
if(state.showSpine)line(packet.spine,state.neutral?'#d8b16f':'#ffd58d',view==='orbit'?2.3:1.6);
ctx.fillStyle='#a8b5b1';ctx.font=(view==='orbit'?'18':'16')+'px system-ui';ctx.fillText(view==='orbit'?'中轴 → 左右立体展开':view==='front'?'同一对象 · X/Y':'同一对象 · X/Z',16,28);if(view==='orbit'){ctx.font='16px system-ui';const s=state.neutral?'中性结构检查':'暖主光 + 冷辅光';ctx.fillText(s,w-ctx.measureText(s).width-16,28)}}
function render(){if(!state.active)return;if(state.geometryDirty||!state.packet){state.packet=window.HaiyuAxisLift.evaluate(state.kind,state.t,params());state.geometryDirty=false}draw(main,'orbit');draw(by('liftSide'),'front');draw(by('liftTop'),'top');const p=state.packet;panel.dataset.kind=state.kind;panel.dataset.time=state.t;panel.dataset.vertices=p.positions.length;panel.dataset.triangles=p.faces.length;panel.dataset.native3d='true';panel.dataset.cameraAffectsGeneration='false';by('liftStatus').textContent=`中轴立体候选 · ${p.positions.length.toLocaleString()} 顶点 / ${p.faces.length.toLocaleString()} 三角面`;by('liftTime').value=Math.round(state.t/(16*Math.PI)*480);by('liftClock').textContent='t = '+state.t.toFixed(3)+' / '+(16*Math.PI).toFixed(3);by('liftState').textContent=state.playing?'运行中':'暂停';by('liftPlay').textContent=state.playing?'暂停小样':'播放小样';state.dirty=false}
function on(id,type,fn){by(id).addEventListener(type,fn)}
on('liftPlay','click',()=>{state.playing=!state.playing;state.last=performance.now();state.dirty=true});on('liftReset','click',()=>{state.t=0;state.playing=false;state.geometryDirty=state.dirty=true});on('liftView','click',()=>{state.yaw=.63;state.pitch=.28;state.zoom=1;state.dirty=true});on('liftTime','input',e=>{state.t=Number(e.target.value)/480*16*Math.PI;state.playing=false;state.geometryDirty=state.dirty=true});
for(const[id,key]of[['liftSpine','showSpine'],['liftSections','showSections'],['liftSurface','showSurface']])on(id,'click',()=>{state[key]=!state[key];by(id).setAttribute('aria-pressed',String(state[key]));state.dirty=true});on('liftLight','click',()=>{state.neutral=!state.neutral;by('liftLight').textContent=state.neutral?'中性检查':'冷暖光';by('liftLight').setAttribute('aria-pressed',String(!state.neutral));state.dirty=true});for(const id of['liftThickness','liftDepth','liftMotion'])on(id,'input',()=>{by(id+'Value').textContent=(Number(by(id).value)/100).toFixed(2);state.geometryDirty=state.dirty=true});
main.addEventListener('pointerdown',e=>{state.drag=[e.clientX,e.clientY,state.yaw,state.pitch];main.setPointerCapture(e.pointerId);main.style.cursor='grabbing'});main.addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw=state.drag[2]+(e.clientX-state.drag[0])*.008;state.pitch=clamp(state.drag[3]+(e.clientY-state.drag[1])*.008,-1.4,1.4);state.dirty=true});for(const ev of['pointerup','pointercancel','lostpointercapture'])main.addEventListener(ev,()=>{state.drag=null;main.style.cursor='grab'});main.addEventListener('wheel',e=>{e.preventDefault();state.zoom=clamp(state.zoom*Math.exp(-e.deltaY*.001),.55,2.4);state.dirty=true},{passive:false});
on('liftExport','click',()=>{const data={schema:'KAOPU.Haiyu.axis-lift/1',version:'R19',kind:state.kind,time:state.t,parameters:params(),diagnostics:state.packet?.diagnostics,source:'Preserved q,d,c scalar relationships from R17/R18 author-source.txt; new thickness/depth are candidate extensions',cameraAffectsGeneration:false};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='海羽-R19-'+state.kind+'-三维谱.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
window.HaiyuLiftUI={setActive(value,kind,initialTime=0){state.active=!!value;state.playing=false;state.drag=null;if(!value)return;state.kind=kind;state.t=Number.isFinite(initialTime)?((initialTime%(16*Math.PI))+(16*Math.PI))%(16*Math.PI):0;state.yaw=.63;state.pitch=.28;state.zoom=1;state.geometryDirty=state.dirty=true;by('liftTitle').textContent=kind==='biomotion'?'05 仿生游动 · 中轴立体':'04 多频羽化 · 中轴立体';by('liftFormula').textContent='材料地址：y 沿中轴，u ∈ [−1,1] 向左右展开。\nk=(5+sin(y))·u；e=y/5−11；d=hypot(k,e)/0.6−6。\nq=99+d·sin(t−d)+y/23·k·(3sin(e)+e·sin(2e)+sin(4d))。\nc=d/4−t/8'+(kind==='biomotion'?' + cos(t+e)/9':'')+'。\n三维化：相同材料地址 → 中轴 / 局部架 → 有厚度的闭合截面；相机最后观察。\n纵向按材料地址 y 单调重排，避免直接沿原二维回折曲线扫掠；q/d/c 作为截面宽度、波动与扭转的驱动。\n新增厚度、截面深度为可替换候选；不声称压平后等于原二维投影。';render()}};
function tick(now){if(state.active&&!document.hidden){if(state.playing&&now-state.last>42){const dt=Math.min(.08,(now-state.last)/1000);state.t=(state.t+dt*2*Math.PI)%(16*Math.PI);state.last=now;state.geometryDirty=state.dirty=true}if(state.dirty)render()}else state.last=now;requestAnimationFrame(tick)}requestAnimationFrame(tick);
})();
