// Source-specific geometric fitting, not an inferred geological process or a generic rock recipe.
import {gate,dot,cross,unit,sub,clamp,normals} from './source.mjs';
const key=(x,y,z)=>x+','+y+','+z,round=x=>Number(x.toPrecision(10));
function frame(n){const u=unit(cross(Math.abs(n[1])<.85?[0,1,0]:[1,0,0],n));return [u,cross(n,u)]}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let j=0;j<n;j++){let k=j;for(let i=j+1;i<n;i++)if(Math.abs(M[i][j])>Math.abs(M[k][j]))k=i;if(Math.abs(M[k][j])<1e-12)return Array(n).fill(0);[M[j],M[k]]=[M[k],M[j]];let q=M[j][j];for(let k=j;k<=n;k++)M[j][k]/=q;for(let i=0;i<n;i++)if(i!==j){q=M[i][j];for(let k=j;k<=n;k++)M[i][k]-=q*M[j][k]}}return M.map(r=>r[n])}
export function facts(mesh){const p=mesh.positions,ix=mesh.indices,nf=ix.length/3,c=new Float64Array(nf*3),n=new Float64Array(nf*3),a=new Float64Array(nf);let area=0,bad=0;for(let f=0;f<nf;f++){const ids=[ix[f*3]*3,ix[f*3+1]*3,ix[f*3+2]*3],pa=p.subarray(ids[0],ids[0]+3),pb=p.subarray(ids[1],ids[1]+3),pc=p.subarray(ids[2],ids[2]+3),v=cross(sub(pb,pa),sub(pc,pa)),l=Math.hypot(...v);if(l<1e-16){bad++;continue}a[f]=l/2;area+=l/2;for(let k=0;k<3;k++){c[f*3+k]=(pa[k]+pb[k]+pc[k])/3;n[f*3+k]=v[k]/l}}gate(area>0,'源表面面积为零');return {c,n,a,area,bad}}
function surfaceSamples(mesh,original,cell){const centers=[],ns=[],areas=[],source=[],p=mesh.positions,ix=mesh.indices;for(let f=0;f<ix.length/3;f++){if(!original.a[f])continue;const ids=[ix[f*3]*3,ix[f*3+1]*3,ix[f*3+2]*3],a=p.subarray(ids[0],ids[0]+3),b=p.subarray(ids[1],ids[1]+3),c=p.subarray(ids[2],ids[2]+3),u=sub(b,a),v=sub(c,a),long=Math.max(Math.hypot(...u),Math.hypot(...v),Math.hypot(...sub(b,c))),n=Math.max(1,Math.ceil(long/(cell*.9)));gate(n<=256,'单个源面过大，无法在本轮预算中测量');function add(x,y){centers.push(...a.map((z,k)=>z+x*u[k]+y*v[k]));ns.push(...original.n.subarray(f*3,f*3+3));areas.push(original.a[f]/(n*n));source.push(f)}for(let i=0;i<n;i++)for(let j=0;j<n-i;j++){add((i+1/3)/n,(j+1/3)/n);if(i+j<n-1)add((i+2/3)/n,(j+2/3)/n)}gate(source.length<2000000,'源面积采样超预算')}return {c:new Float64Array(centers),n:new Float64Array(ns),a:new Float64Array(areas),source:new Uint32Array(source),area:original.area,bad:original.bad};}
export function extract(mesh,identity,colors=null,progress=()=>{}){
 const b=mesh.bounds,dim=sub(b.max,b.min),long=Math.max(...dim);gate(long>0&&dim.every(x=>x>0),'原件需要三维厚度');const cell=long/32,spacing=long/192,original=facts(mesh),f=surfaceSamples(mesh,original,cell),groups=new Map(),nf=f.a.length,facePatch=new Int32Array(nf).fill(-1);progress(.10,'测量原件面方向与空间关系');
 for(let i=0;i<nf;i++){const w=f.a[i];if(!w)continue;const c=Array.from(f.c.subarray(i*3,i*3+3)),n=Array.from(f.n.subarray(i*3,i*3+3)),q=c.map((x,k)=>Math.floor((x-b.min[k])/cell)),axis=Math.abs(n[0])>Math.abs(n[1])?(Math.abs(n[0])>Math.abs(n[2])?0:2):(Math.abs(n[1])>Math.abs(n[2])?1:2),id=key(...q)+':'+(axis*2+(n[axis]>0?1:0));let g=groups.get(id);if(!g){g={id:groups.size,q,c:[0,0,0],n:[0,0,0],area:0,faces:[],color:[0,0,0],cw:0};groups.set(id,g)}g.area+=w;g.faces.push(i);for(let k=0;k<3;k++){g.c[k]+=c[k]*w;g.n[k]+=n[k]*w;if(colors&&colors[f.source[i]*3]>=0)g.color[k]+=colors[f.source[i]*3+k]*w}if(colors&&colors[f.source[i]*3]>=0)g.cw+=w;facePatch[i]=g.id}
 const patches=[];for(const g of groups.values()){const c=g.c.map(v=>v/g.area),n=unit(g.n),[u,v]=frame(n),A=Array.from({length:3},()=>[0,0,0]),rhs=[0,0,0];let variance=0;for(const i of g.faces){const d=Array.from(f.c.subarray(i*3,i*3+3),(x,k)=>(x-c[k])/cell),x=dot(d,u),y=dot(d,v),h=dot(d,n),a=[x*x,x*y,y*y],w=f.a[i];variance+=h*h*w;for(let k=0;k<3;k++){rhs[k]+=w*a[k]*h;for(let j=0;j<3;j++)A[k][j]+=w*a[k]*a[j]}}for(let k=0;k<3;k++)A[k][k]+=.01*g.area;const curve=g.faces.length>=6?solve(A,rhs).map(x=>clamp(x,-.7,.7)):[0,0,0];patches.push({c:c.map(round),n:n.map(round),q:g.q,k:curve.map(round),area:round(g.area),rms:round(Math.sqrt(variance/g.area)*cell),count:g.faces.length,color:g.cw?g.color.map(x=>round(x/g.cw)):null,region:-1})}
 gate(patches.length<=22000,'支持区超出分析预算；不自动抽减');const bins=new Map();patches.forEach((p,i)=>{const k=key(...p.q);if(!bins.has(k))bins.set(k,[]);bins.get(k).push(i)});const order=patches.map((p,i)=>i).sort((a,b)=>patches[b].area-patches[a].area||a-b),regions=[];
 for(const start of order){if(patches[start].region>=0)continue;const seed=patches[start],id=regions.length,stack=[start],members=[];seed.region=id;let area=0,c=[0,0,0],n=[0,0,0];while(stack.length){const i=stack.pop(),p=patches[i];members.push(i);area+=p.area;for(let k=0;k<3;k++){c[k]+=p.c[k]*p.area;n[k]+=p.n[k]*p.area}for(let z=-1;z<=1;z++)for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)for(const j of bins.get(key(p.q[0]+x,p.q[1]+y,p.q[2]+z))??[]){const t=patches[j];if(t.region>=0||dot(t.n,seed.n)<.93||Math.abs(dot(sub(t.c,seed.c),seed.n))>cell*.72||Math.hypot(...sub(t.c,p.c))>cell*1.9)continue;t.region=id;stack.push(j)}}c=c.map(x=>x/area);n=unit(n);const h=(c[1]-b.min[1])/dim[1],kind=h<.2?'基脚候选':n[1]>.55&&h<.85?'凸台候选':Math.abs(n[1])<.55?'主块面候选':'顶部 / 斜面候选';regions.push({id,kind,area:round(area),center:c.map(round),normal:n.map(round),count:members.length})}
 progress(.23,'提取分区与折边候选');const crease=edgeEvidence(mesh,original,cell),sorted=[...regions].sort((a,b)=>b.area-a.area||a.id-b.id),features=[];for(const kind of ['主块面候选','凸台候选','基脚候选','顶部 / 斜面候选'])for(const r of sorted.filter(x=>x.kind===kind).slice(0,kind==='主块面候选'?6:3))features.push({id:'F'+String(features.length+1).padStart(2,'0'),region:r.id,kind:r.kind,center:r.center,normal:r.normal,area:r.area,supportPatches:r.count});
 const recipe={schema:'landscape-mother/source-surface-field/1',version:'B1.0',source:{...identity,vertices:mesh.positions.length/3,triangles:mesh.indices.length/3,bounds:b,dimensions:dim},method:'area-weighted spatial/normal clustering, bounded quadratic oriented field, fixed-grid isosurface',coordinateUnit:'source unit; physical scale unverified',cell:round(cell),spacing:round(spacing),supportRadius:round(cell*2.05),patches,features,creases:crease.features,sourceFacts:{area:round(f.area),degenerateTriangles:f.bad,boundaryEdges:crease.boundary,nonManifoldEdges:crease.nonManifold,sharpEdgeCount:crease.count,creaseThresholdDeg:crease.threshold,regions:regions.length},color:{method:colors?'CPU source-image evidence to region mean colors; no images in fitted field':'unmeasured',measured:!!colors,textureInRenderer:false},limits:{sourceSpecificFit:true,geologicalProcessRecovered:false,crackWidthsAndDepthsVerified:false,photorealMaterialRecovered:false,variantFamilyApproved:false,unobservedBackFacesFilled:false},approvals:{truthApproved:false,visualApproved:false,productionReady:false}};return {recipe,facePatch,creaseLines:crease.lines};
}
function edgeEvidence(mesh,f,cell){const p=mesh.positions,ix=mesh.indices,edges=new Map(),weld=new Map(),wid=new Int32Array(p.length/3);for(let i=0;i<wid.length;i++){const k=key(p[i*3],p[i*3+1],p[i*3+2]);if(!weld.has(k))weld.set(k,weld.size);wid[i]=weld.get(k)}for(let i=0;i<ix.length;i+=3)for(let k=0;k<3;k++){const a=ix[i+k],b=ix[i+(k+1)%3],u=wid[a],v=wid[b],s=Math.min(u,v)+':'+Math.max(u,v);if(!edges.has(s))edges.set(s,{a,b,faces:[]});edges.get(s).faces.push(i/3)}const angles=[];let boundary=0,nonManifold=0;for(const e of edges.values()){if(e.faces.length===1){boundary++;continue}if(e.faces.length!==2){nonManifold++;continue}const [a,b]=e.faces;e.angle=Math.acos(clamp(dot(f.n.subarray(a*3,a*3+3),f.n.subarray(b*3,b*3+3)),-1,1))*180/Math.PI;angles.push(e.angle)}angles.sort((a,b)=>a-b);const threshold=clamp(angles[Math.floor(angles.length*.9)]??35,25,65),lines=[],chosen=[];for(const e of edges.values())if(e.angle>=threshold){const a=Array.from(p.subarray(e.a*3,e.a*3+3)),b=Array.from(p.subarray(e.b*3,e.b*3+3)),length=Math.hypot(...sub(a,b));if(length<cell*.07)continue;lines.push(...a,...b);chosen.push({a,b,angle:e.angle,length})}chosen.sort((a,b)=>b.length*b.angle-a.length*a.angle);const features=[];for(const e of chosen){const center=e.a.map((v,i)=>(v+e.b[i])/2);if(features.some(f=>Math.hypot(...sub(center,f.center))<cell*2))continue;features.push({id:'C'+String(features.length+1).padStart(2,'0'),kind:'折边 / 裂隙候选',center:center.map(round),direction:unit(sub(e.b,e.a)).map(round),edgeLength:round(e.length),angle:round(e.angle),width:null,depth:null,cause:null});if(features.length===16)break}return {features,lines:new Float32Array(lines),boundary,nonManifold,count:chosen.length,threshold:round(threshold)}}
export function validate(r){gate(r?.schema==='landscape-mother/source-surface-field/1','配方类型错误');gate(r.source?.bounds?.min?.length===3&&r.source.bounds.max?.length===3,'配方缺少范围');gate(Number.isFinite(r.cell)&&r.cell>0&&Number.isFinite(r.spacing)&&r.spacing>0&&Number.isFinite(r.supportRadius)&&r.supportRadius>0,'间距错误');gate(r.patches?.length>0&&r.patches.length<=22000,'支持区数量错误');for(const p of r.patches){for(const k of ['c','n','k'])gate(p[k]?.length===3&&p[k].every(Number.isFinite),'支持区含非数值');gate(Math.abs(Math.hypot(...p.n)-1)<.01,'法线不规范')}for(const k of ['positions','indices','uv','texture','rawSource'])gate(!(k in r),'配方夹带源网格或贴图');return true}
export function evaluator(r){validate(r);const c=r.cell,R=r.supportRadius,R2=R*R,min=r.source.bounds.min,bins=new Map(),P=r.patches.map(p=>{const [u,v]=frame(p.n);return {...p,u,v}});for(let i=0;i<P.length;i++){const q=P[i].c.map((x,k)=>Math.floor((x-min[k])/c)),k=key(...q);if(!bins.has(k))bins.set(k,[]);bins.get(k).push(i)}let last='',ids=[];const lookup=new Map();return function(x,y,z,detail=false){const q=[Math.floor((x-min[0])/c),Math.floor((y-min[1])/c),Math.floor((z-min[2])/c)],k=key(...q);if(k!==last){last=k;if(lookup.has(k))ids=lookup.get(k);else{ids=[];for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++)for(let d=-2;d<=2;d++)ids.push(...bins.get(key(q[0]+a,q[1]+b,q[2]+d))??[]);lookup.set(k,ids)}}let nearest=-1,near=Infinity;for(const i of ids){const p=P[i],dx=x-p.c[0],dy=y-p.c[1],dz=z-p.c[2],v=dx*dx+dy*dy+dz*dz;if(v<near){near=v;nearest=i}}if(nearest<0||near>R2*.81)return detail?null:NaN;const ref=P[nearest];let s=0,value=0,nx=0,ny=0,nz=0,c0=0,c1=0,c2=0,cw=0;for(const i of ids){const p=P[i],dx=x-p.c[0],dy=y-p.c[1],dz=z-p.c[2],dist=dx*dx+dy*dy+dz*dz;if(dist>=R2)continue;const w=(1-dist/R2)**4/(.035+dist/(c*c)),u=(dx*p.u[0]+dy*p.u[1]+dz*p.u[2])/c,v=(dx*p.v[0]+dy*p.v[1]+dz*p.v[2])/c,h=clamp((p.k[0]*u*u+p.k[1]*u*v+p.k[2]*v*v)*c,-c*.28,c*.28);value+=(dx*p.n[0]+dy*p.n[1]+dz*p.n[2]-h)*w;s+=w;if(detail){nx+=p.n[0]*w;ny+=p.n[1]*w;nz+=p.n[2]*w;if(p.color){c0+=p.color[0]*w;c1+=p.color[1]*w;c2+=p.color[2]*w;cw+=w}}}if(s<1e-12)return detail?null:NaN;return detail?{value:value/s,normal:unit([nx,ny,nz]),color:cw?[c0/cw,c1/cw,c2/cw]:null,region:ref.region,patch:nearest}:value/s}}
export function rebuild(r,progress=()=>{}){
 const f=evaluator(r),step=r.spacing,b=r.source.bounds,pad=Math.ceil(r.supportRadius/step)+2,origin=b.min.map(x=>x-step*pad),dims=b.max.map((x,k)=>Math.ceil((x-b.min[k])/step)+pad*2+1),[nx,ny,nz]=dims,stride=nx*ny,total=stride*nz;gate(total<=10000000,'固定体素网格超预算，未自动降精度');const vals=new Float32Array(total).fill(NaN);
 for(let z=0;z<nz;z++){for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){let v=f(origin[0]+x*step,origin[1]+y*step,origin[2]+z*step);if(Number.isFinite(v)&&Math.abs(v)<step*.001)v=step*.001;vals[z*stride+y*nx+x]=v}if(z%8===0)progress(.28+.32*z/nz,'编译固定三维数值场')}
 const pp=[],ii=[],nn=[],cc=[],regions=[],cache=new Map(),offsets=[0,1,1+nx,nx,stride,stride+1,stride+1+nx,stride+nx],tet=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]],xyz=id=>{const z=Math.floor(id/stride),v=id-z*stride,y=Math.floor(v/nx),x=v-y*nx;return [origin[0]+x*step,origin[1]+y*step,origin[2]+z*step]};
 function pt(a,b){const k=a<b?a+':'+b:b+':'+a;if(cache.has(k))return cache.get(k);const t=vals[a]/(vals[a]-vals[b]),pa=xyz(a),pb=xyz(b),p=pa.map((x,i)=>x+(pb[i]-x)*t),d=f(...p,true);if(!d)return -1;const id=pp.length/3;pp.push(...p);nn.push(...d.normal);cc.push(...(d.color??[.45,.45,.45]));regions.push(d.region);cache.set(k,id);return id}
 function tri(a,b,c){if(a<0||b<0||c<0||a===b||a===c||b===c)return;const pa=pp.slice(a*3,a*3+3),pb=pp.slice(b*3,b*3+3),pc=pp.slice(c*3,c*3+3),n=cross(sub(pb,pa),sub(pc,pa));if(Math.hypot(...n)<step*step*1e-8)return;if(dot(n,nn.slice(a*3,a*3+3))<0)[b,c]=[c,b];ii.push(a,b,c)}
 for(let z=0;z<nz-1;z++){for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const base=z*stride+y*nx+x,ids=offsets.map(o=>base+o);let lo=Infinity,hi=-Infinity,ok=true;for(const id of ids){const v=vals[id];if(!Number.isFinite(v)){ok=false;break}lo=Math.min(lo,v);hi=Math.max(hi,v)}if(!ok||lo>=0||hi<=0)continue;for(const t of tet){const a=[],b=[];for(const i of t)(vals[ids[i]]<0?a:b).push(ids[i]);if(!a.length||!b.length)continue;if(a.length===1||b.length===1){const [s,rest]=a.length===1?[a[0],b]:[b[0],a];tri(...rest.map(i=>pt(s,i)))}else{const q=[pt(a[0],b[0]),pt(a[0],b[1]),pt(a[1],b[1]),pt(a[1],b[0])];tri(q[0],q[1],q[2]);tri(q[0],q[2],q[3])}}}if(z%8===0)progress(.60+.24*z/nz,'独立生成新三角拓扑')}
 gate(ii.length>0&&ii.length/3<=1800000,'生成为空或超出面数预算');const out={positions:new Float32Array(pp),indices:new Uint32Array(ii),colors:new Float32Array(cc),regions:new Int32Array(regions),fixedSpacing:step,grid:dims,recipeOnly:true,sourceTopologyCopied:false};out.normals=normals(out.positions,out.indices);return out;
}
