import {StitchGroups} from './stitch-groups.mjs';
import {SelfContact} from './self-contact.mjs';
import {ClothLab,cut,clone,directedEdge} from './core.mjs';
export class BodySDF{
 constructor(meta,array){this.meta=meta;this.a=array;}
 sample(x,y,z,out){const m=this.meta,d=m.dimensions,ox=m.originMm,step=m.spacingMm,fx=(x*1000-ox[0])/step,fy=(y*1000-ox[1])/step,fz=(z*1000-ox[2])/step;
 if(fx<0||fy<0||fz<0||fx>=d[0]-1||fy>=d[1]-1||fz>=d[2]-1){out[0]=1e3;out[1]=out[2]=out[3]=0;out[4]=0;return out;}
 const i=Math.floor(fx),j=Math.floor(fy),k=Math.floor(fz),u=fx-i,v=fy-j,w=fz-k,nx=d[0],ny=d[1],o=(k*ny+j)*nx+i,a=this.a;
 const p=a[o],q=a[o+1],r=a[o+nx],s=a[o+nx+1],t=a[o+nx*ny],b=a[o+nx*ny+1],c=a[o+nx*ny+nx],e=a[o+nx*ny+nx+1];
 const lo=(p*(1-u)+q*u)*(1-v)+(r*(1-u)+s*u)*v,hi=(t*(1-u)+b*u)*(1-v)+(c*(1-u)+e*u)*v;
 out[0]=(lo*(1-w)+hi*w)*m.quantizationMm*.001;
 const dx=((q-p)*(1-v)+(s-r)*v)*(1-w)+((b-t)*(1-v)+(e-c)*v)*w,dy=((r-p)*(1-u)+(s-q)*u)*(1-w)+((c-t)*(1-u)+(e-b)*u)*w,dz=hi-lo,n=Math.hypot(dx,dy,dz);out[1]=n?dx/n:0;out[2]=n?dy/n:1;out[3]=n?dz/n:0;out[4]=1;return out;
 }
}
export class GarmentLab extends ClothLab{
 constructor(spec,sdf,{substeps=18,iterations=3,sewingDuration=4,clearanceMm=3.5}={}){
  super(cut(spec));this.sdf=sdf;this.substeps=substeps;this.iterations=iterations;this.sewingDuration=sewingDuration;this.clearance=clearanceMm*.001;this.gravityScale=0;this.collisions=true;this.bodyContacts=0;this._q=new Float64Array(5);this._old=new Float64Array(this.positions.length*3);this.support=[];this.orientationGuides=true;this.guideSigns=new Int8Array(this.positions.length);
  for(const p of this.spec.panels){if(p.placement.rigidBasis){const o=this.offsets.get(p.id),b=p.placement.rigidBasis,t=p.placement.translationMm;for(let j=0;j<p.uvMm.length;j++){const[u,v]=p.uvMm[j];this.positions[o+j]=[(b[0]*u+b[1]*v+t[0])/1000,(b[3]*u+b[4]*v+t[1])/1000,(b[6]*u+b[7]*v+t[2])/1000];this.previous[o+j]=[...this.positions[o+j]];}}
   if(p.meshType==='unstructured'){const off=this.offsets.get(p.id);for(const i of p.temporaryGuideMaterialIds)this.guideSigns[off+i]=(p.source.bodySide==='front'||p.id.includes('F'))?1:-1;}else if(p.id!=='G'){const off=this.offsets.get(p.id),isFront=p.id.includes('F'),cols=p.meshGrid?.columns??13,rows=p.uvMm.length/cols,j0=p.meshGrid?.guideRows[0]??1,j1=p.meshGrid?.guideRows[1]??rows-2,i0=p.meshGrid?.guideColumns[0]??2,i1=p.meshGrid?.guideColumns[1]??cols-3;for(let j=j0;j<=j1;j++)for(let i=i0;i<=i1;i++)this.guideSigns[off+j*cols+i]=isFront?1:-1;}
   for(const index of p.temporaryPins){if(p.temporaryPinTargetsMm?.[index]){const id=this.offsets.get(p.id)+index;this.support.push({id,start:[...this.positions[id]],target:p.temporaryPinTargetsMm[index].map(x=>x/1000)});continue;}const id=this.offsets.get(p.id)+index,sign=p.id.endsWith('R')?-1:1,start=[...this.positions[id]],waist=this.spec.source.measurementSnapshot.lowerWaist||this.spec.source.measurementSnapshot.waist;const isCenter=this.spec.source.waistFixtures&&index===p.edges.waist[0],back=p.id.startsWith('B'),target=isCenter?[sign*.0004,(this.spec.source.measurementSnapshot.waist.heightMm-this.spec.source.options.waistbandHeightMm)/1000,(back?waist.backZ-3.8:waist.frontZ+3.8)/1000]:[sign*(Math.abs(waist.sideRightXZ[0])+3.8)/1000,(this.spec.source.measurementSnapshot.waist.heightMm-this.spec.source.options.waistbandHeightMm)/1000,(waist.sideRightXZ[1]+(back?-.4:.4))/1000];this.support.push({id,start,target});}
  }
  this.strainTriangles=this.triangles.map(t=>{const [a,b,c]=t.uv.map(x=>x.map(y=>y/1000)),du=b[0]-a[0],dv=b[1]-a[1],eu=c[0]-a[0],ev=c[1]-a[1],det=du*ev-dv*eu;return{ids:t.ids,c:[(dv-ev)/det,ev/det,-dv/det],d:[(eu-du)/det,-eu/det,du/det]};});
  this.meshEdges=[];const seen=new Set();for(const t of this.triangles)for(let i=0;i<3;i++){const a=t.ids[i],b=t.ids[(i+1)%3],key=a<b?a+':'+b:b+':'+a;if(!seen.has(key)){seen.add(key);this.meshEdges.push([a,b]);}}
  this.selfContacts=new SelfContact(this);this.selfCollisionEnabled=true;this.stitchGroups=new StitchGroups(this);this.stitchEqualityElimination=false;this.strainGuard=true;this.frameCount=0;this.actions=[];
 }
 activate(stageId,current=this.spec){const existed=this.completed.has(stageId);super.activate(stageId,current);if(!existed)this.actions.push({kind:'sew-stage',stageId,atFrame:this.frameCount});for(const c of this.seamConstraints)if(c.rampDuration===undefined)c.rampDuration=this.sewingDuration;}
 detach(){super.detach();this.actions.push({kind:'detach',atFrame:this.frameCount});this.positions=this.positions.map(p=>[...p]);this.velocity=this.velocity.map(p=>[...p]);this.invMass=this.baseInvMass.map((w,i)=>this.pins.has(i)?0:w);this.stitchGroups=new StitchGroups(this);}
 setGravity(scale){this.gravityScale=scale;this.actions.push({kind:'gravity',scale,atFrame:this.frameCount});}
 releasePins(){super.releasePins();this.actions.push({kind:'release-supports',atFrame:this.frameCount});this.support=[];this.orientationGuides=false;if(this.stitchEqualityElimination)this.stitchGroups.rebuild();}
 contact(ids,weights,margin=this.clearance){let x=0,y=0,z=0;for(let k=0;k<ids.length;k++){const p=this.positions[ids[k]],w=weights[k];x+=p[0]*w;y+=p[1]*w;z+=p[2]*w;}const q=this.sdf.sample(x,y,z,this._q);if(!q[4]||q[0]>=margin)return;let sum=0;for(let k=0;k<ids.length;k++)sum+=this.invMass[ids[k]]*weights[k]*weights[k];if(sum<1e-12)return;const lambda=(margin-q[0])/sum;for(let k=0;k<ids.length;k++){const p=this.positions[ids[k]],f=this.invMass[ids[k]]*weights[k]*lambda;p[0]+=q[1]*f;p[1]+=q[2]*f;p[2]+=q[3]*f;}this.bodyContacts++;}
 strainLimit(){
  const ps=this.positions,im=this.invMass;
  for(const t of this.strainTriangles){const[a,b,c]=t.ids,A=ps[a],B=ps[b],C=ps[c],u=t.c,w=t.d;
   let ux=A[0]*u[0]+B[0]*u[1]+C[0]*u[2],uy=A[1]*u[0]+B[1]*u[1]+C[1]*u[2],uz=A[2]*u[0]+B[2]*u[1]+C[2]*u[2],vx=A[0]*w[0]+B[0]*w[1]+C[0]*w[2],vy=A[1]*w[0]+B[1]*w[1]+C[1]*w[2],vz=A[2]*w[0]+B[2]*w[1]+C[2]*w[2];
   const aa=ux*ux+uy*uy+uz*uz,bb=vx*vx+vy*vy+vz*vz,ab=ux*vx+uy*vy+uz*vz,angle=.5*Math.atan2(2*ab,aa-bb),co=Math.cos(angle),si=Math.sin(angle);
   for(let mode=0;mode<2;mode++){ux=A[0]*u[0]+B[0]*u[1]+C[0]*u[2];uy=A[1]*u[0]+B[1]*u[1]+C[1]*u[2];uz=A[2]*u[0]+B[2]*u[1]+C[2]*u[2];vx=A[0]*w[0]+B[0]*w[1]+C[0]*w[2];vy=A[1]*w[0]+B[1]*w[1]+C[1]*w[2];vz=A[2]*w[0]+B[2]*w[1]+C[2]*w[2];const qx=mode?-si:co,qy=mode?co:si,nx=ux*qx+vx*qy,ny=uy*qx+vy*qy,nz=uz*qx+vz*qy,len=Math.hypot(nx,ny,nz),target=Math.max(.985,Math.min(1.015,len));if(Math.abs(len-target)<1e-6||len<1e-9)continue;const ca=u[0]*qx+w[0]*qy,cb=u[1]*qx+w[1]*qy,cc=u[2]*qx+w[2]*qy,den=im[a]*ca*ca+im[b]*cb*cb+im[c]*cc*cc;if(den<1e-12)continue;const factor=-(len-target)/(den*len),fa=im[a]*ca*factor,fb=im[b]*cb*factor,fc=im[c]*cc*factor;A[0]+=fa*nx;A[1]+=fa*ny;A[2]+=fa*nz;B[0]+=fb*nx;B[1]+=fb*ny;B[2]+=fb*nz;C[0]+=fc*nx;C[1]+=fc*ny;C[2]+=fc*nz;}
  }
 }
 step(dt=1/60){
  this.frameCount++;const n=this.positions.length,h=dt/this.substeps,ps=this.positions,vs=this.velocity,im=this.invMass,q=this._q,old=this._old,all=[...this.constraints,...this.seamConstraints];this.bodyContacts=0;
  for(let sub=0;sub<this.substeps;sub++){
   this.elapsed+=h;this.seamElapsed+=h;if(this.stitchEqualityElimination)this.stitchGroups.synchronize();
   for(const hold of this.support){const p=ps[hold.id],t=Math.min(1,this.elapsed/4),s=t*t*(3-2*t);for(let k=0;k<3;k++)p[k]=hold.start[k]+(hold.target[k]-hold.start[k])*s;}
   for(let i=0;i<n;i++){const p=ps[i],o=i*3;old[o]=p[0];old[o+1]=p[1];old[o+2]=p[2];}for(let i=0;i<n;i++){if(this.stitchEqualityElimination&&this.stitchGroups.find(i)!==i)continue;const p=ps[i],v=vs[i];if(!im[i])continue;v[1]-=9.81*this.gravityScale*h;p[0]+=v[0]*h;p[1]+=v[1]*h;p[2]+=v[2]*h;}
   for(const c of all)c.lambda=0;
   for(let iter=0;iter<this.iterations;iter++){
    for(const c of all){if(c.eliminated)continue;const a=ps[c.a],b=ps[c.b],w1=im[c.a],w2=im[c.b],dx=a[0]-b[0],dy=a[1]-b[1],dz=a[2]-b[2],len=Math.hypot(dx,dy,dz);if(len<1e-12||w1+w2===0)continue;const alpha=c.compliance/(h*h),target=c.type==='seam'?c.rest+(c.startRest-c.rest)*Math.max(0,1-(this.elapsed-c.activatedAt)/c.rampDuration):c.rest,dl=(-(len-target)-alpha*c.lambda)/(w1+w2+alpha),f=dl/len;c.lambda+=dl;a[0]+=w1*f*dx;a[1]+=w1*f*dy;a[2]+=w1*f*dz;b[0]-=w2*f*dx;b[1]-=w2*f*dy;b[2]-=w2*f*dz;}
    if(this.strainGuard)this.strainLimit();
    if(this.orientationGuides)for(let i=0;i<n;i++){const sign=this.guideSigns[i];if(!sign||!im[i])continue;const p=ps[i],y=p[1]*1000,m=this.spec.source.measurementSnapshot,split=y>=m.hip.heightMm?(m.hip.sideRightXZ[1]+(m.waist.sideRightXZ[1]-m.hip.sideRightXZ[1])*Math.min(1,(y-m.hip.heightMm)/(m.waist.heightMm-m.hip.heightMm))):25,limit=(split+sign*12)/1000;if(sign>0&&p[2]<limit)p[2]=limit;if(sign<0&&p[2]>limit)p[2]=limit;}

    if(this.collisions)for(let i=0;i<n;i++){if(!im[i])continue;const p=ps[i];this.sdf.sample(p[0],p[1],p[2],q);if(q[4]&&q[0]<this.clearance){const d=this.clearance-q[0];p[0]+=q[1]*d;p[1]+=q[2]*d;p[2]+=q[3]*d;this.bodyContacts++;}}
   }
   // A sewing block is solved after local material/body projections as well.
   // This changes constraint ordering, never UV rest metrics or mesh identity.
   for(const c of this.seamConstraints){if(c.eliminated)continue;const a=ps[c.a],b=ps[c.b],w1=im[c.a],w2=im[c.b],dx=a[0]-b[0],dy=a[1]-b[1],dz=a[2]-b[2],len=Math.hypot(dx,dy,dz);if(len<1e-12||w1+w2===0)continue;const target=c.rest+(c.startRest-c.rest)*Math.max(0,1-(this.elapsed-c.activatedAt)/c.rampDuration),alpha=c.compliance/(h*h),dl=(-(len-target)-alpha*c.lambda)/(w1+w2+alpha),f=dl/len;c.lambda+=dl;a[0]+=w1*f*dx;a[1]+=w1*f*dy;a[2]+=w1*f*dz;b[0]-=w2*f*dx;b[1]-=w2*f*dy;b[2]-=w2*f*dz;}
   if(this.collisions&&sub%3===2){for(const e of this.meshEdges)this.contact(e,[.5,.5],.0015);for(const t of this.triangles)this.contact(t.ids,[1/3,1/3,1/3],.0015);}
   if(this.selfCollisionEnabled&&sub%3===2){let maxDelta=0;for(let i=0;i<n;i++){const p=ps[i],o=i*3;maxDelta=Math.max(maxDelta,Math.hypot(p[0]-old[o],p[1]-old[o+1],p[2]-old[o+2]));}this.lastMaxSubstepDisplacement=maxDelta;this.selfContacts.rebuild();this.selfContacts.project();}
   const damping=Math.exp(-20*h);for(let i=0;i<n;i++){if(this.stitchEqualityElimination&&this.stitchGroups.find(i)!==i)continue;const p=ps[i],v=vs[i],o=i*3;v[0]=(p[0]-old[o])/h*damping;v[1]=(p[1]-old[o+1])/h*damping;v[2]=(p[2]-old[o+2])/h*damping;if(p[1]<0){p[1]=0;v[1]=0;}}
  }
 }
 metrics(){const m=super.metrics();let minBody=Infinity,bad=0,domain=0,minY=Infinity,maxY=-Infinity;const q=new Float64Array(5);for(const p of this.positions){this.sdf.sample(...p,q);if(q[4]){minBody=Math.min(minBody,q[0]*1000);if(q[0]<-.0005)bad++;}else domain++;minY=Math.min(minY,p[1]*1000);maxY=Math.max(maxY,p[1]*1000);}const seams=this.spec.seams.map(s=>{const a=directedEdge(this.spec,s.a),b=directedEdge(this.spec,s.b),o1=this.offsets.get(a.panel.id),o2=this.offsets.get(b.panel.id);const distances=a.ids.map((v,i)=>Math.hypot(...this.positions[o1+v].map((x,k)=>x-this.positions[o2+b.ids[i]][k]))*1000);return{id:s.id,active:this.active.has(s.id),maxGapMm:Math.max(...distances)};});return{...m,bodySignedDistanceMinMm:minBody,bodyInsideVertexCount:bad,outsideCollisionDomain:domain,minYmm:minY,maxYmm:maxY,seams,activeMaxGapMm:Math.max(0,...seams.filter(s=>s.active).map(s=>s.maxGapMm)),temporarySupportCount:this.support.length,stitchEqualityElimination:this.stitchEqualityElimination?this.stitchGroups.report():false,gravityScale:this.gravityScale,temporaryOrientationGuides:this.orientationGuides,bodyContact:'grid-SDF from exact Anny triangle nearest distance; exact audit required',selfCollision:this.selfCollisionEnabled?'discrete vertex-face, exact audit still required':'disabled',selfContactCorrections:this.selfContacts.corrections,skippedSelfContactTriangles:this.selfContacts.skippedLargeTriangles};}
 export(){const m=this.metrics();return{...super.export(),schema:'kaopu-garment-physical-trial@1',frameCount:this.frameCount,actions:this.actions,materialToSolverGroup:this.stitchEqualityElimination?this.positions.map((_,i)=>this.stitchGroups.find(i)):this.positions.map((_,i)=>i),metrics:m,solver:{...super.export().solver,version:'garment-small-step-r1',contacts:'triangle-body-SDF vertex/edge/face samples and ground',strainGuard:this.strainGuard?{kind:'per-iteration principal stretch clamp',min:.985,max:1.015,acceptanceThreshold:false}:false,velocityDampingRate:20,substeps:this.substeps,iterations:this.iterations,sewingDuration:this.sewingDuration,clearanceMm:this.clearance*1000,gravityScale:this.gravityScale,temporaryOrientationGuides:this.orientationGuides,bodyContact:'sampled triangle-mesh SDF + edge midpoint and face centroid projections',selfCollision:this.selfCollisionEnabled,stitchEqualities:this.stitchEqualityElimination?this.stitchGroups.report():false},sourceBody:this.spec.source.measurementSnapshot.bodyId};}
}
