import * as THREE from'../source/registration-vendor/three.module.js';
import{BoxingArena,RING_SPEC}from'../boxing-r02/Arena.mjs';
import{AnimatedHuman}from'../boxing/AnimatedHuman.mjs';
import{createBoxingRig,recommendPairSeparation}from'../boxing/Motion.mjs';
import{createGlovePair}from'../boxing-r02/Gloves.mjs';
/** Scene-only extraction of the already accepted R02 arena behavior.
 * No R03 action inventory, DOM controls, renderer or camera are imported.
 * Caller supplies the original36 recipes on an unmodified baseline model.
 * Existing page remains untouched. All36 full humans continue to evaluate. */
export async function createR02ArenaScene({root,model,states,onProgress=()=>{},signal}={}){
 if(!root?.add||!model?.compute||states?.length!==36)throw Error('Existing root, baseline model and exactly original36 recipes required');
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),gradient=ctx.createRadialGradient(64,64,5,64,64,62);gradient.addColorStop(0,'rgba(0,0,0,.55)');gradient.addColorStop(.45,'rgba(0,0,0,.3)');gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const shadowTexture=new THREE.CanvasTexture(shadowCanvas);
 const group=new THREE.Group();group.name='accepted-r02-18-arenas';root.add(group);const arenas=[],actors=[],arenaBounds=[];let time=0,contactIK=true,disposed=false;
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x17232c,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.003;group.add(ground);
 try{
 for(let i=0;i<18;i++){const arena=new BoxingArena(i),x=(i%6-2.5)*RING_SPEC.pitch,z=(Math.floor(i/6)-1)*RING_SPEC.pitch;arena.group.position.set(x,RING_SPEC.deckHeight,z);group.add(arena.group);root.updateWorldMatrix(true,true);const measured=new THREE.Box3().setFromObject(arena.group).applyMatrix4(root.matrixWorld.clone().invert());arenaBounds.push({id:'arena-'+i,min:measured.min.toArray(),max:measured.max.toArray(),source:'actual R02 static meshes including ropes, labels, apron and stairs'});arenas.push({index:i,arena,group:arena.group,x,z});}
 for(let i=0;i<36;i++){if(signal?.aborted)throw new DOMException('Cancelled','AbortError');const entry=states[i];if(!entry.state||!entry.id)throw Error('Explicit native recipe required');model.compute(entry.state);const color=i%2?0xc56e43:0x2f90b6,human=new AnimatedHuman(model,entry.state,{color,tone:.64}),child=['child','teen'].includes(entry.stage),motion=createBoxingRig({names:human.names,parents:human.rig.parents,restMatrices:human.rig.restMatrices,stature:human.height,child}),actorGroup=new THREE.Group();actorGroup.rotation.y=i%2?-Math.PI/2:Math.PI/2;actorGroup.position.y=human.floorOffset;actorGroup.add(human.mesh);const gloves=createGlovePair({names:human.names,height:human.height,color});for(const glove of gloves)actorGroup.add(glove);const footShadows=['L','R'].map(side=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.24,.37),new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false,opacity:.75}));mesh.rotation.x=-Math.PI/2;mesh.renderOrder=1;actorGroup.add(mesh);return{mesh,index:human.names.indexOf('foot.'+side)};});const actor={...entry,human,motion,group:actorGroup,gloves,footShadows,child,latest:null};actors.push(actor);arenas[Math.floor(i/2)].group.add(actorGroup);onProgress({completed:i+1,total:36});await new Promise(r=>setTimeout(r,0));}
 for(let i=0;i<18;i++){const a=actors[i*2],b=actors[i*2+1],d=recommendPairSeparation(i);a.group.position.x=-d/2;b.group.position.x=d/2;arenas[i].separation=d;}
 }catch(e){dispose();throw e;}
 function update(seconds){if(disposed)throw Error('Arena scene disposed');if(!Number.isFinite(seconds)||seconds<0)throw Error('Finite scene time required');for(let i=0;i<36;i++){const a=actors[i],p=a.motion.evaluate(seconds,{pairIndex:Math.floor(i/2),fighter:i%2,child:a.child,intensity:1,opponentStature:actors[i^1].human.height,contactIK,footLock:contactIK});a.latest=p;a.human.animate(p.skinMatrices);for(const sh of a.footShadows){const m=p.posedMatrices[sh.index],scale=a.human.height/1.75;sh.mesh.position.set(m[3],.005-a.group.position.y,-m[7]-.035*scale);sh.mesh.scale.setScalar(scale);sh.mesh.material.opacity=.75*Math.exp(-20*Math.max(0,m[11]-a.human.rig.restMatrices[sh.index][11]));}for(const glove of a.gloves)glove.updateFromPose(p.posedMatrices,a.human.height);}time=seconds;}
 function dispose(){if(disposed)return;disposed=true;for(const a of actors){a.human.dispose();for(const glove of a.gloves)glove.dispose();for(const sh of a.footShadows){sh.mesh.geometry.dispose();sh.mesh.material.dispose();}}for(const a of arenas)a.arena.dispose();ground.geometry.dispose();ground.material.dispose();shadowTexture.dispose();group.removeFromParent();}
 update(0);return{group,actors,arenas,arenaBounds,update,setRopes(mode){for(const a of arenas)a.arena.setRopeMode(mode);},setIK(enabled){contactIK=!!enabled;update(time);},diagnostics(){return{version:'accepted-r02-scene-extraction/1',time,actors:actors.length,arenas:arenas.length,vertices:actors.map(a=>a.human.N),bones:actors.map(a=>a.human.names.length),contactIK,weightsTruncated:false,approximatePhysicalHits:false,motion:'unchanged R02 independent rules and support IK',arenaBounds};},dispose};
}
