/* KAOPU R10 — inherit R04/R07, never R08. IQ/TDM research derivatives: CC BY-NC-SA 3.0. */
'use strict';
(async()=>{
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o));
const baseURL=new URL('./',document.currentScript.src||(document.baseURI==='about:blank'?'https://kaopu.invalid/':document.baseURI));
const files=['wet-baseline.frag','wet-material-baseline.frag','wet-material.frag','iq-baseline.frag','iq-merged.frag'];
const frozen={wet:{yaw:1.155,pitch:.2,time:3.85,palette:0,pbr:1,view:0,baseline:false,roughness:.72,wet:.65,crack:0,crackWidth:.018,crackScale:1.35,moss:0,relief:.014,lichen:0,exposure:1.2,seed:11,light:-.65},iq:{yaw:0,pitch:0,time:0,k:.0125,method:2,displacement:1,planes:28,view:0,tone:1,look:0,shapeSeed:0,noiseSeed:0,cut:1,scale:[1,1,1],base:[180/255,180/255,180/255],low:[.018,.024,.031],high:[.057,.063,.07],patina:[.078,.048,.026],mica:[1,1,1],grain:[.45,.45,.43],specular:3,layers:[{on:false,strength:1,scale:7,cover:.5,seed:0},{on:false,strength:.4,scale:3.1,cover:.5,seed:0},{on:true,strength:1,scale:32,cover:.5,seed:0},{on:false,strength:.18,scale:80,cover:.5,seed:0}]}};
const rigDefault={enabled:false,keyTint:[1,1,1],fillTint:[1,1,1],keyPower:1,fillPower:1,keyAngles:[0,0],fillAngles:[0,0],background:[0,0,0]};
const extraDefaults={micro:.35,surfaceRough:1,surfaceWet:0,micaDark:.9,micaReflect:1.1};Object.assign(frozen.iq,extraDefaults);
const studioDefault={...clone(rigDefault),enabled:true,background:[.058,.064,.073],look:0};rigDefault.look=0;
const quality={mode:'auto',samples:1,hd:true};let manualResolution=0,saveTimer=0,lastEdit=0,inspectorTab='color';
let states=clone(frozen),rig=clone(studioDefault),active='wet',overview=true,ready=false,running=false,last=0,dirty=true,frames=0;
let inspect={wet:{ref:{zoom:1,pan:[0,0],hidden:true},result:{zoom:1,pan:[0,0],hidden:false}},iq:{ref:{zoom:1,pan:[0,0],hidden:true},result:{zoom:1,pan:[0,0],hidden:false}}};
const palette=[['暖褐','#73513b','#bf9e78'],['砂米','#a49578','#e3d4b6'],['冷灰','#636d75','#bdc6cf'],['炭黑','#22272c','#626b72'],['铁锈红','#7f3324','#cf8660'],['赭黄','#8b601c','#d8b661'],['青绿','#285f52','#8fba98'],['蓝灰','#334c72','#96b1ce'],['灰紫','#65455f','#b7a0b8'],['象牙白','#b1ac9c','#ece5d5']];
const iqPal=['#b4b4b4','#b8aa98','#909ba8','#4f565c','#b87c62','#b3a170','#729587','#7a90ad','#958092','#d1cbc0'];
const effect={dry:{wet:0,roughness:.9,crack:0,moss:0,lichen:0},wet:{wet:.9,roughness:.65,crack:0,moss:0,lichen:0},cracked:{wet:.12,roughness:.86,crack:.04,moss:0,lichen:0},moss:{wet:.2,roughness:.82,crack:.01,moss:.70,lichen:0},lichen:{wet:.05,roughness:.88,crack:.015,moss:0,lichen:.9},forest:{wet:.78,roughness:.72,crack:.045,moss:.63,lichen:.6}};
const wetRanges=[['roughness','粗糙度',.1,.95,.01],['wet','湿润 / 水膜',0,1,.01],['crack','裂纹深度',0,.075,.001],['crackWidth','裂纹宽度',.004,.04,.001],['crackScale','裂纹密度',.65,3,.01],['moss','青苔覆盖',0,1,.01],['relief','苔层厚度',0,.035,.001],['lichen','地衣覆盖',0,1,.01],['exposure','原材质曝光',.4,2.5,.01],['light','原灯方位',-3.14,3.14,.01],['seed','苔裂分布种子',1,99,1]];
const shapeRanges=[['shapeSeed','形状种子',0,99,1],['planes','裁切面数量',1,28,1],['cut','裁切距离',.7,1.2,.01],['k','平滑 k',0,.075,.0025],['displacement','原噪声位移',0,1,.02],['noiseSeed','噪声种子',0,99,1],['scale.0','长宽 X',.7,1.3,.01],['scale.1','高低 Y',.7,1.3,.01],['scale.2','厚度 Z',.7,1.3,.01]];
const layerNames=['01 矿物底色斑','02 棕色风化斑','03 原云母暗斑 / 反光','04 可选细颗粒'];
const sources={},renderers={},media={};let sourceFingerprint='';
const get=(o,path)=>path.split('.').reduce((x,k)=>x[k],o);const set=(o,path,v)=>{const a=path.split('.'),key=a.pop();a.reduce((x,k)=>x[k],o)[key]=v;};
const hexRaw=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255);
const linear=h=>hexRaw(h).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);
function toHex(v,lin=false){return '#'+v.map(x=>{x=Math.max(0,Math.min(1,x));if(lin)x=x<=.0031308?x*12.92:1.055*x**(1/2.4)-.055;return Math.round(x*255).toString(16).padStart(2,'0');}).join('');}
function fail(e){$('error').textContent=String(e.message||e);$('error').hidden=false;console.error(e);}
window.addEventListener('unhandledrejection',e=>fail(e.reason));
async function read(name){if(window.KAOPU_BUNDLE?.[name])return window.KAOPU_BUNDLE[name];const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{let r=await fetch(new URL(name,baseURL),{cache:'no-cache',signal:c.signal});if(!r.ok)throw Error('资源 '+name+' HTTP '+r.status);return await r.text();}finally{clearTimeout(timer);}}
async function digest(s){if(!crypto.subtle)return '';return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
const VS='#version 300 es\nprecision highp float;const vec2 P[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));void main(){gl_Position=vec4(P[gl_VertexID],0,1);}';
function zoomSource(s){return s.replace(/gl_FragCoord\.xy/g,'((gl_FragCoord.xy-.5*iResolution.xy)/uInspectZoom+.5*iResolution.xy+uInspectPan*iResolution.y)').replaceAll('KP_NATIVE_PIXEL','gl_FragCoord.xy').replaceAll('KP_WET_SAMPLE','((gl_FragCoord.xy+o-.5*iResolution.xy)/uInspectZoom+.5*iResolution.xy+uInspectPan*iResolution.y)').replace('#version 300 es','#version 300 es\nuniform highp float uInspectZoom;uniform highp vec2 uInspectPan;');}

function makeRenderer(canvas){const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2 未启动。');const programs=new Map(),vao=gl.createVertexArray();
function compile(t,s){const a=gl.createShader(t);gl.shaderSource(a,s);gl.compileShader(a);if(!gl.getShaderParameter(a,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(a));return a;}
function use(name){if(!programs.has(name)){const p=gl.createProgram(),v=compile(gl.VERTEX_SHADER,VS),f=compile(gl.FRAGMENT_SHADER,zoomSource(sources[name]));gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(v);gl.deleteShader(f);const uniforms=[];for(let i=0;i<gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS);i++){const a=gl.getActiveUniform(p,i);uniforms.push([a.name,a.type,gl.getUniformLocation(p,a.name)]);}programs.set(name,{p,uniforms});}const a=programs.get(name);gl.useProgram(a.p);gl.bindVertexArray(vao);return a;}
return {canvas,gl,draw(name,values){const {uniforms}=use(name);gl.viewport(0,0,canvas.width,canvas.height);for(const [k,t,l] of uniforms){const v=values[k];if(v===undefined)continue;if(t===gl.FLOAT)gl.uniform1f(l,v);else if(t===gl.INT||t===gl.BOOL)gl.uniform1i(l,v);else if(t===gl.FLOAT_VEC2)gl.uniform2fv(l,v);else if(t===gl.FLOAT_VEC3)gl.uniform3fv(l,v);else if(t===gl.FLOAT_VEC4)gl.uniform4fv(l,v);else throw Error('不允许的 uniform 类型 '+k);}gl.drawArrays(gl.TRIANGLES,0,3);},pixels(){const b=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,b);return b;}};}
function uniforms(id,s,q,renderer,useRig=true){const rr=useRig?rig:rigDefault, v={iResolution:[renderer.canvas.width,renderer.canvas.height,1],iTime:s.time,iFrame:Math.max(0,Math.floor(s.time*30)),uInspectZoom:q.zoom,uInspectPan:q.pan,uSharedRig:rr.enabled?1:0,uKeyTint:rr.keyTint,uFillTint:rr.fillTint,uKeyPower:rr.keyPower,uFillPower:rr.fillPower,uKeyAngles:rr.keyAngles,uFillAngles:rr.fillAngles,uBackground:rr.background,uRigLook:rr.look||0,uHD:useRig&&quality.hd?1:0,uAASamples:quality.samples,uDetailZoom:q.zoom,uMicro:s.micro||0,uSurfaceRough:s.surfaceRough||1,uSurfaceWet:s.surfaceWet||0,uMicaDark:s.micaDark??.9,uMicaReflect:s.micaReflect??1.1};
if(id==='wet'){Object.assign(v,{iMouse:[s.yaw*100,(2-s.pitch)*100,1,0],uRoughness:s.roughness,uWet:s.wet,uCrack:s.crack,uCrackWidth:s.crackWidth,uCrackScale:s.crackScale,uMoss:s.moss,uRelief:s.relief,uLichen:s.lichen,uSeed:s.seed,uExposure:s.exposure,uLight:s.light,uZoom:1,uBaseline:s.baseline?1:0,uPBR:s.pbr,uView:[0,5,3,1,2,4,6][s.view]||0,uBase:linear(palette[s.palette][1]),uGrain:linear(palette[s.palette][2])});}else{Object.assign(v,{uYaw:s.yaw,uPitch:s.pitch,uIQK:s.k,uDisp:s.displacement,uTone:s.tone,uPlanes:s.planes,uChannel:s.view<=2?s.view:0,uMethod:s.method,uLook:s.look,uShapeSeed:s.shapeSeed,uNoiseSeed:s.noiseSeed,uShapeScale:s.scale,uCutStrength:s.cut,uBaseRaw:s.base,uMineralLow:s.low,uMineralHigh:s.high,uPatinaColor:s.patina,uMicaTint:s.mica,uGrainColor:s.grain,uSurfaceView:s.view>=3?s.view-2:0,uSpecularScale:s.specular});for(const [u,k]of [['uLayerOn','on'],['uLayerStrength','strength'],['uLayerScale','scale'],['uLayerCover','cover'],['uLayerSeed','seed']])v[u]=s.layers.map(a=>k==='on'?(a[k]?1:0):a[k]);}return v;}
function draw(){if(!ready)return;resizeForQuality();const s=states[active],q=inspect[active];if(!q.result.hidden)renderers.result.draw(active==='wet'?'wet-material.frag':'iq-merged.frag',uniforms(active,s,q.result,renderers.result));if(!q.ref.hidden){const ref=clone(frozen[active]);Object.assign(ref,{yaw:s.yaw,pitch:s.pitch,time:s.time,view:Math.min(s.view,2)});renderers.ref.draw(active==='wet'?'wet-material-baseline.frag':'iq-baseline.frag',uniforms(active,ref,q.ref,renderers.ref,false));}dirty=false;frames++;updateReadout();}
function preview(id,canvas){const r=renderers.result,w=r.canvas.width,h=r.canvas.height;r.canvas.width=canvas.width;r.canvas.height=canvas.height;r.draw(id==='wet'?'wet-material-baseline.frag':'iq-baseline.frag',uniforms(id,frozen[id],{zoom:1,pan:[0,0]},r,false));canvas.getContext('2d').drawImage(r.canvas,0,0);r.canvas.width=w;r.canvas.height=h;dirty=true;}
function layout(){const q=inspect[active];$('referencePane').hidden=q.ref.hidden;$('resultPane').hidden=q.result.hidden;let n=+!q.ref.hidden + +!q.result.hidden;$('stage').classList.toggle('single',n===1);$('closed').hidden=n>0;for(const side of ['ref','result'])$(side+'Zoom').textContent=Math.round(q[side].zoom*100)+'%';$('compare').textContent=q.ref.hidden?'显示原版对照':'隐藏原版对照';dirty=true;}
function action(side,type){const q=inspect[active][side];if(type==='in')q.zoom=Math.min(5,q.zoom*1.25);if(type==='out')q.zoom=Math.max(.35,q.zoom/1.25);if(type==='reset'){q.zoom=1;q.pan=[0,0];}if(type==='focus'){q.hidden=false;inspect[active][side==='ref'?'result':'ref'].hidden=true;}if(type==='close')q.hidden=true;layout();}
function applyPalette(i,s){s.base=hexRaw(iqPal[i]);const ratio=s.base.map(x=>(x/(180/255))**3);for(const k of ['low','high','patina'])s[k]=frozen.iq[k].map((x,j)=>Math.min(1,x*ratio[j]));}
function mark(){dirty=true;lastEdit=performance.now();queueSave();$('stateLabel').textContent=(JSON.stringify(states[active])===JSON.stringify(frozen[active])&&!rig.enabled)?'原版默认状态':'用户参数变化 · 可还原';$('sharedRig').checked=rig.enabled;if($('returnMaterial'))$('returnMaterial').hidden=states[active].view===0;updateReadout();}
function updateControls(){document.querySelectorAll('[data-path]').forEach(el=>{const o=el.dataset.scope==='rig'?rig:states[active];let v=get(o,el.dataset.path);if(el.type==='checkbox')el.checked=v;else if(el.type==='color')el.value=toHex(v,el.dataset.linear==='yes');else el.value=v;const out=el.parentElement.querySelector('output');if(out)out.textContent=typeof v==='number'?(Number.isInteger(v)?v:v.toFixed(el.step&&+el.step<.01?4:2)):'';});document.querySelectorAll('[data-palette]').forEach(b=>b.classList.toggle('on',active==='wet'?+b.dataset.palette===states.wet.palette:toHex(states.iq.base)===iqPal[+b.dataset.palette]));$('channel').value=states[active].view;$('source').textContent=sources[active==='wet'?'wet-material.frag':'iq-merged.frag'];mark();}
function slider(target,path,label,min,max,step,scope='state'){const l=document.createElement('label');l.className='control';l.innerHTML=`<span>${label}</span><input type="range" min="${min}" max="${max}" step="${step}" data-path="${path}" data-scope="${scope}"><output></output>`;l.querySelector('input').oninput=e=>{const o=scope==='rig'?rig:states[active];set(o,path,+e.target.value);if(scope==='rig'){rig.enabled=true;states.wet.baseline=false;}else if(active==='wet')states.wet.baseline=false;updateControls();};$(target).append(l);}
function color(target,path,label,lin=false,scope='state'){const l=document.createElement('label');l.className='colorRow';l.innerHTML=`<span>${label}</span><input type="color" data-path="${path}" data-scope="${scope}" data-linear="${lin?'yes':'no'}" aria-label="${label}">`;l.querySelector('input').oninput=e=>{set(scope==='rig'?rig:states[active],path,lin?linear(e.target.value):hexRaw(e.target.value));if(scope==='rig'){rig.enabled=true;states.wet.baseline=false;}updateControls();};$(target).append(l);}
function build(){for(const id of ['palettes','wetControls','wetEffects','iqBase','shapeControls','seedButtons','layers','rigControls'])$(id).replaceChildren();const wet=active==='wet';$('objectTitle').textContent=wet?'01 / 原 Wet Stone · 完整保留':'02 / IQ 岩石 · 原02 / 03 合并';$('objectHint').textContent=wet?'原球体削切、原噪声、十色、裂纹、苔层、干湿与 PBR 都沿用 R04。':'默认就是原03的形体和质感；原02外观只作为同一原形体的材质选项。';$('lookButtons').hidden=wet;$('shapePanel').hidden=wet;$('layersPanel').hidden=wet;$('resultTitle').textContent=wet?'原湿石 · 可调材质':'原 IQ 岩石 · 可调斑纹';$('renderLabel').textContent='LIVE 3D · '+(wet?'R04 原形体':'IQ 原平面 / 原 fBm');
$('channel').replaceChildren();const channels=wet?['完整材质','白模几何','表面朝向 · 几何推导','底色','粗糙度','苔裂分布','AO']:['完整材质','白模几何','表面朝向 · 几何推导','底色','矿物层','风化层','云母层','细颗粒层'];channels.forEach((t,i)=>$('channel').add(new Option(t,i)));
palette.forEach((p,i)=>{const b=document.createElement('button');b.dataset.palette=i;b.innerHTML=`<i style="background:${wet?'linear-gradient(90deg,'+p[1]+','+p[2]+')':iqPal[i]}"></i>${p[0]}`;b.onclick=()=>{if(wet){states.wet.palette=i;states.wet.baseline=false;}else applyPalette(i,states.iq);updateControls();};$('palettes').append(b);});
if(wet){for(const [key,label]of [['dry','干燥粗石'],['wet','雨后湿石'],['cracked','开裂石'],['moss','青苔覆盖'],['lichen','地衣风化'],['forest','潮湿苔裂叠层']]){const b=document.createElement('button');b.textContent=label;b.dataset.effect=key;b.onclick=()=>{Object.assign(states.wet,effect[key],{baseline:false});updateControls();};$('wetEffects').append(b);}wetRanges.forEach(a=>slider('wetControls',...a));for(const [v,n]of [[1,'PBR / GGX'],[0,'原光照词汇']]){const b=document.createElement('button');b.textContent=n;b.onclick=()=>{states.wet.pbr=v;states.wet.baseline=false;updateControls();};$('wetEffects').append(b);}const b=document.createElement('button');b.textContent='返回老师原始复刻';b.onclick=()=>{states.wet.baseline=true;rig.enabled=false;states.wet.view=0;updateControls();};$('wetEffects').append(b);}else{
color('iqBase','base','原底色数值');slider('iqBase','tone','底色亮度',.4,2,.02);slider('iqBase','specular','原高光强度',0,4,.05);
shapeRanges.forEach(a=>slider('shapeControls',...a));for(const seed of [0,3,11,23,41]){const b=document.createElement('button');b.dataset.seed=seed;b.textContent=seed===0?'原形 seed 0':'形状 seed '+seed;b.onclick=()=>{states.iq.shapeSeed=seed;updateControls();};$('seedButtons').append(b);}for(const [m,n]of [[2,'原 sqrt 平滑'],[1,'多项式平滑'],[0,'硬裁切']]){const b=document.createElement('button');b.textContent=n;b.onclick=()=>{states.iq.method=m;mark();};$('seedButtons').append(b);}
for(let i=0;i<4;i++){const d=document.createElement('div');d.className='layer';d.id='layer'+i;d.innerHTML=`<div class="layerHead"><label><input type="checkbox" data-path="layers.${i}.on">${layerNames[i]}</label><button data-mask="${i}">单看分布</button></div>`;$('layers').append(d);d.querySelector('input').onchange=e=>{states.iq.layers[i].on=e.target.checked;mark();};d.querySelector('button').onclick=()=>{states.iq.view=states.iq.view===4+i?0:4+i;$('channel').value=states.iq.view;mark();};slider(d.id,`layers.${i}.strength`,'强度',0,1,.01);slider(d.id,`layers.${i}.scale`,'尺度 / 频率',i===3?10:.5,i===3?160:80,.1);slider(d.id,`layers.${i}.cover`,'覆盖偏移',0,1,.01);slider(d.id,`layers.${i}.seed`,'本层种子',0,99,1);if(i===0){color(d.id,'low','矿物暗色',true);color(d.id,'high','矿物亮色',true);}else color(d.id,['','patina','mica','grain'][i],i===1?'风化斑色':i===2?'云母乘色':'颗粒色',i!==2);}
}
color('rigControls','keyTint','主光乘色',false,'rig');color('rigControls','fillTint','次光乘色',false,'rig');color('rigControls','background','背景色',true,'rig');for(const a of [['keyPower','主光强度',0,2,.01],['fillPower','次光强度',0,2,.01],['keyAngles.0','主光水平偏角',-2,2,.01],['keyAngles.1','主光俯仰偏角',-1,1,.01],['fillAngles.0','次光水平偏角',-2,2,.01],['fillAngles.1','次光俯仰偏角',-1,1,.01]])slider('rigControls',...a,'rig');
attachExtras(wet);$('relation').textContent=wet?'01：冻结 R04 teacher.frag → 原九球削切/噪声 → 原 material.glsl 裂纹与苔层高度 → 原 GGX/Smith/Schlick。\n十色独立于几何；六种表面状态保留。统一灯光是可撤销的观察环境，不替换原形体。':'02：冻结 IQ 平面裁切与 fBm → 种子0 / 尺度1保留原形 → 原云母反光层 → 02附加矿物与棕斑层 → 原双灯。\n贴图占位已用同运算次序常量替代；无 sampler / texture 调用。\nshape seed / noise seed / 每层 seed 相互独立；默认新层关闭，只有原云母层开启。';updateControls();showInspector(inspectorTab);}
function select(id,push=true){running=false;$('rotate').textContent='开始旋转';$('teacherVideo').pause();overview=id==='home';$('catalog').classList.toggle('overview',overview);$('workspace').hidden=overview;$('gallery').hidden=true;document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===id));if(!overview){active=id==='wet'?'wet':'iq';build();layout();if(ready)draw();}if(push&&location.protocol.startsWith('http'))history.pushState({},'',new URL('?case='+id+'&v=r10',location.href));}
function reset(){$('rotate').textContent='开始旋转';states[active]=clone(frozen[active]);for(const side of ['ref','result']){inspect[active][side].zoom=1;inspect[active][side].pan=[0,0];}inspect[active].result.hidden=false;running=false;build();layout();}
function chooseLook(dark){const s=states.iq,shape={};for(const k of ['yaw','pitch','time','k','method','displacement','planes','shapeSeed','noiseSeed','cut','scale'])shape[k]=clone(s[k]);states.iq=Object.assign(clone(frozen.iq),shape);if(dark){states.iq.look=1;states.iq.layers[0].on=true;states.iq.layers[1].on=true;states.iq.specular=.45;}rig.enabled=true;rig.look=dark?1:0;build();}
// Pointer controls change sampling rays, never CSS page zoom.
for(const side of ['ref','result']){const el=$(side==='ref'?'referenceView':'resultView'),pts=new Map();let drag=null,pinch=0;el.addEventListener('wheel',e=>{e.preventDefault();const q=inspect[active][side];q.zoom=Math.max(.35,Math.min(5,q.zoom*Math.exp(-e.deltaY*.0015)));layout();},{passive:false});el.addEventListener('pointerdown',e=>{running=false;pts.set(e.pointerId,[e.clientX,e.clientY]);el.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,yaw:states[active].yaw,pitch:states[active].pitch,pan:[...inspect[active][side].pan],isPan:e.shiftKey};if(pts.size===2){let [a,b]=[...pts.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);}});el.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,[e.clientX,e.clientY]);const q=inspect[active][side];if(pts.size===2){let[a,b]=[...pts.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);q.zoom=Math.min(5,Math.max(.35,q.zoom*d/Math.max(pinch,1)));pinch=d;drag=null;layout();return;}if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y,h=el.getBoundingClientRect().height;if(drag.isPan)q.pan=[drag.pan[0]-dx/h/q.zoom,drag.pan[1]+dy/h/q.zoom];else{states[active].yaw=drag.yaw+dx*.006;states[active].pitch=Math.max(active==='wet'?.015:-1.2,Math.min(active==='wet'?2.5:1.2,drag.pitch+dy*.005));}dirty=true;});for(const e of ['pointerup','pointercancel'])el.addEventListener(e,p=>{pts.delete(p.pointerId);drag=null;pinch=0;mark();});el.addEventListener('dblclick',()=>action(side,'reset'));}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>select(b.dataset.go));document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.pane,b.dataset.act));window.onpopstate=()=>select(new URLSearchParams(location.search).get('case')||'home',false);
$('compare').onclick=()=>{inspect[active].ref.hidden=!inspect[active].ref.hidden;layout();};$('focus').onclick=()=>action('result','focus');$('restoreWindows').onclick=()=>{inspect[active].ref.hidden=false;inspect[active].result.hidden=false;layout();};$('resetAll').onclick=reset;$('cameraReset').onclick=()=>{Object.assign(states[active],{yaw:frozen[active].yaw,pitch:frozen[active].pitch,time:frozen[active].time});for(const side of ['ref','result'])action(side,'reset');running=false;mark();};$('rotate').onclick=()=>{running=!running;$('rotate').textContent=running?'暂停旋转':'开始旋转';};$('channel').onchange=e=>{states[active].view=+e.target.value;if(active==='wet')states.wet.baseline=false;mark();};$('iqOriginal').onclick=()=>chooseLook(false);$('darkLook').onclick=()=>chooseLook(true);$('resetShape').onclick=()=>{for(const k of ['k','method','displacement','planes','shapeSeed','noiseSeed','cut','scale'])states.iq[k]=clone(frozen.iq[k]);updateControls();};$('sharedRig').onchange=e=>{rig.enabled=e.target.checked;if(rig.enabled)states.wet.baseline=false;mark();};$('rigReset').onclick=()=>{rig=clone(rigDefault);updateControls();};$('warmCool').onclick=()=>{rig=clone(studioDefault);states.wet.baseline=false;updateControls();};
async function gallery(){running=false;document.querySelectorAll('[data-go]').forEach(b=>b.disabled=true);$('galleryButton').disabled=true;$('gallery').replaceChildren();$('gallery').hidden=false;const s=clone(states[active]),r=renderers.result,w=r.canvas.width,h=r.canvas.height;try{r.canvas.width=384;r.canvas.height=216;for(let i=0;i<10;i++){if(active==='wet'){s.palette=i;s.baseline=false;}else applyPalette(i,s);r.draw(active==='wet'?'wet-material.frag':'iq-merged.frag',uniforms(active,s,inspect[active].result,r));const fig=document.createElement('figure'),img=new Image();img.src=r.canvas.toDataURL();const cap=document.createElement('figcaption');cap.textContent=palette[i][0];fig.append(img,cap);$('gallery').append(fig);await new Promise(res=>setTimeout(res,0));}}finally{r.canvas.width=w;r.canvas.height=h;$('galleryButton').disabled=false;document.querySelectorAll('[data-go]').forEach(b=>b.disabled=false);dirty=true;draw();}}
$('galleryButton').onclick=gallery;
function score(){return {schema:'kaopu.stone.r10',sourceFingerprint,active,states:clone(states),rig:clone(rig),inspect:clone(inspect)};}
function valid(o,reference,path=''){if(reference===null)return;if(Array.isArray(reference)){if(!Array.isArray(o)||o.length!==reference.length)throw Error('数组无效 '+path);reference.forEach((v,i)=>valid(o[i],v,path+'.'+i));return;}if(typeof reference==='object'){if(!o||typeof o!=='object')throw Error('对象无效 '+path);for(const k of Object.keys(reference))valid(o[k],reference[k],path+'.'+k);return;}if(typeof o!==typeof reference)throw Error('类型无效 '+path);if(typeof o==='number'&&(!Number.isFinite(o)||Math.abs(o)>100000))throw Error('数值无效 '+path);}
function importScore(o){if(o.schema!=='kaopu.stone.r10'||o.sourceFingerprint!==sourceFingerprint)throw Error('参数谱版本或原码指纹不匹配');if(!['wet','iq'].includes(o.active))throw Error('对象无效');valid(o.states,frozen,'states');valid(o.rig,rigDefault,'rig');valid(o.inspect,inspect,'inspect');for(const id of ['wet','iq'])for(const side of ['ref','result']){const q=o.inspect[id][side];if(q.zoom<.35||q.zoom>5||q.pan.some(v=>Math.abs(v)>20))throw Error('观察越界');}for(const a of wetRanges){let x=o.states.wet[a[0]];if(x<a[2]||x>a[3])throw Error('湿石参数越界 '+a[0]);}for(const a of shapeRanges){let x=get(o.states.iq,a[0]);if(x<a[2]||x>a[3])throw Error('形状参数越界 '+a[0]);}if(!Number.isInteger(o.states.wet.palette)||o.states.wet.palette<0||o.states.wet.palette>9)throw Error('配色无效');for(const l of o.states.iq.layers){if(l.strength<0||l.strength>1||l.cover<0||l.cover>1||l.scale<.5||l.scale>160||l.seed<0||l.seed>99)throw Error('材质层参数越界');}for(const a of [o.states.iq.base,o.states.iq.low,o.states.iq.high,o.states.iq.patina,o.states.iq.mica,o.states.iq.grain,o.rig.keyTint,o.rig.fillTint,o.rig.background])if(a.some(x=>x<0||x>1))throw Error('颜色参数越界');for(const id of ['wet','iq']){const a=o.states[id];if(!Number.isInteger(a.view)||a.view<0||a.view>(id==='wet'?6:7)||Math.abs(a.pitch)>3.15||Math.abs(a.yaw)>10000||a.time<0)throw Error('观察/时间越界');}if(![0,1].includes(o.states.wet.pbr)||![0,1].includes(o.states.iq.look)||![0,1,2].includes(o.states.iq.method)||o.states.iq.tone<.4||o.states.iq.tone>2||o.states.iq.specular<0||o.states.iq.specular>4)throw Error('材质模式越界');for(const k of ['shapeSeed','noiseSeed','planes'])if(!Number.isInteger(o.states.iq[k]))throw Error('种子/数量须为整数');if(o.rig.keyPower<0||o.rig.keyPower>2||o.rig.fillPower<0||o.rig.fillPower>2)throw Error('灯光强度越界');states=clone(o.states);rig=clone(o.rig);inspect=clone(o.inspect);select(o.active);}
function save(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('export').onclick=()=>save('KAOPU_R10_'+active+'.json',new Blob([JSON.stringify(score(),null,2)],{type:'application/json'}));$('import').onclick=()=>$('scoreFile').click();$('scoreFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('文件太大');importScore(JSON.parse(await f.text()));}catch(e){fail(e);}finally{e.target.value='';}};
$('loadTeacher').onclick=()=>$('teacherFile').click();$('teacherFile').onchange=e=>{const f=e.target.files[0];if(!f)return;let type=f.type.startsWith('video/')?'video':f.type.startsWith('image/')?'image':null;if(!type){fail(Error('请选择原图片或录像'));return;}if(media.url)URL.revokeObjectURL(media.url);media.url=URL.createObjectURL(f);$('teacherVideo').pause();$('teacherVideo').hidden=type!=='video';$('teacherImage').hidden=type!=='image';$('mediaHolder').hidden=false;const el=type==='video'?$('teacherVideo'):$('teacherImage');el.src=media.url;$('mediaInfo').textContent=f.name+' · 原件直接读取';el.onerror=()=>{$('mediaInfo').textContent='原件解码未完成；作品仍可独立运行。';};e.target.value='';};$('closeTeacher').onclick=()=>{$('teacherVideo').pause();$('mediaHolder').hidden=true;};

function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('KAOPU_R10_STATE',JSON.stringify(score()));}catch(e){}},700);}
function restoreSession(){try{const text=localStorage.getItem('KAOPU_R10_STATE');if(text){const o=JSON.parse(text);if(o.sourceFingerprint===sourceFingerprint&&o.schema==='kaopu.stone.r10'){importScore(o);}}}catch(e){console.warn('旧参数未载入',e.message);}}
function requestedWidth(){if(manualResolution)return manualResolution;const box=$('resultView').getBoundingClientRect(),device=window.devicePixelRatio||1;return quality.mode==='auto'?Math.min(2560,Math.max(960,Math.ceil(box.width*device/16)*16)):Number(quality.mode);}
function resizeForQuality(){if(overview&&!manualResolution)return;const w=requestedWidth();for(const r of Object.values(renderers)){const limit=Math.min(r.gl.getParameter(r.gl.MAX_RENDERBUFFER_SIZE),4096);const rw=Math.min(w,limit);if(r.canvas.width!==rw){r.canvas.width=rw;r.canvas.height=Math.round(rw*9/16);}}}
function updateReadout(){if(!$('resolutionInfo')||!renderers.result)return;const c=renderers.result.canvas;$('resolutionInfo').textContent=`${c.width} × ${c.height} · ${quality.samples===2?'4次子像素采样':'原生采样'} · ${Math.round(inspect[active].result.zoom*100)}%`;$('surfaceModeNote').textContent=states[active].view===0?'完整材质 · 形体与斑纹独立':'当前为诊断通道；其他材质层仍保留。点击“返回完整材质”。';}
function showInspector(tab){inspectorTab=tab;if(active==='wet'&&['shape','layers'].includes(tab))inspectorTab='color';for(const [key,ids] of Object.entries({color:['colorPanel'],shape:['shapePanel'],layers:['layersPanel'],light:['rigPanel'],quality:['qualityPanel']})){for(const id of ids)$(id).hidden=key!==inspectorTab;}document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('on',b.dataset.tab===inspectorTab);b.hidden=active==='wet'&&['shape','layers'].includes(b.dataset.tab);});}
function attachExtras(wet){
 if(!wet){slider('iqBase','surfaceRough','反光宽窄 / 粗糙',.35,2.5,.01);slider('iqBase','surfaceWet','湿润响应',0,1,.01);slider('iqBase','micaDark','云母暗斑深度',0,1,.01);slider('iqBase','micaReflect','云母反光强度',0,2.5,.01);slider('shapeControls','micro','微起伏 · 原噪声延展',0,1,.01);}
 $('microExplanation').hidden=wet;
 $('qualityInfo').textContent=wet?'01 保留原形体、裂纹与苔层几何；原老师高频颗粒仍包含程序推导的光照朝向细节，不冒充全部是轮廓位移。':'02 保留原7层几何噪声，微起伏只延展同一噪声的第8—10层。几何频谱不随镜头换成另一块石头。';
 for(let i=0;i<4;i++){if($('layer'+i)){$('layer'+i).classList.toggle('layerOff',!states.iq.layers[i].on);}}
}
function installInspector(){
 $('darkLook').textContent='原02 · 蓝灰丰富斑纹';$('iqOriginal').textContent='原03 · 白灰云母';$('rigPanel').open=true;
 const colorPanel=$('palettes').closest('section');colorPanel.id='colorPanel';
 const inspector=document.createElement('aside');inspector.id='inspector';
 inspector.innerHTML='<div class="inspectorHead"><b>材质控制室</b><span>参数即时保存</span></div><div class="inspectorTabs"><button data-tab="color">色彩</button><button data-tab="shape">形状</button><button data-tab="layers">斑纹层</button><button data-tab="light">双灯</button><button data-tab="quality">精度</button></div><div id="inspectorBody"></div>';
 const desk=document.createElement('div');desk.id='desk';const view=document.createElement('div');view.id='viewColumn';$('stage').before(desk);desk.append(view,inspector);view.append($('stage'),$('closed'));const hint=document.querySelector('.hint');if(hint)view.append(hint);
 $('rigPanel').querySelector('summary').textContent='共同工作室 · 原 IQ 主光＋次光';$('rigPanel').querySelector('p.muted').textContent='01、02默认使用同一组暖主光与冷次光、灰色工作室背景。灯光变化不会改变石头或斑纹种子。';
 const qualityPanel=document.createElement('section');qualityPanel.className='panel';qualityPanel.id='qualityPanel';qualityPanel.innerHTML='<h3>高清观察</h3><label class="qualityRow">渲染像素<select id="renderQuality"><option value="auto">匹配显示像素 · 自动</option><option value="1920">1920 × 1080</option><option value="2560">2560 × 1440</option><option value="3840">3840 × 2160 · 高耗时</option><option value="960">960 × 540 · 原版对照</option></select></label><label class="qualityRow">边缘 / 颗粒采样<select id="sampleQuality"><option value="1">原生清晰</option><option value="2">精修 · 每像素4次射线</option></select></label><p id="qualityInfo" class="muted"></p><p id="microExplanation" class="muted">微起伏在“形状”页独立调节；不是锐化贴图。放大后重新求交、重新着色。</p><button id="exactR09">R09原始采样对照</button><button id="hdReturn">返回高清工作室</button><p class="muted">4K与4次采样会明显增加GPU工作量；不降低或随机替换模型。</p>';
 $('inspectorBody').append(colorPanel,$('shapePanel'),$('layersPanel'),$('rigPanel'),qualityPanel);
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showInspector(b.dataset.tab));
 $('renderQuality').onchange=e=>{quality.mode=e.target.value;manualResolution=0;quality.hd=true;dirty=true;draw();};$('sampleQuality').onchange=e=>{quality.samples=+e.target.value;dirty=true;draw();};
 $('exactR09').onclick=()=>{quality.hd=false;quality.mode='960';quality.samples=1;rig=clone(rigDefault);states.iq.micro=0;manualResolution=960;updateControls();draw();};
 $('hdReturn').onclick=()=>{quality.hd=true;quality.mode='auto';manualResolution=0;rig=clone(studioDefault);states.iq.micro=.35;updateControls();draw();};
 const bar=document.createElement('div');bar.className='qualityBar';bar.innerHTML='<span id="surfaceModeNote"></span><b id="resolutionInfo"></b><button id="returnMaterial" hidden>返回完整材质</button>';view.prepend(bar);$('returnMaterial').onclick=()=>{states[active].view=0;updateControls();};
 window.addEventListener('resize',()=>{if(!manualResolution)dirty=true;});
 // Maintain obvious access to a large same-camera ten-color contact sheet.
 const oldGallery=gallery;$('galleryButton').onclick=async()=>{await oldGallery();$('gallery').classList.add('fullGallery');};
 $('rigReset').textContent='恢复统一双灯';$('rigReset').onclick=()=>{rig=clone(studioDefault);updateControls();};
}

function tick(t){if(ready&&!overview){if(running&&!inspect[active].result.hidden){const dt=Math.min((t-last)/1000,.08);if(active==='wet')states.wet.yaw+=dt*.16;else states.iq.time+=dt*8;dirty=true;}if(dirty)draw();}last=t;requestAnimationFrame(tick);}
try{
 document.querySelectorAll('button').forEach(b=>b.disabled=true);
 await Promise.all(files.map(async n=>{sources[n]=await read(n);}));
 sourceFingerprint=await digest(files.map(n=>sources[n]).join('\n'));
 renderers.ref=makeRenderer($('referenceCanvas'));renderers.result=makeRenderer($('resultCanvas'));ready=true;
 installInspector();restoreSession();const requested=new URLSearchParams(location.search).get('case')||'iq';select(requested==='smooth'?'iq':requested,false);
 preview('wet',$('thumb-wet'));preview('iq',$('thumb-iq'));if(!overview)draw();
 document.querySelectorAll('button').forEach(b=>b.disabled=false);$('status').textContent='R10 · 原形体继承 / 高清射线重算 / 独立材质层 / 共用双灯';
 window.KAOPU10=window.KAOPU9={ready:true,sources,frozen:clone(frozen),getState:()=>clone(states),getRig:()=>clone(rig),getInspect:()=>clone(inspect),getScore:score,setScore:importScore,select,reset,draw,action,chooseLook,frames:()=>frames,setValues:(o)=>{Object.assign(states[active],o);build();layout();draw();},setLayer:(i,o)=>{Object.assign(states.iq.layers[i],o);build();draw();},setRig:(o)=>{Object.assign(rig,o);updateControls();draw();},setResolution:w=>{manualResolution=w;for(const r of Object.values(renderers)){r.canvas.width=w;r.canvas.height=w*9/16;}dirty=true;draw();},setQuality:o=>{Object.assign(quality,o);manualResolution=0;dirty=true;draw();},quality:()=>clone(quality),showInspector,legacy:()=>{quality.hd=false;quality.samples=1;rig=clone(rigDefault);states.iq.micro=0;manualResolution=960;build();draw();},pixels:side=>Array.from(renderers[side||'result'].pixels()),glErrors:()=>Object.values(renderers).map(r=>r.gl.getError()),programCount:files.length,stop:()=>{running=false;}};
 requestAnimationFrame(tick);
}catch(e){fail(e);$('status').textContent='工作台未完成启动';}
})();
