'use strict';const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const root=path.resolve(process.env.HAIYU_HTML||'kaopu-haiyu-workbench/index.html'),out=path.resolve(process.env.HAIYU_STRUCTURE_OUT||'haiyu-structure-results');fs.mkdirSync(out,{recursive:true});const hash=s=>crypto.createHash('sha256').update(s).digest('hex');const report={commit:process.env.GITHUB_SHA,htmlSHA256:hash(fs.readFileSync(root)),browser:'Official Chromium',physicalDevice:false,checks:[],errors:[]};const save=()=>{report.crossRuntimeGeometry={maximumAbsoluteError:maxNumericError,tolerance:1e-12,topologyAndCountsStrict:true};fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(report,null,2))};
let maxNumericError=0;
function samePacket(actual,expected){if(typeof expected==='number'){assert.equal(typeof actual,'number');assert.ok(Number.isFinite(actual));const error=Math.abs(actual-expected);maxNumericError=Math.max(maxNumericError,error);assert.ok(error<=1e-12,'Cross-runtime coordinate error '+error);return;}if(expected===null||typeof expected!=='object'){assert.equal(actual,expected);return;}assert.deepEqual(Object.keys(actual).sort(),Object.keys(expected).sort());for(const key of Object.keys(expected))samePacket(actual[key],expected[key]);}
const geom=p=>JSON.stringify([p.axis,p.ribs.map(r=>r.points)]),packet=async f=>f.evaluate(()=>window.HaiyuSparseCandidate.getPacket()),state=async f=>f.evaluate(()=>window.HaiyuSparseCandidate.getState()),pixels=async(f,id='scene')=>hash(await f.locator('#'+id).evaluate(c=>c.toDataURL()));
async function child(p){return (await p.$('#sparseFrame')).contentFrame()}
async function ready(p){await p.waitForFunction(()=>document.body.dataset.stage==='19');const f=await child(p);await f.waitForFunction(()=>document.body.dataset.ready==='true');return f}
(async()=>{let browser,p;try{const G=await import(pathToFileURL(path.join(path.dirname(root),'studies/axis-ribs-wrap-r02/geometry.mjs')).href);browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));const base=process.env.HAIYU_STRUCTURE_URL||'file://'+root;await p.goto(base+'?module=axis-ribs-r01',{waitUntil:'load'});let f=await ready(p);assert.equal(await p.locator('[data-module="axis-ribs-r01"]').count(),1);assert.equal(await p.locator('#pointfieldCatalogue').isVisible(),false);
 let current=await packet(f),expected=JSON.parse(JSON.stringify(G.evaluate(current.parameters)));samePacket(current,expected);assert.equal(current.stations.length,12);assert.equal(current.vertexCount,729);assert.equal(G.inspect(current).rootError,0);const initialGeometry=hash(geom(current)),initialImage=await pixels(f);
 const evidence=await f.evaluate(()=>window.HaiyuSparseCandidate.getRenderEvidence());assert.equal(new Set(Object.values(evidence).map(x=>x.worldFingerprint)).size,1);assert.equal(new Set(Object.values(evidence).map(x=>x.geometryRevision)).size,1);assert.deepEqual(Object.keys(evidence).sort(),['front','scene','side','top']);
 const viewHashes=[];for(const id of['front','top','side']){viewHashes.push(await pixels(f,id));await f.locator('#'+id).screenshot({path:path.join(out,`c01-${id}.png`)})}assert.equal(new Set(viewHashes).size,3);await f.locator('main').screenshot({path:path.join(out,'c01-default-and-three-views.png')});report.checks.push({defaultGeometryMatchesIndependentModule:true,worldGeometryHash:initialGeometry,threeViewsSameWorld:evidence,distinctViewPixels:true});save();
 await f.locator('#scene').scrollIntoViewIfNeeded();const box=await f.locator('#scene').boundingBox();await p.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.5+125,box.y+box.height*.5+70,{steps:12});await p.mouse.up();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);assert.notEqual(await pixels(f),initialImage);assert.equal(hash(geom(await packet(f))),initialGeometry);assert.notEqual((await state(f)).yaw,.45);await f.locator('#scene').screenshot({path:path.join(out,'c01-manual-rotation.png')});
 await f.locator('[data-view="front"]').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);const preZoom=await pixels(f);await f.locator('#scene').hover();await p.mouse.wheel(0,-300);await p.waitForTimeout(100);assert.notEqual(await pixels(f),preZoom);assert.equal(hash(geom(await packet(f))),initialGeometry);await f.locator('#resetView').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);assert.equal((await state(f)).view,'orbit');assert.equal(await pixels(f),initialImage);for(const id of['axisOnly','neutral']){await f.locator('#'+id).click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);assert.notEqual(await pixels(f),initialImage);assert.equal(hash(geom(await packet(f))),initialGeometry);await f.locator('#'+id).click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);assert.equal(await pixels(f),initialImage);}report.checks.push({manualRotationChangesViewOnly:true,orthographicZoomWorks:true,resetCameraExact:true,layerAndColorDoNotAlterGeometry:true});save();
 for(const [id,values]of[['wrapAngle',['2.10','2.75','2.40']],['widthScale',['.85','1','.94']]])for(const value of values){await f.locator('#'+id).selectOption(value);await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);const p=await packet(f);samePacket(p,JSON.parse(JSON.stringify(G.evaluate(p.parameters))));assert.equal(G.inspect(p).rootError,0)}
 for(const n of[2,6,24,12]){await f.locator('#ribCount').selectOption(String(n));await f.waitForFunction(n=>window.HaiyuSparseCandidate.getPacket().stations.length===n&&window.HaiyuSparseCandidate.getState().pendingRAF===0,n);const p=await packet(f);samePacket(p,JSON.parse(JSON.stringify(G.evaluate(p.parameters))));assert.equal(p.ribs.length,n*2);assert.equal(G.inspect(p).rootError,0)}
 for(const a of[0,.4,1,2]){await f.locator('#amplitude').selectOption(String(a));await f.locator('#time').fill('1.25');await f.waitForFunction(a=>window.HaiyuSparseCandidate.getPacket().parameters.amplitude===a&&window.HaiyuSparseCandidate.getPacket().parameters.time===1.25&&window.HaiyuSparseCandidate.getState().pendingRAF===0,a);const p=await packet(f);samePacket(p,JSON.parse(JSON.stringify(G.evaluate(p.parameters))));assert.equal(G.inspect(p).rootError,0);assert.ok(G.inspect(p).allFinite)}
 await f.locator('#frames').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);await f.locator('main').screenshot({path:path.join(out,'c01-adjusted-parameters-frames.png')});const before=hash(geom(await packet(f)));await f.locator('#play').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().time>1.45);await f.locator('#play').click();await f.waitForFunction(()=>!window.HaiyuSparseCandidate.getState().playing&&window.HaiyuSparseCandidate.getState().pendingRAF===0);const stopped=await state(f),stoppedGeometry=hash(geom(await packet(f))),stoppedImage=await pixels(f);assert.notEqual(stoppedGeometry,before);await p.waitForTimeout(500);assert.equal((await state(f)).time,stopped.time);assert.equal(hash(geom(await packet(f))),stoppedGeometry);assert.equal(await pixels(f),stoppedImage);assert.equal(G.inspect(await packet(f)).rootError,0);report.checks.push({parameterCases:{ribPairs:[2,6,24,12],motion:[0,.4,1,2]},allMatchIndependentGeometry:true,rootsRemainAttached:true,propagationChangesWorldGeometry:true,pauseFreezesTimeGeometryAndPixels:true});save();
 await f.locator('#reset').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getPacket().parameters.time===0);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>scrollTo(0,0));await f.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await f.evaluate(()=>scrollY),0);const sceneBox=await f.locator('#scene').boundingBox();assert.ok(sceneBox.y<340,'C01 mobile canvas should appear below compact controls');assert.equal(await p.locator('.dimension-navigation').isVisible(),false);await p.screenshot({path:path.join(out,'c01-mobile-main-viewport.png')});await p.locator('#sparseNavigation').click();assert.equal(await p.locator('.dimension-navigation').isVisible(),true);await p.locator('#sparseNavigation').click();assert.equal(await p.locator('.dimension-navigation').isVisible(),false);report.checks.push({mobileMainCanvasTop:sceneBox.y,rootAndFrameScrollY:0,candidateNavigationToggleWorks:true});await f.locator('main').screenshot({path:path.join(out,'c01-mobile.png')});await p.locator('#sparseReturn').click();await p.waitForFunction(()=>document.body.dataset.stage==='5'&&document.body.dataset.pending==='0');assert.equal(await p.locator('.dimension-navigation').isVisible(),true);await p.locator('button[data-stage="19"]').click();f=await ready(p);assert.equal(await p.locator('.dimension-navigation').isVisible(),false);report.checks.push({mobileReturnRestoresOldNavigation:true,mobileReentryCompactsOnlyC01:true});await p.setViewportSize({width:1440,height:1000});
 // Preserve the already published 08/09 anchors and restore the exact previous case.
 await p.locator('#sparseReturn').click();await p.waitForFunction(()=>document.body.dataset.stage==='5'&&document.body.dataset.pending==='0');assert.equal(await p.locator('.dimension-navigation').isVisible(),true);
 for(const [stage,n]of[[17,'08'],[18,'09']]){await p.locator(`button[data-stage="${stage}"]`).click();await p.waitForFunction(s=>document.body.dataset.stage===String(s)&&document.body.dataset.pending==='0',stage);await p.locator('#timeline').fill('80');await p.waitForFunction(()=>document.body.dataset.frame==='80'&&document.body.dataset.pending==='0');const original=hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL()));await p.locator('button[data-stage="19"]').click();f=await ready(p);await f.locator('#play').click();await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().time>.1);await p.locator('#sparseReturn').click();await p.waitForFunction(s=>document.body.dataset.stage===String(s)&&document.body.dataset.frame==='80'&&document.body.dataset.pending==='0',stage);assert.equal(hash(await p.frameLocator('#live').locator('canvas').evaluate(c=>c.toDataURL())),original);assert.equal(await p.locator('#sparseFrame').getAttribute('srcdoc'),null);report.checks.push({preservedSource:n,frame:80,returnPixelExact:true,candidateDestroyedOnExit:true})}
 await p.locator('button[data-stage="19"]').click();f=await ready(p);await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);
 const imageBytes=await f.locator('#scene').evaluate(c=>c.toDataURL().split(',')[1]);const imageDownload=p.waitForEvent('download');await p.locator('#saveFrame').click();const savedImage=await imageDownload,imagePath=path.join(out,'c01-export.png');await savedImage.saveAs(imagePath);assert.equal(hash(fs.readFileSync(imagePath)),hash(Buffer.from(imageBytes,'base64')));
 const htmlDownload=p.waitForEvent('download');await p.locator('#saveHtml').click();const savedHTML=await htmlDownload,htmlPath=path.join(out,'temporary-saved-workbench.html');await savedHTML.saveAs(htmlPath);const reopened=await ctx.newPage();await reopened.goto('file://'+htmlPath+'?module=axis-ribs-r01',{waitUntil:'load'});const rf=await ready(reopened);assert.equal((await packet(rf)).stations.length,12);await reopened.close();fs.unlinkSync(htmlPath);await p.locator('#sparseReturn').click();await p.waitForFunction(()=>document.body.dataset.pending==='0');report.checks.push({currentViewPNGExportExact:true,downloadedFullWorkbenchReopensCandidate:true});
 const frameCount=await p.locator('iframe').count();for(let i=0;i<5;i++){await p.locator('button[data-stage="19"]').click();f=await ready(p);assert.equal((await state(f)).playing,false);await f.waitForFunction(()=>window.HaiyuSparseCandidate.getState().pendingRAF===0);assert.equal(await p.locator('iframe').count(),frameCount);await p.locator('#sparseReturn').click();await p.waitForFunction(()=>document.body.dataset.pending==='0');assert.equal(await p.locator('#sparseFrame').getAttribute('srcdoc'),null)}report.checks.push({reentryCycles:5,iframeCountStable:frameCount,startsPaused:true,noCandidateRAFWhenPaused:true});assert.deepEqual(report.errors,[]);report.ok=true;report.crossRuntimeGeometry={maximumAbsoluteError:maxNumericError,tolerance:1e-12,topologyAndCountsStrict:true};save();console.log(JSON.stringify(report,null,2));
}catch(e){report.ok=false;report.error=e.stack;save();if(p)await p.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1}finally{if(browser)await browser.close()}})();
